### PR TITLE
Fix pip3 install

### LINKED ISSUE #5813: Contributor setup script fails installing PIP packages
### The problem

A recent change to the setup script `./scripts/setup` that configures a new developer environment for contributing to ESPHome causes the setup script to crash. This crash is caused by a misunderstanding of the PIP command line arguments and parameter ordering that causes PIP to fail. 

https://github.com/esphome/esphome/blame/df838b5788e8d9b42718225d89c8f5f3854fa076/script/setup#L23

Current:
```shell
pip3 install -e --config-settings editable_mode=compat ".[dev,test,displays]"
```

Desired:
```shell
pip3 install -e ".[dev,test,displays]" --config-settings editable_mode=compat
```

### Which version of ESPHome has the issue?

dev branch

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

N/A

### Component causing the issue

scripts/setup

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

```txt
When executing as is, the setup script returns the following error:

ERROR: Invalid requirement: 'editable_mode=compat'
Hint: = is not a valid operator. Did you mean == ?
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by syssi**
# What does this implement/fix?

Fixes https://github.com/esphome/issues/issues/5813

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [5813](https://github.com/esphome/issues/issues/5813)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** Not needed.

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Thanks for the fix

**Comment by docteurzoidberg** [comment]
thanks for the fix, but seems to still a have a problem for me:
direct11

**Comment by syssi** [comment]
@docteurzoidberg Which `pip` version do you use? It looks like the `--config-settings` parameter is available since version 20.

**Comment by docteurzoidberg** [comment]
> @docteurzoidberg Which `pip` version do you use? It looks like the `--config-settings` parameter is available since version 20.

using the devcontainer !

**Comment by Links2004** [comment]
running in to a problem with this PR, can not longer setup the dev env. 
both local and in the devcontainer.

local:
```
Using cached wheel-0.43.0-py3-none-any.whl (65 kB)
Installing collected packages: wheel
Successfully installed wheel-0.43.0
ERROR: Invalid requirement: 'editable_mode=compat'
Hint: = is not a valid operator. Did you mean == ?

$ python3 --version
Python 3.12.3

$ pip3 --version
pip 24.0 from /home/links/code/esphome/esphome/venv/lib/python3.12/site-packages/pip (python 3.12)
```

vscode dev container:
```
Successfully installed esphome-dashboard-20240429.1 platformio-6.1.15 pytest-8.2.0
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (66.1.1)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (0.38.4)
ERROR: Invalid requirement: 'editable_mode=compat'
Hint: = is not a valid operator. Did you mean == ?

# python3 --version
Python 3.11.2

# pip3 --version
pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)
``` 

after tring to fix the argument order I run in to a new error:

```
 $ pip3 install --config-settings editable_mode=compat -e ".[dev,test,displays]"
Obtaining file:///home/links/code/esphome/esphome
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
ERROR: Project file:///home/links/code/esphome/esphome has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

**Comment by syssi** [comment]
Oh no! I didn't expected there are pip versions out requiring a different order of the arguments. :-(

**Comment by syssi** [comment]
@Links2004 I'm unable to reproduce your issue using python 3.11.2, pip 23.0.1 (Debian Bookworm):

```
$ git clone git@github.com:esphome/esphome.git
$ cd esphome
$ script/setup
....
Tool Manager: framework-arduinopico@1.30702.0 is already installed
Library Manager: noise-c@0.1.4 is already installed
Library Manager: libsodium@1.10018.1 is already installed
Library Manager: NeoPixelBus@2.7.3 is already installed


Virtual environment created. Run 'source venv/bin/activate' to use it.
$
$ python3 --version
Python 3.11.2
$ pip3 --version
pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)
$
```

**Comment by docteurzoidberg** [comment]
> pip3 --version

weird i got not the same version of pip in the devcontainer... still on 20

**Comment by Links2004** [comment]
@syssi does the devcontainer in vscode work for you?
my local Python and pip are newer then whats on Bookworm.
but I at least expect the the devcontainer to work, but it does not for me.

**Comment by syssi** [comment]
@docteurzoidberg I'm not very familiar with the ESPHome container. Could you tell me the container name + registry I need to pull to retrieve the devcontainer?

I've tried to reproduce the issue locally using Debian Bookworm (python 3.11) and Debian Bookworm + backported python 3.12 (used to run Home Assistant). Both versions are working fine using the HEAD of the `dev` branch of ESPHome.

```
$ git clone git@github.com:esphome/esphome.git
$ cd esphome
$ script/setup
[...]
Virtual environment created. Run 'source venv/bin/activate' to use it.
$
$ source venv/bin/activate
(venv) $
(venv) $ python3 --version
Python 3.12.3
(venv) $ pip3 --version
pip 24.0 from /tmp/esphome/venv/lib/python3.12/site-packages/pip (python 3.12)
(venv) $
```

**Comment by syssi** [comment]
@Links2004 I didn't tried/used the devcontainer + vscode yet. Are you sure the container includes the fix of this PR? Is the container perhaps outdated and is still suffering on what I tried to fix here? :-) Do you like to have a brief chat on discord?

**Comment by Links2004** [comment]
ghcr.io/esphome/esphome-lint:dev (.devcontainer/devcontainer.json)
it is started via vscode itself so not sure about the args / env used.

**Comment by docteurzoidberg** [comment]
nevermind. i deleted container. image and volume and now it's working back !

**Comment by syssi** [comment]
Soothing! :-) I'm unable to reproduce the issue using the devcontainer too:

```
# It's a bit hacky but it's doing the job/proof

$ docker run --rm -it --entrypoint bash ghcr.io/esphome/esphome-lint:dev
$ cd /tmp
$ git clone https://github.com/esphome/esphome.git
$ cd esphome
$ script/setup

Virtual environment created. Run 'source venv/bin/activate' to use it.
$
$ python3 --version
Python 3.11.2
$ pip3 --version
pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)
$
```

**Comment by Links2004** [comment]
got the dev container working again had to delete the docker image locally looks like vscode did not update it.

but currently no idea how to fix my local (non container) error:
```
ERROR: Project file:///home/links/code/esphome/esphome has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.
```

I am in the esphome discord if this makes it easyer ;)

**Comment by Links2004** [comment]
found a workaround:
https://stackoverflow.com/questions/69711606/how-to-install-a-package-using-pip-in-editable-mode-with-pyproject-toml

a empty setup.cfg does the trick, sound strange but works (touch setup.cfg)

**Comment by syssi** [comment]
TL&DR: This PR did resolve the issue (`ERROR: Invalid requirement: 'editable_mode=compat'`) and doesn't make it worse. ;-)

**Pull request merged**
