### PR TITLE
Add hyphen to supported name characters

### LINKED ISSUE #418: Allow hyphens in node name
**Describe the problem you have/What new integration you would like**
Allow hyphens in node name.

**Please describe your use case for this integration and alternatives you've tried:**
Node names currently allow underscore, which is in the set of valid mDNS service identifier and DHCP client id characters, but not in the set of (strictly) valid DNS hostname characters.  Some people have DHCP servers which create dynamic DNS names, and DNS servers which are configured to strictly verify valid hostnames.

Rather than altering network topology to accommodate mDNS, I would like to simply use DNS name resolution to reach ESP nodes.  Cosmetically, I'd like to use a separator in the node hostnames.  Hyphen is the only functional character for this.

**Additional context**
There are, realistically, other options for resolving this issue:
 * I could use a subdomain specific to the ESP devices rather than a naming convention.  That's moderately inconvenient, as it means an additional configuration step rather than just letting the DHCP server hand out an address wherever on the network the device attaches
 * I could alter the DNS server to accept underscores.  The drawback to this is that future devices could create hostnames with underscores, and underscores are not valid in real hostnames, dang it. :D 
 * I could just mash the hostnames together instead of using hyphens.  But that decreases legibility, and reduced legibility increases the possibility of mistakes later on.
 * I could rearrange my network so multicast DNS worked reliably.  That's kind of a hassle, though. :)

After a quick glance, it looks like this is just a matter of adding a hyphen to the string at https://github.com/esphome/esphome/blob/7ad593d674e488e3abbfb3208326e3cbcd404d24/esphome/config_validation.py#L46 - I'll wait to open a PR in a few hours, because Hacktoberfest. 👕

### PR DESCRIPTION
**Pull request by ianleeder**
## Description:
This is a duplicate of esphome/esphome#740 since that PR went stale last year (and wasn't rejected outright).

I'm a PR-virgin, so go easy on me.  I'm trying.  I've made the changes that I can see that are required, and tested.  This has already been discussed between @dannysauer and @OttoWinter.  The key points I can see are:
 - Apparently hyphen _used to be_ invalid due to HA MQTT discovery (as per https://github.com/esphome/esphome/pull/740#issuecomment-543312315).  They support hyphens now (I found the specific commit where this changed [back in 2017](https://github.com/home-assistant/core/commit/be53cc70682ca55ec983630d283d3afbe2736a02#diff-7c6eaa44a1a537b1fbd15e6c05b14522).
 - @OttoWinter states the the dashboard matching logic needs updating.  The allowable characters are defined in [esphome/config_validation.py](https://github.com/ianleeder/esphome/blob/ba1a862a76ebafb095d6c28aa1db8a91b0032b4d/esphome/config_validation.py#L43) included in this PR.

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/418

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#719

## Checklist:
  - [x] The code change is tested and works locally.

  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — COMMENTED** [review]
Thanks! Yes I think hyphens should work now, as you said the mqtt name allowlist in HA was changed.

There may be places in the codebase that don't expect hyphens, but if there are we can fix them later. If it works well on your test setup it's fine.

These lines needs to be updated too:

https://github.com/esphome/esphome/blob/8414a223564e58bbbd4c4e43b8acd95c392b8486/esphome/dashboard/templates/index.html#L362

https://github.com/esphome/esphome/blob/8414a223564e58bbbd4c4e43b8acd95c392b8486/esphome/wizard.py#L172

~~And the docs need to be updated here:~~ Edit: I see the linked docs pr now.

https://github.com/esphome/esphome-docs/blob/current/components/esphome.rst#L25

**Comment by OttoWinter** [comment]
Ah yes and please also update this testcase (add `-` after `_`):

https://github.com/esphome/esphome/blob/8414a223564e58bbbd4c4e43b8acd95c392b8486/tests/unit_tests/test_config_validation.py#L30

**Comment by ianleeder** [comment]
Ok, done as requested.  I couldn't find a way to fire off the unit tests, so I made the edit blindly.

**Comment by glmnet** [comment]
Are you doing something else before setting it ready? (I mean not draft)

**Comment by ianleeder** [comment]
Sorry, that's just me being noob.  I actually never expected it to be publicly visible when I created a draft.  And then I was waiting for the checks to pass.  Done now.

**Comment by dannysauer** [comment]
BTW, thanks for picking this up @ianleeder; my "I'll look this weekend" turned into, well, a whole lot longer. :D

**Comment by OttoWinter** [comment]
:tada: Thanks for your first contribution!

**Comment by ianleeder** [comment]
While I've got your ear @OttoWinter is there a good reason why the `ALLOWED_NAME_CHARS` is defined in two places?
https://github.com/esphome/esphome/blob/aea2e9a6bb08936cb40463718c96381377d4182c/esphome/const.py#L13
https://github.com/esphome/esphome/blob/aea2e9a6bb08936cb40463718c96381377d4182c/esphome/config_validation.py#L43
Can I make another PR to update `config_validation.py` to remove it and import the version in `const.py`?

**Comment by OttoWinter** [comment]
@ianleeder Yeah these parts of the codebase are very old (probably mostly the same since initial commit even), probably the duplicate was a result of some refactor work.

Updating to move it to `const.py` is ok with me :+1: thanks!

**Pull request merged**
