### PR TITLE
Wake on lan

### PR DESCRIPTION
**Pull request by willwill2will54**
# What does this implement/fix? 

Creates a wake_on_lan button platform that allows the sending of a WOL Magic packet over UDP broadcast to port 9.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** [implements feature request 126 (kinda)](https://github.com/esphome/feature-requests/issues/126)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1775

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: wol-esp

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "e933df78ec0367a9403d0a95e99bf5c2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wol-Esp Fallback Hotspot"
    password: "4yIZT0HlHsVR"

captive_portal:

button:
  - platform: wake_on_lan
    target_mac_address: E9:48:B8:CA:58:A1
    name: SomeServer
    id: some_server

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO27
      mode:
        pulldown: true
        input: true
    name: "Pin 27"
    on_press:
      - button.press:
          id: some_server
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by willwill2will54** [comment]
I need someone else to test if it works on esp8266, as I don't (and won't) have access to one at this time.

**Comment by oxan** [comment]
I would prefer it if this was built upon the `socket` abstraction, instead of using the Arduino networking libraries, since we're trying to move away from those Arduino libraries.

**Comment by willwill2will54** [comment]
> I would prefer it if this was built upon the `socket` abstraction, instead of using the Arduino networking libraries, since we're trying to move away from those Arduino libraries.

Sure! I'll work on that. Any objections to the interface, documentation, etc that I should also resolve?

**Comment by oxan** [comment]
Nothing major :)

**Comment by willwill2will54** [comment]
@oxan I could use a little guidance on sending a broadcast without sendto() or connect()

**Comment by oxan** [comment]
Hmm, crap, I didn't realize we didn't have that implemented yet, and now that I'm looking into it, the socket implementation on ESP8266 is TCP-only, so adding `sendto()`/`connect()` there will be quite involved :/

**Comment by willwill2will54** [comment]
Should I revert to the Arduino based version?

**Comment by willwill2will54** [comment]
I am going to close this PR and start a new one with the legacy Arduino code dependency. I will preserve the sockets component dependent version so that it may supersede the Arduino code at such time as the sockets component supports the necessary APIs.

**Pull request closed without merging**
