### PR TITLE
waveshare_epaper: Add 2.90in-dke

### PR DESCRIPTION
**Pull request by polyfloyd**
# What does this implement/fix?

This MR adds support for the 2.90in-dke variant epaper display to the waveshare_epaper module. This display variant was used in the SHA2017 and HackerHotel2018 event badges.

The code proposed here was initially written by @Nizzle ~~with a minor patch by @rikroe to fix a compilation issue~~. I am interested in building upon his work to have this working upstream in esphome.

The code has been verified working on the respective badges. Please let me know whether additional effort is needed.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3780

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
spi:
  clk_pin: 18
  mosi_pin: 5

display:
  - platform: waveshare_epaper
    model: 2.90in-dke
    cs_pin: 19
    dc_pin: 21
    busy_pin: 22
    reset_pin: 23
    full_update_every: 1  # Partial not working yet so full updates only.
    update_interval: 20s
    lambda: |-
      it.printf(0, 34, id(font_small), "${name}");
      it.printf(0, 0, id(font_big), "%.0f ppm", id(co2).state);
      it.graph(4, 64, id(co2_graph));
      it.printf(160, 10, id(font_small), "%.1f °C", id(temperature).state);
      it.printf(160, 34, id(font_small), "%.0f %%", id(humidity).state);
      it.printf(220, 34, id(font_small), "%.0f hPa", id(pressure).state);
    rotation: 270
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by polyfloyd** [comment]
Converted to draft, I'm going to have a crack at partial updates this week

**Comment by polyfloyd** [comment]
Alright, I decided that partial updates is not really worth my effort. There also seem to be other display drivers that do not perform partial updates.

I did managed to fix a bug in the data entry though.

@clydebarrow Could you please review?

**Comment by clydebarrow** [comment]
Needs a docs update too. Otherwise looks ok. I'll approve when the docs are done.

**Comment by polyfloyd** [comment]
Got a doc update right here: https://github.com/esphome/esphome-docs/pull/3780

**Comment by clydebarrow** [comment]
> Got a doc update right here: [esphome/esphome-docs#3780](https://github.com/esphome/esphome-docs/pull/3780)

After creating a doc PR you should update the initial comment in the code PR to point to it. Otherwise nobody knows it's there.

**Review by clydebarrow — APPROVED** [review]

**Review by clydebarrow — APPROVED** [review]

**Comment by polyfloyd** [comment]
I thought I updated the initial comment, but apparently I dreamed that :grimacing: 

Thanks!

**Comment by rikroe** [comment]
Thanks @polyfloyd! 🎉

**Pull request merged**
