### PR TITLE
[font] Make display an auto-load, not a dependency

### PR DESCRIPTION
**Pull request by clydebarrow**
# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
I'm not sure I see the point in having a font with nothing to display it on...

**Comment by clydebarrow** [comment]
> I'm not sure I see the point in having a font with nothing to display it on..

Maybe not, but somebody else might. It's currently restricted for no technical reason. Who knows, someone might want to drive some other bit of hardware that can draw stuff, just not on a display.

**Comment by jesserockz** [comment]
In that case would it not be better to define `USE_DISPLAY` and preprocess the display code out of the font code if it is not included?

**Comment by clydebarrow** [comment]
Is that what you meant? And I suspect the other PR #7367 will need to be merged before this one will pass CI.

**Comment by jesserockz** [comment]
Not exactly, I have pushed a commit with what I was thinking

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
