### PR TITLE
add water delivered to dsmr component

### PR DESCRIPTION
**Pull request by jerome992**
# What does this implement/fix?

add water delivered to dsmr component

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2464

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
dsmr:
  uart_id: p1_uart
  water_mbus_id: 2
  
sensor:
  - platform: dsmr
    water_delivered:
      name: Water delivered
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by zuidwijk** [comment]
I'm no esphome code developer. Yet if this data is in the telegrams of the meter (P1 port), could you give an example telegram in which you can see the obis code and the format used?

**Comment by jerome992** [comment]
It is not very easy to export the decrypted telegram from esphome. The very verbose logging only logs the beginning of the telegram.

Here is the P1 specification  of Luxembourg: 
https://www.luxmetering.lu/pdf/SPEC%20-%20E-Meter_P1_specification_20210308.pdf

Gas and water have the same OBIS in Luxembourg, but they are on different channels.

**Comment by massamino** [comment]
Hi,

I would love to see it merged.
The dsmr parser for home assistant has the water part integrated.
I can provide logging when I receive my meters.

dutch/belgian version: https://www.netbeheernederland.nl/_upload/Files/Slimme_meter_15_a727fce1f1.pdf
example for data: https://www.cdem.be/13_technical/#water-data

Thanks in advance

**Comment by AndreasStefanDahl** [comment]
I would very much like to see this functionality supported as well.

**Comment by meeusen** [comment]
Belgian digital electricity and water meter, no gas. With the changes from this PR, running on "slimmelezer" and setting the water_mbus_id to 1, I get the water meter values in the "Water Consumed" sensor. Below are the fields from a telegram of my meter (with the equipment ID changed). I also have to set the gas_mbus_id to 2, or anything but 1, I suppose, otherwise the water meter value ends up in the "Gas Consumed" sensor.

0-1:24.1.0(007) 
0-1:96.1.1(1234567123456712345671234567) 
0-1:24.2.1(230623000337S)(00042.176*m3)

**Comment by massamino** [comment]
That's what I'm seeing. I thought my gas usage was strange. It's probably the watermeter that is measured. 😁. Explains a lot.

**Comment by massamino** [comment]
@glmnet Can you please review the changes of @jerome992. As far as I can tell the code looks legit and would be very welcome.
Thank you.

**Review by glmnet — APPROVED** [review]

**Pull request merged**
