### PR TITLE
Modular light transformers

### LINKED ISSUE #1558: anything newer than 1.15.2 doesn't transition LEDs as HA requests
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

arch | x86_64
-- | --
dev | false
docker | false
hassio | false
installation_type | Home Assistant Core
os_name | Linux
os_version | 4.15.0-118-generic
python_version | 3.8.0
timezone | Europe/London
version | 0.116.2
virtualenv | true

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESPNodeMCU V2
**ESPHome version (latest production, beta, dev branch)**

1.15.2
**Affected component:**

transition on or off of WS2812 and SK6812 from HA service

**Description of problem:**
After upgrading from ESPHome 1.13.6 to 1.15.2 i have found that the transitions doesn't quite count right, so a transition of 60 seconds really just goes full brightness after 15 seconds, no fade/ramp up

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp7
  platform: ESP8266
  board: nodemcuv2

# Window lights

wifi:
  ssid: 'WIFI'
  password: 'WIFI'

mqtt:
  broker: '192.168.1.113'
  username: 'user'
  password: 'pass'

# Enable logging
logger:
  level: INFO

ota:
  password: 'pass'

switch:
  - platform: restart
    name: "ESP7 Restart"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal ESP7"
    update_interval: 120s
  - platform: adc
    pin: A0
    name: "ESP7 ldr"
    unit_of_measurement: lux
    update_interval: 30s
    filters:
      - lambda: >-
          return (x / 10000.0) * 2000000.0;


light:
  - platform: neopixelbus
    type: GRBW
    pin: GPIO3
    num_leds: 89
    name: "ESP7 LED"
    id: mylight
    color_correct: [100%, 100%, 100%, 50%]
    default_transition_length: 0.5s
#    variant: SK6812
#    method: BIT_BANG
#    gamma_correct: 2.8
    effects:
      - random:
          name: Random Effect Fast
          transition_length: 0.1s
          update_interval: 0.5s
      - addressable_rainbow:
          name: Rainbow Effect
          speed: 20
          width: 75
      - addressable_color_wipe:
          name: Color Wipe Effect
          colors:
            - random: true
              num_leds: 16
            - random: true
              num_leds: 16
          add_led_interval: 50ms
          reverse: False
      - addressable_color_wipe:
          name: Color Wipe Effect Fast
          colors:
            - random: true
              num_leds: 16
            - random: true
              num_leds: 10
            - random: true
              num_leds: 19
          add_led_interval: 10ms
          reverse: False
      - strobe:
          name: Strobe Effect With Custom Values
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 80%
              blue: 0%
              white: 0%
              duration: 500ms
            - state: True
              brightness: 1%
              red: 0%
              green: 0%
              blue: 0%
              white: 1%
              duration: 250ms
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              white: 0%
              duration: 500ms
            - state: True
              brightness: 1%
              red: 0%
              green: 0%
              blue: 0%
              white: 1%
              duration: 250ms
            - state: True
              brightness: 100%
              red: 80%
              green: 0%
              blue: 100%
              white: 0%
              duration: 500ms
      - addressable_scan:
          name: Scan Effect
          move_interval: 5ms
#          scan_width: 2
      - addressable_twinkle:
          name: Twinkle Effect
          twinkle_probability: 30%
          progress_interval: 4ms
      - addressable_random_twinkle:
          name: Random Twinkle Effect
          twinkle_probability: 35%
          progress_interval: 32ms
      - addressable_fireworks:
          name: Fireworks Effect
          update_interval: 32ms
          spark_probability: 25%
          use_random_color: false
          fade_out_rate: 70
      - addressable_flicker:
          name: Flicker Effect
          update_interval: 25ms
          intensity: 25%
      - strobe:
          name: Flash Red
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 0%
              blue: 0%
              white: 0%
              duration: 500ms
            - state: True
              brightness: 1%
              red: 1%
              green: 0%
              blue: 0%
              white: 0%
              duration: 500ms
      - strobe:
          name: Flash Green
          colors:
            - state: True
              brightness: 100%
              red: 0%
              green: 100%
              blue: 0%
              white: 0%
              duration: 500ms
            - state: True
              brightness: 1%
              red: 0%
              green: 1%
              blue: 0%
              white: 0%
              duration: 500ms
      - addressable_color_wipe:
          name: XMAS2
          colors:
            - red: 100%
              green: 0%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 0%
              green: 0%
              blue: 0%
              white: 1%
              num_leds: 4
            - red: 0%
              green: 100%
              blue: 0%
              white: 0%
              num_leds: 2
            - red: 0%
              green: 0%
              blue: 0%
              white: 1%
              num_leds: 4
          add_led_interval: 100ms
          reverse: False

```

**Logs (if applicable):**

```
[08:07:19][I][app:142]: Rebooting safely...
[08:07:32][I][mqtt:202]: MQTT Connected!
[08:07:32][I][app:059]: setup() finished successfully!
[08:07:32][D][sensor:092]: 'WiFi Signal ESP7': Sending state -61.00000 dB with 0 decimals of accuracy
[08:07:32][I][app:105]: ESPHome version 1.15.2 compiled on Oct 16 2020, 08:06:52
[08:07:32][C][wifi:443]: WiFi:
[08:07:32][C][wifi:303]:   SSID: 'WIFI'
[08:07:32][C][wifi:304]:   IP Address: 192.168.1.178
[08:07:32][C][wifi:306]:   BSSID: 80:2A:A8:5A:7F:19
[08:07:32][C][wifi:307]:   Hostname: 'esp7'
[08:07:32][C][wifi:311]:   Signal strength: -61 dB ▂▄▆█
[08:07:32][C][wifi:315]:   Channel: 1
[08:07:32][C][wifi:316]:   Subnet: 255.255.255.0
[08:07:32][C][wifi:317]:   Gateway: 192.168.1.1
[08:07:32][C][wifi:318]:   DNS1: 192.168.1.1
[08:07:32][C][wifi:319]:   DNS2: (IP unset)
[08:07:32][C][logger:185]: Logger:
[08:07:32][C][logger:186]:   Level: DEBUG
[08:07:32][C][logger:187]:   Log Baud Rate: 115200
[08:07:32][C][logger:188]:   Hardware UART: UART0
[08:07:32][C][light:177]: Light 'ESP7 LED'
[08:07:32][C][light:179]:   Default Transition Length: 0.5s
[08:07:32][C][light:180]:   Gamma Correct: 2.80
[08:07:32][C][restart:021]: Restart Switch 'ESP7 Restart'
[08:07:32][C][restart:021]:   Icon: 'mdi:restart'
[08:07:32][C][adc:026]: ADC Sensor 'ESP7 ldr'
[08:07:32][C][adc:026]:   Unit of Measurement: 'lux'
[08:07:32][C][adc:026]:   Accuracy Decimals: 2
[08:07:32][C][adc:026]:   Icon: 'mdi:flash'
[08:07:32][C][adc:031]:   Pin: 17
[08:07:32][C][adc:051]:   Update Interval: 30.0s
[08:07:32][C][ota:029]: Over-The-Air Updates:
[08:07:32][C][ota:030]:   Address: esp7.local:8266
[08:07:32][C][ota:032]:   Using Password.
[08:07:32][C][mqtt:051]: MQTT:
[08:07:32][C][mqtt:053]:   Server Address: 192.168.1.113:1883 (192.168.1.113)
[08:07:32][C][mqtt:054]:   Username: 'sensor'
[08:07:32][C][mqtt:055]:   Client ID: 'esp7-dc4f2218280c'
[08:07:32][C][mqtt:057]:   Discovery prefix: 'homeassistant'
[08:07:32][C][mqtt:058]:   Discovery retain: YES
[08:07:32][C][mqtt:060]:   Topic Prefix: 'esp7'
[08:07:32][C][mqtt:062]:   Log Topic: 'esp7/debug'
[08:07:32][C][mqtt:065]:   Availability: 'esp7/status'
[08:07:32][C][wifi_signal.sensor:009]: WiFi Signal 'WiFi Signal ESP7'
[08:07:32][C][wifi_signal.sensor:009]:   Unit of Measurement: 'dB'
[08:07:32][C][wifi_signal.sensor:009]:   Accuracy Decimals: 0
[08:07:32][C][wifi_signal.sensor:009]:   Icon: 'mdi:wifi'
[08:07:32][C][mqtt.switch:038]: MQTT Switch 'ESP7 Restart': 
[08:07:33][C][mqtt.switch:039]:   State Topic: 'esp7/switch/esp7_restart/state'
[08:07:33][C][mqtt.switch:039]:   Command Topic: 'esp7/switch/esp7_restart/command'
[08:07:33][C][mqtt.sensor:024]: MQTT Sensor 'WiFi Signal ESP7':
[08:07:33][C][mqtt.sensor:028]:   State Topic: 'esp7/sensor/wifi_signal_esp7/state'
[08:07:33][C][mqtt.sensor:024]: MQTT Sensor 'ESP7 ldr':
[08:07:33][C][mqtt.sensor:028]:   State Topic: 'esp7/sensor/esp7_ldr/state'
[08:07:33][C][mqtt.light:053]: MQTT Light 'ESP7 LED':
[08:07:33][C][mqtt.light:054]:   State Topic: 'esp7/light/esp7_led/state'
[08:07:33][C][mqtt.light:054]:   Command Topic: 'esp7/light/esp7_led/command'
[08:07:44][D][adc:056]: 'ESP7 ldr': Got voltage=0.43V
[08:07:44][D][sensor:092]: 'ESP7 ldr': Sending state 85.74219 lux with 2 decimals of accuracy
[08:08:14][D][adc:056]: 'ESP7 ldr': Got voltage=0.43V
[08:08:14][D][sensor:092]: 'ESP7 ldr': Sending state 85.93750 lux with 2 decimals of accuracy
[08:08:39][D][sensor:092]: 'WiFi Signal ESP7': Sending state -60.00000 dB with 0 decimals of accuracy
[08:08:44][D][adc:056]: 'ESP7 ldr': Got voltage=0.43V
[08:08:44][D][sensor:092]: 'ESP7 ldr': Sending state 86.13281 lux with 2 decimals of accuracy
[08:09:14][D][adc:056]: 'ESP7 ldr': Got voltage=0.43V
[08:09:14][D][sensor:092]: 'ESP7 ldr': Sending state 86.71875 lux with 2 decimals of accuracy
[08:09:23][I][ota:046]: Boot seems successful, resetting boot loop counter.
[08:09:43][D][adc:056]: 'ESP7 ldr': Got voltage=0.44V
[08:09:44][D][sensor:092]: 'ESP7 ldr': Sending state 87.10938 lux with 2 decimals of accuracy
[08:10:13][D][adc:056]: 'ESP7 ldr': Got voltage=0.43V
[08:10:14][D][sensor:092]: 'ESP7 ldr': Sending state 86.91406 lux with 2 decimals of accuracy
[08:10:39][D][sensor:092]: 'WiFi Signal ESP7': Sending state -60.00000 dB with 0 decimals of accuracy
[08:10:44][D][adc:056]: 'ESP7 ldr': Got voltage=0.44V
[08:10:44][D][sensor:092]: 'ESP7 ldr': Sending state 87.10938 lux with 2 decimals of accuracy
[08:10:44][D][light:264]: 'ESP7 LED' Setting:
[08:10:44][D][light:273]:   State: ON
[08:10:44][D][light:277]:   Brightness: 100%
[08:10:44][D][light:286]:   Red=100%, Green=100%, Blue=100%
[08:10:44][D][light:289]:   White Value: 100%
[08:10:44][D][light:303]:   Transition Length: 60.0s
[08:11:14][D][adc:056]: 'ESP7 ldr': Got voltage=0.40V
[08:11:14][D][sensor:092]: 'ESP7 ldr': Sending state 80.85938 lux with 2 decimals of accuracy


```

**Additional information and things you've tried:**

The following are me setting the trasition time in HA to diffrent things and then testing how long it takes
10 seconds transition goes full brightness after about 3 seconds (no fade/ramp, just straight to full after 3 seconds) 
15 second transition goes full brightness after about 4 seconds (no fade/ramp, just straight to full after 4 seconds)
30 seconds transition goes full brightness after about 7 seconds (no fade/ramp, just straight to full after 7 seconds) 
60 seconds transition goes full brightness after about 15 seconds (no fade/ramp, just straight to full after 15 seconds) 

esphome:dev same results
1.14.0 same results

### PR DESCRIPTION
**Pull request by oxan**
# What does this implement/fix? 

This removes the hardcoding of the transition transformer from `LightState`, and instead lets each `LightOutput` specify a transformer. This allows lights that need custom transitioning behaviour to replace the default transformer with their own. One example of this are addressable lights, and @mmakaay also has a light that needs custom transitions.

In the future I want to add different transitions and allow the user to select a transition to be used for each light (i.e. one I want personally is a cascade transition for addressable lights, where the lights are turned on one-by-one).

This also fixes a bug with addressable light transitions: currently the state of the transition gets [reset](https://github.com/esphome/esphome/blob/dev/esphome/components/light/addressable_light.cpp#L40-L41) on every tick, which results (through some complicated math) in the transition running fast (it finishes _a lot_ earlier than it should).

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#1558.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
> In the future I want to add different transitions and allow the user to select a transition to be used for each light (i.e. one I want personally is a cascade transition for addressable lights, where the lights are turned on one-by-one).

I can see this being used a lot

**Comment by mmakaay** [comment]
On my lamp project, I had the need for a custom transformer to make the transitions work correctly. That wasn't even something fancy, but simply "make a standard transition that looks good". I did manage to get it working, but I had to jump a lot of hoops. If you read [my document on the process that I went through](https://github.com/mmakaay/esphome-yeelight_bs2-revengineering/blob/master/override_ESPHome_light_transformations.md), you'll get why I'm super stoked about this PR.

**Comment by OttoWinter** [comment]
> If you read my document on the process that I went through, 

Oh wow, sorry for the complicated Light API design! :)  I also am not really happy about the design, but haven't gotten around to a big refactor (well I tried during the color mode stuff, but got stuck haha).

**Review by OttoWinter — APPROVED** [review]

**Comment by oxan** [comment]
> Oh wow, sorry for the complicated Light API design! :) I also am not really happy about the design, but haven't gotten around to a big refactor (well I tried during the color mode stuff, but got stuck haha).

Honestly, I don't think the design is too bad. It's mostly a matter of tight coupling, but that's a relatively minor refactor to solve. Except for the addressable lights, that stuff is messy... [Working](https://github.com/oxan/esphome/tree/light/next-addressable) on it :) (subtle plug for #1963 :))

I'm not sure why this PR suddenly has conflicts, but I'll see if I can rebase it tonight.

**Comment by oxan** [comment]
Rebased :+1:

**Comment by mmakaay** [comment]
> Oh wow, sorry for the complicated Light API design! :)

Haha, no worries, let's say I had a really interesting journey and was happy to finally have ended up with a working piece of code :-D Nonetheless, I welcome the decoupling a lot :-D Going to test this code out now, by checking if I can refactor my code into something more digestable.

**Comment by mmakaay** [comment]
Started working on switching to a custom light transformer in my code base. Mainly deleting a butload of my current code (which is good :-) ), but now running into an issue while implementing the required transformer. From `LightState::loop()`:

```c++
  // Apply transformer (if any)
  if (this->transformer_ != nullptr) {
    auto values = this->transformer_->apply();
    this->next_write_ = values.has_value();  // don't write if transformer doesn't want us to
    if (values.has_value())
      this->current_values = *values;

    if (this->transformer_->is_finished()) {
      this->transformer_->stop();
      this->transformer_ = nullptr;
      this->target_state_reached_callback_.call();
    }
  }
```

This code allows me to return no value for `apply()`, which is what I need. I need to drive the ledc outputs in a custom way there.
However, this also results in `current_values` never being updated. 
So what I would like to be able to do, is to send some values at the end of the transformation.

Easy, I thought, simply have something like this in my custom `apply()` method:

```c++
  optional<light::LightColorValues> apply() override {

    // ... code for custom handling removed for clarity

    if (is_finished()) {
      return target_values_;
    } else {
      return {};
    }
  }
```

However, the code for a true result of is_finished() isn't hit in my tests.
Most likely, this is a timing issue. The `apply()` might run right before the end time is reached, so at that time is_finished() is false and my code would return no values. After getting back to the loop code, the time might have passed, and `is_finished()` would return true, stopping the transition.

Would it be an idea to define the `stop()` method as `virtual optional<LightColorValues> stop() = 0`, and allow a custom transformer to update the color values by returning the new light values to use from there?

Otherwise, a way to make `is_finished()` return a usable value from within the transformer `apply()` method would be nice.

In my component code, I will go for a custom implementation of the `is_finished()` method for now, to make sure that `apply()` is always called one last time when the transformation has finished.

**Comment by mmakaay** [comment]
Hmm, I tried implementing an is_finished() method, but the code never gets to the finishing state of a transition. I am testing this with the built-in random effect, which moves the light from color to color. What I'm seeing now is that each transition starts with the initial starting color from when the effect started. This is because the remote_values are never updated, and those are the values that are used as the starting point for the next random transition.

Off to bed now. Tomorrow I'll have to dive a bit deeper to see how to get my transformer to work correctly.

**Comment by oxan** [comment]
> Would it be an idea to define the stop() method as virtual optional<LightColorValues> stop() = 0, and allow a custom transformer to update the color values by returning the new light values to use from there?

Not a bad idea, should do that for start() too then.

> What I'm seeing now is that each transition starts with the initial starting color from when the effect started.

Uh yeah, I seem to have that mixed up. `current_values_` should be `remote_values_` in start_transition().

**Comment by oxan** [comment]
> Not a bad idea, should do that for start() too then.

Or instead just unconditionally write `remote_values` to `current_values` at the end of a transform. That's what the transform should end with anyway.

**Comment by mmakaay** [comment]
Yes, current and remote values are mixed up a bit. I thought I noticed something like that yesterday, but ..well.. whisky happened, so I wasn't sure if I saw and understood that correctly ;-)

With my custom transformer, I think I would still need some way to tell what the new color values are at the end of the transformation. My transformer can't return values in-between, because I need to drive the LED output pins independently. The only points for which I know the correct color values are the start and the end of the transformation.
When I don't have a way to return the color values, then unconditionally writing to current_values wouldn't work, since the remote_values aren't updated either, right?

I think I did get correct transformations when basically switching between colors (traveling home currently, so the lamp isn't at hand for testing). The use case that was failing for me, is the random light effect. That one starts a transformation for every color change. Only start() and apply() are called. The stop() method is never reached. 

For me, this might be fixed once I added another bit of required functionality to the new transformer implementation (i.e. globally keeping track of the pin outputs during an active transformation, so I can use those as a new starting point when an ongoing transformation gets interrupted by a new one).

**Comment by oxan** [comment]
> With my custom transformer, I think I would still need some way to tell what the new color values are at the end of the transformation. 

But are those different from the target values? If they aren't, and I can't think of a reason why they wouldn't be, then having LightState write the remote_values (which are identical to the target values) to current_values at the end of the transition should fix that.

> When I don't have a way to return the color values, then unconditionally writing to current_values wouldn't work, since the remote_values aren't updated either, right?

remote_values are always updated with the target values, see LightState.start_transition(). remote_values are what the user has applied and what is reported to the frontend, and those don't have a transition applied.

> The use case that was failing for me, is the random light effect. That one starts a transformation for every color change. Only start() and apply() are called. The stop() method is never reached.

Have you set the update interval & transition length of the effect to the same value?

It's a somewhat complicated situation. The random effect is applied first, determines it should go to the next color and applies that, but that aborts the still running transition, which was going to be stopped. We could call stop() whenever the transition is aborted, but maybe having a separate method for that is better.

**Comment by mmakaay** [comment]
Ah yes, when remote_values are the target_values, then that would be correct indeed.

The interval and transition time are conflicting yes. I did add a bit of extra time, but not enough to see the stop() being called. I'll experiment a bit further with that when I get home later today.

And yes, my LED outputs during a transition are wildly different from linear RGB transitions. The light circuitry in the Bedside Lamp 2 is far from linear and easy. It does provide very smooth transitions when doing a linear transition between two sets of pin output values, but shows b*tt ugly transitions when doing a linear transition between color values. This is the main reason for requiring my custom handling here.

**Comment by oxan** [comment]
The fundamental issue here is that if a transformer doesn't write through LightState (i.e. returns nothing from apply()), the current_values isn't kept up-to-date. We can resolve that at the end of the transition (because we know what it ends with), but we can't if a transition is aborted halfway through, because there's no way to know what the current state is (for lights like yours knowing that might actually be physically impossible). This also means that if a transition is aborted halfway through and another transition is started, that the start values for that transition are incorrect.

I don't think it's crazy to require transitions that write to the output directly to track the output state themselves as well. However, current_values not being guaranteed to represent the current state of the light might break other things, so we'll need to check all usages. Conceptually I think it's fine though, the only reader of that field should be the light output anyway.

Initial implementation (not even compile-tested) adding an abort() method and updating current_values at the end: https://github.com/oxan/esphome/tree/light/transformers-api

**Comment by mmakaay** [comment]
The not so crazy thing (tracking output state from my custom code) is actually what my current stable code does. So I agree on that this is a feasible strategy. I'm fine with introducing my own state object for handling that part.

I looked at the code and I like the renaming of `stop` to `finish`. That makes for a much better distinction with `abort`.
Maybe the `abort` method could better be named `cancel`? That matches the terminology that I've seen with for example the Home Assistant timer. Just a thought, not a biggy.

I'll grab the light/transformers-api code and see where I end up with that!

**Comment by mmakaay** [comment]
I tried the code from light/transformers-api, and it does work.
I implemented a few log calls and did some experiments.
The logs showed the expected finish and abort calls.

**Pull request merged**
