### PR TITLE
Add VirtualWire / RadioHead RH_ASK Protocol

### LINKED ISSUE #160: Custom Sensor - how to access to Remote receiver or I2C component
Hello,

Is it possible to query a remote receiver or an i2c component (previously declared in the yaml config file) from a custom sensor ?

I've a project where i want to receive analog sensor values transmitted over RF which idealy would be encrypt with xxxtea and using virtualwire library. If i can't use the esp8266 for receiving directly RF signal, i could use an arduino for doing the job, store values and then use it as an i2c slave to get the sensor value.

Thanks for your help.

### PR DESCRIPTION
**Pull request by Mat931**
# What does this implement/fix?

This PR adds support for transmitting and receiving [VirtualWire](https://www.airspayce.com/mikem/arduino/VirtualWire/) / [RH_ASK](https://www.airspayce.com/mikem/arduino/RadioHead/classRH__ASK.html) messages.
It can be used to send messages between Arduino and ESPHome devices via 433MHz / 868MHz / infrared / wire / etc.
This is a complete re-write of the protocol using the ESPHome remote_receiver and remote_transmitter.

Requires https://github.com/esphome/esphome/pull/4798

[Transmitter documentation](https://deploy-preview-3022--esphome.netlify.app/components/remote_transmitter.html#remote-transmitter-transmit-virtualwire)
[Receiver documentation](https://deploy-preview-3022--esphome.netlify.app/components/remote_receiver.html?highlight=virtualwire)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/esphome-core/issues/160

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3022

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
external_components:
  - source: github://pr#4954
    components: [remote_base]
    refresh: always

remote_receiver:
  filter: 15us
  pin:
    number: 26
    mode:
      input: True
      pullup: True
    inverted: False
  dump: virtualwire
  on_virtualwire:
    then:

remote_transmitter:
  pin: 25
  carrier_duty_percent: 100

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      inverted: true
    id: test
    filters:
      - delayed_on_off: 100ms
    on_press:
      - remote_transmitter.transmit_virtualwire:
          data: [0x00]
          speed: 2000

  - platform: remote_receiver
    name: "RX Test"
    virtualwire:
      data: [0x00]
      speed: 2000
    filters:
      delayed_off: 1s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by fightforlife** [comment]
@Mat931 is this a final close? Or will there be some kind of followup. I really liked this idea for transmitting custom data over longer distances.

**Comment by Mat931** [comment]
@fightforlife I was originally planning to use it to exchange data with an Arduino for my mailbox sensor, maybe with an additional encryption layer added later on. But there doesn't seem to be any interest in merging this into ESPHome. With the regular changes to ESPHome I would need to keep this PR up-to-date which I don't want to do anymore.

**Comment by fightforlife** [comment]
Thanks for this info, I completely understand. Maybe do not delete your branch yet, so others can reuse the code.
I also wanted to use this for mailbox and power/energy sensor in the basement. But I think I can also just use an rcswitch protocol to transmit binary data.

**Comment by Mat931** [comment]
Sure, feel free to use or update my code :)

**Pull request closed without merging**
