### PR TITLE
Better symlink support under Windows

### LINKED ISSUE #142: esphome symbolic link issues with Windows 10
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):** Windows 10 x86

**Affected component:**

https://esphome.io/components/esphome.html#esphome-esphome-core-version
esphome tool, when using it with local esphome-core code

**Description of problem:**
Pointing ESPHome to your local copy relies on using Symbolic links
So far I see two issues related, 
1. It seems that Windows won't allow an Administrator to create symbolic links (simlinks) the solution I found so far is to run the tool as Administrator (even when you are an administrator) I use vscode so right click -> Run as administrator (it would be nice to print an error message suggesting this, the current one is something like "you don't held the rights")
2. In python 2.7 many symlink functions are implemented as `return false` and of course it does not work, interestingly I see the symlink (to create sym links) is "fixed" and it creates the symlink the first time you use it, but next time it fails (attached stack trace) this code relies on other symlink functions: unlink, islink and readlink. Those are not working in Python 2.7 (they seem to work in Python 3 which I did not test)

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: test_local
  platform: ESP8266
  board: nodemcu
  # Use a local copy of ESPHome
  esphome_core_version:
    local: C:\glmgit\glmnet_esphome\esphome-core
```

**Traceback (if applicable):**

```
Traceback (most recent call last):
  File "C:\Python27\Scripts\esphome-script.py", line 11, in <module>
    load_entry_point('esphome', 'console_scripts', 'esphome')()
  File "c:\glmgit\glmnet_esphome\esphome\esphome\__main__.py", line 484, in main
    return run_esphome(sys.argv)
  File "c:\glmgit\glmnet_esphome\esphome\esphome\__main__.py", line 474, in run_esphome
    return POST_CONFIG_ACTIONS[args.command](args, config)
  File "c:\glmgit\glmnet_esphome\esphome\esphome\__main__.py", line 277, in command_compile
    exit_code = write_cpp(config)
  File "c:\glmgit\glmnet_esphome\esphome\esphome\__main__.py", line 150, in write_cpp
    writer.write_platformio_project()
  File "c:\glmgit\glmnet_esphome\esphome\esphome\writer.py", line 477, in write_platformio_project
    write_platformio_ini(content, platformio_ini)
  File "c:\glmgit\glmnet_esphome\esphome\esphome\writer.py", line 448, in write_platformio_ini
    symlink_esphome_core_version(CORE.esphome_core_version)
  File "c:\glmgit\glmnet_esphome\esphome\esphome\writer.py", line 231, in symlink_esphome_core_version
    symlink(src_path, dst_path)
  File "c:\glmgit\glmnet_esphome\esphome\esphome\helpers.py", line 155, in symlink
    raise ctypes.WinError()
WindowsError: [Error 183] Cannot create a file when that file already exists.
```

**Additional information and things you've tried:**
I'm already fixing this, creating this issue to track the problem and do PR later hopefully this week, I've got working simlink, unlink, readlink and islink functions working on Windows 10

### PR DESCRIPTION
**Pull request by glmnet**
## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/142

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs# N/A
**Pull request in [esphome-core](https://github.com/esphome/esphome-core) with C++ framework changes (if applicable):** esphome/esphome-core# N/A

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphomedocs](https://github.com/OttoWinter/esphomedocs).

### CODE REVIEW

**Comment by glmnet** [comment]
I tested this in my environment Windows 10 / VSCode and works. I added code to keep working on Linux/mac but did not test it those environments.

**Review by OttoWinter — COMMENTED** [review]
I won't even try to understand what this code is trying to do :) Windows is complicated lol

- Likely the issue you're seeing with travis is because you're loading the WinDLL on all systems, not just windows.

- This is too complicated to live in helpers.py, please create a new file (like symlink_ops) that speciales in these symlink operations. In there, check if python supports symlink and only if not load the DLL.

```python
if hasattr(os, 'symlink'):
    def symlink(...):
        os.symlink(...)
else:
    # do weird windows stuff
    def symlink(...):
        # windows implementation
```

- The reason travis is failing is because you do not use ESPHome's python naming conventions, functions are lower_snake_case and classes UpperCamelCase

- I'd appreciate a bit more testing of this (if possible) on more windows systems. especially if you load the DLL on a module level and not in a function esphome will fail even if you never use symlinks.

**Comment by glmnet** [comment]
Thanks @OttoWinter for your comments, very valuable as I'm not much familiar with Python and did not know I could do that. By now I'm considering installing Linux at my PC, any recommended distro?

Now it is failing at pylint but only for Python 3.5
```
python --version
Python 3.5.3
---
pylint esphome
************* Module esphome.symlink_ops
esphome/symlink_ops.py:126:15: E1101: Instance of 'OSError' has no 'winerror' member (no-member)
```
For Python 3.5 I believe this all symlink_ops won't be needed, however it tries to validate it anyway. I will need another bit of guidance on how to solve this one.

**Comment by OttoWinter** [comment]
Ah for that just disable the lint check. Add a comment line `# pylint: disable=no-member` just before the offending line.

**Review by OttoWinter — APPROVED** [review]
Thanks!

**Pull request merged**
