### PR TITLE
st7789 using mode3 when no cs pin

### PR DESCRIPTION
**Pull request by rletendu**
# What does this implement/fix?

The ST7789 display component uses CS pin with SPI mode 0. But when the hwd implementation physically tight CS pin to GND, the idle state of SCK line should be high and leading the SPI mode being used move to mode 3 instead of 0.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

Issue seems having being discussed multiple times for users experimenting issues with ST7789 with no real outcomes
Recently while trying to use  ESP Home with such litle gadget [Geekmagic with ESPHome](https://community.home-assistant.io/t/installing-esphome-on-geekmagic-smart-weather-clock-smalltv-pro/618029) I figure out the issue.
This PR is only addressing the SPI mode concern with no CS pin, the ESP8266 memory limitation might be addressed later on in a different PR since this is more a workaround for frame buffer size limitation on this platform.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

The fix is fully transparent and detects if no CS pin being declared in the display st7789 component.
If no CS, the SPI mode is forced to 3.

```yaml

font:
  - file: 'OpenSans-Regular.ttf'
    id: font1
    size: 30

color:
    - id: color_green
      red: 0%
      green: 100%
      blue: 0%

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  interface: hardware
  id: spihwd

display:
  - platform: st7789v
    model: "Custom"
    spi_id: spihwd
    height: 240
    width: 240
    offset_height: 0
    offset_width: 0
    dc_pin: GPIO02
    reset_pin: GPIO04
    id: disp

        
    lambda: |-
      it.rectangle(0,  0, it.get_width()-1, it.get_height()-1, id(color_green));

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by kbx81** [comment]
@clydebarrow any thoughts on this? 😄

**Review by jesserockz — CHANGES_REQUESTED** [review]
This should be done in config validation

**Comment by kbx81** [comment]
Ah, yes, sorry, commented before looking at the code (it was late).

As Jesse suggested, we will not unexpectedly change the SPI mode on the C/C++ side, especially now that it can be configured in yaml (see `spi_mode` in the updated docs [here](https://next.esphome.io/components/display/st7789v#configuration-variables)).

We are finding that some of these controllers/modules seem to work better with mode 0 while others work better with mode 3; I don't think we should assume that the CS pin plays into this. It's certainly possible, but it's probably best to let the user choose which works best for their display, especially since it is now quite easy to change in the yaml config.

**Comment by rletendu** [comment]
Many thanks for looking into this and sorry did not have to look to the beta version...
The SPI configuration now visible at yaml level is definitely the most flexible option !

**Comment by nielsnl68** [comment]
Is this something that could benefit other SPI controlled displays as well?

**Comment by kbx81** [comment]
> Is this something that could benefit other SPI controlled displays as well?

Yes, I do believe so @nielsnl68. 😉

**Comment by clydebarrow** [comment]
> Is this something that could benefit other SPI controlled displays as well?

Any other SPI device including displays that uses the pre-defined `spi_device_schema()` already has this implemented, as it is now handled in `register_spi_device()`.

**Pull request closed without merging**
