### PR TITLE
Move Pillow requirement from test to prd reqs.

### PR DESCRIPTION
**Pull request by mmakaay**
# What does this implement/fix? 

Docker builds currently use an old verison of the Python Pillow library, used for font support.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** https://github.com/esphome/issues/issues/1991

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [x] ESP32
- [x] ESP8266
- [ ] Windows
- [x] Mac OS
- [x] Linux

# Explain your changes

When creating a Docker build, the Pillow library as provided by the base distro is used, because only requirements.txt is applied. When doing a local setup though (which includes the requirements_test.txt), Pillow is upgraded to a recent version, fixing some isuses.

This change moves the Pillow requirements from requirements_test.txt to requirements.txt, so Docker builds will also use a recent Pillow version.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
Ok, so the original reason for not having this in prod reqs is this: On some platforms (RPi, etc), there are no pre-compiled pillow packages on PyPi (but that may have changed).

Adding this to requirements.txt would mean that a user is unable to install ESPHome if the pillow install fails.

> Docker builds currently use an old verison of the Python Pillow library, used for font support.

Maybe we can solve this another way. Remove [this line](https://github.com/esphome/esphome-docker-base/blob/5c7f548fd42f8a092daafd42f1ff9645fbb37fdf/template/Dockerfile#L10) and add pillow to the install commands [here](https://github.com/esphome/esphome/blob/063d9c47a402bf78f57e051f88c56acc08eedfdf/docker/Dockerfile#L7)

**Comment by mmakaay** [comment]
That would work too. The core issue is with the Docker container and that one is under full control to get it right, so it is fixable one way or the other.

I didn't have issues on raspberry BTW: 
```
pi@hass2:~ $ pip3 show pillow
Name: Pillow
Version: 5.4.1
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: Standard PIL License
Location: /usr/lib/python3/dist-packages
Requires:
Required-by:
```

I will update the PR per your suggestion.

**Comment by OttoWinter** [comment]
I tried implementing the change in the docker base image. Sadly, the docker `aarch64` does not have any matching pillow binaries on PyPi (https://github.com/esphome/esphome/pull/1879#issuecomment-857062894).

**Comment by OttoWinter** [comment]
> so Docker builds will also use a recent Pillow version.

Unfortunately, I don't think that is true. See for example:

```bash
$ docker run --rm -it esphome/esphome-base:latest bash
root@400a58ad9a06:/usr/src/app# echo 'pillow>4.0.0' >requirements.txt
root@400a58ad9a06:/usr/src/app# pip3 install -r requirements.txt 
Requirement already satisfied: pillow>4.0.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (5.4.1)
root@400a58ad9a06:/usr/src/app# 
```

it doesn't upgrade pillow because the `/usr/lib/python3/dist-packages` already matches the version. And because of the aarch64 issue we can't do a force-upgrade. The only option I could think of is to make the docker base image _only_ include the python3-pil package for aarch64 (for other platforms, it will later be installed during the pip install).

**Comment by OttoWinter** [comment]
Closing due to mentioned issue

**Comment by mmakaay** [comment]
Agreed. 👍

**Pull request closed without merging**
