### PR TITLE
Expose object_id in YAML configuration file

### PR DESCRIPTION
**Pull request by RoganDawes**
# What does this implement/fix? 

This allows specific naming of the HomeAssistant entity_id,
independently of the friendly "name" parameter.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
binary_sensor:
  - platform: "whatever"
    id: zone_01
    object_id: alarm_zone_01
    name: "Front door"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — COMMENTED** [review]
Hi,

Could you maybe explain the rationale for this change? Why do users need to be able to edit `object_id`?

**Comment by RoganDawes** [comment]
In my particular use case, I am interfacing an alarm panel to HA. Each zone
has a friendly name “kitchen”, “garage”, etc, but I would prefer to refer
to each zone in HA using the actual zone number.

So, by setting object_id independently from name, I can have the HA entity
id be e.g. alarm_zone_01, and have the friendly text as specified in the
yaml appear as “Front door”.

Hope this explains why this can be useful.

**Comment by Misiu** [comment]
out of curiosity why did you named that property `object_id` and not `entity_id`?

**Comment by RoganDawes** [comment]
It’s a good question.

I named it object_id, because that is the internal variable name. I did
consider changing it, and it can still be done quite easily. Just a single
place, const.py, or else pervasively if preferred.

Happy to change it if desired.

**Comment by oxan** [comment]
> I would prefer to refer to each zone in HA using the actual zone number. So, by setting object_id independently from name, I can have the HA entity id be e.g. alarm_zone_01, and have the friendly text as specified in the yaml appear as “Front door”.

You can manually change the entity id in HA (under configuration > entities) if you don't like the default generated entity ID.

**Comment by jesserockz** [comment]
I also don't really see the need for this. It's not difficult to change the name or the entity ID in HA after the device is added.

**Comment by RoganDawes** [comment]
Ah, ok. I didn't realise that you could rename the entities in HA. Close/Reject this then if you like. Thanks for considering it.

**Comment by OttoWinter** [comment]
> out of curiosity why did you named that property object_id and not entity_id?

Precisely because it's _not_ an `entity_id` :) HA itself converts from the name to `entity_id` (and has a quite complex logic for it, which would be hard to replicate in ESPHome), ESPHome doesn't know/care what `entity_id` a component has.

The purpose of `object_id` is just to give the `unique_id` generation some entropy.

**Pull request closed without merging**
