### PR TITLE
Decode DHT11 decimal part

### PR DESCRIPTION
**Pull request by airy10**
## Description:
Decode the decimal part of temperature and humidity for the DHT11 sensor - for now, only the integral part is decoded

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — CHANGES_REQUESTED** [review]
I don't think this is correct.

I believe you're using a DHT22, not a DHT11.
There's no good datasheet for DHT11, but mine only sends zeros for that part - and DHT11 is advertised as having 0 digits of precision after the comma.

Another piece of evidence is how the checksum is calculated - the checksum consists exclusively of the integral parts (see line 158) for DHT11, it doesn't make sense that the fractional part would not be part of the checksum if it exists.

**Comment by airy10** [comment]
That's really a DHT11 module. I noticed that with the other libraries that I used before testing ESPHome, I was getting temperature values with 1-digit decimal that seemed right (I'm getting .1 ... .9 intermediate values in the right order when then temperature goes slowly up or down between two int values).
I've checked the code from some other libraries and some random docs on the internet that seem to agree with that while I agree that it seems weird that the checksum. (some code is also handling negative values for the temperature which seems also weird since it's out of spec for this sensor - and I couldn't find doc about that)
All  I can say is that with that code, I'm getting some values that seem right with the DHT11-labelled module that I have... 


After rechecking the sensor label on my sensor, it's saying ASAIR DHT11 - and -20°/+50°C so with specs a bit different that the 0°/+50°C often found for the DHT11. Maybe it's an update or just some different clone/maker...
Labelling on my model in the same as on this one : https://www.yoycart.com/Product/560168769397/
I'll do more tests but I guess I need to add support for the high bit for negative value too (which shouldn't matter for models that don't go below 0...)

And some code from the Arduino DHT_sensor_library lib : 
`    case DHT11:
      f = data[2];
      if (data[3] & 0x80) {
        f = -1 - f;
      }
      f += (data[3] & 0x0f) * 0.1;
`

And I'll recheck the checksum issue since that other lib seems to use 4 bytes for the checksum so either this one or ESPHome should complain with my decide...

**Comment by airy10** [comment]
So after checking the data received from my sensor, I'm getting :
36 0 20 5 61 - for 36% 25.5°C - so the checksum is the 4 bytes sum - and ESPHome code is actually checking both checksum to the received one - which is why it's working.
Looks like for this kind of DHT11, the decoding is similar to the one for the DHT12.

**Comment by airy10** [comment]
Official datasheet v1.3 of the DHT11 are confirming the change 
Chinese version : https://datasheet.lcsc.com/szlcsc/Aosong-Guangzhou-Elec-DHT11_C117051.pdf
Google translation fo the temp part : 

```
Temperature: 0001 1000 (integer) = 18H = 24 ° C 0000 0100 (decimal) = 04H = 0.4 ° C => 24 ° C + 0.4 ° C = 24.4 ° C
 ◎Special instructions:
 When the temperature is below 0 °C, the highest position of the lower 8 bits of the temperature data is 1. 
  Example: -10.1 °C is expressed as 0000 1010 1000 0001
  Temperature: 0000 1010 (integer) = 0 AH = 10 ° C, 0000 0001 (decimal) = 01 H = 0.1 ° C => - (10 ° C + 0.1 ° C) = -10.1 ° C
```

**Comment by OttoWinter** [comment]
Ok, I see - there are probably different DHT11 boards around.

The issue I have with this code is that if there's some random data in the lower byte, this would break some users' sensors. As there are many sensors of this tpye out there, it's hard to tell what could break things.

I'd like to propose a compromise: right now, we have two checksum checks. If any of them pass, the value is decoded. I propose to add the fractional part *if and only if the checksum including the lower byte passes*.

**Comment by airy10** [comment]
All the older specs I could find from the maker say that the checksum should use the 4 bytes, while some version explicitly saying that the fractional part are always 0 and reserved for future use. But anyway, I agree with your idea of decoding the fractional part only if the 4 bytes checksum is matching. That doesn't hurt recent chips and will safely keep the current behavior for any chip that might use 2 bytes checksum only. I've pushed code for that.

**Comment by airy10** [comment]
Travis seems stuck in the pending state while it seems it ran OK

**Pull request merged**
