### PR TITLE
Sensor value is NaN - pzemac

### PR DESCRIPTION
**Pull request by kovalank**
# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ Y] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ Y] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [Y ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by ssieb** [comment]
Why are you trying to do this?  That case can never happen anyway.

**Comment by kovalank** [comment]
Whenever mains fail or under voltage/over voltage threshold what I set to trip, the relay not turn on due to last value(voltage) stayed for examble(Sensor PZEM004T, V3) present voltage reading is 220V when suddenly mains fail this value has not reset or zero, and stay its last reading of value here 220v, due to this relay not turn on, so i want whenver mains fail or sensor disconnected from esp mcu voltage value must show zero.

**Comment by kovalank** [comment]
> Why are you trying to do this? That case can never happen anyway.

Whenever mains fail or under voltage/over voltage threshold what I set to trip, the relay not turn on due to last value(voltage) stayed for examble(Sensor PZEM004T, V3) present voltage reading is 220V when suddenly mains fail this value has not reset or zero, and stay its last reading of value here 220v, due to this relay not turn on, so i want whenver mains fail or sensor disconnected from esp mcu voltage value must show zero.

**Comment by ssieb** [comment]
That has nothing to do with the change you've made here.  Use https://esphome.io/components/sensor/#timeout .  Come ask on the esphome discord if you need more help.

**Pull request closed without merging**
