### PR TITLE
Mitsubishi Heat Pump - Fixed default transmit_state to be generic instead of for a specific type of heat pump

### PR DESCRIPTION
**Pull request by RubyBailey**
## Description:

This pull is to update the default transmit_state for mitsubishi heat pumps as follows:
Byte 6 to 0x08 (generic for heat mode), from 0x48 (which is specific for FA type unit)
Byte 10 to 0x00 ,from 0x61 (which sets time to 4:10pm)
Bytes 14 and 15 to 0x00, from 0x10 and 0x40 (these are specialty bytes that are specific to individual units, values in here will cause some heat pumps to operate incorrectly, for example in the case of MFZ units they cannot be turned off.)

The current transmit_state was taken from ToniA work on heat pumps (excellent work by the way). That work has since been updated and also allows the selection of specific heat pump types for each manufacturer, which also enables the users to then select more operating parameters and modes of the heat pumps. ESPHome at present does not enable that type of heat pump unit type selection. It would be better that the transmit_state be a generic version for mitsubishi heat pump units. 

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
do you own this unit?

I made this component long ago however I don't own any. Would you mind listing yourself as CODE OWNER?

Also, isn't this change going to remove compatibility with other units? In that case you can add a configuration setting to the component to change the bytes accordingly, if you need an easy example look at the whirlpool ac which does something like that

**Comment by RubyBailey** [comment]
Yes, I own 4 Mitsubishi units. I did a small bit of work with ToniA to ensure compatibility with other Mitsubishi units. 

What is involved with being CODE OWNER? I can work my way through code, don't have very much experience with C++, yet always willing to learn. If I get stuck is there someone that I can bounce question off of?

I have mapped IR codes for 6 different varieties of Mitsubishi heat pumps. 
In all cases the generic code for Mode (Heat/Cool/Dry and Auto) byte 6 is the same. 
Fan speed and Vane positions, which the present version of the component doesn't yet do, begin to get a bit unique.  Usually only because a unit has more speeds, vane positions or has horizontal, vertical or both vanes. 
Byte 10, the clock setting can be 0x00, because we don't use the HVAC clock for anything.
Byte 14 ad 15 are specialty settings for each specific unit. In all cases changing these to 0x00 ensures that all units will run, yet not in any special mode. It's better from a compatibility perspective. 

The change shouldn't remove compatibility, it should make the present code more compatible.

I did look at the whirlpool ac code and thought about taking that route. I think for now making the proposed changes will enhance compatibility and then for the next revision we can look at added model types as well as additional unit specific controls such as fan speed and vane positions or others. It essentially means merging some of the unique aspects from ToniA's code for the type of Mitsubishi units along with my research into this component. Admittedly easier said than done from someone like myself.  I'm willing to work at it.

For the future; from a programming perspective (this is the part where I get lost) it may be worthwhile to have a discussion where the fan speed and vane position options should be. An additional trait in ClimateIR or only at the component specific file level. My terminology may be off, hopefully that clear enough for now.

Thanks again for getting back to me.

**Comment by glmnet** [comment]
In that case can you add yourself to code owners? this will make sure you get notified if somebody tries to modify this integration. To do so look how it's done in other components, like whirlpool ac

**Comment by RubyBailey** [comment]
Done. Updated code owners. Can this pull request now be merged? Thanks.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
