### PR TITLE
CCS811 support

### LINKED ISSUE #19: [Feature Request] Please add CO2 sensor CCS811
**What new integration would you wish to have?**

CO2 sensor CCS811

* CO2 sensor with temperature and humidity sensor.
* I2C communication.

Integration can extend already implemented support for MH-Z19 #94 

**If possible, provide a link to an existing library for the integration:**
https://github.com/sparkfun/SparkFun_CCS811_Arduino_Library
https://github.com/maarten-pennings/CCS811

**Please describe your use case for this integration and alternatives you've tried:**

CO2 measuring in a room.

**Additional context:**
A lot of useful information about sensor [CJMCU-811](https://revspace.nl/CJMCU-811)
Multiple boards with this sensor:
* [SparkFun](https://www.sparkfun.com/products/14193)
* [Adafruit](https://www.adafruit.com/product/3566)
* [CJMCU](https://www.banggood.com/CJMCU-811-CCS811-Carbon-Monoxide-CO-VOCs-Air-Quality-Digital-Gas-Sensor-p-1157216.html?cur_warehouse=CN)

Edit: SPI->I2C

### PR DESCRIPTION
**Pull request by OttoWinter**
## Description:

Credit goes to @huhuhugo1 for providing the initial implementation!

See https://github.com/esphome/esphome-core/pull/590

Changes:

 - Base PR used a library for communication - principally ESPHome will allow that more. However looking at the datasheet the protocol didn't look too hard so I implemented it straight in esphome
 - Base PR used MQTT client directly - that is against ESPHome's principle: Create back-end and front-end that communicate solely through a defined interface (sensor). For example it would not work for native API mode.
 - Automatically select meas_mode.
 - Added new methods for i2c interface - now accepts/uses stdlib types
 - Baseline is done over config option - then it doesn't depend on network etc to work. Not as user-friendly as doing it over network, but much simpler.

TODO:

 - Testing - I do not have the sensor.

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/19

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by pashar1** [comment]
do you calibrate for the fix temperature?

**Comment by OttoWinter** [comment]
@pashar1 Please explain what you mean in more detail.

Also see the documentation over at https://next.esphome.io

**Comment by pashar1** [comment]
here is example 

https://github.com/maarten-pennings/CCS811/tree/master/examples/ccs811envdata

where you take Temp and Humidity from other sensor and pass it to ccs811

library i have used is:

https://github.com/maarten-pennings/CCS811

**Comment by OttoWinter** [comment]
It didn't but it seemed like a simple feature so I added it now.

**Comment by dougmoscrop** [comment]
Is there a good pattern for deferring measurement until sensor is warmed up?  You're not supposed to use the readings until it's been powered for 20 minutes

**Comment by OttoWinter** [comment]
@dougmoscrop That would be a good case of a sensor filter. Just create a simple lambda that checks an uptime sensor against 20*60 and otherwise returns NAN.

**Pull request merged**
