### PR TITLE
Fix temperature and humidity for bme680 with bsec2

### LINKED ISSUE #6227: bme68x_bsec2_i2c: Temperature readings too high and can't calibrate
### The problem

Hello everybody,

I've tried the bme68x_bsec2_i2c sensor but after two days reverted back to my existing bme680 sensor module, because the temperature reading was one to four degrees too high and after a short period in the state of `Stabilizing` it went into `Uncertain`. I'm using the BME680.

I've tried to bring some amplitude into the `gas_resistance` reading by opening the window and holding it close for some time to help the algorithm to calibrate but nothing changed.

Here's an example of the temperature:
image

Switching between LP and ULP mode changed the temperature behavior.
The rel. humidity reading was also about 5% lower than expected with the new module.

### Which version of ESPHome has the issue?

2024.8.1

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

esp-wrover-kit

### Component causing the issue

bme68x_bsec2_i2c

### Example YAML snippet

```yaml
bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  state_save_interval: 24h

[...]

  - platform: bme68x_bsec2
    temperature:
      name: "Temperatur"
      accuracy_decimals: 1
      state_topic: /esp32-buero/tempin
    pressure:
      name: "Barometer"
      accuracy_decimals: 1
      state_topic: /esp32-buero/pres
    humidity:
      name: "rel. Luftfeuchte"
      accuracy_decimals: 1
      state_topic: /esp32-buero/humin
    gas_resistance:
      name: "BME68x Widerstand"
      state_topic: /esp32-buero/gasin-res
    iaq:
      name: "BME68x IAQ"
      state_topic: /esp32-buero/gasin-iaq
    iaq_static:
      name: "BME68x IAQ static"
      state_topic: /esp32-buero/gasin-iaq-static
    co2_equivalent:
      name: "BME68x CO2 Equivalent"
      state_topic: /esp32-buero/gasin-eco2
    breath_voc_equivalent:
      name: "BME68x Breath VOC Equivalent"
      state_topic: /esp32-buero/gasin-bvoc
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by luar123**
# What does this implement/fix?
Align the run_() method with bsec2 library version. This fixes the issue that temperature is too high in LP mode and way too high in ULP mode.
Does not address the issue that setting sample rates for individual sensors doesn't work.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes esphome/issues/issues/6227
- fixes partially esphome/issues/issues/6369

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
bme68x_bsec2_i2c:
  address: 0x77
  model: bme680
  operating_age: 28d
  sample_rate: LP
  supply_voltage: 3.3V
  state_save_interval: 24h

[...]

  - platform: bme68x_bsec2
    temperature:
      name: "Temperatur"
    pressure:
      name: "Barometer"
    humidity:
      name: "rel. Luftfeuchte"
    gas_resistance:
      name: "BME68x Widerstand"
    iaq:
      name: "BME68x IAQ"
    iaq_static:
      name: "BME68x IAQ static"
    co2_equivalent:
      name: "BME68x CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME68x Breath VOC Equivalent"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by luar123** [comment]
Left side is the current state without the fix (LP mode, ULP is even worse) and right side with this PR applied in ULP mode:
grafik

Four sensors: Xiaomi, AHT10, BME680 with bme680 component and BME680 with bme68x_bsec2_i2c component.

With this fix bme680 and bme68x_bsec2_i2c are aligned.
Generally, BME680 is 1-2°C higher than AHT10/Xiaomi and humidity is 2% higher than Xiaomi and 6% higher than AHT10. The humidity alignment between AHT10 and bme68x_bsec2_i2c without the fix might be only coincidence or it was better before and Xiaomi is off.

**Comment by schneich** [comment]
Hi everybody,

I can confirm that temperature readings are now a lot better then before. (+ 0.4°C, tested with an infrared laser.) Thanks for your work.

Humidity readings are still too high - by 5-10% in my case. What are the next steps with this? Can you take another look into the code? I am not knowledgeable enough in coding to be able to support you - can I assist you with anything else?

Regarding VOCs and IAQ: well, VOCs do jump a lot and very high. I get the feeling that this might be an expected behaviour? E.g. if we start cooking, something is emitting high levels of VOCs (-> +600'000 ppb). After opening the windows, the levels drop back to something between (2'000 - 20'000 ppb). (I have an expensive Airthingswave Plus device, which shows an increase as well, but levels stay below 1'200 ppb and after opening the windows, the readings drop back to 100 ppb or even lower. I start to believe that there are several ways to measure VOCs, so the readings of the two devices are not comparable.) Even though there are heavy differences in the readings, the air quality indication is very similar between the two devices. I will probably not show any VOC-readings from the BME680 in HomeAssistant, but focus on the IAQ and use that in dashboard, scripts and automations...

**Review by kbx81 — APPROVED** [review]
Seeing much "more correct" readings on my BME680s. Thanks for working on this @luar123!
If there are additional tweaks to improve humidity readings, please feel free to open another PR. I'm merging this now so we can get it into the November beta & release.

**Comment by luar123** [comment]
I will compare with the Bosch examples again - last time I was focusing on temperature.
@schneich: will let you know if there is anything to test.

**Pull request merged**
