### PR TITLE
SCD30 fixes and improvements

### LINKED ISSUE #987: SCD30 (Sensirion - CO2, Temperature and Relative Humidty Sensor) does not transmit any measurements.
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io, esphome
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 WROOM32 DevKit
**Affected component:**

SCD30 CO₂, Temperature and Relative Humidty Sensor
https://esphome.io/components/sensor/scd30.html

**Description of problem:**
Has anyone successfully tested the SCD30 integration (Sensirion CO2 sensor)? 
I only get the message "Data not ready yet!"

**Problem-relevant YAML-configuration entries:**
```yaml
substitutions:
  devicename: xxx_test_6
  upper_devicename: Test6

esphome:
  name: $devicename
  platform: ESP32
  board: esp32dev

i2c:
  id: bus_a
  sda: GPIO21
  scl: GPIO22
  scan: True
  frequency: 50kHz

sensor:
  - platform: scd30
    address: 0x61
    update_interval: 60s
    i2c_id: bus_a
    co2:
     name: ${upper_devicename} scd30 CO2
     accuracy_decimals: 1
    temperature:
     name: ${upper_devicename} scd30 Temperature
     accuracy_decimals: 2
    humidity:
     name: ${upper_devicename} scd30 Humidity
     accuracy_decimals: 1


```

**Logs (if applicable):**

```
[18:06:34][I][i2c:033]: Scanning i2c bus for active devices...
[18:06:34][I][i2c:040]: Found i2c device at address 0x61

[18:19:51][VV][i2c:056]: Beginning Transmission to 0x61:
[18:19:51][VV][i2c:093]:     Writing 0b00000010 (0x02)
[18:19:51][VV][i2c:093]:     Writing 0b00000010 (0x02)
[18:19:51][VV][i2c:061]:     Transmission ended. Status code: 0x00
[18:19:51][VV][i2c:083]: Requesting 3 bytes from 0x61:
[18:19:51][VV][i2c:113]:     Received 0b00000000 (0x00)
[18:19:51][VV][i2c:113]:     Received 0b00000000 (0x00)
[18:19:51][VV][i2c:113]:     Received 0b10000001 (0x81)
[18:19:51][W][scd30:086]: Data not ready yet!


```

**Additional information and things you've tried:**
Other I2C sensors (such as the CS811) have been successfully tested.

Comment on API Description:
Detailed Description «This class implements support for the Sensirion scd30 i2c GAS (VOC and CO2eq) sensors.»  is not correct.
The SCD30 is a CO2 Sensor and not a not a VOC and CO2eq Sensor

API Reference:
https://esphome.io/api/scd30_8h.html
https://esphome.io/api/classesphome_1_1scd30_1_1_s_c_d30_component.html#details

Interface Description Sensirion SCD30 Sensor Module
https://www.sensirion.com/fileadmin/user_upload/customers/sensirion/Dokumente/9.5_CO2/Sensirion_CO2_Sensors_SCD30_Interface_Description.pdf

### PR DESCRIPTION
**Pull request by Sizurka**
Currently SCD30 CO2 sensors do not work "out of the box" with ESPHome.  This is because the current code sends an (invalid) start measurement command with no pressure setting.  This likely "worked" for others because they had sensors that had already been configured for continuous measurements and the sensor itself will retain that setting its on board non-volatile memory.

So this fixes the start measurement command to be valid.  Since "valid" in this case also means disabling altitude/pressure compensation (the parameter is required and overwrites any stored one), it also adds an optional setting to set the measurement altitude.

It also adds a setting to enable/disable automatic self calibration by the sensor.  This is somewhat analogous to the "baseline" measurement resistive VOC/CO2eq sensors require, though the measurement principal is very different and it is not required for normal operation.  However, mine gave somewhat odd readings until I turned it on and let it calibrate, but I can't really say for sure it was required: I was changing other things at the time.

Finally, it also sets I2C clock stretching when the sensor is used on ESP8266.  The interface specification says the sensor requires up to 150ms of stretching, but this appears to only be when it's doing a daily cycle of some sort.  Normally it only seems to require a much smaller amount, but I was still getting spurious I2C errors on ESP8266 until I increased it, so this just sets it the maximum the sensor would ever need.

## Description:

**Related issue (if applicable):** fixes esphome/issues#987

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#473

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by torfbolt** [comment]
Maybe the altitude compensation parameter could be defined as a length with unit meters?

**Comment by Sizurka** [comment]
@torfbolt Can you clarify what you're suggesting here?  Are you asking to make it so the configuration parser accepts a "m" unit suffix?  Or something else?

**Comment by torfbolt** [comment]
Yep, I think a physical unit might be helpful to clarify the parameter meaning and differentiate from atmospheric pressure or some other quantity.

**Review by torfbolt — COMMENTED** [review]
I think there's already an existing config validation type "cv.distance", which handles the unit.

**Comment by Sizurka** [comment]
That accepts a floating point number.  I'd think it's preferable to reject non-integers, since we're setting something directly on the sensor (which only takes an integer), rather than rounding or something.

**Comment by torfbolt** [comment]
Well, it is a physical property, so accepting floats and rounding would also be ok in my opinion. But keeping it as an int works too.

**Comment by joegross** [comment]
FYI: I have been using this PR branch successfully with a three new SCD30 devices without issue. After a week of uptime they have converged to similar and reasonable levels for indoor CO2 levels.

If there are no procedural blockers it would be nice to merge this into dev.

**Review by torfbolt — APPROVED** [review]

**Comment by brandond** [comment]
LGTM. Thanks for the success report @joegross

**Pull request merged**
