### PR TITLE
Add support for display widgets

### PR DESCRIPTION
**Pull request by quentinmit**
## This is a draft PR, I would appreciate feedback on the general direction but it's not quite complete enough to be merged. Specific things I would like feedback on:

- This feels weird to me to live in `components/display/__init__.py`, but I can't figure out a better structure for it. Ideally each component would be able to provide its own widgets (e.g. the `graph` component could also provide a widget), but I couldn't figure out how to make that work with the way `config.py` finds platform components.
- To what extent should `CONF_*` constants live in individual components vs. `esphome.const`? I don't see a pattern in existing components.
- Am I using `TEMPLATABLE_VALUE` right? It appears to require that the class be defined with a spurious `template<typename... Ts>`, which means that the `Text` widget class has to be instantiated with a spurious `Text<>`.
- I'd like to be able to add `on_touch` handlers for widgets, but that requires a `touchscreen` component which itself has a dependency on the `display` component... how can I resolve this dependency cycle?

Once these design questions are nailed down a bit better and I've cleaned up the code, I'll write up some docs and open a corresponding doc PR.

# What does this implement/fix?

The `DisplayBuffer` class has a lot of powerful methods, but it can be hard to design a complicated display because you have to write a long `lambda` function. This PR adds support for widgets that can be defined in YAML without any code needing to be written.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** None that I know of

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
- platform: inkplate6
  id: inkplate_display
  greyscale: false
  partial_updating: false
  update_interval: 60s
  model: inkplate_6_plus

  # <snip pins for readability>

  pages:
  - id: weather
    widgets:
      vertical:
      - horizontal: # Weather
        - vertical: # Local temperatures
          - text:
              format: "%.1f"
              sensor: workshop_temp
              font: medium_40
          - text:
              format: "%.1f"
              sensor: bedroom_bed_temp
              font: medium_40
          - text:
              format: "%.1f"
              sensor: outdoor_temp
              font: medium_40
        - vertical: # Main weather
          - horizontal:
            - vertical:
              - text:
                  text: !lambda |
                    char buffer[64];
                    size_t ret = id(esptime).now().strftime(buffer, sizeof(buffer), "%a");
                    if (ret > 0) {
                      return std::string(buffer, ret);
                    }
                    return " ";
                  font: bold_32
                  align: top center
              - text:
                  text: !lambda |
                    if (id(moon_phase).state == "new_moon") { return "\U000F0F64"; }
                    if (id(moon_phase).state == "waxing_crescent") { return "\U000F0F67"; }
                    if (id(moon_phase).state == "first_quarter") { return "\U000F0F61"; }
                    if (id(moon_phase).state == "waxing_gibbous") { return "\U000F0F68"; }
                    if (id(moon_phase).state == "full_moon") { return "\U000F0F62"; }
                    if (id(moon_phase).state == "waning_gibbous") { return "\U000F0F66"; }
                    if (id(moon_phase).state == "last_quarter") { return "\U000F0F63"; }
                    if (id(moon_phase).state == "waning_crescent") { return "\U000F0F65"; }
                    return "\U000F05CE";
                  font: font_icon_moon
                  align: top center
            - vertical:
              - text:
                  text: !lambda |
                    char buffer[64];
                    size_t ret = id(esptime).now().strftime(buffer, sizeof(buffer), "%H:%M");
                    if (ret > 0) {
                      return std::string(buffer, ret);
                    }
                    return "??:??";
                  font: font_clock
                  align: top center
              - text:
                  text: !lambda |
                    char buffer[64];
                    size_t ret = id(esptime).now().strftime(buffer, sizeof(buffer), "%Y/%m/%d");
                    if (ret > 0) {
                      return std::string(buffer, ret);
                    }
                    return "????" "/?" "?/??";
                  font: bold_40
                  align: top center
          - horizontal:
            - text:
                text: !lambda |
                  if (id(weather_icon).state == "clear-night") { return "\U000F0594"; }
                  if (id(weather_icon).state == "cloudy") { return "\U000F0590"; }
                  if (id(weather_icon).state == "partlycloudy") { return "\U000F0595"; }
                  if (id(weather_icon).state == "fog") { return "\U000F0591"; }
                  if (id(weather_icon).state == "hail") { return "\U000F0592"; }
                  if (id(weather_icon).state == "lightning") { return "\U000F0593"; }
                  if (id(weather_icon).state == "lightning-rainy") { return "\U000F067E"; }
                  if (id(weather_icon).state == "pouring") { return "\U000F0596"; }
                  if (id(weather_icon).state == "rainy") { return "\U000F0597"; }
                  if (id(weather_icon).state == "snowy") { return "\U000F0F36"; }
                  if (id(weather_icon).state == "snowy-rainy") { return "\U000F067F"; }
                  if (id(weather_icon).state == "sunny") { return "\U000F0599"; }
                  if (id(weather_icon).state == "windy") { return "\U000F059D"; }
                  if (id(weather_icon).state == "windy-variant") { return "\U000F059E"; }
                  if (id(weather_icon).state == "exceptional") { return "\U000F0F38";}
                  return "\U000F1531";
                font: conditions
            - vertical:
              - text:
                  format: "%2.1f°"
                  sensor: weather_temp
                  font: font_clock
              - horizontal:
                - text:
                    format: "%2.0f°"
                    sensor: weather_temp_low
                    font: medium_40
                - text:
                    format: "%2.0f°"
                    sensor: weather_temp_high
                    font: medium_40
        - vertical: # Extra weather data
          - horizontal:
            - text:
                text_sensor: sunrise
                font: medium_40
            - text:
                text: "\U000F00DE"
                font: font_icon_sun
          - horizontal:
            - text:
                text_sensor: sunset
                font: medium_40
            - text:
                text: "\U000F00DD"
                font: font_icon_sun
      - horizontal:
        - text:
            text: "\U000F140B"
            font: font_icon_small
        - text:
            format: "%4.0fW"
            sensor: eversource_power
            font: medium_32
            align: baseline left
        - text:
            format: "%5.1f"
            sensor: download_speed
            font: medium_32
            align: baseline left
        - text:
            format: "Mbps"
            font: medium_20
            align: baseline left
        - text:
            text: !lambda |
              if (wifi::global_wifi_component->is_connected()) {
                float rssi = id(wifi_signal_dBm).state;
                if (rssi >= -50) { return "\U000F08BE"; } // 3 bars
                else if (rssi >= -60) { return "\U000F08BD"; } // 2 bars
                else if (rssi >= -70) { return "\U000F08BC"; } // 1 bar
                return "\U000F08BF"; // 0 bars
              }
              return "\U000F0783"; // X bars
            font: font_icon_small
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by quentinmit** [comment]
Hi, I am still waiting for input/comments on this PR.

**Comment by nielsnl68** [comment]
Do you know openHASP? I'm working on an integration into espHome of it.
My idea is almost the same as you have, but it looks a bit simpler. Instead of changing the display component, i choose for a separate component, and i use absolute positioning. 

Maybe we can work together? check out what i already have:
[SwitchPlate](https://github.com/nielsnl68/switchplate)

**Comment by quentinmit** [comment]
> Do you know openHASP? I'm working on an integration into espHome of it. My idea is almost the same as you have, but it looks a bit simpler. Instead of changing the display component, i choose for a separate component, and i use absolute positioning.

I looked at doing this as a separate component, but I didn't want to recreate the page abstraction that already exists inside the display component.

> Maybe we can work together? check out what i already have: [SwitchPlate](https://github.com/nielsnl68/switchplate)

Yeah, I looked at openHASP/LVGL. LVGL does not seem like a good fit for eInk displays because it assumes it can use animations/gradients/high FPS/etc. Also it looks like your config requires explicit positioning of GUI elements, instead of using a layout manager. Otherwise it looks very similar in config syntax.

**Comment by nielsnl68** [comment]
> I looked at doing this as a separate component, but I didn't want to recreate the page abstraction that already exists inside the display component.
> 
I have also looked into that as well, but i did not found it to interest to use the already existing page and extending the display component for it. I just wondering what will happen when you use your PR on a char display. Do you check for this?
 
> Yeah, I looked at openHASP/LVGL. LVGL does not seem like a good fit for eInk displays because it assumes it can use animations/gradients/high FPS/etc. 

You could be right with that time will tell of it works with does.

> Also it looks like your config requires explicit positioning of GUI elements, instead of using a layout manager. 

Yes, i do indeed use explicit positioning, sorry to say, i do not see the added value to use a layout manager like you do. I expect you define the screen for a specifiek screen (size). My honest opinion is that a layout manage give more overhead then needed and only useful when you use the same screens for different displays.

**Comment by quentinmit** [comment]
> > I looked at doing this as a separate component, but I didn't want to recreate the page abstraction that already exists inside the display component.
> 
> I have also looked into that as well, but i did not found it to interest to use the already existing page and extending the display component for it. I just wondering what will happen when you use your PR on a char display. Do you check for this?

My PR only adds widgets to `FULL_DISPLAY_SCHEMA`, which I think means it doesn't affect char (or Nextion-style) displays at all.

> > Yeah, I looked at openHASP/LVGL. LVGL does not seem like a good fit for eInk displays because it assumes it can use animations/gradients/high FPS/etc.
> 
> You could be right with that time will tell of it works with does.

Well, I have an eInk display in front of me, we don't need much time. :)

Is your component at the point where I could give it a try? I'm happy to run a demo and see how it performs.

> > Also it looks like your config requires explicit positioning of GUI elements, instead of using a layout manager.
> 
> Yes, i do indeed use explicit positioning, sorry to say, i do not see the added value to use a layout manager like you do. I expect you define the screen for a specifiek screen (size). My honest opinion is that a layout manage give more overhead then needed and only useful when you use the same screens for different displays.

I use it with a very complicated display layout - dozens of widgets per page. It's a massive pain to manually edit the positioning information for dozens of widgets every time I want to add/remove something. With a high-res eInk display I can pack a lot of information onto a single screen. Of course my branch still supports absolute positioning if you do want to do it that way.

What is the overhead you're concerned about? I don't know about LVGL but the simple layout manager I have implemented is a tiny amount of overhead compared to the actual drawing time.

**Comment by AaronVerDow** [comment]
There seems to be a hard dependency on `esphome/components/sensor/sensor.h` and `esphome/components/text_sensor/text_sensor.h` so that firmware cannot be compiled without having both `sensor` and `text_sensor` defined in yaml.

**Comment by AaronVerDow** [comment]
Got this up and running, the layouts work beautifully.  Are there any planned or existing touch screen functionality in this pull request?  I saw "buttons" exist but could not figure out a valid config to try them.

**Comment by quentinmit** [comment]
> There seems to be a hard dependency on `esphome/components/sensor/sensor.h` and `esphome/components/text_sensor/text_sensor.h` so that firmware cannot be compiled without having both `sensor` and `text_sensor` defined in yaml.

Hm, yeah. I added `#ifdef USE_SENSOR` guards, which appears to be what other components do for that case.

> Got this up and running, the layouts work beautifully. Are there any planned or existing touch screen functionality in this pull request? I saw "buttons" exist but could not figure out a valid config to try them.

See the comment at the top of the PR thread - I want to add a generic `on_touch` for every widget, but that introduces a circular dependency. I'm looking for advice on how best to resolve that.

If you want to make a button (that can't actually be tapped...) that's just something like

```yaml
        - button:
            content:
              text:
                text: "Left"
                align: center
                font: medium_40
```

i.e. buttons just have a `content` field that takes another widget.

**Comment by nielsnl68** [comment]
Hi @quentin, after our conversation last week i did some thinking on how to get thinks together and this is my proposal. I hope you can find yourself in it, i tried to pick as much from both sides:
- first, i have evaluated the LVGL widget code and found it to much to handle to be used as a starting point, there is just to much of a learning curve that i dont think it is worth our time trying to use it. I have also looked at GUIslice and i think that is much easier to modify into our needs. https://github.com/ImpulseAdventure/GUIslice
- For now we can use your widgets as starting point and add missing widgets that are useful on the go.
- We use the already existing color system, extended to a new designed style system inspired by how LVGL has done it. An other solution that i like is the way CSS is done. Not sure of that could be implemented in YAML.
- Lets make it an external component as i did already with my version and i would love the name i already chosen, when you okay with that? There is namely already a discord channel for it at: https://discord.gg/yAWXDx56
- Although i created my own pages setup, i can live with the fact that we use the display page as it being used by your version. This way it would be easier to migrate the component in the native Display component when that is desirable.
- For the coordination system i think a relative system is better then an absolute system. This allows us to have a scrolling and moving option in the future.
- You talked about dynamic sized widgets. My honest opinion i think that we should skip that for now. Would it workable that when you click on a widget that was previous dynamic and does not show all the content now that a the content will be shown in a scrollable dialog window?
- let me know what you think about the above @quentin and when you are still missing some parts just add them.

**Comment by nielsnl68** [comment]
I'm still working on this.

**Pull request closed without merging**
