### PR TITLE
Vl53l1x distance based on Sparkfun Vl53l1x libary

### PR DESCRIPTION
**Pull request by JannickBlmndl**
## Description:
PR following up on #1447, but using Sparkfun Vl53l1x libary and implemented that straight into ESPHome C++. This is all preparation for making a presence sensor component using this time of flight sensor.

The goal of this project is to detect the presence of people in a space and also count how many there are present in a space. To, eventually, with that information toggle the state of the light(s) and do other automation 'stuff' in Home Assistant. (_EDIT 2021-08-23_: [Roode](https://github.com/Lyr3x/Roode) is a start to esphome room presence detection with this VL53L1X sensor.)

**Related issue:** adds on to <https://github.com/esphome/esphome/pull/1447>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation:** None yet

Sparkfun Vl53l1x libary: https://github.com/sparkfun/SparkFun_VL53L1X_Arduino_Library/tree/master/src

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
First thing to note is please remove the `VL53L1X_` prefix from all the functions =)

**Comment by jcastro** [comment]
I was looking into create some sensors with these lasers to replace the PIR sensors. After reading your comment about presence detection I'm super interested into know how you can detect presence and not just motion? Thanks!

**Comment by DutchDeffy** [comment]
> I was looking into create some sensors with these lasers to replace the PIR sensors. After reading your comment about presence detection I'm super interested into know how you can detect presence and not just motion? Thanks!

Great to hear that! Well the working principle of the presence detection is based on a solution made by STMicroelectronics. The explanation of it can be found in the second and third url in this markdown file. https://github.com/DutchDeffy/esphome_VL53L1X_presence_sensor/blob/dev/inspiration%20and%20resources.md. If you have any questions let me know.

**Comment by sdc53** [comment]
Any progress on this integration?  Looks like there are some minor lint issues that need to get dealt with before the devs will consider it further.

**Comment by JannickBlmndl** [comment]
> Any progress on this integration? Looks like there are some minor lint issues that need to get dealt with before the devs will consider it further.

Hi, no I haven't really worked on the development of integrating the VL531LX time of flight sensor into ESPHome. At the moment if you just want to use the time of flight sensor to measure the distance, PR #1447 and the corresponding [https://github.com/mampfes/esphome/tree/vl53l1x](branch) is a make-do solution that I have tested to be working. (See the [esphome config file](https://gist.github.com/DutchDeffy/be6c871a43c9c4e757e1830b946c4bd3#file-esphome_vl53l1x_distance-yaml))

The point is that that PR uses a different library and the way it is written could conflict with the standard I2C component of ESPHome. That's one of the reasons why I initialized to base the component on the Sparkfun Vl53l1x library instead, also because the Sparkfun variant of the time of flight sensor library has more functionality which would allow for directional information based on multiple region of interest. ([st.com docs](https://www.st.com/content/ccc/resource/technical/document/user_manual/group1/df/1d/a8/2e/35/28/47/64/DM00626942/files/DM00626942.pdf/jcr:content/translations/en.DM00626942.pdf), [arduino sketch](https://github.com/Andrea-Fox/peopleCounter)) With that extra information on direction, maybe the sensor module could do more than just measuring distance. 

I don't think I could do the development of the component on my own though. Although, I have some technical computer skills, I'm not quite a software developer.

**Comment by JannickBlmndl** [comment]
Closing because before integrating to Esphome, an alternative way of getting people counting with VL531LX is created as an external component . At the time of writing the dev version 1.3 of this repo https://github.com/Lyr3x/Roode accomplishes this.

**Pull request closed without merging**
