### PR TITLE
Add state_class total

### LINKED ISSUE #2881: state_class 'total' not valid
### The problem

I try to set the state_class to `total` as described in the HA documentation here: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

But I get an error:
image
image

According to the documentation of esphome total should be valid:

> state_class (Optional, string): The state class for the sensor. See https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes for a list of available options. Set to "" to remove the default state class of a sensor.

### Which version of ESPHome has the issue?

2021.12.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

./.

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

sensor

### Example YAML snippet

```yaml
- platform: dsmr
    energy_delivered_lux:
      name: ${upper_devicename} Energy Consumed Total
      id: energy_consumed_total
      state_class: "total"
      device_class: "energy"
      unit_of_measurement: "KWh"
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by TyzzyT**
Added the state_class total: https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes

# What does this implement/fix?
Add the state_class total, as this is a valid state_class in HA.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [2881](https://github.com/esphome/issues/issues/2881)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
- platform: template
    id: water_daily_consumption
    name: "${friendly_name} daily water consumption"
    unit_of_measurement: "L"
    accuracy_decimals: 0
    icon: "mdi:water"
    state_class: total
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by TyzzyT** [comment]
I'm very new to Github, so if this is done completely wrong please ignore this PR and discard it.

**Review by jesserockz — CHANGES_REQUESTED** [review]
Woops, sorry, hit the close button while scrolling down.

Thanks for starting this.

`STATE_CLASS_TOTAL` also needs to be added in `sensor.h` to the `StateClass` enum, and to `api.proto` and then regenerate the proto files.

**Comment by TyzzyT** [comment]
@jesserockz I updated the sensor.h and api.proto file. Is this fine now?

**Comment by TyzzyT** [comment]
Bump, awaiting review/merge

**Pull request closed without merging**
