### PR TITLE
Insert Europe Tank Types from mopeka_std_check

### PR DESCRIPTION
**Pull request by lukasl96**
# What does this implement/fix?

Make Europe Tank Types useable with mopeka pro

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2886

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
Please add them to the docs too =)

**Review by spbrogan — APPROVED** [review]

**Comment by spbrogan** [comment]
I don't know much about European LPG tanks/bottles.  Are these names descriptive enough and useful to the casual user?   Do most of the European countries use the same shaped/sized tanks? For the US sizes they are very consistent but I did add the "v" to indicate vertical in case someone was using a horizontal tank (probably more likely in the larger sizes like 100lb).

**Comment by lukasl96** [comment]
Added to Docs under Pull Request
https://github.com/esphome/esphome-docs/pull/2886

**Comment by lukasl96** [comment]
> I don't know much about European LPG tanks/bottles. Are these names descriptive enough and useful to the casual user? Do most of the European countries use the same shaped/sized tanks? For the US sizes they are very consistent but I did add the "v" to indicate vertical in case someone was using a horizontal tank (probably more likely in the larger sizes like 100lb).

I am also not an expert on European LPG tanks/cylinders, however I can say that the three added formats are the most common in the private sector. I also know only vertical gas bottles. These are used a lot at the barbecues and in the campers.

**Comment by randybb** [comment]
We have 2 kg, 5 kg, 10 kg, 11 kg and 33 kg LPG cylinders. I guess there is no standard.

**Review by HeMan — APPROVED** [review]

**Pull request merged**
