### PR TITLE
Add startup_delay to interval.

### PR DESCRIPTION
**Pull request by clydebarrow**
# What does this implement/fix?

Add a new configuration option for the `interval` component to delay the first execution after boot.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3158

## Test Environment

- [x] ESP32
- [x] ESP32 IDF

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
interval:
  - interval: 5s
    startup_delay: 10s
    then:
      - logger.log: Interval called
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nagyrobi** [comment]
This is useful!

**Comment by nagyrobi** [comment]
Can't remember right now, but can this be negative?

Afaik when the device boots, there's one empty cycle passed before the first call. How about shortening that?

**Comment by clydebarrow** [comment]
> Can't remember right now, but can this be negative?

I don't see how:

```
Optional(
                CONF_STARTUP_DELAY, default="0s"
            ): cv.positive_time_period_milliseconds
```

> Afaik when the device boots, there's one empty cycle passed before the first call. How about shortening that?

I don't believe that's the case. Here's the interval setup code:

```
  item->interval = interval;
  item->last_execution = now - offset - interval;
  item->last_execution_major = this->millis_major_;
```
So it seems it sets `last_execution` in the past, which should trigger the first `update()` call pretty soon. My motivation for this was that my `interval:` calls were happening too soon - before other components had completed setup - so I did not get the impression there was any initial delay.

**Comment by clydebarrow** [comment]
@jesserockz Can we get this merged? I'd like to not have to keep merging it to my dev branches.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
