### PR TITLE
Fix name_add_mac_suffix using _ instead of -

### PR DESCRIPTION
**Pull request by glmnet**
# What does this implement/fix? 

Change `name_add_mac_suffix` the format of `_` to `-` as we are now using dash instead of _

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1111
  
# Test Environment

- [ ] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

# Explain your changes

Describe your changes here to communicate to the maintainers **why we should accept this pull request**.
Very important to fill if no issue linked

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
Obviously would be a breaking change for the users of this feature (name change) - but if we do this within the upcoming release it should be ok.

CC @jesserockz (#1615) Do you know how widely is this deployed already?

**Comment by glmnet** [comment]
it was never released so... breaks dev? LOL

**Comment by OttoWinter** [comment]
yeah breaking dev is not an issue :)

don't know if the recent tag reader etc projects use this feature, but if they do we'd need to notify them (but that won't block this PR; just want to make sure those other projects are notified)

**Comment by adonno** [comment]
> yeah breaking dev is not an issue :)
> 
> don't know if the recent tag reader etc projects use this feature, but if they do we'd need to notify them (but that won't block this PR; just want to make sure those other projects are notified)

not been used for tag reader since it's in dev/beta

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
