### PR TITLE
Change unset ESPHOME_LOG_LEVEL fallback to NONE

### PR DESCRIPTION
**Pull request by dbuezas**
# What does this implement/fix? 

ESPHome uses more RAM (2kb) ~~and flash (7kb)~~ without `logger:` than it does with it. This PR aims to save 4kb RAM and 8kb flash when the logger is not used.

Using the yaml below:

* Without `logger:`
```
Free RAM at runtime: 46,464 bytes 
RAM:   [====      ]  39.0% (used 31920 bytes from 81920 bytes)
Flash: [===       ]  32.2% (used 336344 bytes from 1044464 bytes)
```

* With `logger:` 
```
Free RAM at runtime: 48,632 bytes  ** +2168 free RAM**
RAM:   [====      ]  35.2% (used 28844 bytes from 81920 bytes) ** -3076 **
Flash: [===       ]  32.9% (used 343964 bytes from 1044464 bytes) ** +7620 **
```

* After this fix and without `logger:`
```
Free RAM at runtime: 50,216 bytes ** +3752 free RAM**
RAM:   [===       ]  34.3% (used 28076 bytes from 81920 bytes) ** -3844**
Flash: [===       ]  31.4% (used 327704 bytes from 1044464 bytes) ** -8640 **
```

The difference is more pronounced as yamls grow, I've seen up to 8kb difference in one of my bigger yamls. To be sure this is real, I added a global `uint8_t[43000]` and it crashes without the fix but runs ok with it (no logger).

### Hypothesis
I believe this to be because when the `logger:` component is not added, the `ESPHOME_LOG_LEVEL` falls back to `DEBUG` level, but `USE_STORE_LOG_STR_IN_FLASH` is not set to 1, so the logger strings are put in RAM.
~~Note that the static RAM analysis indicates the opposite, but AFAIK this only accounts for global variables. I believe this is why the issue wasn't noted before.~~

By falling back to `NONE` instead, nothing should land in neither RAM nor flash.

### non-breaking
To make sure this is not a breaking change, I tested that the default logging level is still `DEBUG` when the `logger:` is present via this lambda:
```yaml
text_sensor:
  - platform: template
    name: "defines"
    lambda: |-
      return str_sprintf("ESPHOME_LOG_LEVEL=%d", ESPHOME_LOG_LEVEL);
    update_interval: 1h
```

### Workarounds / alternatives:
Force defining the level to NONE
```yaml
esphome:
  platformio_options:
    build_flags:
      - -DESPHOME_LOG_LEVEL=ESPHOME_LOG_LEVEL_NONE
```

Defining a "crippled" logger
```yaml
logger:
  baud_rate: 0
  tx_buffer_size: 0
  level: none
```

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: remote-transmitter-test
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 250
    then:
      - sensor.template.publish:
          id: free_ram
          state: !lambda "return ESP.getFreeHeap();"

sensor:
  - platform: template
    id: "free_ram"
    name: "free ram"
    unit_of_measurement: bytes
    update_interval: never

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_pass
  fast_connect: true

api:

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by CarlosGS — APPROVED** [review]

**Comment by agners** [comment]
FWIW, according to `xtensa-esp32-elf-size` text and data section get smaller with or without this change, but even smaller with this change
```
Before, without logger
   text    data     bss     dec     hex filename
 702682  251056   27200  980938   ef7ca config/.esphome/build/esp32-test/pioenvs/esp32-test/firmware.elf

Before, with logger
   text    data     bss     dec     hex filename
 707742  253000   27296  988038   f1386 config/.esphome/build/esp32-test/pioenvs/esp32-test/firmware.elf

After, without logger
   text    data     bss     dec     hex filename
 690930  242468   27200  960598   ea856 config/.esphome/build/esp32-test/pioenvs/esp32-test/firmware.elf
 
After, with logger
    text    data     bss     dec     hex filename
 707742  253000   27296  988038   f1386 config/.esphome/build/esp32-test/pioenvs/esp32-test/firmware.elf
```

**Review by agners — APPROVED** [review]

**Review by oxan — CHANGES_REQUESTED** [review]
Good catch! Unfortunately, this fix effectively disables static analysis of log messages, since they now vanish in preprocessing. Could you add a define for `ESPHOME_LOG_LEVEL` to the `clangtidy` environment in `platformio.ini`?

@agners That's expected on ESP32, as we don't place log strings in flash there.

**Comment by dbuezas** [comment]
I see @oxan, thanks. Is my last commit right?
I'm not sure what this does, I assume this way warnings are shown during development if the conventions are not followed, is that correct?

Anything I can run to make sure it now works as intended?
Also: shouldn't one use `ESPHOME_LOG_LEVEL_VERY_VERBOSE` instead, to ensure the check is done with anything that can be logged?

**Comment by oxan** [comment]
Argh. Your commit is correct, except that I had read `platformio.ini` too fast and didn't notice that we already define `ESPHOME_LOG_LEVEL` there (to `ESPHOME_LOG_LEVEL_VERY_VERBOSE`, as you correctly suggested), so your extra change wasn't needed. Sorry about that.

I'll revert it and merge this PR. Thank you very much!

**Review by oxan — APPROVED** [review]

**Pull request merged**
