### PR TITLE
PMSX003: Add support for specifying the update interval and spinning down

### PR DESCRIPTION
**Pull request by mjg59**
The PMSX003 series includes a moving fan, and device lifetime is likely to
be limited by (a) how long the fan is running, and (b) how much dust the
device ingests. If continuous sensor readings aren't required, we can spin
the fan down and increase the expected useful lifetime of the sensor.
However, there's an expected delay between turning the fan on and getting
reasonable data back, so we only want to spin the fan down if the update
interval is greater than that. This involves maintaining some additional
state in the loop() method, but the core functionality remains consistent.

# What does this implement/fix? 

Configuration of the update interval for PMSX003 devices, and associated logic for spinning down the fan.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1803

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: pmsx003
    type: PMSX003
    update_interval: 300000ms

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by oxan** [comment]
Hi Matthew, nice to see you here!

I like the idea of this PR, but I'm wondering if we could maybe implement it in a somewhat more idiomatic way. I think we can always enable manual measurement method. If we then make `PMSX003Component` extend `PollingComponent` (and the config schema `cv.polling_component_schema("60s")`), we get the update interval setting and an `update` method that gets called at that interval for free. Then the state machine doesn't have to be evaluated at 60 Hz in the loop, and we can probably get rid of it all together. Something like this in pseudocode:
```
setup() {
  send_command_(PMS_CMD_AUTO_MANUAL, 0);
  send_command_(PMS_CMD_ON_STANDBY, this->update_interval_ > PMS_STABILISING_MS);
}

update() {
  if (this->update_interval_ > PMS_STABILISING_MS) {
    send_command_(PMS_CMD_ON_STANDBY, 0);
    this->set_timeout(PMS_STABILISING_MS, this->trigger_measurement);
  } else {
    this->trigger_measurement();
  }
}

trigger_measurement() {
    consume_uart_buffer();
    this->send_command_(PMS_CMD_TRIG_MANUAL, 0);
}

loop() {
  // leave unchanged, except for going back to sleep in parse_data_()
}
```

What do you think?

**Comment by mjg59** [comment]
Thanks! That seems like a sensible approach - I'll try to rework this.

**Review by OttoWinter — APPROVED** [review]
LGTM, thanks!

From my side I think doing it in `loop` is not a problem here, as the function exists anyway and needs to be called, the overhead of this check is negligible.

**Comment by OttoWinter** [comment]
I added a validation check to see require the tx pin to be set if using the update interval feature, and to check the update interval is greater than or equal to 30s if set.

I tested it on my sensor and it worked, from my side this LGTM. Can you check if the changes look ok to you too? Thanks!

Note: this changes the update_interval to *only* be used to go into/out of standby (i.e., when the feature is disabled the loop will again try to read all the time)

**Comment by mckochan** [comment]
@mjg59  have you tested Otto's changes? They work for me and I am eager to see this merged. Thanks!

**Pull request merged**
