### PR TITLE
Update esphome.css

### PR DESCRIPTION
**Pull request by 3ative**
Make HA Themed Background colour available to ESPHome iframe Dashboard.

## Description:
If "primary-bg-color:" is removed from this CSS file, then ESPHome's Dashboard will use Home Assistant Background colour as used in 'Themes'

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — COMMENTED** [review]
So this only changes the background color, right?

Is there a way that we can only update the BG color for HA installs where the theme was manually changed? I don't want to change the look for normal installs.

**Comment by 3ative** [comment]
@OttoWinter 
Yeah, it allows the HA theme BG color to show - I guess it makes the BG of ESPhome dash transparent
E.G.
Demo

... So yeah that _may_ effect the normal install.

I was unable to find a line I could add to an HA theme that would effect this - as everything gets over-ridden by the 'esphome.css'

**Comment by 3ative** [comment]
This might work for both..
Capture

I wonder if adding: **--primary-bg-color: var(--primary-color);** would get ignored on 'normal' installs of ESPHome

**Comment by 3ative** [comment]
[esphome.zip](https://github.com/esphome/esphome/files/5323539/esphome.zip)

 For someone to test

**Comment by edenhaus** [comment]
> 
> 
> This might work for both..
> 
> Capture
> 
> I wonder if adding: **--primary-bg-color: var(--primary-background-color);** would get ignored on 'normal' installs of ESPHome

I have a standalone ('normal') installation and your suggesttion is not ignored but we could use it with a fallback.

`--primary-bg-color: var(--primary-background-color, #fafafa);`

The above code set the `--primary-bg-color` to `--primary-background-color`, if the variable is set otherwise to `#fafafa`. Therefore for standalone installation the color would alsways be `#fafafa` as it is now.
@3ative Can you please test, if my suggestion is working also in your case?

> Is there a way that we can only update the BG color for HA installs where the theme was manually changed? I don't want to change the look for normal installs.

In HA the `--primary-background-color` is default set to  `#fafafa`, when the light (day) theme is selected. The background color will be the same, so the enduser will see no difference. 

When he selects the dark (night) theme, then  `--primary-background-color`  is set to `#111111` and the dashboard looks like the snipping below
grafik

@OttoWinter What do you think?

**Comment by 3ative** [comment]
@edenhaus 
> --primary-bg-color: var(--primary-background-color, #fafafa);

I didn't know about fall-back, great info. Thanks.

I'm unable to test, I don't have direct access to 'esphome.css' - I can only use Chrome dev tools in browser. 

But, if it does work, and won't effect the standalone ESPHome, that'll be fantastic for mine and others HA themes.

**Comment by oxan** [comment]
Hi, sorry this took so long! In the meantime, the dashboard frontend has been split out into its [own repository](https://github.com/esphome/dashboard), so this PR no longer applies to this repository, so I'll close this PR here. If you or anyone else still wants to pursue this, please open a PR with the relevant changes there. Nevertheless, thanks for being willing to contribute!

**Pull request closed without merging**
