### PR TITLE
Remove duplicate scrollbar & move scrollbar

### PR DESCRIPTION
**Pull request by TheZoker**
Removes the duplicate scrollbar on the editor modal

### CODE REVIEW

**Comment by OttoWinter** [comment]
I tried this change locally and the autoscroll does not appear to be working anymore. (again chrome on macOS)

When I go to "show logs" I see the logs scroll by, but the logs are not scrolling automatically. Though when I do scroll down manually the title stays at the top (I guess this was the intention of the change)

**Comment by TheZoker** [comment]
Yes that was the intention. Very strange, works perfectly for me:
https://www.useloom.com/share/e739879f4bf04fbaae8c664d7c698924

What is the easiest/fast way to check this? So far I just tried the changes by modifying the DOM within the console.

**Comment by OttoWinter** [comment]
So for testing you have to clone esphome and install it locally:

```bash
git clone https://github.com/esphome/esphome
cd esphome
pip2 install -e .
```
(not possible for docker afaik, for Hass.io you can type `pulls/443` as `esphome_version` and install dev hass.io addon)

I'm no flex expert, so I don't know why this is not working and how to fix it. I think I tried something similar to that when I originally added the autoscroll - but somehow that wouldn't work because of the moda or whatever.

I just know that when I try this myself auto-scroll doesn't seem to work for my browser, will try with firefox when I get time.

btw, the jsfiddle does work for me. Don't know why though

**Comment by TheZoker** [comment]
Alright, will try that.

Ok so on firefox, the jsfiddle does not work. But that's good, because now I can test it and try to make it work. Would a javascript solution for the autoscroll also work? Or do you prefer css (which might not work the same in every browser)

**Comment by OttoWinter** [comment]
I'd prefer CSS - most of the JS autoscroll solutions I've seen (for example travis, gitlab) are pretty bad and feel sluggish.

**Comment by OttoWinter** [comment]
Ok, just checked out this PR and it appears to work now! thanks! I will add it to the 1.11 milestone so that it can get in that release 👍

**Comment by TheZoker** [comment]
Glad it works :)
I forgot to remove one unnecessary wrapper:
https://github.com/esphome/esphome/blob/dev/esphome/dashboard/templates/index.html#L138

Should I open another PR?

**Comment by TheZoker** [comment]
PR opened: #444

**Pull request merged**
