### PR TITLE
[hm3301] Updated the AQI based on the airnow document

### PR DESCRIPTION
**Pull request by optimusprimespace**
Changed the code according to the https://www.airnow.gov/sites/default/files/2020-05/aqi-technical-assistance-document-sept2018.pdf  document

# What does this implement/fix?

This change fixes a typo when the AQI is calculated.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by freekode — APPROVED** [review]

**Comment by zry98** [comment]
Can we make the AQI calculator an independent component, so that it can be used easily with other pm2.5 sensor as source?

**Comment by optimusprimespace** [comment]
Yes it would be awesome to have a separate AQI calculator component, but which of the main pollutants would you include? They need to meet these criteria:
- Ozone (ppm) – truncate to 3 decimal places
- PM 2.5 (μg/m 3) – truncate to 1 decimal place
- PM 10 (μg/m 3) – truncate to integer
- CO (ppm) – truncate to 1 decimal place
- SO2 (ppb) – truncate to integer
- NO2 (ppb) – truncate to integer

Also you have multiple options for Ozone: 8 hour or 1 hour average. If you want real-time AQI you're supposed to give it a max 3 hours average. It's not as simple as you might expect it. Furthermore you can't just give a 1 minute reading because there aren't any experiments with that time frame for the human body.

**Comment by optimusprimespace** [comment]
Upon further research the CAQI is no longer endorsed by the EU, and instead from 2017 it was replaced by EAQI which has different index levels (now 6). (https://www.eea.europa.eu/themes/air/air-quality-index)

**Comment by optimusprimespace** [comment]
@jesserockz Can you look at the code? It's a small PR, i need help as i don't know what is causing it to have CI/CD errors.

**Comment by jesserockz** [comment]
@optimusprimespace Please look at the CI run details, it tells you exactly why it is failing and exactly what code needs to change. It is a formatting issue, because the lines got longer with your changes.
The reason we have these CI runs is to not take time away from maintainers when changes like formatting is still required before a review can happen

**Comment by optimusprimespace** [comment]
@jesserockz, @freekode  Can you review the code?

**Review by freekode — APPROVED** [review]

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
