### PR TITLE
Background calibration & ABC commands for SenseAir S8

### PR DESCRIPTION
**Pull request by nmaggioni**
# What does this implement/fix? 

Additional ModBus commands (and thus ESPHome actions) for the SenseAir S8 sensor to trigger a manual background calibration (ambient air @ 400ppm CO2) and to enable or disable _Automatic Baseline Calibration_. ABC will be enabled with the default interval of 180 hours as per the official specs: changing this value is possible but outside the scope of this PR.

I followed the specs reported in [this](https://www.driesen-kern.de/downloads/ba-senseair-s8-modbus.pdf) document.

Should help troubleshoot issues like esphome/issues#1899.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** esphome/issues#1899

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1066
  
# Test Environment

- [ ] ESP32
- [X] ESP8266
- [ ] Windows
- [ ] Mac OS
- [X] Linux

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: senseair
    id: senseair1
    co2:
        name: "CO2"
    update_interval: 60s

switch:
  - platform: template
    name: "Trigger background calibration"
    turn_on_action:
      - senseair.background_calibration: senseair1
  - platform: template
    name: "Get background calibration result"
    turn_on_action:
      - senseair.background_calibration_result: senseair1
  - platform: template
    name: "Get ABC Period"
    turn_on_action:
      - senseair.abc_get_period: senseair1
  - platform: template
    name: "Disable ABC"
    turn_on_action:
      - senseair.abc_disable: senseair1
  - platform: template
    name: "Enable ABC"
    turn_on_action:
      - senseair.abc_enable: senseair1
```

# Explain your changes

I copied the implementation of the commands from the [MHZ19 sensor](https://github.com/esphome/esphome/tree/08998caabc7d592ef07bb1bdc7386ae4e697b4a0/esphome/components/mhz19).

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] ~Tests have been added to verify that the new code works (under `tests/` folder).~ N/A
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
Could you please add each action to the test file. You can just add them in the `on_value` of the sensor itself.

**Comment by nmaggioni** [comment]
@jesserockz Done, thanks.

**Review by jesserockz — APPROVED** [review]
Thanks

**Review by OttoWinter — APPROVED** [review]
LGTM :+1:

**Comment by quizzical86** [comment]
@nmaggioni thanks a lot for this nice feature.
Your example entry for config.yaml is also very usefull. Perhaps a good idea to add it to the [documentation page](https://esphome.io/components/sensor/senseair.html).

**Comment by nmaggioni** [comment]
@quizzical86 The relevant bits are [already there](https://esphome.io/components/sensor/senseair.html#senseair-background-calibration-action), you're not restricted to attaching the actions to dedicated switches for example.

**Pull request merged**
