### PR TITLE
pm1006: add support for sending a measurement request

### PR DESCRIPTION
**Pull request by Habbie**
# What does this implement/fix? 

The existing pm1006 driver (that I PRed before the previous ESPHome release) assumes it is 'sniffing' the serial bus from the PM1006 sensor to the IKEA MCU/PCB in the IKEA VINDRIKTNING. However, some people would like to remove that MCU or even the PCB. In that case, the IKEA MCU no longer sends measurement requests to the pm1006.

This PR adds support for sending such requests to the pm1006.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes --

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1423

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
uart:
  rx_pin: D2
  tx_pin: D1
  baud_rate: 9600

sensor:
  - platform: pm1006
    pm_2_5:
      name: "Particulate Matter <2.5µm"
    update_interval: 20s
```

Compared to the existing pm1006 implementations, the new items are `tx_pin` and `update_interval`.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by rvdm** [comment]
Just flashed this to my D1 Mini with a pm1006's rx/tx connected (VINDRIKTNING with removed MCU), and this patch is working fine!

Just for completeness, these are the relevant yaml bits I used:

```
external_components:
- source: github://Habbie/esphome@pm1006-rxtx
  components: [ pm1006 ]

uart:
  rx_pin: D2
  tx_pin: D3
  baud_rate: 9600
 
sensor:
- platform: pm1006
  pm_2_5:
    name: Ikea_Vindriktning_PM25
  update_interval: 10s

```

.. don't forget update_interval, otherwise there's no updates!

**Review by oxan — APPROVED** [review]

**Comment by MattWestb** [comment]
Its possible also implanting the fan control from ESPHome with the timing of sending and receiving commands on the comport is being made and the printout of the MCU is being made if some like to so it or the LEDs and light sensor.
https://threadreaderapp.com/thread/1415291684569632768.html (use google translate)

**Comment by Habbie** [comment]
> Its possible also implanting the fan control from ESPHome

Yes, I thought of that, but did not have time to add it yet. I'll likely do another PR for that at some point.

**Comment by MattWestb** [comment]
The LEDs and light level can being added as "normal ESPHome" components so its no problems.
The fan timing is little more tricky but shall being not so hard implanting as one option later then this PR is merged.

I was baying 2 yesterday but dont have time modding them then i going for holiday and not being back in 3 weeks.

And latest from tasmota they is taking the 2 "not supported" sensors for 1.0 and 10 away then its looks its not valid at all.

Great work done devs !!!

**Comment by Habbie** [comment]
> The LEDs and light level can being added as "normal ESPHome" components so its no problems.

Yep!



>  The fan timing is little more tricky but shall being not so hard implanting as one option later then this PR is merged.

Indeed, would be hard to time correctly without support in the PM1006 driver itself. You're exactly right.



> And latest from tasmota they is taking the 2 "not supported" sensors for 1.0 and 10 away then its looks its not valid at all.

Indeed. I asked Cubic about those values and they say they are "reserved for R&D". As far as I can tell, they definitely are not 1.0/10 values.

**Review by jesserockz — COMMENTED** [review]
You could add a `FINAL_VALIDATE_SCHEMA` that can look at the uart and automatically change the `update_interval` 

Or the opposite, it can check if `update_interval` is set to something other than `never` and fail validation if `tx` is not set on uart

**Comment by Habbie** [comment]
> Or the opposite, it can check if `update_interval` is set to something other than `never` and fail validation if `tx` is not set on uart

Pushed this one, thanks for the tip!

**Comment by Habbie** [comment]
(comments welcome, especially on my matching of `never` which clearly is a hack)

**Comment by Habbie** [comment]
I just realised `update_interval`is missing from `dump_config`. Will fix that soon.

**Comment by Habbie** [comment]
> I just realised `update_interval`is missing from `dump_config`. Will fix that soon.

Pushed this (last night).

**Comment by Habbie** [comment]
Rebased and squashed.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
