### PR TITLE
Add option to lock a switch.

### PR DESCRIPTION
**Pull request by manonfgoo**
# What does this implement/fix?
This PR adds a feature to lock a switch. When a switch is locked it can not be switched 
from the frontend until unlocked.

This code adds
the following actions:
switch.lock: Lock the switch
switch.unlock: Unlock the switch
switch.lock_turn_off:  Turn OFF and lock
switch.lock_turn_on:  Turn ON and lock
switch.lock_toggle:  Toggle and lock

and the following conditions:
switch.is_locked: true when switch is locked
switch.is_unlocked: true when switch is unlocked

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml

switch:
  - platform: gpio
    pin: 25
    name: "Water Pump Relay"
    id: pump_relay


binary_sensor:
  - platform: gpio
    # ...
    on_press:
      min_length: 150ms
      then:
        if:
          condition:
              switch.is_locked: pump_switch
          then:
            - switch.unlock: pump_switch
          else:
            - logger.log: "Not locked, do not need to unlock"

    on_release:
      then:
            - switch.lock_turn_off: pump_switch



```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
Not sure I agree with this concept living in the base switch code. This is something that one can achieve with a template switch in front of the real switch in YAML.

**Comment by manonfgoo** [comment]
> Not sure I agree with this concept living in the base switch code. This is something that one can achieve with a template switch in front of the real switch in YAML.

I thought of this too, but
- this would not prevent the underlying switch from being the switched on or off by an action or a lambda 
- The syntax is much less complex from a users perspective, and less prone to errors. As this feature may be used to add some level of security, I believe that Simplicity from a users perspective is valuable.  

If you do  not want this in base switch code, I could either try to put this in "Generic Output Switch" or create a new component "Generic Lockable Output Switch" 

What do you think about this?

**Comment by jesserockz** [comment]
> - this would not prevent the underlying switch from being the switched on or off by an action or a lambda

Well this is up to the user to not put in these actions with the underlying switch id when designing your configuration. :smiley: 

> - The syntax is much less complex from a users perspective, and less prone to errors. As this feature may be used to add some level of security, I believe that Simplicity from a users perspective is valuable.

Yes this is always desired, but it adds complexity to debug every switch platform now when something goes wrong. Its a trade-off there.

> If you do not want this in base switch code, I could either try to put this in "Generic Output Switch" or create a new component "Generic Lockable Output Switch"

I would lean towards creating a lockable template switch, but then this restricts the switch to the outputs only, and not another platforms switch if it were in the base code, or just a template switch in front.

I will have a think about it and get back to you.

**Comment by jesserockz** [comment]
So, I asked others in the [chat in discord](https://discord.gg/N5SxdhTXXu), and I am going to push back and stick with my original statement about this being easy enough to implement using a template switch.

I will look into creating a cookbook or guide on the website for a "lockable" template switch to make it easy for people to implement.

We do appreciate you wanting to contribute, and hope this does not put you off for future PRs.

Thanks,
Jesse

**Comment by SeByDocKy** [comment]
Is-it possible to do the same type of locking for a button object ?

**Pull request closed without merging**
