### PR TITLE
No dyn memory alloc

### PR DESCRIPTION
**Pull request by jflecool2**
# What does this implement/fix?
Although many users use less than the memory available on their devices, some users are pushing the limit. 
I firmly believe ESPHome should use statically allocated memory whenever possible, and requests it's PR to do the same.
As it stands, most ESPHome objects are on the stack, and when memory is full, all hell break lose. That is because most components assume their alloc/new will succeed and does not recover gracefully.
While working on my issue [3199](https://github.com/esphome/issues/issues/3199) I thought it was ram overflowing, but as of right now it doesn't seem to be the case.
Reguardless, I think this PR and a new guideline would improve ESPHome by ensuring that there is enough memory at compile time by giving an error rather than at runtime by crashing in bootloop. 
Many component require to be initialized at runtime because of arguments, so the syntax for 'new' is the following:
```
type *pointer_name;
char pointer_name_sbuf[sizeof(type)];
[...]
pointer_name = new (pointer_name_sbuf) type(arguments);
```
I will say that cpp_generator.py is rather advanced/complicated and there may be a more elegant way to implement this. 
Please note this is my first PR in ESPHome so if I did something wrong, please bear with me...

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** 
Related to [3199](https://github.com/esphome/issues/issues/3199) but not a fix (sadly)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 
Not applicable

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:
Use your most complicated config.yaml to ensure all components and variations work with this fix

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jflecool2** [comment]
On the subject of failed unit test:
### test1.yaml
```
/home/runner/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: .pioenvs/test1/firmware.elf section `.dram0.bss' will not fit in region `dram0_0_seg'
/home/runner/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: DRAM segment data does not fit.
/home/runner/.platformio/packages/toolchain-xtensa32/bin/../lib/gcc/xtensa-esp32-elf/5.2.0/../../../../xtensa-esp32-elf/bin/ld: region `dram0_0_seg' overflowed by 76040 bytes
```
This either show a serious lack of understanding of how memory works on my end and my proposal is moot, or it show how important my PR is (that is, test1.yaml will compile and OTA but will fail on runtime because the ram is full)
### test3.yaml
```
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: address 0x40001850 of .pioenvs/test3/firmware.elf section `.bss' is not within region `dram0_0_seg'
/home/runner/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/10.3.0/../../../../xtensa-lx106-elf/bin/ld: address 0x40001850 of .pioenvs/test3/firmware.elf section `.bss' is not within region `dram0_0_seg
```
This is ... confusing. Could this be the same as test1.yaml but with much more obscure error message due to different compiler/linker?
I will try to split both into 2 (test1a.yaml test1b.yaml) to see if it resolve the issue, but because of the size of those yaml it will take time to split. In the meantime, please tell me if you are ok with the concept and/or implementation of this PR.

**Comment by OttoWinter** [comment]
> As it stands, most ESPHome objects are on the stack, 

Probably just a typo, but most of them are on the heap?

---

The issue is that global vars are put in the `bss` section (aka `dram0_0_seg` in your testcase above). These sections are defined by the linker script and have constant size (https://github.com/espressif/arduino-esp32/blob/cf01523ded6d40e6feaa92b9aa647e5553148b60/tools/sdk/esp32/ld/memory.ld#L57-L67, https://github.com/esp8266/Arduino/blob/601da8e933d3b0878ad8dd0ab569af2361fec7ec/tools/sdk/ld/eagle.flash.4m.ld#L12), even if the RAM chip installed has more available.

And in any case there are plenty of dynamic allocations happening in other places in esphome anyway (for example, any time a `std::string` is used, which is a lot of places); So probably this PR would only catch cases where the config uses _way_ more RAM than is available, but can't catch the more likely case of being a bit above the limit

(test1/test3 _probably_ would run out of memory without this change too, just at runtime; they're only for testing compilation)

**Comment by jflecool2** [comment]
Thank you @OttoWinter for your comments.
My Sonoff NsPanel is crashing for what I believe is memory issue, even though it looks like plenty is avail when compiling.  But I suspected some dynamic memory was the culprit, just couldn't prove it yet.
You know the codebase better, and I wasn't aware string was used everywhere. In other embedded project I've been working on there wasn't much string, only char array... and other static things ...
This endeavor would be very long to do, and maybe some tasks would even be not doable.
Do you think we could overwrite the New operator in a way to make out-of-memory reset and/or warn?
Otherwise, do you have any other idea to have a more graceful handling of memory filled?
Thank you!!

**Comment by OttoWinter** [comment]
> Do you think we could overwrite the New operator in a way to make out-of-memory reset and/or warn?

It does already do a reset, and prints a warning to the serial port (though not over network connections, as at that point the system is in a bad state).

**Pull request closed without merging**
