### PR TITLE
Ble scanner

### PR DESCRIPTION
**Pull request by jzlka**
## Description:
Added a ble_scanner component that scans reachable BLE devices using [text_sensor](https://esphome.io/components/text_sensor/index.html) and [esp32_ble_tracker](https://esphome.io/components/esp32_ble_tracker.html). Implemented together with @jozhalaj.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation:** esphome/esphome-docs#611

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

## Example log:
| Address | RSSI | Name | Timestamp |
|---|---|---|---|
|62:E1:67:95:71:AA | -91 |   | Mon, 06 Jan 2020 13:08:50 GMT|
|62:E1:67:95:71:AA | -88 |   | Mon, 06 Jan 2020 13:08:50 GMT|
|62:E1:67:95:71:AA | -88 |   | Mon, 06 Jan 2020 13:08:47 GMT|
|62:E1:67:95:71:AA | -92 |   | Mon, 06 Jan 2020 13:08:46 GMT|
|62:E1:67:95:71:AA | -87 |   | Mon, 06 Jan 2020 13:08:45 GMT|
|62:E1:67:95:71:AA | -90 |   | Mon, 06 Jan 2020 13:08:43 GMT|
|2C:41:A1:87:CC:E5 | -80 | LE-Bose QC35 II | Mon, 06 Jan 2020 13:08:43 GMT|
|62:E1:67:95:71:AA | -94 |   | Mon, 06 Jan 2020 13:08:42 GMT|
|E7:F2:42:2D:7C:E7 | -93 | Amazfit Bip Watch | Mon, 06 Jan 2020 13:08:42 GMT|
|62:E1:67:95:71:AA | -90 |   | Mon, 06 Jan 2020 13:08:41 GMT|
|D7:E7:E7:6B:D6:3F | -82 | MI Band 2 | Mon, 06 Jan 2020 13:08:41 GMT|

### CODE REVIEW

**Comment by OttoWinter** [comment]
Thanks!

Please check the [travis CI](https://travis-ci.org/esphome/esphome/jobs/647324570?utm_medium=notification&utm_source=github_status) logs, there are some small formatting issues that need to be resolved.

**Comment by TheKuko** [comment]
@OttoWinter Should I move the test into test3.yaml file? (https://travis-ci.org/esphome/esphome/jobs/648412741#L963)

**Comment by TheKuko** [comment]
I rebased the branch to be synced with upstream (that's why there is the force-push).

**Comment by TheKuko** [comment]
I'd appreciate if anybody can validate test edits :).

**Comment by glmnet** [comment]
GTM when docs fixed

**Pull request merged**
