### PR TITLE
esp32_rmt_led_strip: fix compile with ESP-IDF >= 5

### PR DESCRIPTION
**Pull request by stintel**
# What does this implement/fix?

Fix compilation of the esp32_rmt_led_strip component with ESP-IDF >= 5.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by kbx81** [comment]
🤔 How did we fix this in https://github.com/esphome/esphome/pull/4364/files ? I remember this issue happening everywhere across the board initially, but I think you changed something so we didn't have to do this fix everywhere else.

**Comment by kroimon** [comment]
@kbx81 It was fixed everywhere else by PR #4671 according to [this comment](https://github.com/esphome/esphome/pull/4364#discussion_r1164739287).

**Comment by stintel** [comment]
The esp32_rmt_led_strip component was added after #4671. Unfortunately there were other components that were also missed in that PR. I have fixed a few more in small PRs hoping they could be reviewed and merged quickly.

**Comment by stintel** [comment]
Can someone ping me when CI is fixed? Appreciate it!

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
