### PR TITLE
Ruuvi BLE: Fix NA handling of fields

### LINKED ISSUE #3489: ruuvi_ble: incorrect parsing of invalid values (NA)
### The problem

Ruuvi tag sensor handling seems to handle "invalid" (N/A values) sensor values incorrectly with data format `0x05` (aka RawV2):

1. Invalid values with Signed two byte fields are  signaled with `[0x80, 0x00]`, not `[0x7F, 0xFF]` (implementation with temperature) nor `[0xFF, 0xFF]` (implementation with acceleration x/y/z). Apart from temperature and acceleration fields, there are no other fields affected. See https://docs.ruuvi.com/communication/bluetooth-advertisements/data-format-5-rawv2
2. Invalid values with unsigned fields are signaled with "largest presentable number for unsigned values", e.g. `0xFF` or `[0xFF, 0xFF]`. The invalid value handling is missing completely with "movement counter" and "measurement sequence number". According to my tests other fields are handled correctly.
3. There is a calculated field, "acceleration" (magnitude of acceleration vector). The calculated field is set as `NAN` if any of the components (x, y or z) "equal" to `NAN`, i.e. `== NAN`. According to my ad-hoc testing [1] of the code on x86_64 this is not working as expected, as the comparison will be always false. Limited testing on ESP32 [2] seems to imply the same. As end result, the calculated acceleration field value will be nonsense when some of the acceleration components is NAN. **Does this simplified testing approach have some caveats?**
4. RuuviParseResult is storing fields as optional<float>. However, invalid values are stored as `NAN`, not as empty optional. **Is this intended behavior?** It will influence at least [publishing of values](https://github.com/esphome/esphome/blob/df853bf61ed7be05a7b7ff0722846eb3760c6a95/esphome/components/ruuvitag/ruuvitag.h#L25-L46) and [logging to Serial](https://github.com/esphome/esphome/blob/df853bf61ed7be05a7b7ff0722846eb3760c6a95/esphome/components/ruuvi_ble/ruuvi_ble.cpp#L97).

I have currently done these tests "locally" on my PC with x86_64 architecture, see [3] for the test code.

See https://github.com/esphome/esphome/compare/dev...ssalonen:esphome:dev for initial approach for a fix.

Note: to my knowledge, it is really hard (impossible?) to test these invalid values with a real sensor.

<details> <summary> [1] test code for NAN comparisons</summary>

```c++
// Test code for NAN comparison
            float floatNAN = NAN;
            esphome::optional<float> optNAN = NAN;
            std::cout << "false <=>   result.acceleration_x == NAN  result.acceleration_y == NAN  result.acceleration_z == NAN" << std::endl;

            std::cout << std::endl
                      << std::endl
                      << "NAN tests" << std::endl;
            std::cout << "float floatNAN = NAN;" << std::endl
                      << "esphome::optional<float> optNAN = NAN;" << std::endl;
            std::cout << std::endl;
            std::cout << ((optNAN == NAN) ? "true <=> optNAN == NAN" : "false <=> optNAN == NAN") << std::endl;
            std::cout << ((NAN == NAN) ? "true <=> NAN == NAN" : "false <=> NAN == NAN") << std::endl;
            std::cout << ((floatNAN == floatNAN) ? "true <=> floatNAN == floatNAN" : "false <=> floatNAN == floatNAN") << std::endl;
            std::cout << ((*optNAN == NAN) ? "true <=> *optNAN == NAN" : "false <=> *optNAN == NAN") << std::endl;
            std::cout << ((isnan(*optNAN)) ? "true <=> isnan(*optNAN)" : "false <=> isnan(*optNAN)") << std::endl;
            std::cout << ((isnan(NAN)) ? "true <=> isnan(NAN)" : "false <=> isnan(NAN)") << std::endl;
            std::cout << ((isnan(floatNAN)) ? "true <=> isnan(floatNAN)" : "false <=> isnan(floatNAN)") << std::endl;

// output (x86_64 linux, compilation with g++)

false <=> optNAN == NAN
false <=> NAN == NAN
false <=> floatNAN == floatNAN
false <=> *optNAN == NAN
true <=> isnan(*optNAN)
true <=> isnan(NAN)
true <=> isnan(floatNAN)
```

</details>

<details> <summary>[2] test code run on ESP32 to test NAN handling </summary>

```c++

#include <Arduino.h>
#include <math.h>

void setup()
{
  Serial.begin(115200);
}

void loop()
{
  Serial.println("Nan Tests\n");
  float floatNAN = NAN;
  Serial.println("float floatNAN = NAN;");
  Serial.println();
  Serial.println();
  Serial.println(((NAN == NAN) ? "true <=> NAN == NAN" : "false <=> NAN == NAN"));
  Serial.println(((floatNAN == NAN) ? "true <=> floatNAN == NAN" : "false <=> floatNAN == NAN"));
  Serial.println(((isnan(NAN)) ? "true <=> isnan(NAN)" : "false <=> isnan(NAN)"));
  Serial.println(((isnan(floatNAN)) ? "true <=> isnan(floatNAN)" : "false <=> isnan(floatNAN)"));

  delay(1000);
}

//
// ---
// output

float floatNAN = NAN;

false <=> NAN == NAN
false <=> floatNAN == NAN
true <=> isnan(NAN)
true <=> isnan(floatNAN)
```

</details>

<details> <summary>[3] test code for parsing against official test vectors in spec</summary>

```c++

// test code for parsing against official test vectors in 
// https://docs.ruuvi.com/communication/bluetooth-advertisements/data-format-5-rawv2

int main()
{
    std::cout << "Testing Ruuvi parsing";

    {
        auto result = esphome::RuuviParseResult();
        auto data = esphome::esp32_ble_tracker::adv_data_t();
        data.push_back(0x05);
        data.push_back(0x12);
        data.push_back(0xFC);
        data.push_back(0x53);
        data.push_back(0x94);
        data.push_back(0xC3);
        data.push_back(0x7C);
        data.push_back(0x00);
        data.push_back(0x04);
        data.push_back(0xFF);
        data.push_back(0xFC);
        data.push_back(0x04);
        data.push_back(0x0C);
        data.push_back(0xAC);
        data.push_back(0x36);
        data.push_back(0x42);
        data.push_back(0x00);
        data.push_back(0xCD);
        data.push_back(0xCB);
        data.push_back(0xB8);
        data.push_back(0x33);
        data.push_back(0x4C);
        data.push_back(0x88);
        data.push_back(0x4F);

        parse_ruuvi_data_byte(data, result);

        std::cout << std::endl
                  << std::endl
                  << "VALID" << std::endl;

        print_field("humidity", result.humidity);
        print_field("temperature", result.temperature);
        print_field("pressure", result.pressure);
        print_field("acceleration", result.acceleration);
        print_field("acceleration_x", result.acceleration_x);
        print_field("acceleration_y", result.acceleration_y);
        print_field("acceleration_z", result.acceleration_z);
        print_field("battery_voltage", result.battery_voltage);
        print_field("tx_power", result.tx_power);
        print_field("movement_counter", result.movement_counter);
        print_field("measurement_sequence_number", result.measurement_sequence_number);
    }

    {
        auto result = esphome::RuuviParseResult();
        auto data = esphome::esp32_ble_tracker::adv_data_t();
        data.push_back(0x05);
        data.push_back(0x7F);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFE);
        data.push_back(0xFF);
        data.push_back(0xFE);
        data.push_back(0x7F);
        data.push_back(0xFF);
        data.push_back(0x7F);
        data.push_back(0xFF);
        data.push_back(0x7F);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xDE);
        data.push_back(0xFE);
        data.push_back(0xFF);
        data.push_back(0xFE);
        data.push_back(0xCB);
        data.push_back(0xB8);
        data.push_back(0x33);
        data.push_back(0x4C);
        data.push_back(0x88);
        data.push_back(0x4F);

        parse_ruuvi_data_byte(data, result);

        std::cout << std::endl
                  << std::endl
                  << "MAX" << std::endl;

        print_field("humidity", result.humidity);
        print_field("temperature", result.temperature);
        print_field("pressure", result.pressure);
        print_field("acceleration", result.acceleration);
        print_field("acceleration_x", result.acceleration_x);
        print_field("acceleration_y", result.acceleration_y);
        print_field("acceleration_z", result.acceleration_z);
        print_field("battery_voltage", result.battery_voltage);
        print_field("tx_power", result.tx_power);
        print_field("movement_counter", result.movement_counter);
        print_field("measurement_sequence_number", result.measurement_sequence_number);
    }

    {
        auto result = esphome::RuuviParseResult();
        auto data = esphome::esp32_ble_tracker::adv_data_t();
        data.push_back(0x05);
        data.push_back(0x80);
        data.push_back(0x01);
        data.push_back(0x00);
        data.push_back(0x00);
        data.push_back(0x00);
        data.push_back(0x00);
        data.push_back(0x80);
        data.push_back(0x01);
        data.push_back(0x80);
        data.push_back(0x01);
        data.push_back(0x80);
        data.push_back(0x01);
        data.push_back(0x00);
        data.push_back(0x00);
        data.push_back(0x00);
        data.push_back(0x00);
        data.push_back(0x00);
        data.push_back(0xCB);
        data.push_back(0xB8);
        data.push_back(0x33);
        data.push_back(0x4C);
        data.push_back(0x88);
        data.push_back(0x4F);

        parse_ruuvi_data_byte(data, result);

        std::cout << std::endl
                  << std::endl
                  << "MIN" << std::endl;

        print_field("humidity", result.humidity);
        print_field("temperature", result.temperature);
        print_field("pressure", result.pressure);
        print_field("acceleration", result.acceleration);
        print_field("acceleration_x", result.acceleration_x);
        print_field("acceleration_y", result.acceleration_y);
        print_field("acceleration_z", result.acceleration_z);
        print_field("battery_voltage", result.battery_voltage);
        print_field("tx_power", result.tx_power);
        print_field("movement_counter", result.movement_counter);
        print_field("measurement_sequence_number", result.measurement_sequence_number);
    }
    {
        auto result = esphome::RuuviParseResult();
        auto data = esphome::esp32_ble_tracker::adv_data_t();
        data.push_back(0x05);
        data.push_back(0x80);
        data.push_back(0x00);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0x80);
        data.push_back(0x00);
        data.push_back(0x80);
        data.push_back(0x00);
        data.push_back(0x80);
        data.push_back(0x00);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);
        data.push_back(0xFF);

        parse_ruuvi_data_byte(data, result);

        std::cout << std::endl
                  << std::endl
                  << "INVALID" << std::endl;

        print_field("humidity", result.humidity);
        print_field("temperature", result.temperature);
        print_field("pressure", result.pressure);
        print_field("acceleration", result.acceleration);
        print_field("acceleration_x", result.acceleration_x);
        print_field("acceleration_y", result.acceleration_y);
        print_field("acceleration_z", result.acceleration_z);
        print_field("battery_voltage", result.battery_voltage);
        print_field("tx_power", result.tx_power);
        print_field("movement_counter", result.movement_counter);
        print_field("measurement_sequence_number", result.measurement_sequence_number);

   }
}
```

</details>

### Which version of ESPHome has the issue?

dev branch 4d56a975e6fc2521dc77af656f056ef8bd6f119c

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

ruuvi_ble

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

**Initial fix** here https://github.com/esphome/esphome/compare/dev...ssalonen:esphome:dev This is _not_ changing the optional behaviour (point 4) and we still would store NANs in optional.

### PR DESCRIPTION
**Pull request by ssalonen**
# What does this implement/fix?

With Ruuvi BLE advertisements: Fixes NA value handling of signed fields (temperature, acceleration). Added NA value handling of `movement_counter` and `measurement_sequence_number`.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/3489

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Checklist:
  - [ ] The code change is tested and works locally.
  -- not feasible to test locally (NA values are rare in practice). Need guidance or testers to check that valid values are still parsed correctly.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  -- not applicable? Or is it possible to introduce c++ unit tests there?

If user exposed functionality or configuration variables are added/changed: Not applicable, no changes like that.
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by ssalonen** [comment]
CI passed and ruuvi is part of test2.yml. If I understand the CI setup correctly, this means that compilation succeeded with the changes.

With this, I am fairly confident that changes are safe but would not mind second pair of eyes to have a code review.

**Comment by ssalonen** [comment]
Not stale

**Comment by jesserockz** [comment]
Changes look fine. Can you attach a raw data dump of a normal and an advertisement that has invalid readings?

**Comment by ssalonen** [comment]
Unfortunately that is not possible, this is really a cornercase

**Pull request closed without merging**
