### PR TITLE
[rotary_encoder] Fix volatile increment/decrement deprecation warnings

### PR DESCRIPTION
**Pull request by edwardtfn**
# What does this implement/fix?

Similar to the [pulse counter fix](https://github.com/esphome/esphome/pull/7954), this PR addresses warnings about deprecated use of increment/decrement operators on volatile-qualified types in the rotary encoder component. 

The warnings being fixed are:
```log
- warning: '++' expression of 'volatile'-qualified type is deprecated [-Wvolatile]
- warning: '--' expression of 'volatile'-qualified type is deprecated [-Wvolatile]
```

Changes:
- Keep the volatile qualifier as it's important for interrupt context
- Replace increment/decrement operations with load/store approach

This is a similar change to #7954 (pulse counter fix) but for the rotary encoder component.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by clydebarrow — CHANGES_REQUESTED** [review]
* Using `InterruptLock` _inside_ an interrupt is pointless;
* The warnings about ++ are probably spurious in this context since on any of the target chips the increment should compile to an atomic operation.
* The `volatile` qualifier is important since it alerts the compiler that the value may change unexpectedly.

I would suggest reverting the changes and simply suppressing the warning with a pragma.

The other option would be to use `std::atomic` or similar but I don't know if that is supported across the platforms, and would be a performance hit.

There are discussions on the net about the inappropriateness of recent C++ changes deprecating compound operations on volatile objects, with a lack of appreciation for their use in embedded applications.

**Comment by clydebarrow** [comment]
Alternatively (and more cleanly) load the value +1 into an auto variable then store it back. The load and store are each guaranteed to be atomic and will avoid the warning.
```
    if (arg->counter < arg->max_value) {
      auto x = arg->counter +1;
      arg->counter = x;
    }
```

**Comment by edwardtfn** [comment]
Ok, I will look at that.
It should be the same for #7954 as that is exactly the same case. I will review both later today or tomorrow morning. 😉

**Comment by edwardtfn** [comment]
Done!
On both this one and also #7954.

**Review by clydebarrow — APPROVED** [review]

**Pull request merged**
