### PR TITLE
Add 2.13in-ttgo-b1 waveshare epaper module.

### LINKED ISSUE #1187: Waveshare TTGO-T5 2.13 EPaper Display Does Not Display
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Installed via pip3, version 1.14.3

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 (Lilygo T5 v2.3)

**Affected component:**

https://esphome.io/components/display/waveshare_epaper.html?highlight=waveshare

**Description of problem:**
I'm unable to convince the ePaper to display anything on this device. Using esphome 1.14.3.   It all seems to build and start fine, but I dont see any change to the display, nor anything in the logs indicating a problem.  It seems to be fine, but nothing outputs to the epaper (which I've tried to write with other tools and works fine). I'm using the 2.3 pinouts described here: https://github.com/Xinyuan-LilyGO/T5-Ink-Screen-Series which matches the info silkscreened onto the board.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: textdisplay
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "XXXX"
  password: "XXXX"

# Enable logging
logger:
  level: VERBOSE

ota:

time:
  - platform: sntp
    id: sntp_time

spi:
  clk_pin: 18
  mosi_pin: 23

font:
  - file: "FiveByFive.ttf"
    id: five8
    size: 8

display:
  - platform: waveshare_epaper
    cs_pin: 5
    dc_pin: 17
    busy_pin: 4
    reset_pin: 16
    model: 2.13in-ttgo
    full_update_every: 2
    update_interval: 5s
    lambda: |-
      it.strftime(0, 0, id(five8), "%Y-%m-%d %H:%M", id(sntp_time).now());


```

**Logs (if applicable):**

```
INFO Successfully uploaded program.
INFO Starting log output from /dev/cu.SLAB_USBtoUART with baud rate 115200
[14:10:35][I][logger:156]: Log initialized
[14:10:35][C][ota:364]: There have been 3 suspected unsuccessful boot attempts.
[14:10:35][I][app:028]: Running through setup()...
[14:10:35][V][app:029]: Sorting components by setup priority...
[14:10:35][C][spi:020]: Setting up SPI bus...
[14:10:36][C][wifi:033]: Setting up WiFi...
[14:10:36][V][wifi_esp32:033]: Enabling STA.
[14:10:36][V][esp-idf:000]: I (451) wifi: wifi driver task: 3ffafbe8, prio:23, stack:3584, core=0
[14:10:36][V][esp-idf:000]: I (1072) wifi: wifi firmware version: 7997e4b
[14:10:36][V][esp-idf:000]: I (1073) wifi: config NVS flash: enabled
[14:10:36][V][esp-idf:000]: I (1074) wifi: config nano formating: disabled
[14:10:36][V][esp-idf:000]: I (1081) wifi: Init dynamic tx buffer num: 32
[14:10:36][V][esp-idf:000]: I (1087) wifi: Init data frame dynamic rx buffer num: 32
[14:10:36][V][esp-idf:000]: I (1095) wifi: Init management frame dynamic rx buffer num: 32
[14:10:36][V][esp-idf:000]: I (1103) wifi: Init management short buffer num: 32
[14:10:36][V][esp-idf:000]: I (1110) wifi: Init static rx buffer size: 1600
[14:10:36][V][esp-idf:000]: I (1117) wifi: Init static rx buffer num: 16
[14:10:36][V][esp-idf:000]: I (1123) wifi: Init dynamic rx buffer num: 32
[14:10:36][V][esp-idf:000]: I (1200) wifi: mode : softAP (a4:cf:12:24:93:71)
[14:10:36][V][esp-idf:000]: I (1201) wifi: Total power save buffer number: 16
[14:10:36][V][esp-idf:000]: I (1203) wifi: Init max length of beacon: 752/752
[14:10:36][V][esp-idf:000]: I (1210) wifi: Init max length of beacon: 752/752
[14:10:36][D][WiFiGeneric.cpp:337] _eventCallback(): Event: 0 - WIFI_READY
[14:10:36][D][WiFiGeneric.cpp:337] _eventCallback(): Event: 14 - AP_STOP
[14:10:36][V][wifi_esp32:357]: Event: WiFi AP start
[14:10:36][V][wifi_esp32:302]: Event: WiFi ready
[14:10:36][V][esp-idf:000]: I (1238) wifi: mode : sta (a4:cf:12:24:93:70)
[14:10:36][D][WiFiGeneric.cpp:337] _eventCallback(): Event: 2 - STA_START
[14:10:36][V][wifi_esp32:311]: Event: WiFi STA start
[14:10:36][D][WiFiGeneric.cpp:337] _eventCallback(): Event: 2 - STA_START
[14:10:36][V][esp-idf:000]: I (1260) wifi: Set ps type: 1
[14:10:36]
[14:10:36][D][wifi:304]: Starting scan...
[14:10:38][D][WiFiGeneric.cpp:337] _eventCallback(): Event: 1 - SCAN_DONE
[14:10:38][V][wifi_esp32:307]: Event: WiFi Scan Done status=0 number=27 scan_id=128
[14:10:38][D][wifi:319]: Found networks:
<snip>
[14:10:38][I][wifi:193]: WiFi Connecting to 'XXXX'...
[14:10:38][V][wifi:195]: Connection Params:
[14:10:38][V][wifi:196]:   SSID: 'XXXXX'
[14:10:38][V][wifi:199]:   BSSID: XXXX
[14:10:38][V][wifi:203]:   Password: 'XXXX'
[14:10:38][V][wifi:205]:   Channel: 6
[14:10:38][V][wifi:215]:   Using DHCP IP
[14:10:38][V][wifi:217]:   Hidden: NO
[14:10:38][V][esp-idf:000]: I (3498) wifi: n:6 0, o:1 0, ap:255 255, sta:6 0, prof:1
[14:10:39][V][esp-idf:000]: I (4233) wifi: state: init -> auth (b0)
[14:10:39][V][esp-idf:000]: I (4242) wifi: state: auth -> assoc (0)
[14:10:39][V][esp-idf:000]: I (4250) wifi: state: assoc -> run (10)
[14:10:39][V][esp-idf:000]: I (4270) wifi: connected with XXXXX, channel 6, BW20
[14:10:39][V][esp-idf:000]: I (4271) wifi: pm start, type: 1
[14:10:39]
[14:10:39][D][WiFiGeneric.cpp:337] _eventCallback(): Event: 4 - STA_CONNECTED
[14:10:39][V][wifi_esp32:324]: Event: Connected ssid='XXXX' bssid=XXXX channel=6, authmode=WPA2 PSK
[14:10:39][D][WiFiGeneric.cpp:337] _eventCallback(): Event: 7 - STA_GOT_IP
[14:10:39][D][WiFiGeneric.cpp:381] _eventCallback(): STA IP: 192.168.0.122, MASK: 255.255.255.0, GW: 192.168.0.1
[14:10:39][V][wifi_esp32:349]: Event: Got IP static_ip=192.168.0.122 gateway=192.168.0.1
[14:10:39][I][wifi:423]: WiFi Connected!
[14:10:39][C][wifi:283]:   SSID: 'XXXX'
[14:10:39][C][wifi:284]:   IP Address: 192.168.0.122
[14:10:39][C][wifi:286]:   BSSID: XXXXXXXXXX
[14:10:39][C][wifi:287]:   Hostname: 'textdisplay'
[14:10:39][C][wifi:291]:   Signal strength: -53 dB ▂▄▆█
[14:10:39][V][wifi:293]:   Priority: 0.0
[14:10:39][C][wifi:295]:   Channel: 6
[14:10:39][C][wifi:296]:   Subnet: 255.255.255.0
[14:10:39][C][wifi:297]:   Gateway: 192.168.0.1
[14:10:39][C][wifi:298]:   DNS1: 192.168.0.1
[14:10:39][C][wifi:299]:   DNS2: 0.0.0.0
[14:10:39][C][ota:029]: Over-The-Air Updates:
[14:10:39][C][ota:030]:   Address: textdisplay.local:3232
[14:10:39][W][ota:036]: Last Boot was an unhandled reset, will proceed to safe mode in 7 restarts
[14:10:39][C][sntp:017]: Setting up SNTP...
[14:10:39][I][app:058]: setup() finished successfully!
[14:10:39][I][app:100]: ESPHome version 1.14.3 compiled on Apr 30 2020, 14:10:04
[14:10:39][C][wifi:415]: WiFi:
[14:10:39][C][wifi:283]:   SSID: 'XXXX'
[14:10:39][C][wifi:284]:   IP Address: 192.168.0.122
[14:10:39][C][wifi:286]:   BSSID: 82:2A:A8:14:19:B3
[14:10:39][C][wifi:287]:   Hostname: 'textdisplay'
[14:10:39][C][wifi:291]:   Signal strength: -53 dB ▂▄▆█
[14:10:39][V][wifi:293]:   Priority: 0.0
[14:10:39][C][wifi:295]:   Channel: 6
[14:10:39][C][wifi:296]:   Subnet: 255.255.255.0
[14:10:39][C][wifi:297]:   Gateway: 192.168.0.1
[14:10:39][C][wifi:298]:   DNS1: 192.168.0.1
[14:10:39][C][wifi:299]:   DNS2: 0.0.0.0
[14:10:39][C][spi:079]: SPI bus:
[14:10:39][C][spi:080]:   CLK Pin: GPIO18 (Mode: OUTPUT)
[14:10:39][C][spi:082]:   MOSI Pin: GPIO23 (Mode: OUTPUT)
[14:10:39][C][spi:083]:   Using HW SPI: YES
[14:10:39][D][sntp:059]: Synchronized time: Thu Apr 30 14:10:39 2020
[14:10:39][C][logger:175]: Logger:
[14:10:39][C][logger:176]:   Level: VERBOSE
[14:10:39][C][logger:177]:   Log Baud Rate: 115200
[14:10:39][C][logger:178]:   Hardware UART: UART0
[14:10:39][C][waveshare_epaper:161]: Waveshare E-Paper
[14:10:39][C][waveshare_epaper:161]:   Rotations: 0 °
[14:10:39][C][waveshare_epaper:161]:   Dimensions: 128px x 250px
[14:10:39][C][waveshare_epaper:170]:   Model: 2.13in (TTGO)
[14:10:39][C][waveshare_epaper:176]:   Full Update Every: 2
[14:10:39][C][waveshare_epaper:177]:   Reset Pin: GPIO16 (Mode: OUTPUT)
[14:10:39][C][waveshare_epaper:178]:   DC Pin: GPIO17 (Mode: OUTPUT)
[14:10:39][C][waveshare_epaper:179]:   Busy Pin: GPIO4 (Mode: INPUT)
[14:10:39][C][waveshare_epaper:180]:   Update Interval: 5.0s
[14:10:39][C][ota:029]: Over-The-Air Updates:
[14:10:39][C][ota:030]:   Address: textdisplay.local:3232
[14:10:39][C][sntp:043]: SNTP Time:
[14:10:39][C][sntp:044]:   Server 1: '0.pool.ntp.org'
[14:10:39][C][sntp:045]:   Server 2: '1.pool.ntp.org'
[14:10:39][C][sntp:046]:   Server 3: '2.pool.ntp.org'
[14:10:39][C][sntp:047]:   Timezone: 'PST8PDT7,M3.2.0/2,M11.1.0/2'

```

**Additional information and things you've tried:**

It seems to be fine, but nothing outputs to the epaper (which I've tried to write with other tools and works fine).

### PR DESCRIPTION
**Pull request by matikij**
## Description:

It seems that there are 3 different versions of the ttgo T5 with 2.13 inch epaper module:

https://github.com/ZinggJM/GxEPD2/blob/master/src/epd/GxEPD2_213_B72.cpp#L347 LUT looks like the one in `2.13in-ttgo`
https://github.com/ZinggJM/GxEPD2/blob/master/src/epd/GxEPD2_213_B73.cpp#L348 LUT looks like the one in `2.13in-ttgo-b73`
https://github.com/ZinggJM/GxEPD2/blob/master/src/epd/GxEPD2_213.cpp#L341 - this looks like nothing in esphome, and unfortunately I seem to have this one :-)

My initial idea was to just use the GxEPD2 library, but it proved too much of a challenge, so I added another waveshare epaper model

During my experiments it turned out that not only the LUT is missing, but also that this particular version seems to only like `0x01` data mode (opposed to `0x03`), which starts at bottom-left and ends at top right (x increase and y decrease), hence the need of a couple of switch statements. 

Also, screen redraw takes more than 1 second, so I had to override `idle_timeout_()` method for this particular model.

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/1187

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** https://github.com/esphome/esphome-docs/pull/808

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder). - not sure if this is enough

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by matikij** [comment]
Don't really know what to do with the remaining linter errors: as `idle_timeout_()` was already there. I guess I can try silencing the linter about this one.

**Comment by jesserockz** [comment]
@matikij Can you merge the latest dev branch in and resolve the conflicts, then this should be good to merge. Sorry for the delay

**Comment by matikij** [comment]
Done

**Comment by matikij** [comment]
Bump ?

**Comment by nikito7** [comment]
@matikij check this https://github.com/esphome/issues/issues/1458#issuecomment-802322957

New panel. B1?

**Review by nikito7 — APPROVED** [review]

**Review by nikito7 — APPROVED** [review]
B73 still work :-)

**Comment by matikij** [comment]
> @matikij check this [esphome/issues#1458 (comment)](https://github.com/esphome/issues/issues/1458#issuecomment-802322957)
> 
> New panel. B1?

Seems to be a ew panel: B74 https://www.good-display.com/product/375.html
created a feature request here: esphome/feature-requests#1167

**Comment by nikito7** [comment]
2 failing checks

**Comment by jesserockz** [comment]
Please run the black formatter locally and move the test to a different test file (we are still working out the best way to solve the forever growing test files)

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
