### PR TITLE
Add support for Tuya Climate devices

### PR DESCRIPTION
**Pull request by jesserockz**
## Description:
This starts to add support for Tuya based Climate devices.

It starts with heat only as I only have a heater.

There is commented code for `eco_mode` (which my heater supports) but that relies on #1075

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#632

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by KiLLeRRaT** [comment]
Hi @jesserockz, Looking forward to this.  I see you're from NZ too (and I also use Sharesight by the way! Awesome product).  Which heater are you using for this? 

I have a Goldair GECO270 which is TUYA.  I'm using the a Home Assistant integration with this which works through the TUYA apis/cloud.  It'd be great to get a ESPHome setup working, so that I can get rid of the whole TUYA cloud stuff... 

I guess I'd have to use TUYA Convert to flash it with ESPHome.  Is that what you did with your heater? Or did you solder headers on to use FTDI to flash?

Cheers,

**Comment by jesserockz** [comment]
> Hi @jesserockz, Looking forward to this.  I see you're from NZ too (and I also use Sharesight by the way! Awesome product).  Which heater are you using for this? 
> 
> I have a Goldair GECO270 which is TUYA.  I'm using the a Home Assistant integration with this which works through the TUYA apis/cloud.  It'd be great to get a ESPHome setup working, so that I can get rid of the whole TUYA cloud stuff... 
> 
> I guess I'd have to use TUYA Convert to flash it with ESPHome.  Is that what you did with your heater? Or did you solder headers on to use FTDI to flash?
> 
> Cheers,
> 
> 

Hi @KiLLeRRaT 

I have the Kogan 2000W smart heater.

I believe they are all mostly the same, the only differences might be the datapoint IDs that you need but they are quite easy to guess once you set up the basic `tuya` component.

I use tuya-convert with no issues at all.
It works fantastically though once running esphome.

If you use the **Dev** version of the esphome Home-assistant Add-on you can set the configuration to:
```
esphome_version: 'jesserockz:kogan-heater'
```
If you want to try it out before it is merged. 

My branch also has code for tuya switches and sensors that are not specifically climate like the child lock (if needed).

Jesse

**Comment by whighway** [comment]
Hey @jesserockz , I also have a tuya-converted heater, I started creating switches and sensors myself but came accross your implementation, you're a bit further (also with the climate code) so I will continue building on your code. My heater (https://eurom.nl/en/product/heating/convectors/alutherm-2000-wifi/) has some slightly different features than yours the way it looks,
particularly mine has a a "manual" and "program" mode, and 3 (actually 4) heating levels: low, mid, high and off. in manual mode it is possible to set the heating level yourself, opening the posibility to not use the heater's internal thermostat logic, but create own logic to set the heating level based on a different temperature sensor in the room (the internal sensor in my heater tends to show too high values as it is quickly influenced by the heat of the heater)
Does your heater have these options as well? I'd like to see how we can create a generic tuya climate that works for all tuya heaters.
Also, my heater has a date/time display and the MCU asks for the time every 10 seconds.. gotta try to find out how to send date/time back to the mcu.
Anyway, I'll try your code and compare against mine. I also created a text_tensor to show the heating level enum with their friendly names

**Comment by jesserockz** [comment]
Hi @whighway, My heater does not have that functionality. It does have eco/conservative mode and off which could be a dynamic set of `heating_modes` you could put in the yaml, but to get these into HA, the actual `climate` component needs to support it.

What does the `tuya: ` component dump for the datapoints available on your heater?

**Comment by whighway** [comment]
@jesserockz my datapoints are
```
[11:27:14][C][tuya:032]:   Datapoint 1: switch (value: ON)
[11:27:14][C][tuya:034]:   Datapoint 2: int value (value: 13)
[11:27:14][C][tuya:034]:   Datapoint 3: int value (value: 17)
[11:27:14][C][tuya:036]:   Datapoint 4: enum (value: 1)
[11:27:14][C][tuya:036]:   Datapoint 101: enum (value: 3)
[11:27:14][C][tuya:032]:   Datapoint 102: switch (value: OFF)
```
1 = switch
2 = target temp
3 = current temp
4 = operation mode (1 = auto/program)
101 = heating level (3 = off)
102 = eco mode switch

**Comment by jesserockz** [comment]
Mine is:

```
[22:07:15][C][tuya:023]: Tuya:
[22:07:15][C][tuya:032]:   Datapoint 1: switch (value: OFF)
[22:07:15][C][tuya:032]:   Datapoint 2: switch (value: OFF)
[22:07:15][C][tuya:034]:   Datapoint 3: int value (value: 20)
[22:07:15][C][tuya:034]:   Datapoint 4: int value (value: 14)
[22:07:15][C][tuya:034]:   Datapoint 5: int value (value: 0)
[22:07:15][C][tuya:036]:   Datapoint 7: enum (value: 1)
```

1 = power switch
2 = key/child lock switch
3 = target temp
4 = current temp
5 = countdown timer in mins
7 = eco mode switch (not sure why its an enum, maybe it should be the heating level)

**Comment by whighway** [comment]
Ah, my eco mode works differenty; it sets the target temperature to 16 degrees and control-mode to auto.
so in that sense your dp 7 looks more like my 101 (heating level).

hmmm I think the climate component could actually do with a more generic 'preset mode' like in HA. it now has explicit "away", but that could be just a preset like eco mode. anyway, i see your pull request for the eco mode and that looks fine I will use that too.. 

I'll work on a branch of your code and try to add my functionality as optional and generically as possible

**Comment by jesserockz** [comment]
Yeah looks like it, I just use my Eco mode with a switch at the moment. 

There was a discussion on an issue somewhere about the preset modes, and also on discord. I think esphome should be defining them for HA and not just the away mode but that requires a lot more work.

**Pull request merged**
