### PR TITLE
Media Player: added triggers

### PR DESCRIPTION
**Pull request by dudanov**
# What does this implement/fix?

`on_state`, `on_idle`, `on_play`, `on_pause` triggers

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2142

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example configuration entry
media_player:
  - platform: i2s_audio
    name: '${friendly_name}'
    mode: mono
    dac_type: external
    i2s_lrclk_pin: GPIO33
    i2s_dout_pin: GPIO27
    i2s_bclk_pin: GPIO26
    on_state:
      - light.turn_on:
          id: led_status
          flash_length: 50ms
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by mmakaay** [comment]
What would make the trigger more useful, is when it would make the new state accessible from the trigger handling actions. For example to turn on a lamp when the state is `PLAYING`, while other states would turn off the lamp.

Could you look into implementing that?

**Comment by dudanov** [comment]
> What would make the trigger more useful, is when it would make the new state accessible from the trigger handling actions. For example to turn on a lamp when the state is `PLAYING`, while other states would turn off the lamp.
> 
> Could you look into implementing that?

Of course, I can implement separate triggers for all states, but you can use lambdas for this.

**Comment by mmakaay** [comment]
Separate triggers would work too. They can all be built on top of the same callback.

For an example setup, see [the OTA automation triggers](https://esphome.io/components/ota.html#on-state-change) which provide both specific triggers per state, and a general `on_state_change` trigger (maybe adopt this trigger name here too?) that gets a `state` variable that can be inspected.

**Review by jesserockz — APPROVED** [review]
Thanks!

**Pull request merged**
