### PR TITLE
Add rc522

### LINKED ISSUE #37: Support RC522
It's a great 1.8.0 release and the support for NFC readers is a great addition.
I wondered if you plan to support the RC522 as well?

### PR DESCRIPTION
**Pull request by glmnet**
## Description:

Well, an old request... 

should work like `pn532`

you might need to wire the reset pin, I did not mark it optional yet. More test is needed:

```yaml
 rc522_spi:
  cs_pin: D8
  reset_pin: D3
```

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/37

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#810

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
Can I suggest you name this component `rc522_spi` as the chip also supports I2C and UART so down the line it would be easier to add them as components too without renaming...
Similar to what I am doing for the `pn532` in #1302

**Review by jesserockz — APPROVED** [review]
Awesome, I will give this a go soon

**Comment by jesserockz** [comment]
Works for me - same tag on both readers on same d1 mini
```
[12:24:17][D][pn532:149]: Found new tag 'B4-B4-C1-DD'
[12:24:19][D][rc522_spi:159]: Found new tag 'B4-B4-C1-DD'
```

**Comment by rcxrbt** [comment]
Hi all,
 i m interested to useRC522 on ESPHOME. Where i can find code?

**Comment by jesserockz** [comment]
> Hi all,
>  i m interested to useRC522 on ESPHOME. Where i can find code?

Hello, you can use it via the dev branch and docs at https://next.esphome.io/components/binary_sensor/rc522.html

**Comment by rcxrbt** [comment]
> > Hi all,
> > i m interested to useRC522 on ESPHOME. Where i can find code?
> 
> Hello, you can use it via the dev branch and docs at https://next.esphome.io/components/binary_sensor/rc522.html

tnx!

Follow pinout are suitable for ESP 8266?

_`spi:
  clk_pin: D0
  miso_pin: D1
  mosi_pin: D2
  
rc522_spi:
  cs_pin: D8
  reset_pin: D3
  update_interval: 1s
  on_tag:
    then:
      - homeassistant.tag_scanned: !lambda 'return x;'`_

**Comment by rcxrbt** [comment]
My logs:

> [00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:53:59][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error
[00:54:00][E][rc522_spi:122]: Error

**Comment by jesserockz** [comment]
@rcxrbt please join discord for easier support https://discord.gg/S7q6vEBA

**Comment by Aterfax** [comment]
If / when this gets refactored so it works without the logging level set to being VERBOSE hmu and I can test it.

**Pull request merged**
