### PR TITLE
Tests for CPP Code generation and some Python3 improvements

### PR DESCRIPTION
**Pull request by timsavage**
## Description:
Next set of test cases to cover code generation.

Also has improvements to code for Python 3
- Improved annotations
- Some improved docs and exceptions (and messages)

**Related issue (if applicable):** fixes more tests!

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by brandond** [comment]
Are you still working on this @timsavage ?

**Comment by timsavage** [comment]
This PR is dependant on the earlier testing PR. Left as WIP until that was merged.

**Comment by brandond** [comment]
Just merged #931. Is this ready to go now or did you want to add more before we merge?

**Comment by timsavage** [comment]
I'll give it review is a couple of months old now. I'll likely open another PR to cover the tests that where failing (as documented in #931) so they can be integrated into the Travis build pipeline.

**Comment by timsavage** [comment]
I've given it a review and I'll add a few (dozen) more tests to ensure complete coverage of code-gen. Should get the total up to ~25%. Once the tests are in place, the project will be in a good place to modernize some of the async code away from using `@coroutine` to `async def`.

**Comment by timsavage** [comment]
I've called it for now, test coverage is now over 24%.

The cpp_helpers code I couldn't quite identify (well didn't have time to trace through) behaviour and what rests are required for rest of the methods.

**Comment by glmnet** [comment]
LGTM

**Pull request merged**
