### PR TITLE
Add support for led matrices

### PR DESCRIPTION
**Pull request by DerrickGibbs1**
## Description:

Add support for led matrices that are supported by [pxmatrix](https://github.com/2dom/PxMatrix). I'm still working on adding documentation and tests I just wanted to post this here to get some feedback on the code. Currently this code only supports one color, I plan on adding configuration for on/off colors unless there are plans to add full color support to the display rendering engine.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs pending...

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by rspaargaren** [comment]
This is an interesting component to add support! Hi your pull request draw my attention as I have worked on the a small led display based on the max7219 chip. I have not fully reviewed your code.
Some first “issue” I see is that your code is fully depending on an external library which contains also a SPI driver this can conflict with the SPI driver within esphome. So most probably to get fully integrated in esphome you need to use that driver.
Also you need to enable the user to configure the pins via the yaml file. So you have to set the parameters in the python file.

**Comment by glmnet** [comment]
Colors support just got merged, in case you want to review and update your code.

**Comment by DerrickGibbs1** [comment]
Good to hear! I'll take a look at adding the color support in as well as rspaargaren's suggestions.

**Comment by jpoles1** [comment]
I think this is a great idea! Very interested in trying to employ it for one of my projects, but I've his a bit of a dead end, is there any way to get it working on a live version of ESPHOME before these changes get merged in?

**Pull request closed without merging**
