### PR TITLE
dfrobot_sen0395: Use setLatency instead of outputLatency

### PR DESCRIPTION
**Pull request by jfroy**
# What does this implement/fix?

The `outputLatency` command does not properly set the detect (on) latency. See https://github.com/esphome/esphome/pull/4203#issuecomment-1370804752.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** #4203

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** TODO

## Test Environment

- [ ] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
external_components:
  - source: github://pr#5663
    components: [ dfrobot_mmwave_radar ]

uart:
  - id: uart_mmwave
    tx_pin: 14
    rx_pin: 27
    baud_rate: 115200

dfrobot_mmwave_radar:
    - id: mmwave
      uart_id: uart_mmwave

binary_sensor:
  - platform: dfrobot_mmwave_radar
    name: Mmwave Detected UART

  - platform: gpio
    name: Mmwave Detected GPIO
    device_class: motion
    pin:
      number: 13
      mode: INPUT_PULLDOWN

button:
  - platform: template
    name: "Update Settings"
    on_press:
      - dfrobot_mmwave_radar.settings:
          # id: mmwave
          factory_reset: true
          detection_segments:
            - [0cm, 3m]
          output_latency:
            delay_after_detect: 0s
            delay_after_disappear: 0s
          start_after_power_on: true
          turn_on_led: false
          presence_via_uart: true
          sensitivity: 7
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jfroy** [comment]
Also @EverythingSmartHome

**Comment by jfroy** [comment]
Also @jesserockz.

**Review by jesserockz — APPROVED** [review]

**Comment by jfroy** [comment]
I think breaking-change can be removed. This component has not been released yet.

**Comment by niklasweber** [comment]
Thanks for this contribution! The code looks good to me! However, I tested it, and it still behaves like before. The delay after detection doesn't work. Only after disappearing. The setLatency command is properly sent and the sensor responds with Done. But somehow it still has no effect. Does anyone else have the same problem? @jesserockz @EverythingSmartHome

**Comment by jfroy** [comment]
> Thanks for this contribution! The code looks good to me! However, I tested it, and it still behaves like before. The delay after detection doesn't work. Only after disappearing. The setLatency command is properly sent and the sensor responds with Done. But somehow it still has no effect. Does anyone else have the same problem? @jesserockz @EverythingSmartHome

I'll do some testing with the stock esphome firmware for EPOne. What settings did you use? Maybe it's very picky about values it actually accepts. Or it may depend on other settings.

I did some testing before submitting with "5.000 15.000" (eg 5 s on delay, 15 s off delay) and it seemed to work.

**Comment by EverythingSmartHome** [comment]
I agree that I found outputLatency didn't work for me despite the manual saying it should, it seemed to ignore the on latency value.

Though to be fair it was about a year ago last time I did any digging on it.

setLatency was the one that I also ended using too and that's been working great. I can give this code a test tomorrow and check my results

**Comment by niklasweber** [comment]
I tested with various numbers between 0 and 60s
image

**Pull request merged**
