### PR TITLE
Fix unexpected disconnects when outgoing buffer is full during keepalive

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

Screenshot 2023-12-21 at 4 26 10 PM

```
64 bytes from 192.168.107.104: icmp_seq=5026 ttl=64 time=4.007 ms
Request timeout for icmp_seq 5027
Request timeout for icmp_seq 5028
Request timeout for icmp_seq 5029
64 bytes from 192.168.107.104: icmp_seq=5030 ttl=64 time=4.111 ms
64 bytes from 192.168.107.104: icmp_seq=5031 ttl=64 time=4.491 ms
```

The retries correspond with the drop outs

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
Not sure if this should log at `W` when the send fails, OTOH, this previously meant the connection was going to drop before, and there is no other indication packets are being dropped

**Comment by bdraco** [comment]
connection is stable now. 

It wouldn't stay up for more than 10 minutes before without disconnecting

**Review by jesserockz — APPROVED** [review]
LGTM

**Comment by bdraco** [comment]
Most failures I see is 6 so hopefully nobody gets warnings unless its really really bad

Screenshot 2023-12-21 at 4 31 13 PM

**Pull request merged**
