### PR TITLE
Add the ability to manually set unique_object_id for unique_id generation, instead of using name

### LINKED ISSUE #1741: Request for friendly name for ESPHOME devices to use HA feature to reduce entity names
**Describe the problem you have/What new integration you would like**
I can assign the esphome device a name with: 

```
substitutions:
  upper_devicename: "Lampe Aussen Hausbeleuchtung"
  devicename: "lampe-aussen-hausbeleuchtung" #(upper case and space not allowed)
esphome:
  name: $devicename
```

but I cannot assign a friendly name for Home Assistant: 
`friendly_name: ${upper_devicename} #--> doesn't work`

If I give e.g. a light entity a name: 
```
light:
  - platform: binary
[...]
    name: "${upper_devicename} Balkon"
```

It doesn't show the right way in Home Assistant: 
image

If I rename the device name into the "friendly one" it works: 
image

So it would be nice to have a "friendly" device name with uppercase and spaces via the yaml code. That way the look in HA would be much cleaner

### Anything in the logs that might be useful for us?

```txt
nothing
```

**Additional context**
It would be an alternative, if the `esphome name` accepts upper case and spaces and translates to lowe case and "-" were needed.

If you would be able to set an uppercase device name via the yaml you can make use of the truncating in Home Assistant (would be much clearer)
**Please describe your use case for this integration and alternatives you've tried:**

Example YAML snippet
```yaml
substitutions:
  upper_devicename: "Lampe Aussen Hausbeleuchtung"
  devicename: "lampe-aussen-hausbeleuchtung"

esphome:
  name: $devicename
#  friendly_name: ${upper_devicename} --> missing?

light:
  - platform: binary
    id: light1
    output: relay1
    name: "${upper_devicename} Balkon"
```

### PR DESCRIPTION
**Pull request by arduanov**
# What does this implement/fix?
Add new optional parameter `object_id` in Components. This Object Id is used instead sanitized name of component in MQTT and HA integrations.

This fixes several issues:
1. Safe rename of component without breaking HA and MQTT integrations.
2. Ability to use localized name of Components in MQTT integration with autodiscovery. Now topic name generated for autodiscovery uses sanitized Component name, which will be empty for names as "Температура", "Влажность".

I'm not sure if the parameter name should be `object_id`, maybe `entity_id` or something like that.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1741

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** https://github.com/esphome/esphome-docs/pull/2717

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
switch:
  - platform: gpio
    pin: 25
    name: "Living Room Dehumidifier"
    object_id: living_room_dehumidifier
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nagyrobi** [comment]
Is `object_id` in ESPHome meant to be part of the `entity_id` in Home Assistant?

Eg. is it the intention with `object_id: living_room_dehumidifier` in ESPHome to set the `entity_id` in Home Assistant to be `switch.living_room_dehumidifier`?

**Comment by arduanov** [comment]
`object_id` is part of Home Assistant `unique_id`

Example for MQTT discovery. `this->get_default_object_id_()` returns `object_id`
```
root[MQTT_UNIQUE_ID] = "ESP" + this->component_type() + this->get_default_object_id_(); 
```

Example for API integration. `entity->get_object_id()` returns `object_id`
```
msg.unique_id = get_default_unique_id("binary_sensor", binary_sensor);
...

std::string get_default_unique_id(const std::string &component_type, EntityBase *entity) {
  return App.get_name() + component_type + entity->get_object_id();
}
```
API message also have `object_id`, but i do not now how Home Assistant use it.
```
msg.object_id = binary_sensor->get_object_id();
```

More suitable `config.yaml` example
----
```
switch:
  - platform: gpio
    pin: 25
    name: "Name Living Room Dehumidifier"
    object_id: object_id_living_room_dehumidifier
```

Home assistant create entity with `entity_id: switch.name_living_room_dehumidifier`, not with `object_id_living_room_dehumidifier`


Entity from Home Assistant `core.entity_registry`
```
      {
...
        "config_entry_id": "ee484f134247c828625f2c0eaec20e90",
        "device_id": "a75f997befc1fe5980bcc1bcf666e706",
        "entity_id": "switch.name_living_room_dehumidifier",
        "id": "6545e5de293ec8b8f5e63ab662d9bc70",
        "original_name": "Name Living Room Dehumidifier",
        "unique_id": "my-sensorsswitchobject_id_living_room_dehumidifier",
...
      }
```

**Comment by oxan** [comment]
> 2\. Ability to use localized name of Components in MQTT integration with autodiscovery. Now topic name generated for autodiscovery uses sanitized Component name, which will be empty for names as "Температура", "Влажность".

FYI this is already possible by using the `discovery_unique_id_generator: mac` option in the MQTT component.

**Comment by arduanov** [comment]
> FYI this is already possible by using the discovery_unique_id_generator: mac option in the MQTT component.

It's not usable for names of components with non ASCII symbols.

Example
----
```
esphome:
  name: my-sensors

esp32:
  board: lolin32_lite
  framework:
    type: arduino

logger:
api:
ota:

mqtt:
  broker: !secret mqtt_broker
  discovery: true
  username: !secret mqtt_username
  password: !secret mqtt_password
  use_abbreviations: false
  discovery_unique_id_generator: mac

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: gpio
    name: "Температура"
    pin: 4
  - platform: gpio
    name: "Влажность"
    pin: 5

```

Result in logs
-------
```
[04:45:13][C][mqtt.switch:041]: MQTT Switch 'Температура': 
[04:45:13][C][mqtt.switch:042]:   State Topic: 'my-sensors/switch//state' <-- no component name in topic
[04:45:13][C][mqtt.switch:042]:   Command Topic: 'my-sensors/switch//command'
[04:45:13][C][mqtt.switch:041]: MQTT Switch 'Влажность': 
[04:45:13][C][mqtt.switch:042]:   State Topic: 'my-sensors/switch//state' <-- same as previous component
[04:45:13][C][mqtt.switch:042]:   Command Topic: 'my-sensors/switch//command'
```
Сonclusions
----
Two switches have same topics without component names. And without using option `the discovery_unique_id_generator: mac`, we have same results with bad topics.

This PR changes
====
Config
----
```
esphome:
  name: my-sensors

esp32:
  board: lolin32_lite
  framework:
    type: arduino

logger:
api:
ota:

mqtt:
  broker: !secret mqtt_broker
  discovery: true
  username: !secret mqtt_username
  password: !secret mqtt_password
  use_abbreviations: false
  discovery_unique_id_generator: mac

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

switch:
  - platform: gpio
    name: Температура
    object_id: Temperature
    pin: 4
  - platform: gpio
    name: Влажность
    pin: 5

```

Result in logs
-------
```
[07:50:04][C][mqtt.switch:041]: MQTT Switch 'Температура': 
[07:50:04][C][mqtt.switch:042]:   State Topic: 'my-sensors/switch/temperature/state' <-- use object_id if it exists in config
[07:50:04][C][mqtt.switch:042]:   Command Topic: 'my-sensors/switch/temperature/command'
[07:50:04][C][mqtt.switch:041]: MQTT Switch 'Влажность': 
[07:50:04][C][mqtt.switch:042]:   State Topic: 'my-sensors/switch//state' <-- use name as old behaviour
[07:50:04][C][mqtt.switch:042]:   Command Topic: 'my-sensors/switch//command'
```
Now topic have right name based on provided `object_id`. If `object_id` is empty - use `name` instead.

**Comment by clinta** [comment]
This is great. The sanitized version of a name is often not ideal. I think it would be more obvious what it does if it was named `entity_id` though.

**Comment by arduanov** [comment]
It's not the same as Home Assistant Entity ID and this name may confuse people in the future. It's part of `unique_id` which Home Assistant internally used.

**Comment by clinta** [comment]
> It's not the same as Home Assistant Entity ID and this name may confuse people in the future. It's part of `unique_id` which Home Assistant internally used.

The entity id is something like `light.<object_id>`? Or is it more involved than that?

**Comment by nagyrobi** [comment]
The name, `object_id` creates a lot of confusion for the users. Perhaps something like `unique_object_id` would be cleaner.

**Comment by oxan** [comment]
> It's not usable for names of components with non ASCII symbols.

Ah, I see your point. The `mac` generator does generate actual `unique_id`s, but the topic name is still identical. Booh.

**Comment by arduanov** [comment]
> The entity id is something like `light.<object_id>`? Or is it more involved than that?

Home Assistant Entity ID is like `light.<sanitize(name)>`. This PR does not change any in HA Entity ID.

**Comment by arduanov** [comment]
> Ah, I see your point. The mac generator does generate actual unique_ids, but the topic name is still identical. Booh.

Problem not only in mqtt integration, its for API too.

The main problem in ESPHome `object_id` generation, which for non ASCII generates empty string. Also `object_id` is part of `unique_id`, so we have same `unique_id` for two components. Home Assistant can't use one `unique_id` for two Entitys.

Example for Home Assistant API  integration
----
```
switch:
  - platform: gpio
    name: Температура
    pin: 4
  - platform: gpio
    name: Влажность
    pin: 5
```

ESPHome generates two switches with the same `unique_id: my-sensorsswitch`


Home Asistant Entity
----
```
{
...
    "id": "5d22b8b8fd23ddfcf4ee5a7fc85511d8",
    "original_name": "Влажность",
    "unique_id": "my-sensorsswitch",
...
}
```
Home Asistant  creates only one switch with `unique_id: my-sensorsswitch`

**There are several ways to solve this:**
1. Generate a unique_id in ESPHome using transliteration. It's too heavy for the device.
2. Use `fnv_hash(name)` for the unique_id generation. This will break existing integrations.
3. Add a new parameter that will be written in ASCII and will have no problems with generating a unique_id based on it. This does not break any existing integrations.


I chose option 3 as the most optimal and implemented it.

**Comment by clinta** [comment]
> > The entity id is something like `light.<object_id>`? Or is it more involved than that?
> 
> Home Assistant Entity ID is like `light.<sanitize(name)>`. This PR does not change any in HA Entity ID.

Then how does this address https://github.com/esphome/feature-requests/issues/2119?

**Comment by arduanov** [comment]
> Then how does this address [esphome/feature-requests#2119](https://github.com/esphome/feature-requests/issues/2119)?

You are right, this feature request about device `friendly_name`, not for the component name. Thank you.

**Comment by oxan** [comment]
> The main problem in ESPHome `object_id` generation, which for non ASCII generates empty string. Also `object_id` is part of `unique_id`, so we have same `unique_id` for two components. Home Assistant can't use one `unique_id` for two Entitys.

Yes, I'm aware of that, but the `mac` generator for MQTT doesn't have that problem (but it still has the problem of using non-unique topic names); hence my comment.

**Comment by arduanov** [comment]
I renamed it to `unique_object_id` and made improvements to generate the hash correctly.

**Comment by arduanov** [comment]
Entity object_id can be set on compie stage. Close PR for now.

**Pull request closed without merging**
