### PR TITLE
Add support for Airthing Wave Mini 

### PR DESCRIPTION
**Pull request by ncareau**
# What does this implement/fix? 

Add support for the Airthing Wave Mini BLE device.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1505

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

Sensors:

```yaml
  - platform: airthings_wave_mini
    ble_client_id: airthingsmini
    update_interval: 5min # default
    temperature:
      name: "WaveMini Temperature"
    humidity:
      name: "WaveMini Humidity"
    pressure:
      name: "WaveMini Pressure"
    tvoc:
      name: "WaveMini VOC"   
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by ncareau** [comment]
Hello, I've made this PR in particular for the event hacktoberfest by digital ocean : https://hacktoberfest.digitalocean.com. I would really appreciate if you could add the label **hacktoberfest-accepted** to this PR (or add a label `hacktoberfest` to the project) in order to make my PR count towards my goal. Thank you.

**Comment by jesserockz** [comment]
> Hello, I've made this PR in particular for the event hacktoberfest by digital ocean : [hacktoberfest.digitalocean.com](https://hacktoberfest.digitalocean.com). I would really appreciate if you could add the label **hacktoberfest-accepted** to this PR (or add a label `hacktoberfest` to the project) in order to make my PR count towards my goal. Thank you.

ESPHome is already participating, and PRs will count once approved or merged =)
No need for extra labels

**Review by jesserockz — APPROVED** [review]
LGTM

**Comment by ncareau** [comment]
Thanks a lot.

**Pull request merged**
