### PR TITLE
unpin mbedtls version

### PR DESCRIPTION
**Pull request by glmnet**
## Description:

Fixes issue with xiamoi tls lib

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
Hmm, I'm a bit confused. Isn't mbedtls packaged with the Arduino framework? (I think their Https client used mbedtls).

If so, we shouldn't include a `add_library` call for it, since that (probably) pulls in a library from PIO (with potentially wrong setups for ESP32)

**Comment by vevsvevs** [comment]
@OttoWinter, I'm not the integration code author (neither coder at all), but I've checked your remark with the real hardware, and found that you're absolutely right - it compiles and works perfectly without `add_library` call :)

**Comment by glmnet** [comment]
cc @ahpohl

**Comment by ahpohl** [comment]
I also checked on mine and it compiles without the `add_library` call like you already figured out. I am sure when I started working on ESPHome it compiled only with the extra mbedtls pulled in. But this must have been an issue with my initial development setup. I guess the additional mbedtls libraries could be removed from all new `xiaomi_ble `sensors which use the encryption (if not already done so in the last PR).

**Comment by OttoWinter** [comment]
@ahpohl Yeah no problem! I know getting libraries to compile can be a bit hard sometimes.

All references to it have been removed in this PR.

**Comment by Misiu** [comment]
@OttoWinter so `cg.add_library("mbedtls", None)` can be removed in those 3 places?

**Comment by glmnet** [comment]
It was removed already.

**Pull request merged**
