### PR TITLE
Add the touch screen GUI component

### PR DESCRIPTION
**Pull request by numo68**
# What does this implement/fix? 

This pull request implements a way to create a touch screen GUI where a set of virtual buttons for multiple display pages can be created. The touch screen events such as ones from the XPT2046 touch screen controller implemented the (not yet merged) #1542 can be routed to this component where the interaction with the buttons is evaluated and provided in the binary sensor way.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1083
  
# Test Environment

- [x] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

See the `test4.yaml` and the documentation PR for more examples.

```yaml
# Example config.yaml
touch_gui:
  id: gui
  button_colors:
    background: color_button_background
    active_background: color_button_activated
    foreground: color_button_text
    active_foreground: color_button_text
    border: color_button_text
  button_font: sans20
  on_update:
    then:
      - component.update: tft

binary_sensor:
  - platform: touch_gui
    id: btn_page_next
    type: momentary
    x_min: 162
    y_min: 270
    x_max: 238
    y_max: 318
    pages:
      - page_thermostats
      - page_covers
    text: 'Next'
    on_press:
      then:
        - display.page.show_next: tft
```

# Explain your changes

In the #1542 I implemented a touch screen controller for the common XPT2046 chip. After some experiments I decided to implement a clean way to implement touch buttons of the common types and build a component able to take the touch screen events, manage the button states, draw the buttons according to them and trigger automations based on it.

The code is already used with my home project consisting of four display pages containing about 16 buttons.

In addition to the component itself I needed to make a small modification in the `ci-custom.py`. This is just to exempt a needed true-type font file from the unicode format check.

Note that an extensive GUI is prone to run into stack size issues like those in esphome/issues#855 

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by numo68** [comment]
Hello @glmnet , I attempted to come up with a way to make a yaml-parametrized GUI for touch screen based devices. It works for me and it seems to solve my needs in a pretty elegant way and I think that it can be a basis for adding more control elements later if needed. I would appreciate some comments. The docs is already added as well.

**Comment by PiratWeber** [comment]
Hey, thank you for creating this feature also! Was just looking for it. Can't wait for it to be merged and released :)

**Comment by rdehuyss** [comment]
This looks like a cool addon to esphome.

Small question to make it less verbose, is this also an option?:

```yaml
binary_sensor:
  - platform: touch_gui
    id: btn_page_next
    type: momentary
    coordinates: (162, 270, 238, 318) // e.g. like https://developer.android.com/reference/android/graphics/Rect
    pages:
      - page_thermostats
      - page_covers
    text: 'Next'
    on_press:
      then:
        - display.page.show_next: tft
```

**Comment by numo68** [comment]
> Small question to make it less verbose, is this also an option?:
> ```yaml
>     coordinates: (162, 270, 238, 318) // e.g. like https://developer.android.com/reference/android/graphics/Rect

I considered this and frankly I don't know what is the usual way to do things in esphome, i.e. whether verbosity or compactness is preferred or whether it is maybe common to offer both. `x_min` etc is self-explaining, this is not and one needs to look up in the docs.

A comment from the maintainers would be welcome here.

**Comment by rdehuyss** [comment]
@jesserockz Any reason why this was not merged?

**Pull request closed without merging**
