### PR TITLE
Install updated git version in lint image

### PR DESCRIPTION
**Pull request by jesserockz**
## Description:
Updates the git version installed in the lint container.

Looking to (re)create the gitlab-ci & travis in github actions completely but the git version needs to be updated.
This could be done in the workflow step, but it means adding more wait time there.

I am not sure where this docker image is built though and might be a manual build and upload to docker hub.

jesserockz/esphome#1

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here> 

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
Ahh thanks, I wasn't working on this because Otto started but he did not finish, it seems like he wanted to create it's own github action for this, I don't understand why.

I'm testing a new github action already on the esphome-docs repo.

**Comment by jesserockz** [comment]
Yeah I saw the (empty) lint action repo and thought he must have started but never got anywhere. I figured I could just reuse the existing image for consistency.

**Comment by glmnet** [comment]
I don't think that is going to update the container automatically, we can add the actions with another docker meanwhile if you want to create it

**Comment by jesserockz** [comment]
Yeah thought so, I can push it a build under my own user for now.

**Pull request merged**
