### PR TITLE
Call Stepper should_step_ every loop iteration

### PR DESCRIPTION
**Pull request by akonradi**
## Description:

Without this, Stepper::last_calculation_ only gets updated when a step is
needed. This means that when the motor first starts, the delta time from the
last step is computed incorrectly, resulting in instantaneous acceleration to
the maximum allowed speed.

Calling Stepper::should_step_ every loop iteration ensures that the time
interval between calls stays small.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

**Comment by akonradi** [comment]
I'm not sure how to add a test for this that doesn't depend on real hardware. I've run the patched code on my own device though with a stepper connected to a ULN2300 and it seems to work.

**Comment by akonradi** [comment]
@jesserockz any suggestions for how to add tests for this? I programmed my device with this patched into a local clone and it's been working as expected.

**Comment by jesserockz** [comment]
Tests are not required for this change. It just needs people to test it.

**Comment by akonradi** [comment]
Any suggestions for how to recruit volunteers?

**Comment by SalexSun** [comment]
The [issue ](https://github.com/esphome/issues/issues/1748) I encountered seems to be the same. I would love to test it, but I'm not sure how to add @akonradi patch on my home assistance instance

**Comment by akonradi** [comment]
@SalexSun you can use this version locally. I'd suggest doing it in a virtualenv (https://docs.python.org/3/library/venv.html), but either way, you can use pip to install from the branch for this PR:
```
pip install 'git+https://github.com/esphome/esphome@refs/pull/1373/head'
```
Then run the esphome program like normal.

**Comment by jesserockz** [comment]
@SalexSun You can also add `akonradi:patch-1` in the `esphome_version` in the HA ESPHome addon configuration page and restart the addon

Screen Shot 2021-02-14 at 4 43 26 PM

**Comment by SalexSun** [comment]
Seems to work as it should 👍

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Thanks for this, sorry for the delay in merging

**Pull request merged**
