### PR TITLE
Add min_value and max_value in filters for sensors

### LINKED ISSUE #1581: Add support for max_value/min_value in filters for sensors
**Describe the problem you have/What new integration you would like**

Ability to limit the value of a sensor to a min/max value

**Please describe your use case for this integration and alternatives you've tried:**

```
  - lambda: |-
      if (x >= 150.0) { return 150.0;}
      return x
```

**Additional context**

I know it's possible with a lambda but it feels like this should be supported out of the box with ``max_value`` and ``min_value`` in the filters.

### PR DESCRIPTION
**Pull request by euEmica**
# What does this implement/fix?

A threshold value for the maximum and minimum values has been added to the filter for sensors.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [#1581](https://github.com/esphome/feature-requests/issues/1581)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2156

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by mmakaay** [comment]
I think sensors should be in control of the min and max values themselves, so having a filter that applies min and max values feels a bit strange. When things feel strange, I'm usually missing the context of the exact use case. Yould you elaborate on the intended use for these filters?

I was trying to grab this context from the referenced issue #1581 , however that one is about 'Bump platformio from 5.0.4 to 5.1.0". Maybe the wrong ID was used there?

**Comment by euEmica** [comment]
Sorry, I have corrected the issues  reference [#1581](https://github.com/esphome/feature-requests/issues/1581) you can now access. 

The resolution of this problem is to make it possible to limit the value of a sensor to a minimum and maximum value.

**Comment by mmakaay** [comment]
"Ability to limit the value of a sensor to a min/max value" is what the PR implements. It's the solution to a problem. I was looking for the problem. With what kind of sensor do you use this?
(mainly curiousity, because I never ran into the need for that myself)

**Comment by mmakaay** [comment]
In addition to @OttoWinter 's documentation review, in which he asks for a more clear description of what this filter does functionally: I propose to rename the options to `limit_min` and `limit_max`.
That changes the key names from nouns to verbs, which would remove ambiguity right at the YAML level:

```yaml
filters:
      - offset: 2.0
      - multiply: 1.2
      - limit_min: 0
      - limit_max: 50
 ```

**Review by mmakaay — CHANGES_REQUESTED** [review]
In addition to @OttoWinter 's documentation review, in which he asks for a more clear description of what this filter does functionally: I propose to rename the options to `limit_min` and `limit_max`.
That changes the key names from nouns to verbs, which would remove ambiguity right at the YAML level:

```yaml
filters:
      - offset: 2.0
      - multiply: 1.2
      - limit_min: 0
      - limit_max: 50
```

**Comment by glmnet** [comment]
I would suggest truncate_min or trim_min

**Comment by mmakaay** [comment]
> I would suggest truncate_min or trim_min

Truncate and trim both are conceptually about "chopping off" a part of something, leaving part of that something intact in the result. For example, truncating a date to only the day of the month, or trimming whitespace from a string.

**Comment by spacemanspiff2007** [comment]
> I was looking for the problem.

How do I report sensor values in a specific range on every change and outside of the specific range only with a heard beat.

I have NTC sensors that measure temperature. The sensor parameters were approximated and work well in a specific range.
Because of the non-linearity outside the window the sensor changes the value very often. Since the values outside of this spec range are of no interest I'd like to have it set to a fixed value.
e.g.

| measurement | reported value |
|-|-|
| <= 20°C | 20 °C |
| 35°C | 35°C |
| >= 120 °C | 120°C |

---

Tbh ``limit_min`` is not very self explanatory, either.
I would have preferred ``min`` but that was already taken (and should be renamed to ``moving_minimum``.
The next best way to describe what the filter does is minimum value, because it'll always output at least the specified minimum value. 
It's not doing something, it's a limitation of the range of the sensor, a sensor property and thus a verb is not appropriate.
That's why I think ``min_value`` is a much better and clearer.
(see ``min``, ``sliding_window_moving_average`` and ``exponential_moving_average`` which are nouns, too.)

**Comment by mmakaay** [comment]
Or a combination of verb + your nouns?
For example, inspired by the ESPHome core `clamp(...)` function:

```yaml
filters:
  - clamp:
      min_value: 10
      max_value: 100
```

**Comment by spacemanspiff2007** [comment]
I'm afraid for me "clamp" obfuscates the meaning even more 🙈 

A more readable substructure could be:

```yaml
filters:
  - limit_value:
      min: 10
      max: 100
```

But I'd still prefer a single entry and still think ``min_value`` is a good wording.
How about ``lowest`` and ``highest``? That would not include the word "value".

**Comment by glmnet** [comment]
Well introducing a breaking change here won't cause much damage. So this could be min and max and rename the moving ones makes sense to me

**Comment by spacemanspiff2007** [comment]
> Well introducing a breaking change here won't cause much damage.

That's right. Since the current min/max expects at least one of the sub keys ``window_size``, ``send_every`` or ``send_first_at`` it would fail with a proper error message. 

One could even inspect the current configuration structure and issue an appropriate error message (e.g. ``min`` has been renamed to ``sliding_window_min``) to make the migration easier.

**Comment by glmnet** [comment]
> One could even inspect the current configuration structure and issue an appropriate error message (e.g. `min` has been renamed to `sliding_window_min`) to make the migration easier.

yes, that's how _configuration_ breaking changes are usually handled, do you agree @mmakaay  @jesserockz @euEmica

**Comment by jesserockz** [comment]
Yeah it could work. 
It would be more work than normal as we are still legitimately using the key.

**Comment by ssieb** [comment]
I would second the use of `clamp:` with parameters since that's the general term for this action.

**Comment by glmnet** [comment]
This one should be fixed somehow

**Pull request closed without merging**
