### PR TITLE
pipsolar component. Correct the sscanf format for QPIG command parsin…

### PR DESCRIPTION
**Pull request by eroldan**
…g to set pv_input_voltage as float (not int)

# What does this implement/fix?

This extra small PR makes the parsing of the QPIGS command compatible with newer devices. Previously, the field "PV Input Current" was parsed as an integer, which is not correct for the latest devices/firmware. The %f format will parse older (without a dot) representations too, making this backwards compatible.

## Types of changes

- [x ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ maybe] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [ x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

Here are two screenshots of older documents with the integer definition
voltronic_ks_mks_v
voltronic_2015

Here is a screenshot of a 2020 model (Axpert MAX) with the float definition:

voltronic_max

These documents are released by the manufacturer (Voltronic).

Here is an actual reading from an Axpert VM-III made by myself, next to the format declared by the manufacturer and the correct sscanf string:

```
245.1 50.0 245.1 50.0 1591 1486 031 408 54.00 000 100 0040 10.7 135.8 00.00 00000 10010110                 00 00 01461 110
%f    %f   %f    %f   %d   %d   %d  %d  %f    %d  %d  %d   %f   %f    %f    %d    %1d%1d%1d%1d%1d%1d%1d%1d %d %d %d    %1d%1d%1d
BBB.B CC.C DDD.D EE.E FFFF GGGG HHH III JJ.JJ KKK OOO TTTT EE.E UUU.U WW.WW PPPPP statusby                 QQ VV MMMMM b10b9b8 Y ZZ AAAA
```

### CODE REVIEW

**Comment by VirtualFab** [comment]
Hi I can confirm the issue: on my Voltronic Axpert MK IV the QPIGS command doesn't correctly decode all fields and stops just before a crucial one: PV power. 
My sampled data is
(224.8 49.9 224.8 49.9 2248 2247 040 367 48.80 000 028 0026 **00.4** 119.8 00.00 00000 00010111 00 00 00053 010\xCC\xCE\r
and the breaking float is named "PV1 Input current" in my protocol manual. 
So just changing the %d to %f should fix it and let me reach that "00053" which is so important to me :-)

Thank you guys for your hard work!

**Comment by eroldan** [comment]
@andreashergert1984 can you break silence and tell us if you are able to review this PR and on which timeframe? You are the codeowner and obviously an expert on this topic. We need you here. Thanks.

**Comment by andreashergert1984** [comment]
> @andreashergert1984 can you break silence and tell us if you are able to review this PR and on which timeframe? You are the codeowner and obviously an expert on this topic. We need you here. Thanks.

sry i´m heavily loaded by work .. let me try to do this over xmas-days

**Comment by eroldan** [comment]
Any news? @andreashergert1984

**Review by jesserockz — APPROVED** [review]
Apologies for the delay

**Pull request merged**
