### PR TITLE
proceed if AP mode is set up

### LINKED ISSUE #3956: Web Server not working on AP mode when a WiFi network is configured
### The problem

The web server does not seem to be started on AP mode when there is a WiFi network configured but out of reach. When not configuring a WiFi network and only AP mode the server is normally started.

My use case is a portable heater that can be used with home assistant when in reach of the network but can still be used with the build in web server if not. This does not seem possible right now and I would have to choose to either only allow home assistant access or only access via the build in AP.

As the web server does indeed work over the AP when no network is configured this seems like a bug and not like an intended limitation?

### Which version of ESPHome has the issue?

 v2022.12.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.12.8

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

Web Server

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ssieb**
# What does this implement/fix?

If wifi is configured but can't connect and the AP comes up, the web server and other services are not available.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/3956

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by Hiekkaharju** [comment]
No success. See attached. 
No sign of web server starting, even when AP is connected.
I believe starting of Captive portal is done the way it is for a reason.
[test2.yaml.txt](https://github.com/esphome/esphome/files/15107202/test2.yaml.txt)
[test2_logs.txt](https://github.com/esphome/esphome/files/15107210/test2_logs.txt)

**Comment by ssieb** [comment]
Try again.  I've tested this one and it works.

**Comment by Hiekkaharju** [comment]
Thanks for yor effort. This version indeed seems to start the web server properly with or without STA-wifi presence.

BUT strangely enough I found one sequence that does not now work:
-reset the device when STA-wifi is not available - AP and webserver will start after ap_timeout
-make STA wifi available - device connects to STA-wifi and stops AP
-make STA wifi unavailable - device starts to scan for wifi. BUT it does not start AP after the ap_timeout time. Web server likely would be still running, but it can't be accessed as the AP is not. 

The strangest part is that if the device is started with STA-wifi available, i.e AP is not started before STA-wifi is connected, it will start AP when STA-wifi is lost.

I tested with esphome 2024.4.1 + pr#6631, but I can't see anything in 2024.4.2 changelog that could affect this.

**Comment by ssieb** [comment]
What happens in that scenario without this change?

**Comment by Hiekkaharju** [comment]
As you apparently suspected, the same happens also with pure 2024.4.1. (exept of course web server starts only when STA-wifi is connected)
I created a new issue for the the ap restart
https://github.com/esphome/issues/issues/5759
Thus I think that this PR would be ready for review, merge and release.
Thanks !

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
