### PR TITLE
Added support for pvvx_mithermometer sensor

### PR DESCRIPTION
**Pull request by pasiz**
## Description:

Added support for pvvx mithermometer custom firmware format (0.01 precision in temperature, 0.01 precision in humidity)
Configuration is same than atc_mithermometer, just added protocol support.

**Related issue (if applicable):** fixes support request in issue: 877

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1290

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by pasiz** [comment]
I edited docs and test are runned locally ok. I cannot understand why in github those failed

**Comment by myhomeiot** [comment]
Thanks for great job! Please change device class for battery voltage sensor to DEVICE_CLASS_VOLTAGE.
@jesserockz @pasiz

```
            cv.Optional(CONF_BATTERY_LEVEL): sensor.sensor_schema(
                UNIT_PERCENT, ICON_EMPTY, 0, DEVICE_CLASS_BATTERY
            ),
            cv.Optional(CONF_BATTERY_VOLTAGE): sensor.sensor_schema(
                UNIT_VOLT, ICON_EMPTY, 3, DEVICE_CLASS_VOLTAGE
            ),
```

**Comment by pasiz** [comment]
> Thanks for great job! Please change device class for battery voltage sensor to DEVICE_CLASS_VOLTAGE.
> @jesserockz @pasiz
> 
> ```
>             cv.Optional(CONF_BATTERY_LEVEL): sensor.sensor_schema(
>                 UNIT_PERCENT, ICON_EMPTY, 0, DEVICE_CLASS_BATTERY
>             ),
>             cv.Optional(CONF_BATTERY_VOLTAGE): sensor.sensor_schema(
>                 UNIT_VOLT, ICON_EMPTY, 3, DEVICE_CLASS_VOLTAGE
>             ),
> ```

Thanks for feedback!

Just changing...

**Comment by myhomeiot** [comment]
I confirm that this integration works.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
