### PR TITLE
Vl53l1x

### PR DESCRIPTION
**Pull request by mampfes**
## Description:

add support for vl53l1x time of flight distance sensor

**Related issue (if applicable):** none

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#916

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by DutchDeffy** [comment]
Hello, I really appreciate your work. This time of flight sensor is awesome and has a lot of potential. I’m expecting to receive a pair of sensors in the coming weeks. Is there any way I could help to test this PR? Just got started with a little bit of programming. But already have like a few years experience with Home Assistant and and diy sensors and stuff. I would really love to see if the people counting concept as developed by STMicroelelectronics could be integrated with this component. @Andrea-Fox already wrote code translating the concept to be used in an arduino environment. But there an other library for the Vl53l1x is used. Could we get something together so people can use the very well done integration of Esphome in Home Assistant to count people and detect presence in a space?

**Comment by Andrea-Fox** [comment]
As @DutchDeffy I already wrote some code for esp32/esp8266 which is able to count the people in a room using vl53l1x, however it uses the library provided by Adafruit and not the Pololu one. Moreover I'm not good enough to understand all the code necessary for integrating my idea inside esphome, however I would gladly help you if you don't understand some parts of my code

**Comment by mampfes** [comment]
@DutchDeffy As @Andrea-Fox already mentioned, the vl53l1x code for esphome is based on the Pololu library. I don't know the detailed differences between the 2 implementations, but I assume that they are interchangeable to some extend. Feel free to ask questions, I would be happy to help you.
The first show-stopper that comes into my mind is the fact that my current vl53l1x component doesn't support multiples devices at the same time. Do you need the support for multiple devices at the same time? If yes, I could try to implement this, based on the groundwork in the vl53l0 component, but I'm not able to test it because I don't own 2 VL53L1x devices.

**Comment by Andrea-Fox** [comment]
> Do you need the support for multiple devices at the same time?

No, you don't need multiple VL53L1X devices. You just need to connect one to the I2C connectors and that's it.  

> I don't know the detailed differences between the 2 implementations, but I assume that they are interchangeable to some extend

I'm not really sure whether the library has been updated, but when I started developing the code a few months ago, I couldn't manage to it work using the Pololu library, as at the time a function that I use wasn't implemented  in that library, while at the same time it was in the Adafruit library. The function in question is the one that allows changing the Region of Interest (in the Adafruit library is called `setROI`) and is a  pivotal piece of the algorithm

**Comment by mampfes** [comment]
`setROI `is still missing in the Pololu library. I could add it to the esphome component if you want.
1. Do you just need a setROI method similar to the Adafruit implementation?
2. Or do you also need access to the setROI arguments (x, y, opticalCenter) from the yaml configuration in esphome?

**Comment by DutchDeffy** [comment]
For setROI it would be nice, and since almost every user's situation is different almost necessary, for the user to be able to set the arguments in the yaml config in esphome. So that's the second option you mention. I made a bit of start adding lines to config schema and to the 'to_code' function in sensor.py. Would this be a way to do the config? https://github.com/DutchDeffy/esphome_custom_component_VL53L1X_people_counter/blob/dev/copy%20of%20%40mampfes%20vl53l1x%20%2B%20people%20counter%20algorithm/sensor.py

A sample esphome config yaml would look like this then

```
 sensor:
       - platform: vl53l1x
         name: "VL53L1x *name*"
         update_interval: 60s
         distance_mode: LONG
         timing_budget: 50ms
         optical_center:
           x_coordinate: 159
           y_coordinate: 231
         roi_height: 16
         roi_width: 7

```
 Is this something? Btw, I wasn't really sure about if at line 58 and 59 ([permalink](https://github.com/DutchDeffy/esphome_custom_component_VL53L1X_people_counter/blob/e2a1a541df2353e5e831995c27d2f55c182e564c/copy%20of%20%40mampfes%20vl53l1x%20%2B%20people%20counter%20algorithm/sensor.py#L58-L59)) it's also possible to pass the whole list to the C++ code instead of calling the two elements separately. So you would get:
` 
optical_center_config = config[CONF_OPTICAL_CENTER]
cg.add(var.set_optical_center(optical_center_config))
`

**Comment by Andrea-Fox** [comment]
Completely agree with @DutchDeffy. I think that all the parameters that he specified are needed.  
Moreover I would also add the value of the height threshold, as different doors need different values of the threshold

**Comment by DutchDeffy** [comment]
Good catch @Andrea-Fox. That config schema could look like this I guess

```
CONFIG_SCHEMA = sensor.sensor_schema(UNIT_METER, ICON_ARROW_EXPAND_VERTICAL, 2).extend({

    //... more lines of code which could be referenced from my previous comment ...

    cv.Optional(CONF_DIST_THRESHOLD, default=1600): cv.int_range(min=0, max=0xFFFF),

    //... etc ...

}).extend(cv.polling_component_schema('60s')).extend(i2c.i2c_device_schema(0x29))

def to_code(config):

    //... etc ...
    
    cg.add(var.set_retry_budget(config[CONF_DIST_THRESHOLD]))

    //... etc ...

    yield i2c.register_i2c_device(var, config)
```

**Comment by mampfes** [comment]
I added support to set the user roi from within a esphome yaml config (see branch https://github.com/mampfes/esphome/tree/vl53l1x_set_user_roi).
I reused the original coordinate system from ST (top-left-X/Y + bottom-right-X/Y, range: 0-15).

Regarding thresholds: Setting threshold only makes sense if you are using the interrupt pin and the VL53 is measuring either continuously or with a very high sample rate. The current esphome component uses a polling schema - which doesn't fit together with an interrupt approach.

Just the be curious: Are you refering to the ST application note to count persons? If yes, this application note requires to split the ROI into 2 section und measure the distance of both - which means that you have to measure distance of region 1 and afterward measure distance of region 2. How do want to toggle between the to sections?

**Comment by Andrea-Fox** [comment]
I think that the code has to measure continuously in order to detect people passing under the door (with continuously I mean that a measure is taken every 50 ms)

> Are you refering to the ST application note to count persons?

Yes, basically I translated their idea into an algorithm suitable for ESP32/ESP8266 and added mqtt support 

> How do want to toggle between the to sections?

The idea is that every 50 ms we take a measure of one of the two zones. After 50 ms we take a new measure of the other zone and so on

**Comment by mampfes** [comment]
Ok, then I got it right.

But I don't understand why you need `setROI `from the yaml config (because you need to change it for every new msmt).

Anyhow: I think this should be feasible within esphome. But I wouldn't build your functionality on top of my vl53l1x component, because this one made to measure single distances with quite low sampling rates.
I would create a new component (equals to a folder like vl53l1x) especially for your people counting component. Inside this you  can reuse the library code for the vl53l1x (VL53LX1.h and VL53L1X.cpp) and maybe also some configuration options for the VL53L1X.
Do you agree? Do you know how to setup such a component or do you need help?

**Comment by Andrea-Fox** [comment]
> But I don't understand why you need setROI from the yaml config (because you need to change it for every new msmt).

What do you mean for msmt?

> I would create a new component (equals to a folder like vl53l1x) especially for your people counting component. Inside this you can reuse the library code for the vl53l1x (VL53LX1.h and VL53L1X.cpp) and maybe also some configuration options for the VL53L1X.
Do you agree? Do you know how to setup such a component or do you need help?

I agree with the fact that creating a new folder specific for the people counter would be a good idea. I am not able to do all the necessary things, hence I would definitely help from someone

**Comment by mampfes** [comment]
@Andrea-Fox I created a small framework for you: https://github.com/mampfes/esphome/tree/vl53l1x_people_counter

The code compiles and is compliant with the esphome coding guidelines, but I didn't test if on a real hardware.

The platform is called: vl53l1x_people_counter (feel free to change it if you want)

**Comment by Andrea-Fox** [comment]
Thank you for creating the component. In the next few days I will test it and I will let you know if I'm able to make it work

**Comment by DutchDeffy** [comment]
Correct me if I'm wrong, but it's still a framework, right? So that means the code doesn't do the people counting yet or does it? @Andrea-Fox What do you mean by testing it? What are willing to test then, the connection of the microcontroller and the hardware using this framework?

**Comment by Andrea-Fox** [comment]
You are right. Yesterday I misunderstood what @mampfes wrote and thought that it was already working as a people counter

**Comment by mampfes** [comment]
Yes - it is only a framework: It provides an environment for your people counting algorithm. It is able to read values from multiple zones of a vl53l1x (theoretically - not tested) within the polling environment of esphome. There you can plug your algorithm. The output of your algorithm - the people counter - can also be fed back to esphome easily. I hope this helps because you don't have to deal with most of the esphome entrails.

**Comment by DutchDeffy** [comment]
Hello all, yesterday I received my Chinese VL53I1x time of flight sensor and got the distance sensor component working with a Nodemcu today already. These are the steps I took.
1. Installed esphome in a python-venv from the Vl53l1x branch corresponding with this pull request. See the home-asssitant and esphome docs for how to do that. HA: [1](https://www.home-assistant.io/docs/installation/virtualenv/) ESPHOME: [2](https://esphome.io/guides/getting_started_command_line.html#bonus-esphome-dashboard)

2. Creating a yaml config file
```
substitutions:
  device_name: "time_of_flight"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssdi
  password:  !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: "!secret ota_pass"
  
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:
  scan: True
  sda: 4
  scl: 5 

sensor: 
  - platform: vl53l1x
    name: "VL53L1x Distance"
    update_interval: 5s
    distance_mode: LONG
    timing_budget: 50ms
    address: 0x29 # The i2C-address from device TOF-sensor was different than the one's from Sparkfun / Pololu
```
3. Connect all the wires

**NODEMCU | VL53L1X board**
3V3/VIN to VIN 
GND to GND 
D2 to SDA 
D1 to SCL

4. The usual uploading config + integrating with Home Assistant

These are the results
The logs: https://gist.github.com/DutchDeffy/08f7eda40ccad72ca2dc7a4943b17c94 
Screenshot of the Home Assistant sensor graph

Could this be seen as a valid test or is more information needed? Does this help for the component to be integrated to an  official esphome release?

**Comment by DutchDeffy** [comment]
Could someone maybe have a look at the config schema. Based on @mampfes branch with the people counter framework, I rewrote the sensor.py code adding all the needed in the yaml-file configurable variables and passing these to the C++ code using setters. Here's the code https://github.com/DutchDeffy/esphome_custom_component_VL53L1X_people_counter/tree/dev/Copy%20of%20%40mampfes%20vl53l1x%20%2B%20people%20counter%20vl53l1x_people_counter
It includes an example_config.yaml file. Is this going the right direction or did I miss anything?

**Comment by kkellner** [comment]
@mampfes Any chance you can incorporate "i2c address change" into your code so allow support of multiple vl53l1x on the same i2c bus?  Similar to this change:  https://github.com/esphome/esphome/pull/1126

**Comment by mampfes** [comment]
> @mampfes Any chance you can incorporate "i2c address change" into your code so allow support of multiple vl53l1x on the same i2c bus? Similar to this change: #1126

I could try - but I don't have access to 2 vl53l1x at the moment. Therefore will not be able to test it.

**Comment by DutchDeffy** [comment]
I

> > @mampfes Any chance you can incorporate "i2c address change" into your code so allow support of multiple vl53l1x on the same i2c bus? Similar to this change: #1126
> 
> I could try - but I don't have access to 2 vl53l1x at the moment. Therefore will not be able to test it.

I have two sensors, so I could test it for you if you want to. Btw, If we want to get this merged maybe it's better to rewrite the library into esphome c++. So the component could be developed and updated more easily. I suggest we base the rewrite on the more comprehensive Sparkfun library. https://github.com/sparkfun/SparkFun_VL53L1X_Arduino_Library

**Comment by mampfes** [comment]
> I have two sensors, so I could test it for you if you want to. Btw, If we want to get this merged maybe it's better to rewrite the library into esphome c++. So the component could be developed and updated more easily. I suggest we base the rewrite on the more comprehensive Sparkfun library. https://github.com/sparkfun/SparkFun_VL53L1X_Arduino_Library

@DutchDeffy I have some question regarding your suggestions:
- What do you mean with esphome c++? What should have been changed in the component? Why does this simplify development and updates?
- What are the advantages of the Sparkfun library? Is s.th. missing in the Pololu library? In the meantime I had to learn that there is also an implementation from ST itself. Would this be an even better choice?
- Why do you think this component will not be merged? Do you have insights?

To be honest I didn't compare all available libraries when I started to implement this component. I took the Pololu variant because I bought a Pololu board. Initially I tried to use the Pololu code without any changes - to be able to incorporate bugfixes, enhancements in the original library easily. Unfortunately I had to learn that esphome has really, really strict guidelines in respect to naming conventions, indentation, etc, which forced me to change a lot of stuff in the original library. Personally I don't like this approach, because it effectively impedes development (btw: HomeAssistant for example forces you to separate everything into python packages -> great).

**Comment by Andrea-Fox** [comment]
> What are the advantages of the Sparkfun library? Is s.th. missing in the Pololu library? In the meantime I had to learn that there is also an implementation from ST itself. Would this be an even better choice?

Basically the Pololu library misses the function setROI, which is used for understanding the direction of someone passing under the sensor. Hence it is a pretty pivotal function for counting people in a room

**Comment by mampfes** [comment]
> Basically the Pololu library misses the function setROI, which is used for understanding the direction of someone passing under the sensor. Hence it is a pretty pivotal function for counting people in a room
Is this still an issue? I thought I already copied the function from the original ST library and added it in a separate branch to esphome.

**Comment by DutchDeffy** [comment]
> * What do you mean with esphome c++? What should have been changed in the component? Why does this simplify development and updates?

See the chat conversation I had with JesseRockz on the esphome-dev discord channel.
Chat_1

> * What are the advantages of the Sparkfun library? Is s.th. missing in the Pololu library? In the meantime I had to learn that there is also an implementation from ST itself. Would this be an even better choice?
The Sparkfun library is more complete, the Polulu one is more meant as a quick and easy way to get started with the sensor. Reference: [Pololu vl53l1x-arduino github readme](https://github.com/pololu/vl53l1x-arduino#sts-vl53l1x-api-and-this-library)

> * Why do you think this component will not be merged? Do you have insights?
I think that the things said in the chat on the discord devs channel and the fact that, at the moment, there's no official ESPHome component that uses an I2Cdummy to implement the functionality of a library will make that the pull request in it's current state won't probably be merged .

**Comment by jcastro** [comment]
Anyone can help me out to use this code? I've added the branch to the esphome_version variable on the Hassio Addon (both dev and stable version) but I'm unable to start it with that branch name ``mampfes:vl53l1x``

image

**Comment by hoangtruong2412** [comment]
Hello everybody! Is the VL53L0X sensor suitable for this code?

**Comment by Andrea-Fox** [comment]
Hi @hoangtruong2412. No, unfortunately the code for VL53L1X is not suitable for the VL53L0X sensor

**Comment by hoangtruong2412** [comment]
> Chào bạn @ hoangtruong2412 . Không, rất tiếc mã cho VL53L1X không phù hợp với cảm biến VL53L0X
hi, why i use this code for vl53l1x sensor, when it shows on home assistant it is unknow. and why is the entry "platform: vl53l1x", if I leave it like that, then esphome gives an error?
image

**Review by oxan — CHANGES_REQUESTED** [review]
As @DutchDeffy hinted at above, we won't merge the component in this state. All components integrated into ESPHome need to use the ESPHome abstractions to do I/O. It's not only for ease of maintainance, it's also to support features like I2C expanders, and the (upcoming) support for running directly on the ESP-IDF without the Arduino framework. 

Alternatively, you could also maintain this component as [an external component](https://esphome.io/components/external_components.html), where such restrictions do not exist and you can freely use external libraries (but beware that then it may not work in combination with all ESPHome features).

**Comment by JannickBlmndl** [comment]
Correct me if I’m wrong. Just to get things clear. So for now the options for doing distance measurements with ESPHome are:
- [VL53L0X](https://esphome.io/components/sensor/vl53l0x.html) 
- [Ultrasonic distance sensor](https://esphome.io/components/sensor/ultrasonic.html) 
- [TOF10120 ultrasonic](https://esphome.io/components/sensor/tof10120.html) 

Is there any advantage of using the VL531LX tof sensor for distance only? In other words, what does putting effort in this component add to the stuff that’s already out there? Doesn’t the VL53L0X use the same working principle as the VL531LX? The VL53L0X is even cheaper right?

**Comment by rradar** [comment]
> Doesn’t the VL53L0X use the same working principle as the VL531LX? The VL53L0X is even cheaper right?

I think so, yes.

Difference is mainly the distance. The (cheap) VL53L0X maxes out at 2 meters and the (expensive) VL531LX can "travel" double the distance up to 4 meters

>VL53L0X vs. VL53L1X – Differences Range
> 
>As already mentioned, the most obvious difference between the VL53L0X and VL53L1X is the range. Under optimal conditions, i.e. with good reflection of the surface to be detected and little interference light, you can reach up to two meters with the VL53L0X, but with the VL53L1X up to four meters.
Source: https://wolles-elektronikkiste.de/en/vl53l0x-and-vl53l1x-tof-distance-sensors

**Comment by ruimarinho** [comment]
It would be great to add support for this sensor. There are a few people counter projects out there using ESPHome and VL53L1X, but they increase the complexity for smaller home-focused projects. Is there an agreed architecture with the maintainers to move forward with this pull request?

**Comment by Lyr3x** [comment]
@rradar you missed the main difference: the programmable FoV or also called ROI. You would need to use two VL53L0X for the job that one 1X can do. There are also some more slight changes in the API. 
However, you have a minimum distance of 4cm for reliable measurements when using the 1X

I would be happy to integrate the RooDe component completely into ESPHome but I will not add the VL53L1X support any time soon. I currently use the ULD api which is working fine and would need to be ported nearly 100%.

**Pull request closed without merging**
