### PR TITLE
Renaming and extending the ili9341 to the ili9xxx component

### PR DESCRIPTION
**Pull request by nielsnl68**
# What does this implement/fix?

This is the extended version of the ili9341 with multiple other display drivers from the same driver family.

Removed clearing the screen twice and should only being done by DisplayBuffer::init_internal_();
Made ili9xxx:initalize() protected and renamed it to ili9xxx::initialize().
ili9xxx::initialize() sub-classes should only initialize the display and set the width and height.

with the ili9xxx component can now be used with the following display drivers:
ILI9341, ILI9342, ILI9481, ILI9486, ILI9488 and ST7796 (when you have any other display that works the same way i'm happy to add them as well)

the new ili9xxx display driver is also ready to be used with the extended version of the DisplayBuffer class which is now directly inherent of the PollingComponent instead of being inherited via the display components.

Clean
Related issue or feature (if applicable): fixes PR#3756

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2729

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
    display:
      - platform: ili9xxx
        model: ili9341
        cs_pin: 14
        dc_pin: 27
        reset_pin: 33
        lambda: |-
          it.fill(COLOR_BLACK);
          it.print(0, 0, id(my_font), id(my_red), TextAlign::TOP_LEFT, "Hello World!");
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nielsnl68** [comment]
@davet2001, i did modified your changes a little bit around. Do you mind checking of i did not removed anything important to your changes?

Also i was wondering about when BIT8_INDEXED is chosen, and an unknow color (not yet in the `palette_` array) is chosen, will that color then automatically added to the in `palette_` array?

**Comment by davet2001** [comment]
> Also i was wondering about when BIT8_INDEXED is chosen, and an unknow color (not yet in the `palette_` array) is chosen, will that color then automatically added to the in `palette_` array?

(From memory, it was a while ago) the colors in the palette are created automatically based on the sample image.  It picks the 256 most frequently occurring colors, then everything else uses the closest match in the palette.

**Comment by philippedeswert** [comment]
Hi!

First of all thank you for your work! I tested this on a wt32-sc01. However your latest commits seem to break something as the screen is completely garbled, it works still if I go back to 5f00dfd. I can do debugging/bisecting for you if you need more information.

**Comment by nielsnl68** [comment]
> Hi!
> 
> First of all thank you for your work! I tested this on a wt32-sc01. However your latest commits seem to break something as the screen is completely garbled, it works still if I go back to [5f00dfd](https://github.com/esphome/esphome/commit/5f00dfd03ee2e5ece073afd1cfa179c8937f5008). I can do debugging/bisecting for you if you need more information.

Thanks for your report. i have been trying to fix the ili9488 display and i have not a good result right now, indeed.

**Comment by nielsnl68** [comment]
> > Also i was wondering about when BIT8_INDEXED is chosen, and an unknow color (not yet in the `palette_` array) is chosen, will that color then automatically added to the in `palette_` array?
> 
> (From memory, it was a while ago) the colors in the palette are created automatically based on the sample image. It picks the 256 most frequently occurring colors, then everything else uses the closest match in the palette.

@davet2001 from what i got is that `this-palate_` is not initialised when it is defined in the yaml file, 
The current version will try to use 16 bit colors when there is enough memory and will now fallback to 8 bit color when there is not enough space. I would love to fallback to the indexed 8bit mode but i do not know for what to do with the `this-palate_` property. Could you give me some suggestion on how to implement this and could you check if the new colors are indeed added automatically.

**Comment by Rendman** [comment]
Hello!  I've been tinkering around with adding ILI9488 support to ESPHome for some time now.  I've been struggling a lot due to the memory constraints of the device and the size of the display.  One of the most common configurations of ESP32 devices is 512K of RAM, of which 200K is reserved for IRAM, and not usable as a framebuffer. The remaining 320K is DRAM.  The DRAM is further segmented into two 160K portions.  One of which is for statically allocated memory at compile time (.bss).  The other portion is reserved for dynamic allocation at runtime.  This means in non PSRAM configured devices the maximum framebuffer size is realistically 116K, subtracting for RTOS and other ESPHome created buffers.  The ILI9488 display size is 320x480, so in 8 bpp mode the framebuffer size is 153K, exceeding the available heap memory. The allocator is designed to take advantage of PSRAM, which means there are some devices which can use this code as is however, this limitation is not immediately apparent and can cause confusion and frustration for users.  

I've been giving this some thought, and have a couple solutions in mind:  

1)  Check for available memory on the device, using heap_caps_get_largest_free_block and fail with a more informative message for the user explaining the memory issue in a concise fashion.  (always fail on ESP8266)

2)  Expand or create a new display_buffer implementation that can check for failed buffer allocs and fail into an "immediate" mode (ala tft_espi), where drawing is flushed immediately to the display.  This has it's own drawbacks, but would allow for non animated displays in a reasonable way that is intuitive to the user, using already existing ESPHome patterns.  These displays generally already have GRAM that can be written and read from using SPI, not unlike PSRAM on the device itself.

Both options have drawbacks, and no single "right answer".  I'm interested in hearing your opinion, or if I'm missing something as well.  I'm also interested in helping to solve this problem, as the ILI9488 is a good display and is an attractive option for a lot of hobbyists. 

Thank you,

**Comment by nielsnl68** [comment]
Hello @Rendman, you are correct about the memory issues. At this moment of time the ili9xxx go's in fail mode when it cant allocate enough memory. 
Your option 1 is how LVGL is setup to work. I do not know how this code change properly should be addressed. 
However i think option 2 is easier to do i think.

**Comment by davet2001** [comment]
I have not read the above comments in detail but my suggestion is to make a RAM limit a compile time problem not a run time problem.  I.e. make the preprocessor / linker generate an error if compiling for a target without enough RAM. One way of achieving this (mostly) is static allocation of the screen buffer.

**Comment by nielsnl68** [comment]
Hi @davet2001, that sounds interesting, but i have no clue on how to resolve that, when you up to that could you give me a code example?

**Comment by Rendman** [comment]
@davet2001 This sounds like a great solution to fail gracefully on devices without enough memory.

**Review by jesserockz — CHANGES_REQUESTED** [review]
Mostly looks good to me.

One thing I think is probably not needed is the `backlight_pin` which can be handled in yaml by a `binary` or `monochromatic` light the user then has full control over with automations.

**Comment by nielsnl68** [comment]
> One thing I think is probably not needed is the `backlight_pin` which can be handled in yaml by a `binary` or `monochromatic` light the user then has full control over with automations.

@jesserockz it is there as backwards compatibility of the old ili9341 component which has it named as LED_PIN. Also i did removed it before because the *pin* was only setup as output and was never used in the code. But people needed it to enable the backlight for them.

I agree with you to remove it from the display driver and move it to a light component. Can we do that in a new PR later?

**Comment by Rendman** [comment]
Hello,

 just saw the new commit.  Are you reverting this change altogether?

**Comment by nielsnl68** [comment]
No, it is just to allow easier to migrate from the old to the new driver.

**Comment by Rendman** [comment]
Around 18 Jan you mentioned that you were having problems with the ILI9488 display working properly.  Did you ever resolve them?  There is one specific issue involving 4 wire SPI mode with that controller.

**Comment by nielsnl68** [comment]
Sadly not yet. I have now ordered on myself and i hope it will be here with in the next 14 day's or so.
After that i hope it give the same issue one of the testers did have as well.

🤞

**Comment by Rendman** [comment]
I had an issue getting the ILI9488 to initialize and work correctly as well.  I dug around in the data sheet and found a note in the 4 wire SPI section that said 16-bit modes are not supported in SPI mode.

I changed the init array and it works for me now.  I don't know that we are having the same problem, but could be.  Here is the change:

 //ILI9XXX_PIXFMT,  1, 0x55,  // Interface Pixel Format = 16bit
  ILI9XXX_PIXFMT, 1, 0x66,   //ILI9488 only supports 18-bit pixel format in 4/3 wire SPI mode 

I also had to hack the pixel push routine to convert the 16 bit internal pixel representation to the 18 bit format required by the display.  I can prepare a pull request with these changes if you like.

Let me know if that works.

**Comment by nielsnl68** [comment]
@Rendman cool to know ~~, how is that doing for the colors? Do you see any side affects?
When not i will update the driver right away.~~

I see you did and fixed it 👍🏻

**Comment by nielsnl68** [comment]
Do you mind Can you PR your changes you made into my github repo? at https://github.com/nielsnl68/esphome/tree/nvds-ili9341-revisited then i'm happy to add your changes.

**Comment by Rendman** [comment]
Give me some time.  I'll prepare the pull request when I get back to the house.

**Comment by Wummeke** [comment]
I tested this PR with the following display configuration and it worked as expected:

```
display:
  - id: my_display
    platform: ili9xxx
    model: ili9488
    cs_pin: 14
    dc_pin: 27
    reset_pin: 33
    auto_clear_enabled: false
    lambda: |-
      it.fill(my_black);
      it.horizontal_line(5, 5, 50, my_red);
      it.horizontal_line(5, 55, 50, my_white);
      it.vertical_line(5, 5, 50, my_blue);
      it.vertical_line(55, 5, 50, my_yellow);
      for(auto i = 0; i<256; i++) {
        it.horizontal_line(100+5,i,100, my_red.fade_to_white(i));
        it.horizontal_line(100+110,i,100, my_red.fade_to_black(i));
        it.horizontal_line(100+215,i,100, my_red.gradient(my_blue, i));
      }

```

**Comment by dendige** [comment]
I tested the code from Wummeke with ili9488. Unfortunately there is only a dithered screen.

**Comment by nielsnl68** [comment]
> I tested the code from Wummeke with ili9488. Unfortunately there is only a dithered screen.

Can you show your yaml configuration and a link to the display you are using. Thanks.

**Comment by dendige** [comment]
esphome:
  name: touchdisplay

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "c274e5f98fc53fe782a2dcc6ddfae632"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Touchdisplay Fallback Hotspot"
    password: "sxopXIC3EVpO"

web_server:

captive_portal:

external_components: 
  - source: github://pr#4275
    components:
      - ili9xxx
      - display

time:
  - platform: homeassistant
    id: home_time

sensor:
  - platform: homeassistant
    id: temperatur
    entity_id: sensor.broadlinkrm3_temperature
    unit_of_measurement: "°C"
  - platform: homeassistant
    id: humid
    entity_id: sensor.broadlinkrm3_humidity
    unit_of_measurement: "%"

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19 

touchscreen:
  platform: xpt2046
  id: tastdisplay
  cs_pin: GPIO21
  interrupt_pin: GPIO27
  update_interval: 50ms
  report_interval: 1s
  threshold: 400
  #dimension_x: 480
  #dimension_y: 320
  calibration_x_min: 3680
  calibration_x_max: 307
  calibration_y_min: 3732
  calibration_y_max: 176
  swap_x_y: true

binary_sensor:
  - platform: touchscreen
    name: taste0
    id: touch_key0
    x_min: 20
    x_max: 90
    y_min: 50
    y_max: 120
    on_state:
      - lambda: 'ESP_LOGI("main", "key0: %s", (x ? "touch" : "release"));'

  - platform: touchscreen
    name: taste1
    id: touch_key1
    x_min: 20
    x_max: 90
    y_min: 140
    y_max: 210

  - platform: touchscreen
    name: taste2
    id: touch_key2
    x_min: 20
    x_max: 90
    y_min: 230
    y_max: 300
    on_state:
      - lambda: 'ESP_LOGI("main", "key2: %s", (x ? "touch" : "release"));'

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%  
  - id: my_yellow
    red: 60%
    green: 10%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%

font:
  - file: "../fonts/Roboto-Regular.ttf"
    id: my_font
    size: 50

  
light:
  - platform: binary
    name: "Desk Lamp"
    output: light_output

output:
  - id: light_output
    platform: gpio
    pin: GPIO32

display:
  - id: my_display
    platform: ili9xxx #ili9486
    model: ili9488
    cs_pin: GPIO15
    dc_pin: GPIO2
    reset_pin: GPIO4
    auto_clear_enabled: false
    lambda: |-
      it.fill(my_black);
      it.horizontal_line(5, 5, 50, my_red);
      it.horizontal_line(5, 55, 50, my_white);
      it.vertical_line(5, 5, 50, my_blue);
      it.vertical_line(55, 5, 50, my_yellow);
      for(auto i = 0; i<256; i++) {
        it.horizontal_line(100+5,i,100, my_red.fade_to_white(i));
        it.horizontal_line(100+110,i,100, my_red.fade_to_black(i));
        it.horizontal_line(100+215,i,100, my_red.gradient(my_blue, i));

**Comment by dendige** [comment]
`esphome:
  name: touchdisplay

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "########################"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Touchdisplay Fallback Hotspot"
    password: "sxopXIC3EVpO"

web_server:

captive_portal:

external_components: 
  - source: github://pr#4275
    components:
      - ili9xxx
      - display

time:
  - platform: homeassistant
    id: home_time

sensor:
  - platform: homeassistant
    id: temperatur
    entity_id: sensor.broadlinkrm3_temperature
    unit_of_measurement: "°C"
  - platform: homeassistant
    id: humid
    entity_id: sensor.broadlinkrm3_humidity
    unit_of_measurement: "%"

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19 

touchscreen:
  platform: xpt2046
  id: tastdisplay
  cs_pin: GPIO21
  interrupt_pin: GPIO27
  update_interval: 50ms
  report_interval: 1s
  threshold: 400
  calibration_x_min: 3680
  calibration_x_max: 307
  calibration_y_min: 3732
  calibration_y_max: 176
  swap_x_y: true

binary_sensor:
  - platform: touchscreen
    name: taste0
    id: touch_key0
    x_min: 20
    x_max: 90
    y_min: 50
    y_max: 120
    on_state:
      - lambda: 'ESP_LOGI("main", "key0: %s", (x ? "touch" : "release"));'

  - platform: touchscreen
    name: taste1
    id: touch_key1
    x_min: 20
    x_max: 90
    y_min: 140
    y_max: 210

  - platform: touchscreen
    name: taste2
    id: touch_key2
    x_min: 20
    x_max: 90
    y_min: 230
    y_max: 300
    on_state:
      - lambda: 'ESP_LOGI("main", "key2: %s", (x ? "touch" : "release"));'

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%  
  - id: my_yellow
    red: 60%
    green: 10%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%

font:
  - file: "../fonts/Roboto-Regular.ttf"
    id: my_font
    size: 50
  
light:
  - platform: binary
    name: "Desk Lamp"
    output: light_output

output:
  - id: light_output
    platform: gpio
    pin: GPIO32

display:
  - id: my_display
    platform: ili9xxx #ili9486
    model: ili9488
    cs_pin: GPIO15
    dc_pin: GPIO2
    reset_pin: GPIO4
    auto_clear_enabled: false
    lambda: |-
      it.fill(my_black);
      it.horizontal_line(5, 5, 50, my_red);
      it.horizontal_line(5, 55, 50, my_white);
      it.vertical_line(5, 5, 50, my_blue);
      it.vertical_line(55, 5, 50, my_yellow);
      for(auto i = 0; i<256; i++) {
        it.horizontal_line(100+5,i,100, my_red.fade_to_white(i));
        it.horizontal_line(100+110,i,100, my_red.fade_to_black(i));
        it.horizontal_line(100+215,i,100, my_red.gradient(my_blue, i));`

**Comment by nielsnl68** [comment]
@dendige when you add \`\`\`yaml at the top of the yaml source and \`\`\` at the bottom then the code will be shown nicely.

**Comment by dendige** [comment]
```yaml
esphome:
  name: touchdisplay

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "c----------------------------------2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Touchdisplay Fallback Hotspot"
    password: "sxopXIC3EVpO"

web_server:

captive_portal:

external_components: 
  - source: github://pr#4275
    components:
      - ili9xxx
      - display

time:
  - platform: homeassistant
    id: home_time

sensor:
  - platform: homeassistant
    id: temperatur
    entity_id: sensor.broadlinkrm3_temperature
    unit_of_measurement: "°C"
  - platform: homeassistant
    id: humid
    entity_id: sensor.broadlinkrm3_humidity
    unit_of_measurement: "%"

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19 

touchscreen:
  platform: xpt2046
  id: tastdisplay
  cs_pin: GPIO21
  interrupt_pin: GPIO27
  update_interval: 50ms
  report_interval: 1s
  threshold: 400
  #dimension_x: 480
  #dimension_y: 320
  calibration_x_min: 3680
  calibration_x_max: 307
  calibration_y_min: 3732
  calibration_y_max: 176
  swap_x_y: true

binary_sensor:
  - platform: touchscreen
    name: taste0
    id: touch_key0
    x_min: 20
    x_max: 90
    y_min: 50
    y_max: 120
    on_state:
      - lambda: 'ESP_LOGI("main", "key0: %s", (x ? "touch" : "release"));'

  - platform: touchscreen
    name: taste1
    id: touch_key1
    x_min: 20
    x_max: 90
    y_min: 140
    y_max: 210

  - platform: touchscreen
    name: taste2
    id: touch_key2
    x_min: 20
    x_max: 90
    y_min: 230
    y_max: 300
    on_state:
      - lambda: 'ESP_LOGI("main", "key2: %s", (x ? "touch" : "release"));'

color:
  - id: my_red
    red: 100%
    green: 3%
    blue: 5%
  - id: my_white
    red: 100%
    green: 100%
    blue: 100%
  - id: my_black
    red: 0%
    green: 0%
    blue: 0%  
  - id: my_yellow
    red: 60%
    green: 10%
    blue: 0%
  - id: my_blue
    red: 0%
    green: 0%
    blue: 100%

font:
  - file: "../fonts/Roboto-Regular.ttf"
    id: my_font
    size: 50
  
light:
  - platform: binary
    name: "Desk Lamp"
    output: light_output

output:
  - id: light_output
    platform: gpio
    pin: GPIO32

display:
  - id: my_display
    platform: ili9xxx #ili9486
    model: ili9488
    cs_pin: GPIO15
    dc_pin: GPIO2
    reset_pin: GPIO4
    auto_clear_enabled: false
    lambda: |-
      it.fill(my_black);
      it.horizontal_line(5, 5, 50, my_red);
      it.horizontal_line(5, 55, 50, my_white);
      it.vertical_line(5, 5, 50, my_blue);
      it.vertical_line(55, 5, 50, my_yellow);
      for(auto i = 0; i<256; i++) {
        it.horizontal_line(100+5,i,100, my_red.fade_to_white(i));
        it.horizontal_line(100+110,i,100, my_red.fade_to_black(i));
        it.horizontal_line(100+215,i,100, my_red.gradient(my_blue, i));
      }

```

**Comment by nielsnl68** [comment]
@dendige are you sure it is an ili9488 board and not one of the others? 
Can you show me the link to that display?

**Comment by dendige** [comment]
I soldered the Display to a pcb so I can‘t Look a the backside. WhatsApp Option do I habe Tobias identify the Display?Von meinem iPhone gesendetAm 03.03.2023 um 16:13 schrieb nielsnl68 ***@***.***>:﻿
@dendige are you sure it is an ili9488 board and not one of the others?
Can you show me the link to that display?

**Comment by Rendman** [comment]
@nielsnl68 were you able to test with your display?

**Comment by dendige** [comment]
The Display was sold by amazon as: "HGY LCD-Modul TFT Touch Screen Display Serial Peripheral Interface ILI9488 HD 480x320 3,5 Zoll"

**Comment by Wummeke** [comment]
Dendige, I see in the datasheet of your board (https://cdn.shopify.com/s/files/1/1509/1638/files/ESP32_DevKit_C_V4_Pinout.pdf?v=1615364529) that the pins you use  (GPIO15, GPIO2 and GPIO4) for the screen are used for the SD card interface. Perhaps you could try three different pins, to see if that makes a difference?

**Comment by dendige** [comment]
@Wummeke: I use Dustin Watts TFT-Combiner ([https://github.com/DustinWatts/ESP32_TFT_Combiner](url)) to connect the nodemcu to the display. So I can't change the pins.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
