### PR TITLE
Allow mdns services to be exposed by config

### PR DESCRIPTION
**Pull request by elupus**
# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2553

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
mdns:
  services:
    - name: "_nibegw"
      protocol: "_udp"
      port: 10090
      txt:
        read_port: 10091
        write_port: 10092
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nagyrobi** [comment]
Does it work properly on esp-idf platform?

**Comment by elupus** [comment]
As long as the standard mdns work, then yes. You can test it as external component.

**Comment by jesserockz** [comment]
Curious, for what purpose would you need to expose extra mdns services?

**Comment by tube0013** [comment]
> Curious, for what purpose would you need to expose extra mdns services?

I'm interested in this as I can use it to provide discovery information for networked zigbee coordinators for HA - ie: 

```
mdns:
  services:
    - service: "_tubeszb"
      protocol: "_tcp"
      port: 6638
      txt:
        version: 1.0
        name: TubesZB
        radio_type: znp
        baud_rate: 115200
        data_flow_control: software
```

**Review by jesserockz — APPROVED** [review]
Happy with this as its purely additive

**Pull request merged**
