### PR TITLE
Support for MCP9600 Thermocouple Amplifier

### PR DESCRIPTION
**Pull request by mreditor97**
# What does this implement/fix?
Adds support for the MCP9600 I2C Thermocouple Amplifier.
This can also work with the MCP9601.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2217

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: mcp9600
    thermocouple_type: K
    address: 0x67
    hot_junction:
      name: "Thermocouple Temperature"
    cold_junction:
      name: "Ambient Temperature"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs/pull/2217).

### CODE REVIEW

**Comment by mreditor97** [comment]
Is it possible to do a check within the configuration validation step to be able to check to ensure that the I2C bus frequency is high enough to support the device? As the frequency must be higher than 100Khz or it does not work?

**Comment by jesserockz** [comment]
> Is it possible to do a check within the configuration validation step to be able to check to ensure that the I2C bus frequency is high enough to support the device? As the frequency must be higher than 100Khz or it does not work?

Yes you could look at doing that with `FINAL_VALIDATE_SCHEMA`

**Comment by mreditor97** [comment]
> > Is it possible to do a check within the configuration validation step to be able to check to ensure that the I2C bus frequency is high enough to support the device? As the frequency must be higher than 100Khz or it does not work?
> 
> Yes you could look at doing that with `FINAL_VALIDATE_SCHEMA`

Thanks, I shall look into adding this into the validation step.

**Comment by mreditor97** [comment]
After going through the codebase, looking for some examples of ``FINAL_VALIDATION_SCHEMA``, I have only found examples of it being used with UART, and SPI - so there are no previous uses of any I2C validation checks, however, I'm thinking that I could use the ``inherit_property_from`` function like this:

```python
FINAL_VALIDATION_SCHEMA = cv.All(
     inherit_property_from(CONF_FREQUENCY, CONF_I2C, transform=inherit_unit_of_measurement),
)
```

Would you say that is the correct usage of the function? If that is correct, then how would I then go about checking the value is above 100Khz. Potentially by adding this in on the ``inherit_property_from`` line in the code that is above?
```python
cv.All(
     cv.frequency, cv.Range(min=100000, min_included=True)
),
```
Unfortunately I am away from my development environment so I am unable to test it to see if my thinking is correct.

**Comment by jesserockz** [comment]
No, `inherit_property_from` is for another purpose.

Basically you want to do similar to the UART implementation. You will need to create a new function in `i2c/__init_.py` that adds this function and has a kwarg for `min_frequency` perhaps.

**Comment by mreditor97** [comment]
I have rebased the `mcp9600` sensor component. The I2C frequency check has also been added so it is possible to verify that the I2C bus frequency is above or equal to the required frequency.

**Comment by mreditor97** [comment]
@jesserockz This should be ready for a review now.

Thanks

**Comment by emuehlstein** [comment]
Is it possible to incorporate support for multiple mcp9600s with configurable i2c addresses?  I use these several of these with each esp, each with a different bus address.

**Comment by MrEditor97** [comment]
> Is it possible to incorporate support for multiple mcp9600s with configurable i2c addresses?  I use these several of these with each esp, each with a different bus address.

Yes, it is possible to set these up more than one at a time. With the Adafruit MCP9600, you can solder some contacts on it which will change the I2C address. They will be between `0x60` and `0x67` according to Adafruit's I2C Address sheet.
```yaml
sensors:
  - platform: mcp9600
    address: 0x67
    hot_junction:
      name: "Thermocouple One"
  - platform: mcp9600
    address: 0x66
    hot_junction:
      name: "Thermocouple Two"
```

**Comment by mreditor97** [comment]
> Is it possible to incorporate support for multiple mcp9600s with configurable i2c addresses?  I use these several of these with each esp, each with a different bus address.

Yes, it is possible to set these up with more than one at a time. With the Adafruit MCP9600, you can solder some contacts on it which will change the I2C address. They will be between `0x60` and `0x67` according to Adafruit's I2C Address sheet.
```yaml
sensor:
  - platform: mcp9600
    address: 0x67
    hot_junction:
      name: "Thermocouple One"
  - platform: mcp9600
    address: 0x66
    hot_junction:
      name: "Thermocouple Two"
```

Hope this helps!

**Comment by emuehlstein** [comment]
> > Is it possible to incorporate support for multiple mcp9600s with configurable i2c addresses?  I use these several of these with each esp, each with a different bus address.
> 
> Yes, it is possible to set these up with more than one at a time. With the Adafruit MCP9600, you can solder some contacts on it which will change the I2C address. They will be between `0x60` and `0x67` according to Adafruit's I2C Address sheet.
> 
> ```yaml
> sensor:
>   - platform: mcp9600
>     address: 0x67
>     hot_junction:
>       name: "Thermocouple One"
>   - platform: mcp9600
>     address: 0x66
>     hot_junction:
>       name: "Thermocouple Two"
> ```
> 
> Hope this helps!

Fantastic!  I didn't see an address line in the example above so I had to ask.  Thank you - this will eliminate a pile of custom code from my current setup.

**Comment by mreditor97** [comment]
> > > Is it possible to incorporate support for multiple mcp9600s with configurable i2c addresses?  I use these several of these with each esp, each with a different bus address.
> > 
> > Yes, it is possible to set these up with more than one at a time. With the Adafruit MCP9600, you can solder some contacts on it which will change the I2C address. They will be between `0x60` and `0x67` according to Adafruit's I2C Address sheet.
> > 
> > ```yaml
> > sensor:
> >   - platform: mcp9600
> >     address: 0x67
> >     hot_junction:
> >       name: "Thermocouple One"
> >   - platform: mcp9600
> >     address: 0x66
> >     hot_junction:
> >       name: "Thermocouple Two"
> > ```
> > 
> > Hope this helps!
> 
> Fantastic!  I didn't see an address line in the example above so I had to ask.  Thank you - this will eliminate a pile of custom code from my current setup. 

I have updated it now. The docs do include it ready for when the integration is merged into the code base!

I hope it works well for you, let me know if there are any problems. From my testing, everything has been working as expected.

**Comment by mreditor97** [comment]
@jesserockz Is this ready for merging now?

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
