### PR TITLE
Nextion brightness setting requires an assignment

### LINKED ISSUE #3342: Nextion brightness argument breaks the script
### The problem

I have a script that runs fine and everything displays as expected on a Nextion display, but the display is really bright during the evening, so I'd like to decrease its brightness programmatically. Seems to be trivial, doesn't it?

Changing the brightness from script or using the `brightness` option of the display component makes the script fail. No updates happen to the screen.

### Which version of ESPHome has the issue?

2022.5.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.6.2

### What platform are you using?

ESP8266

### Board

WEMOS-D1-MINI

### Component causing the issue

display/nexion

### Example YAML snippet

```yaml
esphome:
  name: internal-display

esp8266:
  # board: esp01_1m
  board: d1_mini

uart:
  rx_pin: D1
  tx_pin: D6
  baud_rate: 115200

# Enable logging
logger:
#  baud_rate: 0  # disables logging

# Enable Home Assistant API
api:
  encryption:
    key: "redacted"

ota:
  password: "redacted"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
    - seconds: 0
      minutes: /1
      then:
      - lambda:
          auto time = id(homeassistant_time).now();
          id(nextion_clock).set_state(time.strftime("%H:%M"), false, true);

text_sensor:
  - platform: nextion
    nextion_id: internal_display
    id: nextion_clock
    component_name: page0.clock
  - platform: nextion
    nextion_id: internal_display
    id: nextion_temperature
    component_name: page0.temperature
      
sensor: 
  - platform: homeassistant   # Outside temperature
    id: temperature_outside    
    entity_id: sensor.trisensor_air_temperature
    on_value:
      then:
        - lambda:
            char buffer [6];
            int n;
            n=sprintf (buffer, "%2.1f", x);
            id(nextion_temperature).set_state(buffer, false, true);

display:
  - platform: nextion
    id: internal_display
    update_interval: 5s
    # Removing the following comment fails the script
    #brightness: 10%
```

### Anything in the logs that might be useful for us?

```txt
-
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by nagyv**
Fixes https://github.com/esphome/issues/issues/3342

# What does this implement/fix?

Quick description and explanation of changes

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [<link to issue>](https://github.com/esphome/issues/issues/3342)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

See https://github.com/esphome/issues/issues/3342

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by SenexCrenshaw — APPROVED** [review]
Good catch

**Comment by jesserockz** [comment]
@SenexCrenshaw The ~original~ existing code in ESPHome works just fine with my NSPanel

**Comment by nagyv** [comment]
@jesserockz What do you mean by original code? Is that the code from me in the issue description?

**Comment by jesserockz** [comment]
@nagyv Sorry I mean my panel works fine with the current ESPHome code, no modifications needed as I wrote in the issue comments. 
I am not saying this is not needed as it could be a version difference for the nextions that is doing it differently. I will try this patch with my NSPanel to confirm it still works.

**Comment by jesserockz** [comment]
My panel still works with thee changes so happy to merge in. 
If people say it stops working, we can look at it again.

**Pull request merged**
