### PR TITLE
Ensure names containing characters other than `a-z` `A-Z` `0-9` or `_` are unique

### LINKED ISSUE #5135: esphome does not generate unique IDs
### The problem

I have an air gradient air quality sensor which has a name and friendly_name of ag1.  It contains a pms5003 particulate matter sensor which provides pm1.0, pm2.5 and pm10 values. There seems to be a clash between the ID’s that are chosen for the pm1.0 and pm10 entities.  The names for the pm1.0 and pm10 entities are getting munged such that they are identical.  This creates a conflict which prevents one of them from being used.  Deleting and re-adding the entities and device doesn't seem to resolve the issue.

Log message:

ERROR (MainThread) [homeassistant.components.sensor] Platform esphome does not generate unique IDs. ID 84:F3:EB:16:77:BC-sensor-pm_10m is already used by sensor.ag1_pm_10m - ignoring sensor.ag1_pm_10m

Relevant sections of ag1’s config:

```
esphome:
  name: ag1
  friendly_name: ag1

sensor:
  - platform: pmsx003
    type: PMSX003
    uart_id: uartuno
    pm_1_0:
      id: pm11
      name: "pm 1.0µm"
    pm_2_5:
      id: pm251
      name: "pm 2.5µm"
    pm_10_0:
      id: pm101
      name: "pm 10µm"
    update_interval: 120s
```

### Which version of ESPHome has the issue?

2023.11.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.11.2

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

pmsx003

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by bdraco**
## Breaking change

Home Assistant users may need to remove the config entry, and set it back up again if the name contained non-ascii characters.  Alternatively the entity can be manually renamed.

# What does this implement/fix?

Instead of dropping chars in `str_sanitize` we now replace them with `_` to reduce the chance of collisions.  

This will cause the unique ids to change for any entity that previously had characters disallowed by sanitize

fixes esphome/issues#5135

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
Traveling so I can't test this right now but will when I get back home later in the week

**Comment by bdraco** [comment]
Also need to modify it to make a new string instead

**Comment by bdraco** [comment]
Will pick this back up when its not after midnight and I've just flown 17 hours 😉

**Review by jesserockz — APPROVED** [review]
LGTM

**Comment by swifty99** [comment]
Thanks for having better unique IDs. 
This change may have side effects, as described here: https://github.com/bramstroker/homeassistant-powercalc/issues/1919#issuecomment-1820418175

could you have a look into that?

**Comment by bdraco** [comment]
> Thanks for having better unique IDs. This change may have side effects, as described here: [bramstroker/homeassistant-powercalc#1919 (comment)](https://github.com/bramstroker/homeassistant-powercalc/issues/1919#issuecomment-1820418175)
> 

I would expect there is some fallout, as this PR is marked as a breaking change.

> could you have a look into that?

That looks unrelated to this PR.  Please open an issue, PRs are not a place to get support.

**Comment by swifty99** [comment]
> I would expect there is some fallout, as this PR is marked as a breaking change.
> 
Maybe my comment was a little unclear.

The last ESPHome unique ID change destroyed almost all of my energy history. If that was assumed for a breaking change, so may it be. I just wanted to point out the consequences.

Home assistant sometimes tries to provide repair options. In a case of complete data loss this is what I was hoping for.
I will try to ask at the appropriate forum,  how to get most my energy statistics of the last years back.

**Comment by bdraco** [comment]
> 
> 
> > I would expect there is some fallout, as this PR is marked as a breaking change.
> 
> > 
> 
> Maybe my comment was a little unclear.
> 
> 
> 
> The last ESPHome unique ID change destroyed almost all of my energy history. If that was assumed for a breaking change, so may it be. I just wanted to point out the consequences.
> 
> 
> 

The unique id change in 2023.11.x was not expected to be breaking concerning entity ids as they should be migrated.  The unique ids themselves did change though so if something was using those instead of tracking on the entity id it would be expected to break.

Nobody has opened any issues in HA core that I'm aware of so this is the first time I'm hearing of a problem.  If you think there is a bug in the unique id migration process in HA, please continue at https://github.com/home-assistant/core/issues/new/choose


> Home assistant sometimes tries to provide repair options. In a case of complete data loss this is what I was hoping for.
> 
> I will try to ask at the appropriate forum,  how to get most my energy statistics of the last years back. 
> 
> 
> 
> 
> 
>

**Comment by bdraco** [comment]
flashed existing device and added the below yaml, no more error in the log

Screenshot 2023-11-23 at 5 19 58 PM



```yaml

sensor:
  - platform: template
    id: pm11
    name: "pm 1.0µm"
    lambda: return 1.0;
  - platform: template
    id: pm251
    name: "pm 2.5µm"
    lambda: return 2.5;
  - platform: template
    id: pm101
    name: "pm 10µm"
    lambda: return 10;

```

```json
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "f7e6bc63b2e0674fab8c0365e1012faa",
        "device_class": null,
        "device_id": "8d613f686c779f1fba6fa0491afe9407",
        "disabled_by": null,
        "entity_category": null,
        "entity_id": "sensor.picoproxy_pm_1_0_m",
        "hidden_by": null,
        "icon": null,
        "id": "6dd258d5b47d98cc68dc286cce6c3bcc",
        "has_entity_name": true,
        "name": null,
        "options": {
          "conversation": {
            "should_expose": false
          }
        },
        "original_device_class": null,
        "original_icon": null,
        "original_name": "pm 1.0µm",
        "platform": "esphome",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "30:83:98:E1:1D:24-sensor-pm_1_0_m",
        "previous_unique_id": null,
        "unit_of_measurement": null
      },
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "f7e6bc63b2e0674fab8c0365e1012faa",
        "device_class": null,
        "device_id": "8d613f686c779f1fba6fa0491afe9407",
        "disabled_by": null,
        "entity_category": null,
        "entity_id": "sensor.picoproxy_pm_2_5_m",
        "hidden_by": null,
        "icon": null,
        "id": "54194c54de60ac2f92cec92937343dcf",
        "has_entity_name": true,
        "name": null,
        "options": {
          "conversation": {
            "should_expose": false
          }
        },
        "original_device_class": null,
        "original_icon": null,
        "original_name": "pm 2.5µm",
        "platform": "esphome",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "30:83:98:E1:1D:24-sensor-pm_2_5_m",
        "previous_unique_id": null,
        "unit_of_measurement": null
      },
      {
        "aliases": [],
        "area_id": null,
        "capabilities": null,
        "config_entry_id": "f7e6bc63b2e0674fab8c0365e1012faa",
        "device_class": null,
        "device_id": "8d613f686c779f1fba6fa0491afe9407",
        "disabled_by": null,
        "entity_category": null,
        "entity_id": "sensor.picoproxy_pm_10_m",
        "hidden_by": null,
        "icon": null,
        "id": "865a8574ad346fe277888bfeba1c8310",
        "has_entity_name": true,
        "name": null,
        "options": {
          "conversation": {
            "should_expose": false
          }
        },
        "original_device_class": null,
        "original_icon": null,
        "original_name": "pm 10µm",
        "platform": "esphome",
        "supported_features": 0,
        "translation_key": null,
        "unique_id": "30:83:98:E1:1D:24-sensor-pm_10_m",
        "previous_unique_id": null,
        "unit_of_measurement": null
      }
```

**Comment by bdraco** [comment]
Tested on a few production devices as well to make sure there weren't any unexpected side effects.  All good

**Pull request merged**
