### PR TITLE
Create basic ES8388 DAC amplifier component

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix?

This is the DAC used in the Raspiaudio Muse Luxe, and this is a basic implementation which is specific to that device for now.

```yaml
external_components:
  - source: github://pr#3552
    components: [es8388]

es8388:
```

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
Just recently got a Muse Luxe Speaker so I will be continuing this component next year

**Comment by cociweb** [comment]
Just a quick comment/feedback: with this PR the ESP32 Audio kit's  jack output is not working for me (silent with some noise), only the onboard 3W speaker connectors gives a quiet audio output.

**Comment by nagyrobi** [comment]
> Just a quick comment/feedback: with this PR the ESP32 Audio kit's jack output is not working for me (silent with some noise), only the onboard 3W speaker connectors gives a quiet audio output.

@cociweb what config did you use and what board revision do you have?

I have ESP32 Audio Kit v2.2 A247, and tried a few GPIO mappings I found over the web but couldn't figure out a good one:

```yaml
es8388:

i2c:
  sda: GPIO33
  scl: GPIO32
  frequency: 400kHz


media_player:
  - platform: i2s_audio
    name: "ESP32 Audio Kit"
    dac_type: external
    i2s_lrclk_pin: GPIO25
    i2s_dout_pin: GPIO26
    i2s_bclk_pin: GPIO27
    mode: stereo
    mute_pin:
      number: GPIO21
      inverted: true
```
No sound at all in the earphone output. Only helicopter noise on the speaker output connectors.

A few configs I [found](https://github.com/muvox-io/euphonium/blob/master/dacs.json):

```
       "board": "AI-Thinker Audio board (A1S ES8388)",
       "dac": "ES8388",
       "mclk": "0",
       "bck": "27",
       "ws": "25",
       "data": "26",
       "scl": "32",
       "sda": "33"


       "board":"Espressif LyraT v4.3",
       "dac":"ES8388",
       "mclk":"0",
       "bck":"5",
       "ws":"25",
       "data":"26",
       "scl":"23",
       "sda":"18"
```

**Comment by nagyrobi** [comment]
@jesserockz I've [placed a few ideas](https://github.com/esphome/feature-requests/issues/1882#issuecomment-1492243847) do you think it's worth considering them and merge after, or should I try to make the docs for this as it is now? Can't test myself because I have no Muse Luxe, but I do have an ESP32 Audio Kit with the same DAC, would be nice if at least basic sound would come out of that too.

**Comment by NightDav** [comment]
Hi,
I'm trying to have my ESP32-A1S audio kit with ES8388 working with this code but it's not successful yet.

There is a great ES8388 implementation from pschatzmann here : https://github.com/pschatzmann/arduino-audiokit/tree/main/src/audio_driver/es8388 and this code is working on my board, but it's much more complicated to integrate here.

Could you give feedback on your plan for this ES8388 integration so I can help (testing / code integration) ?

**Comment by jesserockz** [comment]
@NightDav At the moment, this component is basically hardcoded to the config on the RaspiAudipo Muse Luxe. It would need to be expanded to configure for other boards.

**Comment by ecertik** [comment]
Hi, is there any possibility to update this great  component to use with ESP32-s3 with other than default MCLK pin? For example GPIO38 in my case? Because -s3 is a bit different, change just this line:
PIN_FUNC_SELECT(PERIPHS_IO_MUX_GPIO0_U, FUNC_GPIO0_CLK_OUT1);
will not work (I tried).

certik

**Comment by sbur83** [comment]
> @jesserockz I've [placed a few ideas](https://github.com/esphome/feature-requests/issues/1882#issuecomment-1492243847) do you think it's worth considering them and merge after, or should I try to make the docs for this as it is now? Can't test myself because I have no Muse Luxe, but I do have an ESP32 Audio Kit with the same DAC, would be nice if at least basic sound would come out of that too.

```

i2c:
  sda: GPIO33
  scl: GPIO32
  scan: true

external_components:
  - source: github://pr#3552
    components: [es8388]

es8388:

i2s_audio:
  i2s_lrclk_pin: GPIO25
  i2s_bclk_pin: GPIO27

microphone:
  - platform: i2s_audio
    id: thinker_mic
    i2s_din_pin: GPIO35
    adc_type: external
    pdm: false

media_player:
  - platform: i2s_audio
    id: thinker_media_player
    name: "thinker media player"
    dac_type: external
    i2s_dout_pin: GPIO26 
    mode: stereo
    mute_pin:
      number: GPIO21
      inverted: true
      
voice_assistant:
  microphone: thinker_mic

switch:
  - platform: gpio
    pin: GPIO21
    name: "AMP Switch"
    restore_mode: ALWAYS_ON
 
binary_sensor:
  - platform: status
    name: "Node Status"
    id: system_status
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
      mode:
        input: true
    name: "Headphone Jack Status"
#  - platform: gpio
#    pin:
#      number: GPIO12
#      inverted: true
#      mode:
#        input: true
#        pulldown: true
#    name: "Microphone Jack Status"
  - platform: gpio
    pin:
      number: GPIO34
      inverted: true
      mode:
        input: true
    name: "SD Status"
  - platform: gpio
    pin:
      number: GPIO36
      inverted: true
    name: "Key 1"
    id: key1
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    name: "Key 2"
    id: key2
    on_press:
      - voice_assistant.start:
    on_release:
      - voice_assistant.stop:
  - platform: gpio
    pin:
      number: GPIO19 #D5 RED LED
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 3"
    id: key3
  - platform: gpio
    pin:
      number: GPIO23
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 4"
    id: key4
  - platform: gpio
    pin:
      number: GPIO18
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 5"
    id: key5
  - platform: gpio
    pin:
      number: GPIO05
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Key 6"
    id: key6 
light:
  - platform: binary
    name: "Test LED 1"
    output: light_output_1
  - platform: binary
    name: "Test LED 2"
    output: light_output_2
 
output:
  - id: light_output_1
    platform: gpio
    pin: GPIO22
    inverted: true
  - id: light_output_2
    platform: gpio
    pin: GPIO19
    inverted: true
```
This is giving me sound from the speaker output using Jesse's component with the ESP Audio Kit, but I can't get the microphone working. Reading another form there is mention that to switch between microphone and speaker there needs to be an i2c command sent. I assume this would need to be done in the component but I wouldn't have the slightest how to do it.

**Comment by George1422** [comment]
@sbur83 I have the same configuration as you. Are you having a problem when playing audio with the ESP32 Audio Kit where the audio volume is reset to 100%. You can adjust it down while its playing, but if you send another audio stream to the player it reverts back to 100%? I know that this issue should have been covered in issue number 4433 https://github.com/esphome/issues/issues/4433 and marked resolved. 

I'm wondering if 
1. You are seeing the same results with a fresh rebuild of the image
2. It could be related to the es8388 needing to be controlled over I2C (but then again I can adjust the audio volume while its playing). 

I've also noticed some instability in the board in that it will start making some static noise at random. Playing something will remove the static noise but its a bit strange. I'm also driving a rgb matrix display at the same time so there might be some unexpected interactions there too. I'm trying to correlate what I'm seeing with what others are experiencing. 

Also I can confirm that the built in microphones do not work with the assistant.

**Comment by sbur83** [comment]
@George1422 I haven't really used it other than in testing and didn't pay attention to volume setting to 100%. It wouldn't suprise me at all tho as I've had similar issue using the esphome i2s component in other projects where on rebooting esp32 the volume always goes up to 100%. I've also had similar interference noise when using longer speaker wire that I assume is emf and short speaker wire was recommended in the documentation iirc. Anyway we are probably digressing from the topic a bit I just wanted it known this component is partially working with the audio kit.

**Comment by NightDav** [comment]
Same here with ESP32-A1S Audio Kit: media player is OK but no mic signal seems to be transferred to voice assistant.

For the volume, this was a bug in last i2s implementation, it is fixed now. Notice that the volumes is controlled by the media player and not the es8388 chip directly since volume is at max by the hard coded implementation.

I've tried to look at all registers / bits, comparing how init is done here and how it's done in espressif SDK, and even trying some modifications. Init sequence is not exactly the same but nothing obviously wrong. I've not been able to make it work.

~~@jesserockz : could you explain more in details with format is expected by the i2s mic (sampling rate / mono vs stereo / PCM format or pdm /....), I can't find exact details in the code ? Thanks !~~

**Comment by George1422** [comment]
@NightDav Thank you for the confirmation. After I posted that last night I realized I still had this in my yaml file which forced the fix and current code to not be applied. Once I removed it and recompiled the audio volume started working again. I wan't sure if it was a fluke or not but it seems persistent now. 

` - source: github://pr#4775
    components: [adc, i2s_audio, microphone]
    refresh: 0s`

I've been reading up on that audio codec and its a pretty interesting critter. 
https://www.pschatzmann.ch/home/2021/12/06/the-ai-thinker-audio-kit-experience-or-nothing-is-right/

The user guide has in section "8.4.3 Single ended Microphone input circuit and sample code" has the setup code for single ended mic input. It doesn't talk about codec or audio streams. 
https://dl.radxa.com/rock2/docs/hw/ds/ES8388%20user%20Guide.pdf

**Comment by NightDav** [comment]
I finally found out tonight how to have the ESP32-A1S mic working (still not perfect but it works).:

First, on my board (V2.2 A247) I have a hardware bug, and it seems to be present for most (all ?) versions of the boards => I have discrete microphones (through holes) and the capacitors are not correctly placed on the board. see [schematics here](https://drive.google.com/file/d/1_BVt7JmH4DF2Ci9sU4MnrvydLPv5qu5h/view?usp=sharing), C22 and C24 are populated instead of C17 and C19. The picture of the mod is [here](https://drive.google.com/file/d/1bNTqA7qR6yINwzaFS8-NN3DnJnNqaQof/view?usp=sharing). Unfortunately this is quite difficult to fix without good soldering skills...


Secondly with the hard wired configuration you have to modify two registers to have it working properly. 

The first one is very specific to the ESP32-A1S audio kit because the microphones are in diff mode (as detailed in the schematics above). I don't have the Muse Luxe schematics but it should be different. @jesserockz I don't know how to handle this option in the code ? something like mic_mode : single | diff ?
The fix for the Audio Kit board is to change the value in register 0x0A :
`this->write_byte(0x0A, 0xF0);  // Mic input : L-R differential
`

The second register to change is to match the audio mono right channel. This change has to be done for all versions of es8388 boards in order to match the i2s_audio mic config for the voice assistant:
`this->write_byte(0x0B, 0x10);  // set to Mono Right`

with these fixes I've been able to send voice commands to my home assistant, even if the voice recognition is far from perfect. I have to speak close to the mic to have my voice properly recognized, even if the gains are set to maximum. Chip has embedded automatic gain control, but it is disabled in the current config, I'll try to configure / enable it in the future and do some tests.

**Comment by George1422** [comment]
@NightDav Initially I found it hard to believe you were right, but you are. I have the same AI Thinker [original developer] board (or its a clone) the silkscreen says AI Tinker but that bit is the easy part to mask. It is also version 2.2 that I picked up in early 2022 for a different project. I can confirm that the mic-out of the 4 pin mic (not installed) is connected to the capacitor that is out of place. I did a quick google search for the esp32 audio kit (pictures) and some boards are like the ones you and I have. Others have the cap in the right spot, and still others have both caps in place with the condenser mic. I assume my board is a clone because its wired wrong, and I don't think the developer would have made that mistake. 

I'm wondering if an easier way to hack this is to solder bridge the mic side between the condenser mic and the not installed mic.  There is no devices between the out pin on the not installed mic and that cap and it looks like the left side of those two caps 22 and 19 are going to the same location on the schematic (I did not test this when I had the board out). If they are connected together on the left side then creating a solder bridge on the right side is easier to do. I need to get the board out and see if I'm right. 

I do have to say well done on finding this flaw. It would have been the last thing I would have considered to be at fault here. For my project the mic doesn't matter but for others it might be a deal beaker.

**Comment by NightDav** [comment]
Did some tests with ALC. It definitely improves speech recognition for me (still not perfect).
This is compatible with all es8388 mic implementations and is not specific to ESP32 Audio kit so I think it should be default config.
The following code is based on the user manual (the one mentioned by @George1422 few posts above), specifically the section about voice recording. User manual says that hold / decay and attack timing could be adjusted when not sampling at 48kHz (we are at 16kHz), but it did not change anything for me, so I kept recommended values.

Change :
`this->write_byte(0x09, 0x88);`
to
`this->write_byte(0x09, 0x77); // +21dB : recommended value for ALC & voice recording`

and add the following section where the `// ALC OFF` comment is:
` // ALC Config (as recommended by ES8388 user guide for voice recording)`
`  this->write_byte(0x12, 0xe2); // Reg 0x12 = 0xe2 (ALC enable, PGA Max. Gain=23.5dB, Min. Gain=0dB)`
`  this->write_byte(0x13, 0xa0); // Reg 0x13 = 0xa0 (ALC Target=-1.5dB, ALC Hold time =0 mS)`
`  this->write_byte(0x14, 0x12); // Reg 0x14 = 0x12(Decay time =820uS , Attack time = 416 uS)`
`  this->write_byte(0x15, 0x06); // Reg 0x15 = 0x06(ALC mode)`
`  this->write_byte(0x16, 0xc3); // Reg 0x16 = 0xc3(nose gate = -40.5dB, NGG = 0x01(mute ADC))`

At some point it would be nice to include register names in some .h file, to make this code easier to read.

I'm sorry to paste the code here instead of submitting it directly but as an hardware electronics guy I'm not very familiar with software workflows ! :(

**Comment by mulcmu** [comment]
@NightDav Is this what your ALC changes should look like? 

```
........
  // i2S 16b
  this->write_byte(0x0C, 0x0C);
  // MCLK 256
  this->write_byte(0x0D, 0x02);
  // ADC Volume
  this->write_byte(0x10, 0x00);
  this->write_byte(0x11, 0x00);
  
  // ALC OFF  original
  //this->write_byte(0x03, 0x09);
  //this->write_byte(0x2B, 0x80);

  //@nightDav
  // ALC Config (as recommended by ES8388 user guide for voice recording)
  this->write_byte(0x12, 0xe2); // Reg 0x12 = 0xe2 (ALC enable, PGA Max. Gain=23.5dB, Min. Gain=0dB)
  this->write_byte(0x13, 0xa0); // Reg 0x13 = 0xa0 (ALC Target=-1.5dB, ALC Hold time =0 mS)
  this->write_byte(0x14, 0x12); // Reg 0x14 = 0x12(Decay time =820uS , Attack time = 416 uS)
  this->write_byte(0x15, 0x06); // Reg 0x15 = 0x06(ALC mode)
  this->write_byte(0x16, 0xc3); // Reg 0x16 = 0xc3(nose gate = -40.5dB, NGG = 0x01(mute ADC))

  this->write_byte(0x02, 0xF0);
  delay(1);
..........
```

**Comment by NightDav** [comment]
Sorry my explanation was not clear, this is what it should be:

```c
........
  // i2S 16b
  this->write_byte(0x0C, 0x0C);
  // MCLK 256
  this->write_byte(0x0D, 0x02);
  // ADC Volume
  this->write_byte(0x10, 0x00);
  this->write_byte(0x11, 0x00);
  
  //@nightDav
  // ALC Config (as recommended by ES8388 user guide for voice recording)
  this->write_byte(0x12, 0xe2); // Reg 0x12 = 0xe2 (ALC enable, PGA Max. Gain=23.5dB, Min. Gain=0dB)
  this->write_byte(0x13, 0xa0); // Reg 0x13 = 0xa0 (ALC Target=-1.5dB, ALC Hold time =0 mS)
  this->write_byte(0x14, 0x12); // Reg 0x14 = 0x12(Decay time =820uS , Attack time = 416 uS)
  this->write_byte(0x15, 0x06); // Reg 0x15 = 0x06(ALC mode)
  this->write_byte(0x16, 0xc3); // Reg 0x16 = 0xc3(nose gate = -40.5dB, NGG = 0x01(mute ADC))

  // Power on ADC 
  this->write_byte(0x03, 0x09);
  this->write_byte(0x2B, 0x80);

  this->write_byte(0x02, 0xF0);
  delay(1);
..........
```

**Comment by George1422** [comment]
How can I view the code related to this pull request, I can only seem to find the diff code changes. The reason why I ask is with the esp32 audio kit, it seems like something is not getting initialized on startup. More often than not when I recompile the media player and send it to the audio kit with the ES8388 audio chip, I get what I call digital static after about 30 seconds, and it continues on. Its not white noise but a noise that has a rhythm to it. If turn the amp off with gpio 22 the audio noise stops, when I turn the amp back on it comes back. So the noise is being generated before the audio amp stage. I can make it stop by having it play anything. Even a 1 second audio file with silence. When I tell it to play I hear a pop then it goes quiet. If there is audio to play it plays it and then goes silent again and its normal like my other esp32 media players that use different I2S codec amps. The other I2S codec amps do not act this way, its only the ES8388 chip. 
So the thought is there must be some additional initialization that goes on just before it plays the audio file that needs to be configured in the startup/init code for the es8388.

**Comment by roblamoreaux** [comment]
> I'm wondering if an easier way to hack this is to solder bridge the mic side between the condenser mic and the not installed mic. There is no devices between the out pin on the not installed mic and that cap and it looks like the left side of those two caps 22 and 19 are going to the same location on the schematic (I did not test this when I had the board out). If they are connected together on the left side then creating a solder bridge on the right side is easier to do. I need to get the board out and see if I'm right._

Looking at the schematic and the picture this is what I would do since 0402s are a pain to move with my old eyes.  I haven't done it yet since the board is at home, but if mine is the same I'll bring it in to work tomorrow and uses the rework station.

Rob

**Comment by George1422** [comment]
> Looking at the schematic and the picture this is what I would do since 0402s are a pain to move with my old eyes. I haven't done it yet since the board is at home, but if mine is the same I'll bring it in to work tomorrow and uses the rework station.

Surely check this out for yourself, but it looks like the side of the cap (plus missing cap) closest to the mic (on each side) should be bridged. The solder pads farthest from the mics appear to be already bridged in circuit. For the life of me I can normally create a solder bridge without thinking twice, but not with this board, I ended up using some 30 gauge wire wrap wire to make the bridge. You are right those components are really tiny, having a microscope to work on them is almost a necessity, I think I got lucky.

**Comment by sbur83** [comment]
Thanks everyone, this is working on the ESP32 Audiokit with hardware fix and NightDav's edits. 
@George1422 you need to copy the component from jesserocks repository, save it in your local esphome/components folder then include the suggested edit in the es8388_component.cpp file and point to it in esphome .yaml. Well that's what I did and it's working, I'm not sure I have gone the best way about it. 
Maybe @NightDav could make an audio kit branch with PR? 
@George1422 :Here's an example of the .yaml:
```
external_components:
#  - source: github://pr#3552
#    components: [es8388]
  - source:
      type: local
      path: components
es8388:
```

**Comment by mulcmu** [comment]
I started a separate repository with the patches.  Any luck on extra init to address the "digital static"?

```
external_components:
  - source: github://mulcmu/esphome-es8388-a1s@nightdav-patch
    components: [es8388]
    refresh: 0s

  #### Not needed if on 2023.5.0 or later
  # - source: github://pr#4775
  #   components: [adc, i2s_audio, microphone]
  #   refresh: 0s
```

**Comment by NightDav** [comment]
I don't have this digital noise on my board, so maybe it's related to your setup...
how do you power the board ? uart usb / power usb / battery ? maybe if you try with different cable os charger it can improve it.

The implementation of the chip configuration that we perform with this driver (static and hard coded) is not ideal and not what it should be when looking at the user manual. The recommended way of using the chip is to be low power (and output off) in idle mode and init DAC and/or ADC only when needed. this way it should avoid parasitic noises/cracks/pops on the speakers when not playing or recording anything.

On my side I don't have time now to learn how to code a 'clean' version of this driver (it could be interesting to have parameters to enable ALC or not, select which output to enable -speakers and/or headphones- and so on) in the esphome environment, especially the python file to handle options which looks completely weird to me. I should learn how to code it. If you know some tutorials or some reference drivers that are documented, let me know, I may give it a try...

**Comment by mateuszdrab** [comment]
Just wanted to add my 2 cents as I've also been experiencing the white noise issue on the ESP Muse, there are couple of issues created in different repos so I've tried to collate them all together. Essentially HASS TTS can be heard when played from the media browser but no MP3/voice assistant responses are audible.

https://github.com/esphome/issues/issues/4535
https://github.com/esphome/media-players/issues/29

I'm awaiting a delivery of the M5stack Atom Echo to test if it would also suffer the same issue, but I understand that this is specific to the DAC so it should not since it's only used in this speaker. I'm just confused how did the HA team have it work on their demos.

**Comment by cociweb** [comment]
many variations, many references, many links pointed to this PR on the WWW,  and additionally it results many unsuccesful stories...

Until this driver is still WIP, @jesserockz could you please update this PR with @mulcmu's  [branch](https://github.com/mulcmu/esphome-es8388-a1s/tree/nightdav-patch) which is based on @NightDav 's adjustment and  it also supports headphone output as well? it is well organized.

**Comment by RichardPar** [comment]
Is there any life in this ticket? .. 

I have a ESP32-LyraT dev board and notice that TTS microphone seems to be recording at the wrong speed. Using HA's Voice debug, the audio files say 16Khz, but audio contained is lower rate. (Audio plays too fast) 

Richard

**Comment by jesserockz** [comment]
Replaced by #6956

**Pull request closed without merging**
