### PR TITLE
Add X9C Potentiometer component

### LINKED ISSUE #1270: Digital potentiometers X9C103/X9C104 etc
**Describe the problem you have/What new integration you would like**

X9C103, X9C104 can be found for a dollar or so on aliexpress and can be really useful. 
They are digital potentiometers that can be tricky to use for beginners: https://inventr.io/%F0%9F%8E%9B-how-to-connect-the-digital-potentiometer-x9c102-x9c103-x9c104-to-arduino/
This would be great to have an integration in esphome. Something were all I have to do is set the level of the resistance. At the moment I have to use lambda with for loop to control these.

**Please describe your use case for this integration and alternatives you've tried:**

Atm I use these type of digital potentiometer to control the power of my kitchen hood. But being able to control a digital pot is useful for tons of other things :)

**Additional context**

### PR DESCRIPTION
**Pull request by EtienneMD**
# What does this implement/fix?

Adds a number component for the [X9C](https://4donline.ihs.com/images/VipMasterIC/IC/RNCC/RNCC-S-A0010771724/RNCC-S-A0010813887-1.pdf?hkey=6D3A4C79FDBF58556ACFDE234799DDF0) family of digital potentiometers.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2541

Related issue or feature (if applicable): fixes https://github.com/esphome/feature-requests/issues/1270

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
output:
  - platform: x9c
     id: x9c_pot
     cs_pin: GPIO25
     inc_pin: GPIO27
     ud_pin: GPIO26
     initial_value: 100
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by EtienneMD** [comment]
This is a first working commit and still a work in progress. I am not a developper and this is my first time working with microcontrollers. If this PR is not welcome I can close it, but so far everything seems to work as expected.

Any input is appreciated, documentation will follow.

**Comment by EtienneMD** [comment]
To the best of my knowledge this component is ready. It has been tested locally on both ESP8266 and ESP32. Let me know if adjustments are required.

Very simple communication interface, based on a three wire interface.

Datasheet : 
- https://www.renesas.com/us/en/document/dst/x9c102-x9c103-x9c104-x9c503-datasheet


Example Libraries: 
- [Arduino-X9C](https://github.com/philbowles/Arduino-X9C)
- [LapX9C10X](https://github.com/lucyamy/LapX9C10X)

**Comment by nagyrobi** [comment]
Wonderful!

Any chance you could add an option for logarithmic adjustment?

Logarithmic potentiometers are used as volume controls in audio equipment because the response of the human ear to the loudness of sound is also logarithmic.

So the goal would be to adjust the number on the UI linearly, but adjust the value on the potentiometer on the log scale.
https://learnabout-electronics.org/Resistors/resistors_09a.php

In the config a simple option say `logarithmic_adjustment: true`, which would default to false.

Use case would be adjustment of analog audio levels in conjunction with `media_player`.

**Comment by nagyrobi** [comment]
Is it possible to control multiple potentiometers? All need separate cs, inc and ud pins? Could some pins be common?

**Comment by EtienneMD** [comment]
All would need 3 separate pins. As long as you have available gpio, you can add more potentiometers.

**Comment by nagyrobi** [comment]
Would an I2C GPIO expander supported by ESPHome work with this?

**Comment by EtienneMD** [comment]
If esphome can control the pins, it can control de pot, so I would say yes. 

As far as logarithmic control, not sure how that would look like. These particular potentiometers are linear and only feature 100 positions. Software could convert to log, but so could a template number and lambda template.

**Comment by nagyrobi** [comment]
Yes, I meant by software. The component would do the required conversion math.

**Comment by EtienneMD** [comment]
Could be done, but would offer very limited value since you only have 100 taps. Once converted to log you would only get limited resolution.

https://www.analog.com/en/technical-articles/logging-the-linear-digital-potentiometer.html

**Comment by EtienneMD** [comment]
I have been thinking about this. For fun I created a function to convert log input to a corresponding potentiometer value. 
Here is what it looks like.

```
Log -> Linear
1   ->   1
2   ->   3
3   ->   5
4   ->   8
5   ->   11
6   ->   13
7   ->   15
8   ->   17
9   ->   19
10  ->   22
11  ->   23
12  ->   25
13  ->   27
14  ->   29
15  ->   30
16  ->   33
17  ->   35
18  ->   36
19  ->   38
20  ->   39
21  ->   41
22  ->   42
23  ->   44
24  ->   46
25  ->   47
26  ->   48
27  ->   50
28  ->   51
29  ->   52
30  ->   53
31  ->   55
32  ->   57
33  ->   58
34  ->   59
35  ->   60
36  ->   61
37  ->   62
38  ->   63
39  ->   64
40  ->   66
41  ->   67
42  ->   67
43  ->   68
44  ->   69
45  ->   70
46  ->   71
47  ->   72
48  ->   72
49  ->   73
50  ->   74
51  ->   75
52  ->   75
53  ->   77
54  ->   78
55  ->   78
56  ->   79
57  ->   80
58  ->   80
59  ->   81
60  ->   82
61  ->   82
62  ->   83
63  ->   83
64  ->   84
65  ->   84
66  ->   85
67  ->   85
68  ->   86
69  ->   86
70  ->   88
71  ->   88
72  ->   89
73  ->   89
74  ->   90
75  ->   90
76  ->   90
77  ->   91
78  ->   91
79  ->   92
80  ->   92
81  ->   92
82  ->   93
83  ->   93
84  ->   93
85  ->   94
86  ->   94
87  ->   94
88  ->   95
89  ->   95
90  ->   95
91  ->   96
92  ->   96
93  ->   96
94  ->   96
95  ->   97
96  ->   97
97  ->   97
98  ->   97
99  ->   99
100 ->   99
```

I tried to adjust the input to provide as much resolution as possible for 100 values. I think this might be backwards to what you had in mind, but that can be fixed. Resolution is not great, but if it can be useful to someone I can take a crack at it.

**Review by jesserockz — CHANGES_REQUESTED** [review]
I know you have already done the work here, but I feel this might be better as an `output` component. Considering an output has a 0-100% level, it would match nicely with this and could then be used by other components that require an output. It can also be used with a `template number` in front of it with no extra code needed by the component itself.

It shouldn't be a massive change to convert this to an `output`, but feel free to ask in the devs channel on discord if you have any questions.

**Comment by EtienneMD** [comment]
Okay I can get started on that after the holidays, doesn't look that much different. Will update the docs and ping you when done.

**Comment by EtienneMD** [comment]
Once again I believe this is ready to merge. Tested on ESP8266/ESP32 as an output.

**Review by jesserockz — APPROVED** [review]
LGTM! Thanks

**Comment by jesserockz** [comment]
@nagyrobi you could implement a log scale using a template output in front of this one.

**Pull request merged**
