### PR TITLE
P1 values for capacity tariff in Belgium

### PR DESCRIPTION
**Pull request by bwynants**
# What does this implement/fix?
implements capacity tariff in Belgium

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
active_energy_import_current_average_demand:
  name: "Current Average Demand"
active_energy_import_maximum_demand_running_month:
  name: "Maximum Month Demand"
active_energy_import_maximum_demand_last_13_months:
  name: "13 Month Maximum Quarterly Demand"
```

## Checklist:
  - [ x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bwynants** [comment]
closed https://github.com/esphome/esphome/pull/4412 by accident
requires https://github.com/glmnet/arduino-dsmr/pull/15

**Comment by max246** [comment]
> ested a revie

I feel like until the arduino is merged, we cant approve this PR otherwise one option wont be present.

**Comment by glmnet** [comment]
Hey there, the glmnet/Dsmr@0.8 package should be available, please update the dependency in this PR to point to the newer version.

**Comment by bwynants** [comment]
> Hey there, the glmnet/Dsmr@0.8 package should be available, please update the dependency in this PR to point to the newer version.

done and tested. it works!

**Review by glmnet — APPROVED** [review]

**Pull request merged**
