### PR TITLE
Add Grow Fingerprint Reader

### LINKED ISSUE #572: Fingerprint Sensor supports
I found SSL Fingerprints in ESPHOME.io page 
 https://esphome.io/components/mqtt.html#ssl-fingerprints

 Can I use this sensor for esphome ? 
 https://www.amazon.com/Optical-Fingerprint-Control-Mega2560-Geekstory/dp/B07BQ9VNWR/ref=sr_1_3?keywords=fingerprint+sensor&qid=1579352235&sr=8-3

**Describe the problem you have/What new integration you would like**

      I want to use this sensor for security if it supports 

**Please describe your use case for this integration and alternatives you've tried:**

     I tried in arduino code but I don't know how to make it in ESPHOME 

**Additional context**

     I always thanks for esphome developers Otto and all contributers thanks again.

### LINKED ISSUE #642: R307 Fingerprint sensor support on ESP Home
**Describe the problem you have/What new integration you would like**
Can I use this sensor R307 for esphome ?
https://www.electronicscomp.com/sensors-module/sensors/finger-print-sensor/finger-print-sensor-module-r307-india

**Please describe your use case for this integration and alternatives you've tried:**
I tried in arduino code but I don't know how to make it in ESPHOME.
the audrino code uses UART software serial  communication
following are the audrino code that i have tested & found Ok. I dont know how to use in esphome
Fingerprint Registry code : https://www.codepile.net/pile/RKDg2yeX
Fingerprint Check code : https://www.codepile.net/pile/G2El56Dy 
I want to use this sensor for security purposes for various home assistant integration to trigger various states/devices in a secure way.

**Additional context**

### PR DESCRIPTION
**Pull request by loongyh**
## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/642
fixes https://github.com/esphome/feature-requests/issues/572

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#835

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by loongyh** [comment]
Credits: Original author: @OnFreund
Co-author: @loongyh

**Comment by jesserockz** [comment]
2 things:
1. `rxxx` is a very ambiguous name, can we rename it to `fingerprint_rxxx` maybe?
2. Looking at the [adafruit library](https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library), its not very large when you strip out a lot of the "if hwserial etc...". Could we re-implement that code directly in the cpp file in esphome?

**Comment by loongyh** [comment]
@jesserockz thanks for reviewing!

1. Are we allowed to use the Adafruit name? If so a better name would be `Adafruit Fingerprint Reader` since it's based on that library.

2. Yep I have started [some work](https://github.com/loongyh/esphome-fingerprint/tree/refactor) to re-implement the Adafruit FP lib, however have put it on hold as I've been [advised](https://github.com/esphome/feature-requests/issues/642#issuecomment-707659207) to just use the library for now as it already has most of the features implemented, and still actively updated, to be able to keep up with any future changes/improvements. Regardless do let me know if re-implementation is required, I'll continue it this weekend.

**Comment by jesserockz** [comment]
I would say don't put `adafruit` in the name as we prefer the names of components to be tied to the hardware, not the software that drives them. In that case I think it would be preferable to wait until that version is ready before merging in and adding another library dependency.

@glmnet @OttoWinter @kbx81 @ssieb Thoughts on this?

**Comment by loongyh** [comment]
> I would say don't put `adafruit` in the name as we prefer the names of components to be tied to the hardware, not the software that drives them. In that case I think it would be preferable to wait until that version is ready before merging in and adding another library dependency.

Hmm the thing is, this particular protocol as defined in the Adafruit lib seems to be used by different manufacturers in China, i.e. the Rxxx series is manufactured by Hangzhou GROW Technologies while the ZFM-20, which seems to be similar to the R307, is manufactured by Hangzhou Zhian Technologies.

I believe there may be other models from other manufacturers that also use the protocol as defined in the Adafruit lib.

**Comment by glmnet** [comment]
What is as608?

**Comment by loongyh** [comment]
> What is as608?

seems like the chipset used by the optical readers

**Comment by OnFreund** [comment]
First of all, thanks @loongyh - most of the credit here should definitely go to you.

As for the name, all of the fingerprint components I've seen out there use this same protocol, but I really wouldn't know what to call it. Adafruit did create the library, but they did it by implementing the API advertised by Hangzhou Zhian Technologies for their optical sensors. Grow is also using that same API (and is also selling capacitive sensors with the same API), but has expanded it, which the Adafruit library picked up on when they started selling a rebranded version of Grow.

Since it's the only known API for fingerprint sensors, maybe we should just call it `Fingerprint`, but that less future proof.

**Comment by mgiako** [comment]
Hi all, please merge this PR, I can't wait to test my R307!

**Comment by kbx81** [comment]
+1 here for using more generic naming; `Fingerprint` is probably fine and/or something based on the device series name/model itself. Related: it's not really "Adafruit protocol", as I think @OnFreund is alluding to; it's a protocol dictated by the manufacturer of the device(s). I think whatever name we choose should reflect these things as best as reasonably possible. 😄

Also +1 for @jesserockz's comment that `rxxx` is...pretty generic and ambiguous. 😁 It would be good to choose something somewhat more specific.

My two cents. 🙂

**Comment by loongyh** [comment]
Thanks everyone for your feedback! So shall we rename the component to just fingerprint? So basically just drop the Rxxx and have it appear as:
```
# something.yaml
fingerprint:
  sensing_pin: ...
  ...
```
--esphome/components/rxxx
++esphome/components/fingerprint
```
// fingerprint.h

```

**Comment by OnFreund** [comment]
@kbx81 I agree that `rxxx` is hard to comprehend, but I wouldn't call it generic, since the alternative `fingerprint` is even more generic :)

ESPHome already has components with specific names that also support other models (e.g. `BMP085` also supports `BMP180`), so maybe that's the right approach? We can call it R503 (which seems to be one of the most popular models).

A generic `fingerprint` also makes sense, but I'm just afraid that at some point we'll find a fingerprint sensor with a different API.

**Comment by loongyh** [comment]
The Rxxx actually derives from Hangzhou Grow's line of readers:

H4e4e010135154590a2eb5b7bf6be18629
H37a4d36aa6a649649858af3f2d6ee409V

Perhaps if there needs to be a more specific but unambiguous name, how about `fingerprint_grow`? Future integrations for other manufacturers can just adopt `fingerprint_<manufacturer>`

**Comment by frequencx** [comment]
+1 for `fingerprint_<manufacturer>` --> `fingerprint_grow`. 

& thank you for working on this! I was just about to dive in when I came across your pull request...

**Comment by loongyh** [comment]
> 2. Looking at the [adafruit library](https://github.com/adafruit/Adafruit-Fingerprint-Sensor-Library), its not very large when you strip out a lot of the comments and serial code. Could we re-implement that code directly in the cpp file in esphome?

@jesserockz Have finished reimplementation of the adafruit lib, and removed that lib dependency. Tested working on my side. Do let me know if there's anything else to do or if it's ready to merge :)

**Comment by blademckain** [comment]
very nice works!
please merge in the next dev

**Comment by michelebossa** [comment]
Hi,
I'm trying to use this component but i have a problem to install this version with addon i have  added into config section the option esphome_version: loongyh:rxxx but i receive an error during the installation related to pip-build-ywsffyik/cryptography (maybe because i'm using a RPI4) There is something i can do to use this component?
Thanks a lot

**Comment by loongyh** [comment]
@michelebossa I've not used `esphome_version` before, but you can try the method described by the [Contributing guide](https://esphome.io/guides/contributing.html#setting-up-development-environment):

If you have an existing version of esphome installed already, then you can use python virtualenv to containerize it:
   ```
   python3 -m venv ~/esphome-dev
   cd ~/esphome-dev
   source bin/activate
   pip3 install wheel
   git clone --single-branch --branch rxxx https://github.com/loongyh/esphome.git
   cd esphome/script
   ./setup
   ```
Whenever you want to compile against this dev build, `source ~/esphome-dev/bin/activate` first and verify the virtualenv is active with the (esphome-dev) shell prompt prefix. You can also check with `esphome version` command, it should show `1.16.0-dev`.

**Comment by michelebossa** [comment]
@loongyh  it is worked thanks a lot i have just a question about the sensing_pin if i try to use i can't read any fingrprint withiut all it is ok i'm using the R502-A. just to understand how it is work the sensing pin? 
Thanks.

**Comment by loongyh** [comment]
you have to connect pin 5 (finger detection signal) of the R502-A to any available GPIO pin and define it under `sensing_pin`. Also connect pin 6 (finger detection power) to 3.3V.

**Comment by miga97** [comment]
hi  @loongyh, 
I installed your changes in esphome's dev addon for home assistant with configuration: esphome_version: loongyh:rxxx
so far no problem, everything is installed fine. (esphome version=1.16.0.dev0)

I wrote a test device by taking the code from your additions to the test3.yaml file,
the board I am compiling for is a nodemcuv2.
when I try to compile it gives me many warnings and then this error:

image

am I doing something wrong or is it a real problem?

**Comment by loongyh** [comment]
@miga97 can you attach your yaml config?

**Comment by miga97** [comment]
> @miga97 can you attach your yaml config?

https://pastebin.com/savauZhy

I took the lines from the test3.yaml file of this PR

**Comment by raidnet-ms** [comment]
Hi guys,
first of all thank you for working on this great feature.
I want ask you a question about where is supposed to store the fingerpring enrollment hash. I suppose you will store it inside the reader, so my next question would be: what happens if you have 2 separate doors with 2 separate readers?
Is there a way to relate the fingerprint hash with hassio user and update things Db with the central ACL?
thanks for your answer.

**Comment by OnFreund** [comment]
There is no hash - there is a `finger_id` that you choose when you enroll a fingerprint. The reader api does have the options to load and store fingerprints, so you could potentially share fingers between readers, but it might be easier to just enroll in each reader and make sure you're using the same `finger_id` for the same person.

**Comment by loongyh** [comment]
@miga97 let me take a look on my side, will update shortly.

@raidnet-ms it may be possible perhaps if/when home-assistant comes up with some kind of datastore api and esphome integrates it. Otherwise creating such a server and its underlying security concerns such as auth and encryption can be a separate project already.

**Comment by raidnet-ms** [comment]
> There is no hash - there is a `finger_id` that you choose when you enroll a fingerprint. The reader api does have the options to load and store fingerprints, so you could potentially share fingers between readers, but it might be easier to just enroll in each reader and make sure you're using the same `finger_id` for the same person.

Sure that would be great at home, i was just considering the opportunity to make this usable also in more complex business scenario.

**Comment by raidnet-ms** [comment]
> @miga97 let me take a look on my side, will update shortly.
> 
> @raidnet-ms it may be possible perhaps if/when home-assistant comes up with some kind of datastore api and esphome integrates it. Otherwise creating such a server and its underlying security concerns such as auth and encryption is probably not a trivial undertaking.

Oh thank you, now I understand.

**Comment by loongyh** [comment]
> Sure that would be great at home, i was just considering the opportunity to make this usable also in more complex business scenario.

In a business context perhaps a standalone project featuring this reader will be more apt, exposing some sort of API to be integrated with ERP/Payroll systems.
Regardless imo ESPHome/Home-Assistant are not intended for such commercial uses.

**Comment by raidnet-ms** [comment]
@loongyh Sure I wasn't supposing to adopt this into a bank, but simply in a small office to get rid of room door keys. No big values to secure.

@OnFreund are they stored as image?

**Comment by loongyh** [comment]
> @loongyh Sure I wasn't supposing to adopt this into a bank, but simply in a small office to get rid of room door keys. No big values to secure.

Haha I see, yep a small single unit office would be similar use case to a home. Then some sort of centralized credential management would make sense, unless the turnover rate of your employees is not high.

> @OnFreund are they stored as image? Sorry if i bother, I was searching the answer [here](https://learn.adafruit.com/adafruit-optical-fingerprint-sensor?view=all#enrolling-vs-searching) but with no success.

They are stored as templates. In the [datasheet](https://cdn-shop.adafruit.com/product-files/4651/4651_R503+fingerprint+module+user+manual.pdf) under "To upload character or template" (page 15).

**Comment by loongyh** [comment]
@miga97 I just tried compiling your .yaml, no errors for my side

**Comment by OnFreund** [comment]
It's not just securing the database, you'll also need to track resolution (different reader models have different resolutions), and orientation (from my experience orientation matters; not in a binary way, but average confidence levels change significantly).

**Comment by loongyh** [comment]
> ...and match orientation (from my experience orientation matters; not in a binary way, but average confidence levels change significantly).

I thought my reader was crapping out on me, that explains why sometimes it didn't match my enrolled finger.

**Comment by OnFreund** [comment]
Yeah, after I mounted it in its permanent location I erased the entire DB and enrolled all the fingers again to ensure correct orientation. I guess the rectangular sensors don't have this concern...

**Comment by miga97** [comment]
@loongyh, I use a container of esphome dev on docker, so I have not cloned any repository, it does it automatically every time I start the container, as you can see from this image:
image
I tried to remove and put the container back, with no result. I configured the version according to the addon guide:
image

since everything works well for you, I think it could be an issue with this type of installation, so I think I'll wait for them to do the merge in dev before doing other tests;
anyway thanks for your time

**Comment by raidnet-ms** [comment]
> Yeah, after I mounted it in its permanent location I erased the entire DB and enrolled all the fingers again to ensure correct orientation. I guess the rectangular sensors don't have this concern...

they should not have this problem because they are not optical but resistive.

**Comment by OnFreund** [comment]
Capacitive, not resistive, but it's unrelated. Capacitive vs optical relates to how the bitmap is obtained, not what type of processing is done on it.

**Comment by loongyh** [comment]
@miga97 Installed the ESPHome add-on in HASS, and added in the `esphome_version: 'loongyh:rxxx'` in the add-on config.
No errors on compile:
Capture

**Comment by loongyh** [comment]
@miga97 can you try using the latest stable version (1.15.3) of the add-on?

**Comment by miga97** [comment]
> @miga97 can you try using the latest stable version (1.15.3) of the add-on?
done, it kept giving me the error, until he disappeared by itself...

for reasons I don't understand now compile correctly, I have not changed anything, I just deleted the.yaml file and create a new one equal...

**Comment by raidnet-ms** [comment]
> Capacitive, not resistive, but it's unrelated. Capacitive vs optical relates to how the bitmap is obtained, not what type of processing is done on it.

[Here ](https://arxiv.org/ftp/arxiv/papers/1905/1905.03699.pdf) is described how the orientation is calculate in capacitive readers.
That's very complex (at least for me :-)) and interesting because it also describe the solution for matching fprints when enrolled and read by different type of sensors.

**Comment by OnFreund** [comment]
> Here is described how the orientation is calculated in readers.

Interesting, but not really relevant:
1. It's an academic paper that has a reference as late as March 2019. I doubt the algorithm mentioned in it has made its way into any existing hardware.
2. From a cursory reading, it seems to be about making existing fingerprint data work among across different sensor types.
3. The word "orientation" is used in a different context there (we're talking about the orientation of the sensor, not the ridges).

**Comment by loongyh** [comment]
I think we can at least cover the use case of sharing the templates across the same model fingerprint sensors across the premises, that only leaves the orientation problem, which afaik isn't an issue with the rectangular sensors.

**Comment by sblfc** [comment]
Thanks very much for making this, it's working great!

**Comment by blademckain** [comment]
plx merge

**Comment by stich86** [comment]
> I think we can at least cover the use case of sharing the templates across the same model fingerprint sensors across the premises, that only leaves the orientation problem, which afaik isn't an issue with the rectangular sensors.
> 
> I actually also intend to eventually come up with of some form of centralised management of templates, which comes pretty standard with commercial access controls. ESPHome does have a way to send data over to Home Assistant via events, may be worthwhile to investigate.

Hi @loongyh how can I use your repository?
I want to test my R503 with your version of ESPHome

Thanks in advance!

**Comment by loongyh** [comment]
> Hi @loongyh how can I use your repository?

ESPHome Home Assistant Add-on Method:
Add this line to the add-on config: `esphome_version: 'loongyh:rxxx'`.

Clone the Repo Method (Requires python and deps to be installed on your system):
Look [here](https://github.com/esphome/esphome/pull/1356#issuecomment-756567997).

Reference [here](https://pastebin.com/savauZhy) for the example .yaml.

**Comment by miga97** [comment]
Hi @loongyh, for some reasons I had to reinstall the esphome (1.16.0) addon, and now it doesn't allow me to use your branch anymore.

I also tried to go back to the 1.15.3 version of the addon

I get an error when starting the addon:
image

does it happen to you too? thanks in advance

**Comment by loongyh** [comment]
I have just upgraded to 1.16.0, and yes it does happen here too.

**Comment by miga97** [comment]
> I have just upgraded to 1.16.0, and yes it does happen here too.

this is very strange, last week it seemed to me to work on 1.16.0 as well. What may have happened?

**Comment by miga97** [comment]
@loongyh, i have an idea, in the master they have done the revert of esptools to 2.8, perhaps this is the problem #1702

**Comment by loongyh** [comment]
@miga97 I have synced the latest dev commits into this feature branch, and the issue is resolved on my end. Try starting the add-on again, it should work now.

**Comment by stich86** [comment]
> @miga97 I have synced the latest dev commits into this feature branch, and the issue is resolved on my end. Try starting the add-on again, it should work now.

hi Loongyh,

i've successfully download latest dev branch of your project, I still have a question:

Sense pin is connected to D5 (D1/D2 used as UART) on NodeMCUv2, but I got console flooed from this message:

```
[18:39:26][D][fingerprint_grow:091]: Scan and match
[18:39:26][D][fingerprint_grow:122]: Getting image 1
[18:39:26][D][fingerprint_grow:132]: No finger
```
Is it normal?
I'm not using 3.3PIN, is it necessary?

Thanks

**Comment by loongyh** [comment]
@stich86 Does it still happen after connecting 3.3VT to 3.3V?

You can define a template switch in your ESPHome config to trigger the enroll action, an input_number in Home Assistant to provide an input field to select your enrollment slot, expose that input_number as a sensor value via the homeassistant sensor platform, and then use a lambda to pass that value to the enroll action.
[Here](https://github.com/OnFreund/esphome-fingerprint/pull/1#issuecomment-717576471)'s an example.

**Comment by stich86** [comment]
> @stich86 Does it still happen after connecting 3.3VT to 3.3V?
> 
> You can define a template switch in your ESPHome config to trigger the enroll action, an input_number in Home Assistant to provide an input field to select your enrollment slot, expose that input_number as a sensor value via the homeassistant sensor platform, and then use a lambda to pass that value to the enroll action.
> [Here](https://github.com/OnFreund/esphome-fingerprint/pull/1#issuecomment-717576471)'s an example.

Hi loongyh,

now i've attached also 3.3VT, but still the same message spammed on the console :(

Thanks!

**Comment by stich86** [comment]
Looking at the code, it looks like that with or without sense_pin defined the log is always printed (DEBUG or VERBOSE)

```
  if (this->sensing_pin_ != nullptr) {
    ESP_LOGD(TAG, "Scan and match");
  } else {
    ESP_LOGV(TAG, "Scan and match");
  }

    case NO_FINGER:
      if (this->sensing_pin_ != nullptr) {
        ESP_LOGD(TAG, "No finger");
      } else {
        ESP_LOGV(TAG, "No finger");
      }
```

Is it intentional?

Thanks

**Comment by loongyh** [comment]
Yes, however it shouldn't spam the logs when log level is debug and below. With sensing_pin enabled, the update function should immediately return when there's no finger (sensing_pin == high). scan_and_match() shouldn't even execute. This means your sensing_pin is not high when there's no finger present.

Can you use a multimeter to physically check if the pin goes low when there's a finger on it, and that it goes high when there's no finger present?

**Comment by stich86** [comment]
> Yes, however it shouldn't spam the logs when log level is debug and below. With sensing_pin enabled, the update function should immediately return when there's no finger (sensing_pin == high). scan_and_match() shouldn't even execute. This means your sensing_pin is not high when there's no finger present.
> 
> Can you use a multimeter to physically check if the pin goes low when there's a finger on it, and that it goes high when there's no finger present?
> 
> On some boards there may be external pull-ups/downs connected to some GPIOs. Do make sure that's not the case for the GPIO pin you connected the sensing_pin to.

with a multimeter, the blue wire (touch detection) reports 3.3v when there is not finger, and 0v when there is a finger.
I've used: D5,D6,D7 as sensing_pin, but the same issue. When IRQ PIN is attached, with ground i still get 3.3v with or without finger.

I'm using this module: http://myosuploads3.banggood.com/products/20200617/20200617011758R502-Afingerprintmoduleusermanual.pdf

thanks

**Comment by loongyh** [comment]
> When IRQ PIN is attached, with ground i still get 3.3v with or without finger.

Don't understand what you mean, IRQ PIN refers to the blue wire (touch detection)? When you connect it to ground, it becomes...3.3v?

**Comment by stich86** [comment]
> > When IRQ PIN is attached, with ground i still get 3.3v with or without finger.
> 
> Don't understand what you mean, IRQ PIN refers to the blue wire (touch detection)? When you connect it to ground, it becomes...3.3v?

Let me explain better:

- touch sensor with blue (touch sense) not attached to NodeMCU, missing with multimeter on GND gives me: 3.3v without finger, 0v with finger just for few seconds
- Sensing_PIN still at 3.3v on the NodeMCU (should be at 0v?)

Hope it’s clear.
Thanks!

**Comment by loongyh** [comment]
hmm so when the blue wire is not connected to the MCU, it goes to 0v on finger present, however when the blue wire is connected, it stays at 3.3v regardless of finger presence?

**Comment by stich86** [comment]
> hmm so when the blue wire is not connected to the MCU, it goes to 0v on finger present, however when the blue wire is connected, it stays at 3.3v regardless of finger presence? anyway if sensing_pin stays at 3.3v, then the update function will forever return and never go into the scan_and_match() function in the first place.

Yes exactly. But the scan in my case works, if a put a registered finger send confidence and finger id to HA.

**Comment by loongyh** [comment]
yep, in your case the MCU sees it as finger always present, hence it tries to scan it every update interval. to prevent log spam, you can just treat it as you got no sensing pin and just remove the `sensing_pin:` yaml option.

**Comment by stich86** [comment]
> yep, in your case the MCU sees it as finger always present, hence it tries to scan it every update interval. to prevent log spam, you can just treat it as you got no sensing pin and just remove the `sensing_pin:` yaml option.

just to understand: sensing_pin should stay low (0v) or high (3.3v) without anything attached?

thanks

**Comment by loongyh** [comment]
I didn't configure the input pin with any pull-up/down, just input so it should be floating if you didn't connect it.

**Comment by simonemarin** [comment]
Hallo got a r502-aw here, compiled properly and updated the esphome firmware to a NodeMCU esp8266, I double checked the connections but the led does not light up, and nothing happens on esphome webserver panel, am I missing something here?

**Comment by simonemarin** [comment]
> 
> 
> Hallo got a r502-aw here, compiled properly and updated the esphome firmware to a NodeMCU esp8266, I double checked the connections but the led does not light up, and nothing happens on esphome webserver panel, am I missing something here?
> EDIT: I tried to reupload and just noticed this:
> [22:57:01][I][logger:166]: Log initialized
> [22:57:01][C][ota:366]: There have been 0 suspected unsuccessful boot attempts.
> [22:57:01][I][app:029]: Running through setup()...
> [22:57:01][C][uart_esp8266:046]: Setting up UART bus...
> [22:57:01][C][fingerprint_grow:052]: Setting up Grow Fingerprint Reader...
> [22:57:01][D][fingerprint_grow:189]: Checking password
> [22:57:02][E][fingerprint_grow:417]: No response received from reader
> [22:57:02][E][component:092]: Component was marked as failed.

ok fixed it I had the TX ad RX swapped, now it is working.

I have the same issue now as @stich86 where the sensing is always active and the log is spammed with scanning info.

- on the sensor sensing pin voltages are 3-3.3 with no finger and 0.5-2.8 with finger
- I tried to connect PIN5 both to GND and to 3.3v but the log does not stop

**Comment by loongyh** [comment]
Yes it seems the finger detection pin goes from high to low only momentarily when a finger is placed, after a second it goes back to high even when the finger is still on the reader.
Perhaps the pin is meant to be used for interrupts? Which afaik ESPHome doesn't support yet. Will have to rethink the logic for this.

**Comment by loongyh** [comment]
Hmm could be a bug somewhere in the update() function.

@stich86 did you spot any anomalies when you looked through `fingerprint_grow.cpp`?

**Comment by jesserockz** [comment]
> Perhaps the pin is meant to be used for interrupts? Which afaik ESPHome doesn't support yet. Will have to rethink the logic for this.

You are able to `attachInterrupt` if needed in ESPHome. Look in the codebase for how other components do it. And just make sure it is only doing very simple logic, usually setting a variable for `loop` or `update` to handle

**Comment by loongyh** [comment]
Ahh I stand corrected :) Is there documentation for this?

If I understand correctly, we define the ISR with `ICACHE_RAM_ATTR` tag, then in setup() attach it to the GPIO pin with
`this->pin->attach_interrupt(&isr, <what's this?>, <trigger mode>)`

What's the 2nd parameter for? Some components define `this`, another one defines some `&this->store_` which seems to be some kind of seperately-defined struct.

**Comment by jesserockz** [comment]
The second parameter is a struct object or class instance which becomes the first (and only) argument to the interrupt function. You can use `this` to then access an instance variable directly on the component

**Comment by loongyh** [comment]
Oh I see it now, the attach_interrupt() method is called from the `GPIOPin` class, hence in order for the ISR to access the members in the component class we need to pass it in via that arg.

**Comment by jesserockz** [comment]
Its a static method

**Comment by loongyh** [comment]
Hmm interesting, haven't bumped into static methods till now. That clears it up, thanks!

**Comment by simonemarin** [comment]
Hallo just reporting that apart from the aforementioned issue, the addon is woking great, this week I am going to install it on my custom door lock system for real life testing. I copied over the leds events and they are working as well.

**Comment by simonemarin** [comment]
I think I fried the 502 applying 3.3v to GND, so I ll be off until I get a replacement.

**Comment by loongyh** [comment]
> I think I fried the 502 applying 3.3v to GND, so I ll be off until I get a replacement.

Yeah I think I fried the sensor for one too, the image is a blurry mess when viewed with the cfgdemo program. The other four I have which are not used for testing seems fine. It seems these are not built to be quite robust (at least for during testing); best to have a few lying around.

**Comment by simonemarin** [comment]
I tried on an Arduino and it seems to work fine, reading, leds, serial, etc. but not on ESPhome, weird, any idea how that could be possible?

**Comment by loongyh** [comment]
Arduino, as in the 5V arduino hardware?

**Comment by simonemarin** [comment]
- yes Arduino 5V but powering the Nodemcu with 3.3v
- update: I got it working... and I am not even so shure how, I connected GND to the chassis of the usb instead of GND pin and it started to work, for what I know it may have been a bad connection on the dupont wires, I guess I will never know

**Comment by loongyh** [comment]
Well, in your case I would break out the multimeter! 😉

**Comment by simonemarin** [comment]
I finally managed to get everything up and working on my DIY door lock system, thanks to ESPhome I could move all the code to the ESP (compared to Tasmota) so the system can work independently from Home Assistant. I hope I can publish all the files, CAD and wiring soon.

**Comment by dortizesquivel** [comment]
Hey guys, what is still missing in this PR? I could help with it.

**Comment by dortizesquivel** [comment]
> I finally managed to get everything up and working on my DIY door lock system, thanks to ESPhome I could move all the code to the ESP (compared to Tasmota) so the system can work independently from Home Assistant. I hope I can publish all the files, CAD and wiring soon.

Looking forward! any links?

**Comment by simonemarin** [comment]
> 
> 
> > I finally managed to get everything up and working on my DIY door lock system, thanks to ESPhome I could move all the code to the ESP (compared to Tasmota) so the system can work independently from Home Assistant. I hope I can publish all the files, CAD and wiring soon.
> 
> Looking forward! any links?

Yes I have just patched up some documentation, if there is any need I can add some step by step, just let me know.
https://github.com/simonemarin/esphome_smartlock

**Comment by loongyh** [comment]
> Hey guys, what is still missing in this PR? I could help with it.

Change the sensing pin to use interrupts. Currently not working well as apparently the sensing pin only goes low momentarily and will not stay low even when the finger is still on the reader.

**Review by OttoWinter — APPROVED** [review]
Hi, thanks for this integration!

I've looked over the code and it looks good :) I don't have the hardware to test, so I can't test if the code actually works.

Merging would be ok from my side; Please let me know if the integration works in the current form (the discussion tab is long, so I didn't read all of it)

**Comment by loongyh** [comment]
>Please let me know if the integration works in the current form

Currently enabling the `sensing_pin` option may not work for some models with momentary triggers and cause the log to be spammed. Will try to come up with the fix by the next week.

**Comment by raidnet-ms** [comment]
> > Please let me know if the integration works in the current form
> 
> Currently enabling the `sensing_pin` option may not work for some models with momentary triggers and cause the log to be spammed. Will try to come up with the fix by the next week.

As Hassio will fix mqtt 5.1.1 bug I will test everything 🥳

**Comment by loongyh** [comment]
> I have the same issue now as @stich86 where the sensing is always active and the log is spammed with scanning info.

@simonemarin did you manage to resolve the sensing pin issue?

**Comment by simonemarin** [comment]
> @simonemarin I see you have created a door lock using this, did you manage to resolve the sensing pin issue?
Not really in my case I have just disregarded the pin and lowered the LOG level

**Comment by loongyh** [comment]
> > Not really in my case I have just disregarded the pin and lowered the LOG level

No need to lower the log level, if you're not using the sensing pin you can delete the `sensing_pin:` option from your yaml and the spam should stop. It is coded such that without the sensing pin, it'll output the scanning messages only on verbose and above.

**Comment by PaulAntonDeen** [comment]
The documentation mentions a security level for the sensor but as far as I can see there is no way to change this from ESPHome, is that correct?

**Comment by PaulAntonDeen** [comment]
Yes sure! I have created two fingerprint scanners and it works great, thank you! I'll gladly test things out.

**Pull request merged**
