### PR TITLE
Use latest version of upstream NeoPixelBus library

### PR DESCRIPTION
**Pull request by agners**
# What does this implement/fix? 

Quick description 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [x] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:

Tested with:

```yaml
# Example config.yaml
light:
  - platform: neopixelbus
    type: RGB
    variant: SK6812
    pin: GPIO23
    num_leds: 16
    method: ESP32_I2S_1
    name: "NeoPixel Light"
```

# Explain your changes

Describe your changes here to communicate to the maintainers **why we should accept this pull request**.
Very important to fill if no issue linked

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by agners** [comment]
This is a different approach to fix esphome/issues#1481 than #1519. Instead of using the NeoPixelBus fork just use upstream version. From what I can tell, the only downstream change is https://github.com/OttoWinter/NeoPixelBus/commit/d310a07e8c917a35834105f984e265a6abd298ef, which seems not to be required anymore (from what I can tell).

**Comment by OttoWinter** [comment]
Oh that would be nice if the patch is no longer required. If the clang-tidy job passes then things should be ok :+1:

**Comment by agners** [comment]
Unfortunately, this is still a problem upstream it seems.

Just sent a patch upstream: https://github.com/Makuna/NeoPixelBus/pull/471

Meanwhile, let's bump to your 2.6.2 release.

**Comment by agners** [comment]
Note there is a similar PR with #1756, but it misses the bump in `platformio.ini`.

**Comment by agners** [comment]
Btw, this should also fix esphome/issues#1600.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
