### PR TITLE
Tsl2591 gain publish

### LINKED ISSUE #4031: TSL2591 Ambient Light Sensor Auto Gain Mode Reporting
### The problem

The TSL2591 Ambient Light Sensor component (https://esphome.io/components/sensor/tsl2591.html) does not currently expose its actual gain value when in "auto" gain mode.

When in "auto" gain mode, it properly adjusts the gain value and reports relative values across full spectrum, infrared, visible, and an estimated/calculated lux.  However, it does _not_ provide any indication via sensor value publishing of the _actual gain_ used for those readings.  When transitioning between extremes (very dark, to very bright or vice-versa) the auto gain mode appears to function correctly; however, without a "gain" readout for what is being used to determine the raw values/lux, it can create a misleading situation where low and high light values spanning an auto adjustment may be perceived as inverted.

This can lead to incorrect conclusions for automation and users where a room may be perceived as darker than before even though it is now brighter (or vice versa).

I believe the correct route would be to publish the actual gain value being used when in "auto" mode, as well as other modes, probably as a numeric value (e.g. 1x, 25x, 400x, 9500x).  This seems like it might be a feature request, but I can also see the case for filing it as a bug since it provides values that are potentially misleading relative to one another.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.2

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

tsl2591

### Example YAML snippet

```yaml
sensor:
  - platform: tsl2591
    name: "${node_name} Light Sensor"
    id: "${node_id}_Light_Sensor"
    address: 0x29
    update_interval: 1s
    device_factor: 53
    gain: auto
    glass_attenuation_factor: 14.4
    integration_time: 500ms
    visible:
      name: "${node_name} TSL2591 Visible Light"
      id: "${node_id}_Visible_Light"
    infrared:
      name: "${node_name} TSL2591 Infrared Light"
      id: "${node_id}_Infrared_Light"
    full_spectrum:
      name: "${node_name} TSL2591 Full Spectrum Light"
      id: "${node_id}_Full_Spectrum_Light"
    calculated_lux:
      name: "${node_name} TSL2591 Lux"
      id: "${node_id}_i_lux"
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

The issue appears to be consistent across any version supporting the component.  It appears, based on https://github.com/esphome/feature-requests/issues/267 that this is a hold-over from the addition of "auto" mode.

### PR DESCRIPTION
**Pull request by z3liff**
# What does this implement/fix?

This exposes the actual gain used when the TSL2591 is in "auto" mode.  This allows the user/automations to see what the actual gain is for the published values, thus enabling differentiation between brightness level inversions that might occur when transitioning between brightness extremes.

For more detailed info, please refer to: https://github.com/esphome/issues/issues/4031

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4031

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 
https://github.com/esphome/esphome-docs/pull/2600

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: tsl2591
    name: "${node_name} Light Sensor"
    id: "${node_id}_Light_Sensor"
    address: 0x29
    update_interval: 1s
    device_factor: 53
    gain: auto
    glass_attenuation_factor: 14.4
    integration_time: 500ms
    visible:
      name: "${node_name} TSL2591 Visible Light"
      id: "${node_id}_Visible_Light"
    infrared:
      name: "${node_name} TSL2591 Infrared Light"
      id: "${node_id}_Infrared_Light"
    full_spectrum:
      name: "${node_name} TSL2591 Full Spectrum Light"
      id: "${node_id}_Full_Spectrum_Light"
    calculated_lux:
      name: "${node_name} TSL2591 Lux"
      id: "${node_id}_i_lux"
    actual_gain:
      name: "${node_name} TSL2591 Actual Gain"
      id: "${node_id}_actual_gain"

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by wjcarpenter** [comment]
LGTM, modulo the python lint that the pipeline noticed.

**Comment by wjcarpenter** [comment]
It would be nice to do a doc update to mention this new output.

**Comment by z3liff** [comment]
I literally just did that.  Sorry it took a sec.  Thanks!

**Comment by z3liff** [comment]
@wjcarpenter went ahead and fixed those issues.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
