### PR TITLE
Reject template select/number/switches that don't handle user input

### LINKED ISSUE #2328: Template Number state is always "unknown"
### The problem

I decided to try out the new template number as it seems a so much simpler concept to configure than how I used to do it. 

However, although in the ESPHome logs I can see the value being set successfully, Home Assistant always reports the value as `unknown`.

I've tried changing the value internally on the esp 8266, and by calling a service from within home assistant:

```
service: number.set_value
target:
  entity_id: number.kitchen_window_hold_until
data:
  value: 10
```

image

### Which version of ESPHome has the issue?

v2021.8.0

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.8.7

### What platform are you using?

ESP8266

### Board

d1 mini

### Component causing the issue

template number

### Example YAML snippet

```yaml
number:
  - platform: template
    name: "Kitchen Window Hold Until"
    id: kitchen_window_hold_until
    min_value: 0
    max_value: 86400
    step: 1
```

### Anything in the logs that might be useful for us?

```txt
[19:35:24][D][number:010]: 'Kitchen Window Hold Until' - Setting
[19:35:24][D][number:029]:   Value: 10.000000
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by oxan**
# What does this implement/fix? 

Reject the creation of template selects/numbers/switches with `optimistic` mode disabled that don't have `set_action`. These selects/numbers/switches are useless, since they cannot possibly do anything with user input; and a sensor should be used instead. This frequently confused users that used such a template in combination with an `on_value` that never triggered. See e.g. esphome/issues#1911, esphome/issues#2328, esphome/issues#2370, but there's plenty more reports on the Discord.

Also some cleanups:
* Set default value for `optimistic` in the schema, as is convention.
* Reject the usage of `optimistic`, `initial_option` and `restore_value` with `lambda` for select, like number already does. These options are ignored when a lambda is set anyway.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#2328

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
select:
  - platform: template
    name: "Template"
    options:
      - A
      - B
      - C
    update_interval: 5s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
Thanks. I was going to clean this up and probably do something similar before the release

**Comment by jesserockz** [comment]
I wonder if something is needed in the docs for these changes?

**Comment by oxan** [comment]
> I wonder if something is needed in the docs for these changes?

I submitted https://github.com/esphome/esphome-docs/pull/1441 with some minor clean-up and fixed examples, but yeah, maybe a big note about this in the docs would be useful too.

**Comment by jesserockz** [comment]
You should link the PRs in the description =)
I don't look at `next` PRs directly, only generally clicking through from a PR here

**Comment by oxan** [comment]
> You should link the PRs in the description =)
> I don't look at `next` PRs directly, only generally clicking through from a PR here

Well, it was a PR against current, and not directly related to this PR, as the changes it made were applicable before this PR as well =)

**Pull request merged**
