### PR TITLE
Add ‘only-generate’ parameter to generate command to only generate the C++ code

### LINKED ISSUE #69: Wishlist: 'generate' command
I am running ephomeyaml in docker and upload using native platformio:
```
docker run --rm -v "`pwd`":/config -it ottowinter/esphomeyaml livingroom.yaml compile
platformio run -d livingroom -t upload
```
The first step compiles everything while the second compiles it again. It would be nice to have a 'generate' command that only generates the cpp code in the first step.

### PR DESCRIPTION
**Pull request by apeeters**
Add 'generate' command that only generates the C++ code without compiling it.
Fixes #69.

### CODE REVIEW

**Comment by OttoWinter** [comment]
Hmmm, I'm not so happy with creating a whole new "verb" like generate or compile. The option list with `esphomeyaml --help` is already quite bloated and I don't want it to end up like the docker command. I would say an `--only-generate` flag for the `compile` flag would be better. What do you think?

**Comment by apeeters** [comment]
Whatever gets the job done :)

**Comment by apeeters** [comment]
I updated the PR with a only-generate parameter as discussed.

**Comment by OttoWinter** [comment]
Sorry for the delay. LGTM!

**Pull request merged**
