### PR TITLE
RTC implementation of pcf8563

### PR DESCRIPTION
**Pull request by KoenBreeman**
# What does this implement/fix?

Implementation of the feature request for PCF8563.
https://github.com/esphome/feature-requests/issues/2173

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>
https://github.com/esphome/feature-requests/issues/2173

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2868

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
external_components:
  - source: github://pr#4696
    components: pcf8563

time:
  - platform: pcf8563

on_...:
  - pcf8563.read_time

  # in case you need to specify the PCF8563 id
  - pcf8563.read_time:
      id: pcf8563_time

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). 
  https://github.com/KoenBreeman/ESPHome_doc_fork/tree/PCF8563

### CODE REVIEW

**Comment by jesserockz** [comment]
You need to tidy up this branch and remove the m5stack relay code from here

**Comment by KoenBreeman** [comment]
> You need to tidy up this branch and remove the m5stack relay code from here

Hi Jesse

I've removed the m5stack4relay files, but somehow it also has some files belonging to voice_assistant. I think I did something wrong, but I do not know what. First serious use of Github in a multi user development. I solely used it for myself. Any help is appreciated.

**Comment by jesserockz** [comment]
You need to **rebase** your branch from the latest ESPHome `dev` branch, and drop any commits that are not your code additions. Trying to undo changes by making new commits just makes it worse =)

**Comment by KoenBreeman** [comment]
> You need to **rebase** your branch from the latest ESPHome `dev` branch, and drop any commits that are not your code additions. Trying to undo changes by making new commits just makes it worse =)

Hi Jesse

I tried to do what you asked, but somehow I'm doing something wrong. 

I think I made a mistake by updating the branch. I choose merge instead of rebase. So that's why all the changes by others are reversed in my commits. Is this something that can be corrected or should I make new branches and create new pull requests. Because I did it with another pull request as well.

**Comment by jesserockz** [comment]
At this point it might be easier to make a new branch and cherry-pick your specific commits across, or just copy the new code across.

**Comment by KoenBreeman** [comment]
created a new pull request: https://github.com/esphome/esphome/pull/4998

**Pull request closed without merging**
