### PR TITLE
Support built-in endstop in Endstop cover

### PR DESCRIPTION
**Pull request by makstech**
# What does this implement/fix?

At the moment, Time Based Cover has an option `has_built_in_endstop`, while Endstop Cover doesn't. It should have this option because most gates already have their own stopping mechanisms. In my case, ESP32 is connected in parallel with the existing "dumb" system, since it already does everything, like controlling the motor, encrypted remote control, and also has magnetic end stops.  

With these changes, I've copied the built-in endstop logic from Time Based Cover along with the general logic of the `loop`, since it is much cleaner and makes more sense.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2182

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

### Note on testing

I don't know Python very well but at this point I tried everything I know and it still fails after building with `ImportError: cannot import name 'DNSAddress' from partially initialized module 'zeroconf'` when I try to run freshly installed ESPHome as it is described [here](https://esphome.io/guides/contributing.html#esphome-via-gitpod). 
<details>
<summary>Stacktrace</summary>
<br>

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/redacted/esphome/esphome/__main__.py", line 940, in <module>
    sys.exit(main())
  File "/Users/redacted/esphome/esphome/__main__.py", line 931, in main
    return run_esphome(sys.argv)
  File "/Users/redacted/esphome/esphome/__main__.py", line 918, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/Users/redacted/esphome/esphome/__main__.py", line 373, in command_run
    exit_code = compile_program(args, config)
  File "/Users/redacted/esphome/esphome/__main__.py", line 190, in compile_program
    rc = platformio_api.run_compile(config, CORE.verbose)
  File "/opt/homebrew/lib/python3.9/site-packages/esphome-2022.7.0.dev0-py3.9.egg/esphome/platformio_api.py", line 106, in run_compile
    return run_platformio_cli_run(config, verbose)
  File "/opt/homebrew/lib/python3.9/site-packages/esphome-2022.7.0.dev0-py3.9.egg/esphome/platformio_api.py", line 102, in run_platformio_cli_run
    return run_platformio_cli(*command, **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/esphome-2022.7.0.dev0-py3.9.egg/esphome/platformio_api.py", line 91, in run_platformio_cli
    import platformio.__main__
  File "/opt/homebrew/lib/python3.9/site-packages/platformio/__main__.py", line 21, in <module>
    from platformio import __version__, exception, maintenance
  File "/opt/homebrew/lib/python3.9/site-packages/platformio/maintenance.py", line 22, in <module>
    from platformio import __version__, app, exception, fs, telemetry
  File "/opt/homebrew/lib/python3.9/site-packages/platformio/telemetry.py", line 30, in <module>
    from platformio import __version__, app, exception, util
  File "/opt/homebrew/lib/python3.9/site-packages/platformio/util.py", line 30, in <module>
    from platformio.device.list import list_serial_ports as get_serial_ports
  File "/opt/homebrew/lib/python3.9/site-packages/platformio/device/list.py", line 21, in <module>
    import zeroconf
  File "/Users/redacted/esphome/esphome/zeroconf.py", line 8, in <module>
    from zeroconf import (
ImportError: cannot import name 'DNSAddress' from partially initialized module 'zeroconf' (most likely due to a circular import) (/Users/redacted/esphome/esphome/zeroconf.py)

% python3 esphome version                                                   
Version: 2022.7.0-dev
```
</details>

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

cover:
  - platform: endstop
    device_class: gate
    id: gate
    name: "Outside Gate"
    open_action:
      then:
        - button.press: gate_button
    open_duration: 30s
    open_endstop: gate_open
    close_action:
      then:
        - button.press: gate_button
    close_duration: 30s
    close_endstop: gate_closed
    stop_action:
      then:
        - button.press: gate_button
    max_duration: 30s
    has_built_in_endstop: true 
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
So, you are attaching an ESP to a gate that already does all the work and you just want to report position and trigger that gate? 
It sounds like you only need a template cover, as endstop (and time-based) covers are for completely encapsulating the cover/gate logic within ESPHome.

Also, looks like the gitpod instructions are incorrect. I might actually remove them as a codespace on GitHub is probably easier.

**Comment by makstech** [comment]
@jesserockz Basically yes. I have considered using template cover but the issue with those is that they don't have the toggle logic for whatever reason. My gates work with the exact logic like endstop when toggled (i.e. open, stop, close, stop, ...), so it's perfect. But with the template cover, I would have to write pretty complicated lambdas with logic that would set the correct status depending on the previous state, and then double it, because one ESP controls 2 gates.

**Comment by ssieb** [comment]
What "toggle logic" are you referring to?  How is this different than using the timed cover with built-in endstops?

**Comment by makstech** [comment]
@ssieb  The toggle logic I'm referring to is the toggle support from Cover Trait. E.g. [Endstop toggle support](https://github.com/esphome/esphome/blob/9ff187c3f8b2e2653ca1c49e274cbcc735b224c2/esphome/components/endstop/endstop_cover.cpp#L15) and [Endstop toggle logic](https://github.com/esphome/esphome/blob/9ff187c3f8b2e2653ca1c49e274cbcc735b224c2/esphome/components/endstop/endstop_cover.cpp#L24-L37), while [Template cover](https://github.com/esphome/esphome/blob/9ff187c3f8b2e2653ca1c49e274cbcc735b224c2/esphome/components/template/cover/template_cover.cpp) doesn't have one, and if "toggle" is called, would fail with [this](https://github.com/esphome/esphome/blob/9ff187c3f8b2e2653ca1c49e274cbcc735b224c2/esphome/components/cover/cover.cpp#L123).

**Comment by ssieb** [comment]
I don't understand how that is useful for your case.  I kind of understand the point of this PR, but I think the better option would be to add toggle support to the template cover instead.

**Comment by makstech** [comment]
My garage doors have their own logic board and controller, which stops the garage on its own. When it reaches the end (and it stops on its own), the sensor is triggered, and then the ESPHome endstop cover triggers the switch and makes my garage door go in the opposite direction, [logic](https://github.com/esphome/esphome/blob/9ff187c3f8b2e2653ca1c49e274cbcc735b224c2/esphome/components/endstop/endstop_cover.cpp#L73).

The template cover would be fine, but I primarily use this to control with the Apple Home app, which has support for `closing`, `opening`, and `stopped` (a.k.a. `idle` using `max_duration`) statuses, which the Template cover doesn't have.   

It's been a while now since I last messed with this but there was also some other issue I had with Template and/or Time-based covers.

**Comment by TheJulianJES** [comment]
Shouldn't this also be possible with Feedback Cover?

**Comment by ssieb** [comment]
The template cover has support for the opening and closing status.

**Comment by makstech** [comment]
Actually, first time hearing about it, since this PR was opened a month before the Feedback cover has been merged into the `dev` branch. I will check it out but from a quick look at it, it seems exactly what I needed.

**Pull request closed without merging**
