### PR TITLE
Also allow dot secrets dot yaml

### PR DESCRIPTION
**Pull request by cvwillegen**
# What does this implement/fix? 

When using a ``secrets.yaml`` file, it always generates an ``invalid config`` message when using ``esphome <command> *yaml`` on the command line. This patch creates the possibility to use a ``.secrets.yaml`` file, so that it is hidden from the file system and isn't specified by the shell when using the ``*`` wildcard.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1588
**Pull request in [esphome-dashboard](https://github.com/esphome/dashboard) with documentation (if applicable):** esphome/dashboard#139

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
<<: !include .common.yaml

# Example .common.yaml
api:
  encryption:
    key: !secret noise_key

# Example .secrets.yaml
  # This takes the secrets.yaml that is in the HomeAssistant config folder
<<: !include ../secrets.yaml
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
This will also need some changes in [esphome/dashboard](https://github.com/esphome/dashboard) for the editor

**Review by oxan — COMMENTED** [review]
This changes the error message when no secrets file exists from file not found to secret not defined though, I don't think that's desirable.

**Comment by cvwillegen** [comment]
> This changes the error message when no secrets file exists from file not found to secret not defined though, I don't think that's desirable.

Good catch! This has been fixed in the PR.

**Comment by cvwillegen** [comment]
> This will also need some changes in [esphome/dashboard](https://github.com/esphome/dashboard) for the editor

Yes, very true, but I haven't found where that code is! I could use some help here...

**Comment by oxan** [comment]
> > This will also need some changes in [esphome/dashboard](https://github.com/esphome/dashboard) for the editor
> 
> Yes, very true, but I haven't found where that code is! I could use some help here...

I think @jesserockz meant this: https://github.com/esphome/dashboard/blob/main/src/legacy.js#L74

**Comment by frenck** [comment]
ESPHome also generates a .gitignore... Does that need to be updated?

**Comment by cvwillegen** [comment]
> ESPHome also generates a .gitignore... Does that need to be updated?

Yes. I've now added code for that as well.

**Comment by balloob** [comment]
Why would we add this and not just have esphome automatically ignore secrets.yaml ?

**Comment by balloob** [comment]
This is not a good solution, we're putting the solution on the user by having each user run into this issue and figure it out. This is not acceptable. We also can't default to `.secrets.yaml` because users can't find it because it's hidden.

The only correct solution is to have ESPHome detect it's a secret file and ignore it / raise an error.

**Comment by cvwillegen** [comment]
I will follow the comment in esphome/esphome#2649 from @balloob and skip (or warn) at files called `secrets.yaml` and `secrets.yml`

**Pull request closed without merging**
