### PR TITLE
Added missing PM_1_0 and PM_10_0  for PMS5003T

### PR DESCRIPTION
**Pull request by genestealer**
PMS5003T sensor supports PM_1_0 and PM_10_0 which was missing for some reason. Added.

# What does this implement/fix?

PMS5003T sensor supports PM_1_0 and PM_10_0 which was missing for some reason. Added.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2741

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
N/A

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).
https://github.com/esphome/esphome-docs/pull/2741

### CODE REVIEW

**Comment by genestealer** [comment]
Documentation Update: https://github.com/esphome/esphome-docs/pull/2741

**Comment by jesserockz** [comment]
Do you have documentation supporting this? I had a quic search online and only saw it has the PM2.5 and humidity still...

**Comment by Delta1977** [comment]
Particle Range of measurement
Particle Counting Efficiency
Index 0.3 ~ 1.0 ; 1.0 ~ 2.5 ; 2.5 ~ 10
unit Micrometer(μm)
        

https://m.eleparts.co.kr/data/_gextends/good-pdf/201903/good-pdf-4316621-1.pdf

**Comment by genestealer** [comment]
Sorry, can I check, would we need to change more of the code, I did not see pmsx003.cpp, in which I'm unsure if we would need to change "case PMSX003_TYPE_5003T" to pull out the same date which "case PMSX003_TYPE_X003:" does: I.E.
```
  uint16_t pm_1_0_std_concentration = this->get_16_bit_uint_(4);
  uint16_t pm_2_5_std_concentration = this->get_16_bit_uint_(6);
  uint16_t pm_10_0_std_concentration = this->get_16_bit_uint_(8);
  uint16_t pm_1_0_concentration = this->get_16_bit_uint_(10);
  uint16_t pm_2_5_concentration = this->get_16_bit_uint_(12);
  uint16_t pm_10_0_concentration = this->get_16_bit_uint_(14);
  uint16_t pm_particles_03um = this->get_16_bit_uint_(16);
  uint16_t pm_particles_05um = this->get_16_bit_uint_(18);
  uint16_t pm_particles_10um = this->get_16_bit_uint_(20);
  uint16_t pm_particles_25um = this->get_16_bit_uint_(22);
```

Note, the following would not be copied over from the PMSX003_TYPE_X003 for PMSX003_TYPE_5003T
```
  uint16_t pm_particles_50um = this->get_16_bit_uint_(24);
  uint16_t pm_particles_100um = this->get_16_bit_uint_(26);
```

As those values are used on the PMS5003T for temperature and humidity :
```
  float temperature = this->get_16_bit_uint_(24) / 10.0f;
  float humidity = this->get_16_bit_uint_(26) / 10.0f;
```

PMS5003: https://www.aqmd.gov/docs/default-source/aq-spec/resources-page/plantower-pms5003-manual_v2-3.pdf
PMS5003T: https://m.eleparts.co.kr/data/_gextends/good-pdf/201903/good-pdf-4316621-1.pdf
PMS5003ST: https://homotix_it.e-mind.it/upld/catalogo/doc/PMS5003ST.pdf

**Comment by genestealer** [comment]
E.G. Like this: https://github.com/esphome/esphome/compare/dev...genestealer:esphome:patch-2

**Pull request closed without merging**
