### PR TITLE
add full position and tilt support to the template cover

### PR DESCRIPTION
**Pull request by ssieb**
## Description:  Adds full support for tilt and position reporting and handling to the template cover.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#420

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by KristopherMackowiak** [comment]
It's already done and approved. To close.

Ser #877

**Comment by ssieb** [comment]
Oops! :-)

**Comment by ssieb** [comment]
I would still like these changes to be considered.

**Comment by KristopherMackowiak** [comment]
I think there is no point in adding has_till because this parameter is set together with position_action. in the case of has_position it is the same, but it must already stay because it was released. position lambda also does not make sense, because the general lambda parameter is used here, which we can control the state in.

**Comment by ssieb** [comment]
You're missing why has_position was added (by me) in the first place.  Even if you don't have any lambdas creating the state, you might want to publish the state from somewhere else using the publish command.  There has to be some way to set the supports_position trait.  has_tilt has the same use for supports_tilt.  I think position_lambda is useful as it corresponds to the tilt_lambda and triggers the position support.  If you used just "lambda", then you would also have to use has_position.

**Comment by KristopherMackowiak** [comment]
Let me explain to you:
- in the lambda parameter we return the state of the blind, i.e. 0 - closed, 1 - open and similarly 0.2 - 20% etc. Therefore, we do not need position_lambda (unlike tilt_lambda).
- has_position and has_tilt are set to true when we set the action for these actions (position_action, tilt_action). After all, if the roller blind supports these options, we still need to complete these actions (if for unknown reasons you do not need an action, then call the logger).

I think there is no point in adding code if we can do everything without it.

**Comment by glmnet** [comment]
@ssieb as @KristopherMackowiak said, all you request is already supported, I understand these changes will add a more natural configuration, but it also adds redundancy and confusion, is there anything that I'm missing? Is something not supported the way it is now? (after @KristopherMackowiak  latest commit)

**Comment by ssieb** [comment]
If you are publishing the position from another sensor, there is no position_action or position_lambda in the cover config, so has_position needs to be set.  That was the reason for adding it and the same applies for tilt.
If you just use lambda, the only states that will get sent are open and closed, no positions in between.  Again, you will need to add has_position to make that work.  By adding the position_lambda option, it's clear that you are providing a position and not just the open/closed state and it will set the has_position for you as well.

**Comment by KristopherMackowiak** [comment]
@ssieb 
If your cover supports position, then setting the 'position_action' parameter is probably obvious? If you do not want to trigger any action, add:
`position_action:
    - logger.log: "set position"`
so you will set the has_position variable to true without performing any action.

The situation looks analogous with tilt.

The only thing we can do is add to the documentation that the lambda parameter is not only used to return CLOSED and OPEN, but also positions (e.g. return 0.2 returns 20%)

**Comment by ssieb** [comment]
How is that "obvious"?
And the lambda *does not* return positions unless you set has_position.
Why is this such a difficult change to add?  it's a tiny change to make things simpler and more obvious.

**Comment by KristopherMackowiak** [comment]
ESPHome is a large project, difficult to maintain and developers focus on adding new features and patching errors. It is difficult to meet every vision of the community, which is why solutions are sought if something cannot be doing in the current version.

Send a sample yaml code and describe what you can't do in the current dev version?

**Comment by ssieb** [comment]
bump

**Pull request closed without merging**
