### PR TITLE
Add text sensors for project name and version

### PR DESCRIPTION
**Pull request by jzucker2**
# What does this implement/fix?

Another nice thing about this, is when combined with my recent prometheus prs, results in nice metrics about versions and projects.

```
esphome_text_sensor_failed{id="esphome_project_version_detailed",area="Dev",node="devtestprometheus",name="ESPHome Project Version Detailed"} 0
esphome_text_sensor_value{id="esphome_project_version_detailed",area="Dev",node="devtestprometheus",name="ESPHome Project Version Detailed",value="1.0.1 Oct 31 2024, 00:04:29"} 1.0
esphome_text_sensor_failed{id="esphome_project_version",area="Dev",node="devtestprometheus",name="ESPHome Project Version"} 0
esphome_text_sensor_value{id="esphome_project_version",area="Dev",node="devtestprometheus",name="ESPHome Project Version",value="1.0.1"} 1.0
esphome_text_sensor_failed{id="esphome_project_name",area="Dev",node="devtestprometheus",name="ESPHome Project Name"} 0
esphome_text_sensor_value{id="esphome_project_name",area="Dev",node="devtestprometheus",name="ESPHome Project Name",value="jordan.exampleproject"} 1.0
```

I can also see this being useful in combination with the managed ota updates component.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Code quality improvements to existing code or addition of tests
- [x] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#4404

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [x] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

esphome:
  name: exampleproject
  friendly_name: "ESPHome Example Project"
  project:
    name: "My Custom Project"
    version: "1.0.0"

text_sensor:
  - platform: project_version
    name: "ESPHome Project Version Detailed"

  - platform: project_version
    name: "ESPHome Project Version"
    hide_timestamp: true

  - platform: project_name
    name: "ESPHome Project Name"

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
I personally don't feel like these should be exposed as sensors.
If you want them for your devices, it is as easy as this:
```yaml
text_sensor:
  - platform: template
    name: ...
    lambda: return ESPHOME_PROJECT_NAME;
```

**Comment by jzucker2** [comment]
> I personally don't feel like these should be exposed as sensors. If you want them for your devices, it is as easy as this:
> 
> ```yaml
> text_sensor:
>   - platform: template
>     name: ...
>     lambda: return ESPHOME_PROJECT_NAME;
> ```

That makes sense. I can close this out. That's easy enough.

I made a similar branch (but separate) to make some sensors for bluetooth proxies:

Screenshot 2024-11-04 at 3 04 14 PM

Is that worth opening a PR for? Or should I just implement that as a template sensor too?

Thanks!

**Comment by jesserockz** [comment]
> Is that worth opening a PR for? Or should I just implement that as a template sensor too?

Just templating them is fine. If there are more people requesting this info directly in a sensor we can revisit making them. If you want, you could add the templates to the documentation.

**Comment by jzucker2** [comment]
I finally got around to making a pr to the docs repo for this work instead https://github.com/esphome/esphome-docs/pull/4445

**Pull request closed without merging**
