### PR TITLE
Implement ByteBuffer

### PR DESCRIPTION
**Pull request by clydebarrow**
# What does this implement/fix?

Based on [Java's ByteBuffer](https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html) class, this implements a class that allows wrapping an array of bytes and performing
put and get operations of various data types, with configurable endian-ness.

Follows on from discussion here: https://github.com/esphome/esphome/pull/6865#discussion_r1632394779

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esphome:
  name: bytebuffer
  on_boot:
    - lambda: |-
        auto buf = ByteBuffer::create(16);
        assert(buf.get_endianness() == Little);
        assert(buf.get_remaining() == 16);
        buf.set_limit(10);
        assert(buf.get_capacity() == 16);
        buf.put_uint8(1);
        assert(buf.get_remaining() == 9);
        buf.put_uint16(0x1234);
        assert(buf.get_remaining() == 7);
        buf.put_uint32(0x12345678UL);
        assert(buf.get_remaining() == 3);
        assert(buf.array()[1] == 0x34);
        assert(buf.array()[2] == 0x12);
        assert(buf.array()[3] == 0x78);
        assert(buf.array()[4] == 0x56);
        assert(buf.array()[5] == 0x34);
        assert(buf.array()[6] == 0x12);
        buf.flip();
        assert(buf.get_capacity() == 16);
        assert(buf.get_remaining() == 7);
        assert(buf.get_uint8() == 1);
        assert(buf.get_uint16() == 0x1234);
        assert(buf.get_uint32() == 0x12345678ul);
        assert(buf.get_remaining() == 0);
        buf.rewind();
        buf.big_endian();
        assert(buf.get_remaining() == 7);
        assert(buf.get_uint8() == 1);
        assert(buf.get_uint16() == 0x3412);
        buf.mark();
        assert(buf.get_uint32() == 0x78563412ul);
        assert(buf.get_remaining() == 0);
        buf.reset();
        assert(buf.get_remaining() == 4);
        assert(buf.get_uint32() == 0x78563412ul);
        auto buf1 = ByteBuffer::wrap(buf.array(), buf.get_limit());
        buf.clear();
        assert(buf.get_position() == 0);
        assert(buf.get_capacity() == 16);
        assert(buf.get_limit() == 16);
        assert(buf1.get_remaining() == 7);
        assert(buf1.get_capacity() == 7);
        buf1.set_position(3);
        assert(buf1.get_uint32() == 0x12345678ul);
        buf1.clear();
        assert(buf1.get_limit() == 7);
        assert(buf1.get_capacity() == 7);
        assert(buf1.get_position() == 0);
        float f = 1.2345;
        buf1.put_float(f);
        buf1.flip();
        assert(buf1.get_remaining() == 4);
        assert(buf1.get_float() == f);
        buf1.clear();
        buf1.put_uint16(-32760);
        buf1.put_uint24(-302760);
        buf1.flip();
        assert(buf1.get_int16() == -32760);
        assert(buf1.get_int24() == -302760);
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nielsnl68** [comment]
This is really a nice start. It would be nice when we could manipulate this buffer not only for bytes etc. but also with strings. Have a look at the NodeJs implementation: https://nodejs.org/api/buffer.html

BTW do you know if there is a Python equivalent as well?

**Comment by nielsnl68** [comment]
> BTW do you know if there is a Python equivalent as well?

This could be useful for example with the remote_transmitter components. That is now only able to do byte arrays to Std::vector conversions and it would be nice when it does allow to have the option to set more types (like strings) as well.

**Comment by dentra** [comment]
Why just not to use language built in struct to manipulate binary data? It is less error prone, more easy to read, understand and maintain.
```cpp
struct MyData {
  uint8_t u8;
  uint32_t u32;
  struct {
    bool b_one : 1;
    uint8_t u_two : 2;
    unit8_t reserved : 5;
  };
  uint8_t arr[3];
// other fields
} PACKED;
if (sizeof(MyData) != buf_size) {
  return;
}
auto *data = reinterpret_cast<MyData*>(buf);
data->u32 = 12345;
if (data->b_one) {
  // do something 
}
// etc…

MyData other{}; // init with all fields set to 0
// do some stuff
send(reinterpret_cast<uint8_t*>(&other), sizeof(other));
```

**Comment by clydebarrow** [comment]
> Why just not to use language built in struct to manipulate binary data?

For a whole bunch of reasons.

* Structures may have padding (there are non-standard compiler extensions that can mitigate that, but it's still not portable)
* Endianness of the data may differ from the host machine
* Many CPU architectures require data to be on word boundaries when accessing data larger than a byte - tough luck if your incoming data doesn't match that.

Using C structs to model external data formats seems appealing at first glance and might work first up but simply isn't portable.

**Comment by nielsnl68** [comment]
Why do you close this PR? i was looking for it to be merged.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
