### PR TITLE
Remove power and energy from sensors that are not true power

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix? 

Quick description and explanation of changes

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/home-assistant/core/issues/58354

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — APPROVED** [review]

**Comment by dvisser** [comment]
why are we removing apparent (VA) and reactive power (VAR, kVArh) ?

Ref my home assistant issue 

[https://github.com/home-assistant/core/issues/58354](https://github.com/home-assistant/core/issues/58354)

**Comment by jesserockz** [comment]
> why are we removing apparent (VA) and reactive power (VAR, kVArh) ?
> 
> Ref my home assistant issue
> 
> [home-assistant/core#58354](https://github.com/home-assistant/core/issues/58354)

The only thing we are removing is `device_class: power` from those sensors as it should not have been `power`. You can still see and use the sensors.

**Comment by dvisser** [comment]
ok, thanks for clarifying :-)

**Comment by dvisser** [comment]
I still don't understand the "logic" as apparent and reactive are still "power" ? Is this explained somewhere in further detail that I can read up on?

**Comment by jesserockz** [comment]
As Frenck commented in the HA issue, Home Assistant's `power` class is only for power sensors that use `W` or `kW` units. You could open a feature request for adding new device classes `power_apparent` and `power_reactive` which would be for these sensors. 

Please move any further comments to that feature request if you decide to make one and not on merged PRs, or feel free to ask in discord about it =)

**Pull request merged**
