### PR TITLE
Please ignore

### PR DESCRIPTION
**Pull request by X-Ryl669**
# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by ssieb** [comment]
A proper description would be better.  The Draft status already means that no one will try reviewing it.

**Comment by X-Ryl669** [comment]
Yes, you are right, but that's the intend. This exact same PR is submitted on maintainer's fork to improve his own PR (#3886). 

I'm abusing Github's CI here for PR submission to apply all checks and validate my work is correct (CI doesn't run on forks) and also to have a simple way for users to test the PR. Hopefully, it'll be merged and I'll close this PR. 

Sorry for inconvenience.

**Comment by ssieb** [comment]
Then you should put that in the description and the top comment.

**Comment by jesserockz** [comment]
If this is the case and it is never intended to be merged. Please open PRs under your own fork which then will not take CI resources away from the reset of the ESPHome org on GitHub, which has limits.

**Comment by X-Ryl669** [comment]
Can you describe the limits you are referring to? 

I'm curious about the process selected by ESPHome and any fee it incurs, I thought it was free for public repository. 
In all cases, I didn't want to incur any penalty on ESPHome, the final intend of this PR was to be merged, but not directly, first it should have been merged in Ruby's fork and then here (so the CI will still need to run here anyway). 

BTW, it's out of the context, but I've opened a PR on your esp32-s3-box-3-board fork for supporting the temperature and humidity sensor (in fact the 2nd I2C bus). I don't know if you've received the notification.

**Comment by ssieb** [comment]
It's free, but it's very limited.  There are only a few processes allowed at a time and those are shared across the project.  So the more things running, the longer everything takes.  I think you should be able to run the CI on your own fork.

**Pull request closed without merging**
