### PR TITLE
B/W support for GooDisplay GDEY029T94 (as used on Adafruit MagTag)

### PR DESCRIPTION
**Pull request by AaronJackson**
# What does this implement/fix?

The GooDisplay is a black/white/gray display used on the Adafruit MagTag. This PR adds partial support for the display, but I was unable to get grey working - I don't really understand LUTs etc, so I'm using the one built into the OTP memory. The GooDisplay is mostly waveshare compatible so it doesn't feel right to split it into a separate component entirely. 

The change set is not that great, so I understand if you'd rather not merge, or entirely replace it :D I'll pull it in as a custom component anyway, and it might help someone else with their MagTag.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [issues#3515 (https://github.com/esphome/issues/issues/3514)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2765

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
display:
  - platform: waveshare_epaper
    cs_pin: GPIO8
    dc_pin: GPIO7
    busy_pin: GPIO5
    reset_pin: GPIO6
    model: gdey029t94
    reset_duration: 200ms
    # full_update_every: 30
    update_interval: 20s
    lambda: |-
      ESP_LOGI("display", "Updating display");
      it.rectangle(20, 50, 30, 30);
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by kjell** [comment]
I've been trying fix the "all black pixels" screen on my magtag. This did it. Thanks!

**Comment by AaronJackson** [comment]
Hmm in hindsight this might break something for *actual* waveshare displays and that does concern me. I'll see if I can come up with a proper fix by adding a separate display type

**Comment by ssieb** [comment]
This will definitely break things for the currently supported display.  Which one do you have?

**Comment by AaronJackson** [comment]
@ssieb https://www.good-display.com/product/389.html This is the one used by the Adafruit MagTag. It's very similar to the 2.9in Waveshare displays but as you can tell by my PR, it uses the 0x13 command for the black/white data. I think another command for grey maybe. 

I will try implementing a new display for it but given that it is not a waveshare display I was thinking about calling it something like "gd-2.90in-bwg" for "Good Display 2.9in black/white/grey"

**Comment by ssieb** [comment]
Yes, if it has different commands (and doesn't have color), it should have a separate identifier.  Maybe `GDEY029T94`?

**Comment by Zagrophyte** [comment]
Anything left to clear this for merge? Looks like it was successfully changed to add it as a new device as requested.

If you need another tester I could try it out with my MagTag. I'm excited for this PR as it fixes the remaining blocker preventing full use of the MagTag directly within ESPHome.

**Comment by AaronJackson** [comment]
@Zagrophyte if you want to use esphome with your magtag you can just pull in the component as an external component from my fork

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/AaronJackson/esphome
      ref: waveshare_2p9inb
    refresh: 0s
    components: [ waveshare_epaper ]

display:
  - platform: waveshare_epaper
    cs_pin: GPIO8
    dc_pin: GPIO7
    busy_pin: GPIO5
    reset_pin: GPIO6
    model: gdey029t94
    reset_duration: 200ms
    #full_update_every: 30
    update_interval: 60s
    rotation: 270
    lambda: |-
      ....
```

It doesn't support grey though. I haven't spent enough time to figure out how LUTs work to add support for this :sweat_smile:, but it would still be cool to get it merged. It seems to work well though as it stands, had three of them running 24/7 with ESPHome since I last commented on this pr :slightly_smiling_face:

**Comment by firthh** [comment]
I've been running this for over a month now with no issues. I built it from the fork so I'm really glad that there's an easier way to get this working. It would be even nicer to have it merged.

The only issue I encountered was trying to display a [graph](https://esphome.io/components/display/index.html#graph-component) and being a bit of an esphome noob I wasn't sure if it was my configuration or something else...

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Please add (or link) a docs PR targeting `next` for this model addition.

**Comment by AaronJackson** [comment]
Thanks @jesserockz - PR for addition to docs https://github.com/esphome/esphome-docs/pull/2765

**Pull request merged**
