### PR TITLE
Add panasonic ac climate component

### LINKED ISSUE #1058: IR Transmitter climate support for Panasonic
**Describe the problem you have/What new integration you would like**
I would like to control my Panasonic AC Units with my IR Blaster

**Please describe your use case for this integration and alternatives you've tried:**
attempting raw codes but they only supply one state per trigger

**Additional context**

### LINKED ISSUE #1218: IR Remote Climate Panasonic
**Describe the problem you have/What new integration you would like**
Please add support receiver platform for Panasonic in IR Remote Climate

**Please describe your use case for this integration and alternatives you've tried:**
Not supported in current version

**Additional context**

### PR DESCRIPTION
**Pull request by WeekendWarrior1**
# What does this implement/fix? 

I have been using esphome to control my Panasonic AC (via IR) for over a year with a custom component, thought it was finally time to get an official component going. Tested and working on my AC.
Currently doesn't do any of the Panasonic presets "eg. eco, quiet, powerful", they seem to really mangle the IR packet.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**  

- fixes https://github.com/esphome/feature-requests/issues/1218
- fixes https://github.com/esphome/feature-requests/issues/1058

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1301

## Test Environment

- [x] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
remote_receiver:
  id: rcvr
  pin:
    number: GPIO18
    inverted: True
    mode: INPUT_PULLUP
  # high 55% tolerance is recommended for some remote control units
  tolerance: 55%

remote_transmitter:
  pin:
    number: GPIO21
    inverted: True
  carrier_duty_percent: 50%

climate:
  - platform: panasonic
    name: "Lounge AC"
    receiver_id: rcvr
    supports_horizontal_swing: true

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
Awesome!!
Finally something I actually have in my house I can test =)
I just quickly built a receiver and transmitter and tested this and it worked first time.

**Comment by WeekendWarrior1** [comment]
Excellent, I am glad to hear. I will fix the failed lint and add to the docs in the coming days.

**Comment by jesserockz** [comment]
The ON/OFF byte is different for my unit though, could be because it should only look at/set a single bit in `message[5]` Mine works with `0x0A`/`0x0B` instead of `0x08`/`0x09`.
I also have added horizontal/vertical/both swing support locally so far as mine supports that.

**Comment by WeekendWarrior1** [comment]
What model is your AC, and what does your remote look like?
The ones in my home are the CS-MRE7QKR, and my remote is:
image

>  I also have added horizontal/vertical/both swing support locally so far as mine supports that.

Can you please elaborate on what you mean by this?
Did setting
```yaml
    supports_horizontal_swing: true
```
In the climate config not make those swing modes visible in HA? (I believe it should)

**Comment by jesserockz** [comment]
No, setting that did not work. But also I modified it to not use a define and allow setting of each mode from yaml. I can push this commit if you are interested?



Indoor unit: CS-E18NKR

**Comment by WeekendWarrior1** [comment]
Please do!

**Comment by jesserockz** [comment]
Can we rename this platform to be `panasonic_ir` as there is an external component that uses the serial port that should eventually make its way into ESPHome. https://github.com/DomiStyle/esphome-panasonic-ac/tree/dev-cztacg1

**Pull request closed without merging**
