### PR TITLE
Humidifier component

### PR DESCRIPTION
**Pull request by Jaco1990**
# What does this implement/fix?

Add a humidifier component to ESPHome as well as Generic Humidifier (User Modifiable) component similar to Bang Bang in climate.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** N/A

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3808

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
humidifier:
  - platform: generic_humidifier
    default_target_humidity: 65
    sensor: humidity_sensor
    name: test humidifier
    normal_action:
      - switch.turn_on: switch_1
    eco_action:  
      - switch.turn_off: switch_1
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by Jaco1990** [comment]
[https://github.com/esphome/esphome-docs/pull/3808](url)

**Comment by paravoid** [comment]
I'm very interested :) Thanks so much!

Not sure if you're aware, but there was an earlier attempt that was almost there but kind of died down:
- esphome: https://github.com/esphome/esphome/pull/3523
- esphome-docs: https://github.com/esphome/esphome-docs/pull/2110
- aioesphomeapi: https://github.com/esphome/aioesphomeapi/pull/221
- homeassistant/core: https://github.com/home-assistant/core/pull/72946

Hopefully this one gets merged!

**Comment by paravoid** [comment]
Another thing: I'm personally interested in a *de*humidifier. Home Assistant calls the component a "humidifier", but I believe it supports both. Moreover, the "generic" component is a called a "generic hydrostat", rather than a "generic humidifier". Perhaps this should follow suit?

That said, given what happened with the earlier attempt at this, I'd personally rather see this merged as-is and later iterated on, rather than attempting to make it support all use cases.

**Comment by Jaco1990** [comment]
I hope it gets merged as well. once there is a proper UI to test from ill be happy to put in more work. 

I have seen the Generic Hygrostat. and I would love to get the component working for dehumidifiers as well. At the moment I do not own a Dehumidifier to test the component with and where I stay we are moving into our dry season, I might be able to get a dehumidifier later this year.

**Comment by paravoid** [comment]
> I have seen the Generic Hygrostat. and I would love to get the component working for dehumidifiers as well. At the moment I do not own a Dehumidifier to test the component with and where I stay we are moving into our dry season, I might be able to get a dehumidifier later this year.

I have one, and I can play around with hooking it up! It's a Tuya one, so I can use the generic hydrostat to begin with, but in the longer I'll try to hook up the Tuya component directly (similar to Tuya Climate etc.). But let's not get ahead of ourselves :)

BTW I noticed this PR was just closed? Was this accidental?

**Comment by Jaco1990** [comment]
> > I have seen the Generic Hygrostat. and I would love to get the component working for dehumidifiers as well. At the moment I do not own a Dehumidifier to test the component with and where I stay we are moving into our dry season, I might be able to get a dehumidifier later this year.
> 
> I have one, and I can play around with hooking it up! It's a Tuya one, so I can use the generic hydrostat to begin with, but in the longer I'll try to hook up the Tuya component directly (similar to Tuya Climate etc.). But let's not get ahead of ourselves :)
> 
> BTW I noticed this PR was just closed? Was this accidental?


I closed it because my commit went haywire. I will submit another pull request. I just need to work out the issues.

**Pull request closed without merging**
