### PR TITLE
Add action for vol+/-

### PR DESCRIPTION
**Pull request by foxsam21**
## Description:

Added action to be able to do relative vol+.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1212

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

--
I am not a programmer so I am sure something can be missing.

### CODE REVIEW

**Comment by glmnet** [comment]
GTM when docs added 👍

**Comment by jesserockz** [comment]
@foxsam21 I have created a docs PR for this, can you rebase/merge dev so I can then merge this in?

**Review by jesserockz — APPROVED** [review]
Approving now, just needs a rebase because of the conflicts

**Comment by jesserockz** [comment]
Closing in favour of #1856

**Pull request closed without merging**
