### PR TITLE
[core] fix running script\build_codeowners.py on windows.

### PR DESCRIPTION
**Pull request by nielsnl68**
# What does this implement/fix?

windows setup needs to iinstall python-magic-bin. I was not able to run the script\build_codeowners.py before this was installed on my system.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by clydebarrow** [comment]
As far as I can see the only use for libmagic is to identify an SVG file, but to do that it's bringing in a rather heavyweight package that depends on an external native library. And that library apparently just identifies an SVG file by searching for the string "<svg" so maybe that's all that needs doing, and then the requirement for libmagic can be removed.

**Comment by clydebarrow** [comment]
Something like this:
```
diff --git a/esphome/components/image/__init__.py b/esphome/components/image/__init__.py
index e5a205f1e..2e38f2b96 100644
--- a/esphome/components/image/__init__.py
+++ b/esphome/components/image/__init__.py
@@ -6,7 +6,8 @@ import hashlib
 import io
 from pathlib import Path
 import re
-from magic import Magic
+
+from PIL import UnidentifiedImageError

 from esphome import core
 from esphome.components import font
@@ -280,17 +281,18 @@ async def to_code(config):
     except Exception as e:
         raise core.EsphomeError(f"Could not load image file {path}: {e}")

-    mime = Magic(mime=True)
-    file_type = mime.from_buffer(file_contents)
-
     resize = config.get(CONF_RESIZE)
-    if "svg" in file_type:
-        image = load_svg_image(file_contents, resize)
-    else:
+    try:
         image = Image.open(io.BytesIO(file_contents))
         if resize:
             image.thumbnail(resize)
-
+    except UnidentifiedImageError:
+        if "<svg" in str(file_contents):
+            image = load_svg_image(file_contents, resize)
+        else:
+            raise core.EsphomeError(
+                f"Could not load image file {path}"
+            )
     width, height = image.size

     if CONF_RESIZE not in config and (width > 500 or height > 500):
```

**Review by jesserockz — DISMISSED** [review]

**Comment by nielsnl68** [comment]
> As far as I can see the only use for libmagic is to identify an SVG file, but to do that it's bringing in a rather heavyweight package that depends on an external native library. And that library apparently just identifies an SVG file by searching for the string "<svg" so maybe that's all that needs doing, and then the requirement for libmagic can be removed.

I see, Not sure why the **`build_codeowners.py`** needs to check if a file has a "<svg"?

**Comment by nielsnl68** [comment]
@clydebarrow, About the given solution, i disagree on that. I Believe it would work for sure.
But i belief it is as nesty fix as what i suggest to do in this PR.

As i asked above why should the **`build_codeowners.py`** needs to check if a file has a "<svg"?
In my belief **`build_codeowners.py`** should validate of the **`CODEOWNERS`** is in the `__init__.py` etc. and the other stuff inside those files should be untouched.

**Comment by clydebarrow** [comment]
the problem is that the script loads all the components in the ESPHome tree to be able to check if there is a CODEOWNERS property in each one, and it's the image component that references libmagic, so when it gets loaded it complains if the library is absent. I'll raise a separate PR to remove that dependency, which is a pain point irrespective of its effect on the codeowners script.

**Comment by clydebarrow** [comment]
https://github.com/esphome/esphome/pull/7365

**Pull request closed without merging**
