### PR TITLE
Fingerprint_grow: Trigger on finger scan start

### PR DESCRIPTION
**Pull request by alexborro**
# What does this implement/fix?

Implements the trigger `on_finger_scan_start`. It is triggered when the `sense_pin` detects a finger touching the sensor during the "waiting for a finger" state of the system.

This PR was made on top of my previous one (https://github.com/esphome/esphome/pull/5365), so this github diff will include both PRs. You can see only this PRs diff using this link: https://github.com/alexborro/esphome/compare/75a4596...f87d6a5

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** Implements https://github.com/esphome/feature-requests/issues/1792

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
  on_finger_scan_start:
    - fingerprint_grow.aura_led_control:
        state: ALWAYS_ON
        color: GREEN
        speed: 0
        count: 0
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by ShadyMCShadesen** [comment]
Wouldn't it be nice to have a `on_finger_scan_stop` trigger too?

I'm currently using a gpio binary_sensor that reads the sense_pin state. There is the `on_release` trigger that helps me.

With both functions implemented in the grow sensor, the binary_sensor wouldn't be needed any more.

**Comment by alexborro** [comment]
> Wouldn't it be nice to have a `on_finger_scan_stop` trigger too? I'm currently using a gpio binary_sensor that reads the sense_pin state. There is the `on_release` trigger that helps me. With both functions implemented in the grow sensor, the binary_sensor wouldn't be needed any more.

I'm not sure what you mean, but we already have a trigger when finishing a "full" scan process: `on_finger_scan_matched` and `on_finger_scan_unmatched`. 
This space is meant for this PR, please open an issue in the Feature Request session (https://github.com/esphome/feature-requests/labels/integration%3A%20fingerprint_grow) and I will be happy to discuss there.

**Comment by ShadyMCShadesen** [comment]
> > I'm not sure what you mean, but we already have a trigger when finishing a "full" scan process: `on_finger_scan_matched` and `on_finger_scan_unmatched`. 

My sensor has different colors for different situations, on idle it is blue without effect, Now when someone puts their finger on the sensor, my gpio binary sensor recognizes it and lets the LED "breathe" in blue. If he removes the finger, the led turns back to blue without effect.

**Comment by ShadyMCShadesen** [comment]
> > I'm not sure what you mean, but we already have a trigger when finishing a "full" scan process: `on_finger_scan_matched` and `on_finger_scan_unmatched`. 

My sensor has different colors for different situations, on idle it is blue without effect, Now when someone puts their finger on the sensor, my gpio binary sensor recognizes it and lets the LED "breathe" in blue.
If the scan is matched it blinks green, on unmatched it blinks red, etc.
But if the finger is removed before the real scan starts (the real finger scan starts slightly delayed after the sense_pin has detected the finger), the led turns back to blue without effect.

`on_finger_scan_start` would notice straight away if someone puts the finger on the sensor, but not if someone removes the finger before the scan occurred, so before the matched/unmatched triggers are triggered.
The `on_finger_scan_stop` would trigger in this case.

Probably is `on_finger_scan_abort` a better name for this trigger

**Comment by grigi** [comment]
> > > I'm not sure what you mean, but we already have a trigger when finishing a "full" scan process: `on_finger_scan_matched` and `on_finger_scan_unmatched`.
> 
> My sensor has different colors for different situations, on idle it is blue without effect, Now when someone puts their finger on the sensor, my gpio binary sensor recognizes it and lets the LED "breathe" in blue. If the scan is matched it blinks green, on unmatched it blinks red, etc. But if the finger is removed before the real scan starts (the real finger scan starts slightly delayed after the sense_pin has detected the finger), the led turns back to blue without effect.
> 
> `on_finger_scan_start` would notice straight away if someone puts the finger on the sensor, but not if someone removes the finger before the scan occurred, so before the matched/unmatched triggers are triggered. The `on_finger_scan_stop` would trigger in this case.
> 
> Probably is `on_finger_scan_abort` a better name for this trigger

Would the `on_finger_scan_misplaced` not achieve what you are asking for?

**Comment by alexborro** [comment]
> Would the `on_finger_scan_misplaced` not achieve what you are asking for?

Yes, it would. I will be happy to reply to these questions if we discuss this topic in the **Feature Request** session as I posted above. This discussion is not related to this PR.

**Comment by ShadyMCShadesen** [comment]
> > Would the `on_finger_scan_misplaced` not achieve what you are asking for?
> 
> Yes, it would. I will be happy to reply to these questions if we discuss this topic in the **Feature Request** session as I posted above. This discussion is not related to this PR.
> 

Sorry, I didn't see that you had already suggested this trigger 😅

**Comment by ShadyMCShadesen** [comment]
> > Would the `on_finger_scan_misplaced` not achieve what you are asking for?
> 
> Yes, it would. I will be happy to reply to these questions if we discuss this topic in the **Feature Request** session as I posted above. This discussion is not related to this PR.
> 

Sorry, I didn't see that you had already suggested this trigger 😅

**Comment by grigi** [comment]
I have manually built this, and it is working nicely :+1: 
Definitely an improvement getting instant feedback that the sensor is starting a finger read.
This together with #5365 makes using the grow fingerprint reader a significantly more polished experience.

**Comment by grigi** [comment]
This does raise a different issue, sometimes the scan start is instant, and sometimes it's slow. It seems to be related to the sense pin. Would a pull-up/down help stabilise that some?

**Comment by alexborro** [comment]
> This does raise a different issue, sometimes the scan start is instant, and sometimes it's slow. It seems to be related to the sense pin. Would a pull-up/down help stabilise that some?

No, it is not related to the sense pin, but with the component being updated once each 500ms. So if you happen to place your finger just after the last update has taken place, then you will need to wait an extra half second to have your finger scanned.
I'm implementing the code as a state machine and  the transfer to the sensor asynchronously, which will allow us to shorten the updates and make it more responsive.

**Comment by grigi** [comment]
Makes sense, as it was really only happening when I was testing the different failure modes. It would work every time if I removed the finger, waited a second, and tried again.

**Review by jesserockz — CHANGES_REQUESTED** [review]
If this PR is still relevant, please resolve the conflicts so it can be reviewed

Jesse

**Pull request closed without merging**
