### PR TITLE
Add GIF Animation Support

### PR DESCRIPTION
**Pull request by Syndlex**
## Description:

**Related issue (if applicable):** implements https://github.com/esphome/feature-requests/issues/893

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#856

## Checklist:
  - [x] The code change is tested and works locally.

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
GTM when CODE_OWNERS added

**Comment by Syndlex** [comment]
Sry the acronym GTM does not tell me anything.

Is there Something to do for me here?

**Comment by glmnet** [comment]
Sorry yes, I expect you to add yourself to the CODE_OWNERS in the component, see https://esphome.io/guides/contributing.html#extras see https://github.com/esphome/esphome/pull/1200 for example

**Comment by Syndlex** [comment]
@glmnet Done

**Comment by glmnet** [comment]
Thanks!

**Pull request merged**
