### PR TITLE
add VL53L1X Time-Of-Flight sensor

### PR DESCRIPTION
**Pull request by topic2k**
# What does this implement/fix?

Add new component VL53L1X time of flight sensor.

I have not much expierence with writing C++ code and mostly it was trial and error, so please be patient if something needs to be changed.

This is mixture of copying things from [vl53l0x component](https://github.com/esphome/esphome/tree/dev/esphome/components/vl53l0x) and mix it with [Adafruit VL53L1X library](https://github.com/adafruit/Adafruit_VL53L1X).
At least the basic distance measuring is working. More advanced features like direction detecting are not implemented.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>
esphome/feature-requests#1697
esphome/feature-requests#836

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2097

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: vl53l1x
    name: "VL53L1X TOF sensor"
    address: 0x35
    update_interval: 5s
    enable_pin: 16
    io_2v8: true
    timing_budget: 500
    long_range: true
    offset: -50
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by topic2k** [comment]
script/ci-custom -> Lint Custom:
>  Error: POST:1:1: lint: Constant CONF_IRQ_PIN is defined in 4 files. Please move all definitions of the constant to const.py (Uses: esphome/components/ade7953/sensor.py, esphome/components/as3935/__init__.py, esphome/components/vl53l1x/sensor.py, esphome/components/xpt2046/__init__.py)

Not sure if i should ignore the above or apply those changes to this PR?

**Comment by jimtng** [comment]
@topic2k are you still working on this? I'd love to see the support for VL53L1X added

**Comment by jimtng** [comment]
I'd also like to have the ROI feature. I'll be happy to help with this PR if needed

**Comment by topic2k** [comment]
@jimtng : this PR works for me to get distances. On my working tree i have a version with threshold values, so i get 0/1 (false/true) if the distance is above, below, between or outside of min/max values. I also played around with people counting. I had the sensor only installed on bredboard and wanted to install it to a test area with a longer cable, but then i got trouble with the i2c bus. I need to investigate a bit more time, it's the first time i do a larger project with an i2c bus. But currently i don't have much time to work on it, maybe in a month or two.
If you want, i can commit my offline working tree and post the link in the next days.

**Pull request closed without merging**
