### PR TITLE
Trigger on finger scan misplaced

### PR DESCRIPTION
**Pull request by alexborro**
# What does this implement/fix?

This PR implements the trigger `on_finger_scan_misplaced`. It is triggered only for configurations with `sensing_pin`.
The purpose is to detecting when the user is not properly (entirely) touching the sensor, like just touching it with the finger tip or off center. This way the user might receive, for example, an Aura Led visual indication of the issue.

It also includes minor fixes related to the "waiting for finger removal" when `sensing_pin` is used. 

The `dump_config` was also improved including the most recent value of the sensors, the `sensing_pin` configuration and the "System Identifier Code" of the sensor - very likely related to the sensor firmware version.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** New feature: `on_finger_scan_misplaced` trigger

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** https://github.com/esphome/esphome-docs/pull/3172

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
    on_finger_scan_misplaced:
      - homeassistant.event:
          event: esphome.frontdoor_finger_scan_misplaced
      - fingerprint_grow.aura_led_control:
          state: FLASHING
          speed: 25
          color: PURPLE
          count: 2
      - text_sensor.template.publish:
          id: fingerprint_state
          state: "Misplaced finger"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by loongyh** [comment]
> The purpose is to detecting when the user is not properly (entirely) touching the sensor, like just touching it with the finger tip or off center.

Interesting.. How does this work? Afaik sensing pin is a binary sensor which signals whether it detects a finger or not. Or is it actually some magnitude value which reports the percentage of the sensor area contacted?

**Comment by alexborro** [comment]
> Interesting.. How does this work? Afaik sensing pin is a binary sensor which signals whether it detects a finger or not. Or is it actually some magnitude value which reports the percentage of the sensor area contacted?

You are right, the `sensing_pin` is binary, triggered by the sensor when you touch it. Even if you touch 1/2 of its surface area, it will send out this signal. And as soon as the component receives this triggers, it will ask for an image scan and then receives a `NOFINGER` as response because you are not properly touching the sensor.

**Comment by loongyh** [comment]
Hmm so during partial finger contact, it'll return `NO_FINGER` instead of `IMAGE_FAIL`/`IMAGE_MESS`/`NO_MATCH`/`NOT_FOUND`? I didn't know there can be a scenario in which sensing_pin is triggered and `NO_FINGER` is returned, except maybe if the finger is removed after the sensing_pin triggers but just before the matching routine starts.

**Comment by loongyh** [comment]
It'd be worthwhile to implement if the grow fingerprint has this feature. However i don't have the bandwidth to test and review this PR at the moment. Perhaps @OnFreund or someone else with a reader can assist.

**Comment by alexborro** [comment]
> Hmm so during partial finger contact, it'll return `NO_FINGER` instead of `IMAGE_FAIL`/`IMAGE_MESS`/`NO_MATCH`/`NOT_FOUND`? I didn't know there can be a scenario in which sensing_pin is triggered and `NO_FINGER` is returned, except maybe if the finger is removed after the sensing_pin triggers but just before the matching routine starts.

Yeap, it returns `NO_FINGER` when you have a partial image. According to the datasheet, there are only 2 possible errors related to the image scan:

- Confirmation code=00H: finger collection success;
- Confirmation code=01H: error when receiving package;
- Confirmation code=02H: **can’t detect** finger;
- Confirmation code=03H: **fail to collect** finger;

And it is not clear the difference between 0x02 and 0x03.
So according to my tests, every time we don't fully cover the sensor, it will return 0x02. The other errors you mentioned might take place further when converting the image to the character file or searching for a match.

Let me know if you need any other information. 

> It'd be worthwhile to implement if the grow fingerprint has this feature. However i don't have the bandwidth to test and review this PR at the moment. Perhaps @OnFreund or someone else with a reader can assist.

That is an important point. I'm planning some more implementations and improvements to this component, like:
- Action to change the Security Level;
- Powering on the sensor only if a finger is detected (https://github.com/esphome/feature-requests/issues/1672)
- Trigger `on_finger_scanning` (https://github.com/esphome/feature-requests/issues/1792)
- Converting the `update()` to a statemachine, which makes it more clear to follow. 

Let me know if there is any way to make it easier for code reviewers.

**Comment by loongyh** [comment]
> And it is not clear the difference between 0x02 and 0x03.
So according to my tests, every time we don't fully cover the sensor, it will return 0x02.

It could be also be a defect in your particular unit, maybe it's not as sensitive which may cause it to return 0x02 when it should return the other codes. that's why we need more testers to ascertain.

I do agree the current loop-based if-else logic leaves a lot to be desired. It was written in-haste as I needed a working implementation then. Much thanks and appreciative of your initiative and efforts in improving this component. To be frank i don't have much time these days to proactively contribute. Looking forward to seeing your contributions merged 😎. No promises but i'll try to scrape some time to review if it's still stuck in the pipeline for awhile.

**Comment by alexborro** [comment]
> I do agree the current loop-based if-else logic leaves a lot to be desired. It was written in-haste as I needed a working implementation then. Much thanks and appreciative of your initiative and efforts in improving this component. To be frank i don't have much time these days to proactively contribute. Looking forward to seeing your contributions merged 😎. No promises but i'll try to scrape some time to review if it's still stuck in the pipeline for awhile.

Yeah, I know how is it, you made the most difficult part: creating the whole component. Now I think we, as users, can delivery back to the community our contribution! ;-)

**Comment by OnFreund** [comment]
Unfortunately I don't have a good way to test this - I'm actually still using my original custom component that I developed before @loongyh converted this to a native component.
The code looks good, though I have never encountered this scenario.

**Comment by alexborro** [comment]
> It could be also be a defect in your particular unit, maybe it's not as sensitive which may cause it to return 0x02 when it should return the other codes. that's why we need more testers to ascertain.

I've just got a new sensor for development and did this test. I've got the same result.

**Comment by grigi** [comment]
I have manually built this, and it is working nicely :+1: 
Definitely an improvement getting feedback that one didn't get a good finger reading

**Comment by jesserockz** [comment]
Is this still valid after https://github.com/esphome/esphome/pull/5885 being merged? If so, please rebase, otherwise please close :pray: 

Thanks
Jesse

**Review by jesserockz — CHANGES_REQUESTED** [review]
Is this still valid after https://github.com/esphome/esphome/pull/5885 being merged? If so, please rebase, otherwise please close :pray: 

Thanks
Jesse

**Comment by alexborro** [comment]
Hi @jesserockz , I see you approved and merged the PR #5885 which re-implements (in a faulty way) what I implemented in this PR. I'm waiting for the owner approval for more than 2 months and nothing happened. What is the criteria for approving and merging code in EspHome ? I also have the PR #5396 open for more than 2 months.

By the way, in a few ways the #5885 can fail is if the user makes a call to the fingerprint read in the "invalid" callback (like for changing the LED color, the exact reason I implemented this), the line 141 of fingerprint_grow.cpp will return the last executed transfer (the one from the invalid callback), not the one from the original call, which must be cached. 

I had a lot of discussion and test in this PR and in the #5396 and even tho I could *not* get attention from the code owners to review and approve it. Could you please clarify what is the proper way to get work along with reviewers in EspHome ? That is very frustrating when such situations happen in open source communities.

**Comment by jesserockz** [comment]
I do apologise about this PR getting left behind, its hard to keep up.

I am not super familiar with the fingerprint modules, but I am happy if you want to add this callback for a specific error type and remove the other callback for this type of error.

Could you at least rebase this PR on top of the latest code so I can see what the actual changes will be?

Jesse

**Comment by alexborro** [comment]
Thanks @jesserockz for the quick response. I will re-work this PR to replace the #5885 , including the documentation (which demands quite some time). The #5885 uses the "invalid" term which is too vague for biometric authentication (it might mean a malformed sample, a sample not authorised, etc), so I will replace it with my original "misplaced" term.
I'm will try to rework this still today and let you know. 
Cheers.
Alex.

**Pull request closed without merging**
