### PR TITLE
Gitpod

### PR DESCRIPTION
**Pull request by alexiri**
# What does this implement/fix?

Installation in Gitpod is broken, this fixes it.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by balloob** [comment]
This means no one uses it. We should delete it so we don't have to maintain it. Adding a button to the README is absurd. No one uses it and it looks like you just want to use our READMEs as advertisement space for gitpod

**Comment by alexiri** [comment]
@balloob I'm sorry you got that impression. I'm not affiliated with Gitpod at all, I simply thought it was a cool service to set up a dev environment and it could make it easier for people to contribute to ESPHome.

**Comment by balloob** [comment]
We very much prefer codespaces, as it's definition can also be used when doing local development and a standard is also available https://containers.dev

**Comment by alexiri** [comment]
Then it's probably worthwhile to mention that in the contribution documentation, I haven't seen it anywhere. Gitpod *is* mentioned there, however, which is actually how I discovered it in the first place. :upside_down_face: 

It's probably also worth noting that Codespaces aren't available to everyone, or at least they aren't to me.

**Comment by balloob** [comment]
Good point, I have opened https://github.com/esphome/esphome-docs/pull/2399

Codespaces should be more widely available soon.

**Pull request closed without merging**
