### PR TITLE
Add deassert_rts_dtr option to force RTS/DTR low when using miniterm

### LINKED ISSUE #1382: Clear RTS and DTR in serial console
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows 10, pip installation

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP-07 (512K Flash)

**ESPHome version (latest production, beta, dev branch)**

1.14.5

**Affected component:**

https://esphome.io/guides/getting_started_command_line.html

**Description of problem:**
I'm using the ESP-07 with only 512K Flash, so I can't use OTA updates, which requires me to use the serial cable. Upload works fine, but after uploading I need to disconnect the RTS and DTR pins to the serial converter, because both lines are held active (low) in the serial terminal and therefore the ESP doesn't start. As soon as I quit the serial terminal from esphome or disconnect RTS and DTR, the program starts.

**Problem-relevant YAML-configuration entries:**
```yaml
NOT RELATED TO YAML

```

**Logs (if applicable):**

```
NO LOG

```

**Additional information and things you've tried:**

I would suggest to change the code of `run_miniterm` to something like this:

```python
    ...
    backtrace_state = False
    # Not specifying a port name does not open the port
    with serial.Serial(baudrate=baud_rate) as ser: 
      ser.port = port
      ser.rts = False
      ser.dtr = False
      ser.open()  # open port, set DTR and RTS inactive
      while True:
      ...
```

### PR DESCRIPTION
**Pull request by agners**
# What does this implement/fix? 

By default RTS/DTR seem to be True (-> 0 since low active). Most ESP32
boards have a pair of transistors to keep Reset/strapping GPIO as-is
when both RTS/DTR are either True _or_ False.
See: https://raw.githubusercontent.com/nodemcu/nodemcu-devkit/master/Documents/NODEMCU_DEVKIT_SCH_BIG.png

If RTS/DTR are connected to Reset/strapping GPIO directly we'd prefer to have
RTS/DTR False (-> 1 since low active). In theory, we could set it to False
always, since the above mentioned logic makes sure nothing happens if both
signals are False.

However, on some platforms (e.g. Linux) setting them to False leads to toggling
when opening which causes a reset.

This introduces a new config "low_rts_dtr" which allows to set the
signals low if required by the board.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/1382

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1348

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
logger:
  deassert_rts_dtr: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — APPROVED** [review]
LGTM :+1: Docs need to be updated though

**Comment by agners** [comment]
Now that I write the documentation, I don't like `low_rts_dtr`: RTS and DTR are often low active in TTL. So setting the signals to false leads to a high voltage level on the effective TTL lines. How about `deassert_rts_dtr`?

**Comment by OttoWinter** [comment]
> How about deassert_rts_dtr?

Works for me :+1:

**Review by jesserockz — APPROVED** [review]
Worked for my C3

**Pull request merged**
