### PR TITLE
HomeAssistant Device Triggers

### PR DESCRIPTION
**Pull request by thoemy**
# What does this implement/fix? 

This implements discoverable Home Assistant device triggers as proposed by @oxan in a [comment](https://github.com/esphome/esphome/pull/3002#issuecomment-1014953743) of #3002.

Triggers defined in the `api` section of a ESPHome configuration are made available through the native API to Home Assistant. When the `homeassistant.trigger` automation is used, then the device trigger is triggered in HA.

image

With these device triggers I can flash my Sonoff Touch with a generic image that exposes single press, double press and long press triggers and configure the behavior entirely in HA. This is also possible with `homeassistant.event` but unfortunately these events are not automatically discovered by HA and therefore the creation of automations is harder.

## TODO

I didn't manage to do this. I need some guidance here.

* [ ] Simplify the trigger call to `homeassistant.trigger: button_1_press`.
  I need a reference to `APIServer` therefore the schema looks like
  ```python
    HOMEASSISTANT_TRIGGER_ACTION_SCHEMA = cv.Schema(
      {
          cv.GenerateID(): cv.use_id(APIServer),
          cv.Required(CONF_TRIGGER): validate_homeassistant_trigger,
      }
  )
  ```
* [ ] Expose the pretty name of the trigger in the HA frontend.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**

* #3002
* [aioesphomeapi](https://github.com/thoemy/aioesphomeapi/tree/triggers)
* [home-assistant/core](https://github.com/thoemy/home-assistant-core/tree/esphome-triggers)

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
api:
  triggers:
    - trigger: button_1_press
      name: Button 1 pressed

binary_sensor:
  - platform: template
    name: "Touchpad 1"
    on_click:
      - then:
        - homeassistant.trigger:
            trigger: button_1_press
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
This sounds like a great idea for a feature!

Before going into how to implement it to the end, I'd like to discuss how we should expose this to the user.

1. We may want to design it so that in the future some integrations (such as `binary_sensor`) can automatically create basic triggers like click/double click, without any config additions. This may change the approach of the design.
1. Do we want to add the option to transmit additional data (arguments) in triggers? Not sure if it's supported by the HA side, but if it is that might be interesting (https://developers.home-assistant.io/docs/device_automation_trigger/)
2. Do trigger names have to be valid cpp var names? Unless there's a limitation on the HA side, I'd say we should allow these to be any string
3. Ideally, the trigger doesn't have to be forward-declared in the `api` block at all. So that the user can just type `- homeassistant.trigger: my_event` anywhere in an automation without navigating across files (we can register the event in the `register_action` setup code).


Code-wise:
1. There's no need for a `SubscribeHomeassistantTriggersRequest` as far as I see, we can just merge it into `subscribe_homeassistant_services` (saves the pain of conditional logic depending on what esphome api version is at the other end), especially since that call just informs esphome that the connected device is like a homeassistant instance (and so can process these events) -

**Comment by thoemy** [comment]
> 1. We may want to design it so that in the future some integrations (such as `binary_sensor`) can automatically create basic triggers like click/double click, without any config additions. This may change the approach of the design.

That sounds good. But with my limited knowledge of the ESPHome internals I probably won't be much of a help here :).

> 2. Do we want to add the option to transmit additional data (arguments) in triggers? Not sure if it's supported by the HA side, but if it is that might be interesting (https://developers.home-assistant.io/docs/device_automation_trigger/)

I didn't include them to keep things simple. It looks like it's possible to add additional data to device triggers but I'm not sure how to access them in automation. It would probably something for more advanced scenarios.

> 3. Do trigger names have to be valid cpp var names? Unless there's a limitation on the HA side, I'd say we should allow these to be any string

Just tested a trigger with umlauts and emoticons. Worked without problems. So we can probably assume that any unicode string is fine.

> 4. Ideally, the trigger doesn't have to be forward-declared in the `api` block at all. So that the user can just type `- homeassistant.trigger: my_event` anywhere in an automation without navigating across files (we can register the event in the `register_action` setup code).

Right, that makes things easier. I'll see if I can make the necessary changes.

> Code-wise:
> 
> 1. There's no need for a `SubscribeHomeassistantTriggersRequest` as far as I see, we can just merge it into `subscribe_homeassistant_services` (saves the pain of conditional logic depending on what esphome api version is at the other end), especially since that call just informs esphome that the connected device is like a homeassistant instance (and so can process these events) -

I'll have a look at it.

**Comment by thoemy** [comment]
@OttoWinter The new version should address the last 3 points.

**Comment by bdr99** [comment]
Hi, is this change still being considered? I'm really looking forward to this feature since it will make creating automations much easier.

**Comment by thoemy** [comment]
I am willing to spend more time improving this change. But I need some assistance in how to do that exactly.

**Pull request closed without merging**
