### PR TITLE
Fix: Component script not stopped in certain situations

### LINKED ISSUE #1105: script.stop fails to stop the script
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip3
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 (lolin32)
**Affected component:**

core/automation

**Description of problem:**
Under some circumstances, doing ``script.stop: monitor_current`` isn't stopping the monitor_current script (included below).  Specifically the script repeatedly calls ``component.update: motor_current`` and that component (motor_current) has an ``on_value_range`` trigger that (indirectly) tries to stop the monitor_current script, but that isn't happening.

motor_current is an ESP32 adc (components/adc/adc_sensor.cpp) where the new value is published immediately from within the ``update()`` method so I guess the script.stop action is triggered from within the component.update action, i.e. nested from within the script that I'm trying to stop, and that may be the issue.

I had a look at the automation code but it's quite complicated so I thought the core developers might arrive at an idea why this is happening much faster.

**Problem-relevant YAML-configuration entries:**
```yaml
script:
  - id: monitor_current
    then:
      - while:
          condition:
            lambda: 'return true;'
          then:
            - component.update: motor_current
            - delay: 50ms

sensor:
  - name: "Lock motor current"
    id: motor_current
    update_interval: never
    internal: true
    platform: adc
    pin: 35
    ...
    on_value_range:
      above: 0.5
      then:
        - cover.stop: door_lock

cover:
  - id: door_lock
    name: "Door lock"
    device_class: door
    platform: time_based
    open_duration: 4s
    open_action:
      - script.stop: close_later
      - output.turn_off: motor_close
      - output.turn_on: motor_open
      - script.execute: monitor_current
      - script.execute: close_later
    close_duration: 6s
    close_action:
      - script.stop: close_later
      - output.turn_off: motor_open
      - output.turn_on: motor_close
      - script.execute: monitor_current
    stop_action:
      - output.turn_off: motor_open
      - output.turn_off: motor_close
      - script.stop: monitor_current
```

**Logs (if applicable):**

```
[19:48:10][D][cover:072]: 'Door lock' - Setting
[19:48:10][D][cover:080]:   Position: 0%
[19:48:10][D][cover:152]: 'Door lock' - Publishing:
[19:48:10][D][cover:155]:   Position: 88%
[19:48:10][D][cover:168]:   Current Operation: CLOSING
[19:48:10][D][adc:056]: 'Lock motor current': Got voltage=0.16V
[19:48:11][D][sensor:092]: 'Lock motor current': Sending state 0.54351 A with 2 decimals of accuracy
[19:48:11][D][cover:072]: 'Door lock' - Setting
[19:48:11][D][cover:076]:   Command: STOP
[19:48:11][D][cover:152]: 'Door lock' - Publishing:
[19:48:11][D][cover:155]:   Position: 87%
[19:48:11][D][cover:168]:   Current Operation: IDLE
[19:48:11][D][adc:056]: 'Lock motor current': Got voltage=0.00V
[19:48:11][D][sensor:092]: 'Lock motor current': Sending state 0.00000 A with 2 decimals of accuracy
[19:48:11][D][adc:056]: 'Lock motor current': Got voltage=0.00V
[19:48:11][D][sensor:092]: 'Lock motor current': Sending state 0.00000 A with 2 decimals of accuracy
[19:48:11][D][adc:056]: 'Lock motor current': Got voltage=0.00V
[19:48:11][D][sensor:092]: 'Lock motor current': Sending state 0.00000 A with 2 decimals of accuracy
[19:48:11][D][adc:056]: 'Lock motor current': Got voltage=0.00V
[19:48:11][D][sensor:092]: 'Lock motor current': Sending state 0.00000 A with 2 decimals of accuracy
[19:48:11][D][adc:056]: 'Lock motor current': Got voltage=0.00V
...
```

**Additional information and things you've tried:**

### PR DESCRIPTION
**Pull request by balrog-kun**
## Description:

This attempts to fix issue #1105 and a potential unrelated issue with is_running.  See the commit messages and my doubt about protecting against running a script from within the script and ending up running out of stack (if the call is nested) or other resources (if there was a delay since the script starte perhaps?)..

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/1105

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

**Comment by glmnet** [comment]
Ok you've made me read a lot of interesting code 

While this fixes your issue, I see there that any other use of play like in `UpdateComponent` will have the same issue, i.e. in any Action which could itself trigger another Action won't be able to stop the script from which the original Action was called. Am I right?

**Comment by balrog-kun** [comment]
> Ok you've made me read a lot of interesting code

I felt the same way ;-)

> 
> While this fixes your issue, I see there that any other use of play like in `UpdateComponent` will have the same issue, i.e. in any Action which could itself trigger another Action won't be able to stop the script from which the original Action was called. Am I right?

Right.  When I wrote that patch I looked only through `esphome/core/base_automation.h` and concluded no other action triggered Triggers but that was obviously wrong.

So I wonder if I should make a list of all the actions that may need fixing, or try to move my fix to the Action base class in `esphome/core/automation.h`.  This change shouldn't really hurt in the base class, it would basically modify `play_complex` to not call `play_next` if the Action has been stopped.

After that I guess the subclasses that override `play_complex` might still need to be checked but there should be less work than if we wanted to add this fix in every subclass.

**Comment by glmnet** [comment]
Yes, I believe modifying base class is a better idea.

Most classes (if not all) which overrides play_complex are in the same automation.h file, where all other which uses play all around the components code base.

Besides the typical component coder should write Action implementations which simple executes play without worrying about play_complex at all

Thanks

-- 

I haven't tested your example in https://github.com/esphome/issues/issues/1105 (as English isn't my first language) I don't understand if it is easily reproducible bug or happens just some times?

**Comment by balrog-kun** [comment]
> Yes, I believe modifying base class is a better idea.
> 
> Most classes (if not all) which overrides play_complex are in the same automation.h file, where all other which uses play all around the components code base.

Yep.

However, I started on this and I noticed two things that are making me question the Action class structure.  I could add a `bool Action::is_running_` like in my original patch and it would mostly solve the issue.  But firstly, it's going to duplicate `int DelayAction::num_running_` that has exactly the same function, so I should probably just move that from DelayAction to Action.

Secondly though that whole variable makes no sense being duplicated in all Actions within an ActionList.  `is_running` is going to either be true or false for the whole ActionList.  It was already slightly redundant being in all DelayActions but it's more redundant being in all Actions.

So if we wanted to move it to ActionList, the class structure would need to change a little, I guess this needs little more thought.

Another issue is that a script.stop stops all instances of the script that may be currently running, that's fine.  But if that script is restarted within some action, its `num_running_` is going to be back to a non-zero value and all instances that were running before it stopped will be active again instead of only one new instance running.  Possibly this issue is too philosphical but it would be nice to come up with a mechanism that handles this right without adding redundant state variables.  I'm gonna give it some more thought.

> 
> Besides the typical component coder should write Action implementations which simple executes play without worrying about play_complex at all
> 
> Thanks
> 
> --
> 
> I haven't tested your example in [esphome/issues#1105](https://github.com/esphome/issues/issues/1105) (as English isn't my first language) I don't understand if it is easily reproducible bug or happens just some times?

It happens every time that `script.stop` is used within a `component.update` action, that `script.stop` gets ignored in the end.

**Comment by balrog-kun** [comment]
So doing something like moving the "is_running" state into ActionList implies bigger changes to the classes and I'm not sure it can be done without losing the size benefit.

So for now I've re-done the commit to basically move `DelayAction::num_running_` to `Action`.  This should be safe to do without a bigger discussion and at the same time it's kind of tricky to review, because of the changes in `IfAction`, `WhileAction`, `WaitUntilAction`, `WaitScriptAction` etc., so I guess this is enough of a change for this commit.  You'll notice I also added checks for `num_running_ > 0` after conditions are checked... in theory conditions can also have side-effects, like in C++, although you could say if someone is side-effecting in their conditions then they're screwed, but I guess it's good for the code to be extra careful.

The second commit is a proposal to make most of the `Action` members protected, those that are not supposed to be used from outside of the classes.  I think this will make the code slightly easier to understand for someone seeing automation.h and wondering what is going on.  But, feel free to ignore this commit if you don't agree.

**Comment by glmnet** [comment]
Linter is mad 😈

Anyway, looks great, I was testing and found a behavior change in one in my nodes, now that I've been thru the code I understand why my fan in my bathroom never stops:

full code here: https://github.com/glmnet/esphome_devices/blob/master/EHEstudio.yaml

But this script, before it worked ok and now I believe it stops itself and the execution does not go below i.e. delay 600s is not executed

````yaml
script:
  - id: auto_off_extractor
    then:
    - script.stop: auto_off_extractor
    - delay: 600s
    - fan.turn_off: extractor_banio
````

I wonder if I was hacking it or this was expected to work this way, will have to check the docs and make sure we are not changing documented behavior

**Comment by balrog-kun** [comment]
> Anyway, looks great, I was testing and found a behavior change in one of my nodes, now that I've reviewed my script code I understand why my fan in my bathroom never stops:
> 
> full code here: https://github.com/glmnet/esphome_devices/blob/master/EHEstudio.yaml
> 
> But this script, before it worked ok and now I believe it stops itself and the execution does not go below i.e. delay 600s is not executed, which makes sense, everything makes sense, however this is a change in behavior

Thanks for testing, so apparently users might be relying on the old behaviour.  I think the intent in your script was to stop all **other** instances of the script, so all the instances that were in the `delay` at that moment.  Like you noted one solution is to stop the script before starting a new instance.

But the question will be which behaviour makes more sense and whether the esphome project has a backwards compatibility policy, and what's more important.  Unfortunately I can't answer any of that.  At the very least, if accepted, this change might need a note in the Release Notes or wherever such things can be notified.

> 
> ```yaml
> script:
>   - id: auto_off_extractor
>     then:
>     - script.stop: auto_off_extractor
>     - delay: 600s
>     - fan.turn_off: extractor_banio
> ```
> 
> I wonder if I was hacking it or this was expected to work this way, will have to check the docs and make sure we are not changing documented behavior
> 
> Anyway, this is (was) an interesting implementation of a sliding timer
> 
> I modified my scripts to call stop before calling execute on the sliding timers scripts, let's see how it goes

This is what I was doing, too, actually my bathroom extractor code is similar and I also started commenting the cable colours/orders in my .yaml files :wink: 

> 
> Anyway, I like your code, not sure why we do need the num_executions... how do you understand it?

Do you mean the difference between `num_running_` as a number and `is_running_` as a bool?  I think they're equally good, I'm not sure why `DelayAction` used an int, maybe some historical reasons but I suspect the int operations / conditions are just as fast as bool.

> I really a bit confused and also I don't know what the user would expect, docs are not very comprehensive here, may be in advantage of the code, looks like they can be running in different pseudo "threads" but I don't know if this is actually a good idea for a script thing

Right, so I couldn't find docs on the scripts semantics, maybe the user is expected to use lambdas when their use case is advanced enough that this even matters. Yes, that code is really interesting in that it keeps the state of each script execution only on the stack or in the timeout closure, it's like it was inspired by some functional programming language.

So ideally the original author -- Otto Winter -- would give his point of view on this change.  Thanks for the review so far!

**Comment by glmnet** [comment]
So, I want to merge this one but linter is mad, I didn't want to change the linter settings, anyway, rules are virtual method cannot end in `_` even when they are protected, however override members in inheritors are checked but they don't follow the same rules a virtual which seems weird, however Otto seems to hit this wall already and he made override members public (being more fluent in C# I wouldn't have even tried that) so bottom line is protected: virual method does not end in `_` and overriden members are public.

So I'm pushing a commit satisfying this

Then I'd like to understand better what happens when you run scripts which are already running, most likely those with delay or wait for conditions, etc.

I'd like them to stop and start over by default, i.e. a script cannot be running two "instances" simultaneously, what do you think?
I vote this because this should be easier to understand / expect

**Comment by balrog-kun** [comment]
> So, I want to merge this one but linter is mad, I didn't want to change the linter settings, anyway, rules are virtual method cannot end in `_` even when they are protected, however override members in inheritors are checked but they don't follow the same rules a virtual which seems weird, however Otto seems to hit this wall already and he made override members public (being more fluent in C# I wouldn't have even tried that) so bottom line is protected: virual method does not end in `_` and overriden members are public.
> 
> So I'm pushing a commit satisfying this

Thanks for investigating! I understand the linter is happy after this?

So BTW the methods are now protected in the base class and public in the subclasses? Ok.  If you prefer I can just drop my second commit.

> 
> Then I'd like to understand better what happens when you run scripts which are already running, most likely those with delay or wait for conditions, etc.
> 
> I'd like them to stop and start over by default, i.e. a script cannot be running two "instances" simultaneously, what do you think?
> I vote this because this should be easier to understand / expect

Yeah, that would certainly be easy to understand but it's not the case right now.  Right now you can start as many instances as you like and they will be running "in parallel".

I guess Otto Winter should weight in on such a change because I think the action classes are designed with the assumption that you can have more than one instance running, otherwise the design could be simplified.

**Comment by balrog-kun** [comment]
Thanks for the work on this!

One comment: looking at https://github.com/esphome/esphome/commit/c99b2b59c2cd202f52ba7b4889218fd124842a64 I think "protected:" was accidentally dropped in https://github.com/esphome/esphome/blob/dev/esphome/components/display/display_buffer.h#L400-L428, esphome/components/esp8266_pwm/esp8266_pwm.h and esphome/components/fan/automation.h , not sure what happened there.

**Comment by glmnet** [comment]
Ohhh I hit a sync button in my IDE and some merge went in. Maybe it’s related to that. I’ll check in a moment. 

Thanks for all this and for this update

Btw. I decided to merge this so your bug gets fixed and just added the doc that the script can stop itself now.

**Pull request merged**
