### PR TITLE
[modbus_text_sensor] new default ANSI encoding type

### PR DESCRIPTION
**Pull request by dudanov**
# What does this implement/fix?

New default `ANSI` encoding.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3994

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
Wouldn't this be a potential breaking change for anyone who is using/parsing data that had the nulls in it?
(A breaking change is not a bad thing, just needs to be clear)

**Comment by dudanov** [comment]
> Wouldn't this be a potential breaking change for anyone who is using/parsing data that had the nulls in it?
> (A breaking change is not a bad thing, just needs to be clear)

I don't think this will be a breaking change.  It is unlikely that there are devices that transmit null characters between characters.  Only the case when the register encodes a character.  In this case, it is precisely necessary to filter nulls.  The concept of a C-STRING implies a sequence of characters that ends with a null character.  Even if the device needs to transmit enumeration of strings, separators such as commas, semicolons, etc. will be used.

**Comment by dudanov** [comment]
This might be an option:

We already have a NONE filter, which will pass all characters without filtering. And by default, make sure that null character filtering is always used. I will reflect these changes in the documentation.

What do you think of this option, Jesse?

**Comment by jesserockz** [comment]
Do you mean add another Encoding type that will do the null filtering?

**Comment by dudanov** [comment]
> Do you mean add another Encoding type that will do the null filtering?

Yes, I create a new `Encoding type` and use it instead of `NONE` by default.  And those few users who really need zero characters in their config use the `NONE` `Encoding type`.

**Comment by dudanov** [comment]
Hmmm... Well, somehow the issue of filtering null characters turned into an `ANSI` encoding type. :)

**Comment by nagyrobi** [comment]
Is change this documented?

**Comment by dudanov** [comment]
> Is change this documented?

Yes, I added a link.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
