### PR TITLE
[test][web_server] Rejig test for v3

### PR DESCRIPTION
**Pull request by RFDarter**
# What does this implement/fix?

Rejig test to all test for v3

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
What is the purpose of duplicating this exactly?
If v3 needs more on top of common, it can just add them. 
If you are getting yaml key conflicts, change it to use `packages` instead of `<<: !include` so it can be merged.

**Comment by RFDarter** [comment]
> What is the purpose of duplicating this exactly?
> If v3 needs more on top of common, it can just add them. 
> If you are getting yaml key conflicts, change it to use `packages` instead of `<<: !include` so it can be merged.

V3 would need to add:
```yaml
  webserver:
    sorting_weight: 5
    sorting_group: group_id
```
to some components.

Would there not be a conflict if there are duplicates in the yaml if common allready sets all the components and common_v3 would set them again?

**Comment by jesserockz** [comment]
> Would there not be a conflict if there are duplicates in the yaml if common allready sets all the components and common_v3 would set them again?

That is what using `packages` solves because it will merge properly.

**Comment by RFDarter** [comment]
> > Would there not be a conflict if there are duplicates in the yaml if common allready sets all the components and common_v3 would set them again?
> 
> That is what using `packages` solves because it will merge properly.

I never used `packages` so I had to look it up :D
So I guess this PR would not be necessary to make v3 tests possible then.
But I reverted to the original files and replaces `<<: !include` with `packages` to keep it constant with the `common_v3.yaml` from the grouping PR

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
