### PR TITLE
Packages feature

### LINKED ISSUE #437: Enhance !include
**Describe the problem you have/What new integration you would like**

I would like to use includes as templates and rely on substitutions instead of 'standard' changes.

### Example 1
Splitting out the touch sensor in to `capacitivetouch.yaml`

```yaml
esp32_touch:
  setup_mode: false

binary_sensor:
  - platform: esp32_touch
    name: $touchname
    id: mainbutton
    pin: $touchpin
    threshold: 500

    on_click:
      then:
        - light.turn_off: mainlight
```

### Example 2
Encapsulating everything to do with wifi in to `mywifisettings.yaml`

```yaml
wifi:
  ssid: $wifiNameToJoin
  password: $wifiPasswordToJoin

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $accesspointSSID
    password: "esphomeisgreat"

captive_portal:
```

### Example 1

```yaml
light:
    ...
    effects:
      - flicker:
          name: Flicker
          alpha: 95%
          intensity: 1.5%
      - strobe:
          name: Strobe
          colors:
            - state: True
              brightness: 100%
              red: 100%
              green: 100%
              blue: 100%
              white: 100%
              duration: 80ms
            - state: False
              duration: 80ms
      !include includes/genericSingleLEDEffects.yaml
      !include includes/testing/lambdaEffect1.yaml
```

### Example 2 (this one may go a little far)
*Allows for the `!include`s to interact with the tree-based data object itself, not just as text*

`lamp4.yaml`
```yaml
substitutions:
  devicename: lamp4
  upper_devicename: Lamp 4
  ledpin: GPIO18
  upper_devicename2: Lamp 4 (2)
  ledpin2: GPIO19
  onboardledpin: GPIO22

switch:
  - platform: gpio
    pin: $onboardledpin
    name: "Onboard LED"
    id: onboard_led
    internal: true
    inverted: yes

light:
  - platform: monochromatic
    name: $upper_devicename
    output: output_component1
    default_transition_length: 500ms

output:
  - platform: ledc
    id: output_component1
    pin: $ledpin
    frequency: 50000
    bit_depth: 10

!!include includes/twoOutputs.yaml # '!!' is a notation I just made up, meaning 'overwrite any conflicting entries with the ones from the included file'.
```

`twoOutputs.yaml`
```yaml
light:
  - platform: monochromatic
    name: $upper_devicename
    output: output_component1
    default_transition_length: 500ms
  - platform: monochromatic
    name: $upper_devicename2
    output: output_component2
    default_transition_length: 500ms

output:
  - platform: ledc
    id: output_component1
    pin: $ledpin
    frequency: 50000
  - platform: ledc
    id: output_component2
    pin: $ledpin2
    frequency: 50000
```

**Please describe your use case for this integration and alternatives you've tried:**

I want to be able to create dozens of lights based on ESPHome, and 'centrally' manage the settings/properties.
If I find a better touch threshold, or a light transition that I particularly like, then it's just a matter of modifying it in one place and uploading to all devices.

**Additional context**

I know that this goes further than HomeAssistant's yaml import, but that's designed to allow splitting up a monolithic single config, whereas ESPHome is about configuring multiple devices.

### PR DESCRIPTION
**Pull request by corvis**
## Description:

Implementation of the new way to "modularize" esphome configuration which could be very useful when you have some common pieces of config, you do not want to repeat yourself but yuml `!include` feature is not enough.

This basically allows to put common pieces of configuration in separate files and keep only unique pieces of your config in the main yaml file. All definitions from packages will be merged with your main config in non-destructive way so you could always override some bits and pieces of package configuration.

Consider the example below. Note how the piece of configuration describing ``api`` component in ``device_base.yaml`` gets merged with the services definitions from main config file.

```yaml
# === In config.yaml === 
substitutions:
  node_name: mydevice
  device_verbose_name: "My Device"

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

api:
  services:
    - service: start_laundry
      then:
        - switch.turn_on: relay
        - delay: 3h
        - switch.turn_off: relay    

sensor:
  - platform: mhz19
    co2:
      name: "CO2"
    temperature:
      name: "Temperature"
    update_interval: 60s
    automatic_baseline_calibration: false

# === In common/wifi.yaml === 
wifi:
  ssid: "sour_ssid"
  password: !secret wifi_password
  domain: .yourdomain.lan
  fast_connect: true

# === In device_base.yaml === 
esphome:
  name: ${node_name}
  platform: ESP32
  board: wemos_d1_mini32
  build_path: ./build/${node_name}

# I2C Bus
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: True
  frequency: 100kHz

# Enable logging
logger:
  level: ${log_level}

api:
  password: !secret hass_api_key
  reboot_timeout: 1h

sensor:
  - <<: !include common/sensor/uptime.config.yaml
  - <<: !include common/sensor/wifi_signal.config.yaml
binary_sensor:
  - <<: !include common/binary_sensor/connection_status.config.yaml

switch:
  - !include common/switch/restart_switch.config.yaml
```

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/437 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#582

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by corvis** [comment]
Does anyone now why CI checks fail even before start linting with this message?

> apt-get install failed The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install clang-tidy-7 clang-format-7" failed and exited with 100 during .

**Comment by glmnet** [comment]
@ssieb @kbx81 @igg I'd love to have your feedback on this one!

**Comment by kbx81** [comment]
@glmnet my feedback: this is pretty cool and is definitely something we could use. I know a couple of other folks who also use ESPHome and would love it...

**Comment by igg** [comment]
@glmnet, I only have a handful of ESPHome things, but I can already see the utility in a central config for wifi for example, common bus setups, other global configurations where the include directive was limited. It would really simplify much more complex setups with dozens of devices.

**Comment by glmnet** [comment]
I'm ok with this too, is just that if we are going to add this, it'd be nice to get some feedback.

It doesn't seem too intrusive, how does it play along with the validator when there are issues inside packages, etc.

I see a few yaml files in the `test_packages` folder which seems to be unused?

**Comment by corvis** [comment]
Hi @glmnet,

Validator recognizes the origin of yaml config from packages and reports errors in the same way as for any other configuration. It also notifies user about the file containing an issue so it is pretty straight forward to locate it. Please see example below:

I have a main config file called `test_packages_main.yaml` which uses package from the file `test_packages/test_packages_package1.yaml` and this package contains invalid config for uptime sensor. 
As you could see validation message includes information about exact file containing mistake.

Packages error handling example
 
As for the yaml files in `test_packages` they are referrenced from `test_packages_main.yaml` which is in the root of the tests folder. Im not sure if there is a proper unit tests approach for python code right now, at lest Readme.md say it is not there yet. So I tested everything just by running CLI command against these yaml examples. Please let me know if there is any better way

**Comment by glmnet** [comment]
Sorry for the delay, I was checking locally how it works, as you said the errors are correctly indicated in the right file, 
It plays nicely with the vscode extension, by design it skips checking of files which are required by other files, although it gets confused if the package is not included from any node file.
On the dashboard, it will need some additional support I guess, it might be a good idea to have the packages in a subfolder, but that is another issue.

Please remove the test scripts and fix the conflicts and let's put this on dev to see what happens.

To add tests like that some test automation should trigger those test, like its done in test_.yaml files, however this adds build time on the CI, for each file the full esphome pipeline is run, and I don't find it really useful since this is only yaml generation and the output result is not checked.

In any case you can modify test1.yaml and add a `package: ` entry there, of course you'll need one extra file then, this way we don't add compile time and the code is covered in the test

**Comment by corvis** [comment]
Hey @glmnet thanks for verifying this. Good point about dashboard, I never used it so even forgot to check how does it work with this new feature. 

As for the test yaml configs - I removed the file I created earlier for tests and incorporated `packages:` into existing `test1.yaml` files in `test_packages` were preserved as they are referenced from `test1.yaml`.

**Comment by ashmckenzie** [comment]
Great to see this as part of 1.15! ❤️ 🙂

**Pull request merged**
