### PR TITLE
Upgrade clang-format to v13

### PR DESCRIPTION
**Pull request by oxan**
# What does this implement/fix?

Upgrade clang-format to v13, and apply some changed formatting (which mostly seems to be actually honoring the `SpaceAfterCStyleCast` setting).

@nielsnl68 This should solve the problem you mentioned [here](https://github.com/esphome/esphome/discussions/4436#discussioncomment-5159284), it was caused by a version mismatch between the clang-format your VScode used and what we used in CI.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nielsnl68** [comment]
> @nielsnl68 This should solve the problem you mentioned [here](https://github.com/esphome/esphome/discussions/4436#discussioncomment-5159284), it was caused by a version mismatch between the clang-format your VScode used and what we used in CI.

Perfect, i will comeback when i found other differences, when i see them.

**Comment by nielsnl68** [comment]
BTW. Not sure of i should put it here, There is on `clang` requirement that i really dislike and that is the need to have the following:
```cPP
    if (1 == 1)
      return;
```
To me, this could be allow to introduce bugs when someone add a new line between the `if` statement and the `return;`  or could be wrongly read when de code writer misses the decency to do proper indents etc. 
there for imho the above statement should always be:
```cpp
    if (1 == 1)  return;
```
or 
```cPP
    if (1 == 1) {
      return;
    }
```
But that is just me. Not sure why clang does want this to have the `return;` on the new line.

**Comment by oxan** [comment]
> BTW. Not sure of i should put it here, There is on `clang` requirement that i really dislike and that is the need to have the following:

To be honest, I prefer the way it currently is. Putting it all on one line makes it too easy to miss the return, while the variant with the braces is overly verbose. In my experience it doesn't happen often that you insert something in between and create a bug; clang-format also automatically adjusts the indents so it should be evident that the return is no longer conditional.

That said, you're free to always add braces in your own code, I don't think any of the clang tools remove them.

**Comment by jesserockz** [comment]
While I like the single line return personally, for a project this size and so many people looking at it, it makes sense to drop it to the next line.

Haha the `SpaceAfterCStyleCast` is something I always have to manually adjust locally too

**Pull request merged**
