### PR TITLE
ili9341: use larger SPI transfers

### PR DESCRIPTION
**Pull request by numo68**
# What does this implement/fix? 

I noticed that the refresh of the ILI9341 display is quite slow, estimated at several hundreds of milliseconds. 150 kB (320 . 240 . 2 bytes) transferred over the 40 MHz serial bus should not take that long so I started investigating. The present driver uses write_byte to tranfer every byte of the display buffer which seemed a non-trivial amount of code and SPI hardware interaction.

This patch prepares the transfers in 64-byte chunks, then asks the driver to transfer an array. The result is a visible faster redraw of the display.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (non-breaking change which fixes performance)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [x] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

# Explain your changes

I did not create an issue for this as this is just an optimization fix. The original redraw speed however interfered with the responsiveness of the device in general, there was a perceptible lag with other hardware (buttons). 

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by SenexCrenshaw** [comment]
I have been incorporating some of your ideas into a larger PR
https://github.com/esphome/esphome/pull/1386

I ported your driver in that PR to show how this will all work and the fact that the display is now usable on a 8266.  With my INDEXED8 buffer type i need barely any RAM and refreshes quickly (I scope it). I found that a 64 x uint8_t buffer is the sweet spot for speed which makes sense because SPI will chunk up anything bigger into 64 byte chunks on write.

The goal is to take all of the various ideas (buffer size, partial updates, color conversion) and put them into a new API (my PR) that any display driver developer will have immediate access to.

``buffer_base.h`` has ``transfer_buffer_size`` and ``#define NO_PARTIAL`` you can mess with to see your own results. 

It would be great to hear your thoughts.

**Comment by SenexCrenshaw** [comment]
Yeah it has psram support. So it lets you swap buffer types out. The types
are the storage type really. So RGB332 stores color in a 332 bit space, 565
does 565... INDEXED8 stores the color as an index of colors. So like a
palette of predefined colors. Most displays only need a few colors so this
save a lot of RAM and isnt too slow! All the buffers support getting a
color back as 332/565/666 so the INDEXED8 being small only needs <10K and
can output that in 18bits. Checkout the driver. there is a is_18bit_()
function. just remove the ``return false;`` and it will display in 18bit.

Here is a sample config

display: - platform: ili9341 model: TFT 2.4 id: my_display reset_pin: D1
cs_pin: D8 dc_pin: D2 rotation: 0 update_interval: 5s device_width: 96
device_height: 120 col_start: 0 row_start: 0 buffer: type: INDEXED8 colors:
- color: kbx_red - color: kbx_green - color: kbx_blue pages: - id: page1
lambda: |- it.print(0, 10, id(my_font), kbx_green, "Page 1"); - id: page2
lambda: |- it.print(0, 10, id(my_font), kbx_green, "Page 2");

**Review by OttoWinter — COMMENTED** [review]
Thanks!

I just updated the branch with the latest upstream changes. Can you or someone else try if this code still works?

**Comment by numo68** [comment]
> Can you or someone else try if this code still works?

Hello @OttoWinter , yes, it still works fine. Thanks.

**Comment by oxan** [comment]
It seems we can merge this then :)

**Pull request merged**
