### PR TITLE
New CAN bus BMS component

### PR DESCRIPTION
**Pull request by clydebarrow**
# What does this implement/fix?

Add a new component that captures BMS data via CAN bus. Docs in ESPHome-docs.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3087

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml. See also examples in ESPHome docs new file.
canbus_bms:
  - id: byd_bms
    canbus_id: can0
    debug: false
    name: BYD Battery
    throttle: 10s
    timeout: 30s
  - id: jakiper_bms
    canbus_id: can1
    name: Jakiper Battery
    debug: false
    throttle: 10s
    timeout: 30s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by clydebarrow** [comment]
So this is failing *only* in the Docker/Arduino CI run with these errors:

```
Error: /home/runner/work/esphome/esphome/esphome/components/canbus_bms/canbus_bms.h:113:28: error: initializing non-owner argument of type 'std::vector<esphome::canbus_bms::FlagDesc *, std::allocator<esphome::canbus_bms::FlagDesc *>>::value_type &&' (aka 'esphome::canbus_bms::FlagDesc *&&') with a newly created 'gsl::owner<>' [cppcoreguidelines-owning-memory,-warnings-as-errors]
    this->flags_.push_back(new FlagDesc(key, message, msg_id, offset, bit_no, warn_offset, warn_bit_no));

```

Now I kind of see what it's saying, but I have absolutely no idea what to do about it.

**Comment by clydebarrow** [comment]
Well, I think I figured it out. Just reinforces my hatred of C++ and its total unsuitability for embedded work.

**Comment by functionpointer** [comment]
BMS is a pretty generic name. Does this use a specific protocol, or can it really read all BMSes?

I have a similar PR specific for Pylontech: https://github.com/esphome/esphome/pull/4688

**Comment by clydebarrow** [comment]
> BMS is a pretty generic name. Does this use a specific protocol, or can it really read all BMSes?

Obviously not all, but it seems there is more commonality in the CAN bus protocols than the serial (RS485/RS232) interfaces. The CAN bus data does not include the same level of detail as the serial interfaces (no cell voltages etc) so it's primarily for interfacing between BMSes and inverter/chargers. This PR is the basis for another that will merge data from different battery systems and present it as a single battery to an inverter. I have that working as of today.

With some further work there's no reason why that component shouldn't be able to support serial interfaces as well but I have to start somewhere.

**Comment by SeByDocKy** [comment]
> > BMS is a pretty generic name. Does this use a specific protocol, or can it really read all BMSes?
> 
> Obviously not all, but it seems there is more commonality in the CAN bus protocols than the serial (RS485/RS232) interfaces. The CAN bus data does not include the same level of detail as the serial interfaces (no cell voltages etc) so it's primarily for interfacing between BMSes and inverter/chargers. This PR is the basis for another that will merge data from different battery systems and present it as a single battery to an inverter. I have that working as of today.
> 
> With some further work there's no reason why that component shouldn't be able to support serial interfaces as well but I have to start somewhere.

Very nice work ..... I  guess a more or less exhaustive list of compatible BMS can set up versus time. The idea to "merge" several canbus infos into a big one is interesting.....

**Comment by danielschramm** [comment]
Name should make clear if it consumes Data from a BMS or if it can act as a BMS.
Both functionalities might be interesting for users.

**Comment by clydebarrow** [comment]
> Name should make clear if it consumes Data from a BMS or if it can act as a BMS. Both functionalities might be interesting for users.

It does both - consumes BMS data and emulates a BMS. Any suggestions for a more descriptive name?

**Comment by clydebarrow** [comment]
> Name should make clear if it consumes Data from a BMS or if it can act as a BMS. Both functionalities might be interesting for users.

The work in this PR consumes BMS data and makes it available as sensors. In that respect I think "bms" in the name is in line with other sensor-type devices. I have further work in progress that emulates a BMS but it will be a separate component. Suggestions for a more descriptive name for this PR would be welcome.

**Comment by clydebarrow** [comment]
> . The idea to "merge" several canbus infos into a big one is interesting

I have this all working - it's in https://github.com/clydebarrow/esphome.git branch charger. Can't submit PR until this PR is merged.

Screenshot 2023-09-23 at 11 56 56 am

**Pull request closed without merging**
