### PR TITLE
Integration for SimpleEVSE car charger.

### PR DESCRIPTION
**Pull request by stegm**
# What does this implement/fix? 

This PR provides a integration of the popular Simple EVSE car charger (http://evracing.cz/simple-evse-wallbox). It provides:
* various sensors of the state  (vehicle state, EVSE state, charge current, etc)
* services for charging current and disable of charging
* simple web page for configuration of the Simple EVSE

The Simple EVSE is connected to an UART of the ESP and communicates with the modbus protocol.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** na

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1142
  
# Test Environment

- [x] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
uart:
  baud_rate: 9600
  rx_pin: GPIO16
  tx_pin: GPIO17

simpleevse:
  web_config: enable

binary_sensor:
  - platform: simpleevse
    connected:
      name: "Connected"

sensor:
  - platform: simpleevse
    set_charge_current:
      name: "Set Charge Current"
    actual_charge_current:
      name: "Actual Charge Current"
    max_current_limit:
      name: "Max. Current Limit"
    firmware_revision:
      name: "Firmware Revision"

text_sensor:
  - platform: simpleevse
    vehicle_state:
      name: "Vehicle State"
    evse_state:
      name: "EVSE State"

switch:
  - platform: simpleevse
    name: "Charge Enable"
```

# Explain your changes

**Introduction**

The SimpleEVSE is a very popular and cheap car charger for EV's but lacks a reasonable integration for HA or even WiFi. There are some other projects like openWB (https://openwb.de/) or SimpleEVSE-WiFi (https://github.com/CurtRod/SimpleEVSE-WiFi) but all I know are very opinionated, bloated and not very modular. ESPHome on the other side is very simple and its modularity  enables integration with other devices. For example I added a push button via the GPIO integration to switch on/off the charging.

**Communication to Simple EVSE**
SimpleEVSE provides a serial modbus interface to read and write registers. Unfortunately I could not use the existing modbus implementation without changing it almost completely. I therefore implemented it directly into the integration itself to avoid breaking existing code.

The main class for the modbus implementation is `ModbusDeviceComponent`. It is a `UARTDevice` and a `Component`. This class is responsible to send and receive a modbus frames via the uart. It respects all timing of the protocol. If no request is active and all wait times are expired, the pure virtual `idle()` method is called. The actual modbus requests are subclasses of `ModbusTransaction`. Currently there two subclasses, one for reading and one for writing registers. The `ModbusTransaction` instances are responsible for creating the modbus request frame and parsing the modbus response. Clients of the modbus interface can register callbacks which are notified after a transaction completes either successfully or with an error.

I observed that sometimes no responses are received from the SimpleEVSE for whatever reason. I therefore added resending a request if it times out.

**Main platform 'simpleevse'**
The main platform is implemented in the class `SimpleEvseComponent` which is subclasses from `ModbusDeviceComponent`. It is responsible to poll the state of the SimpleEVSE regularly. It also maintains a queue with waiting modbus transaction to execute. The main function is `idle()` which is called from the base class as soon as no modbus transaction is active. 

Each time the status is updated all registered listener a notified about the status update.

**SimpleEVSE sensors**
The class `SimpleEvseSensors` provides multiple sensors which can be configured in the yaml. It simply registers on `SimpleEvseComponent` for updates and sets the configured sensors according the the state.

**SimpleEVSE switch**
Currently there is a single switch which is implemented in `SimpleEvseChargingSwitch`. The switch enables/disabled charging. Changing the state result in a modbus write transaction to specific register. It also listens to updates if the enable state is changed elsewhere.

**Actions**
There are two actions implemented `SetChargingCurrent` and `SetChargingEnabled` which can be used by automations or can be mapped to home assistant services. Executing the action results in a modbus write transaction.

**Configuration register web page**
If enabled in the yaml file, a sub web page (/simpleevse/) is provides which displays the configuration register of the simple evse. This register are rarely changed, but may be really helpful if you want to change some of the settings.

The web page is implemented in the class `SimpleEvseHttpHandler`. If the URL is called, the configuration registers are read using a modbus read transaction. If the user wants to change any of it a modbus write transaction is executed.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by stegm** [comment]
The checks failed with some wired error

`Error: fatal: unable to access 'https://github.com/esphome/esphome/': The requested URL returned error: 500`

so I tried to retrigger the tests, but they still need someone to approve.

**Comment by torfbolt** [comment]
Tested this with my wallbox. Seems to work quite well, but I noticed there's a typo in the action names: "simplevse" should be "simpleevse".

**Comment by torfbolt** [comment]
Maybe #1779 is relevant here as well?

**Comment by stegm** [comment]
>Tested this with my wallbox. Seems to work quite well, but I noticed there's a typo in the action names: "simplevse" should be "simpleevse".

Thank you for your feedback! Typo is fixed.

> Maybe #1779 is relevant here as well?

It might be, but unfortunately it is not integrated either. I have also some tweaked the modbus implementation a bit, e.g. repeats requests because SimpleEVSE does not respond sometimes, force a quicker update if a change was made.

Also the minimal web interface for changing the parameter seems to be worthwhile a separate component.

**Review by jesserockz — CHANGES_REQUESTED** [review]
You are basically reimplementing the modbus protocol instead of using/adding new features to the existing one in ESPHome, which just adds more maintenance down the road.

Can we make this PR a bit smaller and only implement the actual sensors, switches and actions and put the webserver stuff into a new PR that can be reviewed on its own? I am also not sure what the web_server does exactly, but will leave that review for a new PR.

**Comment by stegm** [comment]
> You are basically reimplementing the modbus protocol instead of using/adding new features to the existing one in ESPHome, which just adds more maintenance down the road.

Yes, I do, because at the time I started with this integration the existing modbus protocol was missing almost everything I needed (write access, concurrent transactions, different transactions, error handling). I could have chosen to to change the existing but this will lead to changes in existing integrations which uses the old modbus implementation.

AFAIK there is now a new modbus implementation, which might be usable. maybe even there I have to change somehting e.g. the auto-repeat of failed transactions.

> Can we make this PR a bit smaller and only implement the actual sensors, switches and actions and put the webserver stuff into a new PR that can be reviewed on its own? I am also not sure what the web_server does exactly, but will leave that review for a new PR.

Yes, sure, I can, but first I had some questions because reworking it is a lot of work, especially the testing. 

- Is there the chance to integrated it after the rework? I mean I actually don't know if anyone except me and may be @torfbolt is interested in it?
- Is it ok, to change the existing modbus implementation if I had to?
- Is there a chance to integrated the web server stuff too? It is used to access the configuration register of the device.

Otherwise, we could close the PR and I can provide the integration as [exterrnal component](https://esphome.io/components/external_components.html) via my github repository.

**Comment by jesserockz** [comment]
Yeah I realise there have been changes which came with the modbus_controller after this PR was made, hopefully you can utilise those changes and/or make some more improvements.

> - Is there the chance to integrated it after the rework? I mean I actually don't know if anyone except me and may be @torfbolt is interested in it?

Yes, if only I could legally use the parts to build my own charger here then I would =)

> - Is it ok, to change the existing modbus implementation if I had to?

Depends on the changes, as long as it didn't break the current components using it.

> - Is there a chance to integrated the web server stuff too? It is used to access the configuration register of the device.

Yes, depending on what you are actually changing, a minor upgrade to the built in webserver to allow changing `number` entities would also mean you could use the standard web_server and expose `number` entities that can read and update those registers. Then you can update them from the webserver or Home Assistant.

**Comment by stegm** [comment]
Ok, so I will take a look what is need to change the modbus implementation and strip down the PR.

**Comment by stegm** [comment]
I have made first attempts to use the new modbus implementation. It seems that it provides anything I need to integrated the SimpleEVSE with it, but I'm not yet finished.

Just for record:
* I provide my config here: https://github.com/stegm/esphome-simpleevse-config
* To optimize read requests, I created this PR https://github.com/esphome/esphome/pull/2981

@jesserockz Is there a place where config files for certain devices like the SimpleEVSE can be documented and published on esphome.io?

**Comment by jesserockz** [comment]
@stegm Only really https://esphome-devices.com ?

**Pull request closed without merging**
