### PR TITLE
Add option to use MQTT abbreviations

### PR DESCRIPTION
**Pull request by paulmonigatti**
# What does this implement/fix? 

Adds the option to enable/disable abbreviations for [MQTT Discovery](https://www.home-assistant.io/docs/mqtt/discovery/). Using abbreviations frees up a small amount of flash, memory usage during discovery, and reduces network traffic ever so slightly.

MQTT abbreviations are enabled by default; this _should_ work just fine with Home Assistant since the abbreviations in this PR have been adapted directly from [HA source](https://github.com/home-assistant/core/blob/11cb04822e3dd3e1750234c8aa9df10fc3a28626/homeassistant/components/mqtt/abbreviations.py), however this will be a breaking change if used with other software that uses MQTT discovery but doesn't recognize these abbreviations.

Making this a non-breaking change is not as simple as disabling abbreviations by default, because the MQTT Climate component was already using abbreviations while other components were not.

If this PR is approved, I'll go ahead and update docs/tests.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
Happy with the changes, just cannot decide on default behaviour as both decisions make a change to existing behaviour

**Comment by oxan** [comment]
The MQTT discovery stuff is fairly HA-specific anyway, so I don't think we need to worry too much about other software using it, so I would just default to enabling usage of abbreviations.

**Comment by oxan** [comment]
One thing though, maybe it's better to use constexpr variables instead. That gives us namespacing and type checking, and from a quick look it compiles to the same.

So e.g.
```cpp
constexpr const char* const ACTION_TOPIC = "action_topic";
```

**Comment by paulmonigatti** [comment]
Awesome, thanks! I've changed the defines to `constexpr`, and updated the docs at esphome/esphome-docs#1582

**Review by oxan — APPROVED** [review]

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Only added breaking-change label so I know to mention it in next release just in case people are using the topics directly

**Pull request merged**
