### PR TITLE
BLE loop use

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix? 

Replace the use of semaphores and blocking in ble setup with state machines so that the loop continues normally.

Also moves the ble events to use a queue and they get processed on the main loop.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by buxtronix** [comment]
This looks good, the state based flow should be much more reliable.

A couple of comments...I dont have review perms so will mention here...

A copy of the event data for ESP_GATTS_WRITE_EVT will need to be made in queue.h otherwise the ble stack will likely change/corrupt the data pointer mem before the queue gets serviced. Similar to https://github.com/esphome/esphome/pull/1818

Also, is a separate task needed for setup in ble.cpp? Current BLE code uses the current task so I'm not sure if the added task gives much benefit without adding another potential failure point?

**Comment by jesserockz** [comment]
Thanks @buxtronix 

Indeed the task was not needed anymore and I have removed that now.
Thanks for that tip on the data too.

**Comment by buxtronix** [comment]
Looks Good To Me

**Comment by kordys** [comment]
Hi guys, could this change be somehow connected with an issue with v1.19 and my esp32 where I use the esp32_ble_tracker together with sensors based on xiaomi_lywsd03mmc platform. When I have this configuration the OTA finishes successfully, is uploaded to the ESP32, but the log is not retrieved and a warning message is displayed - initial connection failed, ESP might not be connected to the wifi. The strange thing is that if I remove or comment out the BLE tracker and sensors, OTA succeeds and the log is retrieved. So I m assuming there might be something wrong with the BLE tracker prevent the ESP from booting correctly? Thanks for any feedback.

**Comment by jesserockz** [comment]
This PR and component is completely separate from the ble tracker component. 

It seems there are a few people noticing issues with the tracker after this release so it's something we will be looking into.

**Pull request merged**
