### PR TITLE
ESP8266 change recommended framework version to 2.7.2

### PR DESCRIPTION
**Pull request by OttoWinter**
## Description:

I checked 2.7.2 on my ESP8266 devices and it worked well for some time now. Today I looked at Tasmota and ESPEasy and they also switched to 2.7.2, so it's safe to assume this framework version will perform well on most devices.

Additionally, I saw those other projects use a flag to tell platformio to use a different LwIP static library with some features disabled (none of which we use)

TODO:

 - [x] Check if sntp works for ESP8266 with 3 servers. I'm not sure if the build flag is used for compiling the static lib.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** https://github.com/esphome/esphome-docs/pull/714

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
Remembered that image size was an issue with prior framework versions and did a quick test (same sketch, different `arduino_verison`):

```
# 2.7.2:
RAM:   [=====     ]  49.9% (used 40904 bytes from 81920 bytes)
Flash: [====      ]  38.2% (used 399448 bytes from 1044464 bytes)

# 2.6.3
RAM:   [=====     ]  49.9% (used 40876 bytes from 81920 bytes)
Flash: [====      ]  38.1% (used 398176 bytes from 1044464 bytes)

# 2.5.2
RAM:   [=====     ]  49.5% (used 40524 bytes from 81920 bytes)
Flash: [====      ]  38.1% (used 397900 bytes from 1044464 bytes)

# 2.5.2 without PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH_LOW_FLASH
RAM:   [=====     ]  49.5% (used 40580 bytes from 81920 bytes)
Flash: [====      ]  38.7% (used 404228 bytes from 1044464 bytes)
```

so 2.7.2 doesn't increase flash use by a major amount. In fact, the new `PIO_FRAMEWORK_ARDUINO_LWIP2_HIGHER_BANDWIDTH_LOW_FLASH` flag even shaves off ~6kb.

**Comment by Misiu** [comment]
@OttoWinter 2.7.3 was released couple of hours ago - https://github.com/esp8266/Arduino/releases/tag/2.7.3
it has a fix for OTA.

**Comment by OttoWinter** [comment]
Hi @Misiu,

Thanks for the update. I had to wait a bit before we could apply 2.7.3, because we depend on platformio creating a matching release here: https://github.com/platformio/platform-espressif8266/releases/tag/v2.6.1

I created a PR here to bump the version: https://github.com/esphome/esphome/pull/1229

However, the OTA fix described in the changelog does not impact ESPHome from what I understand. It's mainly for OTAs where the new binary is stored in a compressed format (which ESPHome does not do yet)

**Comment by Misiu** [comment]
I've just found the [feature request](https://github.com/esphome/feature-requests/issues/819) that you created.
P.S. I think that not only I'm happy seeing again your activity in this repo 🎉

**Pull request merged**
