### PR TITLE
Exposing coordinates from touchscreen binary sensor

### PR DESCRIPTION
**Pull request by gpambrozio**
I’ll need this for a project where I use these coordinates to draw elements on the screen and not have to repeat numbers everywhere

# What does this implement/fix?

Exposes coordinates from touchscreen binary sensor

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

Not a full example but this is why I need this for.

Say I have this in my config.yaml:

```
image:
  - file: "images/fanblades.png"
    id: fanblades
    type: TRANSPARENT_BINARY

binary_sensor:
  - platform: touchscreen
    id: button_fan_main
    name: Fan Button
    internal: true
    x_min: 0
    x_max: 100
    y_min: 50
    y_max: 150
    on_click:
        ...
```

I then include a .h file with this code:

```
#include "esphome.h"

void drawButton(
  DisplayBuffer *it,
  TouchscreenBinarySensor *sensor,
  Image *image,
  int16_t x_offset = 0,
  int16_t y_offset = 0
) {
  int cx = sensor->get_x_min() + x_offset + (sensor->get_width() - image->get_width()) / 2;
  int cy = sensor->get_y_min() + y_offset + (sensor->get_height() - image->get_height()) / 2;
  it->image(cx, cy, image);
}
```

Then in my display's `lambda` I can do this:
```
    lambda: |-
      drawButton(&it, id(button_fan_main), id(fanblades));
``` 

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nielsnl68** [comment]
hi @gpambrozio  did you saw my work on the switchplate component? would you have time to check it out and see of it will work for you?

**Comment by gpambrozio** [comment]
@nielsnl68 yes, I did and was trying it out a bit but it looks like it still can't do anything other than changing pages when you touch a button. Or maybe I don't understand how to configure it yet. But looks like the automation source is still empty so.

And for my use this change makes it way easier to use. But I look forward to be able to use switchplate in the future

**Comment by nielsnl68** [comment]
> @nielsnl68 yes, I did and was trying it out a bit but it looks like it still can't do anything other than changing pages when you touch a button. Or maybe I don't understand how to configure it yet. But looks like the automation source is still empty so.

Oww good that you point this out. I found out that i forget to add to the documentation. Yes, there is a way already to "talk" between the switchplate and ESPHome and Home-Assistant using the switch's `platform: switchplate` .

```yaml
switch:
  - platform: switchplate
    widget_id: rgbLamp
    name:  RGB lightball
```

**Review by jesserockz — APPROVED** [review]
LGTM

**Pull request merged**
