### PR TITLE
add xiaomi BLE Thermometer lywsd02 model support

### PR DESCRIPTION
**Pull request by junnikokuki**
## Description:
add xiaomi BLE Thermometer lywsd02 model support

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [OK] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — APPROVED** [review]
LGTM 👍

**Comment by OttoWinter** [comment]
Good to merge when lint checks pass and docs are updated

**Comment by G1K** [comment]
Thank! it works. checked on my watch LYWSD02 

This resolves https://github.com/esphome/feature-requests/issues/251

**Comment by 4everfun** [comment]
@G1K You think you can fix this error? Have been waiting patiently for the past 15 days and would help if I could, but I, unfortunately, lack the experience. :)

**Comment by G1K** [comment]
@4everfun 

I'm not the author of this pull request. There was only an extra space at the end of the line.  If the author will correct and accept my PR https://github.com/junnikokuki/esphome/pull/2 . Or @OttoWinter  when you merge the corrected one space?

**Comment by G1K** [comment]
@OttoWinter pls merge. 
error in tests, skips in all neighboring pullrequests. and does not apply to the code of this

**Comment by sermayoral** [comment]
Hi! I think the pr doesn't pass de CI.

Can anyone correct this? We would like to have this device available in ESPHome.

Thanks you guys :-)

**Comment by wolfg1969** [comment]
@junnikokuki PR #694 had fixed the CI build issue ([env_default renamed to default_envs in platformio.ini](https://docs.platformio.org/en/latest/migration.html#what-is-changed-or-removed)). Could you update this PR by creating your fork then commit your changes again?

**Comment by wolfg1969** [comment]
@junnikokuki Thanks.
@OttoWinter Pls merge.

**Comment by 4everfun** [comment]
@wolfg1969 It seems like @OttoWinter is on holiday seeing @brandond his response on PR #694

**Comment by wolfg1969** [comment]
@brandond Could you merge this PR?

**Review by OttoWinter — APPROVED** [review]

**Comment by sermayoral** [comment]
Hi everybody.

As i read in the documentation, this device is already supported 😃. Thanks.

However, i miss the battery level information. Does not the device publish this information??

**Pull request merged**
