### PR TITLE
Port wifi_component_esp32_arduino from tcpip_adapter to esp_netif

### PR DESCRIPTION
**Pull request by paravoid**
# What does this implement/fix?

wifi_component_esp32_arduino is using the tcpip_adapter API from ESP-IDF. tcpip_adapter, however, was deprecated in ESP-IDF 4.1, and replaced with stubs that use the netif API internally. It was finally removed in ESP-IDF 5.1, and is no longer available. We already depend on ESP-IDF >= 4.1.

Replace all occurences of the tcpip_adapter API with the netif API directly, borrowing code from the ESP-IDF WiFi component. tcpip_adapter is effectively a wrapper over this code, so there are limited to no functional changes.

This removes a dependency on a deprecated API, aligns the implementation further with the ESP-IDF WiFi component, making some of the functions there identical, allowing for future code sharing.

Note that this also resolves at least one more minor bug: the ability to use IPv6 ULA addresses, something that was just not possible before due to limitations of the tcpip_adapter API.

While at it, also try to bring some of the wifi_component_esp32_arduino changes to ESP-IDF, to reduce the delta between the two (now very similar) codebases.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:
```yaml
esphome:
  name: testesp

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

network:
    enable_ipv6: true
    min_ipv6_addr_count: 2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "fallback hotspot"
    password: !secret wifi_ap_password
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - ~~Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).~~

### CODE REVIEW

**Comment by jesserockz** [comment]
@paravoid I have pushed a commit that shuffles around some of the functions in the Arduino code to better match the idf file even more. I will be testing it tomorrow as I only just finished after leaving my desk and didnt get the chance yet.

Let me know if you test it and do/dont have issues.

Jesse

**Comment by paravoid** [comment]
@jesserockz thanks Jesse! Your change makes sense to me. I was contemplating where to stop in aligning those two files with each other :)

I'll have a closer look & test, but it's unlikely I'll get to it by tomorrow. I'd say don't wait for me, and merge as soon as you've tested this yourself. Thanks again!

**Comment by jesserockz** [comment]
> I was contemplating where to stop in aligning those two files with each other :)

I thought since bigger changes were being made, it made sense to do it now.

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Working for me on a couple of devices

**Pull request merged**
