### PR TITLE
Version bump for ESP32 IDF and Arduino

### PR DESCRIPTION
**Pull request by HeMan**
# What does this implement/fix?

Version bump for Platformio, IDF and Arduino for ESP32
Arduino/idf platform changelog:
- [5.4.0](https://github.com/platformio/platform-espressif32/releases/tag/v5.4.0)

Idf framework changelog:
- [4.4.5](https://github.com/espressif/esp-idf/releases/tag/v4.4.5)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
Please include a link to a changelog/release/compare when bumping third party versions in PRs

**Comment by bdraco** [comment]
Looks like there are a few nice bluetooth fixes.

Testing this now...

**Comment by bdraco** [comment]
Usable memory seems a bit better. Everything appears to be working

Screenshot 2023-07-04 at 12 34 36 PM

**Comment by bdraco** [comment]
~3.5-6.5KB less ram used for IDF which helps the proxies a bit

**Comment by bdraco** [comment]
for bluetooth proxies (and others) be tested manually with

```yaml
esp32:
  board: [YOUR BOARD HERE]
  framework:
    type: esp-idf
    version: 4.4.5
    platform_version: 5.4.0
```

**Comment by bdraco** [comment]
running on all production for a few days now. All good

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Tested on a few of my devices

**Comment by bdraco** [comment]
been doing a lot of testing with the wifi based proxies

with the newest esp-idf, all the devices that I couldn't get a connection to establish with that worked fine on ethernet now establish and work fine with the wifi ones 

I have 6 homekit devices paired and its now fast enough to switch between them all to service them all

I'll update the repair issue in HA to recommend updating to ESPHome 2023.8.x when it ships

**Pull request merged**
