### PR TITLE
Add WiFi-Info Networks text sensor

### PR DESCRIPTION
**Pull request by micronen**
# What does this implement/fix? 

Adds a text sensor which reports the WiFi scan results.
 
## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuraiton files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [ ] ESP32
- [X] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:
```yaml
# Example config.yaml snippet
text_sensor:
  - platform: wifi_info
    networks:
      name: $nice_name Networks
```

# Explain your changes

The sensors allows mapping of WiFi reception for multiple WiFi networks. It helps identify network problems and understand the network topology. For example an ESPHome node might use a network with low RSSI under certain conditions. This sensors helps mapping of WiFi reception by including information on all the WiFi networks found in the scan, and not only the selected network.

The sensor text string is in a compact format (and not JSON for example) because home-assistant limits text sensors to 255 (256?) chars. The sensors will limit the text to 250 chars, and thus might omit some of the networks for situations with many long named networks.

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).
          PR esphome/esphome-docs/#1040

### CODE REVIEW

**Comment by glmnet** [comment]
How are you using this?

I wonder if there is a way to format it on hass or something, may be that can be added to docs

**Comment by glmnet** [comment]
it'd be nice to add total networks seen at the beginning?

**Comment by micronen** [comment]
I have a map that shows all the Wi-Fi nerworks coverage in my home. Not only the ones selected currently, but all the options available to the nodes.
It allowed Wi-Fi improvements, and understanding of weird Wi-Fi selection by esphome.

I wanted it to be json, but hass have a 255 chars limit on text sensors. Maybe it can be done better with an array of sensors, but I don't see a nice way to do it, without generating a lot of sensors.
Maybe if esphome could report sensor properties the 50 or so sensors could be grouped to one sensor with many properties.

**Comment by micronen** [comment]
I want to combine it with background scanning, but got into a lot of problems with weird LwIP behavior and heap running out.

**Comment by jesserockz** [comment]
A nicer way could be to add a trigger to the wifi component (`on_wifi_scan_complete` or similar) which allows a user to do "whatever" they want with the results, you could set a template text sensor in your own format, or send each wifi network found as a separate HA `event`? Once it becomes an automation, the ideas are endless and not limited by core code changes.

**Comment by glmnet** [comment]
> A nicer way could be to add a trigger to the wifi component (`on_wifi_scan_complete` or similar) which allows a user to do "whatever" they want with the results, you could set a template text sensor in your own format, or send each wifi network found as a separate HA `event`? Once it becomes an automation, the ideas are endless and not limited by core code changes.

this, + a sample on docs on how to use get's you running in no time.

**Comment by micronen** [comment]
> > A nicer way could be to add a trigger to the wifi component (`on_wifi_scan_complete` or similar) which allows a user to do "whatever" they want with the results, you could set a template text sensor in your own format, or send each wifi network found as a separate HA `event`? Once it becomes an automation, the ideas are endless and not limited by core code changes.
> 
> this, + a sample on docs on how to use get's you running in no time.

I'll look into how to implement this. Can you point me to other component which is a good working example?

**Comment by glmnet** [comment]
This means the scan result will be given in a variable for the user to use it inside a lambda action. 

An example: https://esphome.io/components/sim800l.html#on-sms-received-trigger

**Comment by micronen** [comment]
I prefer the current implementation. while adding a WiFi scan complete event is a nice idea, I don't think it should be part of this PR. The idea is to send a text message with the info using a simple sensor. To do this using lambda, the user needs to define another text sensor, and use a fairly complex lambda to tie it together. 
And I think it misses the point of having a simple text sensor with the scan information,

**Pull request closed without merging**
