### PR TITLE
Allow using a git source for a package

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix? 

This allows for device makers/manufacturers to publish a yaml file configuration for a device and the end-user only has to have a minimal configuration to be able to use the default config (example below).

By using substitutions in the source yaml, the end yaml can override them for example changing the device name and friendly names of sensors etc.

The original `!include` method for packages still works as expected. The new code looks for a `CONF_URL` in the `dict` and goes from there.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1431

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
packages:
  athom:
    url: https://github.com/jesserockz/athom-configs
    files: [athom-relay-board-2.yaml]
  # OR
  athom: github://jesserockz/athom-configs/athom-relay-board-2.yaml

substitutions:
  device_name: relay
  friendly_name: Relay
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by mmakaay** [comment]
Dude, you read my mind! I was planning to provide a few full-fledged configurations for the Bedside Lamp 2 and yesterday I was thinking that it would be really nice if I could provide these directly from GitHub :-D
I will get cracking and test this out. Thanks.

**Comment by mmakaay** [comment]
I gave it a try. I found that the URL should not contain a subdirectory name within a repo, as seems to be the case in the example config. But with a little bit of fiddling, I got the following to work:

```yaml
packages:
  core:
    url: https://github.com/mmakaay/esphome-xiaomi_bslamp2
    ref: package-git
    file: packages/core.yaml
    refresh: always
  ota_feedback:
    url: https://github.com/mmakaay/esphome-xiaomi_bslamp2
    ref: package-git
    file: packages/ota_feedback.yaml
    refresh: always
  preset.activate:
    url: https://github.com/mmakaay/esphome-xiaomi_bslamp2
    ref: package-git
    file: packages/service_preset.activate.yaml
    refresh: always
  behavior_default:
    url: https://github.com/mmakaay/esphome-xiaomi_bslamp2
    ref: package-git
    file: packages/behavior_default.yaml
    refresh: always
```
Really nice to be able to split up features into separate config files this way, pulling the actual configs from GitHub.
Using this piece of config, I could compile the firmware. After uploading the firmware, the device behaved like expected.

One thing that I didn't understand is the use of keys within the `packages` dictionary. Am I right that the contents of `packages` could have been a list instead of a dictionary? I didn't look in the code to see if the key was used somewhere, so I might have missed the obvious here.

**Comment by jesserockz** [comment]
`packages` were already key value and not a list so I didn't want to change that. 
The keys really do not matter and are removed from the merged config anyway.

**Comment by mmakaay** [comment]
Ah, clear. So a thing that can be solved in the documentation, by marking it as an "identifier for your own use".
Or a backward compatible handling, where the packages can be both list- and dict-based?

Looking at the test code that I used: would it be an idea to allow passing in a list of files as well, for a single repo? I have a lot of repeated repo definition code in my example YAML, because all included config files come from the same repo. Would be nice if I only had to define the repo meta data once here.

**Comment by jesserockz** [comment]
@mmakaay I have pushed another change to allow multiple files from a single repo. I have updated the example in the PR description

**Comment by mmakaay** [comment]
Great! I will take the new code for a spin around the block.

**Comment by mmakaay** [comment]
That cleaned up my packages config a lot, thanks.

```yaml
packages:
  bslamp2:
    url: https://github.com/mmakaay/esphome-xiaomi_bslamp2
    ref: package-git
    files:
      - packages/core.yaml
      - packages/behavior_default.yaml
      - packages/ota_feedback.yaml
      - packages/service_preset.activate.yaml
    refresh: always
    ```

**Pull request merged**
