### PR TITLE
[audio_dac] [aic3204] Add new component + platform

### PR DESCRIPTION
**Pull request by kbx81**
# What does this implement/fix?

SSIA

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4286

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
audio_dac:
  - platform: aic3204
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nielsnl68** [comment]
@kbx81, is it possible to use the same code for other audio codec's from texas instruments like the AIC3100 etc.

**Comment by kbx81** [comment]
> @kbx81, is it possible to use the same code for other audio codec's from texas instruments like the AIC3100 etc.

@nielsnl68 I'm not sure -- I only have experience with this specific part.

**Review by jesserockz — APPROVED** [review]

**Comment by nagyrobi** [comment]
Wow! This chip supports multiple analog audio inputs too, and has a built-in audio mixer! (according to [spec sheet](https://www.ti.com/lit/ds/symlink/tlv320aic3204.pdf))

Could be a good all-in-one solution for https://github.com/esphome/feature-requests/issues/1750 and https://github.com/esphome/feature-requests/issues/1751 (use case described [here](https://forum.raspiaudio.com/t/suggestion-for-espmuse-multiple-analog-inputs/401/7)). A board design needed...

@kbx81 what device are you using this with?

**Comment by jesserockz** [comment]
@nagyrobi https://github.com/esphome/home-assistant-voice-pe/blob/dev/home-assistant-voice.yaml#L1338-L1339

**Pull request merged**
