### PR TITLE
tt21100: restore init read

### PR DESCRIPTION
**Pull request by nielsnl68**
# What does this implement/fix?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by clydebarrow — APPROVED** [review]

**Comment by kroimon** [comment]
Just for my understanding: this got lost in #4596?

**Comment by clydebarrow** [comment]
> Just for my understanding: this got lost in #4596?

Yes.

**Comment by clydebarrow** [comment]
https://github.com/esphome/issues/issues/5274 refers.

**Comment by kroimon** [comment]
Also, before #4596, there was a comment saying "Origin is top right, so mirror X by default". Do we also want to restore this default mirroring?

**Comment by clydebarrow** [comment]
> Do we also want to restore this default mirroring?

IMHO no, since that's likely to be hardware-specific, and can be handled by the `transform:` option in yaml.

**Comment by kroimon** [comment]
> IMHO no, since that's likely to be hardware-specific, and can be handled by the `transform:` option in yaml.

That's true, but should probably be part of the default configuration for this component, as the only hardware I know of that uses this touchscreen (ESP32-S3-BOX) has it mirrored and existing configurations will otherwise still be be broken.

**Pull request merged**
