### PR TITLE
Fix for OTA mode not activating in safe_mode when OTA section has an on_xxxx action 

### LINKED ISSUE #5976: Can non longer do an OTA update with ESP32 in safe_mode after ESPHOME update 2024.6.0 when using on_begin: action under ota:
### The problem

Latest changes related to safe_mode and OTA configuration seems to have broken the ability to do an OTA update if the device goes into safe_mode (either manually via a switch or via 10 failed boot attempts) when there is an on_begin action specified for the ota:  I keep getting connection refused.  When the on_begin section is on, the esphome.ota component does not load (no log dump display) during transition to safe_mode. The esphome.ota does show up fine and ota works when the offending on_begin is removed.  

My safe mode and ota config options:
```
ota:
   password: !secret ota_password
   platform: esphome
   on_begin:
          switch.turn_off: connection_status_switch 
          
safe_mode:
```

### Which version of ESPHome has the issue?

2024.6.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Core: 2024.6.4

### What platform are you using?

ESP32

### Board

ESP32-c3 and esp32-d1 mini

### Component causing the issue

OTA and safe_mode

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Dilbert66**
# What does this implement/fix?

Latest changes related to safe_mode and OTA configuration seems to have broken the ability to do an OTA update if the device goes into safe_mode (either manually via a switch or via 10 failed boot attempts) when there is an on_begin action specified for the ota: section. I keep getting connection refused. When the on_begin section is on, the esphome.ota component does not load (no log dump display) during transition to safe_mode. The esphome.ota does show up fine and ota works when the offending on_begin is removed. 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/esphome/issues/issues/5976

## Test Environment

- [x ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
ota:
   password: !secret ota_password
   platform: esphome
   on_begin:
          switch.turn_off: connection_status_switch 
          
safe_mode:

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — COMMENTED** [review]
I have pushed some further changes to enhance this a bit more.
All of the triggers should not load even when in safe mode.

~~I have done a compile test only to verify the order of things in main.cpp~~
Tested and working on device

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
```yaml
esphome:
  name: safe-mode-test

esp32:
  board: esp32dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:
  - platform: esphome
    on_begin:
      - logger.log: "Beginning OTA"

```

<details>
<summary>Safe mode OTA</summary>

```
[09:26:47][I][logger:171]: Log initialized
[09:26:47][C][safe_mode:079]: There have been 10 suspected unsuccessful boot attempts
[09:26:47][D][esp32.preferences:114]: Saving 1 preferences to flash...
[09:26:47][D][esp32.preferences:143]: Saving 1 preferences to flash: 0 cached, 1 written, 0 failed
[09:26:47][E][safe_mode:086]: Boot loop detected. Proceeding to safe mode
[09:26:47][E][component:164]: Component safe_mode set Error flag: unspecified
[09:26:48][I][app:029]: Running through setup()...
[09:26:48][C][wifi:048]: Setting up WiFi...
[09:26:48][C][wifi:061]: Starting WiFi...
...
[09:26:48][D][wifi:482]: Starting scan...
[09:26:48][W][component:157]: Component wifi set Warning flag: scanning for networks
[09:26:54][D][wifi:497]: Found networks:
...
[09:26:56][I][wifi:617]: WiFi Connected!
...
[09:26:56][I][app:062]: setup() finished successfully!
[09:26:56][W][safe_mode:099]: SAFE MODE IS ACTIVE
[09:26:56][W][component:170]: Component wifi cleared Warning flag
[09:26:56][I][app:100]: ESPHome version 2024.12.0-dev compiled on Nov 22 2024, 09:26:05
[09:26:56][C][wifi:600]: WiFi:
...
[09:26:56][C][logger:185]: Logger:
[09:26:56][C][logger:186]:   Level: DEBUG
[09:26:56][C][logger:188]:   Log Baud Rate: 115200
[09:26:56][C][logger:189]:   Hardware UART: UART0
[09:26:56][C][mdns:116]: mDNS:
[09:26:56][C][mdns:117]:   Hostname: safe-mode-test
[09:26:56][C][esphome.ota:073]: Over-The-Air updates:
[09:26:56][C][esphome.ota:074]:   Address: safe-mode-test.local:3232
[09:26:56][C][esphome.ota:075]:   Version: 2
[09:26:56][C][safe_mode:018]: Safe Mode:
[09:26:56][C][safe_mode:020]:   Boot considered successful after 60 seconds
[09:26:56][C][safe_mode:021]:   Invoke after 10 boot attempts
[09:26:56][C][safe_mode:023]:   Remain in safe mode for 300 seconds
[09:26:56][W][safe_mode:031]: SAFE MODE IS ACTIVE
[09:26:56][D][esphome.ota:117]: Starting update from 10.1.1.55...
[09:26:56][W][component:157]: Component esphome.ota set Warning flag: unspecified
[09:26:57][D][esphome.ota:293]: Progress: 0.1%
[09:26:58][D][esphome.ota:293]: Progress: 7.3%
[09:26:59][D][esphome.ota:293]: Progress: 14.3%
[09:27:00][D][esphome.ota:293]: Progress: 22.9%
[09:27:01][D][esphome.ota:293]: Progress: 33.8%
[09:27:02][D][esphome.ota:293]: Progress: 42.1%
[09:27:03][D][esphome.ota:293]: Progress: 47.7%
[09:27:04][D][esphome.ota:293]: Progress: 52.5%
[09:27:05][D][esphome.ota:293]: Progress: 60.8%
[09:27:06][D][esphome.ota:293]: Progress: 68.4%
[09:27:07][D][esphome.ota:293]: Progress: 75.3%
[09:27:08][D][esphome.ota:293]: Progress: 81.0%
[09:27:09][D][esphome.ota:293]: Progress: 87.0%
[09:27:10][D][esphome.ota:293]: Progress: 94.4%
[09:27:11][D][esphome.ota:293]: Progress: 96.2%
[09:27:12][I][esphome.ota:326]: Update complete
[09:27:12][W][component:170]: Component esphome.ota cleared Warning flag
[09:27:12][I][app:132]: Rebooting safely...
```

</details>


<details>
<summary>Normal OTA</summary>

```
[09:26:10][D][esphome.ota:117]: Starting update from 10.1.1.55...
[09:26:10][W][component:157]: Component esphome.ota set Warning flag: unspecified
[09:26:10][D][main:122]: Beginning OTA << --- Not logged in safe mode as expected
[09:26:10][D][esphome.ota:293]: Progress: 0.1%
[09:26:11][D][esphome.ota:293]: Progress: 8.9%
[09:26:12][D][esphome.ota:293]: Progress: 19.4%
[09:26:13][D][esphome.ota:293]: Progress: 25.4%
[09:26:14][D][esphome.ota:293]: Progress: 32.3%
[09:26:15][D][esphome.ota:293]: Progress: 36.4%
[09:26:16][D][esphome.ota:293]: Progress: 41.6%
[09:26:17][D][esphome.ota:293]: Progress: 45.6%
[09:26:19][D][esphome.ota:293]: Progress: 52.8%
[09:26:20][D][esphome.ota:293]: Progress: 62.3%
[09:26:21][D][esphome.ota:293]: Progress: 70.6%
[09:26:22][D][esphome.ota:293]: Progress: 77.2%
[09:26:23][D][esphome.ota:293]: Progress: 83.9%
[09:26:24][D][esphome.ota:293]: Progress: 91.8%
[09:26:25][I][esphome.ota:326]: Update complete
[09:26:25][W][component:170]: Component esphome.ota cleared Warning flag
[09:26:25][I][app:132]: Rebooting safely...
```

</details>

**Comment by yokokito** [comment]
Oh my god!  This could explain what I´m suffering with my  NSPANEL reported in:
https://github.com/esphome/issues/issues/6206#issuecomment-2319456739
I have OTA actions (to display de OTA status in the NSPANEL)
The only solution so far was to downgrade ESPHOME to the may's version.
Thanks so much!

**Comment by Dilbert66** [comment]
> Oh my god! This could explain what I´m suffering with my NSPANEL reported in: [esphome/issues#6206 (comment)](https://github.com/esphome/issues/issues/6206#issuecomment-2319456739) I have OTA actions (to display de OTA status in the NSPANEL) The only solution so far was to downgrade ESPHOME to the may's version. Thanks so much!

Don't forget to close your open issue if this update fixes it:)👍

**Pull request merged**
