### PR TITLE
display: move `Image`, `Font` and `Animation` code into components

### PR DESCRIPTION
**Pull request by ayufan**
# What does this implement/fix?

This includes changes from https://github.com/esphome/esphome/pull/4956.

- display: move `Image` to `components/image`
- display: move `Animation` to `components/animation`, make it depend on `Image`
- display: move `Font` to `components/font`
- graph: fix to depend on `Font`

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected): changes source code location
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32S3
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

**Comment by guillempages** [comment]
@ayufan as mentioned elsewhere, I like this PR.

I have submitted a PR (#4959) to the animation component, that adds (yaml-) actions to control the current frame.
Jesse requested some minor changes; which I have already done; you might want to rebase on top of that, to make sure that the changes are there.
At least you should be aware that the changes are open ;-)

**Comment by ayufan** [comment]
This is nice @guillempages :)

**Comment by ayufan** [comment]
@guillempages It does not matter if I rebase now or not, I will still have to rebase it after it is merged :( So, lets maybe ask @jesserockz to merge yours PR first.

**Review by kbx81 — DISMISSED** [review]

**Comment by kbx81** [comment]
Should be good to rebase now that #4959 is merged -- otherwise, LGTM 😄

**Comment by ayufan** [comment]
@kbx81 Rebased!

**Review by kbx81 — APPROVED** [review]

**Review by kbx81 — APPROVED** [review]

**Pull request merged**
