### PR TITLE
Add Lilygo t5 4.7 Touchscreen

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix? 

Add Lilygo t5 4.7 Touchscreen

## TODO

- [ ] Apply rotation when display rotated

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1886

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by kaweksl** [comment]
Tested on Lilygo t5-47, with touchscreen that can be bought with it and touch is detected, coordinates correspond to screen resolution.

binary sensor touch key state is switching to ON when touched in specified area but in order to switch it off you must press outside this area (or move out of it) , i have experted to switch off on release, and not be able to turn on/off while moving into/outside area . Maybe this is how it suppose to be. Either way its is usable

part of my config
```
i2c:
  sda: 15
  scl: 14
  scan: True

binary_sensor:
  - platform: touchscreen
    touchscreen_id: lilygo_touchscreen
    id: touch_key1
    x_min: 0
    x_max: 100
    y_min: 0
    y_max: 100
    on_press:
      - logger.log: "Touched"

touchscreen:
  - platform: lilygo_t5_47
    id: lilygo_touchscreen
    interrupt_pin: GPIO13
    display: mydisplay
    on_touch:
      - logger.log:
          format: Touch at (%d, %d)
          args: ["touch.x", "touch.y"]
```

**Review by oxan — APPROVED** [review]
Lilygo-specific parts LGTM.

**Comment by jesserockz** [comment]
Thanks for testing @kaweksl!

For the touches not releasing, Following from the original lilygo code, it only sends touch events, so I think I will just set them to auto timeout after 100ms or so to simulate a touch and release.

Still waiting for my touch overlays to arrive, can't wait.

**Comment by Plawasan** [comment]
Tested on my end as well (using code above), works with a couple issues:

- at default orientation y values are flipped, i.e. bottom left corner is 0,0, top right 960,540 while the draw functions start with 0,0 in top left and go to 960,540 in bottom right
- need to test more but sometimes touches are correctly registered but the touchscreen area is not triggered - seems to me like this happens after a period of inactivity, might be the first touch after the display is refreshed but it's pretty rare EDIT: I think this happens right before the display is periodically refreshed
- I can't get it to work when on battery, here's what the log looks likes:

[D][main:671]: Touch at (171, 341)
[D][binary_sensor:036]: 'touch_area1': Sending state OFF

USB power disconnected, error shows up on touch event:

[E][lilygo_t5_47.touchscreen:060]: Failed to communicate!
[E][lilygo_t5_47.touchscreen:060]: Failed to communicate!
[E][lilygo_t5_47.touchscreen:060]: Failed to communicate!
[E][lilygo_t5_47.touchscreen:060]: Failed to communicate!

USB reconnected:

[D][main:671]: Touch at (135, 335)
[D][binary_sensor:036]: 'touch_area1': Sending state ON
[D][main:2910]: Area 1
[D][main:671]: Touch at (135, 335)

Not sure if that's something you can influence however the display won't even boot with the touchscreen connected unless it's connected to USB power, I'm not sure how I could get to the logs though as the moment I connect the serial port the problem goes away...

**Pull request merged**
