### PR TITLE
Add Tuya text_sensor component

### LINKED ISSUE #1342: Components for Tuya Raw Datapoints (and substrings of Raw Datapoints)
**Describe the problem you have/What new integration you would like**

I recently got a Tuya MCU based night light + sound machine, but it uses non-standard DPIDs with much of the data being passed as a raw data point. For example, it has one light but three light modes (white, color, and effect) and the settings for the entire light is in dpid 103, type 0 = raw, data = `0x01000664010200F0000801`. That data breaks down as
```
0x01 - Light On/Off
0x00 - White Mode On/Off
0x06 - White Mode Brightness (1-20)
0x64 - White Mode Color Temp (0-100)
0x01 - Color Mode On/Off
0x02 - Color Mode Brightness (1-20) 
0x00F0 - Color Hue (0-360)
0x00 - Effect Mode On/Off
0x08 - Effect Mode Brightness
0x01 - Effect Index
```
So, in this example, the light is on in color mode at Brightness 2 = 10% and Hue 240 = Blue.

Currently, the Tuya Sensor platform does not even support the raw data type which would allow some reading of this data via lambdas, though I'm currently not sure about writing. A minimum solution could be to expose the raw data through a Tuya sensor then expose a service for writing a raw data substring. Then, a solution could be manageable with lambdas.

**Please describe your use case for this integration and alternatives you've tried:**

This would assist in controlling complex Tuya MCU devices. I have a complete, working solution for the device I have in Home Assistant via templates, input number, etc... https://github.com/tony-fav/SoulsensNL but it would be nice to be able to set this directly in ESPHome.

**Additional context**

### PR DESCRIPTION
**Pull request by tony-fav**
# What does this implement/fix? 

This adds a text_sensor to the Tuya implementation equivalent to the sensor but for string and raw datapoints. Raw datapoints are encoded to strings. Combined with the set_xxx_datapoint_value functions. This enables very powerful Tuya implementations. I have several tuya based lights with effect modes, colors, alarms, etc... that are implemented through raw datapoints. A few helper functions are included for later manipulation of the raw data points in lambda functions.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <https://github.com/esphome/feature-requests/issues/1342>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
text_sensor:
  - platform: tuya
    id: dpid_103
    sensor_datapoint: 103

light:
  - platform: tuya
    name: "${friendly_title} Effect Light"
    id: effect_light
    switch_datapoint: 102
    dimmer_datapoint: 123
    min_value: 10
    max_value: 1000
    effects:
      - lambda:
          name: "Aurora Left"
          update_interval: 1s
          lambda: |-
            std::string value = id(dpid_103).state;
            if ((value[1] != '0') or (value[89] != '0')) 
            {
              value[1] = '0';
              value[89] = '0'; 
              id(tuya_mcu).set_raw_datapoint_value(103, esphome::tuya::raw_decode(value));
            }
      - lambda:
          name: "Sunlight Sunset Orange"
          update_interval: 1s
          lambda: |-
            std::string value = id(dpid_103).state;
            if ((value[1] != '1') or (value[89] != '0')) 
            {
              value[1] = '1';
              value[89] = '0'; 
              id(tuya_mcu).set_raw_datapoint_value(103, esphome::tuya::raw_decode(value));
            }
      - lambda:
          name: "Night Red"
          update_interval: 1s
          lambda: |-
            std::string value = id(dpid_103).state;
            if ((value[1] != '2') or (value[89] != '0')) 
            {
              value[1] = '2';
              value[89] = '0'; 
              id(tuya_mcu).set_raw_datapoint_value(103, esphome::tuya::raw_decode(value));
            }
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by tony-fav** [comment]
My working example on a Dekala Table Lamp: https://github.com/tony-fav/DekalaTableLamp
Shows how the raw datapoint is used for setting the effect mode on the light and how a string datapoint (which in turn is a hex string) is used for the color light function's hue and saturation.

**Comment by tony-fav** [comment]
Suggestion in clang-tidy 4/4 does not seem possible. Getting 'namespace "std" has no member "to_string"' upon trying it in VSCode.

**Comment by irtimaled** [comment]
This would be perfect for setting the RGB value on my tuya mcu outdoor string light.

**Comment by kroimon** [comment]
Partially overlaps with #1812.

**Comment by tony-fav** [comment]
Closing as #1812 handles everything this sought to do.

**Pull request closed without merging**
