### PR TITLE
Climate bang bang enhancements

### LINKED ISSUE #1104: componen climate bang_bang don't work in mode heat or cool. (Source code that works bang_bang.cpp )
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Home assistant, docker
**ESP (ESP32/ESP8266, Board/Sonoff):**

esp32
**Affected component:**

**Description of problem:**
Component bang_bang don't work . Only in mode auto or off.
In mode heat or cool don't wor
Relays don't disable.
Y solve the problem to don't disable relays. But heat and cool modes behave like auto

**Problem-relevant YAML-configuration entries:**
```yaml
"node1.yaml"

sensor:
  - platform: dallas
    index: 0
    name: $Nombre_Sensor_01
    id: $Id_Sensor_01
    dallas_id: $Id_Hub_Sensor_01
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    resolution: 12
  - platform: gpio
    name: $Nombre_Salida_Calefaccion_01
    id: $Id_Salida_Calefaccion_01
    icon: $Icono_Id_Salida_Calefaccion_01
    restore_mode: ALWAYS_OFF    
    pin:
      mcp23008: mcp23008_hub_5
      number: 0
      mode: OUTPUT
  - platform: gpio
    name: $Nombre_Salida_Calefaccion_03
    id: $Id_Salida_Calefaccion_03
    icon: $Icono_Id_Salida_Calefaccion_03  
    restore_mode: ALWAYS_OFF 
    pin:
      mcp23008: mcp23008_hub_5
      number: 2
      mode: OUTPUT

climate:
  - platform: bang_bang
    sensor: $Id_Sensor_01
    id: $Id_Calefaccion_01
    name: $Nombre_Calefaccion_01
    visual:
      min_temperature: 12 °C
      max_temperature: 25 °C
      temperature_step: 0.1 °C

    default_target_temperature_low: 12 °C
    default_target_temperature_high: 22 °C
   
    heat_action:
      - switch.turn_on: $Id_Salida_Calefaccion_01
      - switch.turn_off: $Id_Salida_Calefaccion_03
    idle_action:
      - switch.turn_off: $Id_Salida_Calefaccion_01
      - switch.turn_off: $Id_Salida_Calefaccion_03
    cool_action:
      - switch.turn_on: $Id_Salida_Calefaccion_03
      - switch.turn_off: $Id_Salida_Calefaccion_01
        
"customize.yaml"
        - type: state-label
          entity: climate.nombre_calefaccion_01
          attribute: current_temperature
          suffix: ' ºC'
          style:
            top: 65%
            left: 22%
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
file
esphome/esphome/components/bang_bang/bang_bang_climate.cpp
[bang_bang_climate.zip](https://github.com/esphome/issues/files/4375334/bang_bang_climate.zip)

I think this problem is in return 
void BangBangClimate::compute_state_() {
  if (this->mode != climate::CLIMATE_MODE_AUTO) {
    // in non-auto mode
    this->switch_to_action_(static_cast<climate::ClimateAction>(this->mode));
//  return; THE PROBLEM TO SOLVED 
  }
Now the problem is that it either behaves like a shutdown or always like a car, I think because of the code that follows

### LINKED ISSUE #1205: bang_bang climate issue?
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Docker -> Hassio

**ESP (ESP32/ESP8266, Board/Sonoff):**
Esp32

**Affected component:**
bang_bang

**Description of problem:**
If from Home Assistant you set a temperature_high lower than the current temperature, the bang_bang (correctly) sets the action to OFF. But if later you set a temperature_hight higher than the current temperature, the bang bang does not reactivate and remains off

**Problem-relevant YAML-configuration entries:**
```yaml
climate:
  - platform: bang_bang
    sensor: dht22_t
    name: my_bang_climate
    id: my_bang_climate
    visual:
      min_temperature: 12 °C
      max_temperature: 35 °C
      temperature_step: 0.1 °C
    default_target_temperature_low: 27 °C
    default_target_temperature_high: 28 °C
    away_config:
      default_target_temperature_low: 26 °C
      default_target_temperature_high: 27 °C
    heat_action:
      - logger.log: "Heat ON"
      - switch.turn_on: OU7  
    idle_action:
      - logger.log: "Heat OFF"
      - switch.turn_off: OU7

```

**Logs (if applicable):**

```
[09:25:10][D][climate:010]: 'my_bang_climate' - Setting
[09:25:10][D][climate:020]:   Target Temperature Low: 17.70
[09:25:10][D][climate:023]:   Target Temperature High: 27.40
[09:25:10][D][climate:172]: 'my_bang_climate' - Sending state:
[09:25:10][D][climate:175]:   Mode: AUTO
[09:25:10][D][climate:177]:   Action: HEATING
[09:25:10][D][climate:180]:   Current Temperature: 22.92°C
[09:25:10][D][climate:184]:   Target Temperature: Low: 17.70°C High: 27.40°C
[09:25:10][D][climate:189]:   Away: OFF
[09:25:12][D][climate:010]: 'my_bang_climate' - Setting
[09:25:12][D][climate:020]:   Target Temperature Low: 17.70
[09:25:12][D][climate:023]:   Target Temperature High: 20.80
[09:25:12][D][main:683]: Heat OFF
[09:25:12][D][switch:025]: 'OU7' Turning OFF.
[09:25:12][D][switch:045]: 'OU7': Sending state OFF
[09:25:12][D][climate:172]: 'my_bang_climate' - Sending state:
[09:25:12][D][climate:175]:   Mode: AUTO
[09:25:12][D][climate:177]:   Action: OFF
[09:25:12][D][climate:180]:   Current Temperature: 22.92°C
[09:25:12][D][climate:184]:   Target Temperature: Low: 17.70°C High: 20.80°C
[09:25:12][D][climate:189]:   Away: OFF
[09:25:12][D][climate:172]: 'my_bang_climate' - Sending state:
[09:25:12][D][climate:175]:   Mode: AUTO
[09:25:12][D][climate:177]:   Action: OFF
[09:25:12][D][climate:180]:   Current Temperature: 22.92°C
[09:25:12][D][climate:184]:   Target Temperature: Low: 17.70°C High: 20.80°C
[09:25:12][D][climate:189]:   Away: OFF
[09:25:14][D][climate:010]: 'my_bang_climate' - Setting
[09:25:14][D][climate:020]:   Target Temperature Low: 17.70
[09:25:14][D][climate:023]:   Target Temperature High: 29.30
[09:25:14][D][climate:172]: 'my_bang_climate' - Sending state:
[09:25:14][D][climate:175]:   Mode: AUTO
[09:25:14][D][climate:177]:   Action: OFF
[09:25:14][D][climate:180]:   Current Temperature: 22.92°C
[09:25:14][D][climate:184]:   Target Temperature: Low: 17.70°C High: 29.30°C
[09:25:14][D][climate:189]:   Away: OFF

```

**Additional information and things you've tried:**

### LINKED ISSUE #1229: bang bang climate loses values ​​sent by home assistant
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP32

**Affected component:**
[Bang bang climate controller
](https://esphome.io/components/climate/bang_bang.html)

**Description of problem:**
The default_target_temperature_low and default_target_temperature_high settings, modified through the home assistant's lovelace gui are lost when the esp32 is restarted

**Problem-relevant YAML-configuration entries:**
```yaml
climate:
  - platform: bang_bang
    sensor: dht22_t
    name: my_bang_climate
    id: my_bang_climate
    visual:
      min_temperature: 12 °C
      max_temperature: 35 °C
      temperature_step: 0.1 °C
    default_target_temperature_low: 20 °C
    default_target_temperature_high: 22 °C
    away_config:
      default_target_temperature_low: 16 °C
      default_target_temperature_high: 17 °C
    heat_action:
      - logger.log: "Heat ON"
      - switch.turn_on: OU7  
    idle_action:
      - logger.log: "Idle ON"
      - switch.turn_off: OU7

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
Each time the esp32 is restarted, the bang bang start with the configurations taken in the .yaml file and loses any changes made through the home assistant gui

### PR DESCRIPTION
**Pull request by kbx81**
## Description:

This is a patch/update to the existing bang bang controller component. It aims to accomplish several goals:
  - Fix issues with existing controller behavior
  - Implement adjustable hysteresis, based on the custom component by @ssieb 
  - Implement (as optional configuration) additional actions for all available HA climate actions and modes:
    - `fan_only` and `dry` climate actions
    - Separate actions for climate mode changes
    - All currently available fan modes
    - All currently available swing modes
  - Minor code organization and readability improvements

**Related issues:**
 - fixes https://github.com/esphome/issues/issues/1104
 - fixes https://github.com/esphome/issues/issues/1205
 - fixes https://github.com/esphome/issues/issues/1229
 - implements https://github.com/esphome/feature-requests/issues/425
 - supersedes #1005

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#595

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by Cirrus94** [comment]
Thanks for putting in work to this component. The possibility to use one setpoint instead of two for heating only would be awesome since I think most of the people only use it for controlling their heating devices.

**Comment by kbx81** [comment]
Good suggestion, @Cirrus94 I'll take a look -- it probably wouldn't take much effort to tweak things to that it only reports a single available set point to HA if only one (heat **or** cool) is configured.

**Comment by ssieb** [comment]
I thought if you only configured one temperature that it only showed that one on HA.

**Comment by kbx81** [comment]
I need to research it more, but if this line does what I _think_ it does, then it would not: https://github.com/esphome/esphome/blob/f15713129cd5587242a08ad1e2ee37cbf075aa03/esphome/components/bang_bang/bang_bang_climate.cpp#L76

I need to look at it more closely and do a little more testing. 😄

**Comment by kbx81** [comment]
@Cirrus94 I just pushed up a change...if/when you have a moment, see if this accomplishes what you described. 😄

**Comment by ssieb** [comment]
However, both temperatures are still required in the config.  The requirement should be connected to heating and cooling being available.

**Comment by kbx81** [comment]
Good catch @ssieb...let me take a look and see if I can tweak that, too...

**Comment by Cirrus94** [comment]
@kbx81 How can i test your code? Sorry but I am more the consumer as an dev 🙈

**Comment by kbx81** [comment]
@Cirrus94 no worries! If you have `git` installed, you can clone my fork: kbx81:climate-bang-bang-enhancements (link also at the top of this page).
With that cloned, you can use use ESPHome's command-line tools to install the modified code onto your device for testing: https://esphome.io/guides/getting_started_command_line.html
Hopefully that helps get you started! 😄

**Comment by blademckain** [comment]
hi, can u insert in your enhancements the fix for 
https://github.com/esphome/issues/issues/1229

**Comment by kbx81** [comment]
I just pushed up a fix that has proven to resolve this issue on my hardware. If you're able, please try it and confirm @blademckain. 😄

**Comment by blademckain** [comment]
Thanks a lot, now I try!
I believe the main problem is how the climate component treats away mode. If you read [the Home assistant documentation](https://www.home-assistant.io/integrations/climate/), the away mode is not a true or false Boolean. But it is a PRESET like all the others (default, home, eco, confort, away, etc).


It would be useful to modify the climate component, for example, like this:
`yaml
climate:
.....
     preset:
         -name: home
           target_temperature_low: 20 °C
           target_temperature_high: 22 °C
         -name: away
           target_temperature_low: 16 °C
           target_temperature_high: 18 °C
     initial_preset: home
.....

`

In this way it would also be possible to combine the two structures: BangBangClimateTargetTempConfig and ClimateDeviceRestoreState in a single structure.
For example
`
struct ClimatePresetStruct
{
  string name;
  float target_temperature;
    struct {
      float target_temperature_low;
      float target_temperature_high;
    };
};

struct ClimateDeviceInitialState {
  ClimateMode mode;
  ClimatePreset current_preset;
  ClimateFanMode fan_mode;
  ClimateSwingMode swing_mode;
  ClimatePresetStruct preset[n];
  };

`

and now it would be easy to save the configurations of all the presets (including those possibly modified by the GUI)

`
auto restore = this->restore_state_();
  if (restore.has_value()) {
	    this.ClimateDeviceInitialState <--------- Loaded for memory
  } else {
             this.ClimateDeviceInitialState <--------- Loaded for config
  }
`

**Comment by kbx81** [comment]
@blademckain that's a great idea, however the base class `Climate` in ESPHome handles "away" with a `bool` type. While this would be a great capability to have, it would require changes to at least one upstream class which could impact other components. As such, it's probably a bit out of scope of this particular PR.

**Comment by blademckain** [comment]
I tried your branch and seems that the problem is fixed!
Thx you!

**Comment by blademckain** [comment]
I will wait if someone in the future wants to insert the presets in order to have the possibility through the home assistant GUI to be able to modify the values ​​of all the presets.
:)

**Comment by glmnet** [comment]
Should I tag this breaking change?

**Comment by kbx81** [comment]
@glmnet it's not a breaking change as far as the config itself is concerned. It does, however, change the behavior with respect to the component as it was before -- that said, I think the consensus I've seen as it's been discussed on Discord is that the behavior this change implements is proper and correct. The way it worked before...just wasn't right.

**Comment by glmnet** [comment]
Do you think you can put together a short description of the behavior change? I’d believe it should be included in the release notes.

**Comment by kbx81** [comment]
Absolutely, yes. Where should I put that?

**Comment by glmnet** [comment]
I believe the best way will be creating the change log for v1.15, I believe Otto does them when releasing. 
May be a good habit will be to update chengelog as PR are being merged, so this one docs, can create the v1.15 file? it is in changelog folder

**Comment by kbx81** [comment]
Cool, I'll get one started. Looks like I've got a merge conflict to resolve in the docs for this one, anyway. 😄

**Comment by blademckain** [comment]
after the release of these improvements, I ask you if you can also think about the adaptation of the climate component in line with that of the [home assistant as far as the management of the presets is concerned](https://developers.home-assistant.io/docs/core/entity/climate/#presets)

**Comment by kbx81** [comment]
@blademckain you should submit this through a [feature request](https://github.com/esphome/feature-requests) so that it is not lost when this PR is eventually merged and closed. 😄

**Comment by dseven** [comment]
FWIW, I've been running @kbx81 's code for a couple of weeks, on a couple of prototype ESP thermostats. It's behaving as expected. The current released version makes no sense. This change is much needed. Thanks to @kbx81 for putting the work in!

**Comment by igg** [comment]
This new device is a bang_bang_bang_bang. It has twice as many setpoints as the old bang_bang. The reason it's a breaking change is that the meaning of the high vs. low set point has been changed.  Before, the low and high setpoints defined the hysteresis for the controller, but now the hysteresis is a new variable, and the two setpoints now define the mid-points of the two separate bang_bang controllers that are now implemented here.

There is a simple mitigation here - just call this device by a different name (I would suggest `bang_bang2` in the ^2 sense, not v2) and leave the old bang_bang alone.

I don't know what was confusing about the old bang_bang. The two set points defined the hysteresis for the controller, and it did exactly what was documented, and worked great for me. If someone tried to control both a Heating and AC unit using a single bang_bang, I can see how that would lead to big trouble, but that is not a reason to completely throw out a perfectly good controller in favor of a more complex one.
Using a single bang_bang for both heating and cooling, it would work like this: heater comes on, stays on until the high-temp. High-temp turns on AC and turns off heater. AC stays on until it reaches the low-temp, triggering the heater. Repeat, see-saw back and forth, with the heater or the cooler always on. Don't know why anyone would want that, but that's what a single bang_bang controlling both heating and cooling would do - by design!

This new controller makes much better sense for Heating&AC units, because it implements two separate bang_bangs, one for heating and one for cooling, as it should be. This is a great improvement for a lot of people. There are however also a lot of people who have one of the two, but not both. Same with humidifiers, etc.

Since you can turn one of the two bang-bangs implemented here off, and still have heating (or cooling or humidity) with hysteresis, this is a better implementation, which should probably replace the old bang_bang, but not with a breaking change. This new controller has twice as many bang_bangs, twice as many control points, twice as many hysteresees, plus a fancy fan thingie with tilt and pan, so by all rights should really be named something else. I don't have anything against the old bang_bang and I don't see any reason to deprecate it, but if it is, it should really go through some sort of process. Personally, I will rewrite my device to use the new bang_bang because my device is already deployed and I need to use dev for other reasons. So I don't really have a stake in this anymore other than I want the project to prosper and breaking changes work against that.

Some other implementation notes:
* The hysteresis is a key variable and it would be nice if it was readable and writable at run-time. It will require some fiddling in the initial system configuration, but once set it will be unlikely to change. It must at least be readable on the device if hysteresis can be changed by the HA UI. I tried reading and writing it in the same way as other settings (like `target_temperature_low` for e.g.) and that produced errors.
* There should probably be separate hysteresis for the high side and the low side. I would expect that heaters would prefer a different amount of hysteresis than AC units. I might be wrong about this, but since there are formally two separate bang_bangs implemented, they should really have their hysteresis controllable separately. The existing hysteresis variable can control both, and two new variables can control the high setpoint or the low setpoint separately. There is no point to controlling the high-side-high and high-side-low separately from hysteresis.
* Documentation should discourage users from using a single bang_bang to control both heating and cooling, and describe the heating-cooling see-saw to make sure that's what they want.

**Comment by glmnet** [comment]
Yes, I believe a new double_bang_bang  will fit better in this case, too much change in behavior will make people to have to test all again 

Thanks igg

**Comment by glmnet** [comment]
The problem here is that I’m the only reviewer and I don’t use this. 
We have to figure out a better approach, the components main behavior shouldn’t change, one way of doing this might be the component code owner pattern. 
So I vote for a new bang bang owned by kbx81 and we roll back this new one, the old bang bang can receive some small bug fixes if needed, maybe igg can get in charge of it. 

Please give feedback, this should be easy to come to an agreement

Any other ideas?

**Comment by dseven** [comment]
I couldn't make any sense of the old implementation, but it may be because I was trying to fit it into a heat/cool system. It's been too long now to remember the details. If it's actually useful in its current form (I thought it was just b0rked), then making @kbx81 's implementation into a new component makes sense. I agree with @igg 's other notes too ... maybe those can be implemented later. The basic implementation seems to be working well for me.

**Comment by ssieb** [comment]
This is funny because we discussed this for weeks in Discord.  During that time, several people came in asking what was wrong with the bang_bang controller and were really happy with this new one we were working on.

**Comment by kbx81** [comment]
Piggybacking off of what @ssieb mentioned, I think the main reason for (initially) _not_ making it a new component was the clear abundance of confusion around what the original version was doing. We were seeing many questions about it on Discord, sometimes 2-3 a week. Perhaps the original documentation was not clear somehow -- I'm not really sure.

I am absolutely fine with reverting this merge, renaming it and setting up a new PR.

Personally, I didn't really see it as a real breaking change -- as implemented here, worst-case it requires only a modest config update; possible removal of one, maybe two lines from your config, depending on how you use it. The hysteresis value has a default value but it can be added to the config if the default is not suitable. The behavior is the same in terms of the bang_bang operation, but, as @igg mentioned, there is a bang-bang built around both set points and it uses the hysteresis value to compute that window, as opposed to using the set points themselves. So, it is correct to say that it is a bang-bang-bang-bang.

As it relates to Home Assistant, from what I can tell, the handles on the climate/thermostat UI are not intended to define a window for hysteresis. They are intended to define an upper (cool) and lower (heat) set point -- so I would argue that this update more correctly uses the HA UI. Still, this is also departs from what it was doing before, so if we agree that it should be rolled into a component with a different name, it's perfectly fine by me. I was just trying to make it work in a way that seemed to be more consistent with what most people appear to be expecting. 🙂

**Comment by kbx81** [comment]
@glmnet I am fine with whatever course of action the lot here would prefer. Components are easy to rename, the hard work is really done. I would be happy to submit a PR for the updated component with a different name and we can revisit the issues that were open on the old implementation later. We just need to decide on a new name if we vote to change it. 😆 We'll want to get it merged back in quickly because I am quite sure people will be asking about what happened. 🙂

**Comment by ssieb** [comment]
I've never seen a thermostat that lets you manually adjust the hysteresis and I can't see the point in that.  However, despite HA not having any interface for it, you could adjust the hysteresis using a lambda call in the esphome config.
I'm fine with a name change as well.  My component was called "bang_bang2".  However, to avoid going through the same situation of having many people coming in asking what's wrong with it, please make a big reference to the other component so that people will find it.

**Comment by dseven** [comment]
FWIW, I have two commercially-made WiFi thermostats, and the BOTH allow configuration of anti-hysteresis, although they call it different things. RadioThermostats call it "temperature swing". Venstar calls it "dead band". In both cases, they allow you to define the extent by which the measured value can exceed the limit before the action is invoked (e.g. a swing of 1.5F with a target cooling temp of 76F would cause cooling to begin when the measured temperature exceeds 77.7F). @kbx81 's implementation is slightly different, but it works, so long as it's documented.

**Comment by igg** [comment]
I will work on clarifying the babg_bang docs, and any other fixes it needs, but most of the clarity will be thanks to this device and the work by @kbx81 implementing it, since I have a feeling that most people were trying to implement thermostats for both heating and cooling with a single bang_bang which is almost certainly not what they wanted to do.

@ssieb mentioned that changing the hysteresis in a lambda is possible, bit I could not read or write it in a lambda on the device. Using the call interface with set_hysteresis or reading it like target_temperature resulted in configuration compilation errors about these fields not existing.

Sorry for causing such a stir! I'm glad the consensus seems to be to avoiding breaking any bang_bangs that may be out there!

**Comment by kbx81** [comment]
I'll work on renaming the component tonight and get new PRs together this evening. 🙂 I'll also see if I can sort out what's going on with the hysteresis value, as you _should_ be able to adjust that value in code with a lambada, just like any of the other controller parameters.

**Comment by ssieb** [comment]
`id(my_bang_bang).set_hysteresis(1.5)` should work in a lambda.  There's no way to read the current value.  I suppose that could be considered with the new PR.

**Comment by igg** [comment]
@ssieb, your way works, but that is a new and undocumented way for settings things in the climate controller. The documentation has you do things this way for the temperature setpoints:
```
          auto call = id(climate_control).make_call();
          call.set_target_temperature_low ( target_temp_L_c );
          call.perform();
```
Your way works, but is undocumented, and follows a different pattern from how other fields are set for this control.
I can't change the target temperature by calling `id(my_bang_bang).set_target_temperature_low(20.5)` and I can't call `id(my_bang_bang).target_temperature_low(20.5)`. I have to use the pattern above for writing. Consistency makes things easier to use and even alleviates the requirement that every last thing has to be documented.

For what it's worth, I can't use lambdas to set the default (starting) temperatures in the initial config either, because these parameters are not templatable. Not a show-stopper or anything, but generally being able to set the initial settings programmatically would make life a lot easier. As it is, this doesn't work:

```yaml
climate:
    ...
    default_target_temperature_low: !lambda |-
      return (id(target_temp_L_F) - 32.0) * (5.0/9.0);
    default_target_temperature_high: !lambda |-
      return (id(target_temp_H_F) - 32.0) * (5.0/9.0);
    hysteresis: !lambda |-
      return ( (id(hysteresis_F) - 32.0) * (5.0/9.0) );
```

**Comment by ssieb** [comment]
Only things that are in the interface are accessed through the call interface.  The hysteresis is primarily intended as an initialization value, not a runtime value, so you need direct access to the component.  It has to be that way so that the setup code can set the value.  Lambdas are also not intended for initialization values.  They are only for runtime parameters or values that are expected to change regularly.  The other esphome components have the same "limitation".

**Comment by kbx81** [comment]
Alrighty gang...
https://github.com/esphome/esphome/pull/1105
https://github.com/esphome/esphome-docs/pull/665

@glmnet I'm fine if you want to revert this merge. I'll probably have a couple conflicts to resolve after the revert but they'll be quick fixes. 😄

**Comment by igg** [comment]
@ssieb, fair enough.

**Comment by blademckain** [comment]
+1 for Thermostat component
[but in a thermostat you can not miss the management of presets :)](https://github.com/esphome/feature-requests/issues/752)

**Pull request merged**
