### PR TITLE
Add DNS sensor and simplify format

### PR DESCRIPTION
**Pull request by HeMan**
# What does this implement/fix?

Add a dns sensor to Ethernet component and changes to a simpler format on wifi_sensor dns_address.
New format is the DNS-servers in a space separated list.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3721
## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
esphome:
  name: ethernet

esp32:
  board: esp32dev
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0

text_sensor:
  - platform: ethernet_info
    dns_address:
      name: ESP DNS Address
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nagyrobi** [comment]
How many DNS addresses are supported?

**Comment by HeMan** [comment]
> How many DNS addresses are supported?

It supports two, but your question got me thinking. I'll rewrite all DNS server reporting to support more since with dual stack it could have some servers over IPv4 and some over IPv6.

**Comment by HeMan** [comment]
> How many DNS addresses are supported?

Did some testing and couldn't get any of my configurations to have more than two DNS servers so my guessing is that lwip supports up to two.

**Comment by nagyrobi** [comment]
So your sensor will print them both?
IPv4, IPv6, that's total four?

**Comment by HeMan** [comment]
> So your sensor will print them both? IPv4, IPv6, that's total four?

My sensor will print up to two DNS servers that lwip reports. Not all platform combos (Arduino, esp-idf, rp2040, ethernet, wifi) seem to report any IPv6 server every time.

**Comment by nagyrobi** [comment]
I'd suggest to remove `DNS1:` and `DNS2:` from the output. Just have a space or comma separated list. As we could use DNS in the name of the sensor.

Reason - easier to process output in lambdas.

**Comment by HeMan** [comment]
> I'd suggest to remove `DNS1:` and `DNS2:` from the output. Just have a space or comma separated list. As we could use DNS in the name of the sensor.
> 
> Reason - easier to process output in lambdas.

I copied from `wifi_sensor` and think they should behave the same way. I could do a PR to change that sensor.

**Comment by nagyrobi** [comment]
That would be good!

**Review by clydebarrow — DISMISSED** [review]
LGTM. Tested on a GL-S10

**Comment by clydebarrow** [comment]
Needs docs now...

**Comment by clydebarrow** [comment]
And tests.

**Comment by HeMan** [comment]
> And tests.

Any ideas how to test this? Mock `ethernet::global_eth_component->get_dns_address` and `wifi::global_wifi_component->get_dns_address` and comparing output feels a bit meh

**Comment by clydebarrow** [comment]
Basically just a sample config that will get built - it's a config and compile test, not functionality. Unit testing is yet to gain much of a foothold here.

**Review by clydebarrow — APPROVED** [review]
LGTM

**Pull request merged**
