### PR TITLE
Fix HttpRequestResponseTrigger

### LINKED ISSUE #4010: http_request on_response does not compile with toolchain-riscv32-esp (used on esp32-c3 boards)
### The problem

The on_response trigger for the http_request component does not compile on esp32-c3 boards.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

lolin_c3_mini

### Component causing the issue

http_request

### Example YAML snippet

```yaml
# Minimal yaml reproducing the problem.
wifi:
  ssid: 'ssid'

esp32:
  # nodemcu-32s works fine
  # board: nodemcu-32s
  # but lolin_c3_mini does not
  board: lolin_c3_mini
  framework:
    type: arduino

esphome:
  name: 'on-response-test'
  on_boot:
    then:
      - http_request.send:
          method: PUT
          url: https://esphome.io
          headers:
            Content-Type: application/json
          body: Some data
          verify_ssl: false
          on_response:
            then:
              - logger.log:
                  format: "Response status: %d"
                  args:
                    - status_code

logger:

http_request:
  useragent: esphome/tagreader
  timeout: 10s
```

### Anything in the logs that might be useful for us?

```txt
src/main.cpp: In function 'void setup()':
src/main.cpp:150:79: error: no matching function for call to 'esphome::Automation<long int>::Automation(esphome::http_request::HttpRequestResponseTrigger*&)'
   automation = new Automation<int32_t>(http_request_httprequestresponsetrigger);
                                                                               ^
In file included from src/esphome/components/http_request/http_request.h:6,
                 from src/esphome.h:5,
                 from src/main.cpp:3:
src/esphome/core/automation.h:234:12: note: candidate: 'esphome::Automation<Ts>::Automation(esphome::Trigger<Ts ...>*) [with Ts = {long int}]'
   explicit Automation(Trigger<Ts...> *trigger) : trigger_(trigger) { this->trigger_->set_automation_parent(this); }
            ^~~~~~~~~~
src/esphome/core/automation.h:234:12: note:   no known conversion for argument 1 from 'esphome::http_request::HttpRequestResponseTrigger*' to 'esphome::Trigger<long int>*'
src/esphome/core/automation.h:232:32: note: candidate: 'constexpr esphome::Automation<long int>::Automation(const esphome::Automation<long int>&)'
 template<typename... Ts> class Automation {
                                ^~~~~~~~~~
src/esphome/core/automation.h:232:32: note:   no known conversion for argument 1 from 'esphome::http_request::HttpRequestResponseTrigger*' to 'const esphome::Automation<long int>&'
src/esphome/core/automation.h:232:32: note: candidate: 'constexpr esphome::Automation<long int>::Automation(esphome::Automation<long int>&&)'
src/esphome/core/automation.h:232:32: note:   no known conversion for argument 1 from 'esphome::http_request::HttpRequestResponseTrigger*' to 'esphome::Automation<long int>&&'
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gmbuell**
# What does this implement/fix?

This fixes HttpRequestResponseTrigger which does not compile correctly with toolchain-riscv32-esp.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4010

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Minimal yaml reproducing the problem.
wifi:
  ssid: 'ssid'

esp32:
  # nodemcu-32s works fine
  # board: nodemcu-32s
  # but lolin_c3_mini does not
  board: lolin_c3_mini
  framework:
    type: arduino

esphome:
  name: 'on-response-test'
  on_boot:
    then:
      - http_request.send:
          method: PUT
          url: https://esphome.io
          headers:
            Content-Type: application/json
          body: Some data
          verify_ssl: false
          on_response:
            then:
              - logger.log:
                  format: "Response status: %d"
                  args:
                    - status_code

logger:

http_request:
  useragent: esphome/tagreader
  timeout: 10s

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by grillp** [comment]
Love to see this fixed ASAP! :-)

**Review by jesserockz — APPROVED** [review]

**Comment by gmbuell** [comment]
@jesserockz Looks like your merge removed the change from int to int32_t which was necessary to fix the problem.

**Comment by jesserockz** [comment]
Oh woops..
Wanna make another PR?

**Comment by gmbuell** [comment]
@jesserockz https://github.com/esphome/esphome/pull/4285

**Pull request merged**
