### PR TITLE
add way to exclude tests for given platform

### PR DESCRIPTION
**Pull request by tomaszduda23**
# What does this implement/fix?

There is `test.all.yaml` which is great idea. This add way to exclude given platform from build. Example of usage: `tests/components/datetime/exclude.test.nrf52-mcumgr`. It is part of https://github.com/esphome/esphome/pull/7049

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
I'm not sure we should have a need for this. Anywhere that has a `test.all.yaml` file should be supported on any and all platforms that ESPHome supports. 

I am guessing datetime is failing on not having a `time` platform available for the nrf?

At the very least this should not be a YAML file as this will never contain YAML, but simply be an empty marker file that simply exists.

**Comment by tomaszduda23** [comment]
1. I didn't want to add more code to this PR. I assume it would be possible to fix compilation of time component.
2. I've noticed that after some changes which I made in the past some configuration stopped compiling even though CI was all green. I like the idea of `test.all.yaml`. Most components tests could be tested that way. Some kind of GPIO unification or aliases would be needed but it does not sounds very difficult. Than if needed `exclude` could be used to disable test for some platform. Current design requires adding explicit new target to all components which might be difficult to maintain over time.

I'm not sure if this is good place to discus the future strategy for testing though :smile:

**Comment by tomaszduda23** [comment]
It looks that timezones are not supported by zephyr https://docs.zephyrproject.org/3.5.0/services/portability/posix.html. It would required using external library which I don't want to add  e.g. https://github.com/josmithua/utz. I will implement `time` component without timezone support for now. The easiest solution would be to add time offset and dst flag. It is not perfect either.

**Comment by tomaszduda23** [comment]
@jesserockz would you mind to take a look again? Now the use cases look more clear.

**Pull request closed without merging**
