### PR TITLE
ESP32 BLE controller (server)

### PR DESCRIPTION
**Pull request by wifwucite**
# What does this implement/fix? 

Provides a new component that exposes a BLE server allowing to (securely) communicate with an ESP32 over BLE with for example a smart phone or a tablet in order to
- read sensor values (and be notified of updates)
- turn on/off switches and fans
- view log messages
- set and clear (temporary) Wifi credentials

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [x] ESP32
- [ ] ESP8266
- [ ] Windows
- [x] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

# Explain your changes

Describe your changes here to communicate to the maintainers **why we should accept this pull request**.
Very important to fill if no issue linked

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
I have done most of this in #1849 :wink:

**Comment by wifwucite** [comment]
@jesserockz Good to know, I have missed that PR. I have not looked at your code, but from looking at the description it seems you are missing some good stuff:
- fan support
- logging over BLE (nice if you do not have wifi and cannot attach a cable ;-))
- security (in particular for setting credentials)
- command framework (incl. help and custom commands via automations)

I would appreciate it if you could add a link to my [external component](https://github.com/wifwucite/esphome-ble-controller) in the docs of your server component, so if someone needs the extra stuff, they could find it.

Moving forward it would be nice to integrate this extra stuff into the core as well. What do you think?

**Comment by jesserockz** [comment]
- Fan Is yet to be done (and all other types)
- I added a logging service already
- Security is something I want to get done
- Custom commands I will think about

Happy for a PR to add those things to that branch though. Also you will to do them differently though as you are using the Arduino APIs and I moved my code to use esp-idf directly

**Comment by wifwucite** [comment]
Well, fan should be easy if you have switch already. The other stuff is probably more complicated. 
So you are saying I could make a PR for the ble-server-controller branch?

**Comment by jesserockz** [comment]
Yeah, I was going to do fan, just had other stuff to do up to now...
Yeah, there is no issue making a PR against another branch =)

**Comment by wifwucite** [comment]
I see. Just to make sure we are on the same page concerning fan. I implemented the characteristic as string. When reading it gives a string like "fan=off speed=65 oscillating=no" (depending on the traits). And when you send the string "on 42 yes" it would turn the fan on, set the speed to 42% and turn oscillation on in one transaction. If you are happy with this behaviour, I could try to port my code. :-)

**Pull request closed without merging**
