### PR TITLE
Generate partitions.csv based on flash size

### PR DESCRIPTION
**Pull request by kbx81**
# What does this implement/fix?

This change will generate `partitions.csv` based on `flash_size` in `esp32` config.

The default is `4MB` to maintain compatibility; other supported values are `8MB`, `16MB` and `32MB`.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3345

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
esp32:
  board: esp32dev
  flash_size: 16MB
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by balloob** [comment]
Can we also make this a value that can be passed to the wizard, and if so, it's added to the YAML ? It would also be nice if we could set this when adopting a device.

**Comment by randybb** [comment]
or autodiscovered after first flashing

**Comment by jesserockz** [comment]
Adopting a device probably doesn't need to know about this as the pre-flashed firmware should have the correct setting for the device.

**Comment by balloob** [comment]
Empty ESPHome device firmware flashed through esphome.io/projects or web.esphome.io would need to know the flash size.

**Comment by jesserockz** [comment]
For those we can probably create a firmware file per flash size and esptool.js can get the size and flash the correct file in the first place?
Could be a new feature of the manifest to add an optional `flash_size` to each `build` to match against, just like the `chipFamily` is matched?

**Comment by balloob** [comment]
Yeah it's been a feature requested before for ESP Web Tools. Looks like we can move that forward.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
