### PR TITLE
MIDI In

### PR DESCRIPTION
**Pull request by muxa**
# What does this implement/fix? 

MIDI In allows connecting MIDI devices, such as MIDI Keyboards, drum pads, etc. to ESPHome and receive events, such as Key On/Off, Controller change, etc. Uses "Arduino MIDI Library" under the hood.

> I've published this as external component as well to make it easier for people to test it: https://github.com/muxa/esphome-midi

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** esphome/feature-requests#1501

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 
esphome/esphome-docs#1636

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 31250

midi_in:
  - uart_id: uart_bus
    on_channel_message:
      - logger.log:
          format: "%i: %#04x (%#04x %#04x)"
          args: [ 'x.channel', 'x.type', 'x.data1', 'x.data2' ]
      - lambda: |-
          if (x.type == midi::MidiType::ProgramChange) {
            ESP_LOGD("midi_in", "PROGRAM CHANGE: %#02x (channel %i)", x.data1, x.channel);
          }
    on_system_message:
      - lambda: |-
          if (x.type == midi::MidiType::SystemReset) {
            ESP_LOGD("midi_in", "RESET");
          }
    connected: # optional binary_sensor
      name: "MIDI Keyboard Connected"
      device_class: connectivity
      filters:
        - delayed_off: 5s
    playback: # optional binary_sensor
      name: "MIDI Keyboard Playback"
      device_class: occupancy
      icon: mdi:piano
      filters:
        - delayed_off: 60s
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by muxa** [comment]
Instead of implementing MIDI protocol myself I'll just use Arduino Library (https://github.com/FortySevenEffects/arduino_midi_library/).

**Comment by muxa** [comment]
With trial and error I managed to replace my custom MIDI implementation with MIDI Library for reading and parsing MIDI data (and still relying on the underlying `UARTDevice` as transport)

**Comment by muxa** [comment]
Ok, documentation added. This PR is ready for review.

**Comment by muxa** [comment]
Hey @mmakaay any chance you can review this PR?

**Comment by mmakaay** [comment]
Sure, I can take a look at it tomorrow I think.

**Comment by muxa** [comment]
After some testing controlling addressable lights from MIDI I have found that the MIDI Library does not perform fast enough to drive the LEDs in real time (especially when sending lots of notes together). My custom MIDI implementation (removed in `33b6bdfcbae5141ceaf7395b079badcab3c57352`) was way faster and had no problem keeping up with any number of notes being played). Not sure if there's a bug in MIDI Library of its design affects performance. 
I'll see if I can find the bottleneck in the MIDI Library. Failing that, I'll revert to must custom implementation (keeping MIDI Library for enums and structures though).

**Comment by mmakaay** [comment]
> keeping MIDI Library for enums and structures though

Would be nice if those are implemented without the library then, so make the code compatible with ESP-IDF.

BTW Been looking at the code during some spare moments that I had. So far it looked clean and readable.

**Comment by muxa** [comment]
> Would be nice if those are implemented without the library then, so make the code compatible with ESP-IDF.

Yup, will do that if I can't make it fast enough with the MIDI Library.

> BTW Been looking at the code during some spare moments that I had. So far it looked clean and readable.

Thanks :)

**Comment by muxa** [comment]
@mmakaay I have fixed the performance issue. It turns out I incorrectly used the `read()` function of the library (thinking it behaves similarly to UART's `read()` function).

**Comment by muxa** [comment]
I want to change some internals to expose the note velocities via `uint8_t note_velocity(uint8_t note)` and expose all controller values via `uint8_t controller_value(midi::MidiControlChangeNumber controller)`. I also want to track if the note is playing based on sustain/sostenuno pedal and and be able to get that information via `midi_in::NoteStatus note_status(uint8_t note)`

```c
enum NoteStatus {
  Off = 0,
  On = 1,
  Sustained = 2
}
```

**Comment by muxa** [comment]
I've published this as external component for now to make it easier for people to test it: https://github.com/muxa/esphome-midi

**Comment by mmakaay** [comment]
> to make it easier for people to test it

I gotta solder together that schematic to do some hardware testing with it.
The only thing I'm missing are some MIDI plugs.

**Pull request closed without merging**
