### PR TITLE
ESP32 Set recommended framework to 2.0.0

### PR DESCRIPTION
**Pull request by OttoWinter**
# What does this implement/fix? 

**Blocked due to https://github.com/platformio/platform-espressif32/issues/619**

See https://github.com/espressif/arduino-esp32/releases/tag/2.0.0

Things may break, draft to allow for testing and discussion

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
Looks like the latest platform-espressif32 doesn't support framework v2.0.0 yet :(

https://github.com/platformio/platform-espressif32

**Comment by agners** [comment]
@OttoWinter yeah its not available according to the API currently:

```
$ curl --silent https://api.registry.platformio.org/v3/packages/platformio/tool/framework-arduinoespressif32 | jq '.versions[].name'
"3.10006.210326"
"3.10005.210308"
"3.10005.210223"
"3.10004.210126"
"3.10004.201016"
"2.10004.191002"
"2.10003.190916"
"2.10002.190628"
"2.10001.190111"
"2.10000.0"
"1.10000.0"
"1.6.0"
"1.5.3"
"1.4.0"
"1.3.2"
"1.2.0"
"1.1.5"
```

**Comment by agners** [comment]
There is a `arduino-idf-master` branch. With it you can also select the 2.0.0 release version:

```yaml
esphome:
  ...
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32#feature/arduino-idf-master
    platform_packages:
      - framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.0
```

**Comment by dcousens** [comment]
- https://github.com/platformio/platform-espressif32/issues/619 
has been marked as completed, which was blocking this according to the description

**Pull request closed without merging**
