### PR TITLE
Change millis() to faster micros() for 3ms check in feed_wdt

### PR DESCRIPTION
**Pull request by CarlosGS**
# What does this implement/fix? 

Simple change for slight speed increase. `feed_wdt()` should be as quick as possible because it is called in high speed loops.

Currently it was using `millis()` https://github.com/esp8266/Arduino/blob/60fe7b4ca8cdca25366af8a7c0a7b70d32c797f8/cores/esp8266/core_esp8266_wiring.cpp#L166-L199
That is much longer than `micros()`, and it's unnecessary for such a short delay.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by davet2001 — COMMENTED** [review]
LGTM but looks like this tips one of the tests over the edge on size.

**Comment by CarlosGS** [comment]
It seems micros() wasn't being cached for that test?
I don't quite grasp the problem, as micros() should be pervasive. But the change isn't worth extra RAM.

**Comment by oxan** [comment]
> It seems micros() wasn't being cached for that test? I don't quite grasp the problem, as micros() should be pervasive. But the change isn't worth extra RAM.

It's likely that no component included in that test used `micros()` before, so it wasn't put into the binary. This change causes it to be linked in, making the IRAM section too large. We should probably split that test up, we've seen this problem in another PR too.

**Comment by OttoWinter** [comment]
Hmm, that is a strange issue with test3...

micros() really shouldn't be that big, it just calls `system_get_time` which is a small symbol by itself (and used by millis() as well)

**Comment by oxan** [comment]
> Hmm, that is a strange issue with test3...
> 
> micros() really shouldn't be that big, it just calls `system_get_time` which is a small symbol by itself (and used by millis() as well)

I checked before submitting #2499, and there were only 4 bytes of free IRAM left. Since `micros` cannot be inlined, it pushed usage over the limit. Doesn't matter how big the function is, just the function preamble/epilogue is probably more than 4 bytes already.

**Review by oxan — APPROVED** [review]

**Comment by oxan** [comment]
Thanks!

**Pull request merged**
