### PR TITLE
Change uptime's state_class to total_increasing (esphome/issues#2337)

### LINKED ISSUE #2337: Uptime: state_class empty
### The problem

The default state_class of the uptime sensor reports as `''` (empty string).

Looking at the ESPHome [sensor documentation](https://esphome.io/components/sensor/index.html) and the linked Home Assistant [state classes documentation](https://developers.home-assistant.io/docs/core/entity/sensor/#available-state-classes), I feel the state_class should probably be `total_increasing`. Testing it locally by overriding it in the YAML seems to work fine.

If it should be `total_increasing`, I would be happy to create a PR.

### Which version of ESPHome has the issue?

v2021.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.3

### What platform are you using?

ESP8266

### Board

D1 Mini

### Component causing the issue

uptime

### Example YAML snippet

```yaml
esphome:
  name: garage_freezer
  comment: "Garage freezer temperature monitor"
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_pass
  domain: !secret iot_domain
  enable_mdns: false

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: !secret garage_freezer_ota

captive_portal:

api:
  password: !secret garage_freezer_api

ota:
  password: !secret garage_freezer_ota

# Enable logging
logger:
  level: VERBOSE
  logs:
    app: DEBUG
    sensor: DEBUG

# Dallas 1-Wire Library
dallas:
  pin: D1
  update_interval: 30s

# Dallas 1-Wire Temperature Sensors
sensor:
  - platform: dallas
    id: ds18b20_ae032197799cc128
    name: "DS18B20 0xAE032197799CC128"
    address: 0xAE032197799CC128
    accuracy_decimals: 2

  # Uptime (just for fun)
  - platform: uptime
    name: "Garage Freezer Uptime"
    id: uptime_sensor
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/garage_freezer.yaml...
WARNING 'garage_freezer': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
INFO Starting log output from garage_freezer.[redacted] using esphome API
INFO Connecting to garage_freezer.[redacted]:6053 (192.168.0.102)
INFO Successfully connected to garage_freezer.[redacted].net
[08:42:08][I][app:106]: ESPHome version 2021.8.0 compiled on Aug 20 2021, 08:29:09
[08:42:08][C][status_led:019]: Status LED:
[08:42:08][C][status_led:020]:   Pin: GPIO2 (Mode: OUTPUT)
[08:42:08][C][wifi:499]: WiFi:
[08:42:08][C][wifi:359]:   SSID: [redacted]
[08:42:08][C][wifi:360]:   IP Address: 192.168.0.102
[08:42:08][C][wifi:362]:   BSSID: [redacted]
[08:42:08][C][wifi:363]:   Hostname: 'garage_freezer'
[08:42:08][C][wifi:367]:   Signal strength: -46 dB ▂▄▆█
[08:42:08][V][wifi:369]:   Priority: 0.0
[08:42:08][C][wifi:371]:   Channel: 6
[08:42:08][C][wifi:372]:   Subnet: 255.255.255.0
[08:42:08][C][wifi:373]:   Gateway: 192.168.0.1
[08:42:08][C][wifi:374]:   DNS1: 10.0.1.1
[08:42:08][C][wifi:375]:   DNS2: 1.1.1.1
[08:42:08][C][uptime.sensor:030]: Uptime Sensor 'Garage Freezer Uptime'
[08:42:08][C][uptime.sensor:030]:   State Class: ''
[08:42:08][C][uptime.sensor:030]:   Unit of Measurement: 's'
[08:42:08][C][uptime.sensor:030]:   Accuracy Decimals: 0
[08:42:08][C][uptime.sensor:030]:   Icon: 'mdi:timer-outline'
[08:42:08][V][uptime.sensor:030]:   Unique ID: '5002915fdc5c-uptime'
[08:42:08][C][logger:189]: Logger:
[08:42:08][C][logger:190]:   Level: VERBOSE
[08:42:08][C][logger:191]:   Log Baud Rate: 115200
[08:42:08][C][logger:192]:   Hardware UART: UART0
[08:42:08][C][logger:194]:   Level for 'app': DEBUG
[08:42:08][C][logger:194]:   Level for 'sensor': DEBUG
[08:42:08][C][dallas.sensor:072]: DallasComponent:
[08:42:08][C][dallas.sensor:073]:   Pin: GPIO5 (Mode: OUTPUT)
[08:42:08][C][dallas.sensor:074]:   Update Interval: 30.0s
[08:42:08][D][dallas.sensor:079]:   Found sensors:
[08:42:08][D][dallas.sensor:082]:     0xAE032197799CC128
[08:42:08][C][dallas.sensor:087]:   Device 'DS18B20 0xAE032197799CC128'
[08:42:08][C][dallas.sensor:087]:     Device Class: 'temperature'
[08:42:08][C][dallas.sensor:087]:     State Class: 'measurement'
[08:42:08][C][dallas.sensor:087]:     Unit of Measurement: '°C'
[08:42:08][C][dallas.sensor:087]:     Accuracy Decimals: 2
[08:42:08][V][dallas.sensor:087]:     Unique ID: 'dallas-AE032197799CC128'
[08:42:08][C][dallas.sensor:095]:     Address: 0xAE032197799CC128
[08:42:08][C][dallas.sensor:096]:     Resolution: 12
[08:42:08][C][captive_portal:148]: Captive Portal:
[08:42:08][C][ota:029]: Over-The-Air Updates:
[08:42:08][C][ota:030]:   Address: garage_freezer.[redacted]:8266
[08:42:08][C][ota:032]:   Using Password.
[08:42:08][C][api:095]: API Server:
[08:42:08][C][api:096]:   Address: garage_freezer.[redacted]:6053
[08:42:17][D][sensor:131]: 'Garage Freezer Uptime': Sending state 779.30798 s with 0 decimals of accuracy
[08:42:20][D][dallas.sensor:153]: 'DS18B20 0xAE032197799CC128': Got Temperature=-25.4°C
[08:42:20][D][sensor:131]: 'DS18B20 0xAE032197799CC128': Sending state -25.43750 °C with 2 decimals of accuracy
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DAVe3283**
# What does this implement/fix? 

The state_class of the uptime sensor was `''` (empty string), but should have been `total_increasing`. See esphome/issues#2337.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#2337

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** No docs changes needed

## Test Environment

- [ ] ESP32
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
esphome:
  name: garage_freezer
  comment: "Garage freezer temperature monitor"
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_pass
  domain: !secret iot_domain
  enable_mdns: false
  ap:
    password: !secret garage_freezer_ota

captive_portal:

api:
  password: !secret garage_freezer_api

ota:
  password: !secret garage_freezer_ota

logger:
  level: DEBUG

dallas:
  pin: D1
  update_interval: 30s

sensor:
  - platform: dallas
    id: ds18b20_ae032197799cc128
    name: "DS18B20 0xAE032197799CC128"
    address: 0xAE032197799CC128
    accuracy_decimals: 2
  - platform: uptime
    name: "Garage Freezer Uptime"
    id: uptime_sensor
    update_interval: 60s
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by oxan** [comment]
~~Actually, on second thought I'm not sure this is correct. If I look at the HA [devs docs](https://developers.home-assistant.io/blog/2021/08/16/state_class_total) it seems that `total_increasing` values should _never_ decrease. Uptime values certainly can decrease if you reboot your device.~~ Nevermind, I misunderstood.

**Comment by jesserockz** [comment]
`total_increasing` is not yet released in Home Assistant which is why it is not changed. (No sensors have `total_increasing` yet and it is a task I will go through and do after the release).

This PR is fine to add it, but wont be merged until after the HA release.

**Review by jesserockz — APPROVED** [review]

**Comment by DomiStyle** [comment]
@jesserockz The HA release is here and `total_increasing` is needed now in order to report energy usage to Home Assistant. Is this on the roadmap already for the .9 release or should I create a feature request for it?

**Comment by jesserockz** [comment]
The esphome integration in HA auto translates a sensor with state class: measurement and last_reset_type: auto to be total_increasing. 

But yes, it is on my list to do before the next esphome release.

**Comment by DomiStyle** [comment]
That didn't work for me on my template sensors, it still shows as measurement in HA.

But I'm not in a hurry so I'm just gonna wait for the next release, thanks.

**Pull request merged**
