### PR TITLE
Implement unit_of_measurement for number component

### PR DESCRIPTION
**Pull request by puuu**
# What does this implement/fix? 
This pull request add the `unit_of_measurement` to the number component. This only the MQTT part no native api code.

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1672

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
number:
  - platform: template
    name: My template number
    optimistic: true
    max_value: 100
    min_value: 0
    step: 5
    unit_of_measurement: '%'

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by oxan** [comment]
Any reason why you added this only the MQTT component? We don't really want to have configuration options that don't work with the native API.

**Comment by jesserockz** [comment]
Looks like HA number natively supports `unit_of_measurement`, so we can add it to the api code too.

**Comment by puuu** [comment]
> Any reason why you added this only the MQTT component?

Yes, I have no experience or testing capabilities for the native api. 
HA has `unit_of_measurement` support already integrated into the mqtt component.
I don't know the state of the native api. 

> We don't really want to have configuration options that don't work with the native API.

Neither do I and vice versa. 

Sorry, I didn't have time to review the native API implementation, I would appreciate someone else doing this. 

Just wanted to submit the esphome part and the mqtt-compononet part as implemented and tested.

**Comment by jesserockz** [comment]
I have added it to the native API in the above commits.

Please test that the mqtt version is still working as expected

**Comment by puuu** [comment]
@jesserockz thank you for adding api support. I can confirm that mqtt is still working.

**Review by oxan — APPROVED** [review]

**Pull request merged**
