### PR TITLE
Add PZEM004T/PZEMAC/PZEMDC Support

### LINKED ISSUE #49: New integration request: PZEM-004
**What new integration would you wish to have?**
- Peacefair PZEM-004
- Peacefair PZEM-004T (same, same but without housing and display)

**If possible, provide a link to an existing library for the integration:**
- https://github.com/olehs/PZEM004T
- https://halfforked.wordpress.com/2018/05/18/low-cost-house-power-monitoring-with-pzem-004-for-home-assistant/
- http://pdacontrolen.com/electricity-consumption-meter-peacefair-pzem-004-esp8266-arduino-nano/
- https://www.instructables.com/id/Power-Peacefair-PZEM-004-ESP8266-Arduino-Nano/

**Product link:**
- https://www.aliexpress.com/item/ANENG-4in1-Digital-Ammeter-Voltmeter-Watt-Power-Energy-Meter-AC-80-260V-100A-PZEM-004/32847092493.html

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't use esphomelib for my integrations :cry: 

**Additional context**
Want to measure the total energy consumption/load of a one-phase main connection in real time with esphomelib/yaml :+1:

### PR DESCRIPTION
**Pull request by OttoWinter**
## Description:

Credit goes to @tsunglung for creating the initial pzemac integration!

Usage:
```yaml
uart:
  tx_pin: <TX_PIN>
  rx_pin: <RX_PIN>
  baud_rate: 9600

sensor:
  - platform: pzem004t
    voltage:
      name: PZEM004T Voltage
    current:
      name: PZEM004T Current
    power:
      name: PZEM004T Power
```

Normal/python users: check out this branch with git to test; hass.io users: Add `"esphome_version": "pzem004t"` to your addon config

Only supports a single pzem004t at the moment; but I also don't see any boards with multiple chained pzems so this is probably ok

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/49

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by SeByDocKy** [comment]
Ho :) can we expect soon the other readings available from the PZem ? : power factor, active power, reactive power, total consummation, yesteday & day consummations ?

**Comment by OttoWinter** [comment]
@SeByDocKy The PZEM does not expose those values itself (at least in the documentation I've read) - except for total consumption. But all those can be created by simple template sensors and total_daily_energy.

**Comment by vicfergar** [comment]
Hi @OttoWinter. Do you think this PR is ready to merge? I am interested in PZEM016 support and I was planning to use this PR as reference.

**Comment by OttoWinter** [comment]
It is ready to merge when someone has successfully tested the cod here.

**Comment by SeByDocKy** [comment]
> It is ready to merge when someone has successfully tested the cod here.

I will test asap ... but I quit new in HASS... So actually I need to install manually the esphome/pzem-004T dev branch ?

**Comment by sendorm** [comment]
Is it possible to use the three different UART0, UART1 and UART2 serial interfaces with 3 different pzem004ts?

**Comment by richard-scott** [comment]
@OttoWinter @vicfergar  - maybe this will help:

https://github.com/arendst/Sonoff-Tasmota/blob/d0502c1af869100572f05d6e962d8969d6dbbe2f/sonoff/xnrg_05_pzem_ac.ino

**Comment by OttoWinter** [comment]
@sendorm You don't need to use those hw uarts either - (soft) UARTs attached to other pins will also work

@richard-scott I think this integration is already done... I don't see anything in that file that should concern this integration, could you elaborate. Just waiting for confirmation this actually works.

**Comment by sendorm** [comment]
@OttoWinter can you provide a sample code to connect 3 different pzem’s to one esp32?

**Comment by richard-scott** [comment]
@OttoWinter I was offering that up with a [solution ](https://github.com/arendst/Sonoff-Tasmota/blob/d0502c1af869100572f05d6e962d8969d6dbbe2f/sonoff/xnrg_05_pzem_ac.ino#L78-L83) for retrieving  power factor, active power, reactive power, total consummation, yesteday & day consummations for the PZEM016.

**Comment by OttoWinter** [comment]
@sendorm Yes that is possible - you just can't connect multiple PZEMs to the same uart bus atm.

```yaml
uart:
  - tx_pin: GPIOx
    rx_pin: GPIOy
    baud_rate: 9600
    id: bus1
  # Repeat

sensor:
  - platform: pzem004t
    uart_id: bus1
    # ..
  # Repeat
```

@richard-scott Ok, but that's 016, not 004(t)

**Comment by vicfergar** [comment]
> @OttoWinter @vicfergar - maybe this will help:
> 
> https://github.com/arendst/Sonoff-Tasmota/blob/d0502c1af869100572f05d6e962d8969d6dbbe2f/sonoff/xnrg_05_pzem_ac.ino

@richard-scott, I am familiar with the integrations of PZEMs in Tasmota. Thanks for the recommendation anyway :)

@OttoWinter that referenced file is for silly different piece of hardware from Peacefair. It use Modbus communication layer and should be used for [PZEM014](https://www.aliexpress.com/item/32872615068.html) and [PZEM016](https://es.aliexpress.com/item/32862049796.html)

**Comment by rradar** [comment]
@OttoWinter how could it be tested? It's not in the 'beta' branch nor in the 'dev' branch. I have the hassio addons and local pip install but don't have the pzem004t in it :eyes:

**Comment by OttoWinter** [comment]
@rradar See description

**Comment by rradar** [comment]
Sorry @OttoWinter was to blind to see this information.

> [14:45:10] INFO: Installing esphome version 'pzem004t' (https://github.com/esphome/esphome/archive/pzem004t.zip)...


Testing it and will report back! Will take a little bit because I still need to fiddle with the hardware...

**Comment by SeByDocKy** [comment]
What will be the max sampling rate with ESPhome ?

**Comment by rradar** [comment]
Update: I tested the pzem004t branch and made the following config:

```yaml
uart:
  tx_pin: D2
  rx_pin: D1
  baud_rate: 9600

sensor:
  - platform: pzem004t
    voltage:
      name: ${upper_devicename} Voltage
    current:
      name: ${upper_devicename} Current
    power:
      name: ${upper_devicename} Power
```

and tried on a esp8266 without luck. Don't get any output. With very_verbose logging on I get a continous

```
[VV][uart:230]:     Flushing...
[VV][uart:230]:     Flushing...
[VV][uart:230]:     Flushing...
```

**Comment by rradar** [comment]
New update with the latest changes from @ottowinter aka don't flush as much:

Still not working but more elaborated logs:


```yaml
[22:48:10][VV][component:128]: Running interval 'update':0 with interval=60000 last_execution=4294957417 (now=50124)
[22:48:10][VV][uart:159]:     Wrote 0b10110100 (0xB4)
[22:48:10][VV][uart:159]:     Wrote 0b11000000 (0xC0)
[22:48:10][VV][uart:159]:     Wrote 0b10101000 (0xA8)
[22:48:10][VV][uart:159]:     Wrote 0b00000001 (0x01)
[22:48:10][VV][uart:159]:     Wrote 0b00000001 (0x01)
[22:48:10][VV][uart:159]:     Wrote 0b00000000 (0x00)
[22:48:10][VV][uart:159]:     Wrote 0b00011110 (0x1E)
[22:48:11][VV][component:128]: Running interval '':0 with interval=10000 last_execution=41480 (now=51492)
[22:48:16][VV][api:597]: on_ping_request_
[22:48:21][VV][component:128]: Running interval '':0 with interval=10000 last_execution=51480 (now=61487)
[22:48:26][VV][api:597]: on_ping_request_
[22:48:28][VV][component:128]: Running interval 'update':0 with interval=60000 last_execution=8006 (now=68010)


[22:48:31][VV][component:128]: Running interval '':0 with interval=10000 last_execution=61480 (now=71494)
[22:48:36][VV][api:597]: on_ping_request_
[22:48:41][VV][component:128]: Running interval '':0 with interval=10000 last_execution=71480 (now=81491)
[22:48:46][VV][api:597]: on_ping_request_
[22:48:51][VV][component:128]: Running interval '':0 with interval=10000 last_execution=81480 (now=91492)
[22:48:56][VV][api:597]: on_ping_request_
[22:49:01][VV][component:128]: Running interval '':0 with interval=10000 last_execution=91480 (now=101493)
[22:49:02][VV][component:128]: Running interval 'update':0 with interval=60000 last_execution=41916 (now=101918)
[22:49:10][VV][component:128]: Running interval 'update':0 with interval=60000 last_execution=50121 (now=110132)
[22:49:10][VV][uart:159]:     Wrote 0b10110100 (0xB4)
[22:49:10][VV][uart:159]:     Wrote 0b11000000 (0xC0)
[22:49:10][VV][uart:159]:     Wrote 0b10101000 (0xA8)
[22:49:10][VV][uart:159]:     Wrote 0b00000001 (0x01)
[22:49:10][VV][uart:159]:     Wrote 0b00000001 (0x01)
[22:49:10][VV][uart:159]:     Wrote 0b00000000 (0x00)
[22:49:10][VV][uart:159]:     Wrote 0b00011110 (0x1E)
[22:49:11][VV][component:128]: Running interval '':0 with interval=10000 last_execution=101480 (now=111483)
[22:49:16][VV][api:597]: on_ping_request_
[22:49:21][VV][component:128]: Running interval '':0 with interval=10000 last_execution=111480 (now=121486)

[22:49:25][VV][preferences:046]: SAVE 32: 0=0x00000000 1=0x0DEFE4E3 (Type=233825507, CRC=0x0DEFE4E3)
[22:49:28][VV][component:128]: Running interval 'update':0 with interval=60000 last_execution=68006 (now=128018)
[22:49:31][VV][component:128]: Running interval '':0 with interval=10000 last_execution=121480 (now=131491)
[22:49:36][VV][api:597]: on_ping_request_
[22:49:41][VV][component:128]: Running interval '':0 with interval=10000 last_execution=131480 (now=141486)
[22:49:46][VV][api:597]: on_ping_request_
[22:49:51][VV][component:128]: Running interval '':0 with interval=10000 last_execution=141480 (now=151484)
[22:49:56][VV][api:597]: on_ping_request_
[22:50:01][VV][component:128]: Running interval '':0 with interval=10000 last_execution=151480 (now=161485)
[22:50:02][VV][component:128]: Running interval 'update':0 with interval=60000 last_execution=101916 (now=161926)

[22:50:10][VV][uart:159]:     Wrote 0b10110100 (0xB4)
[22:50:10][VV][uart:159]:     Wrote 0b11000000 (0xC0)
[22:50:10][VV][uart:159]:     Wrote 0b10101000 (0xA8)
[22:50:10][VV][uart:159]:     Wrote 0b00000001 (0x01)
[22:50:10][VV][uart:159]:     Wrote 0b00000001 (0x01)
[22:50:10][VV][uart:159]:     Wrote 0b00000000 (0x00)
[22:50:10][VV][uart:159]:     Wrote 0b00011110 (0x1E)
[22:50:11][VV][component:128]: Running interval '':0 with interval=10000 last_execution=161480 (now=171492)
[22:50:16][VV][api:597]: on_ping_request_
[22:50:21][VV][component:128]: Running interval '':0 with interval=10000 last_execution=171480 (now=181491)
[22:50:26][VV][api:597]: on_ping_request_
[22:50:28][VV][component:128]: Running interval 'update':0 with interval=60000 last_execution=128006 (now=188022)
[22:50:10][VV][uart:159]:     Wrote 0b10110100 (0xB4)
[22:50:10][VV][uart:159]:     Wrote 0b11000000 (0xC0)
[22:50:10][VV][uart:159]:     Wrote 0b10101000 (0xA8)
[22:50:10][VV][uart:159]:     Wrote 0b00000001 (0x01)
[22:50:10][VV][uart:159]:     Wrote 0b00000001 (0x01)
[22:50:10][VV][uart:159]:     Wrote 0b00000000 (0x00)
[22:50:10][VV][uart:159]:     Wrote 0b00011110 (0x1E)
[22:50:11][VV][component:128]: Running interval '':0 with interval=10000 last_execution=161480 (now=171492)
[22:50:16][VV][api:597]: on_ping_request_
[22:50:21][VV][component:128]: Running interval '':0 with interval=10000 last_execution=171480 (now=181491)
[22:50:26][VV][api:597]: on_ping_request_
[22:50:28][VV][component:128]: Running interval 'update':0 with interval=60000 last_execution=128006 (now=188022)
```

**Comment by OttoWinter** [comment]
@rradar Looks like the PZEM is not responding at all to what I think are perfectly valid packets. Could it be that the TX/RX pins are swapped?

**Comment by rradar** [comment]
Hi @OttoWinter I tried again with both configs (switching D1/D2 for TXT/RX) but no luck. I don't get any feedback. It's also for sure no hardware fault because the setup works with espurna right now.
The question is how can I debug further to help here? I think the device implementation of this one is known to be tricky or somewhat unreliable - but what in detail is beyond my knowledge.

**Comment by rradar** [comment]
Just for the record:

Today I found out that there is a new version (v3) of the pzem004t with a lot of chances. The old versions aren't produced anymore.

> Very Important Notification:
> 
> For this product PZEM-004T, we have the update version to replace the old version. The old version has been sold out and no produce anymore. The update information as following: 
> 
> 1. the new version has the same size and TTL port as before
> 
> 2. the software is new, we have English software as same as the PZEM-014,016, The communication protocol change to be Modbus–RTU, the display interface is changed. now it can test Voltage ,Current, Power, Power factor, Frequency and Energy 6 parameters.
> 
> 3. the new version has higher precision, faster refresh speed and the more stability communication than the old version.
> ...

Source: https://www.aliexpress.com/item/32707315880.html

**Comment by SeByDocKy** [comment]
I got both version V2 (TTL) & V3 (MODBUS)

**Comment by rradar** [comment]
@SeByDocKy could you successful test esphome on one of them? Is the protocol changed for v3 = new implantation needed?

**Comment by rradar** [comment]
@OttoWinter I checked everything once again and rewired even the pzem004t (you never no :wink:)

I can tell that it's still the same behavior for esphome (don't get any feedback from the pzem004t, logs up are still valid). I switched D1&D2 for RX&TX once again in software to be sure - same.

On the other hand I checked with espurna and tasmota. Both work on the same hardware stack, wiring and software serial. Hope this helps a bit to dig further and if I can assist with anything just drop a line..

**Comment by SeByDocKy** [comment]
> @SeByDocKy could you successful test esphome on one of them? Is the protocol changed for v3 = new implantation needed?

Sorry, I was a bit away.... I will test soon... for both V2 & V3. Stupid question, how to install this branch from homeassistant ?

**Comment by OttoWinter** [comment]
@SeByDocKy Please see PR header

@rradar I'm waiting for my own PZEM to arrive from china to test - it's definitely odd that the sensor does not appear to respond *at all*. Could you also share your exact settings from the other fws you tested with?

**Comment by rradar** [comment]
Sure @OttoWinter 

My board is a pzem004t v2.

For a test with espurna I used this image here (https://github.com/mcspr/espurna-nightly-builder/releases/download/20190501/espurna-1.13.6-dev.nightly20190501+gitbb33dfd1-nodemcu-pzem004t.bin). Device specific settings were made in the webfront console (menu entry: debug):

```
set pzemSoft 1
set pzemRX 4
set pzemTX 5
reset
```
hit enter after each command. And reboot the device.

For Tasmota I used this image here (http://thehackbox.org/tasmota/release/020402/sonoff-sensors.bin) and set the generic module in the webfront. Then for D1 and D2 I choosed pzemTX and pzem004RX, reboot and profit.

If you need more information I'm here :wink:

**Comment by rradar** [comment]
And by the way @OttoWinter: Watch out which version of the pzem004t you get. I'm not 100% but it looks like the latest available version (v.3) uses a different protocol which should be similar to the pzem016 as I read in some comments.

**Comment by brandond** [comment]
I just picked up two of the new v3 modules. The protocol seems to be pretty well documented.

**Comment by rradar** [comment]
Some interesting information from here: https://github.com/xoseperez/espurna/wiki/Sensor-PZEM004T

> **Sensor Behaviour**
Differently than the first implementation(See commit 3704d366637), this version(See PR #1304) pools device(s) magnitudes every PZEM004T_READ_INTERVAL. A magnitude of a device is read on each sensor tick. This will offload the main thread, as the PZEM004T can take up to 1000ms to answer the request. Same magnitudes are read one after another, so they can be better synced.

**Comment by bpmittal** [comment]
is there any progress in this PZEM integration with esphome , 
@ottoWinter did u got ur PZEM from china ?

**Comment by OttoWinter** [comment]
@brandond @bpmittal Yes, got mine, but haven't gotten around to testing yet.

@rradar It's not responding *at all*, so that's probably not it.

**Comment by SeByDocKy** [comment]
> @brandond @bpmittal Yes, got mine, but haven't gotten around to testing yet.
> 
> @rradar It's not responding _at all_, so that's probably not it.

Please take 10min to make you own testing... We are desperatly waiting this ESPhome integration  :)

**Comment by tsunglung** [comment]
[pzemac.diff.zip](https://github.com/esphome/esphome/files/3480037/pzemac.diff.zip)

I implement PZEMAC component, which can support PZEM014, PZEM016 and PZEM004T V3.0 which are using modbus protocol

yaml
`
sensor:
  - platform: pzemac
    frequency:
      name: PZEM004T Frequency
    voltage:
      name: PZEM004T Voltage
    current:
      name: PZEM004T Current
    power:
      name: PZEM004T Power 
    update_interval: 1s
`

logs:
`
[13:58:40][D][sensor:092]: 'PZEM004T Voltage': Sending state 115.10000 V with 1 decimals of accuracy
[13:58:40][D][pzemac:090]: Got Voltage 115.1 V
[13:58:40][D][sensor:092]: 'PZEM004T Current': Sending state 0.00000 A with 2 decimals of accuracy
[13:58:40][D][pzemac:093]: Got Current 0.00 A
[13:58:40][D][sensor:092]: 'PZEM004T Power': Sending state 0.00000 W with 1 decimals of accuracy
[13:58:40][D][sensor:092]: 'Total Daily Energy': Sending state 0.00000 Wh with 3 decimals of accuracy
[13:58:40][D][pzemac:096]: Got Power 2 W
[13:58:40][D][sensor:092]: 'PZEM004T Frequency': Sending state 60.00000  with 1 decimals of accuracy
[13:58:40][D][pzemac:099]: Got Frequency 60.0 Hz
[13:58:40][D][pzemac:102]: Got Power Factor 49
[13:58:40][D][pzemac:105]: Got Energy 47 Wh
[13:58:41][D][sensor:092]: 'PZEM004T Voltage': Sending state 115.10000 V with 1 decimals of accuracy
[13:58:41][D][pzemac:090]: Got Voltage 115.1 V
[13:58:41][D][sensor:092]: 'PZEM004T Current': Sending state 0.00000 A with 2 decimals of accuracy
[13:58:41][D][pzemac:093]: Got Current 0.00 A
[13:58:41][D][sensor:092]: 'PZEM004T Power': Sending state 0.00000 W with 1 decimals of accuracy
[13:58:41][D][sensor:092]: 'Total Daily Energy': Sending state 0.00000 Wh with 3 decimals of accuracy
[13:58:41][D][pzemac:096]: Got Power 2 W
[13:58:41][D][sensor:092]: 'PZEM004T Frequency': Sending state 60.00000  with 1 decimals of accuracy
[13:58:41][D][pzemac:099]: Got Frequency 60.0 Hz
[13:58:41][D][pzemac:102]: Got Power Factor 49
[13:58:41][D][pzemac:105]: Got Energy 47 Wh
`

**Comment by rradar** [comment]
@tsunglung any chance to get the pzem =<v2 supported? :cat2:

**Comment by tsunglung** [comment]
@rradar for pzem-004t <= v2, you can use pzem004t branch.

**Comment by fake-name** [comment]
Note that the new PZEM-004T (The version 3 ones) are *super* sensitive about stop bits. I had mine completely fail to respond when connected to a FT-232 set to use one stop bit. With two stop bits, it works fine. 

Also, the structure of the optoisolation means you can actually wire several devices in parallel, and as long as you configure the addresses beforehand, you can individually address them on the bus. 

Basically, the serial sensor->MCU is an open-collector output with a pullup. Since the individual modules don't respond unless they're specifically addressed, more then one device can happily coexist on the same bus. I've got 4 different PZEM devices bussed together (3 PZEM-004T V3.0, and a PZEM-017 that I've removed the RS-485 transciever from). You can poll them all with one serial interface.

Note that if you do this, the provided software does not work, since it's apparently hard-coded to only talk to the broadcast address (0xF8). When you do that, the response winds up being garbage, since all the responses get ORed together.

**Comment by rradar** [comment]
@tsunglung I tried this branch but it never worked till now :crying_cat_face:

**Comment by tsunglung** [comment]
@rradar from https://github.com/esphome/feature-requests/issues/49#issuecomment-508044394, this branch shall work. 
I suggest you get PZEM-004T V3.0. It is more accurate.

**Comment by kvvoff** [comment]
@OttoWinter
I wanted to check **pzem004t v1.0**, but when I set `"esphome_version": "pzem004t"` esphome does not start with error. 
This is what the log writes:

`[12:59:26] INFO: Starting ESPHome dashboard...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 11, in <module>
    load_entry_point('esphome==1.14.0.dev0', 'console_scripts', 'esphome')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/esphome/__main__.py", line 10, in <module>
    from esphome import const, writer, yaml_util
  File "/usr/local/lib/python2.7/dist-packages/esphome/writer.py", line 7, in <module>
    from esphome.config import iter_components
  File "/usr/local/lib/python2.7/dist-packages/esphome/config.py", line 15, in <module>
    from esphome import core, core_config, yaml_util
  File "/usr/local/lib/python2.7/dist-packages/esphome/core_config.py", line 6, in <module>
    import esphome.config_validation as cv
  File "/usr/local/lib/python2.7/dist-packages/esphome/config_validation.py", line 1242, in <module>
    Optional(CONF_COMMAND_TOPIC): All(requires_component('mqtt'), subscribe_topic),
  File "/usr/local/lib/python2.7/dist-packages/esphome/voluptuous_schema.py", line 198, in extend
    ret = super(_Schema, self).extend(schema, extra=extra)
  File "/usr/local/lib/python2.7/dist-packages/voluptuous/schema_builder.py", line 782, in extend
    return result_cls(result, required=result_required, extra=result_extra)
TypeError: __init__() got an unexpected keyword argument 'required'`

And so in a circle

Tested for: 
Home Assistant 0.98.4 on Pi3B+, Hassio addon ESPHome 1.13.6 and dev
and Home Assistant 0.97.2 on Debian9, Hassio addon ESPHome 1.13.6 and dev

**Comment by Fusseldieb** [comment]
Guys, let the dev breathe! I know, everyone wants it, me including, as I already bought one and am awaiting arrival, but... he's getting bombarded with the same questions over and over.

It's not done yet! It doesn't work reliably yet, please **wait**!

Thank you.

**Comment by Spirituss** [comment]
Looking forward to working version!

**Comment by hannesbe** [comment]
> @OttoWinter
> I wanted to check **pzem004t v1.0**, but when I set `"esphome_version": "pzem004t"` esphome does not start with error.
> This is what the log writes:

This worked for me at first, but since a while I'm getting the same log output. 
I'm not sure how to use the linked zip file in hassio, from the more recently suggested option.

**Comment by Fusseldieb** [comment]
> I'm not sure how to use the linked zip file in hassio, from the more recently suggested option.

From what I've read, **diff** files are only the changes made in a repository. That means that you should download the branch with the command "git clone <repository link>" and then do this [described here](https://stackoverflow.com/a/12320940/3525780)

**Comment by Spirituss** [comment]
@Fusseldieb And what do you propose for those who use Esphome as HASS.io add-on?

**Comment by rradar** [comment]
@tsunglung could you pack your latest code in a pull request? A new release is coming and I would love to see this one here included! :rocket:

**Comment by Fusseldieb** [comment]
> @tsunglung could you pack your latest code in a pull request? A new release is coming and I would love to see this one here included! 🚀

Please make this happen! :D

**Comment by rradar** [comment]
Does this one here includes support for pzem004t **v1**.x and **v2**.x? :eyes:

**Comment by OttoWinter** [comment]
Yes.

**Comment by randybb** [comment]
What about multiple boards chained together, with different addresses? I want to use 12 of these in one distribution panel.

**Comment by randybb** [comment]
What about multiple boards chained together, with different addresses? I want to use 12 of these in one distribution panel.

**Comment by OttoWinter** [comment]
Yes, with pzemac integration definitely. For PZEM004T-V1 probably not (if I understand my code correctly).

**Pull request merged**
