### PR TITLE
Leds - keep power supply on during effect

### PR DESCRIPTION
**Pull request by Elkropac**
## Description:
When using fastled component with power_supply component, I have noticed, that when you use light effect with periods of "no leds on" (ie. fireworks) , then power supply gets many requests to shutdown and power up (it is covered by keep_on_time, so it never actually shutdowns). This is because it iterates over all LEDs on every spark and it periodicaly finds all LEDs in off state.

To fix that, i have added condition (depending on new config option, to keep old behavior by default) to keep power supply on, when there is effect in progress. It skips itteration over LEDs.

It has a flaw - when you keep effect on a set brightness to 0 , it does not shut down the power supply. I don't know, how to get to value of brightnes.

I will add pull request on docs, if you merge this

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
I think the current behavior is correct - when no power is used (=no leds are on), the power supply should turn off. Plus as you say this is anyway not a problem because of the keep_on time check (which is also user-configurable).

Please explain why this is needed first.

**Comment by Elkropac** [comment]
My motivation was to save CPU cycles, cause by looping over LEDs on every effect change.

I guess, fireworks effect is special, because,in most cases, it has to loop over many LEDs to find first light up LED.
When I used it for first time, my debug console was flooded with messages "Enabling power supply.".

**Comment by OttoWinter** [comment]
@Elkropac 

loop cycles is not an issue here - the looping over the array and checking against 0 will not be a real issue.

If it's flooded with log messages then that's a bug, no need to add this here. Check the latest dev branch, some of the changes there might have fixed the issue.

**Comment by Elkropac** [comment]
Ah, you reworked it totally.

There is still output from power source switching, but i guess it will go away once i stop using debug log level.

Thank you

**Pull request closed without merging**
