### PR TITLE
Add AEHA IR Protocol

### PR DESCRIPTION
**Pull request by hazi**
# What does this implement/fix?

This change corresponds to the infrared remote control signal as defined by the Japanese Home Appliance Association.
AEHA = [Association for Electric Home Appliance](https://www.aeha.or.jp) (Kaseikyo, 家製協, 家電製品協会)

The AEHA standard is upward compatible with Panasonic.
The current `remote_transmitter.transmit_panasonic` does not work well with non-Panasonic products due to capacity limitations and signal settings that are out of specification.

If this AEHA format is adopted, `remote_transmitter.transmit_panasonic` should be unnecessary. I could not determine if it should be removed.

The following are the Japanese manufacturers that use the AEHA format as far as I have been able to ascertain.

- SANYO Electric Co., Ltd.
- SHARP
- DAIKIN
- Panasonic
- Mitsubishi Electric
- Mitsubishi Heavy Industries, Ltd.
- FUJITSU GENERAL LIMITED
- Hitachi, Ltd.

### Format

- Carrier: Infrared (λp = 950nm)
- Subcarrier: fsc = 33 to 40kHz (38kHz typ.), 1/3duty
- T = 350 to 500μs (425μs typ.)
- 16-bit customer code + 4-bit parity
- Variable length frame (48bit typ.), trailer terminated

format
via http://elm-chan.org/docs/ir_format.html

- Since some manufacturers do not use parity, this code lumps them together as data.
- The maximum size of DATA has been set to 35 bytes. The maximum size of the data is 35 bytes, which is the result of analyzing a lot of raw IR codes on the Internet.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

<h2> Example entry for `config.yaml`:</h2>

<details>
<summary>Click to view YAML</summary>

```yaml
esphome:
  name: esp-ir-dev

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "****"

ota:
  password: "****"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Ir-Dev Fallback Hotspot"
    password: "****"

captive_portal:

# GPIO  Component     Description
# 04    LED1i (52)    Blue LED - Link status
# 05    IRrecv (51)   IR Receiver
# 13    Button1 (17)  Button
# 14    IRsend (8)    IR Transmitter

remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 30%

remote_receiver:
  id: rcvr
  pin:
    number: GPIO5
    inverted: True
  tolerance: 30%
  dump:
    - raw
    - panasonic
    - aeha
  idle: 10ms
  buffer_size: 2kb

button:
  - platform: template
    name: "Example IR Code"
    id: example
    internal: true
    on_press:
      - logger.log: "Panasonic sample from the ESPHome documentation [Panasonic]"
      - remote_transmitter.transmit_panasonic:
          address: 0x1FEF
          command: 0x1F3E065F

      - delay: 300ms
      - logger.log: ""
      - logger.log: "Panasonic sample from the ESPHome documentation [AEHA]"
      - remote_transmitter.transmit_aeha:
          address: 0x1FEF
          data: [0x1F, 0x3E, 0x06, 0x5F]

      - delay: 300ms
      - logger.log: ""
      - logger.log: "Daikin air purifier transmitting two codes [RAW]"
      - remote_transmitter.transmit_raw:
          carrier_frequency: 38kHz
          code: [3482, -1732, 446, -1288, 446, -422, 444, -422, 442, -422, 442, -1288, 446, -448, 418, -422,  444, -424, 442, -448, 418, -1288, 446, -422, 444, -1288, 446, -1288, 446, -424, 442, -1288,  444, -1288, 446, -1288, 446, -1288, 446, -1288, 446, -448, 418, -1288, 444, -448, 418, -448,  416, -1290, 444, -448, 416, -450, 414, -450, 414, -452, 412, -1320, 414, -1320, 412, -1322,  412, -1320, 412, -454, 412, -452, 412, -454, 412, -454, 412, -454, 412, -454, 412, -454,  410, -454, 412, -454, 412, -454, 412, -454, 412, -454, 412, -454, 412, -454, 412, -454,  412, -454, 412, -454, 412, -454, 412, -454, 412, -454, 412, -454, 412, -454, 412, -454,  412, -454, 412, -454, 412, -1322, 412, -454, 412, -454, 412, -1322, 412, -1322, 412, -1322,  412, -454, 412,  -29846,  3448, -1766, 412, -1322, 412, -454, 410, -454, 412, -454, 412, -1322, 410, -454, 412, -454,  412, -454, 412, -454, 412, -1322, 412, -454, 412, -1322, 412, -1322, 412, -454, 412, -1322,  412, -1322, 412, -1322, 412, -1322, 412, -1322, 412, -454, 412, -1322, 410, -454, 412, -454,  412, -1322, 412, -454, 412, -454, 410, -454, 412, -454, 410, -454, 412, -452, 412, -454,  412, -454, 412, -1322, 410, -1322, 412, -1322, 410, -1322, 410, -454, 410, -454, 410, -454,  412, -1322, 410, -1324, 410, -454, 412, -454, 410, -454, 410, -454, 412, -454, 410, -454,  412, -454, 410, -454, 412, -454, 410, -454, 412, -454, 412, -454, 410, -454, 412, -454,  410, -456, 410, -454, 410, -1324, 412, -454, 410, -454, 412, -1322, 412, -454, 410, -454,  412, -452, 410]

      - delay: 300ms
      - logger.log: ""
      - logger.log: "Daikin air purifier transmitting two codes [AEHA]"
      - remote_transmitter.transmit_aeha:
          address: 0x885B
          data: [0xE9,0x0F,0x00,0x00,0x00,0x4E]
      - delay: 30ms
      - remote_transmitter.transmit_aeha:
          address: 0x885B
          data: [0xE9,0x00,0xF1,0x80,0x00,0x48]

      - delay: 300ms
      - logger.log: ""
      - logger.log: "Hitachi Climate power on [RAW]"
      - remote_transmitter.transmit_raw:
          carrier_frequency: 38kHz
          code: [3302, -1690, 416, -1248, 442, -494, 442, -468, 416, -520, 442, -468, 442, -494, 416, -494, 442, -468, 416, -520, 442, -468, 468, -468, 416, -494, 416, -1274, 468, -468, 416, -494, 442, -468, 442, -494, 416, -494, 416, -520, 416, -494, 416, -520, 416, -494, 416, -494, 416, -520, 442, -468, 416, -520, 416, -494, 442, -494, 442, -468, 442, -494, 442, -1248, 416, -494, 442, -1248, 416, -1248, 442, -1248, 442, -1222, 416, -1274, 416, -1274, 442, -468, 442, -1248, 442, -1248, 442, -1222, 442, -1248, 442, -1248, 416, -1248, 442, -1248, 416, -1274, 416, -1248, 416, -520, 468, -442, 442, -494, 442, -468, 416, -520, 416, -494, 442, -468, 442, -494, 442, -468, 442, -494, 442, -1248, 416, -1248, 416, -520, 442, -468, 442, -1248, 416, -1274, 416, -1248, 442, -1248, 442, -468, 468, -468, 416, -1248, 442, -1248, 442, -494, 442, -468, 416, -520, 390, -1274, 442, -494, 468, -442, 442, -1248, 416, -520, 416, -494, 442, -1248, 442, -1222, 442, -494, 442, -1248, 416, -1248, 442, -494, 416, -1274, 416, -1248, 416, -520, 442, -1222, 416, -1274, 442, -494, 416, -494, 468, -1222, 442, -468, 416, -494, 416, -494, 442, -494, 442, -468, 442, -1248, 416, -1274, 416, -494, 442, -1248, 416, -1274, 442, -1222, 390, -520, 416, -494, 442, -494, 442, -1248, 416, -494, 416, -1274, 416, -1274, 416, -494, 416, -1274, 416, -1248, 442, -1248, 416, -520, 442, -1222, 442, -494, 442, -468, 442, -1248, 442, -494, 442, -468, 442, -468, 416, -520, 468, -442, 442, -494, 416, -494, 442, -494, 416, -1248, 442, -1248, 442, -1248, 416, -1248, 416, -1274, 442, -1222, 442, -1248, 442, -1248, 442, -468, 442, -494, 416, -494, 468, -442, 416, -520, 468, -442, 468, -468, 442, -468, 442, -1248, 442, -1222, 416, -1274, 442, -1248, 416, -1274, 416, -1248, 416, -1274, 416, -1248, 442, -494, 468, -442, 442, -494, 416, -494, 442, -494, 390, -520, 416, -520, 390, -520, 442, -1248, 442, -1222, 416, -1274, 416, -1248, 416, -1274, 442, -1248, 416, -1248, 442, -1248, 416, -520, 390, -520, 416, -494, 468, -468, 468, -442, 416, -520, 416, -494, 416, -520, 390, -1274, 442, -1248, 416, -1248, 442, -1248, 442, -1248, 390, -1274, 416, -1274, 416, -1274, 416, -494, 416, -494, 416, -520, 416, -494, 442, -494, 468, -442, 416, -520, 416, -494, 416, -1274, 442, -1222, 442, -1248, 416, -1274, 416, -1248, 442, -1248, 442, -1248, 390, -1274, 416, -1274, 442, -1248, 390, -520, 442, -494, 416, -1248, 416, -520, 416, -1274, 416, -494, 442, -494, 390, -520, 442, -1248, 416, -1248, 416, -520, 416, -1274, 442, -468, 442, -1248, 442, -1248, 416, -468, 442, -494, 416, -494, 468, -1222, 442, -1248, 390, -1274, 442, -1248, 416, -494, 442, -1248, 416, -1274, 416, -1248, 442, -494, 416, -494, 442, -494, 416, -494, 416, -520, 468, -442, 416, -520, 390, -520, 442, -468, 416, -520, 416, -494, 416, -520, 442, -1222, 416, -1274, 416, -1274, 390, -1274, 416, -1274, 416, -1274, 442, -1222, 416, -1274, 416, -520, 390, -520, 416, -520, 416, -494, 416, -494, 442, -494, 416, -494, 442, -494, 416, -1274, 390, -1274, 416, -1274, 416, -1248, 416, -1274, 416, -1274, 390, -1274, 416, -1274, 416, -494, 468, -468, 416, -494, 416, -520, 390, -520, 416, -520, 416, -494, 416, -520, 390, -1274, 416, -1274, 442, -1248, 390, -1274, 416, -1274, 416, -1248, 416, -1274, 416, -1274, 416, -494, 416, -520, 390, -520, 416, -520, 390, -520, 390, -520, 416, -520, 416, -494, 416, -1274, 416, -1274, 364, -1300, 416, -1274, 416, -1248, 390, -1300, 390, -1300, 416, -1274, 390, -2054, 78]

      - delay: 300ms
      - logger.log: ""
      - logger.log: "Hitachi Climate power on [AEHA]"
      - remote_transmitter.transmit_aeha:
          address: 0x8008
          data: [0x00, 0x02, 0xFD, 0xFF, 0x00, 0x33, 0xCC, 0x49, 0xB6, 0xC8, 0x37, 0x16, 0xE9, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0xCA, 0x35, 0x8F, 0x70, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF, 0x00, 0xFF]

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "GPIO button"
    internal: true
    on_release:
      - button.press: example

output:
  - platform: esp8266_pwm
    id: esphome_ir1_led
    pin:
      number: GPIO4
      inverted: false

light:
  - platform: monochromatic
    name: "Blue LED"
    output: esphome_ir1_led
    id: light_led
    restore_mode: RESTORE_DEFAULT_ON
```
</details>

In this configuration,`remote_receiver.tolerance ` is set to `30%`.
Most of the codes were decode at 25%, but only Hitachi Climate needed to be coded at 30%.

We are testing whether we can actually send and receive by pressing this ESP button.
The following is the execution log when the button is pressed.
I have confirmed that sending and receiving are working fine.

```log
[D][binary_sensor:036]: 'GPIO button': Sending state ON
[D][binary_sensor:036]: 'GPIO button': Sending state OFF
[D][button:013]: 'Example IR Code' Pressed.
[D][main:1295]: Panasonic sample from the ESPHome documentation [Panasonic]
[D][remote_transmitter:075]: Sending remote code...
[D][remote.panasonic:070]: Received Panasonic: address=0x1FEF, command=0x1F3E065F
[D][remote.aeha:099]: Received AEHA: address=0x1FEF, data=[0x1F,0x3E,0x06,0x5F]
[D][main:1306]: 
[D][main:1309]: Panasonic sample from the ESPHome documentation [AEHA]
[D][remote_transmitter:075]: Sending remote code...
[D][remote.panasonic:070]: Received Panasonic: address=0x1FEF, command=0x1F3E065F
[D][remote.aeha:099]: Received AEHA: address=0x1FEF, data=[0x1F,0x3E,0x06,0x5F]
[D][main:1320]: 
[D][main:1323]: Daikin air purifier transmitting two codes [RAW]
[D][remote_transmitter:075]: Sending remote code...
[D][remote.panasonic:070]: Received Panasonic: address=0x885B, command=0xE90F0000
[D][remote.aeha:099]: Received AEHA: address=0x885B, data=[0xE9,0x0F,0x00,0x00,0x00,0x4E]
[D][remote.panasonic:070]: Received Panasonic: address=0x885B, command=0xE900F180
[D][remote.aeha:099]: Received AEHA: address=0x885B, data=[0xE9,0x00,0xF1,0x80,0x00,0x48]
[D][main:1335]: 
[D][main:1338]: Daikin air purifier transmitting two codes [AEHA]
[D][remote_transmitter:075]: Sending remote code...
[D][remote.panasonic:070]: Received Panasonic: address=0x885B, command=0xE90F0000
[D][remote.aeha:099]: Received AEHA: address=0x885B, data=[0xE9,0x0F,0x00,0x00,0x00,0x4E]
[D][remote_transmitter:075]: Sending remote code...
[D][remote.panasonic:070]: Received Panasonic: address=0x885B, command=0xE900F180
[D][remote.aeha:099]: Received AEHA: address=0x885B, data=[0xE9,0x00,0xF1,0x80,0x00,0x48]
[D][main:1357]: 
[D][main:1360]: Hitachi Climate power on [RAW]
[D][remote_transmitter:075]: Sending remote code...
[D][remote.aeha:099]: Received AEHA: address=0x8008, data=[0x00,0x02,0xFD,0xFF,0x00,0x33,0xCC,0x49,0xB6,0xC8,0x37,0x16,0xE9,0x00,0xFF,0x00,0xFF,0x00,0xFF,0x00,0xFF,0x00,0xFF,0xCA,0x35,0x8F,0x70,0x00,0xFF,0x00,0xFF,0x00,0xFF,0x00,0xFF]
[D][main:1372]: 
[D][main:1375]: Hitachi Climate power on [AEHA]
[D][remote_transmitter:075]: Sending remote code...
[D][remote.panasonic:070]: Received Panasonic: address=0x8008, command=0x0002FDFF
[D][remote.aeha:099]: Received AEHA: address=0x8008, data=[0x00,0x02,0xFD,0xFF,0x00,0x33,0xCC,0x49,0xB6,0xC8,0x37,0x16,0xE9,0x00,0xFF,0x00,0xFF,0x00,0xFF,0x00,0xFF,0x00,0xFF,0xCA,0x35,0x8F,0x70,0x00,0xFF,0x00,0xFF,0x00,0xFF,0x00,0xFF]
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
LGTM. Thanks

**Comment by hazi** [comment]
@jesserockz Thanks for the review.

Let me check one thing.

> The AEHA standard is upward compatible with Panasonic.
> The current `remote_transmitter.transmit_panasonic` does not work well with non-Panasonic products due to capacity limitations and signal settings that are out of specification.
> 
> If this AEHA format is adopted, `remote_transmitter.transmit_panasonic` should be unnecessary. I could not determine if it should be removed.

> [D][remote.panasonic:070]: Received Panasonic: address=0x1FEF, command=0x1F3E065F
> [D][remote.aeha:099]: Received AEHA: address=0x1FEF, data=[0x1F,0x3E,0x06,0x5F]


Is it ok if I don't delete it, even though it will duplicate the functionality of `remote_transmitter.transmit_panasonic`


Modify this PR and documentation if necessary.

**Comment by hazi** [comment]
@jesserockz Sorry for the correction after the review.
Corrected commitments added.
I checked the remote control signal of the fan I bought today and found that the data value is only 16 bits.
image

I fixed esphome-docs as well 
https://github.com/esphome/esphome-docs/pull/2246

**Comment by jesserockz** [comment]
> Is it ok if I don't delete it, even though it will duplicate the functionality of remote_transmitter.transmit_panasonic

There is no need to touch the current panasonic code. That would be a breaking change and it already works for people that already using it.

**Pull request merged**
