### PR TITLE
Implemented m5stack4relay

### PR DESCRIPTION
**Pull request by KoenBreeman**
# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [(https://github.com/esphome/feature-requests/issues/2184)]

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4121

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
external_components:
  - source: github://pr#4786
    components: m5stack4relay

i2c:
  sda: 26
  scl: 32
  scan: True
  id: bus_a

m5stack4relay:
  id: M5stackrelay_ID1
  i2c_id: bus_a

switch:
  - platform: m5stack4relay
    id: relay_1
    name: relay1
    channel: 1
    m5stack4relay_id: M5stackrelay_ID1
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by KoenBreeman** [comment]
Everything is tested

**Comment by randybb** [comment]
Just tested and everything seems to work, thanks! Just one thing - since it is not possible to control LEDs independently maybe it would be better to change _channel_ from a string relay_1 - relay_4 to an integer 1-4.

**Comment by KoenBreeman** [comment]
> Just tested and everything seems to work, thanks! Just one thing - since it is not possible to control LEDs independently maybe it would be better to change _channel_ from a string relay_1 - relay_4 to an integer 1-4.

Hi Randy

I updated the code, now you should enter 1-4 as channel.

**Comment by randybb** [comment]
Thanks! Just tested, now it is in hands of our 🧙.

**Comment by lboue** [comment]
Can you merge this PR?

**Comment by KoenBreeman** [comment]
> Can you merge this PR?

I would like that as well. However only authorized people can do this. And I’m not authorized.

**Comment by KoenBreeman** [comment]
Can someone tell me when this implementation will be reviewed?

**Comment by Daniel-dev22** [comment]
> Can someone tell me when this implementation will be reviewed?

Would be good to know as well.

**Comment by freddiebd** [comment]
+1

**Comment by KoenBreeman** [comment]
Created new documentation, since the old one was incorrect, so it should be ok now.

**Comment by randybb** [comment]
You need to rework tests as these have been changed - there are now files for each platform.
Hope it will be merged as there is a loot of modules from seeedstudio, then why not M5Stack :)

**Comment by KoenBreeman** [comment]
Hi Randy

I saw that, trying to fix it right now

**Comment by KoenBreeman** [comment]
Created new pull request, since this one is full of errors.
https://github.com/esphome/esphome/pull/7234

**Pull request closed without merging**
