### PR TITLE
Use Clang 11

### PR DESCRIPTION
**Pull request by agners**
# What does this implement/fix? 

This moves clang-format and clang-tidy to use LLVM/Clang 11.

This requires the base lint container to be updated first: https://github.com/esphome/esphome-docker-base/pull/20

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [ ] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

# Explain your changes

Describe your changes here to communicate to the maintainers **why we should accept this pull request**.
Very important to fill if no issue linked

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by agners** [comment]
From my testing it seems that the new version of `clang-format` largely formats things the same way. When formatting the whole tree there are only 4 files modified:

```
esphome/components/mqtt/mqtt_client.cpp
esphome/components/mqtt_subscribe/sensor/mqtt_subscribe_sensor.cpp
esphome/components/mqtt_subscribe/text_sensor/mqtt_subscribe_text_sensor.cpp
esphome/core/helpers.h
```

Not sure what we should do with those, I was thinking to just leave as is so it will get reformatted once somebody works on that code. Alternatively I could reformat them as part of this or a separate PR.

For `clang-tidy` this change currently disables all the new checks to make it not complain anything new. I have a list of checks I want to reenable, but I am planning to do those as separate PRs once the infrastructure is up.

**Comment by OttoWinter** [comment]
> Not sure what we should do with those, I was thinking to just leave as is so it will get reformatted once somebody works on that code. Alternatively I could reformat them as part of this or a separate PR.

Leaving them is not really an option, as otherwise the CI checks will always fail. I'd say let's reformat them here, it's only few files anyway.

Note that https://github.com/esphome/esphome/pull/1828/files#diff-24ad71c8613ddcf6fd23818cb3bb477a1fb6d83af4550b0bad43099813088686R55 will also need to be updated once that PR is merged.

**Comment by agners** [comment]
> Leaving them is not really an option, as otherwise the CI checks will always fail. I'd say let's reformat them here, it's only few files anyway.

Ok, I'll add the clang-format changes to this PR.

Note that there is another problem: https://github.com/esphome/esphome-docker-base/pull/20#issuecomment-856990948.

**Comment by agners** [comment]
The clang-lint/clang-tidy runs fail since the esphome-lint container hasn't been updated yet to get shipped with clang-11.

Maybe now that we have clang-7 and clang-11 in one container we could do that step in a separate PR so this PR will turn green before merging?

**Comment by OttoWinter** [comment]
> Maybe now that we have clang-7 and clang-11 in one container we could do that step in a separate PR so this PR will turn green before merging?
done :) https://github.com/esphome/esphome/pull/1879
If you rebase the PR I think this should be ready for merge :star_struck:

**Review by OttoWinter — APPROVED** [review]
Thanks! :rocket:

**Comment by agners** [comment]
Thanks for your help getting this merged! I have some follow up PRs with easy fixes which allows to re-enable some of the checks.

**Pull request merged**
