### PR TITLE
Adafruit qtpy esp32

### PR DESCRIPTION
**Pull request by jenscski**
# What does this implement/fix?

This let ESPHome support chips like ESP32 Pico, which have a different pin schema than the regular ESP32.
E.g. several pins used by ESP32 Pico is blocked by ESPHome as they are used by the flash interface in regular ESP32.

This is implemented by checking if the pin used is defined in the board definition, if it's defined there, it's not checked for reserved usage defined in the ESPHome core.

This PR also includes board definition for the [Adafruit QT Py ESP32 Pico](https://www.adafruit.com/product/5395)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esphome:
  name: pr3997
  on_boot:
    - light.turn_on:
        id: status_led
        brightness: 25%
        red: 1
        green: 0
        blue: 1

esp32:
  board: adafruit_qtpy_esp32
  framework:
    type: arduino
    version: 2.0.5
    platform_version: 5.2.0

external_components:
  - source: github://pr#3997
    components: [ esp32 ]

switch:
  - platform: gpio
    name: "NeoPixel Power"
    internal: true
    pin: NEOPIXEL_POWER
    restore_mode: ALWAYS_ON

light:
  - platform: neopixelbus
    name: "NeoPixel Light"
    internal: true
    id: status_led
    type: GRB
    variant: WS2812X
    pin: NEOPIXEL
    num_leds: 1

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
Happy with the specific change to allow specified pins to be used.

Please don't add all the extra boards though as this list needs to stay in sync with the current recommended platform version ESPHome uses. The list will be syncronised when the platform version is updated (#3564).

**Comment by jenscski** [comment]
> Please don't add all the extra boards though as this list needs to stay in sync with the current recommended platform version ESPHome uses. The list will be syncronised when the platform version is updated (#3564).

That make sense, but, to use the [Adafruit QT Py ESP32 Pico](https://www.adafruit.com/product/5395) in ESPHome, it need to be defined in boards.py, unfortunately for me, this is added in a later version than the one who is current for ESPHome.

Do you know if there is any way of doing this the correct way?

**Comment by jesserockz** [comment]
I see, We could merge the changes in `gpio.py` without the addition of new boards for now, and those will have to wait until after #3564 is merged which I should be getting to once the next release is out the door.

**Comment by jenscski** [comment]
Replaced by https://github.com/esphome/esphome/pull/3999

Board definition for https://www.adafruit.com/product/5395 in separate PR later

**Comment by jesserockz** [comment]
@jenscski Please make a new PR with the pin definitions now that #3564 and #4056 are merged

**Pull request closed without merging**
