### PR TITLE
Setup the mute pin if configured

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix?

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by Jason-nz** [comment]
Confirmed this works on the Muse proto using

```
external_components:
  - source: github://pr#3568
    components: [i2s_audio]
    refresh: 0s
```
Without this PR there is no sound after a power cycle

**Comment by jesserockz** [comment]
Thanks for confirming @Jason-nz

**Comment by renaiku** [comment]
@Jason-nz I updated to 2022.6.1 and I still have no sound outputting from the Muse proto (onboard speaker) with the folllowing config in esphome:

```yaml
substitutions:
  name: raspiaudio-muse-proto-xxxxxx
  friendly_name: "RaspiAudio Muse Proto XXXXXX"
  wifi_ap_password: ""

esphome:
  name: "${name}"
  name_add_mac_suffix: false

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

logger:
api:
ota:

dashboard_import:
  package_import_url: github://esphome/media-players/raspiaudio-muse-proto.yaml@main

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

improv_serial:

media_player:
  - platform: i2s_audio
    id: media_out
    name: ${friendly_name}
    dac_type: external
    i2s_lrclk_pin: GPIO25
    i2s_dout_pin: GPIO26
    i2s_bclk_pin: GPIO5
    mode: mono
    mute_pin: 
      number: GPIO21
      inverted: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      inverted: true
    name: ${friendly_name} Button
    on_click:
      - media_player.toggle: media_out

light:
  - platform: fastled_clockless
    name: ${friendly_name}
    pin: GPIO22
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
```

Does your proto onboard speaker emit sound ? (I can hear the speaker emiting a small noise at volume 0 like every speaker "skrch skrch") or do you use an external speaker ?

**Comment by Jason-nz** [comment]
I have 2, one arrived without the onboard speaker working, the other works as expected. 
Have you tried an external speaker? 

From what I can tell, the onboard speaker is hard wired and can only be disabled by cutting a trace on the back. So if you have sound with an external speaker then you might have a faulty onboard speaker.

Please reply on discord https://discord.gg/KhAMKrd

**Pull request merged**
