### PR TITLE
Add MCP4725 DAC Component

### LINKED ISSUE #1031: Support for mcp4725 - 3.3v 12 bit i2c dac with EEPROM
Hello, we are about to release a new i/o board that includes among all other chips already supported by Tasmota mcp4725 for dual or quad 0-10v output ( mainly for valves, dimmers, fan with 0-10v input )

It is possible to add support to tasmota? 

If dev requires so, we can ship him a board prototype for tests and development/integration.

Thank You

[MCP4725.pdf](https://github.com/esphome/feature-requests/files/5642608/MCP4725.pdf)

### PR DESCRIPTION
**Pull request by JJK801**
## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1031

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#889

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
GTM when codeowners and test added, docs too, thanks!

**Comment by glmnet** [comment]
Thanks!!

**Comment by JJK801** [comment]
Thanks to you @glmnet, i planned to add tests but i was too busy last month :+1:

**Comment by alex-shaw** [comment]
Wanted to leave my thanks also - Im also keen to use this peripheral!

**Pull request merged**
