### PR TITLE
Extend uart: with rx_buffer_size:

### PR DESCRIPTION
**Pull request by ayufan**
This allows to configure `rx_buffer_size:`
to efficiently receive big payloads over UART.

The default value for ESP8266 and ESP32 seems to be `256`.
We keep that.

This is needed for https://github.com/esphome/esphome/pull/956.

## Description:

```yaml
uart:
  - id: adalight_uart
    tx_pin: TX
    rx_pin: RX
    rx_buffer_size: 512
    baud_rate: 115200
```

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** https://github.com/esphome/esphome-docs/pull/528

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by ayufan** [comment]
@brandond Can you take a look?

**Comment by glmnet** [comment]
Does this makes sense for both software and serial uarts?

**Comment by ayufan** [comment]
@glmnet I think for the sake of consistency it makes sense.

**Comment by glmnet** [comment]
it's gonna need some docs

**Comment by ayufan** [comment]
@glmnet https://github.com/esphome/esphome-docs/pull/528?

**Comment by glmnet** [comment]
can you check the build errors?

**Comment by xheronimo** [comment]
hello in uart.h to date 14 november 2019
The definition of size to rx_buffer is 512

  uint32_t bit_time_{0};
  uint8_t *rx_buffer_{nullptr};
  size_t rx_buffer_size_{512};

**Comment by glmnet** [comment]
> hello in uart.h to date 14 november 2019
> The definition of size to rx_buffer is 512
> 
> uint32_t bit_time_{0};
> uint8_t *rx_buffer_{nullptr};
> size_t rx_buffer_size_{512};

indeed, that 512 must go away, we don't initialize fields which are always initialized by the code generation part, which should be the case from now on

**Comment by glmnet** [comment]
@ayufan this one got in conflict and is blocked by docs not being on next branch. Would you like to fix all this?

**Comment by ayufan** [comment]
Yes! I will update it likely early next week, as I'm out now.

**Comment by ayufan** [comment]
@glmnet Can you review?

**Comment by glmnet** [comment]
I'm readding need-docs labels as docs base branch is wrong, should be next

**Pull request merged**
