### PR TITLE
Feature/m5angle8: Add support for m5angle8 input device

### PR DESCRIPTION
**Pull request by rnauber**
# What does this implement/fix?

The [m5angle](https://docs.m5stack.com/en/unit/UNIT%208Angle) has 8 potentiometers a switch and 9 RGB-LEDs and communicates via I2C. This PR adds support for this device to ESPHome.

https://github.com/esphome/esphome/assets/7414650/37478e3a-b317-4fac-b26c-0437211ffbe1

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** -

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3866

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [X] ESP8266
- [X] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

i2c:
  sda: 26
  scl: 32
  scan: false
  id: bus_external
  frequency: 200kHz
  #timeout: 100us
      
m5angle8:
    i2c_id: bus_external
    id: m8_angle_base
    lights:
        id: m8_angle_leds
        name: "M5Angle Lights"
        effects:
            - addressable_rainbow:
            - addressable_lambda:
                name: "Indicate Values"
                update_interval: 200ms
                lambda: |-
                        ESPHSVColor hsv;
                        hsv.value = 255;
                        hsv.saturation = 240;
                        auto parent = id(m8_angle_base);
                        for (int i=0; i < 8; i++) {
                          auto kpos = parent->read_knob_pos(i);
                          if (kpos >= 0){
                            hsv.hue = kpos * 200; 
                            it[i] = hsv;
                          }
                        }
                        if (parent->read_switch() > 0)
                            hsv.hue = 20;   
                        else
                            hsv.hue = 200; 
                        it[8] = hsv;
    knob_position_1:
        name: "M5Angle Knob 1"
    knob_position_2:
        name: "M5Angle Knob 2"
    knob_position_3:
        name: "M5Angle Knob 3"
    knob_position_4:
        name: "M5Angle Knob 4"
    knob_position_5:
        name: "M5Angle Knob 5"
    knob_position_6:
        name: "M5Angle Knob 6"
    knob_position_7:
        name: "M5Angle Knob 7"
    knob_position_8:
        name: "$M5Angle Knob 8"
    input_switch:
        name: "M5Angle Switch"

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
Please reorganise the config to separate platform files to align with other hub components.

Also, please rename the component to m5stack_8angle.

The end result should be like this:
```yaml
m5angle8:
  id: my_angle
  
light:
  - platform: m5angle
    m5angle_id: my_angle
    name: Lights
    effects:
      ...

sensor:
  - platform: m5angle
    m5angle_id: my_angle
    name: Knob 1
    channel: 1

binary_sensor:
  - platform: m5angle
    m5angle_id: my_angle
    name: Angle Switch

```

**Comment by rnauber** [comment]
Hi @jesserockz , 
thanks for the feedback!

> Please reorganise the config to separate platform files to align with other hub components.
> 
Ok, will do.

> Also, please rename the component to m5stack_8angle.

Should I just rename the directory or change it everywhere in the code and configuration? So, should the new  configuration look like this?

```yaml
m5stack_8angle:
  id: my_angle
  
light:
  - platform: m5stack_8angle
    m5angle_id: my_angle
    name: Lights
    effects:
      ...

sensor:
  - platform: m5stack_8angle
    m5angle_id: my_angle
    name: Knob 1
    channel: 1

binary_sensor:
  - platform: m5stack_8angle
    m5angle_id: my_angle
    name: Angle Switch
```

**Comment by jesserockz** [comment]
Yes please rename everywhere. The platform and hub component in yaml come from the directory name automatically. The namespace must match the directory/component name (CI will complain about this otherwise) And its better if the classes and logging/tags match too =)

**Comment by rnauber** [comment]
Hi @jesserockz ,
I refactored the code and the documentation and tested all again. I think it is ready for merging now.

Best,
Richard

**Comment by jesserockz** [comment]
Hey @rnauber, I made some structural changes to the PR, and also some new features =)

I dont have the device myself, so hopefully the changes are working for you?

You can now choose 8bit or 12bit resolution for the knobs, and also have it output the raw value if desired instead of the float %.

Jesse

**Comment by rnauber** [comment]
Hi @jesserockz ,
thank you very much for digging into this code!

> I dont have the device myself, so hopefully the changes are working for you?

I tested it and had to fix two bugs:
1) An uninitialized variable was spicing things up a little with the knob positions, the readout in 8bit mode gained a random component :stuck_out_tongue_closed_eyes: 
2) The firmware of the 8angle chokes on longer SPI transfers. I had to implement a workaround to control all LEDs.

... and now it is working flawlessly!

> You can now choose 8bit or 12bit resolution for the knobs, and also have it output the raw value if desired instead of the float %.

That is great, thank you! 

I will update the docs and then I think this patch is ready for merging!


Best,
Richard

> Jesse

**Review by jesserockz — APPROVED** [review]
> I tested it and had to fix two bugs:
> 
> 1. An uninitialized variable was spicing things up a little with the knob positions, the readout in 8bit mode gained a random component 😝

Woops.

> 2. The firmware of the 8angle chokes on longer SPI transfers. I had to implement a workaround to control all LEDs.

Ah I wondered why you were writing one at a time before. Makes sense if the device cant handle it, and its not a whole lot of bytes anyway.

Glad to see its working though.

**Pull request merged**
