### PR TITLE
Fix deprecation of board_flash_mode parameter

### PR DESCRIPTION
**Pull request by aequitas**
Fixes 
```
Warning! `board_flash_mode` option is deprecated and will be removed in the next release! Please use `board_build.flash_mode` instead.
```

### CODE REVIEW

**Comment by OttoWinter** [comment]
Problem with this is that for users running with [`platformio<3.5.3`](https://github.com/platformio/platformio-docs/commit/26590b1e1c314c3d1119f1809b85b5579f004ec4#diff-667de14ea85f074e556e5d12d35e884f) this will effectively disable this option semi-silently.

This is not an issue for HassIO add-on users, but definitely for users running esphomeyaml on a host system.

As this option is vital for some users and could (according to the tasmota wiki) brick a device, we should check the version using `import platformio; platformio.VERSION` and choose the correct config option.

**Comment by aequitas** [comment]
I was afraid of something like that as well. I'll work on the version check. Don't know when the deprecation is due, but might tackle this right away.

**Comment by aequitas** [comment]
I added the logic. Let me know if you'd like changes to style/structure.

**Comment by OttoWinter** [comment]
Compared to the rest of the esphomeyaml core code, it's not that bad :)

**Comment by aequitas** [comment]
I was tempted to add a test framework, maybe something for the next pr :)

**Comment by OttoWinter** [comment]
Yeah testing would be awesome :) But setting up these frameworks so that they work can be ... well a long process from my experience

**Pull request merged**
