### PR TITLE
Support for TOF10120 distance sensor

### LINKED ISSUE #797: TOF10120 Time Of Flight Distance Sensor up to 180cm
Dear.

It would be great, next to the VL53L0X Time Of Flight Distance Sensor, to have the TOF10120 as well.

Datasheet:
[https://github.com/simpleiot/reference/blob/master/sensors/TOF10120_english.pdf]

This sensor is also based on the time of flight principle and can communicate either with RS232 (UART) and I2C.
It can range up to 180cm and has a sealed sensor body with screws. Very useful in moistured areas (rainwell).

Thank you in advance for the efforts to implement/add this sensor.

Kind regards,
Frederik

### PR DESCRIPTION
**Pull request by wstrzalka**
## Description:

Adds support for TOF10120.

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/797

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#846
## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by AythamiEsp** [comment]
Thanks!
When can we start using this?

**Comment by wstrzalka** [comment]
As soon as somebody from maintainers will find a time to review and merge :) 

If you want to use it asap, you can put the added files directly to your esphome installation and it will start work immediately as they are attached to the final release as is. I'm already using it like that

**Review by glmnet — APPROVED** [review]

**Comment by tomjmul** [comment]
@wstrzalka Would you mind merging in the dev branch please?

**Comment by wstrzalka** [comment]
@tomjmul Sorry - unable - restricted to authorized users only

**Pull request merged**
