### PR TITLE
Autodetect ESP32 variant

### PR DESCRIPTION
**Pull request by oxan**
# What does this implement/fix? 

Autodetect ESP32 variant by querying `mcu` option from the PlatformIO board config. 

Note that `platformio boards` by default queries from their site, is that acceptable? We can also query only installed platforms, but that's problematic on the first run when the ESP32 platform isn't installed yet.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — COMMENTED** [review]
Hmm, for me the `pio boards` command take 0.5s to execute

```
$ time pio boards --json-output nodemcu-32s                         
[{"id": "nodemcu-32s", "name": "NodeMCU-32S", "platform": "espressif32", "mcu": "ESP32", "fcpu": 240000000, "ram": 327680, "rom": 4194304, "frameworks": ["arduino", "espidf"], "vendor": "NodeMCU", "url": "http://www.nodemcu.com/", "connectivity": ["wifi", "bluetooth", "ethernet", "can"], "debug": {"tools": {"esp-prog": {}, "iot-bus-jtag": {}, "jlink": {}, "minimodule": {}, "olimex-arm-usb-tiny-h": {}, "olimex-arm-usb-ocd-h": {}, "olimex-arm-usb-ocd": {}, "olimex-jtag-tiny": {}, "tumpa": {}}}}]
pio boards --json-output nodemcu-32s  0.53s user 0.04s system 100% cpu 0.566 total
```

(not sure why it's that slow, but partially probably to start up the python VM).

That would get run for every esphome operation (validate, etc, especially also live validate in frontend)

We either need to cache it on the fs, or statically ship it with our config (we already have that for pin mappings, so should be ok)

**Comment by oxan** [comment]
> (not sure why it's that slow, but partially probably to start up the python VM).

Yes, that dominates it, when calling pio in-process it takes ~28ms for me:
```
$ python -m timeit -s 'from esphome import platformio_api' 'platformio_api.get_board_config("nodemcu-32s")'
10 loops, best of 5: 27.7 msec per loop
```
First run is slower (~1.3s for me), but platformio already caches the board list locally for a day.

> or statically ship it with our config (we already have that for pin mappings, so should be ok)\

I'm not too fond of that, that'd make the boardlist more important again... One of the nice things about the platform refactor is that the boardlist is now optional.

**Comment by OttoWinter** [comment]
> First run is be slower (~1.3s for me), but platformio already caches the board list locally for a day.

Oh, is it a network request that's cached? If so, that could be another problem then, if pio servers are down then esphome no longer works (https://github.com/esphome/issues/issues/948, which we eliminated by installing libs globally)

> One of the nice things about the platform refactor is that the boardlist is now optional.

Oh, that wasn't intentional haha... I think I just forgot to re-add it after I copied `boards.py` again. But even then, we can make it so that if the board isn't found we just force the user to add the variant manually.

**Comment by oxan** [comment]
> Oh, is it a network request that's cached?

Yes. PlatformIO has an `--installed` option to only query locally-installed platforms, but that might require installing the platform first if it isn't already (probably only relevant for pip installations). 

> But even then, we can make it so that if the board isn't found we just force the user to add the variant manually.

True.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
