### PR TITLE
support spi for sn74hc595

### PR DESCRIPTION
**Pull request by angelnu**
# What does this implement/fix?

Support using SPI for the sn74hc595. This is required when other SPI devices are in the same bus such as by the Shelly Pro 2PM.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** NA

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3341

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

When using the SPI the following can be used:
```yaml
# Example with SPI
spi:
  clk_pin: GPIO21
  mosi_pin: GPIO22
  miso_pin: GPIO23
sn74hc595:
  - id: sn74hc595_hub_2
    latch_pin: GPIO22
    oe_pin: GPIO32
    sr_count: 2
```

When not using the SPI, the same previous schema works:
```yaml
sn74hc595:
  - id: sn74hc595_hub
    data_pin: GPIO21
    clock_pin: GPIO23
    latch_pin: GPIO22
    oe_pin: GPIO32
    sr_count: 2
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by angelnu** [comment]
@notsonominal Did this one also work gor you?

**Comment by ghost** [comment]
Works great both as SPI and non-SPI on Shelly pro and Shelly plus models I tested.

**Comment by jesserockz** [comment]
I just made some (untested) changes to the code to clean it up a bit and truly split spi vs gpio right from codegen.

Please make sure they work for you and let me know

**Comment by angelnu** [comment]
I can confirm it compiles for me. Nice rework.

@notsonominal could you please retest on your side? I do not have this device.

**Comment by ghost** [comment]
yeah, still works both as spi and no spi 👍

**Review by jesserockz — APPROVED** [review]

**Comment by ghost** [comment]
~This might have been premature as i compiled and tested 228c258 while 92b618c was merged.~
It works when checking out  2023.11.0-dev
but moving from spi to not spi (with no spi bus configured) i get this 
```
Compiling .pioenvs/shelly-pro-1pm-30c6f781837c/src/esphome/components/socket/socket.o
*** [.pioenvs/shelly-pro-1pm-30c6f781837c/src/esphome/components/spi/spi.o] Source `src/esphome/components/spi/spi.cpp' not found, needed by target `.pioenvs/shelly-pro-1pm-30c6f781837c/src/esphome/components/spi/spi.o'.
========================================= [FAILED] Took 12.09 seconds =========================================
```
clean and run gets past it though, and both still works

**Comment by angelnu** [comment]
I can take a look at the warning this evening. Can you dm your config (just in case)?

**Comment by angelnu** [comment]
@notsonominal - I am not able to reproduce the warning you are getting. So could you open an issue and attach your configuration? It might be depending on the framework/device...

**Pull request merged**
