### PR TITLE
Fixed RGBWW lights not setting white value when setting to white

### PR DESCRIPTION
**Pull request by Mikaeeld**
## Description:
A previously merged pull request significantly improved the handling of RGBWW lights with regards to the way colors and white value are modified but there was a small bug which resulted in the CWWW leds not becoming active when setting the color to white without also setting a color temperature. This would make it impossible to adjust color temperature or enable the CWWW leds without changing to another color and then changing the color temperature to return to white.

In the original code, a request containing only RGB color data would set the light's white value to 0 but did not account for setting the light's color to white which should set the lights white value to 100. This pull request simply adds a check for this case to solve the problem.

**Related issue (if applicable):** fixes bug in [Rgbww color fix](https://github.com/esphome/esphome/pull/967)
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
so this pr, 
https://github.com/esphome/esphome/pull/1043 by @Skaronator 
and https://github.com/esphome/esphome/pull/1042 by @peq123

they all deal with the same code, can any of you guys figure out whats going on overall so we can get this done?
I don't have RGBWW lights here to test and I'm not aware of what the issues are, but I believe merging one will cause conflicts or errors on the others

**Comment by peq123** [comment]
so i have had a quick look at the two prs and compared with them with mine. i am not sure what #1043 fixes but #1060 attempts to fix the same thing mine. mine has additional fixes that if rgb is set to 255,255,255: the rgb leds get turned off in favour of the warm white / cool white leds

**Comment by NTRNSTR** [comment]
@peq123 is right about that, I should be able to close my pr. With regards to #1043 it seems to just add a a gamma adjustment to each value, from what I can tell it shouldn't cause any problems once the conflicting parts are cleared up.  I'll try to do some testing later today with #1042 and #1043

**Comment by peq123** [comment]
I have been looking at #1043  - I haven't had time to test this yet but I think this would not work with the way Google Home sets colour. Google Home sets the rgb values and brightness to change colour options and therefore having a constant brightness value might interfere the reporting back to Google Home

**Comment by glmnet** [comment]
so, should we close this one and merge #1042 meanwhile?

**Comment by peq123** [comment]
good by me. I have running my pr locally without issue

**Comment by NTRNSTR** [comment]
Yep, #1042 is working perfectly, there's no need for this one.

**Pull request closed without merging**
