### PR TITLE
Remove floating point calculation from ac_dimmer ISR

### LINKED ISSUE #3509: Upgrading from 2022.6.3 to 2022.8.0 causes WDT resets with AC dimmer
### The problem

After upgrading ESPHome, my ac_dimmer based lights stopped working. The serial logs report that shortly after the brightness is set from home assistant, the ESP locks up and gets stuck in a boot loop. 
If I downgrade to 2022.6.3, I can send as many brightness as I want and the ESP remains functional. If I set logger to VERY_VERBOSE, the ESP seems to be stable. 
I've tested this on both an actual lamp and on a bare module with a waveform generator produced zero cross input. 
Replacing the ac dimmer with PWM on the test setup is stable, but obviously won't work for the real lamp.
The logs give no stack trace, only the WDT reset boot message.

### Which version of ESPHome has the issue?

2022.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.8.3

### What platform are you using?

ESP8266

### Board

ESP-12E

### Component causing the issue

ac_dimmer

### Example YAML snippet

```yaml
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 
      number: GPIO13
      inverted: true
    zero_cross_pin: GPIO12
    min_power: 0.2
    zero_means_zero: true
    
light:
  - platform: monochromatic
    output: dimmer1
    name: "test lamp"
    id: lamp
```

### Anything in the logs that might be useful for us?

```txt
[D][light:035]: 'test lamp' Setting:
[D][light:050]:   Brightness: 85%
[D][light:084]:   Transition length: 1.0s
[D][light:035]: 'test lamp' Setting:
[D][light:050]:   Brightness: 31%
[D][light:084]:   Transition length: 1.0s

 ets Jan  8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 3460, room 16
tail 4
chksum 0xcc
load 0x3fff20b8, len 40, room 4
tail 4
chksum 0xc9
csum 0xc9
v0007d8c0
~ld
[I][logger:243]: Log initialized
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Azimath**
# What does this implement/fix?

PR<https://github.com/esphome/esphome/pull/3494> added code to linearize the RMS power output of the ac_dimmer relative to the output state. Doing so introduced an acos into the ISR, which most of the time works, but some race condition exists that causes this call to throw an exception when doing stuff like OTA, setting a new value in home assistant, or sometimes it just keeps working (depending on what version of ESPHome you're running and your luck).

The RMS power linearization only needs to be computed when a new state is written, as it doesn't vary cycle to cycle. This PR moves the acos function outside the ISR into the write_state function where it shouldn't cause problems. 

The original PR was considered breaking because it might change how gamma is perceived on some lights. The linearization previously applied only to leading dimmers, while now it applies to both, so it might change how gamma is perceived on trailing dimmers.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [3509](https://github.com/esphome/issues/issues/3509)

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 
      number: GPIO13
      inverted: true
    zero_cross_pin: GPIO12
    min_power: 0.2
    zero_means_zero: true

```

## Checklist:
  - [x] The code change is tested and works locally.
  - n/a Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
@josephdouce can you please review this?

**Comment by josephdouce** [comment]
Will do

Kind Regards

Joseph Douce BEng (Hons) MIET

**Comment by Azimath** [comment]
@josephdouce Have you had a chance to look at this yet?
-Azimath

**Comment by josephdouce** [comment]
Sorry for the delay, can't see any problem here, I was looking to do
something similar myself but didn't get chance. Good improvement moving the
calculation to cover all edge types too.

Kind Regards

Joseph Douce BEng (Hons) MIET

**Review by glmnet — APPROVED** [review]

**Pull request merged**
