### PR TITLE
Add support for Waveshare 7.5 inch (C) bichromatic display (black-and-white only for now)

### PR DESCRIPTION
**Pull request by pixelspark**
# What does this implement/fix? 

Driving a Waveshare 7.5 inch (version 'C') bichromatic e-paper display is possible using the already supported "7.50in" device configuration, but updates rather slow. Additionally the image appears to fade after a while.

This PR provides support for displaying black-and-white images on 7.5 inch (C) bichromatic Waveshare displays using device type identifier "7.50in-bc" (Waveshare calls this display "7in5bc" in their drivers). It uses a slightly modified initialization sequence (copied from a driver I implemented earlier in Rust for the same display). The 0x04 'power on' command is moved from the init sequence to the display sequence (which otherwise is equal to the 7.50in display).

Note: the versioning of Waveshare displays is a bit confusing. This is for the "v1" series of 7.5inch displays, revision "C" (the displays have a sticker "(C)" on the back), bichromatic variant (mine is yellow-black but red-black and others will work as well). 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):**  n/a

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 

esphome/esphome-docs#1206
  
# Test Environment

- [X] ESP32
- [ ] ESP8266
- [ ] Windows
- [X] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
font:
  - file: "some_font.ttf"
    id: some_font
    size: 40

display:
  - platform: waveshare_epaper
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    model: 7.50in-bc
    id: my_display
    update_interval: 60s
    lambda: |-
      it.print(10, 10, id(some_font), "TEST");
      it.line(0, 65, 640, 65);
```

# Explain your changes

This allows using 7.5inch bichromatic (version 'B') displays from Waveshare with ESPHome. Previously this was possible by using the "7.50in" configuration intended for monochromatic displays, but updating is slower and the image appears to fade.

If required I can provide a video showing the difference between the two on a real display.

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

Not sure how I would write a test for this that works without hardware. There appear to be no tests for the other Waveshare e-paper drivers. Happy to add one if instructed how.
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

Awaiting merge of https://github.com/esphome/esphome-docs/pull/1206

### CODE REVIEW

**Comment by pixelspark** [comment]
Note I also reimplemented the drawing command - this version seems functionality equivalent but a bit more readable. It should be quite easy now to add a setting to allow drawing as color/white rather than (current default) black/white. (if the display library supports multiple colors, then that is relatively easy to add now too).

**Comment by JumpMaster** [comment]
Hi @pixelspark 

I recently received an RMA for a 7.5" V2 display which also has the same symptoms.  I have been told it's a new model which has no identification of A/B/C but does have a different shaped connector.

Do you know if the changes you have made here are also relevant for the 7.2inBv2 display?  I assume this is the correct Arduino code although I'm struggling to get it to work on the waveshare esp32 module.

https://github.com/waveshare/e-Paper/tree/master/Arduino/epd7in5b_V2

Thanks,
Kev

**Comment by pixelspark** [comment]
> Hi @pixelspark
> 
> I recently received an RMA for a 7.5" V2 display which also has the same symptoms. I have been told it's a new model which has no identification of A/B/C but does have a different shaped connector.
> 
> Do you know if the changes you have made here are also relevant for the 7.2inBv2 display? I assume this is the correct Arduino code although I'm struggling to get it to work on the waveshare esp32 module.
> 
> https://github.com/waveshare/e-Paper/tree/master/Arduino/epd7in5b_V2
> 
> Thanks,
> Kev

Not sure actually! I have two different types of 7.5in displays laying around (both have the same connector by the way..) could you perhaps send a picture of what yours looks like? I can compare it to mine.

**Comment by JumpMaster** [comment]
> > Hi @pixelspark
> > I recently received an RMA for a 7.5" V2 display which also has the same symptoms. I have been told it's a new model which has no identification of A/B/C but does have a different shaped connector.
> > Do you know if the changes you have made here are also relevant for the 7.2inBv2 display? I assume this is the correct Arduino code although I'm struggling to get it to work on the waveshare esp32 module.
> > https://github.com/waveshare/e-Paper/tree/master/Arduino/epd7in5b_V2
> > Thanks,
> > Kev
> 
> Not sure actually! I have two different types of 7.5in displays laying around (both have the same connector by the way..) could you perhaps send a picture of what yours looks like? I can compare it to mine.

Pic attached below.  Left is the new screen which shows very faded.  Setting the screen to full black or white looks great but the last stage of the page refresh makes the screen faded when displaying mixed graphics.

The left (new) connector has FPC-8612 printed on it.  The right (older) has WFT0583CZ61 printed.  I suspect that only the connector details.

ePaper

**Comment by pixelspark** [comment]
IMG_3038
 This is what my 7.5 inch "(C)" bichromatic ('yellow'-black) display looks like (this is what this PR is written for).

**Review by oxan — APPROVED** [review]

**Comment by oxan** [comment]
Huh, that's a weird CI failure, I didn't change any formatting.

**Pull request merged**
