### PR TITLE
LEDC song

### PR DESCRIPTION
**Pull request by OttoWinter**
## Description:

See also https://github.com/esphome/feature-requests/issues/380#issuecomment-548480335

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
Really? :dancer:

**Comment by DasBootU96** [comment]
I thought you were joking at first when you said to make it easier with output.ledc.song :stuck_out_tongue_winking_eye:

Guess not :smiley: Love it :heart:

**Comment by glmnet** [comment]
This is great I just found a zip file with 10000 rtttl strings

**Comment by OttoWinter** [comment]
@mblakleyiii 
> This also works with esp8266_pwm. I think this should be made a separate component/platform so you can pass in either an ledc or esp8266_pwm component as a float output.

Yeah I know - but FloatOutput does not have an API for setting frequency yet - and I'm not sure how such a thing would be added yet. Some components, like PCA9685, can set frequency but only for all channels together.

For RTTTL - that's a really interesting format! I did not know about that.

As for the parsing - I think it makes more sense parsing it on the python side. In python we can do better parsing and validate the input before. Plus the current syntax here is very close to RTTL anyway (minus string parsing, but that's simple in python)

**Comment by glmnet** [comment]
> As for the parsing - I think it makes more sense parsing it on the python side. In python we can do better parsing and validate the input before. Plus the current syntax here is very close to RTTL anyway (minus string parsing, but that's simple in python)

The downside of that is that you won't be able to feed a parsed rtttl from a HA service. I'd vote for parsing on the ESP, validating on the YAML would be great

**Comment by minsuke** [comment]
it's great code, I found ringtone which has christmas tunes. 

http://www.picaxe.com/RTTTL-Ringtones-for-Tune-Command/

thx for great idea and codes.

**Pull request closed without merging**
