### PR TITLE
[qspi_dbi] Rename from qspi_amoled, add features

### PR DESCRIPTION
**Pull request by clydebarrow**
# What does this implement/fix?

* Rename the `qspi_amoled` display driver to `qspi_dbi` since it now supports other displays.
* Add custom model and custom init sequences
* Add `draw_from_origin` to support certain broken display driver chips.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4335
## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - platform: qspi_dbi
    model: AXS15231
    data_rate: 40MHz
    dimensions:
      height: 480
      width: 320
    cs_pin:
      number: 45
      ignore_strapping_warning: true
    auto_clear_enabled: false
    update_interval: never
    rotation: 270
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by xiasi0** [comment]
👍

**Comment by xiasi0** [comment]
image

Do you need to wait for the merger?

**Comment by clydebarrow** [comment]
> Do you need to wait for the merger?

I don't, but you probably will have to, not because the editor is showing errors (that is cosmetic only) but because there is a core change which doesn't get pulled in by the external component which will make compilation fail.

The alternative is to clone my repository, switch to the qspi branch and compile via CLI.

**Comment by xiasi0** [comment]
> > Do you need to wait for the merger?
> 
> I don't, but you probably will have to, not because the editor is showing errors (that is cosmetic only) but because there is a core change which doesn't get pulled in by the external component which will make compilation fail.
> 
> The alternative is to clone my repository, switch to the qspi branch and compile via CLI.

Okay, I'll wait until the merge is released before testing! thank you

**Comment by nagyrobi** [comment]
https://discord.com/channels/429907082951524364/1287891890330533959

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
