### PR TITLE
Add support for PCA9535 16 bit I/O expander

### PR DESCRIPTION
**Pull request by clydebarrow**
# What does this implement/fix?

The PCA9554 component is extended to support the 16 bit PCA9535 I/O expander.

## Types of changes

- [x] New feature (non-breaking change which adds functionality)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3315

## Test Environment

- [x] ESP32
- [x] ESP32 IDF

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
pca9554:
  - id: pca9535
    pin_count: 16
    address: 0x20

binary_sensor:
  - platform: gpio
    internal: true
    name: Pin 1_1
    pin:
      pca9554: pca9535
      number: 8
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by hwstar** [comment]
Regressing the changes by testing on a PCA9554 project fails. I added the new files as a external component and I get the errors below during an esphome compile. If I remove the external component and use the stock PCA9554 component, the config compiles OK. The config is attached below as a script.Please note that this script contains other external components which are not included in the .zip file and it will not compile without the missing files. Here is the esphome compile output when it fails:
```
Failed config

binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:350]
  platform: gpio
  name: Zone_8
  id: zone8
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_1_8
    number: 7
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:360]
  platform: gpio
  name: Zone_7
  id: zone7
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_1_8
    number: 6
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:371]
  platform: gpio
  name: Zone_6
  id: zone6
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_1_8
    number: 5
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:382]
  platform: gpio
  name: Zone_5
  id: zone5
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_1_8
    number: 4
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:393]
  platform: gpio
  name: Zone_4
  id: zone4
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_1_8
    number: 3
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:403]
  platform: gpio
  name: Zone_3
  id: zone3
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_1_8
    number: 2
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:413]
  platform: gpio
  name: Zone_2
  id: zone2
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_1_8
    number: 1
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:423]
  platform: gpio
  name: Zone_1
  id: zone1
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_1_8
    number: 0
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:436]
  platform: gpio
  name: Zone_16
  id: zone16
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_9_16
    number: 7
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:446]
  platform: gpio
  name: Zone_15
  id: zone15
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_9_16
    number: 6
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:456]
  platform: gpio
  name: Zone_14
  id: zone14
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_9_16
    number: 5
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:466]
  platform: gpio
  name: Zone_13
  id: zone13
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_9_16
    number: 4
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:476]
  platform: gpio
  name: Zone_12
  id: zone12
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_9_16
    number: 3
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:486]
  platform: gpio
  name: Zone_11
  id: zone11
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_9_16
    number: 2
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:496]
  platform: gpio
  name: Zone_10
  id: zone10
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_9_16
    number: 1
    mode: 
      input: True
    inverted: True
binary_sensor.gpio: [source 16-zone-sensor-acp-customized.yaml:507]
  platform: gpio
  name: Zone_9
  id: zone9
  
  No pca9554 component found with matching id.
  pin: 
    pca9554: pca9554_zones_9_16
    number: 0
    mode: 
      input: True
    inverted: True
```


[16-zone-sensor-acp-customized.yaml.zip](https://github.com/esphome/esphome/files/13218350/16-zone-sensor-acp-customized.yaml.zip)

**Review by hwstar — CHANGES_REQUESTED** [review]
See comment about the PCA9554 regression test failing.

**Comment by clydebarrow** [comment]
> See comment about the PCA9554 regression test failing.

Fixed. If you can confirm correct operation that should make this a wrap.

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Will merge after confirmation from @hwstar

**Comment by clydebarrow** [comment]
The technique I used to find the parent component could be useful elsewhere, and if migrated to core code could be more reliably maintained. Is that something you would see as worth doing? If so I'll look at it after this PR is merged.

**Comment by hwstar** [comment]
The latest version tests good with the PCA9554

**Comment by clydebarrow** [comment]
>The technique I used to find the parent component could be useful elsewhere, and if migrated to core code could be more reliably maintained. Is that something you would see as worth doing? If so I'll look at it after this PR is merged.



That question was meant for @jesserockz of course....

**Comment by jesserockz** [comment]
Yeah, I was actually thinking how we could turn it into a global validation for other expanders without duplicating the code

**Pull request merged**
