### PR TITLE
Added an option to disable mDNS

### PR DESCRIPTION
**Pull request by dnetguru**
# What does this implement/fix? 
This PR adds a boolean config option `enable_mdns` (default=true) to the `esphome` section that can be used to enable/disable mDNS in firmware codegen.

## Type of changes
- New feature (non-breaking change which adds functionality)

**Related issues:**
https://github.com/esphome/feature-requests/issues/983
https://github.com/esphome/feature-requests/issues/769

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation:**
https://github.com/esphome/esphome-docs/pull/1118
  
# Test Environment

- [x] ESP32
- [x] ESP8266
- [ ] Windows
- [ ] Mac OS
- [x] Linux

## Example entry for `config.yaml`:
```yaml
esphome:
  enable_mdns: false
```

# Explain your changes
The `enable_mdns` option will control the inclusion of `ESPmDNS` and `ESP8266mDNS` libraries AND defines the `USE_MDNS` flag for the preprocessor.
All the related mDNS code is wrapped around conditional preprocessor directives so they are omitted when `enable_mdns` is set to false.

I have tested this with ESP32, ESP8266 using WiFi.
I don't have access to an ESP32 ethernet module, so I would appreciate it if someone can test this change with an ethernet shield.

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
I'm ok with this but I believe it will be better if the options is under wifi and ethernet to maintain cohesion

**Comment by dnetguru** [comment]
That is what I initially had in mind but I noticed that for some reason the include flags for mDNS libraries were added in `core_config.py` AND it looks like there is no straightforward way to access other sections of config from that part of the code.

I will move the inclusion of mDNS libraries to WiFi and ethernet components and move the config option with them.

**Comment by dnetguru** [comment]
Done! Now `enable_mdns` can be defined under `wifi` or `ethernet`.

```
dnetguru /workspace/esphome/config $ ls
test2  test_node.yaml
dnetguru /workspace/esphome/config $ grep -B1 mdns test_node.yaml 
ethernet:
  enable_mdns: true
dnetguru /workspace/esphome/config $ esphome test_node.yaml compile 2>&1 | grep SUCCESS
========================= [SUCCESS] Took 3.02 seconds =========================
dnetguru /workspace/esphome/config $ readelf --syms $(find . -name firmware.elf) | grep -i mdns | wc -l
128
dnetguru /workspace/esphome/config $ sed -i 's/mdns: true/mdns: false/' test_node.yaml 
dnetguru /workspace/esphome/config $ grep -B1 mdns test_node.yaml 
ethernet:
  enable_mdns: false
dnetguru /workspace/esphome/config $ esphome test_node.yaml compile 2>&1 | grep SUCCESS
========================= [SUCCESS] Took 41.22 seconds =========================
dnetguru /workspace/esphome/config $ readelf --syms $(find . -name firmware.elf) | grep -i mdns | wc -l
0
dnetguru /workspace/esphome/config $ 
```

**Comment by glmnet** [comment]
> disabling mDNS when using MQTT and/or static IP addresses

is there a validation rule that must be done? e.g. disabling mdns and using dhcp should not validate?
I think not as dhcp can work with a fixed ip lease and no need for host name

**Review by glmnet — APPROVED** [review]

**Comment by dnetguru** [comment]
No, there's no need for enforcing that. Since as you pointed out the user can assign a static lease or determine the IP address in some other way.

The most common use case however is going to be MQTT and static IP addresses which I mentioned I'll cover in the docs.

I did consider having a static IP OR not enabling the API server to imply not enabling mDNS by default but ultimately I decided against it since it's possible some users might be relying on mDNS for discovery in Hass even when they're using a static IP.
The online status functionality in the dashboard seems to rely on mDNS as well, so this might confuse some users.

With that said, it might be worth considering changing the default behavior to disable mDNS when MQTT is used.

**Comment by dnetguru** [comment]
@glmnet added a PR for docs

**Comment by glmnet** [comment]
> The online status functionality in the dashboard seems to rely on mDNS as well, so this might confuse some users.

Please add this on docs too. E.g

If you disable mdns then you will need to set an static IP and use ping for online status to work in the dashboard. 

(You can link to the faq note about that, see docker entry)

Also please test this, we definitely are going to get issue reports about this otherwise

**Comment by dnetguru** [comment]
Done. I added a section on this to the FAQ and linked to it from the components. See: https://github.com/esphome/esphome-docs/pull/1118

As for testing, I've fully tested this on ESP32 and ESP8266 nodes using WiFi.
I don't have access to an ethernet module, so I haven't done any testing with the ethernet component besides making sure that this config flag controls the inclusion of the mDNS code (and mDNS library symbols) in the resultant ``firmware.elf`` file using static analysis.

Feel free to tag me on any issues that are opened about this.

**Comment by glmnet** [comment]
I can test Ethernet 

What should I check?

**Comment by dnetguru** [comment]
First we need to make sure that the existing mDNS functionality continues to work when this flag is enabled.
To do this, just compile a firmware with ethernet and ``enable_mdns`` set to true. Use wireshark or tcpdump to see the mDNS broadcasts are being sent and everything works as expected.

Then change the ``ebable_mdns`` to false (and switch to a static IP if not already set) and recompile/flash then use wireshark or tcpdump again to verify that the mDNS broadcasts are absent from this node and everything else works as expected.

**Comment by dnetguru** [comment]
@glmnet were you able to do these tests? Can we get this and https://github.com/esphome/esphome-docs/pull/1118 merged?

**Comment by glmnet** [comment]
off: 
while looking at this I've found
image

why is data length 13?? is it ok?

**Pull request merged**
