### PR TITLE
Update state_class for DSMR

### PR DESCRIPTION
**Pull request by klaasnicolaas**
# What does this implement/fix? 

This PR updates the `state_class` for some entities with **STATE_CLASS_TOTAL_INCREASING**.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Should the entities for gas also be updated?

**Review by jesserockz — CHANGES_REQUESTED** [review]
A PR changing the state class to total_increasing, should also remove the last reset type.

I am about to do all of them in the codebase, but will skip dsmr

**Comment by jesserockz** [comment]
I am actually changing DSMR too as making underlying changes to completely remove `last_reset_type`

**Comment by jesserockz** [comment]
Closing in favour of #2233

**Comment by klaasnicolaas** [comment]
No problem, as long as it is eventually adjusted. 😄

**Pull request closed without merging**
