### PR TITLE
Sim800l add calls, multiline sms and ussd

### PR DESCRIPTION
**Pull request by glmnet**
# What does this implement/fix?

Fix bugs

Add support to receive multi line sms text, thanks @dz0ny 
Add dial, connect and disconnect calls
Add ussd code

See docs PR for usage

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes 1347

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2284

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

sim800l: 
  on_incoming_call:
    - logger.log:
        format: "Incoming call from '%s'"
        args: ["caller_id.c_str()"]
    - lambda: |-
        id(caller_id_text_sensor).publish_state(caller_id);

text_sensor:
  - platform: template
    id: caller_id_text_sensor
    name: "Caller ID"

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by andriej** [comment]
Just checked against last stable - works, proper CLIP identification, no hang up.

Having it implemented like:
```
  on_incoming_call:
    - logger.log:
        format: "Incoming call from '%s'"
        args: ["caller_id.c_str()"]
    - lambda: |-
        id(caller_id_text_sensor).publish_state(caller_id);

text_sensor:
  - platform: template
    id: caller_id_text_sensor
    name: "Caller ID"
    icon: mdi:phone-incoming
```

in logs I can see that text-sensor gets updated even few minutes after the call (as the routine is called internally - last call was more than 5 minutes ago)

image

also, I'd love to see `ATH` as an option to hang up call just after first CLIP identification/RING

THank you very much!

**Comment by andriej** [comment]
Tested it more througously - apart from not being able to drop incoming call (and also outgoing) it works perfect.
Every "RING"/CLIP casues on_incoming_call to be called so one incoming call (waiting for pick-up) causes multiple launches of service every 5 seconds.
In my case: it opens the gate to neighbourhood and 5 seconds after it clicks again to close it ;-)

`ATH` (call rejection) would be cherry on top

**Comment by andriej** [comment]
I've tested the latest addition trying to add 'sim800l.disconnect' action just fater reporting incoming call.
What surprised me after flashing:
image

Not sure why routine with incoming call doesn't work anymore.

on same compilation, `sim800l.disconnect` works with routine using making calls

**Comment by andriej** [comment]
one more finding: everytime there's unhandled RING/CLIP, soon after that API connection to HA drops
image
not sure why tho :-)

**Comment by andriej** [comment]
Latest addition fixed CLIP identification works well and stable, I've just retested it.

Last thing that may be worth implementing to prevent multiple calls of `on_incoming_call` during one connection would be to wait for `NO CARRIER` after incoming call is noticed.
`NO CARRIER` would show either when call timeouts from network provider perspective (usually it's 20 seconds without pickup) or when call is hanged up using `ATH` from `sim800l.disconnect` - the same network info is passed (that call was not picked up)

**Comment by glmnet** [comment]
@andriej added two more triggers and connect action (see updated description above), works here, please test and let me know so we can try to ship this for the next release, thanks

**Comment by andriej** [comment]
I did just test it in all variants I think:
It works as desired:

**CALL OUT - ANSWERED**
in scenario when call is made by sim800l and picked up on the other side I use:
```
  on_call_connected:
    - logger.log:
        format: "Auto-Disconnecting call"
    - sim800l.disconnect
```

and there was a longer-moment (like 3-4 seconds) of silence on mobile which picked up the clal and two messages in log:
```
[08:30:21][D][sim800l:389]: Dialing +487xxxxxxxx
[08:30:22][I][sim800l:293]: Dialing: '+487xxxxxxxx'
[08:30:22][D][sim800l:217]: Call state is now: 2
[08:30:27][D][sim800l:217]: Call state is now: 0
[08:30:27][D][main:145]: Auto-Disconnecting call
**[08:30:27][D][sim800l:400]: Disconnecting
[08:30:46][D][sim800l:400]: Disconnecting**
```

just wondering if it's SIM800L tried to force-disconnect as first command didn't work?

also 3 minutes after the 2 calls sim800l did restart itself (reboot, uptime went to zero)
I made another try, this time waiting for `[08:38:16][I][ota:105]: Boot seems successful, resetting boot loop counter.` to show up

```
[08:38:44][D][sim800l:389]: Dialing +487xxxxxxxx
[08:38:44][I][sim800l:293]: Dialing: '+487xxxxxxxx'
[08:38:45][D][sim800l:217]: Call state is now: 2
[08:38:50][D][sim800l:217]: Call state is now: 0
[08:38:50][D][main:145]: Auto-Disconnecting call
[**08:38:50**][D][sim800l:400]: Disconnecting
[**08:39:09**][D][sim800l:400]: Disconnecting
```
notice the 'delay' of second "Disconnecting"
this time to restart of node happened but I think there may be something hiding in call received disconnection that could lead to restart? or it was just coincidence.

last try:
```
[08:43:34][D][sim800l:389]: Dialing +487xxxxxxxx
[08:43:34][I][sim800l:293]: Dialing: '+487xxxxxxxx'
[08:43:35][D][sim800l:217]: Call state is now: 2
[08:43:40][D][sensor:124]: 'SIM800L RSSI': Sending state 15.00000 dBm with 0 decimals of accuracy
[08:43:40][D][sim800l:217]: Call state is now: 0
[08:43:40][D][main:145]: Auto-Disconnecting call
[08:43:40][D][sim800l:400]: Disconnecting
[08:43:59][D][sim800l:400]: Disconnecting
```

still 2 messages "Disconnecting" present but node didn't restart itself so it's OK (waited more than 15 mins and everything was ok)

**CALL OUT - NOT ANSWERED**
In the same scenario when sim800 made call which was not picked up:
```
[08:35:18][D][sim800l:389]: Dialing +487xxxxxxxx
[08:35:18][I][sim800l:293]: Dialing: '+487xxxxxxxx'
[08:35:20][D][sim800l:217]: Call state is now: 2
[08:35:25][D][sim800l:217]: Call state is now: 3
[08:35:43][D][sim800l:400]: Disconnecting
```
node didn't restart itself nor 2nd log happened

**INCOMING CALL - DISCONNECTED**
works as expected, no repeats happening

thank you @glmnet for this :) hope it gets to next release as use-cases for such device would be beneficial even for non-HA remote installations

**Comment by andriej** [comment]
Let me know if you need anything else as I'm not fully aware when is the cutoff for next release

**Comment by wizu** [comment]
Will this be merged in next release?

**Comment by glmnet** [comment]
Is in my todo list. Need to do some more debugging on some repeated log messages mostly. 

It can be used as external component without problems anyway

**Comment by glmnet** [comment]
@andriej do you want to give it another try?

**Comment by andriej** [comment]
@glmnet sure.
using same yaml without even one change:
```
scenario 1 - call answered 
[21:09:39][I][sim800l:311]: Dialing: 'xxxxxxxxx'
[21:09:41][D][sim800l:235]: Call state is now: 2
[21:09:43][D][sim800l:235]: Call state is now: 3
[21:09:52][D][sim800l:235]: Call state is now: 0
[21:09:52][D][main:145]: Auto-Disconnecting call
[21:09:52][I][sim800l:036]: Disconnecting...
[21:10:04][I][sim800l:036]: Disconnecting...
```
scenario 2 - call being dropped without answering by phone
```
[21:10:13][I][sim800l:311]: Dialing: 'xxxxxxxxx'
[21:10:16][D][sim800l:235]: Call state is now: 2
[21:10:17][D][sim800l:235]: Call state is now: 3
[21:10:38][I][sim800l:036]: Disconnecting...
```

both calls managed properly, double message about Disconnection is still there but does not seem to hang up anything
SMS also worked.

i did repeat test of scenario 1 above:
```
[21:14:36][I][sim800l:311]: Dialing: 'xxxxxxxxx'
[21:14:41][D][sim800l:235]: Call state is now: 3
[21:14:43][D][sim800l:235]: Call state is now: 0
[21:14:43][D][main:145]: Auto-Disconnecting call
[21:14:43][I][sim800l:036]: Disconnecting...
[21:15:01][I][sim800l:036]: Disconnecting...
```

I don't think if it's even an issue

**Comment by glmnet** [comment]
After merging dev here I am experiencing issues in my test environment, I only have one sim800l in a device "in production" which also has several sensors (adc, dallas, servo, gpio, pulse_counter from the top of my head) and it's not booting properly, I still cannot find the issue by trimming the yaml file so I want to merge `ussd` here so it's complete for docs and ship this

EDIT:
turned out to be a bug in pulse_counter

**Comment by andriej** [comment]
I did compile with 
```
external_components:
  - source: github://pr#3630
    refresh: 0s
    components:
      - sim800l
 ```
so I guess it's with `dev`. maybe GPIO issue then, I have only 3 relays connected tho.

**Comment by andriej** [comment]
Checked (recompiled with latest commits) - still works. :-)

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
