### PR TITLE
[tuya] implement command 0x22 - datapoint-async

### PR DESCRIPTION
**Pull request by christiaanderidder**
# What does this implement/fix?

This change adds support for the synchronous data point report response sent by the tuya MCU.
In my case this is sent by a fan when using the RF remote (which is directly connected to the MCU).

The following error is logged every time the remote is used:
```
[19:01:42][V][tuya:125]: Received Tuya: CMD=0x22 VERSION=3 DATA=[14.01.00.01.00.15.04.00.01.00.17.02.00.04.00.00.01.F4.3C.01.00.01.01.3E.02.00.04.00.00.00.01.3F.04.00.01.00.40.02.00.04.00.00.00.00 (44)] INIT_STATE=3
[19:01:42][E][tuya:297]: Invalid command (0x22) received
[19:01:42][D][uart_debug:114]: <<< 55:AA:03:22:00:2C:14:01:00:01:00:15:04:00:01:00:17:02:00:04:00:00:01:F4:3C:01:00:01:01:3E:02:00:04:00:00:00:01:3F:04:00:01:00:40:02:00:04:00:00:00:00:A0
```

The payload of this command is identical to the asynchronous data point report as documented here:
https://developer.tuya.com/en/docs/iot/tuya-cloud-universal-serial-port-access-protocol?id=K9hhi0xxtn9cb

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** n/a

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment
I have tested this using a ESP12F board connected to a CREATE WINDCALM tuya MCU ceiling fan.

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
external_components:
  # Use custom tuya fork
  - source:
      type: git
      url: https://github.com/christiaanderidder/esphome
      ref: "tuya-invalid-command-0x22"
    components: [ tuya ]

substitutions:
  friendly_name: Bedroom Ceiling Fan
  device_name: bedroom-ceiling-fan
  device_id: bedroom_ceiling_fan
  device_description: ESP12F - CREATE WINDCALM Fan

esphome:
  name: ${device_name}
  comment: ${device_description}
  friendly_name: ${friendly_name}
  
esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: VERBOSE
  baud_rate: 0 # Disable UART logging

# Enable Home Assistant API
api:
  encryption:
    key: !secret encryption_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: on # Don't scan networks, connect straight away
  manual_ip:
    static_ip: 10.0.20.11
    gateway: 10.0.0.1
    subnet: 255.255.0.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}
    password: !secret fallback_ap_password

# Enable web server
web_server:
  port: 80

# Sync time with home assistant
time:
  - platform: homeassistant
    id: homeassistant_time

# Device specific configuration
# CREATE - WINDCALM DC - ceiling fan

uart:
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 9600
  debug:
  
# Register the Tuya MCU connection
tuya:
  id: "tuya_device"
  time_id: homeassistant_time

fan:
  - platform: "tuya"
    id: fan_device
    name: "Fan"
    switch_datapoint: 60
    speed_datapoint: 62
    direction_datapoint: 63
    speed_count: 6
    restore_mode: ALWAYS_OFF

light:
  - platform: "tuya"
    id: light_device
    name: "Light"
    switch_datapoint: 20
    restore_mode: ALWAYS_OFF
```

Logs after running with the fix, with succesfull processing of command 0x22.
```
[20:50:33][C][tuya:041]: Tuya:
[20:50:33][C][tuya:056]:   Datapoint 20: switch (value: OFF)
[20:50:33][C][tuya:062]:   Datapoint 21: enum (value: 0)
[20:50:33][C][tuya:058]:   Datapoint 23: int value (value: 1000)
[20:50:33][C][tuya:056]:   Datapoint 60: switch (value: OFF)
[20:50:33][C][tuya:058]:   Datapoint 62: int value (value: 1)
[20:50:33][C][tuya:062]:   Datapoint 63: enum (value: 0)
[20:50:33][C][tuya:058]:   Datapoint 64: int value (value: 0)
[20:50:33][C][tuya:074]:   Product: '{"p":"p8z27dfdwc4riyp9","v":"1.0.0","m":0}'
[20:50:37][V][tuya:433]: Sending Tuya: CMD=0x00 VERSION=0 DATA=[] INIT_STATE=5
[20:50:37][D][uart_debug:114]: >>> 55:AA:00:00:00:00:FF
[20:50:37][V][tuya:125]: Received Tuya: CMD=0x00 VERSION=3 DATA=[01] INIT_STATE=5
[20:50:37][V][tuya:153]: MCU Heartbeat (0x01)
[20:50:37][D][uart_debug:114]: <<< 55:AA:03:00:00:01:01:04
[20:50:49][V][tuya:125]: Received Tuya: CMD=0x22 VERSION=3 DATA=[14.01.00.01.01.15.04.00.01.00.17.02.00.04.00.00.00.00.3C.01.00.01.00.3E.02.00.04.00.00.00.01.3F.04.00.01.00.40.02.00.04.00.00.00.00 (44)] INIT_STATE=5
[20:50:49][D][tuya:330]: Datapoint 20 update to ON
[20:50:49][D][light:036]: 'Light' Setting:
[20:50:49][D][light:047]:   State: ON
[20:50:49][D][tuya:350]: Datapoint 21 update to 0
[20:50:49][D][tuya:338]: Datapoint 23 update to 0
[20:50:49][D][tuya:330]: Datapoint 60 update to OFF
[20:50:49][V][tuya.fan:030]: MCU reported switch is: OFF
[20:50:49][D][fan:120]: 'Fan' - Sending state:
[20:50:49][D][fan:121]:   State: OFF
[20:50:49][D][fan:123]:   Speed: 1
[20:50:49][D][fan:129]:   Direction: FORWARD
[20:50:49][D][tuya:338]: Datapoint 62 update to 1
[20:50:49][V][tuya.fan:021]: MCU reported speed of: 1
[20:50:49][D][fan:120]: 'Fan' - Sending state:
[20:50:49][D][fan:121]:   State: OFF
[20:50:49][D][fan:123]:   Speed: 1
[20:50:49][D][fan:129]:   Direction: FORWARD
[20:50:49][D][tuya:350]: Datapoint 63 update to 0
[20:50:49][D][tuya.fan:048]: MCU reported reverse direction is: OFF
[20:50:49][D][fan:120]: 'Fan' - Sending state:
[20:50:49][D][fan:121]:   State: OFF
[20:50:49][D][fan:123]:   Speed: 1
[20:50:49][D][fan:129]:   Direction: FORWARD
[20:50:49][D][tuya:338]: Datapoint 64 update to 0
[20:50:49][D][tuya:618]: Setting datapoint 20 to 1
[20:50:49][V][tuya:626]: Not sending unchanged value
[20:50:49][D][uart_debug:114]: <<< 55:AA:03:22:00:2C:14:01:00:01:01:15:04:00:01:00:17:02:00:04:00:00:00:00:3C:01:00:01:00:3E:02:00:04:00:00:00:01:3F:04:00:01:00:40:02:00:04:00:00:00:00:AB
[20:50:52][V][tuya:433]: Sending Tuya: CMD=0x00 VERSION=0 DATA=[] INIT_STATE=5
[20:50:52][D][uart_debug:114]: >>> 55:AA:00:00:00:00:FF
[20:50:52][V][tuya:125]: Received Tuya: CMD=0x00 VERSION=3 DATA=[01] INIT_STATE=5
[20:50:52][V][tuya:153]: MCU Heartbeat (0x01)
[20:50:52][D][uart_debug:114]: <<< 55:AA:03:00:00:01:01:04
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder). 

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
The [documentation](https://developer.tuya.com/en/docs/iot/tuya-cloud-universal-serial-port-access-protocol?id=K9hhi0xxtn9cb#title-14-Report%20status%20(sync)) states:

> The module must respond to each status reporting message. The MCU must not send a new reporting task until receiving a response from the module.

**Comment by christiaanderidder** [comment]
> The [documentation](https://developer.tuya.com/en/docs/iot/tuya-cloud-universal-serial-port-access-protocol?id=K9hhi0xxtn9cb#title-14-Report%20status%20(sync)) states:
> 
> > The module must respond to each status reporting message. The MCU must not send a new reporting task until receiving a response from the module.

I am indeed aware of the required response from ESPHome to the MCU, but did not want to introduce any potentially breaking changes into ESPHome. Without my fix ESPHome receives the command and ignores it, so it also does not give any required response. With my fix the command is parsed and the ESPHome state is updated. So from the MCU's point of view nothing changes, it still sends a command and never gets a response.

I would happily add the "success" response from ESPHome to the MCU, but I am not sure how that would influence the behavior of all existing tuya components that people have configured in ESPHome. Please let me know and will update the PR to include this response.

**Comment by jesserockz** [comment]
I think if we are going to make ESPHome process the new 0x22 command, then we should follow the spec for it and respond.

**Comment by christiaanderidder** [comment]
I've implemented the acknowledgement command, it will always return success as there is currently no way t see if ESPHome correctly processed the command. 

The log below shows the command and acknowledgement:
```
[19:11:57][C][tuya:041]: Tuya:
[19:11:57][C][tuya:056]:   Datapoint 20: switch (value: OFF)
[19:11:57][C][tuya:062]:   Datapoint 21: enum (value: 0)
[19:11:57][C][tuya:058]:   Datapoint 23: int value (value: 0)
[19:11:57][C][tuya:056]:   Datapoint 60: switch (value: OFF)
[19:11:57][C][tuya:058]:   Datapoint 62: int value (value: 1)
[19:11:57][C][tuya:062]:   Datapoint 63: enum (value: 0)
[19:11:57][C][tuya:058]:   Datapoint 64: int value (value: 47)
[19:11:57][C][tuya:074]:   Product: '{"p":"p8z27dfdwc4riyp9","v":"1.0.0","m":0}'
[19:12:01][D][uart_debug:114]: >>> 55:AA:00:00:00:00:FF
[19:12:01][D][uart_debug:114]: <<< 55:AA:03:00:00:01:01:04
[19:12:16][D][uart_debug:114]: >>> 55:AA:00:00:00:00:FF
[19:12:16][D][uart_debug:114]: <<< 55:AA:03:00:00:01:01:04
[19:12:31][D][uart_debug:114]: >>> 55:AA:00:00:00:00:FF
[19:12:31][D][uart_debug:114]: <<< 55:AA:03:00:00:01:01:04
[19:12:35][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
[19:12:40][D][tuya:335]: Datapoint 20 update to ON
[19:12:40][D][light:036]: 'Light' Setting:
[19:12:40][D][light:047]:   State: ON
[19:12:40][D][tuya:355]: Datapoint 21 update to 0
[19:12:40][D][tuya:343]: Datapoint 23 update to 500
[19:12:40][D][tuya:335]: Datapoint 60 update to OFF
[19:12:40][D][fan:120]: 'Fan' - Sending state:
[19:12:40][D][fan:121]:   State: OFF
[19:12:40][D][fan:123]:   Speed: 1
[19:12:40][D][fan:129]:   Direction: FORWARD
[19:12:40][D][tuya:343]: Datapoint 62 update to 1
[19:12:40][D][fan:120]: 'Fan' - Sending state:
[19:12:40][D][fan:121]:   State: OFF
[19:12:40][D][fan:123]:   Speed: 1
[19:12:40][D][fan:129]:   Direction: FORWARD
[19:12:40][D][tuya:355]: Datapoint 63 update to 0
[19:12:40][D][tuya.fan:048]: MCU reported reverse direction is: OFF
[19:12:40][D][fan:120]: 'Fan' - Sending state:
[19:12:40][D][fan:121]:   State: OFF
[19:12:40][D][fan:123]:   Speed: 1
[19:12:40][D][fan:129]:   Direction: FORWARD
[19:12:40][D][tuya:343]: Datapoint 64 update to 46
[19:12:40][D][number:012]: 'Timer': Sending state 46.000000
[19:12:40][D][uart_debug:114]: <<< 55:AA:03:22:00:2C:14:01:00:01:01:15:04:00:01:00:17:02:00:04:00:00:01:F4:3C:01:00:01:00:3E:02:00:04:00:00:00:01:3F:04:00:01:00:40:02:00:04:00:00:00:2E:CE
[19:12:40][D][tuya:623]: Setting datapoint 20 to 1
[19:12:40][D][uart_debug:114]: >>> 55:AA:00:23:00:01:01:24
```

**Review by jesserockz — APPROVED** [review]
> it will always return success as there is currently no way t see if ESPHome correctly processed the command.

This is acceptable =)

Thanks for making those changes.

**Pull request merged**
