### PR TITLE
Dashboard Updates

### LINKED ISSUE #465: Consolidate ESPHome Dashboard
**Describe the problem you have/What new integration you would like**
Add dual / multiple columns in dashboard for nodes. I have quite a few now and need to scroll a lot to get to the last one

**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

Current
current

Proposed Mock up
proposed

### LINKED ISSUE #506: 'Device Type' dropdown list is sticking out of the frame of the wizard.
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
HASS.IO 167
Raspberry Pi3B + SSD boot + Docker
HA 0.95.4
Host system Raspbian GNU/Linux 9 (stretch)

**ESP (ESP32/ESP8266, Board/Sonoff):**
NodeMCU v2 ESP8266

**Affected component:**
-

**Description of problem:**
When I try to create a new configuration with the wizard, I want to set the 'Device Type' from the dropdown list, the list appairs but the list is sticking out of the frame of the wizard. I can see the top items of the list and I can select item very tricky way.

**Problem-relevant YAML-configuration entries:**
-

**Logs (if applicable):**
-

**Additional information and things you've tried:**
A screenshot is attached about the problem.
issue

### LINKED ISSUE #561: Request confirmation when closing editor with changes
**Describe the problem you have/What new integration you would like**
When the editor in the dashboard is about to be closed and changes have been made, request confirmation before discarding the changes.

**Please describe your use case for this integration and alternatives you've tried:**

After having made changes, it is very easy to inadvertently close the editor by clicking slightly left of the line where one wants the cursor to be or by hitting escape after using the search function, discarding all changes. This is a frustrating experience.

### LINKED ISSUE #685: Compact/Condensed view mode for ESPHome UI
**Describe the problem you have/What new integration you would like**
I have many ESPHome devices set up - will soon reach ~20.
It is very frustrating to scroll down in the ESPHome UI to see all statuses and find the one I am looking for.
Currently there are 4 devices displayed on my screen (24" FHD).

There is a lot of empty screen area to fit in much more than 4 devices.

Maybe add an option for compact/condensed view that will place at least 3 devices in each row (there is room) and at least 1 more row (maybe even more) - also consider the option to reduce font/icon sizes if needed.

Alternatively - maybe display a clickable/linked list of devices on the left of the screen

**Please describe your use case for this integration and alternatives you've tried:**
N/A

**Additional context**
N/A

### LINKED ISSUE #781: Hass.io Dashboard edit using iOS Safari
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

General

**Affected component:**

ESPhome Dashboard

**Description of problem:**
Configuration changes can't be saved by using iOS devices and Safari. You can change the config, but it gets lost, when pressing save or upload.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

### LINKED ISSUE #874: Does not save when 'Save' is clicked
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hassio 102/ESPHome add-on
**ESP (ESP32/ESP8266, Board/Sonoff):**

**Affected component:**

N/A

**Description of problem:**
Edits are not saved when 'Save' is clicked.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

### PR DESCRIPTION
**Pull request by jonathanadams**
## Description:
Updates to the dashboard UI interface and the javascript backend.

* Light and dark grey colour scheme
* Added ESPHome logo onto login screen and dashboard
* Implemented a responsive ~two~ three column layout for nodes - Closes esphome/feature-requests#465, Closes esphome/feature-requests#685
* Slimmed down node card with symbols to indicate when update available
* Node cards have coloured tops to denote status (Green = Online, Red = Offline, Yellow = Not Responding, Grey = Unknown)
* Editor can now only be closed by clicking the close button. Clicking outside of the editor window will not close the editor. - Fixes esphome/feature-requests#561
* Editor save now functions correctly on Safari/iOS - Fixed esphome/issues#781, Fixes esphome/issues#874
* Updated wizard - Wizard text now changes to guide first time users through adding their first node. Subsequent runs of the wizard have slimmed down text.
* Wizard board selection now fixed - Fixes esphome/issues#506
* General refactorization and tidy up of HTML and JavaScript files

Submitted as draft as still some work to be done but wanted other peoples opinions.

login

3-col-layout

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

To be completed.

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by mbo18** [comment]
Will also close this request:
https://community.home-assistant.io/t/cosmetic-esphome-addon-dash-device-workflow/147540

**Comment by holdestmade** [comment]
Looks good to me, would 3 colums fit ? there seems to be a lot of white space in the cards.

**Comment by jonathanadams** [comment]
@holdestmade I will adjust the code and post a screenshot of x3 columns later. My only fear with this is long node names spanning over two lines.

**Comment by holdestmade** [comment]
Yes, I see what you mean, but most node names are not that long. Could the path be shortened ? Not sure it really needs `config/esphome/` maybe just the filename ?

**Comment by holdestmade** [comment]
Off topic but how did you get a subtitle in your first node ?

**Comment by mbo18** [comment]
Could the number of columns be dynamic (from number of nodes and screen size)?

**Comment by jonathanadams** [comment]
> Could the number of columns be dynamic (from number of nodes and screen size)?

The number of column is setup to be dynamic based upon the number of nodes present. It then responsively reduces the number of columns as the screen size gets smaller.

https://github.com/esphome/esphome/blob/e0ca329124c99a726bfc37ea784c1ba76a97e28f/esphome/dashboard/static/js/esphome.js#L19-L31

**Comment by jonathanadams** [comment]
3-col-layout

Example of a 3 column layout. I've had to fiddle with the container size to make it work. What do you all think?

Number of columns changes depending on number of nodes in the system:
* >= 12 nodes = 3 column
* >= 6 nodes = 2 column
* <6 nodes = 1 column

**Comment by holdestmade** [comment]
Yes I like it. I have 36 nodes so far so would help greatly.

**Comment by sermayoral** [comment]
Wow, its fantastic. Great job!!

**Comment by holdestmade** [comment]
Does the webserver icon fit OK ?

**Comment by jonathanadams** [comment]
> Does the webserver icon fit OK ?

Yes it does. It goes on the same line as the update icon and the 3 vertical lines. Just realised non of the images show it.

**Comment by holdestmade** [comment]
Yes thats why I asked, great work.

**Comment by jonathanadams** [comment]
I think these are enough changes to start off with.

**Comment by sauloonze** [comment]
Hi @jonathanadams Good job here. Looking forward to use it.

**Comment by jonathanadams** [comment]
@sermayoral thanks for fixing the lint issues.

**Comment by sermayoral** [comment]
> 
> 
> @sermayoral thanks for fixing the lint issues.

@jonathanadams You are welcome :-)

**Comment by glmnet** [comment]
Awesome!

**Comment by holdestmade** [comment]
Look great, any chance of adding an option to sort by node name instead of filename ?

**Comment by theone11** [comment]
Very nice looks good and more useful than before. 

Can you add an option to filter or sort by  online/offline/all.

**Comment by jonathanadams** [comment]
> Very nice looks good and more useful than before.
> 
> Can you add an option to filter or sort by online/offline/all.

I plan on adding filtering/search options in some further updates in the near future. I wanted to get these changes merged and see if any bugs crop up before making further updates.

**Comment by sermayoral** [comment]
@jonathanadams it's quite understandable :-)

**Pull request merged**
