### PR TITLE
Create esp32 rmt addressable light driver

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix?

While trying to move some more devices to esp-idf I realised the addressable led strips were still locked to `neopixelbus` or `fastled` which both require Arduino.

So I decided to write a very basic rmt led strip driver, that has a couple of known chipset timings, and also allows for custom timings in config to allow supporting any others that support driving via RMT.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2902

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
light:
  - platform: esp32_rmt_led_strip
    pin: GPIO27
    num_leds: 1
    chipset: SK6812
    # bit0_high: 300us
    # bit0_low: 900us
    # bit1_high: 600us
    # bit1_low: 600us
    rgb_order: GRB
    rmt_channel: 0
    max_refresh_rate: 10ms
    name: LED Strip
    id: led
    effects:
      - addressable_rainbow:
      - pulse:
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
Marking as draft as it work fine with my atom echo / sk6812, but does not work with a ws2812 for now.

**Comment by jesserockz** [comment]
Ok, fixed that bug. Was to do with multiple leds, not the type

**Comment by jenscski** [comment]
Found this, and tested it with the built in NeoPixel on Adafruit QT Py ESP32 Pico, C3 and S2.
All three of them worked, using IDF on the Pico, and Arduino on the C2 and S2 (I was not able to get IDF to run on these two)

**Comment by mrtoy-me** [comment]
Had Neopixelbus loaded and replaced it with this rmt addressable light component on ESP32-C3 with Arduino then IDF framework using 30 x WS2812 leds with lots of different effects seems to work just fine ... example YAML does not show rmt_channel but worked it out, no problems.
Thanks for your work !

**Pull request merged**
