### PR TITLE
Set up output_switch at priority DATA instead of HARDWARE.

### LINKED ISSUE #1732: ESP32 crashes when LEDc is used
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

I am using docker (`:latest` and `:dev`).

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 on a ESP32dev-Clone from AZDelivery

**ESPHome version (latest production, beta, dev branch)**

`:latest` and `:dev` from dockerhub (pulled today).

**Affected component:**

https://esphome.io/components/output/ledc.html

**Description of problem:**

When I configure an output to use LEDc, the esp crashes immediately on use of that output.

My goal is to have a status LED for a light (on when the light is on and faded when the light is off). That is why I am changing the output in the `on_turn_on` of a switch.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: crash
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "XXX"
  password: "XXXXXXXX"

switch:
  - platform: gpio
    id: light
    pin: 32
    on_turn_on:
        then:
            - output.turn_on: gpio_2
    on_turn_off:
        then:
            - output.turn_off: gpio_2

output:
  - platform: ledc
    id: gpio_2
    pin: GPIO2

debug:

logger:
  level: DEBUG
```

**Logs (if applicable):**

```
[15:53:49]ets Jun  8 2016 00:22:57
[15:53:49]
[15:53:49]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[15:53:49]configsip: 0, SPIWP:0xee
[15:53:49]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[15:53:49]mode:DIO, clock div:2
[15:53:49]load:0x3fff0018,len:4
[15:53:49]load:0x3fff001c,len:1044
[15:53:49]load:0x40078000,len:8896
[15:53:49]load:0x40080400,len:5828
[15:53:49]entry 0x400806ac
[15:53:49][I][logger:166]: Log initialized
[15:53:49][I][app:029]: Running through setup()...
[15:53:49][C][switch.gpio:011]: Setting up GPIO Switch 'light'...
[15:53:49][D][switch:025]: 'light' Turning OFF.
[15:53:49][D][switch:045]: 'light': Sending state OFF
[15:53:49]/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1442 (xQueueGenericReceive)- assert failed!
[15:53:49]abort() was called at PC 0x40088b65 on core 1
[15:53:49]
[15:53:49]Backtrace: 0x4008c730:0x3ffb1b70 0x4008c961:0x3ffb1b90 0x40088b65:0x3ffb1bb0 0x400d9227:0x3ffb1bf0 0x400d1ae1:0x3ffb1c10 0x400d2033:0x3ffb1c40 0x400d204f:0x3ffb1c60 0x401499a5:0x3ffb1c80 0x40149c95:0x3ffb1ca0 0x40149c73:0x3ffb1cc0 0x40149d23:0x3ffb1ce0 0x400d73c7:0x3ffb1d00 0x400d2355:0x3ffb1d20 0x400d1a39:0x3ffb1d50 0x400d2257:0x3ffb1da0 0x400d17a5:0x3ffb1dc0 0x400d17ce:0x3ffb1df0 0x40149ac1:0x3ffb1e10 0x40149b45:0x3ffb1e30 0x400d5c25:0x3ffb1e50 0x400d7325:0x3ffb1ea0 0x400d9d03:0x3ffb1fb0 0x40088e79:0x3ffb1fd0
[15:53:49]
[15:53:49]Rebooting...
```

**Additional information and things you've tried:**

I have googled the problem of an `abort()` in `queue.c` of the IDF, but it seems that that issue can have a number of reasons. Most people seem to have that problem when using an uninitialized mutex...

Re-ordering the output and switch components in the `yaml` is not helping.

### PR DESCRIPTION
**Pull request by duncf**
# What does this implement/fix? 

Changes the setup priority for output_switch, so that it runs after HARDWARE, allowing output_switch to set the state for components that need hardware setup support.

output_switch's setup() method restores the saved state of the
switch. If the underlying output device doesn't get set up until stage
HARDWARE (e.g. ledc), it's possible the switch will try to turn the
device on/off before it's ready.

Arguably, we could move this until much later, or find some way of
setting this up dynamically.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/1732

(This issue is "fixed" already in that it logs a warning instead of crashing. This PR makes it work as intended by restoring switch state.)

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
output:
    # Buzzer connected between 19 and Ground
  - platform: ledc
    pin: 19
    id: buzzer
    frequency: 100Hz
switch:
  - platform: output
    name: Buzzer
    id: buzzer_out
    output: buzzer
    on_turn_on:
    - output.set_level:
        id: buzzer
        level: "50%"
    on_turn_off:
    - output.set_level:
        id: buzzer
        level: "0%"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
I would much rather this be HARDWARE - <some value> 
or
Add a new AFTER_HARDWARE priority to be used for things like this as DATA doesnt really fit and could just get confusing

**Comment by oxan** [comment]
I think at some point we're gonna have to bit the bullet and create a dependency-based setup system, as we keep running into issues like this...

**Comment by duncf** [comment]
From [component.h](https://github.com/esphome/esphome/blob/dev/esphome/core/component.h):
```
// ...
/// For components that deal with hardware and are very important like GPIO switch
extern const float HARDWARE;
/// For components that import data from directly connected sensors like DHT.
extern const float DATA;
/// Alias for DATA (here for compatibility reasons)
extern const float HARDWARE_LATE;
/// For components that use data from sensors like displays
extern const float PROCESSOR;
// ...
/// For components that should be initialized at the very end of the setup process.
extern const float LATE;
```

I picked `DATA` because it seemed like the right level for things that might depend on hardware being setup (as it does, in the case of an output switch depending on ledc).

@jesserockz are you suggesting adding a new level between `HARDWARE` and `DATA` / `HARDWARE_LATE`?

Generally I agree that there's not a one-size-fits-all-solution here, but `DATA` feels like a better default than `HARDWARE`. Another option would be to use `LATE`, since all the output switch setup is doing is restoring previous values. Would anybody depend on the restored value of an output switch while setting up another component?

**Comment by paulmonigatti** [comment]
> @jesserockz are you suggesting adding a new level between `HARDWARE` and `DATA` / `HARDWARE_LATE`?

I see a few components that use intermediate priorities, e.g. `get_setup_priority() const { return setup_priority::HARDWARE - 1.0f; }`

I'd agree with Oxan's comment that a proper dependency-based system is the preferred way to go, since using priorities to ensure the correct ordering of dependencies is rather error-prone. But until that is done, I don't see an issue with bumping the priority one step down from `HARDWARE`.

> Generally I agree that there's not a one-size-fits-all-solution here, but `DATA` feels like a better default than `HARDWARE`. Another option would be to use `LATE`, since all the output switch setup is doing is restoring previous values. Would anybody depend on the restored value of an output switch while setting up another component?

As I understand it, `LATE` components will only be loaded after a Wi-Fi connection is established. This delay would be excessive, and unnecessary.

**Comment by jesserockz** [comment]
> I see a few components that use intermediate priorities, e.g. get_setup_priority() const { return setup_priority::HARDWARE - 1.0f; }

Yeah my comment was meant to have something like 1.0f at the end of the first line but I must have forgot to type it.. Haha

`return setup_priority::HARDWARE - 1.0f;` would be fine for now.

As Oxan said a better system is needed

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
