### PR TITLE
Add mcp23008 support

### LINKED ISSUE #41: MCP 23008
I see esphomelib already supports the pcf8574 I/O expander. I am working on a project that uses an MCP23008 I/O expander. Do you know if they are similar enough to just modify the existing code of the pcf8574 to use with the MCP23008? I am woking with an NCD.io 2 relay board that uses an ESP8266 communication module to talk to the MCP23008 on the board over I2C.

### PR DESCRIPTION
**Pull request by TomFahey**
## Description:

Added support for mcp23008 io expander, based on existing support for mcp23017.

**Related issue (if applicable):** fixes <https://github.com/esphome/feature-requests/issues/41>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#277

## Checklist:
  - [y] The code change is tested and works locally.
  - [y] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [y] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — COMMENTED** [review]
Code looks good to me on a first quick look 👍

**Comment by TomFahey** [comment]
I'm not sure why the build is failing...? I can't see anything wrong with how the brackets are laid out?

**Comment by brandond** [comment]
I'm guessing it's a whitespace change - there's either trailing whitespace after it, or you have tabs instead of spaces.

**Comment by S-Przybylski** [comment]
Dear @TomFahey 
dear @OttoWinter 
i am interrested in using ESPHOME with MCP23008 too. 
Could you be so kind to check, why the check failed? For me it seems to be a minor problem.
Thanks a lot

**Comment by TomFahey** [comment]
Sorrry, I forgot about this! I fixed a couple typos and it passes all the tests now, so I think it should be ok to merge?

**Review by OttoWinter — APPROVED** [review]
Thanks!

**Pull request merged**
