### PR TITLE
Revert "Add option flip_x (#4555)"

### LINKED ISSUE #4432: [MAX7219digit] flip_x commit breaks reversed display
### The problem

The last [commit ](https://github.com/esphome/esphome/pull/4555) from @rafal83 breaks rotated and reversed displays. My clock is installed upside down so i used to rotate & flip it and it worked fine:
```
    rotate_chip: 180
    reverse_enable: true
```
But with that commit the display is completely broken(see details)

### Which version of ESPHome has the issue?

2023.04

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.3

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

MAX7219digit

### Example YAML snippet

```yaml
display:
  - platform: max7219digit
    cs_pin: GPIO25
    num_chips: 4
    intensity: 0
    rotate_chip: 180
    reverse_enable: false
    flip_x: false
    lambda: |-
      it.print(0, 5, id(digit_font), TextAlign::CENTER_LEFT, "1234567890");

```
<details>

image

</details>

==========================================================================

    reverse_enable: false
    flip_x: true

<details>

image

</details>

==========================================================================

    reverse_enable: true
    flip_x: true

With reverse enable the text is even duplicated from both directions
<details>

image

</details>

==========================================================================

    reverse_enable: true
    flip_x: false

<details>

image

</details>

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by voed**
This reverts commit a31fb3c. 

# What does this implement/fix?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4432 and https://github.com/esphome/issues/issues/4437

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation :** https://github.com/esphome/esphome-docs/pull/2863

## Test Environment

- [x] ESP32

## Checklist:
  - [x] The code change is tested and works locally.

### CODE REVIEW

**Comment by jesserockz** [comment]
I don't understand how deleting this feature is making any difference for you. If its set to `false` in config, it is basically the exact same code as if the feature was never there...

**Comment by voed** [comment]
> I don't understand how deleting this feature is making any difference for you. If its set to `false` in config, it is basically the exact same code as if the feature was never there...

See related issues for the detailed explanation. It is not.

**Comment by voed** [comment]
Also i do not really understand what it should do. Isn't it the same as 'reverse' feature we already have?

**Comment by ssieb** [comment]
There was a bug in the python code, fix is in https://github.com/esphome/esphome/pull/4727
This feature flips each block individually, not the whole display like reverse does.

**Pull request closed without merging**
