### PR TITLE
Tm1637 binarysensor

### PR DESCRIPTION
**Pull request by mvturnho**
# What does this implement/fix? 
This changes implements the keyboard circuit as binary_sensors for the tm1637 display controller

Quick description and explanation of changes
Added TM1637Key class to process the keycodes
Added list with binarysensors to TM1637Display to store and process the keypresses

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1653

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x ] ESP8266

## Example entry for `config.yaml`:

```yaml
display:
  - platform: tm1637
    id: dsp1
    clk_pin: GPIO14
    dio_pin: GPIO12
    update_interval: 500ms
    lambda: |-
        static int i = 0;
        i++;
        if ((i % 2) == 0)
          it.strftime("%H.%M", id(homeassistant_time).now());
        else
          it.strftime("%H%M", id(homeassistant_time).now());

binary_sensor:
  - platform: tm1637
    id: key0
    name: key1-00
    tm1637_id: dsp1
    key: 0
  - platform: tm1637
    id: key1
    name: key1-01
    tm1637_id: dsp1
    key: 1
  - platform: tm1637
    id: key2
    name: key1-02
    tm1637_id: dsp1
    key: 2

```

## Checklist:
  - [* ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [* ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
Awesome. Can you explain in docs how to connect the buttons?

**Comment by mvturnho** [comment]
> Awesome. Can you explain in docs how to connect the buttons?

Hi I have updated the documentation as well. 
https://deploy-preview-1653--esphome.netlify.app/components/display/tm1637.html

I have described (using the datasheet) how to connect the buttons to the display controller and how to use only as many pins as there are displays connected. So use two pins for one display, and two pins for two displays. 3 pins for 3 displays etc.

**Comment by mvturnho** [comment]
> Awesome. Can you explain in docs how to connect the buttons?

Hi @glmnet any chance this PR gets committed?

**Comment by glmnet** [comment]
LGTM, please add an entry in a test file for the binary sensor. 
Also there is a small merge conflict to fix.
Thanks

**Review by glmnet — APPROVED** [review]

**Pull request merged**
