### PR TITLE
[ILI9xxx] Update ili9xxx_init.h code for the ILI9488 display for correct white balance

### PR DESCRIPTION
**Pull request by lucasreiners**
# What does this implement/fix?

Recently I had a project using an ILI9488 based display. I found out, that the white balance of the display is incorrect - during the initialization sequence of the display, some gamma values are set, which I improved in this pull request (I also used the official documentation for the display, but tweaked the values further.

You can see the difference in the following image (left is AFTER the change, right is BEFORE - the large numbers on the right are now displayed correctly in white, on the right with the existing init code, the values are displayed in a light blue instead of white):
CDA8ACB4-EC1D-4210-A950-FF938F080D98-COLLAGE

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** n/a

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** 
n/a

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by nielsnl68 — APPROVED** [review]
looks very nice.

**Comment by kroimon** [comment]
Are these gamma values usable for all displays based on the ILI9488 or might it depend on the actual panel?

Where did the previous values come from? Were they just copied from somewhere else and are really bad or do they just not fit to your panel?

**Comment by nielsnl68** [comment]
yes, i copied from one of the existing gui lib's .

**Review by kroimon — APPROVED** [review]

**Comment by lucasreiners** [comment]
Thank you for your review, I had to rebase on the latest changes, so the approvals have been reset.

@kroimon thank you for the questions - whether these values fit every panel, I cannot answer, at least for my panel they did not fit. Unfortunately, I dont have any other 9488 based displays from another vendor, so I cannot test any further. :/

**Comment by kroimon** [comment]
> Unfortunately, I dont have any other 9488 based displays from another vendor, so I cannot test any further. :/

As even @nielsnl68 approves as the code owner, I would suggest just running a scream test then: merge this PR and if it breaks for someone else, they will scream 😉

**Comment by lucasreiners** [comment]
> > Unfortunately, I dont have any other 9488 based displays from another vendor, so I cannot test any further. :/
> 
> As even @nielsnl68 approves as the code owner, I would suggest just running a scream test then: merge this PR and if it breaks for someone else, they will scream 😉

Sounds great! 😄 
@nielsnl68 feel free to merge, if you second this approach

**Pull request merged**
