### PR TITLE
climate: add support for quiet fan mode

### PR DESCRIPTION
**Pull request by MichaelMure**
# What does this implement/fix?

This PR add support for a "quiet" fan mode, which would be used in at least two components: fujitsu_general and toshiba

At least for toshiba, "quiet" mode is a separate thing as the classic "low". It's actually a variant of "auto" where **the fan can actually go to lower speed than the lowest manual speed**, and then be more silent. Great for sleeping.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [X] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Checklist:
  - [ ] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs): https://github.com/esphome/esphome-docs/pull/2160

### CODE REVIEW

**Comment by MichaelMure** [comment]
Draft PR for now as I'm a bit unsure how to actually run that code and I want to run the CI. I likely have a broken python environment so `python3 esphome run foo.yaml` return an unrelated `ImportError: cannot import name 'DNSAddress' from partially initialized module 'zeroconf' (most likely due to a circular import) (/home/michael/dev/esphome/esphome/zeroconf.py)`.

**Comment by MichaelMure** [comment]
Ready for review to have some eyes on this.

**Comment by OttoWinter** [comment]
> `python3 esphome run foo.yaml`

Use `esphome run foo.yaml` or `python3 -m esphome run foo.yaml`. With the command above you're starting `esphome/__init__.py` as `__main__` (and so the python paths are messed up and the zeroconf import fails)

**Comment by OttoWinter** [comment]
LGTM, please also update https://github.com/esphome/aioesphomeapi/ (communication library for HA) and https://github.com/home-assistant/core/ (HA bindings). Otherwise you won't see the new mode show up in HA.

**Comment by MichaelMure** [comment]
@OttoWinter done with:
- https://github.com/esphome/aioesphomeapi/pull/232
- https://github.com/home-assistant/core/pull/74303

**Review by kbx81 — APPROVED** [review]
LGTM also 🙂

**Comment by MichaelMure** [comment]
@OttoWinter can we merge so that I can add the quiet fan support in https://github.com/esphome/esphome/pull/3607?

**Comment by MichaelMure** [comment]
@OttoWinter friendly ping, it'd be nice to move forward now that every sign is green, so I can bubble up things up to homeassistant.

**Comment by MichaelMure** [comment]
@OttoWinter can we merge?

**Comment by kbx81** [comment]
Otto may be away/back at university -- maybe we could get @jesserockz to be another set of eyes? I'm not sure I know enough about the API bits/related PRs to properly review, but the thermostat and climate stuff lgtm. 🙂

**Comment by kbx81** [comment]
It also looks like you need to rebase https://github.com/esphome/aioesphomeapi/pull/232 and you have some feedback to address on https://github.com/home-assistant/core/pull/74303/files 🙂

**Comment by MichaelMure** [comment]
> It also looks like you need to rebase https://github.com/esphome/aioesphomeapi/pull/232 and you have some feedback to address on https://github.com/home-assistant/core/pull/74303/files

True but I'm waiting for this to be safely in to do the finishing touch.

**Comment by MichaelMure** [comment]
@jesserockz a bit of help over here? PR is ready and approved, just need to be merged.

**Comment by jesserockz** [comment]
@MichaelMure Before I merge this and https://github.com/esphome/aioesphomeapi/pull/232, can you show it works via Home Assistant? I see there is some unresolved conversations on https://github.com/home-assistant/core/pull/74303 too. 

I just want to make sure all parts work together properly before I start merging

**Comment by vassil-vassilev** [comment]
Any estimate when this is going to be merged as it blocks other related PRs (#3607 and home-assistant/core#74303)?

**Review by jesserockz — APPROVED** [review]

**Comment by MichaelMure** [comment]
Yes! Thank you @jesserockz !

**Pull request merged**
