### PR TITLE
Add backlight handling for lcd_pcf8574

### LINKED ISSUE #160: PCF8574 LCD backlight control.
**Describe the problem you have/What new integration you would like**

PCF8574 LCD display backlight control. ON/OFF and brightness.

**Please describe your use case for this integration and alternatives you've tried:**

Sonoff-tasmota has ON/OFF function for this display.

**Additional context**

Goal is to automate display backlight to save energy. Éxample use in sauna where temperature goes above 50C turn backlight ON.

### PR DESCRIPTION
**Pull request by adarazs**
Switch the backlight on or off in the display lambda with
it.backlight() and it.no_backlight().

## Description:

I moved my display node from my home brew firmware to ESPHome and this is a missing functionality for me. I also saw it requested by others (see related issue). This is my first pull request here, so please let me know if something doesn't look good.

I adopted the usual Arduino library function names of `backlight()` and `noBacklight()` (changed to `no_backlight()` to fit the coding style guide) that are used to control backlight in other LCD libraries.

Also I want to say thank you for the ESPHome project, it's super nice and well thought out, especially the integration with Home Assistant. I'm in awe how easy it was to re-implement most of my nodes with just a few lines of yaml.

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/160

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** The lcd commands are not really documented in the [lcd_display](https://esphome.io/components/display/lcd_display.html) section, so I didn't want to start adding the backlight ones now.

## Checklist:
  - [x] The code change is tested and works locally. (I have a small yaml where I can trigger the backlight on/off with a button and the node keeps working after.)
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder). -- I'm not sure this is necessary, but let me know if I should add an `it.no_backlight();` [here](https://github.com/esphome/esphome/blob/1ce257c721f454d492bf60eb980f197f88fd7b06/tests/test1.yaml#L1130)

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). https://github.com/esphome/esphome-docs/pull/261

### CODE REVIEW

**Comment by adarazs** [comment]
Hmm, so the test failed because I didn't implement the backlight and no_backlight() functions in the `GPIOLCDDisplay` class as well. Question: would you like me to implement dummy functions there? The alternative solution is more complicated:

I started out by adding the backlight functions directly to the `PCF8574LCDDisplay` class, but unfortunately the code generation is written in a way that `it` doesn't refer to the correct subclass, but to the `LCDDisplay` class. This is from my generated main.cpp file:

    ifaction = new IfAction<>(lambdacondition);
    lcd_pcf8574_pcf8574lcddisplay->set_writer([=](lcd_base::LCDDisplay & it) -> void {
        // content of the lambda here
    });

I was still able call the function with `id(lcd_pcf8574_pcf8574lcddisplay).no_backlight();` but I think most users would expect `it.no_backlight()` to work.

I tried to override the lambda generation in [`display.py`](https://github.com/esphome/esphome/blob/dev/esphome/components/lcd_pcf8574/display.py) but I cannot, because it's defined in the [`__init__.py` of lcd_base](https://github.com/esphome/esphome/blob/1ce257c721f454d492bf60eb980f197f88fd7b06/esphome/components/lcd_base/__init__.py#L32-L35y).

So I will need to remove that definition in the base class's init file, and then separately define the lambda it substitution for both `lcd_gpio` and `lcd_pcf8574`. I have a sort of working solution for this, but I thought it's a lot less elegant than defining the functions in the base.

Please let me know which solution do you prefer.

**Comment by OttoWinter** [comment]
Yep that's a problem. I don't really like adding it as a stub to gpiolcd. So I'd suggest copying the line that sets the write lambda into both sub python files.

**Comment by adarazs** [comment]
@OttoWinter Okay, so I made the change, I think this is is sort of how it should look, based on the lcd_base class and similar display classes like nextion and max7219. It even compiles and uploads for me, but now I broke the whole system somehow and the node doesn't go on the wifi or display anything.

Before I get to a lengthy debugging, can you please take a look at the current commit and see if you can spot my mistake? It's really hard to get my head around the code generation parts of the project for now.

**Comment by OttoWinter** [comment]
The problem is that writer_ is defined in both the base class and the subclass. The base class will access it's own member var hwne trying to write. But that's empty and results in an exception.

Make an abstract function that calls writer and implement it in both subclasses.

**Comment by adarazs** [comment]
Thank you! Will get back to it in the evening and fix the lint errors too.

**Comment by adarazs** [comment]
@OttoWinter I spent a couple of hours trying to understand this and I don't know how to solve this situation the nice way. I understand the problem with the multiple declaration of `writer_`. But I need to declare it in some way in the `LCDDisplay` base class, because the [`update` function calls it](https://github.com/esphome/esphome/blob/8be733efee993fe992de14c27ce8b88838c81c76/esphome/components/lcd_base/lcd_display.cpp#L110). But it would need to have different type in each subclass. I cannot make anything an abstract function there.

I cannot make the `set_writer` function abstract either because they use different types as arguments in the subclasses (and that's pretty much what I want to achieve here so that I can call the backlight functions from the lamda). I have a vague feeling this could be solved with some function templating, but I'm not good at that either and I can't refactor the code easily to do that.

So for now I pushed a simple solution that won't solve the `it.no_backlight()` calling, but will work with `id(mydisplay).no_backlight()`. If you can tell me how to solve the previous issue exactly I can give it another go, but otherwise I don't think I can do it myself.

**Comment by OttoWinter** [comment]
I updated the PR now with a solution which I think will work.

Basically, to solve the `writer_` thing I created an abstract function in the base class which should call the appropriate writer. Both subclasses implement this and have their own writer_.

Let me know if it works

**Comment by adarazs** [comment]
I tried and works using `it.backlight();` and `it.no_backlight();` in the display lamda. Thanks! I think this is good to go. I really couldn't have figured out the proper types of `writer_`, this c++ stuff is sometimes beyond me. :)

**Comment by OttoWinter** [comment]
Great! This will also require a bit of docs; can you add a small note on the LCD page for PCF8574 about this?

**Comment by adarazs** [comment]
Sure, I will make a pull request against the docs too.

**Comment by adarazs** [comment]
Here it is: https://github.com/esphome/esphome-docs/pull/261

**Comment by rradar** [comment]
Sorry to bother. Right now I use the hardware hack to get the back light. I use it to turn automatic on when motion is triggered. Is this still possible with this (software) implementation?

**Comment by OttoWinter** [comment]
@rradar Yes

**Comment by davericher** [comment]
+1

**Review by OttoWinter — APPROVED** [review]

**Comment by davericher** [comment]
@rradar unsure if this works with all lcd_pcf8574 controllers. Certainly is not doing anything on mine, jumper is closed, does not break anything, just has no effect.

**Comment by adarazs** [comment]
@davericher it's entirely possible that not all of these i2c boards are created equal, but maybe it's something with your yaml definition. How are you testing it, care to share the code?

**Comment by davericher** [comment]
I can assure you it is not the yaml. No big deal, if I wanted this control I would have just unlatched the dip and did it manually, just thought you should know this is probably not universal, something you may want to include in the documentation on it.

**Comment by adarazs** [comment]
I messed up twice while trying to test this, resulting in a flickering, almost always on display. So I'd rather trust a few lines of reproducer than an assurance. But of course if you want to write a doc change and @OttoWinter wants to merge it, fine by me. Just not enough evidence for me to write a warning about it myself.

**Comment by davericher** [comment]
When the next person reads this wondering if it works on everything, kindly leave a comment :D

**Comment by OttoWinter** [comment]
@davericher @adarazs It's probably the hw - backlight is done by setting the MSB for the PCF8574. If that pin is not wired up to the backlight pin on the LCD display it won't work.

**Comment by VincenzPa** [comment]
Hi there,
maybe i'm stupid but still get the same error trying to compile with VSC:

src\main.cpp: In lambda function:
src\main.cpp:685:10: error: 'class esphome::lcd_base::LCDDisplay' has no member named 'no_backlight'
it.no_backlight();
^

any suggestion?

**Comment by adarazs** [comment]
@VincenzPa This is the error you would get if you'd try to compile the code before this pull request. My guess would be that you either are not using the latest code from the dev branch (it's not in any release yet) or you need to make sure you have a clean environment. Try deleting the `<name of your node>` folder from where you run `esphome <name of your node>.yaml run` command from to clean things up.

**Comment by VincenzPa** [comment]
@adarazs I'm using the normal release, updated to the last. Deleted the folder to not mess with the old something but still have the same error. May be the board i'm using, esp32doit-devkit-v1. Need to assemble one similar with ESP8266 .

**Comment by adarazs** [comment]
@VincenzPa As I said, this pull request is not part of any release yet, so if you have the latest code from pip it's expected to not work for you. It's merged in the dev branch. You need to clone it from github, switch to the dev branch and install esphome from there with `python setup.py develop` to get this code and use it.

Some more details here: https://esphome.io/guides/contributing.html#setting-up-git-environment -- if it looks too complicated just wait for the next release that will probably have it.

**Comment by VincenzPa** [comment]
Thank you, didn't understood before. Right now i look at the header and saw "esphome:dev".

**Pull request merged**
