### PR TITLE
[esp32] Bump recommended IDF to 5.1.2 and platform to 6.5.0

### PR DESCRIPTION
**Pull request by kbx81**
# What does this implement/fix?

I saw #7349 and remembered that it's coming time to do this...maybe not just yet, but I'm putting this out there so it's a little bit more "on the radar". I'm not sure if this is all we need to do to bump the versions, but a quick smoke test here seems to indicate that it's working as expected.

Our build tests in CI have been running against this IDF/platform combination for at least a couple of releases now.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
Any reason we can't got to [5.1.4](https://github.com/espressif/esp-idf/releases/tag/v5.1.4) It looks like all the same BLE fixes are in there ?

**Comment by randybb** [comment]
Because it is not supported by platformio. The latest one is ESP-IDF 5.1.2 supported from [6.5.0](https://github.com/platformio/platform-espressif32/releases/tag/v6.5.0). The next options are 5.2.1 from 6.6.0 and 5.3.0 from 6.8.0

**Comment by kbx81** [comment]
@bdraco it doesn't appear that specific patch version is available: https://registry.platformio.org/tools/platformio/framework-espidf/versions

While I have your attention... 😏 ...have you done any Bluetooth testing with IDF 5.1? 😄

**Comment by bdraco** [comment]
> @bdraco it doesn't appear that specific patch version is available: [registry.platformio.org/tools/platformio/framework-espidf/versions](https://registry.platformio.org/tools/platformio/framework-espidf/versions)

That's unfortunate
> 
> While I have your attention... 😏 ...have you done any Bluetooth testing with IDF 5.1? 😄

I haven't yet, but I suspect we will have the same issues we are having now with the scanner stopping until we can get to a version with the same fixes as 4.4.8

**Comment by jesserockz** [comment]
Making this a draft until at least after this coming release.

**Comment by bdraco** [comment]
Once 5.1.4 is available on platformio, please ping me and I'll do bluetooth testing

**Comment by nielsnl68** [comment]
I know this will give a lot of work: would it not better to go directly to the latest version 5.3.1?

maybe we could start in a new branch like "IDF-3.5.1" and put there only the most importent components in it and move the other components into a new folder named "external" then we can test the components on after the other.

**Comment by kbx81** [comment]
> I know this will give a lot of work: would it not better to go directly to the latest version 5.3.1?
> 
> maybe we could start in a new branch like "IDF-3.5.1" and put there only the most importent components in it and move the other components into a new folder named "external" then we can test the components on after the other.

@nielsnl68 we are trying to not make such a big jump. We chose 5.1 is because that is what [arduino-esp32](https://github.com/espressif/arduino-esp32/blob/1a42b87fb5a92e25596cff10ebe563a85b847fab/idf_component.yml#L44-L45) is using for 3.0. It would be nice to keep consistent with that as it (I think) maximizes compatibility as people move between pure IDF & Arduino. Also, as we move closer to 5.2/5.3+, we're going to find we have more and more work to do to patch components to support that. Even just getting to 5.0/5.1 took quite a few changes to build everything without errors.

What I'm unclear on is if we will ever get a 5.1.4 platformio package we can use. I don't see a clear pattern to the releases going on there and, if we don't get a 5.1.4+ package, we may have to consider moving to 5.2 or later. I'm not sure exactly which (set of) fixes @bdraco is looking for so I can't say myself if 5.2+ is an option, either.

**Comment by nielsnl68** [comment]
@kbx81 i'm fully aware of the issues that would popup using IDF 5.3+, Before checking i through the Arduino V3.0.4 was already based on 5.3+ but i did not remembered it correctly.

The Main reason i pointed the above out is that i was shocked to see that 4.4.8 was the last bugfix version before it was out of support, (the espresif documentation already starting from version 5.0.7.



Anyway It is good that you already think forward.

**Comment by nielsnl68** [comment]
@kbx81 good to see that you jumped ahead to test newer versions🥰. 
Small question; are you adding the needed fixes in this PR as well or is there a related PR that will have them?

**Comment by kbx81** [comment]
Given that we have been testing against IDF 5.1.2 for multiple releases now, I expect there should be no other changes required. If there are, however, they will go into separate PRs.

**Comment by randybb** [comment]
I have noticed probably only '#warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"' (yea, I know, it is a warning, but you know pleople...)

**Comment by kbx81** [comment]
> I have noticed probably only '#warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"' (yea, I know, it is a warning, but you know pleople...)

Yes, that's not new; our components that use the RMT are going to need some refactoring to get rid of the warnings. I gather the interface has changed a good bit from IDF 4.x. Regardless, I've been using IDF 5.x on my IR blasters and LED controllers for well over a year now without any issues at all -- so I would assert that it works just fine as-is.

**Comment by swoboda1337** [comment]
> I have noticed probably only '#warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"' (yea, I know, it is a warning, but you know pleople...)

Why has no one updated this? Is no one working on it? I would be will to give it a go?

**Comment by kbx81** [comment]
> > I have noticed probably only '#warning "The legacy RMT driver is deprecated, please use driver/rmt_tx.h and/or driver/rmt_rx.h"' (yea, I know, it is a warning, but you know pleople...)
> 
> Why has no one updated this? Is no one working on it? I would be will to give it a go?

@swoboda1337 if you'd like to give it a go, please do! You might also ask in Discord if anyone is known to be working on it, but I don't recall any discussion about it outside of this thread/PR.

**Comment by luar123** [comment]
How about switching to the pioarduino fork: https://github.com/pioarduino/platform-espressif32/releases/tag/51.03.05
They have support for v5.1.4 (and arduino 3) and additionally added esp32-c2 and esp32-h2 boards that are still missing in the official pio releases.
Goal of this fork is to maintain a community pio package because official pio lacks support for some chips and arduino 3 (and no plan to include so far).
Also see: https://github.com/esphome/feature-requests/issues/1397#issuecomment-2302109714

**Comment by kbx81** [comment]
> How about switching to the pioarduino fork: [pioarduino/platform-espressif32@`51.03.05` (release)](https://github.com/pioarduino/platform-espressif32/releases/tag/51.03.05) They have support for v5.1.4 (and arduino 3) and additionally added esp32-c2 and esp32-h2 boards that are still missing in the official pio releases. Goal of this fork is to maintain a community pio package because official pio lacks support for some chips and arduino 3 (and no plan to include so far). Also see: [esphome/feature-requests#1397 (comment)](https://github.com/esphome/feature-requests/issues/1397#issuecomment-2302109714)

I think that, in the long-term, it's pretty clear that we won't have much choice -- or else we'll have to refactor ESPHome to not depend on pio at all. Jesse and I had already discussed (very much in passing) building & using our own pio packages. I guess we'll have to have a longer/deeper discussion about that sooner rather than later. haha

**Comment by kbx81** [comment]
I'm turning my attention back at this a bit this week.

@luar123 if you want to try using the pioarduino fork, you can do this:
```yaml
esp32:
  board: ...
  framework:
    type: esp-idf
    version: 5.1.4
    source: https://github.com/pioarduino/esp-idf/releases/download/v5.1.4.240921/esp-idf-v5.1.4.zip
    platform_version: https://github.com/pioarduino/platform-espressif32/releases/download/51.03.05/platform-espressif32.zip
```
I've found it works quite nicely on an S3 board I'm playing around with here.

**Comment by luar123** [comment]
> @luar123 if you want to try using the pioarduino fork, you can do this:
> [...]
> I've found it works quite nicely on an S3 board I'm playing around with here.

Thanks, I also tried this and it works well on a C3 example I am running now and additionally on a H2 board with my experimental zigbee component.

**Comment by kbx81** [comment]
Superseded by #7706

**Pull request closed without merging**
