### PR TITLE
Inkplate 6 PLUS

### LINKED ISSUE #1570: Inkplate 6PLUS
Hello,

I have been experimenting with the inkplate 6 plus for a few days now. 

I noticed that ESPHome supports inkplate 6 & 10, and was wondering if the 6 PLUS will be added to the compatible models. 

Best Wishes,
Josh.

### LINKED ISSUE #2944: inkplate6 configured with model inkplate_10 has incorrect buffer size until first full update in 1 bit mode
### The problem

Prerequisites:

- Have an inkplate10-device
- Use inkplate6 component
- configured with model "inkplate_10"
- configured with greyscale/partial update set to defaults

The first partial updates before a full update will render incorrectly, as demonstrated in the two screenshots here: https://imgur.com/a/IwqidsA

The lambda used to draw the image is written in the example yaml.

### Which version of ESPHome has the issue?

2a8668ea60ea51a5906efac7c89e1c1baab1d23a

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

inkplate6

### Example YAML snippet

```yaml
esphome:
  name: inkplate10
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "pwpwpw"

wifi:
  ssid: "fofofo"
  password: "afafaf"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Inkplate10 Fallback Hotspot"
    password: "momomo"

captive_portal:


switch:
  - platform: restart
    name: "Inkplate Reboot"
    id: reboot

  - platform: gpio
    id: battery_read_mosfet
    pin:
      mcp23xxx: mcp23017_hub
      number: 9
      inverted: true

  - platform: template
    name: "Inkplate Greyscale mode"
    lambda: return id(inkplate_display).get_greyscale();
    turn_on_action:
      - lambda: id(inkplate_display).set_greyscale(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_greyscale(false);


sensor:
  - platform: adc
    id: battery_voltage
    update_interval: never
    attenuation: 11db
    pin: 35

i2c:

mcp23017:
  - id: mcp23017_hub
    address: 0x20

binary_sensor:
  - platform: status
    name: "Inkplate Status"
    id: system_status

  - platform: gpio
    name: "Inkplate Touch Pad 1"
    pin:
      mcp23xxx: mcp23017_hub
      number: 10
  - platform: gpio
    name: "Inkplate Touch Pad 2"
    pin:
      mcp23xxx: mcp23017_hub
      number: 11
  - platform: gpio
    name: "Inkplate Touch Pad 3"
    pin:
      mcp23xxx: mcp23017_hub
      number: 12

display:
- platform: inkplate6
  id: inkplate_display
  model: inkplate_10
  update_interval: 60s

  ckv_pin: 32
  sph_pin: 33
  gmod_pin:
    mcp23xxx: mcp23017_hub
    number: 1
  gpio0_enable_pin:
    mcp23xxx: mcp23017_hub
    number: 8
  oe_pin:
    mcp23xxx: mcp23017_hub
    number: 0
  spv_pin:
    mcp23xxx: mcp23017_hub
    number: 2
  powerup_pin:
    mcp23xxx: mcp23017_hub
    number: 4
  wakeup_pin:
    mcp23xxx: mcp23017_hub
    number: 3
  vcom_pin:
    mcp23xxx: mcp23017_hub
    number: 5


  lambda: |-
    it.fill(COLOR_ON);
    it.line(0, 0, 1200, 825, COLOR_OFF);
    it.line(1200, 0, 0, 825, COLOR_OFF);
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

Using the example config, the lambda is set to draw a X over the entire inkplate10-display. It will only look correct after the first partial update, which happens after 10 minutes.

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix? 

Adds support for the Inkplate 6 Plus and pulls in some changes from the Inkplate Arduino library to speed things up.

Also fixes esphome/issues#2944 by forcing a full update for first render when using partial updates.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** closes https://github.com/esphome/feature-requests/issues/1570
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1887

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jjhuff** [comment]
Thanks for this!

I only ran into:
* The occasional "Power supply not detected", but haven't been able to narrow it down.
* Partial updates seem broken with a corrupt display that gradually lightens. This sorta feels like it's not related to this PR, but I don't have an inkplate 6 or 10 to test with.

**Comment by jesserockz** [comment]
Thanks for the feedback @jjhuff 

- I will keep an eye out for `Power supply not detected`, it would happen when the code tries to turn on the eink and it doesn't come on fast enough.

- Yeah I have noticed the partial update thing. When I run an example sketch from the Inkplate Arduino repo it also does this.

**Comment by mkocus** [comment]
@jesserockz It's running great.

Also, I wonder if the clearing screen twice during full update is necessary? Some guy here:
https://forum.e-radionica.com/en/viewtopic.php?f=22&t=418
says that only one is enough.

EDIT: I've forked esphome repo and tested that change locally - and it seems that 1 pass of screen full refresh is indeed working correctly.
EDIT2: I've checked your code and it seems that you have implemented latest changed from Arduino lib (maybe without changing the MCP23017 port extender ports to outputs/low to safe power). Also, there is open topic on e-radionica forum for that fading: https://forum.e-radionica.com/en/viewtopic.php?f=22&t=414

**Review by oxan — APPROVED** [review]
Looks good from a high-level point of view, didn't look at all the details but I trust you got them right :)

**Pull request merged**
