### PR TITLE
Local Material Icons

### LINKED ISSUE #558: Remove external dependence on fonts.googleapis.com
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io

**ESP (ESP32/ESP8266, Board/Sonoff):**

N/A
**Affected component:**

The ESPhome dashboard. ESPhome is loaded as add-on in an Hass.io instance.

**Description of problem:**
The ESPhome dashboard seems to require access to fonts.googleapis.com to properly render the dashboard:

- 1x https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic
- 2x https://fonts.googleapis.com/icon?family=Material+Icons

I run my Hass.io instance on a disconnected network. Is there way to render the ESPhome dashboard correctly without dependence on external resources?

**Problem-relevant YAML-configuration entries:**
N/A/

**Logs (if applicable):**

**Additional information and things you've tried:**

### PR DESCRIPTION
**Pull request by Anonym-tsk**
## Description:
Removed external dependence on fonts.googleapis.com

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/558, https://github.com/esphome/issues/issues/650

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — COMMENTED** [review]
Hi, I'm back from a bit of travelling now.

I've had the same thought some time ago (integrating all assets directly), but two issues had kept me from doing so:

1. License - Most fonts have weird licenses and copying them to a code base is not as easy. This *needs* to be addressed.

2. Distribution size: This adds ~350 kb to esphome's dist size - Ideally we would only include the stuff we need (especially for icons)

**Comment by Anonym-tsk** [comment]
Hi, @OttoWinter
Glad to see you again!

1. Materials Design Icons provided by google and licensed under Apache License version 2.0. I think, we should add License file to `fonts` directory to close this question.
2. ~350 kb is not very big size. Many users have problems when dashboard works on hardware without internet access. I think, 350 kb is not very expensive price for fixing this problem.

**Comment by OttoWinter** [comment]
1. That sounds good to me.

2. Yes yes, it's a low priority issue certainly.

Additionally, we could also drop some file formats - .eot is only for ancient IE (which is not supported anyway). Looking at [this list](https://www.w3schools.com/css/css3_fonts.asp), we could get away with only .woff (maybe also include .woff2).

 - `.eot` : IE
 - `.woff` : All major browsers
 - `.woff2` (https://creativemarket.com/blog/the-missing-guide-to-font-formats) : Almost all browsers, a bit better compression than .woff2
 - `.ttf` : All major browsers, but a lot bigger.

**Comment by Anonym-tsk** [comment]
@OttoWinter i'm not sure about license because it is not filled out in google repo - https://github.com/google/material-design-icons/blob/master/LICENSE#L190
Do we really need to add it? Readme file with copyrights is already added into `fonts` dir.

**Comment by brandond** [comment]
Just cause they forgot to fill out the license template doesn't make it invalid. It's clearly Apache licensed, which means you have to bundle the license itself with the files if redistributing them.

**Pull request merged**
