### PR TITLE
Add new wizard + allow installing firmware over webserial

### PR DESCRIPTION
**Pull request by balloob**
# What does this implement/fix? 

A bit too much.

- Rely on an external package for the dashboard frontend. It lives in a new repository https://github.com/esphome/dashboard. See the installation instructions in that README on how to run it in dev mode.
- This updates the wizard on the dashboard to leverage WebSerial when available.
- Wizard writing initial config now supports Wi-Fi password to be optional and allows writing an OTA password different from password. Only the latter is used in the new wizard.

This PR is a draft. To do:

 - [x] Figure out static files in prod
 - [x] ~~Figure out firmware files sourcing~~ temporarily hardcoded.
 - [x] Use Rollup typescript plugin
 - [x] Show message during installation to keep tab in focus
 - [x] Make Wi-Fi required again

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1233

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
Nice! Thanks for the work, this is a nice feature!
While looking through the code/testing I noticed a couple of things, mostly about informing users/UX. But especially last one might be a deeper issue.

> Connect your ESP32 or ESP8266 board with a USB cable to your computer and click on connect. You need to do this once, after that you can install updates wirelessly.

We should make it more clear _what_ computer to connect to (the one with the browser vs. the computer running ESPHome). In the past, we had the problem of people trying to connect the ESP to the web browser computer. This could be the same, just flipped, especially if online issues they find say they should connect to the server computer.

---

> Connect your ESP32 or ESP8266 board with a USB cable to your computer and click on connect. You need to do this once, after that you can install updates wirelessly.

This could use a link to the docs explaining how to install the drivers. I just tested this on a separate computer without the drivers, and I assume a lot of people could be hitting this. (for example, copy the note here to a new FAQ entry: https://esphome.io/guides/faq.html#i-can-t-get-flashing-over-usb-to-work)

---

> Your browser does not support WebSerial. Use Microsoft Edge or Google Chrome to install this configuration on your ESP device via the browser.

This is a bit vague - if I use firefox, will I not be able to configure the device at all? (I know what it means of course, but not the average user) Maybe add an alternative like: "You can create a configuration from this browser, but installing the configuration over the browser is only supported with [...]". Personally, I'd use "flash" terminology here too, but I understand if you think that might be too foreign for the user base.

---

The WebSerial API is only available in secure contexts (https) according to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Serial). How is the case of "chrome but not in secure context" handled?

---

> Figure out firmware files sourcing temporarily hardcoded.

Do you mean bootloader et al? I guess it's ok for the moment (but will be a problem once we update base framework), the fs paths for these files can be retrieved from this API: [`get_idedata`](https://github.com/esphome/esphome/blob/dev/esphome/platformio_api.py#L126) (somewhere in `self.raw`)

---

In the future, it would be nice if the WebSerial stuff were also integrated in the `<select>` box in the top right. For example, when you replace an ESP with a different one (but keep the configuration), there's currently no way to do so via the browser.

----

The [docs](https://esphome.io/guides/getting_started_hassio.html#dashboard-interface) will need to be updated, for example the warning needs to be removed/replaced.

----

I see the "board" select is removed. Keep in mind this does not only affect pin naming, but - importantly - also the flash offsets/size etc.

For example, when flashing ESP8285 (it _has_ an ESP8266, yes they use weird naming), the [check](https://github.com/esphome/dashboard/blob/main/src/wizard/wizard-dialog.ts#L450-L459) will say it's an ESP8266. However, that will cause at least two issues I know of (potentially more):
- The compiler will allow higher code size than actually on the chip. On OTAs past the size limit (which is not _that_ hard to reach) you will get weird errors.
- [flash offsets](https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html) will be wrong. For example, the [`esp8266_restore_from_flash`](https://esphome.io/components/esphome.html) option will not work afaik, because the EEPROM offset would then land past the end of the flash storage. This also means things like the important `captive_portal` feature will not work (stores settings past the end of SPIFFS).

**Comment by OttoWinter** [comment]
Maybe it makes more sense noting these things as individual issues in the dashboard repo. Let me know which ones you'll address right away, then I'll create issues for the rest.

**Comment by balloob** [comment]
So for this PR I would love to focus on getting it merged as there are _many_ moving parts.

1. I will open a PR for the docs before we merge this.
1. I will do another round of UX updates once merged and will make sure they get all addressed.
2. For the board selector: for most people it will work with the defaults. It's a user experience improvement. Actually good if the captive portal doesn't work, so people realize quickly that it's broken and pick a board. 
2. The bootloader et-al indeed should be sourced from the backend dynamically
3. That `<select>` I was hoping we could remove as a global option in a future PR. For online devices we default to doing it OTA, otherwise we can show a picker dialog to the user when they click "upload" (I want to rename upload to install too)

**Comment by balloob** [comment]
PR to update the docs https://github.com/esphome/esphome-docs/pull/1233

**Comment by balloob** [comment]
Will push a UX update in a bit addressing your concerns.

**Comment by balloob** [comment]
Update pushed.

**Comment by balloob** [comment]
Pushed updated frontend to now also allow installing existing configurations via web serial.

**Review by jesserockz — APPROVED** [review]

**Comment by OttoWinter** [comment]
> Actually good if the captive portal doesn't work, so people realize quickly that it's broken and pick a board.

That's kind of the problem - it's _not_ a visible issue _until_ you try to use captive portal. The main use-case of captive portal is to recover devices that (for whatever reason) doesn't connect to your wifi network anymore. Importantly, I don't think anybody uses captive portal _until_ their device is already not connecting to wifi anymore.

But I think the wizard could ultimately help with the issue too - the code that is pushed to the device before the flashing process can theoretically detect which chip type is in use, and then choose the _actual_ chip type, the logic just needs to be added.

**Pull request merged**
