### PR TITLE
Ezo Pump functionality and Ezo Sensor Calibration v2

### PR DESCRIPTION
**Pull request by Assunto**
# What does this implement/fix?

I'm hoping to revive a request that looked to be so close to the finish line. Currently the EZO platform works to read sensor data, but there isn't a way to set calibrations. There are also EZO Peristaltic Pumps that don't have the ability to read as a switch or button so they can't be controlled in esphome and are essentially useless if the accompanying sensors are configured with the same esp32 device.

If there was a card that, when enabled, could read constant sensor states (or change the frequency to read every .5s for example) and had the ability to set the calibration amount with a button press.
If EZO circuits could be set up to be used with both the sensor and switch platforms, or if there was a new "i2c_switch" component created for control without needing a gpio pin.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by Assunto** [comment]
It looks like there are a few more contributors lately! Does anyone have an update/advice?

**Comment by gvdhoven** [comment]
There are quite some errors in the files which you need to fix first.

**Comment by gvdhoven** [comment]
This one became obsolete by https://github.com/esphome/esphome/pull/3561

**Comment by gvdhoven** [comment]
@Assunto can you close this PR?

**Comment by Assunto** [comment]
Thanks to @gvdhoven the ideas behind this pull request are happening!

**Pull request closed without merging**
