### PR TITLE
Add Waveshare 2.9in D display

### LINKED ISSUE #1013: Add waveshare "2.9inch e-Paper HAT (D)"
waveshare 2.9inch e-Paper HAT (D) tested compatible to the cheap MH-ET Live 2.9 inch E-paper Module (e.g. https://de.aliexpress.com/item/4001279382105.html?spm=a2g0s.9042311.0.0.68c34c4djtXUBM, < €16).  For tests I used the Arduino library you can find here: https://www.waveshare.com/wiki/E-Paper_ESP32_Driver_Board
**Describe the problem you have/What new integration you would like**

The 2.9 inch waveshare displays available in ESPhome did not work for the MH-ET module, but I would very much like to use it in ESPhome (CO2 sensor with local display).
**Please describe your use case for this integration and alternatives you've tried:**

**Additional context**

### PR DESCRIPTION
**Pull request by nuttytree**
## Description:

**Related issue (if applicable):** fixes esphome/feature-requests#1013

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1012
## Checklist:
  - [ ] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

I do not have one of these displays I just grabbed it as a feature request I figured I could complete.  If anyone has one of these displays that can test for me that would be awesome.  Otherwise I can update the docs to indicate it has not been tested.

### CODE REVIEW

**Review by nikito7 — APPROVED** [review]

**Comment by velaar** [comment]
I have a display as described in the original request. The red/black/white version with display cable HINK-E029A10. It starts up but instead of white background it displays black with barely visible "Hello World" at the top. 

````
spi:
  clk_pin: 14
  mosi_pin: 13

display:
  - platform: waveshare_epaper
    cs_pin: 15
    dc_pin: 19
    busy_pin: 21
    reset_pin: 22
    model: 2.90in-d
    #full_update_every: 10
    lambda: |-
      it.print(0, 0, id(font3), "Hello World!");

````


image

Edit: sorry for posting in the docs.Moving the post here. 

Additional tests show that the display is in some kind of loop - it tries to refresh the picture several times (blinking) until settles on black

**Comment by nuttytree** [comment]
So this PR is for the [Waveshare 2.9in (D)](https://www.waveshare.com/product/displays/e-paper/epaper-2/2.9inch-e-paper-d.htm?___SID=U) display that is B/W only so not really surprised it is not working with this display.  My guess is that your display is closer to the C model that is 3 color.  I am planning on working on adding several of the Waveshare displays so if you want to add a feature request for the C model I can try to get to that one also.

**Review by OttoWinter — APPROVED** [review]
Sorry for the late review.

Code looks great, thank you very much! :tada:

**Comment by OttoWinter** [comment]
Ah, looking through the discussion it looks like this isn't working yet. If no please let me know and I'll be happy to merge.

**Pull request closed without merging**
