### PR TITLE
Implement addressable_gradient effect

### LINKED ISSUE #417: FastLED Gradient support
**Describe the problem you have/What new integration you would like**
I would like to see support in ESPHome for the FastLED library gradient color palettes. See here: https://github.com/FastLED/FastLED/wiki/Gradient-color-palettes

**Please describe your use case for this integration and alternatives you've tried:**
I would like to use this to be able to quickly and maybe on the fly create static color gradients on ledstrips with individial pixel control. For example it starts red at the beginning but gradually changes and it will be blue at the end. 

Even better would be to be able to change this on the fly with home assistant, but right now the only possible solution (as far as I know) is to cut up the strip in individual partitions and set the color manually, but that takes more processing power and is not really user friendly.

**Additional context**

None

### PR DESCRIPTION
**Pull request by poelzi**
# Description:

This effect allows user defined gradients which the effect shifts through.
The gradient is defined with the gimp gradient format and a user defined length,
which should be much larger then the number of pixels in the strip. Setting flip
to true, will cause the gradient to change direction on the end.

Example:
```
light:
  - platform: neopixelbus
    type: GRBW
    variant: SK6812
    pin: RX
    num_leds: 20
    name: "Test neopixel"
    effects:
      - addressable_gradient:
          length: 50
          name: Fuschia 6
          use_white: true
          gradient: |
            GIMP Gradient
            Name: Fuschia 6
            4
            0.000000 0.125000 0.250000 0.811765 0.192157 0.870588 1.000000 0.784314 0.388235 0.937255 1.000000 0 0
            0.250000 0.375000 0.500000 0.784314 0.388235 0.937255 1.000000 0.560784 0.207843 0.964706 1.000000 0 0
            0.500000 0.625000 0.750000 0.560784 0.207843 0.964706 1.000000 0.823678 0.190171 0.822934 1.000000 0 0
            0.750000 0.875000 1.000000 0.823678 0.190171 0.822934 1.000000 0.560784 0.207843 0.964706 1.000000 0 0
```

**Related issue (if applicable):** fixes <link to issue>

fixes https://github.com/esphome/feature-requests/issues/417

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

esphome/esphome-docs#471

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by poelzi** [comment]
It seems that larger length values cause strange stack corruption due the large number of leds pushed into the colors array. I will instead push only the gradient values and calculate the colors on demand, so length of 10000 should not be a problem anymore.

**Comment by brandond** [comment]
Why use the Gimp gradient format? It seems pretty obtuse. Is there any way to make it more user friendly?

**Comment by poelzi** [comment]
I looked at lots of other formats but they are harder to parse and usually not that powerful. Gimp is free software so it's easy to create new gradients and just open the resulting file and paste it in the config.
I'm still working on it, now the colours are calculated on the esp so you can create very long animations with only some data points. They are now static consts so less memory usage. I might split the gradient from the animation because I very often use the light partition and want the use the same animation on multiple lights. Defining a gradient and later referencing it would save duplication.

**Comment by brandond** [comment]
Is there a way to generate a gradient without installing Gimp? Web page or something?

**Comment by brandond** [comment]
FYI, apparently even the Gimp devs think this format is an abomination
https://www.gimpusers.com/forums/gimp-developer/4024-format-of-gimp-gradient-files#message16152

**Comment by poelzi** [comment]
The new implementation will allow to specify the gradient in different formats and the python side will generate the static struct array in a unified (gimp) format. So, if somebody feels like implement a css gradient parser of some more simple way describe it, this can be easily implemented. I know this format looks ugly, but I see it as a good pasteable bit of text blob, compared to the other formats I looked into. For simple gradients some yaml format could be implemented, but if you want 500 gradient points, I don't want 10000 extra config lines. 500 is hardly barrable. I will support loading gradients form files as well.

The new gradient is basically a top level config object that can later be referenced by different subsystems.

**Comment by poelzi** [comment]
One reason I promoted the gradient to component level was, because I could also imagine the gradient objects being used to describe backgrounds on display components for example. Will also implement the gradient effect for single rgb images.
For the  mono lamps, we could either use only one channel or the average of rgb, what would you prefer ? Average would be better I think for reusing gradients.

**Comment by poelzi** [comment]
There are still some smaller bugs in the code but it looks now very promising. I'm able to define lots and very long animations.

```yaml
gradient:
  - id: SeaDreams13
    gimp: |
      0.000000 0.125000 0.250000 0.823529 0.827451 0.913725 1.000000 0.447059 0.458824 0.964706 1.000000 0 0
      0.250000 0.275000 0.300000 0.447059 0.458824 0.964706 1.000000 0.556863 0.564706 0.968627 1.000000 0 0
      0.300000 0.400000 0.500000 0.556863 0.564706 0.968627 1.000000 0.000000 0.000000 1.000000 1.000000 0 0
      0.500000 0.600000 0.700000 0.000000 0.000000 1.000000 1.000000 0.556863 0.564706 0.968627 1.000000 0 0
      0.700000 0.725000 0.750000 0.556863 0.564706 0.968627 1.000000 0.447059 0.458824 0.964706 1.000000 0 0
      0.750000 0.850000 0.950000 0.447059 0.458824 0.964706 1.000000 0.823529 0.827451 0.913725 1.000000 0 0
      0.950000 0.975000 1.000000 0.823529 0.827451 0.913725 1.000000 0.823529 0.827451 0.913725 1.000000 0 0

light:
  - platform: neopixelbus
    id: leds
    type: GRB
    pin: GPIO3
    method: ESP8266_DMA
    num_leds: 238
    name: "Flower 1 All"
    effects:
      - addressable_gradient:
          length: 4000
          flip: true
          name: SeaDreams 13
          gradient: SeaDreams13

```

**Comment by poelzi** [comment]
I'm also thinking about a dynamic gradient type that can be set by the api. This way, homeassistant can dynamically load gradients into the controller. The number of points however should be limited as I experienced stack problems after adding 400 GradientPoint to a vector.
I would suggest promoting ESPColor and the HSV color class from the light component to the core. It is now used by multiple components and I think it makes sense to have a universal color data type.

**Comment by brandond** [comment]
There are a bunch of test failures; if you want to clean those up this looks good to me. If @OttoWinter doesn't like it he can always fix it or revert ;)

**Comment by ssieb** [comment]
Is this still active?  I would like the load from a file option to be implemented as well.  It would be better for sharing between devices, would avoid the large chunk of numbers in the yaml, and would allow multiple formats to be supported more easily.

**Pull request closed without merging**
