### PR TITLE
Waveshare e-ink 2IN9_V2 - fix full and partial update based on vendor…

### PR DESCRIPTION
**Pull request by darianndd**
… SDK and examples

# What does this implement/fix?

This change contains a new implementation for full and partial update of Waveshare 2.9inch e-ink display (296x128 Black/White; SPI) which may fix an issue mentioned in section "related issues", but I don't know if my e-ink display is V2.1. What I do know, it doesn't work with present implementation of partial update in Esphome.
Original Esphome code works with full update only which is not healthy for frequent display refreshes. The proposed change is based on SDK and examples in ZIP file from this webpage:
https://www.waveshare.com/pico-epaper-2.9.htm

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**
It may fix this issue, because my e-ink behaved in the same way:
https://github.com/esphome/issues/issues/2334
however, labels on my e-ink display says that it is V2, not V2.1, but original Esphome code for V2 doesn't work on my display. 

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
esphome:          
  name: esp32_eink

esp32:          
  board: lolin32

spi:              
  clk_pin: GPIO18 
  mosi_pin: GPIO23
  miso_pin: GPIO19

display:                                                     
  - platform: waveshare_epaper                               
    id: disp1                                                
    cs_pin: GPIO14                                           
    dc_pin: GPIO27                                           
    busy_pin: GPIO13                                         
    reset_pin: GPIO26                                        
    model: 2.90inv2-r2                                          
    full_update_every: 3                                     
    update_interval: 10s                                     
                                                             
    lambda: |-                                               
      it.printf(0, 0, id(font_vcr_21), "0,1:2345");     
      it.printf(0, 30, id(font_vcr_21), "67890");            
      static int i = 0;                                      
      it.printf(0, 60, id(font_vcr_21), "v: %d", i++);       

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — DISMISSED** [review]
If a specific version of a waveshare display requires to override those functions, it should be made as its own class to `override` them correctly and cleanly. See the other recent waveshare PRs that add more sizes/versions as options

**Comment by darianndd** [comment]
> If a specific version of a waveshare display requires to override those functions, it should be made as its own class to `override` them correctly and cleanly. See the other recent waveshare PRs that add more sizes/versions as options

Ok, so I have created model "2.90inv2-r2" (description above is already updated) with separate class for my revision of eink. Let me know if this is ok.

**Comment by clydebarrow** [comment]
The code looks ok as far as I can tell. It will need a PR in esphome-docs to add the new selection.

**Comment by darianndd** [comment]
> The code looks ok as far as I can tell. It will need a PR in esphome-docs to add the new selection.

Fair point, I have added new model type to the eink display doc with short description, here is pull request:
https://github.com/esphome/esphome-docs/pull/3637

**Comment by RubenNL** [comment]
I have been using this before without any issue as a external_component. It stopped working yesterday, but after changing the `model` to the new one it's again working fine.

Happy to see this MR getting some love again :)

**Review by clydebarrow — APPROVED** [review]
LGTM

**Pull request merged**
