### PR TITLE
Revert "Light: include ON_OFF capability to BRIGHTNESS ColorMode"

### LINKED ISSUE #2355: Monochromatic Light don't dim with HA
### The problem

After the last update 2018.8.1 all my monochromatic lights don't show the dim bar in Home Assistant 2018.8.8
with the previous version 2018.8,0 all is ok

### Which version of ESPHome has the issue?

2018.8.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2018.8.8

### What platform are you using?

ESP32

### Board

ESP32 dev

### Component causing the issue

monochromatic light

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by jesserockz**
Reverts esphome/esphome#2186

Reverting this for a patch release and will put it back again in 2021.9.

Fixes esphome/issues#2355

### CODE REVIEW

**Comment by 3ative** [comment]
Hey @jesserockz thanks.

When can we expect this to available? - All of my lights are broken atm.

**Comment by jesserockz** [comment]
Doing it now. Addon backups are important so you can revert to the previous versions =)

**Comment by 3ative** [comment]
Excellent, thank you 👍
Ref: Add-on backups. Never needed them before (For ESPHome at least) It's always been solid. 
... You DEV guys ROCK! 💖

**Comment by 3ative** [comment]
Happy to confirm, we're back. Thanks guys. 
image

**Pull request merged**
