### PR TITLE
Raise minimum python version to 3.7

### PR DESCRIPTION
**Pull request by OttoWinter**
# What does this implement/fix? 

Breaking change. This PR raises the minimum python version to 3.7.

Python 3.7 will be required for some features I'm working on (#1657, #1630). The docker images already use 3.7, and most recent distributions ship with 3.7 or newer (exception: ubuntu bionic LTS, but those folks should upgrade to focal LTS)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [ ] ESP32
- [ ] ESP8266
- [x] Windows
- [x] Mac OS
- [x] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

# Explain your changes

Describe your changes here to communicate to the maintainers **why we should accept this pull request**.
Very important to fill if no issue linked

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by napieraj** [comment]
this breaks installation of the dev addon on supervised Home Assistant (ex. hassio):
```[15:12:05] INFO: Installing esphome version 'dev' (https://github.com/esphome/esphome/archive/dev.zip)...
Collecting https://github.com/esphome/esphome/archive/dev.zip
  Downloading https://github.com/esphome/esphome/archive/dev.zip (2.0MB)
esphome requires Python '>=3.7,<4.0' but the running Python is 3.6.8
[15:12:08] FATAL: Failed installing esphome pinned version.
[cont-init.d] 30-esphome.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.```

**Comment by OttoWinter** [comment]
Ah yes, true. I updated the base image of the dev addon now: https://github.com/esphome/hassio/commit/35c77fe304ba887bd40345dcbcea3106a87e40fd - might take a bit to propagate

**Comment by taifunk** [comment]
Any update on this?

```
 Add-on version: 1.16.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.13  (amd64 / qemux86-64)
 Home Assistant Core: 2021.4.2
 Home Assistant Supervisor: 2021.03.9
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] 30-esphome.sh: executing... 
[15:12:28] INFO: Installing esphome version 'dev' (https://github.com/esphome/esphome/archive/dev.zip)...
Collecting https://github.com/esphome/esphome/archive/dev.zip
  Downloading https://github.com/esphome/esphome/archive/dev.zip (2.0MB)
esphome requires Python '>=3.7,<4.0' but the running Python is 3.6.9
[15:12:43] FATAL: Failed installing esphome pinned version.
[cont-init.d] 30-esphome.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
```

**Comment by OttoWinter** [comment]
@taifunk You appear to be using the stable esphome addon with the `esphome_version` set to `dev`. Please instead use the esphome-addon (from https://github.com/esphome/hassio)

**Pull request merged**
