### PR TITLE
logger: add option to include relative timestamp

### PR DESCRIPTION
**Pull request by ashald**
# What does this implement/fix? 

Add an option to logger component to include a timestamp into every log message.
The timestamp is number of milliseconds since start of ESP execution, and overflows approximately every 49 days and 17 hours. Useful when debugging performance issues, or optimizing battery-powered setups utilizing deep sleep.

Example in which I debug latencies in my battery powered ESP eInk display that received data over BLE (excerpt with parts omitted for brevity):
```
[22:19:36.231][I][app:029]: Running through setup()...
[22:19:36.232][D][main:010]: (T871) Woke up
[22:19:36.874][D][esp32_ble_tracker:214]: Starting scan...
...
[22:19:37.259][D][myhomeiot_ble_client:069]: [3C:61:05:10:D7:6E] Found device
...
[22:19:37.303][I][myhomeiot_ble_client:032]: [3C:61:05:10:D7:6E] Connecting
...
[22:19:37.428][I][myhomeiot_ble_client:087]: [3C:61:05:10:D7:6E] Connected successfully, app_id (1)
...
[22:19:38.487][D][main:059]: Sensor data received, JSON parsing result: Ok
...
[22:19:38.625][D][main:094]: Starting eInk update
...
[22:19:44.090][D][main:096]: Screen update complete
...
[22:19:44.102][I][deep_sleep:103]: Beginning Deep Sleep
```

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** N/A

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:
N/A

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
Why not just make it display the milliseconds in the existing field like `[12:54:30.189]`? I think that would be easier to read IMO

**Comment by ashald** [comment]
@OttoWinter that was my plan originally, but I just didn't find a way to do that. That being said, I was only looking at the `logger` component specifically, as it could be easily replaced via `external_components`. That being said, given that ESPs don't usually have a time source, when you think about it, it's obvious that the timestamping of log records must be happening somewhere on the "server" side when streaming logs.

Now, once I did it the way I did, I kinda liked it, as the time is relative to the boot time, and is very helpful when optimizing run cycles in between deep sleep based setups. So when I look at the output, it's immediately clear how long a run took, and you don't need to do any mental math for that. E.g, compare the excerpt from the above message with:
```
[06:43:25][T       871][D][main:094]: Woke Up
[06:43:26][T      1526][D][esp32_ble_tracker:214]: Starting scan...
...
[06:43:26][T      1537][I][lilygo_t5_47_display:026]: setup(): start
[06:43:26][T      1618][I][app:062]: setup() finished successfully!
[06:43:26][T      1619][D][myhomeiot_ble_client:069]: [3C:61:05:10:D7:6E] Found device
...
[06:43:26][T      1635][I][myhomeiot_ble_client:032]: [3C:61:05:10:D7:6E] Connecting
...
[06:43:26][T      1836][I][myhomeiot_ble_client:087]: [3C:61:05:10:D7:6E] Connected successfully, app_id (1)
...
[06:43:27][T      2629][D][main:060]: (T2629) JSON parsing result: Ok
...
[06:43:27][T      2766][D][main:334]: Screen update: start
...
[06:43:27][T      2991][D][main:126]: Screen lambda: started
...
[06:43:28][T      3498][D][main:148]: Screen lambda: complete
...
[06:43:30][T      5854][D][main:074]: Screen update: complete
[06:43:30][T      5859][D][main:080]: Entering sleep
[06:43:30][T      5864][I][deep_sleep:103]: Beginning Deep Sleep
[06:43:30][T      5870][I][lilygo_t5_47_display:074]: on_shutdown(): start
[06:43:30][T      5877][I][lilygo_t5_47_display:077]: on_shutdown(): complete
```

Thinking about it, the ultimate approach probably would've been allowing to tweak log message format, but I don't have sufficient knowledge of C++ to contribute something like.

So back to the PR - as I mentioned, I find it pretty convenient it's in this PR, but if you strongly prefer doing it the way you described, I'd be happy to try to implement that if you could point me at the relevant source code.

**Comment by jesserockz** [comment]
Serial logs:
https://github.com/esphome/esphome/blob/bf91443f38d273f5fae4868e608a898dd33746cf/esphome/__main__.py#L125-L136

API logs:
https://github.com/esphome/esphome/blob/bf91443f38d273f5fae4868e608a898dd33746cf/esphome/components/api/client.py#L34-L37

MQTT Logs:
https://github.com/esphome/esphome/blob/bf91443f38d273f5fae4868e608a898dd33746cf/esphome/mqtt.py#L115-L119

**Comment by ashald** [comment]
@jesserockz, @OttoWinter thanks - how does it look now?

**Comment by OttoWinter** [comment]
Looks ok, but please re-add the config option for this. IMO we shouldn't add this by default, as it's rather noisy and most people won't care

**Comment by OttoWinter** [comment]
In order to let the util function know, you can make `logger` put a bool flag in `CORE.data`, and read that out in the util function

**Pull request closed without merging**
