### PR TITLE
Add support for SHT4X

### PR DESCRIPTION
**Pull request by sjtrny**
## Description:

Adds support for the SHT4X sensor.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1002

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by sjtrny** [comment]
> Heyo, any chance you would open up a PR upstream with this? I've got a few SHT40s I'd love to add to my home-assistant install 😃

Should be done now.

**Comment by sjtrny** [comment]
Hmmm I'm not sure what happened with all the new tags and review requests. Sorry everyone!

**Comment by glmnet** [comment]
> Hmmm I'm not sure what happened with all the new tags and review requests. Looks like I messed up the rebase. Sorry everyone!

Don't worry. Just try to get the PRs green. Thanks

**Review by jesserockz — APPROVED** [review]

**Comment by sjtrny** [comment]
There's already docs for the component https://github.com/esphome/esphome-docs/pull/1002

**Pull request merged**
