### PR TITLE
esp32 camera add night mode config option

### PR DESCRIPTION
**Pull request by yevgenb**
# What does this implement/fix? 

This will add `night_mode` configuration option that enable "aec2" functionality or the OV2640 camera. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuraiton files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [ ] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

# Explain your changes

This will add "night_mode" configuration option that enable "aec2" functionality or the OV2640 camera.  

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — APPROVED** [review]
LGTM, thanks :+1: 

Ready to merge when docs are ready

**Comment by CarlosGS** [comment]
Note this camera setting was independently tackled here: https://github.com/sveip/esphome/commit/334042347a0c76389f6ea43bcba83aad86eb8326 with docs https://github.com/sveip/esphome-docs/commit/005d09b5c8693ea519b47c1924b63cdc336417a0 @sveip

Both solutions rely on "aec2". Thought of suggesting the name "auto_exposure" here instead of "night_mode". However there is also the plain "aec" setting available for these cameras. We currently don't have it in ESPHome but might need it in the future, or better modes could appear, etc.

So maybe we should add camera settings matching their API name, to avoid issues when new cameras & modes appear (as further example, see that a similar issue occurred with power save modes https://github.com/esphome/issues/issues/1532#issuecomment-850860245). What do you think?

**Comment by sveip** [comment]
I decided to go with the api naming, since that is the only doc that we have. "Night Mode" is slightly misleading, since it's actually not what aec does, it's rather a use case.

That said, as mentioned in the dev channel on discord, I don't see how this particular PR works, given that the `aec_value` isn't exposed, so there is no way to set a sensible value apart from the default. I might be totally wrong here, but in my research I've used the espcam test app that has a webui to control these, to find out which values makes sense controlling. I'm very open to suggestions on this though.

I'll hold off opening a PR until I'm told otherwise :)

**Comment by CarlosGS** [comment]
I'd support merging Sveip's as it is more generic and allows to finely control the auto exposure parameters.
Currently cameras with ESPHome are pitch black at night, so this feature would be very welcome. Most people don't realize the sensor can capture more light with these options.

> I'll hold off opening a PR until I'm told otherwise :)

Can I ask for it? haha :angel:

**Comment by sveip** [comment]
> Can I ask for it? haha angel

Sure @CarlosGS. Have you tested it? I would like a peer review before I make a PR.

**Comment by CarlosGS** [comment]
Yep, and it works! Though these settings on their own didn't provide that much benefit at low light levels.

I experimented with these and other parameters, but merging this code https://github.com/raduprv/esp32-cam_ov2640-timelapse is what yielded really nice exposure at night (see https://github.com/raduprv/esp32-cam_ov2640-timelapse/issues/5#issuecomment-946018148). However, I don't understand their approach enough to port it in an "elegant" way, and currently it oversaturates during the day.

For aec2 your code works just fine, I think it would be nice to have it in ESPHome :)

**Comment by sveip** [comment]
Thanks @CarlosGS. I've opened a PR here: https://github.com/esphome/esphome/pull/2892

The link you provided seems to have good low light performance. It would be useful to detect the saturation and adjust it automatically, in essence that is what AEC is for. I'm not sure how to get any output from it, but I haven't looked either.

EDIT: Can you push your merge to github so that I can have a look?

**Comment by CarlosGS** [comment]
Here you have my merge using @raduprv's method: https://github.com/esphome/esphome/compare/dev...CarlosGS:patch-17?diff=split#diff-f205e83b01167d6f78e8280705d21898142c784d9c33670888b95c2c553ac3dc
It is slow and fails some times. Not sure how to fix it, because there are many parameters I don't understand.

Example of a low light scene captured:
With default ESPHome settings / With new AEC2 (2/1600 settings) / With Radu's method
  

Radu's readme says:

> For long exposures you need to wait for 2 frames to get the right image. So for a 4 second exposure, you need to wait for over 4 seconds before capturing the image. If you are running the camera on batteries, this can be a problem. Fortunately, if you set bit 7 on the 0x43 register on the sensor bank, you get the image after 1 frame only, which saves a lot of time.

But I haven't managed to use that call to get a brighter image with aec2 ;(

**Comment by raduprv** [comment]
Hi.
If my method fails sometimes, it is usually because you didn't wait enough to get the frame.

**Comment by raduprv** [comment]
Oh, I looked at your patch, you only took the night code. You must also take other register settings, or else it will fail sometimes:
    s->set_reg(s,0xff,0xff,0x00);//banksel 
    s->set_reg(s,0xd3,0xff,0x8);//clock
    
    s->set_reg(s,0x42,0xff,0x2f);//image quality (lower is bad)
    s->set_reg(s,0x44,0xff,3);//quality

    //no sharpening
    s->set_reg(s,0x92,0xff,0x1);
    s->set_reg(s,0x93,0xff,0x0);

**Comment by CarlosGS** [comment]
Hi Radu, sorry! I meant that my specific merge is unreliable.
Rest assured your code works beautifully, thanks for sharing all your findings :pray: 

> it is usually because you didn't wait enough to get the frame.

That's probably the cause, as ESPHome simply polls the camera every few seconds.
And also, there might be internal timeouts in ESPHome that prevent sending the frame to home assistant in time.

Overall, one approach that seems viable would be to use the camera's light sensor value to automatically switch between the default capture method (at day) and the long exposure method (at night). But we would need to reset the sensor at each transition, and probably need some hysteresis so it doesn't keep changing at dusk/dawn.

Update: Oh! Going to try that. Thanks again :)

**Comment by raduprv** [comment]
I am glad you found my code useful. About restarting the sensor, I actually never tried my code without restarting the sensor, since I was looking specifically at timelapse on batteries. Probably the best way to deal with dusk/dawn is to use a real light sensor, if you can;t reliably get that info from the light register without restarting it.

**Comment by CarlosGS** [comment]
This PR can be closed as it was merged in https://github.com/esphome/esphome/pull/2892 :smile: 

Note: We could also incorporate a specific long exposure mode that really captures in the dark https://github.com/esphome/esphome/pull/1584#issuecomment-989027579.
As Radu pointed out we need to wait before grabbing the frames. In fact, not waiting enough can cause visible artifacts even in normal mode (see https://github.com/espressif/esp32-camera/issues/314#issuecomment-1012313197). Just in case someone else is working on the camera code. Cheers!

**Pull request closed without merging**
