### PR TITLE
Daikin climate receiver support

### PR DESCRIPTION
**Pull request by puuu**
## Description:

This implements receiver support for the daikin component. @hectorgimenez, thank you for the initial implementation of the daikin component (#964). I tested it with an ARC469A24 remote. The transmitting part worked without modification (even if my remote does not send exactly the same data), so the daikin protocol seems to be compatible at least for the functions we use.

The last two commits fix some parts that IMHO was wrong. It would be nice if someone could test these changes with a different model.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#522

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by puuu** [comment]
This code does not work on a esp32, see esphome/issues#1037.

**Comment by glmnet** [comment]
@hectorgimenez can you test this changes on your setup? Even if you're not going to use the receiver, it'd be nice to know the transmitter is still working for you so we don't go back and forth. Thanks

**Comment by hectorgimenez** [comment]
> @hectorgimenez can you test this changes on your setup? Even if you're not going to use the receiver, it'd be nice to know the transmitter is still working for you so we don't go back and forth. Thanks

Yes, let me try it

**Comment by hectorgimenez** [comment]
I just tried it and is working fine with my remote ARC433A1, tested various functions and looks like everything is working @glmnet @puuu

**Comment by glmnet** [comment]
Thanks!!

**Comment by glmnet** [comment]
Thanks

**Pull request merged**
