### PR TITLE
add position reporting to the template cover

### PR DESCRIPTION
**Pull request by ssieb**
## Description:
Enables position reporting for the template cover

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs). esphome/esphome-docs#410

### CODE REVIEW

**Comment by ssieb** [comment]
This doesn't work yet.

**Comment by OttoWinter** [comment]
Let me know when you want me to review it/it works.

**Comment by ssieb** [comment]
Ok, this is tested and works.  My virtual garage door goes up and down and I can tell where it is. :-)

**Comment by OttoWinter** [comment]
Ok, good. However you will need to create an update to the docs too since you added a new option

**Comment by ssieb** [comment]
I added that to the previous comment, but edits don't get sent in emails.  You're ok with doing it this way?  If so, I'll add a docs PR.

**Comment by OttoWinter** [comment]
Yes, that's good 👍

**Comment by ssieb** [comment]
I added the docs PR.

**Pull request merged**
