### PR TITLE
Add on_tag_removed trigger to pn532

### LINKED ISSUE #172: pn532 on_no_tag
**Describe the problem you have/What new integration you would like**
I would like to propose a on_no_tag, triggering when no tags are near

**Please describe your use case for this integration and alternatives you've tried:**
I'm using the pn532 with the on_tag to update a template text_sensor. Detects fine, but I can't use it to detect when the card leave the proximity of the sensor. The on_tag only gets called when a card is near. At the moment I just blank out the text_sensor at regular intervals, but that gives me multiple triggers if the card is still near.

**Additional context**
I think the binary sensors already does kind of this, but I don't wan't to set up binary sensors for 20+ cards.

### PR DESCRIPTION
**Pull request by romerod**
## Description:

Add ~~on_release~~ on_tag_removed trigger to pn532 to get a notification when tag is removed.

**Related issue (if applicable):** closes esphome/feature-requests#172

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#915

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — COMMENTED** [review]
I like it all apart from the naming of `on_released` maybe `on_tag_removed` or something...
I was considering adding this at some point. Thanks

**Comment by romerod** [comment]
> I like it all apart from the naming of `on_released` maybe `on_tag_removed` or something...
> I was considering adding this at some point. Thanks

Ok, the reasoning was to keep it similar to the binary_sensor, but I agree it's easier to understand like that

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Thanks, Just needs a docs PR then can be merged in.

**Review by ssieb — APPROVED** [review]

**Comment by ssieb** [comment]
You need to edit the description to include the docs PR.
It also looks you might need to rebase the changes to fix conflicts.

**Comment by romerod** [comment]
Changed the description, rebased and tested.

**Review by jesserockz — CHANGES_REQUESTED** [review]
This will not exactly work as it cannot `read_tag_` when there is no tag present at the time. 
While it wont crash, there will be errors in the log when it tries to authenticate with the tag. 
It will return a blank `tag` with the uid: `new nfc::NfcTag(uid, nfc::MIFARE_CLASSIC)`

**Review by jesserockz — APPROVED** [review]

**Comment by romerod** [comment]
Thanks @jesserockz for finishing the work.

**Pull request merged**
