### PR TITLE
Updated Mcp3008 to support reference_voltage and voltage_sampler::VoltageSampler

### PR DESCRIPTION
**Pull request by SenexCrenshaw**
## Description:
I reset hard by mistake and loss #1270 

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#874

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
LGTM

**Comment by fabaff** [comment]
The conflict has to be resolved before it can be merged.

**Comment by SenexCrenshaw** [comment]
> The conflict has to be resolved before it can be merged.

Thanks @jesserockz  . Is this good now?

**Comment by jesserockz** [comment]
> > The conflict has to be resolved before it can be merged.
> 
> Thanks @jesserockz  . Is this good now?

Yes, once the docs changes are done this can merge

**Comment by SenexCrenshaw** [comment]
The docs have been updated. sorry about the mess there.

**Comment by SenexCrenshaw** [comment]
> > > The conflict has to be resolved before it can be merged.
> > 
> > 
> > Thanks @jesserockz  . Is this good now?
> 
> Yes, once the docs changes are done this can merge

Docs are done

**Comment by jesserockz** [comment]
I have fixed the docs now.

I have also marked this as a `breaking-change` as this would change the values on peoples devices from 0-1024 to 0-3.3.

**Comment by SenexCrenshaw** [comment]
> I have fixed the docs now.
> 
> I have also marked this as a `breaking-change` as this would change the values on peoples devices from 0-1024 to 0-3.3.

Ok thank you. Its 0-1023.

But if they set the ref voltage to 1023 they will get the same output.

**Comment by jesserockz** [comment]
|  Its 0-1023.
That's what I meant =)

Yes, but definition of a breaking-change is if you don't change your config but you get different results, which is what this is.

**Comment by SenexCrenshaw** [comment]
> | Its 0-1023.
> That's what I meant =)
> 
> Yes, but definition of a breaking-change is if you don't change your config but you get different/unexpected results, which is what this is.

Yes, sorry I didn't respond to that point. I totally agree.

**Pull request merged**
