### PR TITLE
Fix reactive power unit of measurement from VAR to var

### PR DESCRIPTION
**Pull request by felipecrs**
# What does this implement/fix?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Other

**Related issue or feature (if applicable):**

- fixes https://github.com/home-assistant/core/issues/130485

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

N/A

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
sensor:
  - platform: cse7766
    reactive_power:
      name: "Reactive Power"
      filters:
        - throttle_average: ${sensor_update_interval}
    power_factor:
      name: "Power Factor"
      filters:
        - throttle_average: ${sensor_update_interval}
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by felipecrs** [comment]
I flashed in my device, and I can confirm this fixes the issue.

**Review by DjordjeMandic — APPROVED** [review]
https://en.m.wikipedia.org/wiki/Volt-ampere#cite_note-dir-1

**Comment by jesserockz** [comment]
Duplicate of #7643

**Comment by felipecrs** [comment]
This one also fixes the unit in the logging. Also, as @DjordjeMandic [pointed out](https://github.com/esphome/esphome/pull/7757#pullrequestreview-2433106001), the correct is `var` and not `VAR` (as a reply to https://github.com/esphome/esphome/pull/7643#issuecomment-2433886345).

**Comment by felipecrs** [comment]
Thus, I don't think HA should even provide a way to ignore the unit casing. I believe it's by design, and it's good.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
