### PR TITLE
Add horizontal and vertical enums for climate

### PR DESCRIPTION
**Pull request by F43RY**
# What does this implement/fix? 

The implementation is an idea to add the capability to set vane position (horizontal and vertical) in devices where this functionality is available

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — COMMENTED** [review]
Hi! Thanks for submitting the pull request!

I have a question about the use case here though.

ESPHome follows the [climate entity model of Home Assistant](https://developers.home-assistant.io/docs/core/entity/climate/) - I don't see tilt/pan mode there. How is this feature supposed to be used when there's no UI in HA with which one could change the tilt/pan of a climate device?

**Comment by F43RY** [comment]
Hi,
I'm not using HA however I'm using esphome on Wemos D1 Mini in conjunction with [espmhp](https://github.com/geoffdavis/esphome-mitsubishiheatpump ) external component with MQTT to OpenHab. My internal units have vertical vane position settings and other models have also horizontal vane position settings too (I called pan and tilt in my patch). For this reason I think that add possibility to set vertical and horizontal vane position are useful for devices like mines. 
I think esphome is a great project also without using HA.

Thx
F43RY

**Comment by OttoWinter** [comment]
I see - that makes sense.

Unfortunately I still think we should stick to the HA architecture, because the few times in the past where we deviated from it have all resulted in big maintenance cost (old esphome climate model, light model, fans). Especially if HA introduces them but with different names/semantics it's going to be a big mess.

Since you're already using external code, can you just integrate the MQTT topics into that? Then you can have that support, but we don't need to change the core model.

For reference, [here](https://github.com/home-assistant/architecture/discussions/553) is a discussion about adding related changes to HA climate model.

**Comment by DomiStyle** [comment]
At least in combination with Home Assistant I'm using text sensors as a workaround for manual horizontal/vertical tilt like this:

```
text_sensor:
  - platform: homeassistant
    id: ac01_vertical_swing
    name: ac01_vertical_swing
    entity_id: input_select.ac01_vertical_swing
    on_value:
      - homeassistant.service:
          service: input_select.select_option
          data_template:
            entity_id: input_select.ac01_vertical_swing
            option: "{{ swing }}"
          variables:
            swing: |-
              return id(ac01_vertical_swing).state;
```

From my custom component I just write to that sensor and use the add_on_state_callback to receive updates from the HA frontend.

Not ideal since you manually need to create an input_select in Home Assistant but it works for now.
I do think these should be integrated into the climate component in both Home Assistant and ESPHome. Most modern ACs can set horizontal/vertical swing manually but HA does not have a way to represent this.

**Comment by F43RY** [comment]
Hi, thanks for your replies.
As wrote I don't have HA installed and think that esphome is a very good project in a widely way, not only for HA. However if the idea is to be stuck to HA I'd propose to include an optional preposition in yaml configuration of components (and why not in core) that may "unlock" further functionalities not covered by HA but usefull for all those like me that don't use HA. An extra directive could be excluded from HA but could be usefull in other contexts and explicitly not maintained by esphome team. Something like the following:
`...
  extra:
    - feature1:  value
    - feature2:  value`
 ...`

Thx again

**Comment by OttoWinter** [comment]
> but could be usefull in other contexts and explicitly not maintained by esphome team.

How would that work on the technical side? Adding new properties to climate devices necessarily means that the ClimateDevice base class needs to be modified, which then means we're stuck with that model and have to maintain it.

You can however use the `external_components` feature to override the `climate` integration in your setup with your own fork. Then you can have the horz/vert feature and even easily share it with others.

**Comment by sygys** [comment]
Its funny how devs always looking at things in ways that it cant or wont work instead of how things can work. ESP has a climate function... climate devices have swing modes. So why not just add it in a way it works for everyone?

Seperate swingmodes not presented by the climate entity itself is acceptable but not ideal.

I understand not everyone that uses ESP is using Home Assistant, but allot of people using home assistant are using ESPhome

Please look into this. It would help allot of people making their climate devices local.

**Comment by OttoWinter** [comment]
> Its funny how devs always looking at things in ways that it cant or wont work instead of how things can work. ESP has a climate function... climate devices have swing modes. So why not just add it in a way it works for everyone?

I explained why. If we go ahead and add this now, but HA ends up adding it differently (or even fundamentally incompatible way) we're going to be left with a big mess. This has happened before multiple times, and it's always a big maintenance burden.

> I understand not everyone that uses ESP is using Home Assistant, but allot of people using home assistant are using ESPhome

Which is exactly why it needs to be in sync with HA. Until HA itself adds it to the climate model you wouldn't be able to use this anyway.

There are a number of ways integrations can already expose swing modes, for example using `select` entities (and can do so right from ESPHome).

I too would like to see this, and am happy to merge this when there's consensus on the HA architecture side that it will be added.

**Comment by sygys** [comment]
So if im correct you mean the esphome integration on Home assistant needs to be adjusted? because the climate integration of home assistant with other integrations work just fine with fan speeds and swingmodes
panasonic

**Comment by OttoWinter** [comment]
Those are fan and swing mode. ESPHome already supports that in the architecture.

**Pull request closed without merging**
