### PR TITLE
Always publish energy to address esphome/issues#5501

### LINKED ISSUE #5501: CSE7766 hard to use since ESPHome 2024.2.0
### The problem

With the updates to cse7766 in ESPHome 2024.2.0 (esphome/esphome#6095 and esphome/esphome#6180), it now publishes sensor readings as fast at they come in from the cse7766.

This initially sounds like a good idea, because the user can choose how to filter them. But a couple subtle edge cases are very hard to handle with filters, and were handled quite nicely on the old setup that published all values at once.

- Not using any filters isn't really possible due to the \~10 Hz update rate of the cse7766 when under load. The obvious solution is [throttle_average](https://esphome.io/components/sensor/#throttle-average).
- But under very low and no-load (e.g. Sonoff S31 with the relay off), the cse7766 only has a valid current and power reading very infrequently. Maybe every minute or two.
  - If using [throttle_average](https://esphome.io/components/sensor/#throttle-average), it starts reporting Unknown for current and power, when we really know it to be 0.
    - Extending the timeframe we average over partially solves this, but then results in very unresponsive measurements.
  - If using [throttle](https://esphome.io/components/sensor/#throttle), we miss short transients that could/would meaningfully impact the average value, making the readings less useful.
- Readings are no longer published at the same time, which reduces the accuracy of downstream calculations (such as power factor or apparent power). Though the accuracy may have been dubious to begin with, publishing the voltage, power, and current readings at different times feels like a regression since it makes those calculations worse.

I can't come up with a filter stack to address most of these problems without major downsides.
I propose reverting to the previous behavior: esphome/esphome#6265

<details><summary>Original, inaccurate/incomplete problem statement</summary>

[esphome#6095](https://github.com/esphome/esphome/pull/6095) introduced a bug where the energy output of the CSE7766 will not publish when there is no power consumption.

An attempt to publish an initial 0 was included ([esphome/components/cse7766/cse7766.cpp:166](https://github.com/esphome/esphome/blob/75af4c3d629768ba257d55a89fe40a266ef2fee2/esphome/components/cse7766/cse7766.cpp#L166)) but it does not actually work:
image

Due to the way it was rearchitected, energy only updates when power is present, and now updates at \~10 Hz, so a filter is basically required to not spam Home Assistant to death. But due to energy now only _sometimes_ publishing values, it makes selecting a filter very difficult.

Using the obvious [throttle_average](https://esphome.io/components/sensor/#throttle-average) filter causes the energy to report Unknown not just at startup, but again any time power consumption drops to 0!
[heartbeat](https://esphome.io/components/sensor/#heartbeat) and [throttle](https://esphome.io/components/sensor/#throttle) kind of work, but still suffer from the initial Unknown state.

IMO the only real fix for this is to publish the energy sensor at the same time/rate as the other sensors, even if there is no new energy value. Since a filter is basically required now, it will be handled just like the other sensors and behave consistently.

I will push a PR tomorrow, but I have a fix working on an outlet now. I will try to also update the documentation at the same time.
</details>

### Which version of ESPHome has the issue?

2024.2.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2.2

### What platform are you using?

ESP8266

### Board

Sonoff S31

### Component causing the issue

cse7766

### Example YAML snippet

```yaml
esphome:
  name: s31
  friendly_name: S31
  comment: Sonoff S31 Smart Outlet

esp8266:
  board: esp01_1m

logger:
  baud_rate: 0

api:

ota:

wifi:
  ap:

captive_portal:

uart:
  rx_pin: RX
  baud_rate: 4800

switch:
  - platform: gpio
    name: None
    id: relay
    pin: GPIO12

binary_sensor:
  - platform: gpio
    id: power_button
    entity_category: diagnostic
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

sensor:
  - platform: cse7766
    current:
      name: Current
      id: current
    voltage:
      name: Voltage
      id: voltage
    power:
      name: Power
      id: power
    energy:
      name: Energy

status_led:
  pin: GPIO13
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DAVe3283**
# What does this implement/fix?

Energy would not be published after startup/reboot. All other sensors of the CSE7766 publish at \~10 Hz, so publish energy at the same time and let the user handle it the same way. It would publish at \~10 Hz when power is being consumed anyway, so they needed a filter regardless.

**HOWEVER** I believe reverting the original breaking change change (esphome/esphome#6095) is the correct solution here, not this band-aid: #6265 

The way the component works, the individual outputs drift out of sync with each other, which makes calculating things like power factor or apparent power impossible, since they have to be measured over the same time period.

The original implementation intentionally averaged everything together over a _single_ time period, which enabled calculating downstream values (power factor, apparent power) that had meaning. Notice how after only 2 hours of uptime, the sensors are now reporting over a 15-second window, instead of simultaneously as they should:

```
[12:05:09][D][sensor:093]: 'Uptime': Sending state 10122.79492 s with 0 decimals of accuracy
[12:05:22][D][sensor:093]: 'Energy': Sending state 0.53937 Wh with 0 decimals of accuracy
[12:05:25][D][sensor:093]: 'Voltage': Sending state 120.19772 V with 1 decimals of accuracy
[12:05:32][D][sensor:093]: 'Current': Sending state 0.20806 A with 2 decimals of accuracy
[12:05:37][D][sensor:093]: 'Power': Sending state 23.99924 W with 1 decimals of accuracy
```

I don't know how to solve this with filters, and think the original solution of building the averaging into the component itself was the right answer.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes esphome/issues#5501

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3620

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
external_components:
  - source: github://pr#6261
    components: [ cse7766 ]

sensor:
  - platform: cse7766
    current:
      name: Current
      id: current
      filters:
        - throttle_average: 60s
    voltage:
      name: Voltage
      id: voltage
      filters:
        - throttle_average: 60s
    power:
      name: Power
      id: power
      filters:
        - throttle_average: 60s
    energy:
      name: Energy
      filters:
        - throttle: 60s
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by DAVe3283** [comment]
My preference would be to merge #6265 instead of this band-aid PR.

**Comment by ssieb** [comment]
I'm curious how you can calculate power factor with averaged values.  That doesn't make sense to me.
If the throttle average outputs are drifting out of sync, I think that's a bug in the filter.

**Comment by DAVe3283** [comment]
> I'm curious how you can calculate power factor with averaged values. That doesn't make sense to me.

It does require the power factor be approximately constant over the averaging period, but since most loads have a static power factor over the short-term (10-60 seconds), it works very well in practice.

For example, this is a car battery charger as it brings a dead battery up to the float voltage over the course of a couple weeks:
image

> If the throttle average outputs are drifting out of sync, I think that's a bug in the filter.

It looks like they start out of sync right after a reboot. Using the YAML in this PR, this is what I get right out of the gate:

```
[15:42:16][D][sensor:093]: 'Uptime': Sending state 63.01600 s with 0 decimals of accuracy
[15:42:23][D][sensor:093]: 'Energy': Sending state 0.00000 Wh with 3 decimals of accuracy
[15:42:39][D][sensor:093]: 'Power': Sending state 0.00000 W with 1 decimals of accuracy
[15:42:39][D][sensor:093]: 'Voltage': Sending state 122.94889 V with 1 decimals of accuracy
[15:42:43][D][sensor:093]: 'Current': Sending state 0.00000 A with 2 decimals of accuracy
```

So immediately after reboot the Power & Voltage readings come in 4 seconds before the Current reading does.

And while I suspect power factor and apparent power can still be calculated off this in the long-term (e.g. weeks as my example above) it will be much less responsive to changes on the order of the averaging period.

**Comment by ssieb** [comment]
The offset will be consistent, but different on every boot.  It's a side effect of how the throttle filter does the timing.

**Comment by DAVe3283** [comment]
Yeah, but that is a problem the old built-in averaging filter solved, so it still feels like a regression to me.

But if the consensus is the new way is preferred, I can live with the slightly less responsive power factor and active power calculations. Though this MR is still needed to prevent energy from showing "Unknown" at startup.

**Comment by ssieb** [comment]
I would like to fix that offset issue in some way.
The energy issue appears to be caused by #6180 not #6095.

**Comment by DAVe3283** [comment]
> I would like to fix that offset issue in some way. Is the energy issue caused by #6095 or #6180?

It was caused by an oversight in #6095, specifically an incorrect assumption that `this->energy_sensor_->has_state()` would return true only once a valid state had been published.

That is why my PR #6265 only reverts #6095 but keeps the changes from #6180.

**Comment by ssieb** [comment]
How is that an incorrect assumption?  That's literally what that method is for.

**Comment by DAVe3283** [comment]
~~Regardless of the intention of the function / code written there, as seen in the [issue I opened](https://github.com/esphome/issues/issues/5501), it doesn't actually report 0 on startup.~~

~~My read of the code ([esphome/components/sensor/sensor.cpp:90](https://github.com/esphome/esphome/blob/76a3ffc8a9961bab029a33f91b833a92b014c274/esphome/components/sensor/sensor.cpp#L90C1-L97C60)) sure looks like as soon as any state (including the initial NAN) get sent to the frontend, it will report that it has a state. But I could be reading it wrong. Either way, it doesn't report 0 on startup and this PR fixes that.~~

If there is a better way, let me know.

EDIT: I stand corrected, this appears to have been a filter I applied to try and tame the update rate.
But without reverting to the old behavior, after a reboot it doesn't report values consistently with a throttle_average filter:

image

```
[19:49:45][D][api.connection:1121]: Home Assistant 2024.1.5 (10.0.1.19): Connected successfully
[19:49:45][D][time:048]: Synchronized time: 2024-02-21 19:49:45
[19:49:49][D][sensor:093]: 'Power': Sending state nan W with 1 decimals of accuracy
[19:49:57][D][sensor:093]: 'Current': Sending state nan A with 2 decimals of accuracy
[19:49:59][D][sensor:093]: 'Voltage': Sending state nan V with 1 decimals of accuracy
[19:50:19][D][sensor:093]: 'Power': Sending state nan W with 1 decimals of accuracy
[19:50:21][D][sensor:093]: 'Uptime': Sending state 58.57100 s with 0 decimals of accuracy
[19:50:27][D][sensor:093]: 'Current': Sending state 0.00000 A with 2 decimals of accuracy
[19:50:29][D][sensor:093]: 'Voltage': Sending state 117.08681 V with 1 decimals of accuracy
[19:50:49][D][sensor:093]: 'Power': Sending state 0.00000 W with 1 decimals of accuracy
[19:50:57][D][sensor:093]: 'Current': Sending state nan A with 2 decimals of accuracy
[19:50:59][D][sensor:093]: 'Voltage': Sending state nan V with 1 decimals of accuracy
[19:51:19][D][sensor:093]: 'Power': Sending state nan W with 1 decimals of accuracy
```

**Comment by DAVe3283** [comment]
After more experimentation, this is not the solution to the problems seen with the updated component. Closing this PR.

**Pull request closed without merging**
