### PR TITLE
Internal temperature: Support Beken platform

### PR DESCRIPTION
**Pull request by Mat931**
# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3746

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [x] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
bk72xx:
  board: generic-bk7231n-qfn32-tuya

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]

**Comment by yousaf465** [comment]
working.

image

**Comment by kuba2k2** [comment]
Unfortunately, this is not the right way to implement LibreTiny features. The main goal of LibreTiny is to expose a common, chip-independent API - using the BDK functions effectively prevents that. The API function you used might be gone in the future - the BDK will be restructured along with a major refactor of LibreTiny.

The correct way would be to implement such an API in LibreTiny itself - for example `lt_cpu_get_temp()`. It can then be implemented for the `beken-72xx` platform and used in ESPHome.

**Comment by Mat931** [comment]
@kuba2k2 You're right, this should only be a temporary solution. Unfortunately I don't have a lot of LibreTiny experience or testing hardware. I couldn't find anything temperature related in LibreTiny so I implemented it using the BDK function. When LibreTiny supports such a function I'll gladly use it and have a cleaner solution.

A bit off-topic: I'm currently working on a component for driving addressable LED strips (WS2812 etc) using the Beken SPI DMA interface that follows a similar approach of using BDK functions. Maybe you want to take a look at how to improve that too. I'll make a pull request when it's ready.

**Comment by kuba2k2** [comment]
There's a separate branch on which I started implementing I2C and SPI support:
https://github.com/libretiny-eu/libretiny/tree/feature/i2c-spi
However, I haven't been able to get the SPI to fully work. I only got it to transmit data, and only at a specific clock rate.

**Pull request merged**
