### PR TITLE
Add publish_initial_value option to rotary encoder

### LINKED ISSUE #2535: Unable to set value 0 (zero) to internal state of the rotary encoder at startup
### The problem

I am unable to set value 0 (zero) to rotary encoder variable at the begining. This code is working fine with any other values but with 0 (zero) i am facing with "Unknown":
image

`esphome:
  name: rotary_test
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 600
    then:
      - sensor.rotary_encoder.set_value:
          id: rotary1
          value: 0
sensor:
  - platform: rotary_encoder
    id: rotary1
    name: Rotary Encoder
    pin_a:
      number: D1
    pin_b:
      number: D2`

But if i set value, for example 1 and then set 0 this will work
image

`  on_boot:
    priority: 600
    then:
      - sensor.rotary_encoder.set_value:
          id: rotary1
          value: 1
      - sensor.rotary_encoder.set_value:
          id: rotary1
          value: 0`

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2021.10.2

### What platform are you using?

ESP8266

### Board

wemos d1 mini v3

### Component causing the issue

Rotary Encoder Sensor

### Example YAML snippet

```yaml
esphome:
  name: rotary_test
  platform: ESP8266
  board: d1_mini
  on_boot:
    priority: 600
    then:
      - sensor.rotary_encoder.set_value:
          id: rotary1
          value: 0
sensor:
  - platform: rotary_encoder
    id: rotary1
    name: Rotary Encoder
    pin_a:
      number: D1
    pin_b:
      number: D2
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by niklasweber**
# What does this implement/fix? 

After boot, the state of a rotary encoder is unknown. With this fix, the initial state after boot is 0.

The state is unknown because it is not published until user input is provided (the encoder is turned). 
The counter is initialized with 0 and the previous counter value (last_read) with 0 as well. At the end of the loop of the rotary_encoder component a check takes place whether the counter changed. If both values are the same, publish_state is not called. However, initializing last_read with something other than counter causes the state to be updated once on start (and on user input, as before).

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/2535

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
...
sensor:
  - platform: rotary_encoder
    id: rotary1
    name: Rotary Encoder
    pin_a:
      number: D1
    pin_b:
      number: D2

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs) (https://github.com/esphome/esphome-docs/pull/1565).

### CODE REVIEW

**Review by davet2001 — APPROVED** [review]
The logic makes sense.

I understand that every restart will now trigger a republish of the rotation count which could trigger various actions.  But I assume this is preferable to publishing nothing only to trigger a (potentially very large) published state change in the future when the first tiny movement is made.

This might be a breaking change  for anyone assuming that a change in state means something just moved.

**Comment by markusg1234** [comment]
Hi,
I normaly set the encoder on boot using a global as seen below. 
I tried a number of ways to set the initial boot position but only could get it to work with a global.
Will this change effect it?
  
on_boot:
    then:
      - switch.turn_off: open_switch
      - switch.turn_off: close_switch 
      - sensor.rotary_encoder.set_value:
            id: dining_room_rotary_encoder
            value: !lambda |-
               return id(dining_room_rotary_encoder_global);

      - lambda: |-
          id(dining_room_cover).publish_state(dining_room_cover_global);

**Comment by niklasweber** [comment]
Thanks for the input. I didn't think about that. Indeed I also think this could be a breaking change for some people. However maybe I could make the change an optional feature and keep the default as it is. I'm thinking of adding a boolean configuration variable "publish_state_on_boot" and perhaps another variable "start_value". What are your thoughts on that? Does it make sense? Is the naming good?

**Comment by davet2001** [comment]
Start value would seem to have no reliable meaning for a relative encoder.  I'm struggling to see the use case where you need to set a value at startup.  Perhaps you are assuming that it starts up in a particular position - how do you know?  Surely any offset is meaningless until you've indexed to a known position via a startup sequence or triggered a reset pin?

I wonder whether publishing the initial state as 'Unknown' might be more helpful in the general case.   Unknown could then mean something like "this device has just reset and hasn't moved yet", and logic (on other devices) has the potential to detect this and avoid triggering automations for reboots that would look like movement.

I.e. currently 1->0 could mean:
- Device moved negative
- Device was powered off, moved an undefined amount then was powered on, and moved positive then immediately negative

With your proposal 1->0 could mean:
- device moved negative
- device rebooted
- device was powered off, moved an undefined amount then powered back on again

With an unknown state implemented,  1->0 only happens on genuine movement.  All power cycles result in an 'unknown' state.

**Comment by niklasweber** [comment]
When looking at it in a relative way, a start value is useless, you are absolutely right. You don't need to know the, let's say physical position of the encoder. You only care about the direction. However, just so that we're on the same page, the rotary_encoder component in esphome keeps an internal int32_t counter which by default ranges from INT32_MIN to INT32_MAX and this counter value is published. So it is not a relative value anymore but an absolute one.
Your concern is valid, if the initial counter value of 0 is published on boot, this would trigger an event and maybe cause unwanted effects. Let's say the brightness of a light was 255, esphome restarts, then the light would be set to 0. But by making this optional using a "publish_state_on_boot" variable gives users the option to get this behaviour if they need it (see https://github.com/esphome/issues/issues/2535). And adding "start_value" would give some more control in situations like the light, when you would want the light to be on on reset. But the start_value is still an add-on for me, I would probably leave it out first unless it is very easy to implement. Hope I was not completely missing your point.

**Comment by davet2001** [comment]
>However, just so that we're on the same page, the rotary_encoder component in esphome keeps an internal int32_t counter which by default ranges from INT32_MIN to INT32_MAX and this counter value is published. So it is not a relative value anymore but an absolute one.

I think it's still a relative value if there is no reference point.  It's relative to wherever it was when it booted.  So if it reports  7, it could be in one position, and the next day it is in the same position but reports 0.

My point is what's the need to initialise it to anything specific?

Probably I'm thinking about [absolute vs incremental encoders](https://www.designworldonline.com/what-is-the-difference-between-an-absolute-and-incremental-position-encoder/) from a work context when used to measure something.  We used an incremental encoder and had to do a full rotation powered by a motor (crossing the index point) before we could do anything useful.  In another project an absolute encoder could tell immediately where it was, but this needed many digital inputs.



If you are talking about using a rotary encoder as a dimmer jog dial, then this makes a lot more sense.  If it's a continuous rotation sensor with no end stops or markings, then actual rotation position doesn't matter, just more vs less.  You could [initialise](https://www.designworldonline.com/what-is-the-difference-between-an-absolute-and-incremental-position-encoder/) to what you knew the light level to be at bootup and publish it if desired.

Ultimately if it's optional arguments & defaulting to the existing behaviour, then why not!

**Comment by markusg1234** [comment]
One thing I am wondering is with the reported issue 2335 is why 
- sensor.rotary_encoder.set_value: 
- id: rotary1
value: 0

doesn't set it to 0 and you need to first set it to a 1 and then a 0 for it to work.

Is this a bug?

on_boot: priority: 600 then: - sensor.rotary_encoder.set_value: id: rotary1 value: 1 - sensor.rotary_encoder.set_value: id: rotary1 value: 0

**Comment by niklasweber** [comment]
@markusg1234 if you set it to 0 nothing happens because internally counter and last_read already are initialised to 0 and a new state is only published when the counter differs from last_read. Have a look at https://github.com/esphome/esphome/blob/1308236429d1564ed7cb14ee38c5d904f0c22916/esphome/components/rotary_encoder/rotary_encoder.cpp#L192

That's also the reason why initially after boot the state is unknown. As long as last_read and counter are the same, the state is not published. This is necessary as the check happens in a loop. If it was not in place, the state would be constantly updated.

**Comment by niklasweber** [comment]
I added the optional boolean variable "publish_initial_value". By default it is set to false and the behavior doesn't change. When setting it to true the counter value is published once after boot and on change. I also updated the documentation (https://github.com/esphome/esphome-docs/pull/1565). Hopefully this PR can be merged now. Thanks!

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
