### PR TITLE
[Modbus Controller] Added `on_online` and `on_offline` automation

### PR DESCRIPTION
**Pull request by 0x3333**
# What does this implement/fix?

Added `on_online` and `on_offline` automation to `modbus_controller`. In some cases, you need to configure the module when it goes back online, the offline automation is a bonus just in case.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#4231

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
modbus_controller:
  - id: modbus_controller1
    address: 0x2
    modbus_id: mod_bus1
    on_online:
      - then:
        - logger.log: "Module Online"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nagyrobi** [comment]
Wonderful! These will be extremely useful by the time setting the entity availability will be possible!!

**Comment by 0x3333** [comment]
Don't know why it is failing the tests... I tested in Arduino and IDF.

**Comment by 0x3333** [comment]
Anyone in this? @martgras? Thanks

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
I was about to merge, you didnt need to merge dev in again :rofl: 
Now it has to wait for CI to finish

**Comment by 0x3333** [comment]
> I was about to merge, you didnt need to merge dev in again 🤣 Now it has to wait for CI to finish

Oops...

**Pull request merged**
