### PR TITLE
Bluetooth advertising automation

### PR DESCRIPTION
**Pull request by puuu**
## Description:
Add automations that trigger on Bluetooth advertising messages:
- raw advertising message
- service data advertising message
- manufacturer data advertise message

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#512

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by brandond** [comment]
It looks like the resulting test2 firmware is too large. Can you try moving the tests to another yaml?

**Comment by puuu** [comment]
The `esp32_ble_tracker` component is only in test2. The last commit removes `deep_sleep` from test2 to make test2 successful. However, we need a better solution, as the next change related to `esp32_ble_tracker` will hit the same problem.

**Comment by TheKuko** [comment]
@puuu  Hey, I've just had the same problem in my PR as well. I moved some tests to test3.yaml too, hopefully, I did not break anything.

**Comment by glmnet** [comment]
LGTM

**Pull request merged**
