### PR TITLE
new parser values

### PR DESCRIPTION
**Pull request by bwynants**
# What does this implement/fix?

new p1 values for capacity tariff

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
    active_energy_import_current_average_demand:
      name: "Current Average Demand"
    active_energy_import_maximum_demand_running_month:
      name: "Maximum Month Demand"
    active_energy_import_maximum_demand_last_13_months:
      name: "13 Month Maximum Quarterly Demand"

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — DISMISSED** [review]

**Comment by bartv** [comment]
This is related to this feature request: https://github.com/esphome/feature-requests/issues/2046

**Comment by bwynants** [comment]
this last commit requires https://github.com/glmnet/arduino-dsmr/pull/15

**Comment by alainsmedts** [comment]
When will this be approved and become available?

**Comment by bwynants** [comment]
> When will this be approved and become available?

it is waiting on https://github.com/glmnet/arduino-dsmr/pull/15 but you can already use it.
see https://github.com/esphome/feature-requests/issues/2046#issuecomment-1435653138

when it becomes approved you just remove the extra references....

**Comment by alainsmedts** [comment]
> > When will this be approved and become available?
> 
> it is waiting on [glmnet/arduino-dsmr#15](https://github.com/glmnet/arduino-dsmr/pull/15) but you can already use it. see [esphome/feature-requests#2046 (comment)](https://github.com/esphome/feature-requests/issues/2046#issuecomment-1435653138)
> 
> when it becomes approved you just remove the extra references....

I'm using slimme lezer and added following to slimmelezer.yaml:
substitutions:
  name: slimmelezer
packages:
  zuidwijk.slimmelezer: github://zuidwijk/dsmr/slimmelezer.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: ......


wifi:
  ssid: ...
  password: ...

external_components:
  - source:
      type: git
      url: https://github.com/bwynants/esphome
      ref: capacity_test
    components: [dsmr]
    refresh: 0s
and installed on my device, however I don't see the new values appearing. Am I doing something wrong?

**Comment by bwynants** [comment]
> > > When will this be approved and become available?
> > 
> > 
> > it is waiting on [glmnet/arduino-dsmr#15](https://github.com/glmnet/arduino-dsmr/pull/15) but you can already use it. see [esphome/feature-requests#2046 (comment)](https://github.com/esphome/feature-requests/issues/2046#issuecomment-1435653138)
> > when it becomes approved you just remove the extra references....
> 
> I'm using slimme lezer and added following to slimmelezer.yaml: substitutions: name: slimmelezer packages: zuidwijk.slimmelezer: github://zuidwijk/dsmr/slimmelezer.yaml@main esphome: name: ${name} name_add_mac_suffix: false api: encryption: key: ......
> 
> wifi: ssid: ... password: ...
> 
> external_components:
> 
> * source:
>   type: git
>   url: https://github.com/bwynants/esphome
>   ref: capacity_test
>   components: [dsmr]
>   refresh: 0s
>   and installed on my device, however I don't see the new values appearing. Am I doing something wrong?

you forgot to add the sensors...

sensor:
  - platform: dsmr
    active_energy_import_current_average_demand:
      name: "Current Average Quarterly Demand"
    active_energy_import_maximum_demand_running_month:
      name: "Month Maximum Quarterly Demand"
    active_energy_import_maximum_demand_last_13_months:
      name: "13 Month Maximum Quarterly Demand"

**Comment by alainsmedts** [comment]
> > > > When will this be approved and become available?
> > > 
> > > 
> > > it is waiting on [glmnet/arduino-dsmr#15](https://github.com/glmnet/arduino-dsmr/pull/15) but you can already use it. see [esphome/feature-requests#2046 (comment)](https://github.com/esphome/feature-requests/issues/2046#issuecomment-1435653138)
> > > when it becomes approved you just remove the extra references....
> > 
> > 
> > I'm using slimme lezer and added following to slimmelezer.yaml: substitutions: name: slimmelezer packages: zuidwijk.slimmelezer: github://zuidwijk/dsmr/slimmelezer.yaml@main esphome: name: ${name} name_add_mac_suffix: false api: encryption: key: ......
> > wifi: ssid: ... password: ...
> > external_components:
> > 
> > * source:
> >   type: git
> >   url: https://github.com/bwynants/esphome
> >   ref: capacity_test
> >   components: [dsmr]
> >   refresh: 0s
> >   and installed on my device, however I don't see the new values appearing. Am I doing something wrong?
> 
> you forgot to add the sensors...
> 
> sensor:
> 
> * platform: dsmr
>   active_energy_import_current_average_demand:
>   name: "Current Average Quarterly Demand"
>   active_energy_import_maximum_demand_running_month:
>   name: "Month Maximum Quarterly Demand"
>   active_energy_import_maximum_demand_last_13_months:
>   name: "13 Month Maximum Quarterly Demand"

I put the sensor wrongly in configuration.yaml, however now I'm getting following error:
Compiling /data/slimmelezer/.pioenvs/slimmelezer/src/main.cpp.o
In file included from src/esphome/components/api/api_frame_helper.h:7,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/defines.h:4: warning: "DSMR_SENSOR_LIST" redefined
    4 | #define DSMR_SENSOR_LIST(F, sep) F(energy_delivered_lux) sep F(energy_delivered_tariff1) sep F(energy_delivered_tariff2) sep F(energy_returned_lux) sep F(energy_returned_tariff1) sep F(energy_returned_tariff2) sep F(power_delivered) sep F(power_returned) sep F(electricity_failures) sep F(electricity_long_failures) sep F(voltage_l1) sep F(voltage_l2) sep F(voltage_l3) sep F(current_l1) sep F(current_l2) sep F(current_l3) sep F(power_delivered_l1) sep F(power_delivered_l2) sep F(power_delivered_l3) sep F(power_returned_l1) sep F(power_returned_l2) sep F(power_returned_l3) sep F(gas_delivered) sep F(gas_delivered_be)
      | 
In file included from src/esphome/components/api/api_frame_helper.h:7,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/defines.h:3: note: this is the location of the previous definition
    3 | #define DSMR_SENSOR_LIST(F, sep) F(active_energy_import_current_average_demand) sep F(active_energy_import_maximum_demand_running_month) sep F(active_energy_import_maximum_demand_last_13_months)
      | 
src/main.cpp: In function 'void setup()':
src/main.cpp:885:18: error: 'class esphome::dsmr::Dsmr' has no member named 'set_active_energy_import_current_average_demand'
  885 |   dsmr_instance->set_active_energy_import_current_average_demand(sensor_sensor_25);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:895:18: error: 'class esphome::dsmr::Dsmr' has no member named 'set_active_energy_import_maximum_demand_running_month'
  895 |   dsmr_instance->set_active_energy_import_maximum_demand_running_month(sensor_sensor_26);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:905:18: error: 'class esphome::dsmr::Dsmr' has no member named 'set_active_energy_import_maximum_demand_last_13_months'
  905 |   dsmr_instance->set_active_energy_import_maximum_demand_last_13_months(sensor_sensor_27);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*** [/data/slimmelezer/.pioenvs/slimmelezer/src/main.cpp.o] Error 1
========================== [FAILED] Took 8.05 seconds ==========================

**Comment by bwynants** [comment]
> I put the sensor wrongly in configuration.yaml, however now I'm getting following error: Compiling 

maybe put external component before package?

**Comment by alainsmedts** [comment]
> > I put the sensor wrongly in configuration.yaml, however now I'm getting following error: Compiling
> 
> maybe put external component before package?

Doesn't help (moved it to different places). I'm using ESPHome version: 2023.3.2, This is the full output of the install:
INFO Reading configuration /config/esphome/slimmelezer.yaml...
INFO Updating https://github.com/bwynants/esphome@capacity_test
INFO Generating C++ source...
INFO Compiling app...
Processing slimmelezer (board: d1_mini; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Dependency Graph
|-- ESPAsyncTCP-esphome @ 1.2.3
|-- ESPAsyncWebServer-esphome @ 2.1.0
|   |-- ESPAsyncTCP-esphome @ 1.2.3
|   |-- Hash @ 1.0
|   |-- ESP8266WiFi @ 1.0
|-- DNSServer @ 1.1.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- ArduinoJson @ 6.18.5
|-- Dsmr @ 0.6.0+sha.ef23bec
|-- Crypto @ 0.4.0
|-- noise-c @ 0.1.4
|   |-- libsodium @ 1.10018.1
Compiling /data/slimmelezer/.pioenvs/slimmelezer/src/main.cpp.o
In file included from src/esphome/components/api/api_frame_helper.h:7,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/defines.h:4: warning: "DSMR_SENSOR_LIST" redefined
    4 | #define DSMR_SENSOR_LIST(F, sep) F(energy_delivered_lux) sep F(energy_delivered_tariff1) sep F(energy_delivered_tariff2) sep F(energy_returned_lux) sep F(energy_returned_tariff1) sep F(energy_returned_tariff2) sep F(power_delivered) sep F(power_returned) sep F(electricity_failures) sep F(electricity_long_failures) sep F(voltage_l1) sep F(voltage_l2) sep F(voltage_l3) sep F(current_l1) sep F(current_l2) sep F(current_l3) sep F(power_delivered_l1) sep F(power_delivered_l2) sep F(power_delivered_l3) sep F(power_returned_l1) sep F(power_returned_l2) sep F(power_returned_l3) sep F(gas_delivered) sep F(gas_delivered_be)
      | 
In file included from src/esphome/components/api/api_frame_helper.h:7,
                 from src/esphome/components/api/api_connection.h:3,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/core/defines.h:3: note: this is the location of the previous definition
    3 | #define DSMR_SENSOR_LIST(F, sep) F(active_energy_import_current_average_demand) sep F(active_energy_import_maximum_demand_running_month) sep F(active_energy_import_maximum_demand_last_13_months)
      | 
src/main.cpp: In function 'void setup()':
src/main.cpp:885:18: error: 'class esphome::dsmr::Dsmr' has no member named 'set_active_energy_import_current_average_demand'
  885 |   dsmr_instance->set_active_energy_import_current_average_demand(sensor_sensor_25);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:895:18: error: 'class esphome::dsmr::Dsmr' has no member named 'set_active_energy_import_maximum_demand_running_month'
  895 |   dsmr_instance->set_active_energy_import_maximum_demand_running_month(sensor_sensor_26);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:905:18: error: 'class esphome::dsmr::Dsmr' has no member named 'set_active_energy_import_maximum_demand_last_13_months'
  905 |   dsmr_instance->set_active_energy_import_maximum_demand_last_13_months(sensor_sensor_27);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*** [/data/slimmelezer/.pioenvs/slimmelezer/src/main.cpp.o] Error 1
========================== [FAILED] Took 8.07 seconds ==========================

**Comment by bwynants** [comment]
>> ## Doesn't help (moved it to different places). I'm using ESPHome version: 2023.3.2, This is the full output of the install:
remove

packages:
  zuidwijk.slimmelezer: github://zuidwijk/dsmr/slimmelezer.yaml@main

and copy content of https://github.com/zuidwijk/dsmr/blob/main/slimmelezer.yaml directly in your file....

**Comment by alainsmedts** [comment]
> > > ## Doesn't help (moved it to different places). I'm using ESPHome version: 2023.3.2, This is the full output of the install:
> 
> remove
> 
> packages: zuidwijk.slimmelezer: github://zuidwijk/dsmr/slimmelezer.yaml@main
> 
> and copy content of https://github.com/zuidwijk/dsmr/blob/main/slimmelezer.yaml directly in your file....

This indeed did the trick, many thanks! One more question, when this will be approved and become available will this work without the complete content of https://github.com/zuidwijk/dsmr/blob/main/slimmelezer.yaml, or should I keep the settings I have now?

**Comment by bwynants** [comment]
> > > > ## Doesn't help (moved it to different places). I'm using ESPHome version: 2023.3.2, This is the full output of the install:
> > 
> > 
> > remove
> > packages: zuidwijk.slimmelezer: github://zuidwijk/dsmr/slimmelezer.yaml@main
> > and copy content of https://github.com/zuidwijk/dsmr/blob/main/slimmelezer.yaml directly in your file....
> 
> This indeed did the trick, many thanks! One more question, when this will be approved and become available will this work without the complete content of https://github.com/zuidwijk/dsmr/blob/main/slimmelezer.yaml, or should I keep the settings I have now?

only @glmnet and @jesserockz can answer when it will be integrated. I hope soon for the belgian users... I'm sure it helps that you confirmed it works... 

if they commit the next step is that @zuidwijk adds the sensors to his yaml

**Comment by netweaver1970** [comment]
The new code compiles fine and works but I see the ESPhome YAML editor doesn't 'recognize' the 3rd new parameter yet. Maybe that can be fixed as well before getting it integrated? It confused me and might confuse others too:
image

**Comment by bwynants** [comment]
> The new code compiles fine and works but I see the ESPhome YAML editor doesn't 'recognize' the 3rd new parameter yet. Maybe that can be fixed as well before getting it integrated? It confused me and might confuse others too:

I think this means you forgot the external_components: part somehow....

**Comment by netweaver1970** [comment]
No, it can't be otherwise the first 2 also NEW values would not be accepted in the editor and the code wouldn't compile and install fine into the device... 

It's just a gui thing: the live pre-compilation check. It's not really killing anything, just confusing due to the other 2 being 100% validated.

**Comment by netweaver1970** [comment]
This is my external component 'include'image

**Comment by VerstrooidProfke** [comment]
eagerly waiting for this one to be merged, but after more than 3 months, my hope is getting smaller
Therefore, i would find out how to make the not-merged version work for me. 

As i'm still a beginner in ESPhome,
i fail to see how the "draft version" can be included.

Could somebody post a "complete" working dsmr-read config, because the snippets above do not allow me to find out what to copy and paste in my config to make it work.
or tell me what to change for making "my" config work? 

[smartmeter.yml.txt](https://github.com/esphome/esphome/files/11609852/smartmeter.yml.txt)

**Comment by MaT-dg** [comment]
Also waiting for this.
Any feedback to us why it is taking so long?

**Pull request closed without merging**
