### PR TITLE
dashboard: fix supervisor auth doing I/O in the event loop

### PR DESCRIPTION
**Pull request by bdraco**
# What does this implement/fix?

dashboard: fix supervisor auth doing I/O in the event loop

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by bdraco** [comment]
This one is a bit harder to test

So I'm going to clone this PR and

`root@5c53de3b-esphome-dev:~/esphome/esphome# rsync -av dashboard/ /esphome/esphome/dashboard/`

**Comment by jesserockz** [comment]
> This one is a bit harder to test
> 
> So I'm going to clone this PR and
> 
> `root@5c53de3b-esphome-dev:~/esphome/esphome# rsync -av dashboard/ /esphome/esphome/dashboard/`

The dev addon has a `esphome_fork` config option that will clone a branch from anywhere and run that code instead of the builtin code.

**Review by jesserockz — APPROVED** [review]
LGTM

**Comment by bdraco** [comment]
> > This one is a bit harder to test
> > So I'm going to clone this PR and
> > `root@5c53de3b-esphome-dev:~/esphome/esphome# rsync -av dashboard/ /esphome/esphome/dashboard/`
> 
> The dev addon has a `esphome_fork` config option that will clone a branch from anywhere and run that code instead of the builtin code.

Nice. rsync over it and restarting the container worked fine, but it would have made testing a lot easier to use that option 😉

**Comment by bdraco** [comment]
thanks

**Pull request merged**
