### PR TITLE
Add LD2420 support [ not ready yet ]

### LINKED ISSUE #2219: Support Hi-Link LD2420 (HLK-LD2420) 24GHz Radar Sensor
**Describe the problem you have/What new integration you would like**

* Similar to the [LD2410](https://esphome.io/components/sensor/ld2410.html) Module, the LD2420 is a 24GHz Radar Sensor

**Please describe your use case for this integration and alternatives you've tried:**

* Use LD2420 in place of LD2410

**Additional context**

* Protocol information can be found at https://github.com/soubhik-khan/HLK-LD2420
* https://www.hlktech.net/index.php?id=1150

### PR DESCRIPTION
**Pull request by max246**
# What does this implement/fix?

Add LD2520 support to ESPHOME

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes  https://github.com/esphome/feature-requests/issues/2219

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by descipher** [comment]
Umm, I can't see how this code would work on the LD2420. Looks like a copy of the LD2410 to me.

**Comment by max246** [comment]
> Umm, I can't see how this code would work on the LD2420. Looks like a copy of the LD2410 to me.
I am waiting for the sensor to arrive, this is just a boilet plate for now. I got some more commands to convert but functinality wise would be similar to 2410

**Comment by timmo001** [comment]
I gave this a quick test with my LD2420 and nothing is reported so while no errors are reported, it will need work to be functional

**Comment by max246** [comment]
> I gave this a quick test with my LD2420 and nothing is reported so while no errors are reported, it will need work to be functional

as said the comment above is not ready.

**Comment by descipher** [comment]
Why do a PR on code that is known not to be functional? When you have something that can be reviewed then submit a PR.

**Comment by max246** [comment]
> Why do a PR on code that is known not to be functional? When you have something that can be reviewed then submit a PR.

You can same the thing on some of the other 100+ PRs, if you are keen on reviewing I have two FUNCTIONAL  prs that are ready to merge. 
It is just a waste of time to argue on a project that is not merging functionality straight away and it can wait until is all checked up. 

If you have meaningful comments please be part of the reviewers but otherwise it is just spamming

**Comment by descipher** [comment]
If you have something worth pulling then submit that, otherwise don’t waist the time of a reviewer with a wip that has no good reason to be here.

**Comment by max246** [comment]
> If you have something worth pulling then submit that, otherwise don’t waist the time of a reviewer with a wip that has no good reason to be here.

As said I have two ready PRs, I haven't seen you spend any second to review them just arguing on here. I am using my time to help out this project and it sounds stupid arguing in this matter.

As said again, if you are here to actually give meaningful help I am more than happy to listen but arguing on a PR that I stated I am still working on, please spare your time on other PRs which need more reviewing.

Thanks.

**Comment by descipher** [comment]
> As said I have two ready PRs, I haven't seen you spend any second to review them just arguing on here.

Where are they?

**Comment by descipher** [comment]
Please follow the norms:

The purpose of a Pull Request (PR) in GitHub is to propose changes to a repository's codebase, discuss those changes with other contributors, and merge the changes into the main codebase if they are accepted.

Here is how the process typically works:

1. A developer creates a new branch in the repository to work on a new feature or bug fix.
2. They make changes to the code and commit those changes to their branch.
3. Once they are finished, they create a Pull Request from their branch to the main branch of the repository (usually "master" or "main").
4. Other contributors can review the changes, leave comments, suggest modifications, and discuss the proposed changes with the author.
5. The author can make additional changes and commits to their branch in response to feedback until everyone is satisfied with the changes.
6. If the changes are approved, the Pull Request can be merged into the main branch, and the changes become part of the repository's codebase.

Pull Requests are an essential part of the collaborative development process in GitHub and other similar platforms. They allow multiple developers to work on the same codebase simultaneously, review and discuss changes before they are merged, and ensure that the code is of high quality and consistency.

**Comment by sebcaps** [comment]
@max246 , I don't understand either this PR. After a quick review it basically sounds like a copy/paste of LD2410 implementation (including codeowner ,😉)
If protocol/settings of ld2410 and LD2420 are similar, (I assume I did not read carefully 2420 doc) why not give a try to generic Ld24xx component and some specialized ld2410/ld2420?

**Comment by descipher** [comment]
> @max246 , I don't understand either this PR. After a quick review it basically sounds like a copy/paste of LD2410 implementation (including codeowner ,😉) If protocol/settings of ld2410 and LD2420 are similar, (I assume I did not read carefully 2420 doc) why not give a try to generic Ld24xx component and some specialized ld2410/ld2420?

@sebcaps

The LD2420 has significant differences and it would be hard to do a generic component for both. I have an external component preview build working at https://github.com/GelidusResearch/grps.git

The LD2420 has 16 timing sample gates, significantly higher range, no bluetooth, no light sensor and a cortex front end mpu vs the JL custom BT SOC with a different set of serial commands than the 2410. They do share some command frame structures like header/length/footer but the data streams and modes are completely different.

**Comment by lboue** [comment]
> The LD2420 has 16 timing sample gates, significantly higher range, no bluetooth, no light sensor and a cortex front end mpu vs the JL custom BT SOC with a different set of serial commands than the 2410. They do share some command frame structures like header/length/footer but the data streams and modes are completely different.

@descipher
Could you submit a new PR if your code works?

**Comment by descipher** [comment]
See #4847

**Pull request closed without merging**
