### PR TITLE
Added support for the RadonEye+2

### PR DESCRIPTION
**Pull request by valentinbarral**
# What does this implement/fix?

Added support for reading radon, temperature, and humidity values from RadonEye+2

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2153

## Test Environment

- [X] ESP32
- [X] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
    esp32_ble_tracker:

    ble_client:
      - mac_address: 01:02:03:04:05:06
        id: radon_eye_ble_id

    sensor:
      - platform: radon_eye_rd200_p2
        ble_client_id: radon_eye_ble_id
        update_interval: 10min
        radon:
          name: "Radon"
        temperature:
          name: "Temperature"
        humidity:
          name: "Humidity"
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jhitze** [comment]
I'm in need of this particular plugin, so I'm hoping to help push this along. @valentinbarral It looks like this needs to be rebased in order to be merged in.

**Comment by jesserockz** [comment]
Is this code basically the same as the other radoneye, but just with different sensors? If so, perhaps we could merge the two and have a `model` field which can then validate the correct sensors in config.

**Comment by alexspeller** [comment]
There is an additonal model of the other radoneye that is externally identical to the already supported model, with newer firmware, I am working on a PR to support that also, and was planning to add a type field as the code is similar.

With 3 models that can be supported, merging them likely makes sense

**Comment by jflattery** [comment]
This is still needed.

**Comment by HeedfulCrayon** [comment]
@alexspeller I don't know if this would help you, but this is some of the info that I have found https://github.com/esphome/issues/issues/3371#issuecomment-1357928742

**Pull request closed without merging**
