### PR TITLE
Make HOME 0 so it can be th default

### PR DESCRIPTION
**Pull request by Lumpusz**
# What does this implement/fix? 

This PR is to change enum value for PRESET_HOME to 0, as discussed here: https://github.com/esphome/aioesphomeapi/pull/24#discussion_r654335174

Related PR:
https://github.com/esphome/aioesphomeapi/pull/24

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by Lumpusz** [comment]
Not sure what to do with the clang error, seems to be unrelated to my changes. Any advice? @jesserockz @OttoWinter

**Comment by jesserockz** [comment]
Its related because you regenerated the file, but I need to update the regenerate script to add another `const`

**Comment by jesserockz** [comment]
After #1945 is merged, merge dev and regenerate the protobuf file, (or just add the `const` :wink: )

**Comment by Lumpusz** [comment]
> After #1945 is merged, merge dev and regenerate the protobuf file, (or just add the `const` 😉 )

Thanks, it is done.

**Pull request closed without merging**
