### PR TITLE
Dsmr updates

### LINKED ISSUE #2327: DSMR - Gas consumed empty
### The problem

DSMR internal component.
Sensor Gas consumed is not reporting any values.
The Marcel Zuidwijk's solution with ESP-Link _does_ report Gas consumed.
Issue is also reported here:  https://github.com/zuidwijk/dsmr/issues/7
My Gasmeter and or Energy meter is replaced.

### Which version of ESPHome has the issue?

ESP 2021.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.7

### What platform are you using?

ESP8266

### Board

Wemos D1 mini - SlimmeLezer by M. Zuidwijk

### Component causing the issue

DSMR

### Example YAML snippet

```yaml
gas_delivered:
      name: "Gas Consumed"
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### LINKED ISSUE #2333: DSMR - 'MyData' has not been declared
### The problem

Trying out the DSMR component, just going off on the documentation on https://esphome.io/components/sensor/dsmr.html I added an UART and dsmr block with the most basic config:
```
uart:
  - tx_pin: GPIO12
    rx_pin: GPIO13
    baud_rate: 115200
    id: uart_dsmr
    parity: NONE
    data_bits: 8
    stop_bits: 1
    invert: false

dsmr:
  uart_id: uart_dsmr

sensor:
  - platform: dsmr

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
```

Using the esphome:latest docker image it gives:
```
Compiling .pioenvs/meterkast/src/esphome/components/logger/logger.cpp.o
In file included from src/esphome/components/dsmr/dsmr.cpp:1:0:
src/esphome/components/dsmr/dsmr.h:47:95: error: template argument 3 is invalid
                                       DSMR_BOTH DSMR_SENSOR_LIST(DSMR_DATA_SENSOR, DSMR_COMMA)>;
                                                                                               ^
src/esphome/components/dsmr/dsmr.h:57:24: error: 'MyData' has not been declared
   void publish_sensors(MyData &data) {
                        ^
src/esphome/components/dsmr/dsmr.h: In member function 'void esphome::dsmr::Dsmr::publish_sensors(int&)':
src/esphome/core/defines.h:3:41: error: request for member 'identification_present' in 'data', which is of non-class type 'int'
 #define DSMR_TEXT_SENSOR_LIST(F, sep) F(identification) sep F(p1_version)
                                         ^
src/esphome/components/dsmr/dsmr.h:64:12: note: in definition of macro 'DSMR_PUBLISH_TEXT_SENSOR'
   if (data.s##_present && this->s_##s##_ != nullptr) \
            ^
src/esphome/components/dsmr/dsmr.h:66:5: note: in expansion of macro 'DSMR_TEXT_SENSOR_LIST'
     DSMR_TEXT_SENSOR_LIST(DSMR_PUBLISH_TEXT_SENSOR, )
     ^
src/esphome/core/defines.h:3:41: error: request for member 'identification' in 'data', which is of non-class type 'int'
 #define DSMR_TEXT_SENSOR_LIST(F, sep) F(identification) sep F(p1_version)
                                         ^
src/esphome/components/dsmr/dsmr.h:65:34: note: in definition of macro 'DSMR_PUBLISH_TEXT_SENSOR'
     s_##s##_->publish_state(data.s.c_str());
                                  ^
src/esphome/components/dsmr/dsmr.h:66:5: note: in expansion of macro 'DSMR_TEXT_SENSOR_LIST'
     DSMR_TEXT_SENSOR_LIST(DSMR_PUBLISH_TEXT_SENSOR, )
     ^
src/esphome/core/defines.h:3:63: error: request for member 'p1_version_present' in 'data', which is of non-class type 'int'
 #define DSMR_TEXT_SENSOR_LIST(F, sep) F(identification) sep F(p1_version)
                                                               ^
src/esphome/components/dsmr/dsmr.h:64:12: note: in definition of macro 'DSMR_PUBLISH_TEXT_SENSOR'
   if (data.s##_present && this->s_##s##_ != nullptr) \
            ^
src/esphome/components/dsmr/dsmr.h:66:5: note: in expansion of macro 'DSMR_TEXT_SENSOR_LIST'
     DSMR_TEXT_SENSOR_LIST(DSMR_PUBLISH_TEXT_SENSOR, )
     ^
src/esphome/core/defines.h:3:63: error: request for member 'p1_version' in 'data', which is of non-class type 'int'
 #define DSMR_TEXT_SENSOR_LIST(F, sep) F(identification) sep F(p1_version)
                                                               ^
src/esphome/components/dsmr/dsmr.h:65:34: note: in definition of macro 'DSMR_PUBLISH_TEXT_SENSOR'
     s_##s##_->publish_state(data.s.c_str());
                                  ^
src/esphome/components/dsmr/dsmr.h:66:5: note: in expansion of macro 'DSMR_TEXT_SENSOR_LIST'
     DSMR_TEXT_SENSOR_LIST(DSMR_PUBLISH_TEXT_SENSOR, )
     ^
src/esphome/components/dsmr/dsmr.cpp: In member function 'bool esphome::dsmr::Dsmr::parse_telegram()':
src/esphome/components/dsmr/dsmr.cpp:130:3: error: 'MyData' was not declared in this scope
   MyData data;
   ^
src/esphome/components/dsmr/dsmr.cpp:133:32: error: 'data' was not declared in this scope
       ::dsmr::P1Parser::parse(&data, telegram_, telegram_len_,

```

### Which version of ESPHome has the issue?

docker esphome:latest [ed8a35db2ac8]

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

n.a.

### What platform are you using?

ESP32

### Board

esp32dev

### Component causing the issue

dsmr

### Example YAML snippet

```yaml
uart:
  - tx_pin: GPIO12
    rx_pin: GPIO13
    baud_rate: 115200
    id: uart_dsmr
    parity: NONE
    data_bits: 8
    stop_bits: 1
    invert: false

dsmr:
  uart_id: uart_dsmr

sensor:
  - platform: dsmr

text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
```

### Anything in the logs that might be useful for us?

```txt
Compiling .pioenvs/meterkast/src/esphome/components/logger/logger.cpp.o
In file included from src/esphome/components/dsmr/dsmr.cpp:1:0:
src/esphome/components/dsmr/dsmr.h:47:95: error: template argument 3 is invalid
                                       DSMR_BOTH DSMR_SENSOR_LIST(DSMR_DATA_SENSOR, DSMR_COMMA)>;
                                                                                               ^
src/esphome/components/dsmr/dsmr.h:57:24: error: 'MyData' has not been declared
   void publish_sensors(MyData &data) {
                        ^
src/esphome/components/dsmr/dsmr.h: In member function 'void esphome::dsmr::Dsmr::publish_sensors(int&)':
src/esphome/core/defines.h:3:41: error: request for member 'identification_present' in 'data', which is of non-class type 'int'
 #define DSMR_TEXT_SENSOR_LIST(F, sep) F(identification) sep F(p1_version)
                                         ^
src/esphome/components/dsmr/dsmr.h:64:12: note: in definition of macro 'DSMR_PUBLISH_TEXT_SENSOR'
   if (data.s##_present && this->s_##s##_ != nullptr) \
            ^
src/esphome/components/dsmr/dsmr.h:66:5: note: in expansion of macro 'DSMR_TEXT_SENSOR_LIST'
     DSMR_TEXT_SENSOR_LIST(DSMR_PUBLISH_TEXT_SENSOR, )
     ^
src/esphome/core/defines.h:3:41: error: request for member 'identification' in 'data', which is of non-class type 'int'
 #define DSMR_TEXT_SENSOR_LIST(F, sep) F(identification) sep F(p1_version)
                                         ^
src/esphome/components/dsmr/dsmr.h:65:34: note: in definition of macro 'DSMR_PUBLISH_TEXT_SENSOR'
     s_##s##_->publish_state(data.s.c_str());
                                  ^
src/esphome/components/dsmr/dsmr.h:66:5: note: in expansion of macro 'DSMR_TEXT_SENSOR_LIST'
     DSMR_TEXT_SENSOR_LIST(DSMR_PUBLISH_TEXT_SENSOR, )
     ^
src/esphome/core/defines.h:3:63: error: request for member 'p1_version_present' in 'data', which is of non-class type 'int'
 #define DSMR_TEXT_SENSOR_LIST(F, sep) F(identification) sep F(p1_version)
                                                               ^
src/esphome/components/dsmr/dsmr.h:64:12: note: in definition of macro 'DSMR_PUBLISH_TEXT_SENSOR'
   if (data.s##_present && this->s_##s##_ != nullptr) \
            ^
src/esphome/components/dsmr/dsmr.h:66:5: note: in expansion of macro 'DSMR_TEXT_SENSOR_LIST'
     DSMR_TEXT_SENSOR_LIST(DSMR_PUBLISH_TEXT_SENSOR, )
     ^
src/esphome/core/defines.h:3:63: error: request for member 'p1_version' in 'data', which is of non-class type 'int'
 #define DSMR_TEXT_SENSOR_LIST(F, sep) F(identification) sep F(p1_version)
                                                               ^
src/esphome/components/dsmr/dsmr.h:65:34: note: in definition of macro 'DSMR_PUBLISH_TEXT_SENSOR'
     s_##s##_->publish_state(data.s.c_str());
                                  ^
src/esphome/components/dsmr/dsmr.h:66:5: note: in expansion of macro 'DSMR_TEXT_SENSOR_LIST'
     DSMR_TEXT_SENSOR_LIST(DSMR_PUBLISH_TEXT_SENSOR, )
     ^
src/esphome/components/dsmr/dsmr.cpp: In member function 'bool esphome::dsmr::Dsmr::parse_telegram()':
src/esphome/components/dsmr/dsmr.cpp:130:3: error: 'MyData' was not declared in this scope
   MyData data;
   ^
src/esphome/components/dsmr/dsmr.cpp:133:32: error: 'data' was not declared in this scope
       ::dsmr::P1Parser::parse(&data, telegram_, telegram_len_,
```

### Additional information

I'm guessing it might be a documentation issue where everything claims to be optional, but really isn't.

### LINKED ISSUE #2340: DSMR Belgian Sagemcom T211 invalid string length error
### The problem

Bought a "Slimmelezer", opened the ports on the digital meter, plugged in and did a network setup.
Home Assistant discovers the device but the slimmelezer spits out the following error:

`           ^
Invalid string length
[E][dsmr:138]: 0-0:96.1.4(50215)
`

### Which version of ESPHome has the issue?

Firmware: 2021.8.0 (Aug 19 2021, 16:39:05)

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.8

### What platform are you using?

ESP8266

### Board

Wemos D1 mini - SlimmeLezer by M. Zuidwijk

### Component causing the issue

DSMR

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### LINKED ISSUE #2363: DSMR component givens "No checksum found" with DSMR2
### The problem

I tried to use the DSMR component to read my DSMR2 meter. This works fine with my custom DSMR component, but now there's a built-in component I'd like to use this.

I have a DSMR2, configured the UART component on Serial2 (pin 16/17), baudrate 9600, 7 data bits, no parity and 1 stopbit. 

The data now comes flowing in, but the component complains about not finding the checksum after the '!'. That is correct: DSMR2 does not have a checksum.

### Which version of ESPHome has the issue?

2021.8.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

Not relevant (2021.7.4)

### What platform are you using?

ESP32

### Board

ESP32 devkit

### Component causing the issue

dsmr

### Example YAML snippet

```yaml
uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 9600
  data_bits: 7
  parity: NONE
  stop_bits: 1
  
dsmr:

  - platform: dsmr
    energy_delivered_tariff1:
      name: "Consumption Low Tariff Sensor"
    energy_delivered_tariff2:
      name: "Consumption High Tariff Sensor"
(etc.)
```

### Anything in the logs that might be useful for us?

```txt
No checksum found
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by glmnet**
# What does this implement/fix? 

1. It is accepted a newline before a value starting with `(` this is needed for some dsmr, see also: https://github.com/matthijskooijman/arduino-dsmr/issues/22
2. Allows disabling crc check by a new `crc_check:` bool option, this in conjunction with properly configuring uart port makes the dsmr v2.2 version supported
3. Adds a new `gas_delivered_text` text sensor which will return this entry as a raw value. This needs more investigation hence setting this PR as draft.
4. Fixes https://github.com/esphome/issues/issues/2340 (updated dsmr arduino version to 0.5)
5. Fixes https://github.com/esphome/issues/issues/2333
6. Fixes https://github.com/esphome/issues/issues/2327 by adding new  `gas_mbus_id` option to `dsmr`, see example below

See example config for testing

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/zuidwijk/dsmr/issues/12, fixes https://github.com/esphome/issues/issues/2363

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1475

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml for a DSMR v2 / v3

external_components:
  source: github://glmnet/esphome@dsmr-updates
  components: dsmr

# Custom uart settings might be required (v5 works at 115200 baud rate)
uart:
  baud_rate: 9600
  data_bits: 7
  parity: NONE
  stop_bits: 1

dsmr:
  crc_check: false

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: dsmr_energy_delivered_tariff1
    energy_delivered_lux:
      name: dsmr_energy_delivered_tarifflux

text_sensor:
  - platform: dsmr
    identification:
      name: "dsmr_identification"
    p1_version:
      name: "dsmr_p1_version"
    gas_delivered_text:
      name: "gas delivered raw"


# Set custom gas_mbus_id


dsmr:
  gas_mbus_id: 2
...
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by michielappelman** [comment]
For anyone coming here to get their SlimmeLezer working with DSMR versions 2.2 or 3.0 before this PR is merged, please see the fork at [michielappelman/dsmr](https://github.com/michielappelman/dsmr).

**Comment by glmnet** [comment]
> For anyone coming here to get their SlimmeLezer working with DSMR versions 2.2 or 3.0 before this PR is merged, please see the fork at [michielappelman/dsmr](https://github.com/michielappelman/dsmr).

Hi @michielappelman thanks for finding a solution. However this should already be a easier fix for people with DSMR v2, you just need to use the example yaml and it should work with v2 (I'm about to edit so it uses uart with dsmr v2 settings)

Did you try this already? Is it giving problems to you?

**Comment by michielappelman** [comment]
I had not tried the workaround that you just added to the PR description. Honestly, I wasn't aware that using the GitHub tag for the external component was an option (apologies, still a bit new to the ESPHome ecosystem), but your example YAML makes it much more clear. Unfortunately I am not at home the coming to weeks so will not be able to test it. Will test it as soon as I get back to hopefully get this merged.

**Comment by peterforeman** [comment]
With DSMR2 the "power_delivered" sensor (and maybe the power_returned" sensor as well) should be multiplied by 1000 or reported in kW. Also the "gas_delivered" sensor is empty as well as the "DSMR version" sensor is empty.

Otherwise this seems to work for me.

I do miss the current tariff sensor (high or low) in the DSMR component.

**Comment by bakboord4** [comment]
@glmnet. Added the external-component and DSMR bus_id part. But no gas_delivered no_values were visible in the webserver of the slimmelezer.
Did I make the correct additions for DSMR5?

**Review by OttoWinter — COMMENTED** [review]
LGTM when docs added

**Comment by glmnet** [comment]
> With DSMR2 the "power_delivered" sensor (and maybe the power_returned" sensor as well) should be multiplied by 1000 or reported in kW. Also the "gas_delivered" sensor is empty as well as the "DSMR version" sensor is empty.

this is fixed in another PR earlier today

**Comment by mmakaay** [comment]
These changes LGTM too.
Tested out the code and I see no issues on my device (for DSMR 4.2).

**Comment by michielappelman** [comment]
Better late than never, but I have just flashed the dev branch to my SlimmeLezer (connected to a DSMR version 2.2+ smart meter) as well and see everything working as expected.

**Pull request merged**
