### PR TITLE
RGBW emulate RGBWW (color temp)

### LINKED ISSUE #1131: Create a virtual/soft cct feature to simulate RGBWW/RGB-CCT with just RGBW
**Describe the problem you have/What new integration you would like**
Basically this feature of Tasmota: https://tasmota.github.io/docs/Lights/#virtual-ct. I just got some Teckin SB60 bulbs, and I set them up with Tasmota first, then moved to ESPHome. While I was using Tasmota, I enabled the Soft-CCT feature as per here: https://templates.blakadder.com/teckin_SB60.html#soft-cct-setup. It worked quite well, all things considered. It sounds like tuya was doing it as well. Either way, it'd be awesome if ESPHome could do something similar.

**Please describe your use case for this integration and alternatives you've tried:**
I'd like to simulate having both a warm white and cool white LED, even though I only have one. The other RGB LEDs should be able to help.

### PR DESCRIPTION
**Pull request by WeekendWarrior1**
# What does this implement/fix? 

New feature to mix in some `RED` or `BLUE` with `WHITE` to emulate a RGBWW light.
Similar ideas found in: https://esphome.io/guides/diy.html?#custom-components-code :

- https://gist.github.com/madjam002/31cc88640efa370630fed6914fa4eb7f
- https://gist.github.com/triphoppingman/76153ddf58072b10e229e9147b2bdf72

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1131

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
output:
  - platform: esp8266_pwm
    id: output_component1
    pin: D1
  - platform: esp8266_pwm
    id: output_component2
    pin: D2
  - platform: esp8266_pwm
    id: output_component3
    pin: D3
  - platform: esp8266_pwm
    id: output_component4
    pin: D4

light:
  - platform: rgbw
    name: "test_led_strip_8266"
    id: test_led_strip_8266
    gamma_correct: 0
    red: output_component1
    green: output_component2
    blue: output_component3
    white: output_component4
    default_transition_length: 0s
    color_interlock: true
    emulate_rgbww:
      blue: 20% #mix in 20% blue light to white to emulate cold_white
      red: 40%  #mix in 40% red light to white to emulate warm_white
      cold_white_color_temperature: 6536 K
      warm_white_color_temperature: 2000 K
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by oxan** [comment]
I've been thinking about something like this as well, so I like the idea, but I'm not totally convinced about this approach yet. Doing this in the rgbw platform means that e.g. Tuya lights or LED strips don't get this functionality. 

I think it makes more sense to do this in the light platform by converting a LightCall for the RGBW color mode that has a color temperature to RGB values (the same way we convert a call for RGBWW with a color temperature to CW+WW). That might be a bit more involved patch though. 

Also, the calculation doesn't seem right to me. By using a fixed brightness for the white channel and mixing in red/blue as necessary, the output brightness will actually change when the color temperature changes. That's usually not what users expect. I also don't understand why red/blue aren't gamma corrected.

**Comment by WeekendWarrior1** [comment]
> I've been thinking about something like this as well, so I like the idea, but I'm not totally convinced about this approach yet. Doing this in the rgbw platform means that e.g. Tuya lights or LED strips don't get this functionality.

> I think it makes more sense to do this in the light platform by converting a LightCall for the RGBW color mode that has a color temperature to RGB values (the same way we convert a call for RGBWW with a color temperature to CW+WW). That might be a bit more involved patch though.

I agree, as this is something I would also want to use for my RGBW addressable LED strips.
It does complicate passing the variables around slightly. I think it would also mean extra validation steps on most of the light components are required to validate which lights support the feature and which don't?

> Also, the calculation doesn't seem right to me. By using a fixed brightness for the white channel and mixing in red/blue as necessary, the output brightness will actually change when the color temperature changes. That's usually not what users expect.

This may be hard to juggle. 
Often on RGBW lights, the W channel puts out significantly more light than the other colour channels.
I personally struggle to perceive extra brightness in a room that is lit by 100% White and 30% Red on my sk6812s, but the colour difference is noticeable.

> I also don't understand why red/blue aren't gamma corrected.

They probably can be. I was concerned that people that set eg. 20% blue light to be mixed in, would be frustrated when a barely perceptible change occurs because of the gamma correction on the Blue channel brightness. At the same time, users can always disable it or increase the percentage they mix in.

**Comment by WeekendWarrior1** [comment]
>> Also, the calculation doesn't seem right to me. By using a fixed brightness for the white channel and mixing in red/blue as necessary, the output brightness will actually change when the color temperature changes. That's usually not what users expect.

> This may be hard to juggle.
> Often on RGBW lights, the W channel puts out significantly more light than the other colour channels.
> I personally struggle to perceive extra brightness in a room that is lit by 100% White and 30% Red on my sk6812s, but the colour difference is noticeable.

Might make this an optional bool, something like: `additive_brightness` (default: `false`)

**Comment by WeekendWarrior1** [comment]
By default this implementation tries to keep a constant brightness as a user changes colour temperature now, but a user can opt to keep the white output set to brightness and add red or blue brightness on top by setting `additive_brightness`:
```yaml
    emulate_rgbww:
      blue: 20% #mix in 20% blue light to white to emulate cold_white
      red: 40%  #mix in 40% red light to white to emulate warm_white
      cold_white_color_temperature: 6536 K
      warm_white_color_temperature: 2000 K
      additive_brightness: true
```
Have also fixed up the gamma correct.

@oxan 

> Doing this in the rgbw platform means that e.g. Tuya lights or LED strips don't get this functionality.

> I think it makes more sense to do this in the light platform by converting a LightCall for the RGBW color mode that has a color temperature to RGB values (the same way we convert a call for RGBWW with a color temperature to CW+WW). That might be a bit more involved patch though.

Can you elaborate on this?
How would a user be able to define how much red or blue to mix in for their specific RGBW light?

I was thinking of maybe an emulated_rgbw class that components which support RGBW can inherit, which stores the emulated RGBW values and the setter functions.

**Comment by swifty99** [comment]
I will try your solution, however it is a bit more complicated.

Actually at my home all lights work kind of this way. In the days before esphome I created a light with RGBW to do exactly that. Mixing the channels to create a very wide color temperature spectrum.
White source should be used as much as possible as the color rendering index, which indicates how well perfect light is recrated, is good or very good on white LEDs and really awfully poor on a RGB mix.
What I did, and still think there is no way around it, is to calibrate the light in "stages". For me there were five stages with an interpolation in between. The middle stage is where just white is on an CT is known. 
Going higher CT I use full white with full blue. This CT needs to be measured. These days apps are availble which might be good enough to sense CT. Using a RGB sensor did not work at all, emitted and measured wavelength did not fit. I use a dedicated lumu power sensor for my iphone. Not ony CT needs to be adjusted, some green needs to be added too. Using a xy color space sensor can fix it, I did a"manually" calibration using my eye.
Next stage to blue depends how much you want to go on the CT spectrum. In the end it is almost only blue. At that stage brightness decreases a lot. Again CT is measured an referenced.
Theses two stages are repeated to the red side of light.
In the end the user should be able to decide what is more important: brightness or desired CT.

I am moving my lights to esphome, as my "operating system" and mqqt implementation is too much effort to keep alive. Now I am struggling to recreate the same with esphome. My first try would be to let home assistant do the calculations. An integrated algorithm in esphome would be better.

**Comment by WeekendWarrior1** [comment]
If it's not clear from the PR, this presents itself as:
image
in HASS, where center of the slider is just white, and the max cool would be white + 20% blue (if that is the percentage you choose to be mixed in).

I appreciate your insight into all of the steps one can take to perfect the colour temperature of their RGBW lights, seems like a lot of work!
But that also makes realise that this PR might be a nice middle ground because it's exposing only three simple options that should be quite clear to any end user, without doing their head in.

I do see room for optional arguments for mixing in green to either side using some maths for example, if you want to add that to this PR, but I also will warn you that based on oxan's feedback, this is unlikely to be merged.

**Comment by swifty99** [comment]
I agree,
this is the middle way. I am really interested to have a proper white CT from RGBW and move what I already did in some way to esphome. Maybe together we can find a better solution and move the discussion somwhere else. @oxan: assuming there is a chance that this will be integrated into esphome one day.

**Comment by fabianschaefer** [comment]
I tried to test this PR using this code in my esphome config file:
```yaml
external_components:
  - source: github://pr#2402
    components: [ light, rgbw ]
```

But I get the following error when trying to compile:
```
ERROR Unable to load component light:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/esphome/loader.py", line 162, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/esphome/.esphome/external_components/4b9cf4e6/esphome/components/light/__init__.py", line 25, in <module>
    from .automation import light_control_to_code  # noqa
  File "/config/esphome/.esphome/external_components/4b9cf4e6/esphome/components/light/automation.py", line 23, in <module>
    from .types import (
  File "/config/esphome/.esphome/external_components/4b9cf4e6/esphome/components/light/types.py", line 6, in <module>
    LightState = light_ns.class_("LightState", cg.Nameable, cg.Component)
AttributeError: module 'esphome.codegen' has no attribute 'Nameable'
Failed config
```

Am I missing something or has there been an update in ESPHome that is not compatible with this PR?

Edit: Looks like the refactor in PR https://github.com/esphome/esphome/pull/2418 is causing this error. Anyway, it would be cool if this could be merged into the dev branch. Anything I can do to support you?

**Comment by jesserockz** [comment]
@fabianschaefer Try again now as I merged `dev` in with the changes

**Comment by fabianschaefer** [comment]
Thanks, it's compiling now. However in HASS it still shows up as RGBW Lamp, even after re-adding the integration. Am I missing something?

**Review by jesserockz — COMMENTED** [review]
The rgbw code is small enough that making a new platform `emulated_rgbww` (or something else?) might be easier to configure and maintain?

**Comment by jesserockz** [comment]
> Thanks, it's compiling now. However in HASS it still shows up as RGBW Lamp, even after re-adding the integration. Am I missing something?

@fabianschaefer I have not used this so I have not tested it myself sorry.

**Comment by swifty99** [comment]
Creating a solution for my needs in esphome looks not so easy. Finally I solved the problem using home assistant. I created a blueprint for everyone to use. Give it a try?
https://community.home-assistant.io/t/use-a-rgbw-light-as-a-light-with-color-temperature-control/379484

**Pull request closed without merging**
