### PR TITLE
[sml] Fixed crashing sml parser

### LINKED ISSUE #4213: Bug in SML-Parser
### The problem

Having an long List in the SML-Message with extended length the last list item is not processed. 

### Which version of ESPHome has the issue?

current dev branch

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

_No response_

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

In ` sml_parser.cpp` lines 28 and following:

```
if (has_extended_length) {
    length = (length << 4) + (this->buffer_[this->pos_ + 1] & 0x0f);
    parse_length = length - 1;
    this->pos_ += 1;
  }
```

The length is decremented here which is correct for value type data as the TL-Field is here included in the length but incorrect in case of a complex type like a list. According to SML binary encoding specifications the TL-Field directly encodes the number of items in the list.

### LINKED ISSUE #5588: SML Component converts hex value incorrectly to decimal by offset of 256
### The problem

Hi,

I have a esp with an sml component and the OBIS Code Values in hex format are incorrectly converted to decimal numbers with an offset off 256.

Output of the log of esphome:

```
[17:23:12][D][sensor:094]: 'Sensor 1.8.0': Sending state 64736.00000 kWh with 2 decimals of accuracy
[17:23:12][D][sensor:094]: 'Sensor 2.8.0': Sending state 6116.00000 kWh with 2 decimals of accuracy
[17:23:12][D][sml:078]: OBIS info:
(...)
[17:23:12][D][sml:084]:   (<server id>) 1-0:1.8.0 [0x000000fde0]
[17:23:12][D][sml:084]:   (<server id>) 1-0:2.8.0 [0x00000018e4]
(...)
```
#### The main error: number seems to be converted wrong::
The OBIS Info show a hex number of `fde0` which, if entered in a calculator, results in `64992`, which is not `64736`, which is returned by esphome. `64992 - 64736 = 256` - which is very interesting.

The HEX Number is the correct number which the smart meter also displays, so it doesn't seem to be a reading issue with the sensor.

Another note is the strange behavior: the result in home assistant (so the sensor value of esphome) is for 3/4 days correct, then the value has an offset of `-256` for 3/4 days, then after another 3/4 days the value is correct again. After 3/4 days the value gets an offset of `+256` which is also for 3/4 days, after which its correct again. This cycle repeats itself.

A reboot / reflash doesn't fix anything.

I have no idea that the hell is going on, this issue started since the beginning. Has anyone experienced something similar already? If I forgot to provide something, just tell me

Maybe similar to this:
https://github.com/esphome/issues/issues/4858

### Which version of ESPHome has the issue?

ESPHome version 202x.x.x

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.2.x (every version)

### What platform are you using?

ESP32

### Board

ESP32-WROOM-32 with hichi ttl sensor

### Component causing the issue

sml

### Example YAML snippet

```yaml
esphome:
  name: sml
  friendly_name: sml

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

### wifi + ota + encryption + captive portal here ###

uart:
  id: uart_bus
  rx_pin: GPIO4
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_buffer_size: 2048

sml:
  id: hpz
  uart_id: uart_bus


sensor:
  - platform: sml
    name: "Sensor 1.8.0"
    sml_id: hpz
    server_id: "(<sever id>)"
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 2
    device_class: energy
    state_class: total_increasing
```

### Anything in the logs that might be useful for us?

```txt
[17:23:12][D][sensor:094]: 'Sensor 1.8.0': Sending state 64736.00000 kWh with 2 decimals of accuracy
[17:23:12][D][sensor:094]: 'Sensor 2.8.0': Sending state 6116.00000 kWh with 2 decimals of accuracy
[17:23:12][D][sml:078]: OBIS info:
(...)
[17:23:12][D][sml:084]:   (xxxx) 1-0:1.8.0 [0x000000fde0]
[17:23:12][D][sml:084]:   (xxxx) 1-0:2.8.0 [0x00000018e4]
(...)
```

### Additional information

_No response_

### LINKED ISSUE #6071: SML Crashing ESP8266 after 2024.7.1
### The problem

After 2024.7.1, my ESP8266 used for monitoring my Smartmeter is constantly rebooting, and it is caused by the SML component because if I disconnect the SML reader, the ESP stops rebooting. Unfortunately, I can't log some errors because the ESP is constantly rebooting. 
Probably related to this change: https://github.com/esphome/esphome/pull/6148 

### Which version of ESPHome has the issue?

2024.7.1 - 2024.7.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

_No response_

### What platform are you using?

ESP8266

### Board

d1_mini

### Component causing the issue

SML

### Example YAML snippet

```yaml
uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600

sml:
  id: mysml
  uart_id: uart_bus

sensor:
  - platform: sml
    name: "Zahlerstand"
    sml_id: mysml
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0000001

  - platform: sml
    name: "Zahlerstand HT"
    sml_id: mysml
    obis_code: "1-0:1.8.1"
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0000001

  - platform: sml
    name: "Zahlerstand NT"
    sml_id: mysml
    obis_code: "1-0:1.8.2"
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0000001

  - platform: sml
    name: "Leistung"
    sml_id: mysml
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
    filters:
      - multiply: 0.01

  - platform: sml
    name: "Leistung L1"
    sml_id: mysml
    obis_code: "1-0:36.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
    filters:
      - multiply: 0.01

  - platform: sml
    name: "Leistung L2"
    sml_id: mysml
    obis_code: "1-0:56.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
    filters:
      - multiply: 0.01

  - platform: sml
    name: "Leistung L3"
    sml_id: mysml
    obis_code: "1-0:76.7.0"
    unit_of_measurement: W
    accuracy_decimals: 0
    device_class: power
    state_class: measurement
    filters:
      - multiply: 0.01
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

2024.7.0 was working fine.

### LINKED ISSUE #6091: SML esphome devie after update to 2024.7.2 don't work. device over network not reachable
### The problem

after update from 2024.6.6 to 7.2 esphome device (ESP32) not reachable over network, ip is configured.

I have done some tests and I have noticed that when I do not have the IR read head on the counter, the esphome runs, as soon as I put the read head on the counter, everything seems to hang up.

Restore to 6.6 and everything runs fine again.

I have the same problem on other devices, one that uses BT, one that queries data from the Seplos BMS via Modbus, only the Modbus queries that query the Deye WR work. 

What other data do you need to investigate this in more detail?

Translated with DeepL.com (free version)

### Which version of ESPHome has the issue?

2024.7.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.7.3 and 2024.7.2 

### What platform are you using?

ESP32

### Board

_No response_

### Component causing the issue

SML and BT and modbus

### Example YAML snippet

```yaml
esphome:
  name: "esp32-stromzaehler"
  friendly_name: esp32-stromzaehler

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "xXx"

ota:
  platform: esphome
  password: !secret HA_OTA_Password


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-9E17C4"
    password: "xXx"

captive_portal:

web_server:
  port: 80

time:
   - platform: sntp
     id: sntp_time
     timezone: Europe/Berlin
     servers:
     - 192.168.123.1

uart:
  id: uart_1
  rx_pin: GPIO9
  tx_pin: GPIO10
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

sml:
  id: haus
  uart_id: uart_1

binary_sensor:
  - platform: status
    name: "{name} status"

sensor:
  - platform: sml
    name: "Haus Total energy"
    id: Haus_Total_energy
    sml_id: haus
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 6
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0000001
  - platform: sml
    name: "Haus Total power"
    id: Haus_Total_power
    sml_id: haus
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    accuracy_decimals: 2
    device_class: power
    state_class: measurement
    filters:
      - multiply: 0.01
  - platform: sml
    name: "Haus L1 power"
    id: Haus_L1_power
    sml_id: haus
    obis_code: "1-0:36.7.0"
    unit_of_measurement: W
    accuracy_decimals: 2
    device_class: power
    state_class: measurement
    filters:
      - multiply: 0.01 
  - platform: sml
    name: "Haus L2 power"
    id: Haus_L2_power
    sml_id: haus
    obis_code: "1-0:56.7.0"
    unit_of_measurement: W
    accuracy_decimals: 2
    device_class: power
    state_class: measurement
    filters:
      - multiply: 0.01 
  - platform: sml
    name: "Haus L3 power"
    id: Haus_L3_power
    sml_id: haus
    obis_code: "1-0:76.7.0"
    unit_of_measurement: W
    accuracy_decimals: 2
    device_class: power
    state_class: measurement
    filters:
      - multiply: 0.01 
  - platform: sml
    name: "Haus L1 voltage"
    id: Haus_L1_voltage
    sml_id: haus
    obis_code: "1-0:32.7.0"
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement
    filters:
      - multiply: 0.1
  - platform: sml
    name: "Haus L2 voltage"
    id: Haus_L2_voltage
    sml_id: haus
    obis_code: "1-0:52.7.0"
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement
    filters:
      - multiply: 0.1
  - platform: sml
    name: "Haus L3 voltage"
    id: Haus_L3_voltage
    sml_id: haus
    obis_code: "1-0:72.7.0"
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: voltage
    state_class: measurement
    filters:
      - multiply: 0.1
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eNBeWe**
# What does this implement/fix?

The handling of the TL (type/length) field caused the parser to die with certain edge-cases.
Basically the problem is that value fields count the TL bytes, while lists do not count these.

Additionally there was a slight bug in the sign extension that could cause some wrong values being read.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**

This (hopefully)
fixes esphome/issues#6091
fixes esphome/issues#6071
fixes esphome/issues#4213
fixes esphome/issues#5588

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** (not applicable)

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]

**Comment by passionsfrucht** [comment]
Hey, I cherry-picked this patch on top of `2024.7.3` and the crashes are back with vengeance.
The errors eventually introduced by (https://github.com/esphome/esphome/pull/6148) resulting in the crashes described in https://github.com/esphome/issues/issues/6091 were probably observed by me too, but the frequency of errors went definitely down.

With this patch, SML is basically unusable for me again. The ESP crashes now around every two minutes.

If you need dumps of my raw data stream or if I can help otherwise, please let me know.

Thanks a lot BTW for looking into those things, I planned to do something similar but never found the time!

**Comment by passionsfrucht** [comment]
> Hey, I cherry-picked this patch on top of `2024.7.3` and the crashes are back with vengeance. 

I meant the original crashes before https://github.com/esphome/esphome/pull/6148 was applied.

Not sure how helpful this is, but at least with my smart meter I had to disable the ID transmission as it had crashed instantly otherwise. My assumption back then was some string encoding issues, but I never did investigate further.

The disabled entity with my (probably not correct) comment from then:

```yaml

  # # Disabled this, retults in invalid utf-8, like this: "b'\\n\\x01LOG\\[redacted]"
  # - platform: sml
  #   name: "smart meter ID"
  #   sml_id: mysml
  #   obis_code: "1-0:96.1.0"
  #   format: text
  #   entity_category: "diagnostic"
  ```
Probably even homeassistant did crash back then, not sure anymore, but it was quite dramatic IIRC.

**Comment by passionsfrucht** [comment]
Sorry for the spam, I just noticed that the "invalid utf-8" contained my "Zählernummer". Still a weird string, probably buggy generated from the meter itself, or a configuration error with drastic results? Not sure anymore.

**Comment by eNBeWe** [comment]
@passionsfrucht I guess I can't really do anything without more raw data.
Could you open a new issue and provide some dumps there? I might find time to look into that.

**Pull request merged**
