### PR TITLE
Add support for additional colors on GROW R503

### PR DESCRIPTION
**Pull request by Zebble**
# What does this implement/fix? 

Adds GREEN, YELLOW, CYAN and WHITE to available colors on GROW component.

Docs: https://github.com/esphome/esphome-docs/pull/1850

### CODE REVIEW

**Comment by loongyh** [comment]
Hey thanks for the PR! Which model(s) is this applicable for?

**Comment by Zebble** [comment]
Looks like just the R503 and R503-5V.

**Comment by loongyh** [comment]
I have the R503 and for this model there's only red, blue and purple aura led colors. Hmm interesting, can u post the link to the datasheet/product page for yours?

**Comment by Zebble** [comment]
Interesting...  This is where I got mine but haven't fully tested it yet.  I'll do that today.  Looks like this might be a new "RGB" variant of the R503.

https://a.aliexpress.com/_mOHIZS4

They provide a link to the specs and the R503 shows the additional aura colours.

https://www.dropbox.com/sh/epucei8lmoz7xpp/AAAmon04b1DiSOeh1q4nAhzAa?dl=0

**Comment by OnFreund** [comment]
Looks like it's a new version of the module, and it also has new API calls that take care of the boilerplate in enrollment and identification. Really cool (and backwards compatible)

**Comment by loongyh** [comment]
Nice to learn about this, but with RGB the full color palette should've been possible? Anyway Grow should've released this under a new model or suffix it with RGB or something. This is sure gonna cause some confusion. We should also update the docs to mention the additional 4 colors are only supported for RGB versions of R503, lest we get any tickets over this.

**Comment by loongyh** [comment]
> new API calls that take care of the boilerplate in enrollment and identification.

@OnFreund Hmm do you think we should implement this? Same issue unless there's a way to identify the RGB version from the old one, it may cause issues...

**Comment by Zebble** [comment]
It's not really RGB, as only a few more colours are listed in the docs.  Full individual control of R, G and B is not available.  Definitely going to cause a lot of confusion.

**Comment by loongyh** [comment]
The LED outputs are definitely capable of (pwm?) dimming as we got modes like breathing etc. Full color palette support is just a matter of implementing the protocol in firmware, maybe grow will release a firmware update in the future to support it?

Anyway, your PR looks good to go. Let's implement this for the time being.

**Review by oxan — APPROVED** [review]

**Comment by oxan** [comment]
This needs a PR to the documentation to update the list of valid colors there as well (and preferably note that they're only supported on RGB models as @loongyh suggested).

**Comment by Zebble** [comment]
Have a PR for matching doc changes.  [https://github.com/esphome/esphome-docs/pull/1850](url)

**Comment by oxan** [comment]
Thanks!

**Pull request merged**
