### PR TITLE
BH1750 Measurement time

### LINKED ISSUE #148: Support to measure more than 54612 Lux with the BH1750
**Describe the problem you have/What new integration you would like**

The esphome integration of the BH1750 Lux Sensor only allows to measure a maximum of 54612 Lux (in my tests). There is a possability (software wise) to measure more than 100000 Lux with this sensor at the costs of Measurement Time (MTreg) which can go up to a maximum of around 500 ms in this case (which is not bad at all!).

**Please describe your use case for this integration and alternatives you've tried:**

Like to measure outside with sun :sun_with_face: which easily exceeds 54612 Lux

**Additional context**

There is a library and a little bit of context on this (German only) website:

> Virtueller Modus:
> RESOLUTION_AUTO_HIGH: Die Werte im MTreg ('Measurement Time'-Register) werden je nach Helligkeit automatisch so angepasst, dass eine maximalmögliche Auflösung und Messbereich erziehlt werden. Die messbaren Werte fangen von 0,11 lx und gehen bis über 100000 lx. (ich weis nicht, wie genau die Werte in Grenzbereichen sind, besonders bei hohen Werte habe ich da meine Zweifel. Die Werte scheinen jedoch weitgehend linear mit der steigenden Helligkeit zu wachsen.) Auflösung im Unteren Bereich ca. 0,13 lx, im mittleren 0,5 lx, im oberen etwa 1-2 lx. Die Messzeiten verlängern sich durch mehrfache Messungen und die Änderungen von Measurement Time (MTreg) bis max. ca. 500 ms.

http://s6z.de/cms/index.php/homeautomation-homecontrol/infrastruktur/aktorensensoren/offene-standard-systeme/i-c/15-umgebungslichtsensor-bh1750

### PR DESCRIPTION
**Pull request by rradar**
## Description:

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/148

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#515

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by rradar** [comment]
I don't know why thing's here are failing but I use this since month's as a custom integration and it never failed once. High quality code delivered by @OttoWinter :wink:

**Comment by glmnet** [comment]
can you add `measurement_time` to the test?

**Comment by glmnet** [comment]
@rradar  I re-run the travis and it's showing a lint issue now. Don't forget testx.yaml addition

**Comment by rradar** [comment]
@glmnet actually I have no idea how to edit the data. I'm not even a programmer. I'm lucky that I somehow managed to make a pull request from the code @OttoWinter provided.

I did - however - updated the documentation. But the pull request for it always came polluted with a lot's of other things and I have no idea where it came from (I edit the documentation with the link on the website)

**Comment by glmnet** [comment]
Ahh ok, I'll take care of all this later then.

Thanks for all your support all around!

**Pull request merged**
