### PR TITLE
dht: Fix sensor reading from DHT22

### LINKED ISSUE #239: DHT22 can't read values after software/button restart - works perfect when connecting power again
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io on Ubuntu 18.x in Docker

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMcu v3 LoLin
**Affected component:**

https://esphome.io/components/sensor/dht.html
DHT22

**Description of problem:**
When I'm connecting power wire to my NodeMcu everything works perfect. But when I will restart device with onboard button, or while uploading new firmware, it doesn't works and in logs I get:
`[20:52:22][E][sensor.dht:197]: DHT reports invalid data. Is the update interval too high or the sensor damaged?
[20:52:22][W][sensor.dht:076]: Invalid readings! Please check your wiring (pull-up resistor, pin number).`

I have step-up resistor 4k7 Ohm, I tried all available Dx pins, and I found similar issue ->
https://github.com/micropython/micropython/issues/2651
-they suggest waiting little bit with reading after boot

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
esphome:
  name: esp_home_node_01
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "ssid"
  password: "pass"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: dht
    pin: D1
    temperature:
      name: "Salon - Tempertura"
    humidity:
      name: "Salon - Wilgotnosc"
    update_interval: 30s
    
binary_sensor:
  - platform: gpio
    pin: D0
    name: "Salon - Ruch"
    device_class: motion
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

I have step-up resistor 4k7 Ohm, I tried all available Dx pins, and I found similar issue ->
https://github.com/micropython/micropython/issues/2651
-they suggest waiting little bit with reading after boot

### PR DESCRIPTION
**Pull request by robinsmidsrod**
## Description:

The [datasheet for the DHT22](https://www.sparkfun.com/datasheets/Sensors/Temperature/DHT22.pdf) specifies a delay of 18ms (page 7), but the actual code uses a delay of 0.8ms.

**Related issue (if applicable):** fixes https://github.com/esphome/issues/issues/239

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

esphome/esphome-docs#563

### CODE REVIEW

**Comment by robinsmidsrod** [comment]
@OttoWinter I think this should be possible to merge. As far as I know, there are no needed documentation tasks, and I didn't see any tests for the DHT22 sensor, so I didn't try to create any new ones. Hopefully this doesn't create any regressions.

**Review by OttoWinter — CHANGES_REQUESTED** [review]
This is not really correct.

I can tell you that all DHT22s I've tried expect a reset pulse on the data pin of 800µs. They don't work otherwise.

The problem is that the datasheet/documentation of the protocols for the DHT22/DHT11 is quite bad. Apparently there are some DHT11 derivatives that are labeled as DHT22s and vice-versa (don't know which one is really the correct one).

Please try using DHT11 as the sensor model - I believe that will work just fine for you (essentially the same). If that's true we can introduce a new sensor model for these weird DHT22/DHT11 mixes.

But we should definitely not change the behavior of the existing DHT22 setting. Otherwise we will break people's installs that use DHT22s that expect 800µs pulses.

**Comment by robinsmidsrod** [comment]
@OttoWinter Thanks for taking the time to respond during the holidays. I actually tried all of the different models that were available before I started tinkering with the source code.

This is what I get with model set to either DHT11 or DHT22 (with my patch). If I have it set to DHT22 without my patch then I get just NaN values. The actual temperature/humidity in the room is 24C/39% according to another sensor I have.

```
model=DHT11:

Got Temperature=-11.8°C Humidity=14.5%
[17:16:48][D][sensor:092]: 'Office Temperature': Sending state -11.80000 °C with 1 decimals of accuracy
[17:16:48][D][sensor:092]: 'Office Humidity': Sending state 14.50000 % with 0 decimals of accuracy

model=DHT22 (with my patch):

[17:17:51][D][dht:048]: Got Temperature=24.6°C Humidity=39.1%
[17:17:51][D][sensor:092]: 'Office Temperature': Sending state 24.60000 °C with 1 decimals of accuracy
[17:17:51][D][sensor:092]: 'Office Humidity': Sending state 39.10000 % with 0 decimals of accuracy
```

The product I have is the white one (DHT22) with the extra black resistor board (lower left on the last image with multiple sensors listed).

https://www.aliexpress.com/snapshot/0.html?spm=a2g0s.9042647.6.2.64584c4dGKBzlW&orderId=8006839808009318&productId=32769460765

We could introduce another model for this quirky hardware design, if you feel that is the best approach. How about introducing another variable to tweak the pulse length? The only change that was needed to get this particular sensor to work was to change the pulse from 0.8ms to 18ms.

**Comment by hughsaunders** [comment]
Thankyou so much, I bought some dht22s and they work fine with a pi, but couldn't get any of them to read with esphome, tried all sorts of vodoo but this patch fixed it 🎉

**Comment by OttoWinter** [comment]
@robinsmidsrod Huh, that's really weird. From what I can see, the calculation for the DHT22 and DHT11 are essentially equivalent. See these lines:

https://github.com/esphome/esphome/pull/926/files#diff-84ac26b9ff8c1269165a2d8835a5d35eR199-R200
https://github.com/esphome/esphome/pull/926/files#diff-84ac26b9ff8c1269165a2d8835a5d35eR208

That should return the same thing, right? Or am I missing something there.

Anyway, yes we can add a new model for this sensor, maybe `DHT22_TYPE2` (if you can come up with a better name than that crappy one, please use that).

**Comment by robinsmidsrod** [comment]
@OttoWinter I'm not really a C++ programmer, so I'm not sure about the exact difference.

Not sure what to call it, but DHT22_TYPE2 is as good as any. The only other alternative I could think of is DHT22_SLOW, but you choose what makes sense.

I'm not sure how to introduce a new model, so hopefully you'll be able to tweak the patch?

@hughsaunders Good to hear that someone else can confirm my findings about these DHT22s.

**Comment by wacher74** [comment]
Can I change or override the DHT library to DHTesp? 
I have an AM2302 sensor, it doesn't work with Esphome, neiter Aurdino/DHT.h. 
It works only if I use DHTesp library. I tried sloeber IDE too, it has DHTesp library that is working.

**Comment by ssieb** [comment]
I think that 18ms in the document is a typo.  Everywhere else in there says minimum 1ms.  There was someone in the Discord channel today that couldn't get his DTH22 working until he changed the 800us to 2ms.  Did you actually find a DHT22 that would fail if the pulse was longer than 800us?  When he tried 18ms, it still worked like I expected it to.  But it did have to be more than 1ms because that wasn't enough. 1.5ms would probably be good.

**Comment by robinsmidsrod** [comment]
@ssieb I've verified that the 2ms delay does indeed work with the DHT22 sensor I have. 18ms also works.

@OttoWinter I've updated the PR with a new commit where I define a new model DHT22_TYPE2 which uses a 2ms delay (instead of 0.8ms). Other than the delay it is exactly the same as a DHT22. Hopefully that should be possible to merge with no impact to existing behavior.

**Comment by nick-ratbert** [comment]
I hacked the 2ms change into my esphome install and forced a rebuild. The nodemcu couldn't read from the unmarked DHT22 I have, with a 3k3 pullup. I can confirm that this change gets everything working nicely. (Basically I hard changed the 800us to 2000us, as I only have one system so far.)
This was the one I ordered: https://www.amazon.co.uk/gp/product/B07DJYMCSL

**Comment by robinsmidsrod** [comment]
To anyone else using this patch that I created which made these weird DHT22-based sensors work (with 2ms), have you noticed any issues with negative temperatures (i.e. below freezing)? Whenever more than -1C is detected, a value of -3276.8C is reported. This is obviously wrong, but I'm not exactly sure why. Does anyone that know a bit more C programming know what might be wrong?

**Comment by vlekkenconsult** [comment]
I found this old link from Arduino forum with similar wrong temperature readings:
https://forum.arduino.cc/index.php?topic=129531.0
Here you find some hints which can cause the problem...
I am not (yet) a C++ specialist so not able to go fully into detail in all calculation steps...

**Comment by robinsmidsrod** [comment]
> I found this old link from Arduino forum with similar wrong temperature readings:
> https://forum.arduino.cc/index.php?topic=129531.0
> Here you find some hints which can cause the problem...
> I am not (yet) a C++ specialist so not able to go fully into detail in all calculation steps...

I was able to debug some more regarding the negative temperature reading, and I was able to figure out what code to modify to make it report the correct value. Please test this out with the DHT22s that match the TYPE2 behavior.

**Comment by pove** [comment]
> I hacked the 2ms change into my esphome install and forced a rebuild. 
How have you been able to do that? I am using Hassio, could I do the same?
I have found the dht.cpp on the sources folder of my device, but every time I compile with esphome, it is replaced with the original one.

**Comment by nick-ratbert** [comment]
I'm not sure I recommend it, but basically there are two files and a link.
You need to make sure they all have the change in and this will stop it
being reverted.

It's a bit painful. I really wish the patch would get merged. This sensor
is so common and a suspect it will turn lots of people off using esphome.
It's such a great integration, that would be a shame.

**Comment by glmnet** [comment]
This looks like a simple patch, how hard would it be for ESPHome to recognize DHT22 is not working with 0.8ms and then try again with 2ms?
If you get working it reliably I'd prefer this way as users should not care about which version of the sensor they have.

Otherwise this really needs a docs update so users are guided to try both versions of DHT22

**Comment by robinsmidsrod** [comment]
@glmnet This is actually not a bad suggestion. Trying to increase the delay until you're able to get a good reading might be a useful workaround for an inconsistent hardware design. Obviously, we'll need an upper limit and possibly decide on what the step value should be.

This also brings me back to a thought I had earlier, that the delay should be possible to define by the user, with 0.8ms being the default, but make it possible to set it to 2ms. Then this issue might possible no longer exist. It would just be a doc patch to explain that some sensors need this value set to 2ms.

If you're able to suggest changes to get any of these to work, I'll happily try to incorporate it into my patch.

**Comment by glmnet** [comment]
I’d just go with a simpler approach of trying 0.8 and if it works stick with it otherwise switch to 2 and keep trying. If it works stick with it otherwise switch.

**Comment by pixitha** [comment]
I would love for either option to be merged, either make the default 2ms for all DHT22s (which seems safe from the testing I've seen) or make two types. There is no reason to drag this out into some complicated logic of waiting for a failure, and then trying different timings. It would be great for the community to just get something merged so people don't have to mess with the files to get this working in the mean time.

**Comment by glmnet** [comment]
Ok, somebody add the docs and I'll merge both together

**Comment by robinsmidsrod** [comment]
@glmnet I've added in the docs for the dht component in esphome/esphome-docs#563. As there were no technical details mentioned on the other types I didn't add any for this either, just the user-facing model definition.

**Comment by glmnet** [comment]
It is ok, but as this PR is created against dev branch, the docs one should be created against `next` not `current`. Please update that.

**Comment by robinsmidsrod** [comment]
@glmnet I've pushed a new PR on esphome-docs that is against the `next` branch. Is this now in a state that can be merged?

**Comment by glmnet** [comment]
@robinsmidsrod  Could you please create a new pr for the docs (old one is not mergeable due to travis ci crazyness)

Thanks!

**Pull request merged**
