### PR TITLE
Cleanup web server prometheus integration

### PR DESCRIPTION
**Pull request by OttoWinter**
This reverts commit f63fd9696fe207c2c996e4a8f87b009a0b0174e3.## Description:

We have an API for adding endpoints to the web server. That should be used not forcing it into the `web_server` code, the previous code breaks the modularity principle.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** https://github.com/esphome/esphome-docs/pull/713

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
I can do the docs, it is just adding `prometeus:` in the config right? Should it still be listed at the end of the `web_sever` component or should it migrate to a new config page?

**Comment by OttoWinter** [comment]
@glmnet Yeah I'm not sure where we should put it in the docs. Since it's rather small it could fit in web_server, but then nobody looking for prometheus would find it there.

A new page would be ideal (I can also do it, though I've never used prometheus so can't write well about it).

**Comment by glmnet** [comment]
Docs has been done already. It's at the bottom of web server

**Comment by OttoWinter** [comment]
@glmnet The problem is that the config format changed. Now the config is no longer

```yaml
web_server:
  prometheus: true
```

but 
```yaml
web_server:
# load prometheus integration
prometheus:
```

**Comment by OttoWinter** [comment]
I will update the docs later

**Pull request merged**
