### PR TITLE
Add gp8403 output component

### LINKED ISSUE #2115: Please can the DFRobot 2-Channel I2C DAC module (DFR0971) be integrated into ESPHome
**Describe the problem you have/What new integration you would like**
The DFRobot 2-Channel I2C DAC module (DFR0971) be integrated into ESPHome.

**Please describe your use case for this integration and alternatives you've tried:**
It's very useful for people who have analogue 0-10v LED dimmer drivers that don't use PWM.

**Additional context**
Links to the Github from DFRobot with Arduino code:

- https://wiki.dfrobot.com/SKU_DFR0971_2_Channel_I2C_0_10V_DAC_Module#target_8
- https://github.com/DFRobot/DFRobot_GP8403

### PR DESCRIPTION
**Pull request by jesserockz**
# What does this implement/fix?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** closes https://github.com/esphome/feature-requests/issues/2115
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2901

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
external_components:
  - source: github://pr#4495
    components: gp8403

gp8403:
  id: gp8403_hub
  voltage: 5v

output:
  - platform: gp8403
    channel: 0
    id: gp8403_0
  - platform: gp8403
    channel: 1
    id: gp8403_1

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by ghost** [comment]
Not working yet, this was my config, will try it on ESP32 but don't think it will make much difference?:

```yaml
esphome:
  name: led-dimmers
  friendly_name: LED Dimmers

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "y6THLeeyPNum6yyIiv0RuKaaTZj4vfPTYwcyTCQNV/A="

ota:
  password: "1caf17956efc4e7498819422bbd09cb4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led-Dimmers Fallback Hotspot"
    password: "bZnHlfLqg7oM"

captive_portal:

# Testing 2 Channel 0-10v I2C DAC GP8403
external_components:
  - source: github://pr#4495
    components: gp8403

i2c:
  scan: true

output:
  - platform: gp8403
    channel: 0
    id: gp8403_0
  - platform: gp8403
    channel: 1
    id: gp8403_1

light:
  - platform: monochromatic
    name: "LED 1 Test"
    output: gp8403_0
    gamma_correct: 1.2

  - platform: monochromatic
    name: "LED 2 Test"
    output: gp8403_1
    gamma_correct: 1.2
  ```

**Comment by ssieb** [comment]
Add `address: 0x5F` to each output.

**Comment by ghost** [comment]
Working now with both ESP32 and ESP8266

**Comment by KoenBreeman** [comment]
Gents, I've already build this library. It's here. You can use it to implement it in ESP Home.
https://github.com/KoenBreeman/ESPHome

You can change the channel and alter the voltage to 5V or 10V.

**Comment by KoenBreeman** [comment]
```
GP8403:
  max_level: 10

output:
  - platform: GP8403
    id: GP8403_output
    channel: 2

fan:
  - platform: speed
    output: GP8403_output
    name: "Ventilator"
    speed_count: 100
```

**Comment by nagyrobi** [comment]
Will this support multiple devices with different address?

What's preventing this from being accepted? No docs?

**Comment by jesserockz** [comment]
I actually want to make some changes to it to allow the voltage selection and address set on a component hub instead of each output. Just have not found the time to come back to it. 

But otherwise yes docs I still need to get to unless you want to write them @nagyrobi ?

**Comment by nagyrobi** [comment]
I take the docs, sure! That's why I was asking.

**Comment by jesserockz** [comment]
Thanks, I have pushed the changes I wanted to make now and updated the PR description with an updated test YAML

**Comment by KoenBreeman** [comment]
Gents I already have it build as a component and an output. See my github. How can I contribute to implement that?

**Comment by KoenBreeman** [comment]
> I actually want to make some changes to it to allow the voltage selection and address set on a component hub instead of each output. Just have not found the time to come back to it.
> 
> But otherwise yes docs I still need to get to unless you want to write them @nagyrobi ?

My component has already the output per component set. And you can also change the address.

**Comment by KoenBreeman** [comment]
I’ve also build in the sin triangle en square blocks. As from the original code. But haven’t checked it. It’s still development code

**Comment by nagyrobi** [comment]
@jesserockz how about setting the address and using multiple devices in the config?

**Comment by KoenBreeman** [comment]
> @jesserockz how about setting the address and using multiple devices in the config?

Yes I was updating the code to use multiple devices, I can add multiple devices, but I have to change the code in order for the output to function. Now it just picks up the component, but then you have to specify the component ID. So I'm updating, but perhaps it's better to merge the 2 developments?

**Comment by nagyrobi** [comment]
It's up to you, but having multiple devices and configurable address is trivial because this board only has 2 channels. Which doesn't bring any benefit compared to using PWM output on 2 pins as I2C uses also 2 pins...

Real benefit comes when you need more than 2 such outputs, and with a couple of such boards you still only use up 2 pins for I2C.

**Comment by jesserockz** [comment]
You can have multiple. See how I added this to the `test5.yaml` file for how you can use multiple of them. That example is using 2 independent chips, one set to 5v and one set to 10v. And the outputs in the test file are pointing to each of the main hubs.

**Comment by jesserockz** [comment]
@KoenBreeman While we appreciate the effort you have put into writing your custom component, we don't specifically need a way to represent the waves in the outputs, as whatever component is using the output is able to generate that wave itself and just control the output to match. This is the ESPHome way of moduler components.

I just looked at your code now and I don't think there is anything else to merge into my PR from your code. Let me know if you disagree.

**Comment by KoenBreeman** [comment]
@jesserockz I can follow your reasoning and I agree with that. I’m not sure if home assistant can generate sinus waves. But for me it’s not really necessary. I just thought it was fun to build into the code and it may be convenient for someone. 

I also added the options to steer both channels. The method for esphome is to just create 2 outputs and steer them simultaniously. Is that correct? 

Furthermore I would like to know if it’s possible to change the address of the GP8403. Becausr you can change it on the board. Is that already a standard feature of a I2C device? Or do we have to program for this feature?

**Comment by jesserockz** [comment]
Its not that Home Assistant should generate the sine waves, but another component inside ESPHome could be created to do so.

The i2c address can be changed in yaml on the main hub by just setting `address: 0xXX`

**Comment by alxzndr** [comment]
It's not working on my Liligo esp32 POE board.

The i2c device is detected:
`[14:52:57][I][i2c.arduino:068]: Results from i2c bus scan:
[14:52:57][I][i2c.arduino:074]: Found i2c device at address 0x5F
`
I get this error message in the log when trying to set the output from esphome (tested with different GPIO ports for i2c)
`[E][gp8403.output:021]: Error writing to GP8403, code 2`

This is my yaml config:
```yaml
external_components:
  - source: github://pr#4495
    components: gp8403

i2c:
  scan: true
  sda: GPIO14
  scl: GPIO16
  frequency: 400000Hz

# Set voltage of 0-5v or 0-10v 
gp8403:
  id: gp8403_10v
  voltage: 10v

output:
  - platform: gp8403
    gp8403_id: gp8403_10v
    channel: 0
    id: gp8403_0

light:
  - platform: monochromatic
    name: "test output"
    output: gp8403_0
    gamma_correct: 1.2
```

**Comment by jesserockz** [comment]
@alxzndr The default i2c address in this component is `0x58`, your device is at `0x5F`, you need to change it:
```yaml
gp8403:
  id: gp8403_10v
  voltage: 10v
  address: 0x5f
```

**Comment by alxzndr** [comment]
@jesserockz oh, my bad!
Works perfectly with the correct address. 🎉 :ok_hand:

**Comment by Carpetner** [comment]
Just works! I have tested two devices, on the same i2c bus and on separate buses (3 and 5 V). 

Lights need `gamma_correct: 1` for a linear voltage response, which can then even be limited per channel with `max_power` and `min_power` at the output. And in a very nice and clean way indeed.

Great job, Sir.

**Pull request merged**
