### PR TITLE
ledc: do not try to write_state to an uninitialized output

### LINKED ISSUE #1732: ESP32 crashes when LEDc is used
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

I am using docker (`:latest` and `:dev`).

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 on a ESP32dev-Clone from AZDelivery

**ESPHome version (latest production, beta, dev branch)**

`:latest` and `:dev` from dockerhub (pulled today).

**Affected component:**

https://esphome.io/components/output/ledc.html

**Description of problem:**

When I configure an output to use LEDc, the esp crashes immediately on use of that output.

My goal is to have a status LED for a light (on when the light is on and faded when the light is off). That is why I am changing the output in the `on_turn_on` of a switch.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: crash
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "XXX"
  password: "XXXXXXXX"

switch:
  - platform: gpio
    id: light
    pin: 32
    on_turn_on:
        then:
            - output.turn_on: gpio_2
    on_turn_off:
        then:
            - output.turn_off: gpio_2

output:
  - platform: ledc
    id: gpio_2
    pin: GPIO2

debug:

logger:
  level: DEBUG
```

**Logs (if applicable):**

```
[15:53:49]ets Jun  8 2016 00:22:57
[15:53:49]
[15:53:49]rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
[15:53:49]configsip: 0, SPIWP:0xee
[15:53:49]clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
[15:53:49]mode:DIO, clock div:2
[15:53:49]load:0x3fff0018,len:4
[15:53:49]load:0x3fff001c,len:1044
[15:53:49]load:0x40078000,len:8896
[15:53:49]load:0x40080400,len:5828
[15:53:49]entry 0x400806ac
[15:53:49][I][logger:166]: Log initialized
[15:53:49][I][app:029]: Running through setup()...
[15:53:49][C][switch.gpio:011]: Setting up GPIO Switch 'light'...
[15:53:49][D][switch:025]: 'light' Turning OFF.
[15:53:49][D][switch:045]: 'light': Sending state OFF
[15:53:49]/home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/freertos/queue.c:1442 (xQueueGenericReceive)- assert failed!
[15:53:49]abort() was called at PC 0x40088b65 on core 1
[15:53:49]
[15:53:49]Backtrace: 0x4008c730:0x3ffb1b70 0x4008c961:0x3ffb1b90 0x40088b65:0x3ffb1bb0 0x400d9227:0x3ffb1bf0 0x400d1ae1:0x3ffb1c10 0x400d2033:0x3ffb1c40 0x400d204f:0x3ffb1c60 0x401499a5:0x3ffb1c80 0x40149c95:0x3ffb1ca0 0x40149c73:0x3ffb1cc0 0x40149d23:0x3ffb1ce0 0x400d73c7:0x3ffb1d00 0x400d2355:0x3ffb1d20 0x400d1a39:0x3ffb1d50 0x400d2257:0x3ffb1da0 0x400d17a5:0x3ffb1dc0 0x400d17ce:0x3ffb1df0 0x40149ac1:0x3ffb1e10 0x40149b45:0x3ffb1e30 0x400d5c25:0x3ffb1e50 0x400d7325:0x3ffb1ea0 0x400d9d03:0x3ffb1fb0 0x40088e79:0x3ffb1fd0
[15:53:49]
[15:53:49]Rebooting...
```

**Additional information and things you've tried:**

I have googled the problem of an `abort()` in `queue.c` of the IDF, but it seems that that issue can have a number of reasons. Most people seem to have that problem when using an uninitialized mutex...

Re-ordering the output and switch components in the `yaml` is not helping.

### PR DESCRIPTION
**Pull request by toelke**
# What does this implement/fix? 

See bug https://github.com/esphome/issues/issues/1732

In short: When accessing a LEDc-output from the `on_switch_on` "method", esphome crashes on boot as the LEDc might be uninitialized when the switch has initialized and calls `on_switch_on` the first time. This patch buffers any state-change of LEDc until initialization has finished.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)

**Related issue or feature (if applicable):** fixes esphome/issues#1732
  
# Test Environment

- [X] ESP32
- [ ] ESP8266
- [X] Windows
- [X] Mac OS
- [X] Linux

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

**Comment by jesserockz** [comment]
I find this to be a bit hacky. A better option could be to add `+10` onto the `get_setup_priority()` returned value in `ledc_output.h`
Yes, this could easily come up in another place in the code, but that is what the setup priorities are for. They just need adjusting when issues are found.

**Comment by toelke** [comment]
> I find this to be a bit hacky. A better option could be to add `+10` onto the `get_setup_priority()` returned value in `ledc_output.h`
> Yes, this could easily come up in another place in the code, but that is what the setup priorities are for. They just need adjusting when issues are found.

Perfect, I did not know about that. I tried it and adding `10` indeed helps.

**Comment by JingleheimerSE** [comment]
@jesserockz, just curious, @toelke branch get merged into Dev? Looks like it got cancelled? 

Just wondering if I can switch back to dev for my local builds.

**Comment by jesserockz** [comment]
Oh I accidentally closed this. Sorry

**Comment by jesserockz** [comment]
But also, changing the setup_priority for everyone in this case might not be the best solution.
You can actually change the priority directly in YAML:
```yaml
output:
  - platform: ledc
    id: gpio_2
    pin: GPIO2
    setup_priority: 810
```

**Comment by JingleheimerSE** [comment]
> But also, changing the setup_priority for everyone in this case might not be the best solution.
> You can actually change the priority directly in YAML:
> 
> ```yaml
> output:
>   - platform: ledc
>     id: gpio_2
>     pin: GPIO2
>     setup_priority: 810
> ```

@jesserockz oh that's neat! I like that better as well. Thanks for the heads up!

**Comment by OttoWinter** [comment]
Hmm, this does still feel quite hacky and just fights the symptoms of a depper issue (this issue is not isolated to ledc, but all output platforms). And code-wise it's also not nice because ledc _should_ be HARDWARE setup priority (because it represents hardware). Maybe a better solution is to print a warning if the method is accessed before the setup is complete?

**Review by OttoWinter — APPROVED** [review]

**Pull request merged**
