### PR TITLE
Update sim800l.cpp

### PR DESCRIPTION
**Pull request by fbeek**
Hello,

without the added line and an Sim800l EVB the request of an USSD Code results in an register/deregister GSM loop and the state in HomeAssistant toggles after the ussd request.

Also the STATE_CHECK_USSD  case is never called and the result is newer delivered to the sensor.

With this line everything works as expected.

Regards

# What does this implement/fix?

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:
```yaml
esphome:
  name: emergency-com-centers

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "###"
  services:
    - service: send_sms
      variables:
        recipient: string
        message: string
      then:
        - sim800l.send_sms:
            recipient: !lambda 'return recipient;'
            message: !lambda 'return message;'
    - service: dial
      variables:
        recipient: string
      then:
        - sim800l.dial:
            recipient: !lambda 'return recipient;'
    - service: connect
      then:
        - sim800l.connect
    - service: disconnect
      then:
        - sim800l.disconnect
    - service: send_ussd
      variables:
        ussdCode: string
      then:
        - sim800l.send_ussd:
            ussd: !lambda 'return ussdCode;'

ota:
  password: "###"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Emergency-Com-Center"
    password: "####"

captive_portal:

uart:
  baud_rate: 9600
  tx_pin: 33
  rx_pin: 32


sim800l:
  on_sms_received:
    - lambda: |-
        id(sms_sender).publish_state(sender);
        id(sms_message).publish_state(message);
  on_incoming_call:
    - lambda: |-
        id(caller_id_text_sensor).publish_state(caller_id);
  on_call_connected:
    - logger.log:
        format: Call connected
  on_call_disconnected:
    - logger.log:
        format: Call disconnected
  on_ussd_received:
    - lambda: |-
        id(ussd_message).publish_state(ussd);
        
sensor:
  - platform: sim800l
    rssi:
      name: "Sim800L RSSI"
  
binary_sensor:
  - platform: sim800l
    registered:
      name: "Sim800L Registered"

text_sensor:
  - platform: template
    id: sms_sender
    name: "Sms Sender"
  - platform: template
    id: sms_message
    name: "Sms Message"
  - platform: template
    id: caller_id_text_sensor
    name: "Caller ID"
  - platform: template
    id: ussd_message
    name: "Ussd Code"

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by fbeek** [comment]
Hello,

have you any news on this simple pr?

KInd Regards

**Comment by glmnet** [comment]
The thing is only you submitted this, there is no linked issue. 

Can you please track the author of this feature and kindly ask him to test this?

This doesn't work for me because of my network so cannot test.

**Comment by fbeek** [comment]
Hello,

there is no issue for this in the tracker.
I have build a new device with an Sim800l EVB with an new Vodafone Sim Card and found this problem and simply fixed it :-D

I ruled out other possible issues like power supply and module config and found the problem with the missing line in the code.
I have checked it on three of these modules here on my bench and with two different sim cards.

**Comment by glmnet** [comment]
@maty535 are you using the usssd now in sim800l? 
in that case,
could you check this? looks like it should work ok? 

Thanks

**Review by glmnet — APPROVED** [review]
As OP test ok and no feedback from earlier contributor I approve this

**Comment by fbeek** [comment]
Thank you very much @glmnet.

Dont hesitate to send me an info if there is something to regarding this in the future.

**Pull request merged**
