### PR TITLE
Add Tuya Cover component

### PR DESCRIPTION
**Pull request by pauln**
## Description:
Adds a Tuya Cover component, for Tuya-based curtain motors.  Developed and tested against the Zemismart ZM79E-DT (wifi version).

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
Hi there @pauln

Sorry it took so long to review. I just updated your PR for the latest upstream changes, and the code looks good to me (I removed the api service, because then the component would be unusable with mqtt).

Can you take a look if everything still works?

Thanks!

**Comment by pauln** [comment]
@OttoWinter Sorry for the delayed response - it's winter here, so I wanted to wait for the weekend so that I could try this out during daylight hours.

Aside from the removed service, there's one issue: the Tuya MCU frequently generates an incorrect checksum when it sends datapoint updates for the control datapoint, which means that open/close/stop commands become unreliable, as  `set_datapoint_value()` checks if the requested value is different from the current value - and skips sending the new value (with the verbose log showing "Not sending unchanged value") if it doesn't think it's changed.

I see a couple of possible ways to work around this (both involving tweaks to the core Tuya component):
- Add a `force_set_datapoint_value()` function (might as well add two - one for each variant of `set_datapoint_value()`) which bypasses the "unchanged" check, and use that to send the open/close/stop commands
- Add a way for a Tuya integration to tell the core Tuya component to process datapoint messages even if their checksum is invalid, as everything but the checksum still seems to be valid in this case

I've got a working (and reasonably clean) change for the first option; I can add it to the branch if you're happy with the "force" approach.  The second option seems like it would be more complex, assuming that we want to keep the "drop if checksum is invalid" behaviour except for specific known-broken cases such as this one - and it might not solve this issue completely anyway, as a bit of experimentation suggests that the Tuya MCU doesn't always send the correct initial state (it seems to send `0x0` - which is the "open" command) which means that sometimes one command which should be available isn't (i.e. you can't open the curtains, until you send a "stop" or "close" command).

Back to the API service removal - is there a better way to make it possible to call the `set_direction()` function which won't prevent the component from being used with MQTT (ideally one which works for both MQTT and API)?  If not, perhaps we should add an "inverted" flag to the component configuration, and use that to set the direction on startup?

**Comment by pauln** [comment]
@OttoWinter I've gone ahead and pushed up a tweak to add and use a `force_set_datapoint_value()` function, as the more I thought about it the more I realised that this was the only viable option.  Per the commit message (and note that I added as a code comment), it's not just the invalid datapoint report checksums which are a problem - it turns out that the Tuya MCU doesn't send a datapoint report at all for the command datapoint when a percentage is set, or when the curtains are controlled externally (manually or via the RF remote); it only sends a report effectively echoing back the value that we send.  This means that it might still be set to the command which we want to issue, which means the value "hasn't changed" and so won't be sent.

As an example, if you issue a "close" command, then later send a "50%" command, the command datapoint's last known/reported value is still "close" (0x02), so (without the "force set") it becomes impossible to send a "close" command as the datapoint's value "hasn't changed", even though the curtains are half open.

**Review by OttoWinter — APPROVED** [review]
LGTM then, thanks!

(Don't know Tuya too well, so just requested a second review)

When you have time, could you update the docs as well? Thanks!

**Comment by pauln** [comment]
@OttoWinter Thanks - I'll work on the docs shortly.  Did you have any thoughts on what to do about the direction inversion?

> Back to the API service removal - is there a better way to make it possible to call the set_direction() function which won't prevent the component from being used with MQTT (ideally one which works for both MQTT and API)? If not, perhaps we should add an "inverted" flag to the component configuration, and use that to set the direction on startup?

The Tuya MCU does remember the direction, so setting the direction on startup is unnecessary - but if we can't add an API service without breaking MQTT, it might be the best option.  The direction is unlikely to need changing after the correct direction has been determined and set once, so doing it via configuration rather than a service call probably isn't a bad thing.

**Comment by OttoWinter** [comment]
> Back to the API service removal 

Sorry, missed that. What do you mean with API service removal? Probably I'm missing something obvious here :D

What is needed with `set_direction()`?

**Comment by pauln** [comment]
@OttoWinter From your first comment:
> I removed the api service, because then the component would be unusable with mqtt

Ideally, we need to be able to either call `set_direction()` at runtime (as per my original PR), or add an option to the component's config which is then used to make a `set_direction()` call on startup.  This is because the motor doesn't know which direction it needs to go in order to (for example) open the curtains - from memory, mine are all "inverted" (even though I followed the installation instructions), so out of the box they close when you tell them to open and vice versa; setting the direction to "inverted" makes them go the right way.  Having this available as a service means that you can fix it without having to recompile - but since you're unlikely to want to change it once you've got it correct, perhaps a recompile to change the config isn't a big deal.

**Comment by OttoWinter** [comment]
Ah thanks, totally forgot about that

Yes for situations like this we usually have a config option (and require a recompile).

Fetching that stuff over network is not good anyway, because if the network is down you won't get that data (and for a cover that could be a bad thing).

Another option would be to expose an action that can be called via YAML - but the user needs to wire that up with the `api`/`mqtt` section themselves then.

**Comment by pauln** [comment]
Network availability isn't really an issue in this case, as the direction is "set and forget" (the Tuya MCU stores it persistently), which is why I originally had it as a service which the user can call (i.e. from Home Assistant).

I've just had a go at implementing the config option, and I can't quite make it work as `TuyaCover::setup()` seems to be running before the main Tuya component has finished its initialisation sequence - it doesn't yet know about the datapoint, and so refuses to set it.  I can't see a way to schedule something to happen after the Tuya component reaches `TuyaInitState::INIT_DONE`; I can't even check it in a `loop()` as `init_state_` is protected.  We might need a bit of insight from somebody who's more familiar with Tuya to figure out the best way to achieve this...

**Comment by jesserockz** [comment]
Hi @pauln,

With #2279 merged, do you want to rebase your work on top of the latest dev as there will now be conflicts. A quick look at your PR and there are certain features still in this PR that were not in the other one that will still be useful to have.

Cheers,
Jesse

**Comment by pauln** [comment]
Sorry I didn't get back to this sooner.  I'm looking at #2279 now, to see how I can rework this to build on top of it.

@marmarek, I see you noted that your device has a boolean datapoint with ID `5`; is it possible that toggling that datapoint changes the direction of travel?  I've got a few ZM79E-DT curtain motors, and datapoint `5` inverts the direction on those - so it seems plausible that it'd do the same for your Tuya cover device.  I'm hoping that's the case, as there's otherwise a bit of a conflict with your `invert_position` config option; the position always needs "inverting" for mine, irrespective of which way DP `5` is set, so I'm hoping that yours is actually the same (so that I can just set DP `5` as part of the initialisation and then always subtract the values from `1.0f`).

Mine also have datapoint ID `2` as an enum I've called "control", as it can be used to send open/close/stop commands - does yours have such a datapoint?

**Comment by marmarek** [comment]
> I see you noted that your device has a boolean datapoint with ID `5`; is it possible that toggling that datapoint changes the direction of travel?

It does nothing for me, or at least I haven't found what it does. But also, I do need to set `invert_position` too.

**Comment by pauln** [comment]
Thanks, @marmarek - in that case, I'll work on the assumption that all Tuya cover devices' position values work the same way (the opposite way to HA / ESPHome), and thus always invert the values irrespective of `invert_position`.  I'll then change the `invert_position` config (when used in conjunction with a new `direction_datapoint` config) to set the direction of travel during initialisation.  As this means that the `invert_position` option will effectively be ignored unless `direction_datapoint` is also set, existing configs should still work without any changes.

**Comment by pauln** [comment]
Superseded by #2279 and #2637.

**Pull request closed without merging**
