### PR TITLE
New component iec62056

### PR DESCRIPTION
**Pull request by aquaticus**
# What does this implement/fix?

*IEC 62056-21* is an international standard for a protocol to exchange data with utility meters. Mostly for electricity but also water, thermal and other meters.

The ``iec62056`` component allows you to read data from any compatible meter. The component requires a *serial port* and *an external optical interface*. Data exchange uses an infrared optical channel. Compatible meters are equipped with a characteristic round metal plate with two opto-elements inside. 

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** None

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2644

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [x] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
uart:
  - id: uart_hardware
    rx_pin: GPIO3
    tx_pin: GPIO1
    baud_rate: 300
    data_bits: 7
    parity: EVEN
    stop_bits: 1

iec62056:
  update_interval: 60s
  baud_rate_max: 9600
  receive_timeout: 3s
  battery_meter: False
  retry_counter_max: 2
  retry_delay: 10s

text_sensor:
  - platform: iec62056
    obis: 1-0:15.6.0
    group: 0
    name: Test complete frame

sensor:
  - platform: iec62056
    obis: 1-0:15.8.0
    name: Absolute active energy total
    unit_of_measurement: kWh
    accuracy_decimals: 3
    device_class: energy
    state_class: total_increasing

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
Forgive me if it is obvious, but what is the difference between this and the existing [SML component](https://esphome.io/components/sml.html)?

**Comment by aquaticus** [comment]
> Forgive me if it is obvious, but what is the difference between this and the existing [SML component](https://esphome.io/components/sml.html)?

Main differences:
1. Data in SML is binary encoded (ASN.1) vs pure ASCII in IEC62056-21
2. SML component implements only one way communication. A meter sends data time to time, so you only need receiver. No need to send anything back to a meter. IEC62056-21 requires two way communication. You mut send readout request to a meter.
3. SML uses fixed 9600 bps baud rate while IEC62056-21 negotiate transmission speed.
4. SML uses CRC as checksum vs LRC.

Both protocols require the same hardware for optical interface based on IEC62056-21 (for SML component only receiver part is mandatory).

**Comment by Mat931** [comment]
My smart meter is using a similar protocol but without two way communication. The meter transmits all measurements every second. Only the infrared receiver is connected to the ESP32.
Right now I'm using this component: https://github.com/mampfes/esphome_obis_d0
I tested your code but unfortunately it doesn't work with my smart meter

Framework: ESP32 Arduino

Config:

```yaml
...

external_components:
  - source: github://pr#4388
    components: [iec62056]
    refresh: always

uart:
  id: uart_bus
  rx_pin:
    number: GPIO3
    inverted: false
  baud_rate: 9600
  data_bits: 7
  parity: EVEN
  stop_bits: 1
  rx_buffer_size: 2048

iec62056:
  id: smartmeter
  baud_rate: 9600

sensor:
  - platform: iec62056
    obis: "1-0:1.8.0*255"
    name: "Consumed Energy"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    state_class: total_increasing
    device_class: energy

  - platform: iec62056
    obis: "1-0:16.7.0*255"
    name: "Power"
    unit_of_measurement: W
    accuracy_decimals: 2
    state_class: measurement
    device_class: power

  - platform: iec62056
    obis: "1-0:36.7.0*255"
    name: "Power L1"
    unit_of_measurement: W
    accuracy_decimals: 2
    state_class: measurement
    device_class: power

  - platform: iec62056
    obis: "1-0:56.7.0*255"
    name: "Power L2"
    unit_of_measurement: W
    accuracy_decimals: 2
    state_class: measurement
    device_class: power

  - platform: iec62056
    obis: "1-0:76.7.0*255"
    name: "Power L3"
    unit_of_measurement: W
    accuracy_decimals: 2
    state_class: measurement
    device_class: power
```

Logs: 

```
[20:55:11][C][logger:293]: Logger:
[20:55:11][C][logger:294]:   Level: DEBUG
[20:55:11][C][logger:295]:   Log Baud Rate: 0
[20:55:11][C][logger:296]:   Hardware UART: UART2
[20:55:11][C][uart.arduino_esp32:108]: UART Bus 0:
[20:55:11][C][uart.arduino_esp32:110]:   RX Pin: GPIO3
[20:55:11][C][uart.arduino_esp32:112]:   RX Buffer Size: 2048
[20:55:11][C][uart.arduino_esp32:114]:   Baud Rate: 9600 baud
[20:55:11][C][uart.arduino_esp32:115]:   Data Bits: 7
[20:55:11][C][uart.arduino_esp32:116]:   Parity: EVEN
[20:55:11][C][uart.arduino_esp32:117]:   Stop bits: 1
[20:55:12][C][iec62056.component:045]: IEC62056:
[20:55:12][C][iec62056.component:046]:   Update Interval: 900.0s
[20:55:12][C][iec62056.component:047]:   Connection timeout: 3.000s
[20:55:12][C][iec62056.component:048]:   Battery meter: NO
[20:55:12][C][iec62056.component:050]:   Baud rate: 9600 bps
[20:55:12][C][iec62056.component:054]:   Max retries: 2
[20:55:12][C][iec62056.component:055]:   Retry delay: 15.000s
[20:55:12][C][iec62056.component:057]:   Sensors:
[20:55:12][C][iec62056.component:060]:     OBIS: 1-0:76.7.0*255
[20:55:12][C][iec62056.component:060]:     OBIS: 1-0:56.7.0*255
[20:55:12][C][iec62056.component:060]:     OBIS: 1-0:36.7.0*255
[20:55:12][C][iec62056.component:060]:     OBIS: 1-0:1.8.0*255
[20:55:12][C][iec62056.component:060]:     OBIS: 1-0:96.1.0*255
[20:55:12][C][iec62056.component:060]:     OBIS: 1-0:16.7.0*255
[20:55:12][E][uart:016]:   Invalid baud_rate: Integration requested baud_rate 300 but you have 9600!
[20:55:14][D][iec62056.component:219]: Connection start
[20:55:17][E][iec62056.component:253]: No transmission from meter.
[20:55:17][D][iec62056.component:221]: Connection end
[20:55:17][D][iec62056.component:697]: Retry 2 of 2. Waiting 15000 ms before the next try
[20:55:32][D][iec62056.component:219]: Connection start
[20:55:35][E][iec62056.component:253]: No transmission from meter.
[20:55:35][D][iec62056.component:221]: Connection end
[20:55:35][D][iec62056.component:693]: Exceeded retry counter.
[20:55:35][D][iec62056.component:721]: Waiting 863893 ms for the next scheduled readout (every 900000 ms).
```

**Comment by aquaticus** [comment]
@Mat931 Your meter uses SML protocol (you got "Public Key" printed on the meter right?). 
This component supports **different standard**, so you need a compatible meter and infrared receiver and transmitter. SML is kinda derivative of IEC620560-21 but they are NOT compatible.

If you like I can provide you software meter simulator (I also developed integration tests for this component). In the simplest scenario you can use serial->USB converter that is on many development boards (no need for optical interface).

**Comment by Mat931** [comment]
@aquaticus No it's not SML and there is no Public key on the meter. The data is ASCII encoded and looks like this:
(Baud 9600 7E1)
```
/EBZXXXXXXXXXXX_XXX

1-0:0.0.0*255(1EBZXXXXXXXXXX)
1-0:96.1.0*255(1EBZXXXXXXXXXX)
1-0:1.8.0*255(00XXXX.XXXXXXXX*kWh)
1-0:16.7.0*255(000XXX.XX*W)
1-0:36.7.0*255(000XXX.XX*W)
1-0:56.7.0*255(000XXX.XX*W)
1-0:76.7.0*255(000XXX.XX*W)
1-0:96.5.0*255(XXXXXXXX)
0-0:96.8.0*255(XXXXXXXX)
!
```

**Comment by aquaticus** [comment]
Thanks for the update. Looks like IEC62056 compatible meter. I never saw this mode in a meter.
In short, this is not supported by the component.
I have to implement this mode.
The log file you provided is the entire transmission?
Can you please provide me 4 character from identification string `/EBZXXXXXXXXXXXXXXX` after `Z`? The rest is serial number? 
By any chance do you have access to any other meter?

**Comment by Mat931** [comment]
@aquaticus
Yes, it's the entire transmission, sent every second. It starts with bytes 2F 45 and ends with 0D 0A 21 0D 0A. New lines are 0D 0A.
The string after /EBZ is made of capital letters (A-Z), numbers (0-9) and "_". It's not the serial number.
The serial number is sent twice in the lines:
```
1-0:0.0.0*255(1EBZXXXXXXXXXX)
1-0:96.1.0*255(1EBZXXXXXXXXXX)
```
No I don't have access to other meters.
Thanks for your work!

**Comment by aquaticus** [comment]
@Mat931 I added support for mode D of IEC62056-21. The component supports now unidirectional transmission, so it should work with your meter.

I'll be grateful if you test it with your meter.

The key change in the configuration is a new setting `mode_d` forcing mode D:
```yaml
iec62056:
  id: smartmeter
  mode_d: True
```

**Comment by Mat931** [comment]
@aquaticus Thank you! Everything works except for conversion of hexadecimal to numbers.
The status (1-0:96.5.0*255) and time of operation (0-0:96.8.0*255) are in hexadecimal and give me the error:
```
[E][iec62056.component:622]: Cannot convert data to number. Consider using text sensor. Invalid data: '0000001C'
```

**Comment by aquaticus** [comment]
@Mat931 Good to hear it works with the real device.

`iec62056` sensor supports only decimal numbers. In your case, you have to define text sensor that accepts any format. If you need a decimal value you can convert it, see the sample code below:

```yaml
  sensor:
    - platform: template
      id: hex_to_dec_sensor
      name: "Converted hexadecimal number"

  text_sensor:
    - platform: iec62056
      id: hex_sensor
      obis: 0-0:96.8.0*255
      name: Hex content
      internal: True
      on_value:
        lambda: |-
          std::string hex_str = id(hex_sensor).state;
          uint32_t dec=std::stoul(hex_str, nullptr, 16);
          ESP_LOGI("iec62056.component", "Converted HEX '%s' to %u decimal", hex_str.c_str(), dec);
          id(hex_to_dec_sensor).publish_state((float)dec);
```

**Comment by Mat931** [comment]
Would love to see this merged. Is there anything still missing?

**Comment by lebeno** [comment]
I am planning to test this with a _Landis+Gyr E650_ electricity meter soon in Belgium. It does not have a visible metal ring, but it has an optical interface (IR receiver and transmitter about 6.5mm apart), with "readout" (in Dutch and French) and "dlms" printed next to them and the manual says "The reading head is held magnetically".

Maybe this is to soon, but it could be handy to also mention DLMS in your documentation and some meter models that are known to work with this component? It is very likely that people will search for their meter model in combination with ESPHome.

I will report back when I have acquired an optical interface and I have had access to the meter.

**Comment by aquaticus** [comment]
This component does not support DLMS. Typically you need a password to read data from DLMS meter. In practice, energy distribution company won't give you the password.
I got one meter with DLMS logo but it actually uses a different protocol, so there's a chance you can use this component.

By the way I created new home for this component https://aquaticus.info/iec62056.html

**Pull request closed without merging**
