### PR TITLE
Dsmr Unit Fix

### LINKED ISSUE #3117: Invalid Unit
### The problem

I am trying to set up a [SlimmeLezer+](https://www.zuidwijk.com/product/slimmelezer-plus/) to read data from my smart meter (DSMR 5), but i get an error when trying to read my consumed energy.

If i only request the DSMR Version or Identification it works fine, but as soon as i add the energy_delivered_tariff1 sensor all readings become unavailable.

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.3.1

### What platform are you using?

ESP8266

### Board

SlimmeLezer+

### Component causing the issue

dsmr

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

```txt
[E][dsmr:265]: 1-0:1.8.0(017225650*Wh)
                    ^
Invalid unit
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Herbycheck**
# What does this implement/fix?
Fixes an error when trying to read energy consumed/returned.

The old Library threw an error when reading energy with Wh as unit.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes  https://github.com/esphome/issues/issues/3117

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
You should PR the changes into the upstream library so it can be updated, then just update the version here. Not just change the whole library to another fork please.

**Comment by Herbycheck** [comment]
the problem is that i just reuploaded the library as it is on github and the issue was fixed and I dont have a clue why tbh

**Comment by Herbycheck** [comment]
actually the current version on github hasnt been uploaded to the platformio registry by @glmnet  yet

**Comment by glmnet** [comment]
This change is ok with me, I'm not planning on maintaining that library. I would have liked development to continue on https://github.com/esphome/esphome/pull/2681 in an evolutive manner (merge as is and then improve, the branch was tested properly, but maintainers just didn't like the approach) as this platform is full of "corners" and having several libraries to be updated just makes it a lot harder.

**Pull request closed without merging**
