### PR TITLE
Don't stop effects if brightness goes to zero

### LINKED ISSUE #2296: Pulse Effect not working with RGBWW light
### The problem

The pulse effect is not working with the new lighting mode - I have an RGBWW light setup that I've just attempted to assign a pulse effect to - when turning on the effect the light goes out but doesn't pulse staying visibly off.  Logging shows that the pulse effect has been activated it just doesn't work - I've tried using just the white channels or RGB with no success as well as the standard and a custom pulse. 

### Which version of ESPHome has the issue?

1.21 dev

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

esp8285

### Component causing the issue

light

### Example YAML snippet

```yaml
light:
  - platform: rgbww
    name: ${display_name}
    red: output_red
    green: output_green
    blue: output_blue
    effects:
      - pulse:
          name: "pulsing"
          transition_length: 0.5s
          update_interval: 1s
    default_transition_length: 1s
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by oxan**
# What does this implement/fix? 

Fixes https://github.com/esphome/issues/issues/2296, regression from https://github.com/esphome/esphome/pull/2118.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
Makes sense in terms of the effects that turn the brightness down with a turn_on call... 
Could there be any other side effects to this?

**Comment by oxan** [comment]
> Could there be any other side effects to this?

I can't think of any. This also mimicks the behaviour there already was for years before I broke it in #2118.

**Comment by jesserockz** [comment]
Ah I see, so it got broken by this block that you moved:
```c++
  if (this->brightness_.has_value() && *this->brightness_ == 0.0f) {
    this->state_ = optional<float>(false);
    this->brightness_ = optional<float>(1.0f);
  }
```

**Comment by oxan** [comment]
> Ah I see, so it got broken by this block that you moved:

Yep.

**Pull request merged**
