### PR TITLE
SM16716 support

### PR DESCRIPTION
**Pull request by OttoWinter**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
Closing because SM16716 is apparently an addressable light - and fastled_spi seems to support it already.

**Comment by kll** [comment]
I disagree. You've missed the entire reason I implemented this in the first place. Using the fastled library does not allow me to get a single RGBWW device to show up for my Feit Electric A19 smart bulbs. The fastled library (unless something changed since I created the original PR) does not allow access to individual outputs that can be referenced from a light. The reason I implemented this was so I could get a single RGBWW device to show up.  The chip itself may technically be addressable but is used in a cheap and easy accessible smart bulb that many users want to use with esphome but does not function as intended when used with fastled. The only way to get it to work without this PR is to end up with distinct RGB and CWWW.

**Comment by OttoWinter** [comment]
Ok I didn't know that - I now have a faint memory of reading it in your PR description somewhere but I forgot that.

So, can you comment a bit more on how these smart bulbs work? Do they really use a single SM16716 chip? I mean it probably makes financial sense because they're probably quite cheap - though I'm not sure about the current a single chip can output.

If that's the case I don't have any objections against adding this/reopening the PRs.

**Comment by davericher** [comment]
This is actually the reason I want this to exist, Merkury a21 bulb, Currently have to have 1 PWM W, and a fast_led RGB, would love to combine those into a single RGBW, @kll if you end up figuring out, please share your config

**Comment by jokesters** [comment]
I've been waiting 3 months for this, yes the sm16716 is supported, but it's not supported to have the outputs to assign the colors to a single rgbw bulb so the only way to use it is to add the fastled_spi and a pwm for the white which ends up being 2 different bulbs. One for colors and one for white and if you accidentally have both on the bulb starts flashing after a while I believe due to overheating. I believe @kll was trying to add in the ability to create the red blue and green outputs to assign to a rgbw or rgbww bulb like the MY9231/MY9291 does. Wish I could help in making this happen but what you guys are doing is way over my head.

**Comment by kll** [comment]
@OttoWinter About the best I can do to explain how Feit Electric bulb works is to say that the warm white and cold white LEDs are connected to PWM outputs and the RGB LEDs are connected to the SM16716 chip. There are fewer of the RGB LEDs and their output is significantly less than the white LEDs. Here are the [FCC photos](https://fccid.io/SYW-A19RGBWAGT1/Internal-Photos/Internal-Photos-4018527) showing the inner workings.

@davericher I included a mostly working config in the original [esphome-docs PR](https://github.com/kll/esphome-docs/blob/f17e19e3474197b26251fe4ae0d0a9ad2f9225eb/components/output/sm16716.rst#feit-electric-a19-smart-wifi-bulb)
It shows up as a single bulb but esphome has independent brightness and white level controls with the brightness controlling the RGB and white level controlling the white LEDs so it is still a little hard to control and you can have all the LEDs on at once. I was going to try to tackle that by trying to figure out some way to automatically adjust one when the other was adjusted to ensure only one set was on at a time but life got in the way and I never got back around to it. As is it is still better than the two distinct bulbs showing up.

**Comment by OttoWinter** [comment]
@kll Thanks for the detailed response! Especially for the FCC photos, those helped a lot understanding this!

Ok, let's reinstate this PR then :)

**Comment by OttoWinter** [comment]
@kll So I think this PR and the docs are good now.

Could you try to test this PR and see if the docs are ok? (For testing: since 1.13 you can also create a custom_components folder in your esphome config folder; you can copy the sm16716 folder there to test without doing a dev esphome install)

If it's ok I'll merge

**Comment by kll** [comment]
@OttoWinter It looks ok to me. I've compiled and uploaded to my test bulb using version 1.13.1 and run it through the basic battery of tests and it seems fully functional. :+1:

**Comment by jokesters** [comment]
I installed the dev version of esphome and it compiled and flashed onto the bulb, it shows up and one bulb now, but all it does is turn on and off, the brightness slider doesn't do anything, the white value slider seems to dim it, and it doesn't chage colors. it have the merkery a21 bulb and its only a rgbw light, not like the Feit Electric A19 rgbww.  Im not sure if I did something wrong but I pretty much copied the documentation mentioned above with just leaving out the second pwm.  I'm still learning so it may be something I did, but wanted to share my experince so far.

**Comment by OttoWinter** [comment]
@jokesters Try turning it OFF and ON again (power cycling)

**Comment by davericher** [comment]
I was looking at something like this: 
http://codewelt.com/rgbw
and thinking we could probably do a on_value and adjust the brightness based on the color. Ideas? I would say the first 10% of the W channel adds quite a few 'colors' in my light, anything after the first 10% overpowers to the point of it is just white. This is also how the hues lights work (at least what is visible in my light strips)

**Comment by davericher** [comment]
A nice fix for a a random color effect:
```yaml
effects:
      - lambda:
          name: Random
          update_interval: 10s
          lambda: |-
            auto call = id(composition_light).turn_on();
            // Transtion of 1000ms = 1s
            call.set_transition_length(5000);
            call.set_white(0);
            call.set_rgb(random_float(), random_float(), random_float());
            call.set_brightness(100);
            call.perform();
```

**Comment by OttoWinter** [comment]
@davericher Problem with such a light platform would be that it depends highly on the white point of the channel.

**Comment by jokesters** [comment]
Well as I play around with it its not very reliable in it's behavior which seems strange to me. I unplugged it and plugged it in to power cycle it and then nothing worked except the on off switch. Then I reflashed the firmware and it started working for a while how it was working before with white value at zero I could see colors, brightness controlled color brightness then after a bit it stopped working so I power cycled it and it started working again doe a bit and stopped again..  power cycled again and still didn't work. Also it shuts off after a while if you have brightness and white value both at 100 for a while..  still testing to see if it will stay on with brightness at zero and white value 100..

**Comment by davericher** [comment]
Do you have the power supply pin set up for the color? If not it probably will not shut off that power draw even if the color lights are off

**Comment by jokesters** [comment]
Yeah I have the power supply pin set up.  I can get colors by turning the white value all the way down. If I have the white light on I bane to make sure to set the brightness to zero as it's controlling the color brightness and if both the white and color is on at same time it over heats and shuts off in like 10 min

**Pull request merged**
