### PR TITLE
Add configuration for cover topics

### PR DESCRIPTION
**Pull request by definitio**
# What does this implement/fix? 
This PR adds configuration for cover topics.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>
https://github.com/esphome/feature-requests/issues/321

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
https://github.com/esphome/esphome-docs/pull/1518

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
cover:
  - platform: ...
    position_state_topic: some/topic
    position_command_topic: some/topic
    tilt_state_topic: some/topic
    tilt_command_topic: some/topic
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — APPROVED** [review]
Please modify one of the tests to check these too

**Comment by definitio** [comment]
Done

**Comment by definitio** [comment]
Done

**Review by OttoWinter — APPROVED** [review]
Thanks!

**Pull request merged**
