### PR TITLE
Make dejitter optional for pulse_meter

### PR DESCRIPTION
**Pull request by hanzoh**
# What does this implement/fix? 

Adds dejitter as an optional configuration.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1180
  
# Test Environment

- [ ] ESP32
- [X] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
sensor:
  - platform: pulse_meter
    dejitter: False
```

# Explain your changes

Describe your changes here to communicate to the maintainers **why we should accept this pull request**.
Very important to fill if no issue linked

Some meters may lose accuracy, if their pulse widths are very short and they are truncated from microseconds to milliseconds.
This change adds and optional configuration with the default being True, so that it does not break any existing implementations.

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by frenck** [comment]
Why not expose the pulse width instead?

**Comment by stevebaxter** [comment]
Is this a real problem or a theoretical one? 

In my experience this is likely to give quite poor results, if you are at 1000 pulses/second then you may see significant swings in the value due to the very short pulse widths. You will also get 1000 readings a second sent to HA, which probably isn't what you want. At that speed you are probably better of using `pulse_counter` and averaging over several seconds.

**Comment by stevebaxter** [comment]
I'd advise understanding a bit more about exactly what problem this is trying to solve before accepting it.

**Comment by hanzoh** [comment]
I am using pulse_meter with a BL0937 sensor in a smart plug, as I got the best results with it. pulse_counter and pulse_width were giving me unsatisfactory results (low accuracy, low loads were basically undetectable).

When I tested the plug with higher loads, I found that the pulses/min got rounded to full thousands (for example 43000, 44000 etc), which results in jumping results when I apply the factor of 0.028 to calculate the power draw.
After removing the ```/ 1000```, I got much better results.

An example for a load of 29W:

before:
```
[20:44:56][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:44:57][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:44:58][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:44:58][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:00][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:00][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:00][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:00][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:01][D][sensor:099]: 'esp01_power': Sending state 983.60657 pulses/min with 2 decimals of accuracy
[20:45:01][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:02][D][sensor:099]: 'esp01_power': Sending state 983.60657 pulses/min with 2 decimals of accuracy
[20:45:02][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:03][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:03][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:03][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:03][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:04][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:04][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:05][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:05][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:06][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:06][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:06][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:06][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:07][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:07][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:07][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:07][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:08][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:08][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:09][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:09][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:09][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:09][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:10][D][sensor:099]: 'esp01_power': Sending state 983.60657 pulses/min with 2 decimals of accuracy
[20:45:10][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:10][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:10][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[20:45:11][D][sensor:099]: 'esp01_power': Sending state 1016.94916 pulses/min with 2 decimals of accuracy
[20:45:11][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
```

after:
```
[20:46:23][D][sensor:099]: 'esp01_power': Sending state 1034.46497 pulses/min with 2 decimals of accuracy
[20:46:23][D][sensor:099]: 'esp01_power': Sending state 1013.46216 pulses/min with 2 decimals of accuracy
[20:46:23][D][sensor:099]: 'esp01_power': Sending state 1007.60742 pulses/min with 2 decimals of accuracy
[20:46:23][D][sensor:099]: 'esp01_power': Sending state 1008.96295 pulses/min with 2 decimals of accuracy
[20:46:23][D][sensor:099]: 'esp01_power': Sending state 1012.79498 pulses/min with 2 decimals of accuracy
[20:46:23][D][sensor:099]: 'esp01_power': Sending state 1009.60809 pulses/min with 2 decimals of accuracy
[20:46:23][D][sensor:099]: 'esp01_power': Sending state 1004.57080 pulses/min with 2 decimals of accuracy
[20:46:23][D][sensor:099]: 'esp01_power': Sending state 1002.02075 pulses/min with 2 decimals of accuracy
[20:46:23][D][sensor:099]: 'esp01_power': Sending state 1006.17120 pulses/min with 2 decimals of accuracy
[20:46:23][D][sensor:099]: 'esp01_power': Sending state 1015.12537 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1012.24823 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1009.79498 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1002.99225 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 998.86792 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1005.39563 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1007.81055 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1007.60742 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1005.47986 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1006.77899 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1007.37061 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1002.79108 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1004.65491 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 1003.81451 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 998.45239 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 998.88458 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 993.88757 pulses/min with 2 decimals of accuracy
[20:46:24][D][sensor:099]: 'esp01_power': Sending state 996.13171 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1007.06622 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1008.72546 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1005.10931 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1003.78088 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1003.51227 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1008.64069 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1012.65820 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1006.32306 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1007.72589 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1009.94800 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1004.35217 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1002.77435 pulses/min with 2 decimals of accuracy
[20:46:25][D][sensor:099]: 'esp01_power': Sending state 1004.31854 pulses/min with 2 decimals of accuracy
```

I know that I will get much more results the higher the load is, so I just put a throttle or moving average filter in my yaml and it works great.

**Comment by hanzoh** [comment]
pulse_counter (which is also used by the hlw8012 component) gives even worse results:

```
[21:11:58][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:01][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:12:04][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:07][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:12:10][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:13][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:16][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:12:19][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:22][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:25][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:28][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:12:31][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:34][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:12:37][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:40][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:12:43][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:46][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:12:49][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:52][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:12:55][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:12:58][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:13:01][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:13:04][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:13:07][D][sensor:099]: 'esp01_power': Sending state 1020.00000 pulses/min with 2 decimals of accuracy
[21:13:10][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
[21:13:13][D][sensor:099]: 'esp01_power': Sending state 1000.00000 pulses/min with 2 decimals of accuracy
```

**Comment by hanzoh** [comment]
Any other feedback on this? Am I doing something wrong with the other integrations?

**Comment by OttoWinter** [comment]
> `pulse_counter` (which is also used by the hlw8012 component) gives even worse results:

Look at the data. It's jumping between 1000 and 1020 pulses/min, which in your 3s measurement interval is 50 and 51 pulses. You _can't_ get any more accurate than what you have there (only fake accuracy, by smoothing or the random timing jitter). The data that would allow you to distinguish in detail between the two different readings is not there.

You can increase the accuracy by sampling over longer time periods (gives lower update rate), or adding a `sliding_window_moving_average` filter (`window_size: 5; send_every: 1`)

**Comment by hanzoh** [comment]
Hm, this makes sense, but why am I getting correct results once I remove the dejitter from ```pulse_meter``` and apply a multiplier of 0.028 to get power in Watts?
The plug then reports accurate results for all kinds of loads (3W, 50W, 1.8kW).
With dejittering, I get huge jumps between values which are getting worse with higher loads.
The original firmware of the Gosund plugs was also able to provide similar detailed readings...

**Comment by OttoWinter** [comment]
> Hm, this makes sense, but why am I getting correct results once I remove the dejitter from pulse_meter and apply a multiplier of 0.028 to get power in Watts?

Hard to say but I'd guess some part of the system (maybe related to how it's measured) inadvertently adds some smoothing.

> The original firmware of the Gosund plugs was also able to provide similar detailed readings...

Was it able to do so instantaneously? As I said, if you add smoothing you get more accurate results, but sacrifice update speed.

**Pull request closed without merging**
