### PR TITLE
Constant brightness

### LINKED ISSUE #460: Choice in calculation method of cwww lights
**Describe the problem you have/What new integration you would like**

The brightness of CWWW lights are not constant when changing the color temperature. 
This is due to the current calculation method. 
 
```
/// Convert these light color values to an CWWW representation with the given parameters.
  void as_cwww(float color_temperature_cw, float color_temperature_ww, float *cold_white, float *warm_white) const {
    const float color_temp = clamp(this->color_temperature_, color_temperature_cw, color_temperature_ww);
    const float ww_fraction = (color_temp - color_temperature_cw) / (color_temperature_ww - color_temperature_cw);
    const float cw_fraction = 1.0f - ww_fraction;
    const float max_cw_ww = std::max(ww_fraction, cw_fraction);
    *cold_white = this->state_ * this->brightness_ * (cw_fraction / max_cw_ww);
    *warm_white = this->state_ * this->brightness_ * (ww_fraction / max_cw_ww);
  }
```
Changing the last three lines to 
```
*warm_white = this->state_ * this->brightness_ * ww_fraction ;
 *cold_white = this->state_ * this->brightness_  - *warm_white;
```

Ensures that the brightness of the light is constant over temperature changes.
This will result in smoother transitions between temperatures. As a side effect you won't be able to use the full brightness of your lights. 
So i would like a feature where the calculation method (constant brightness vs full brihgtness range) can be chosen.

**Please describe your use case for this integration and alternatives you've tried:**

My CWWW led strip "flashes" whenever I change colour temperature which I find disturbing.
I've tried adjusting the brightness depending on the colour but got stuck in an infinite loop. 

**Additional context**

https://github.com/esphome/issues/issues/780

### PR DESCRIPTION
**Pull request by kroimon**
## Description:

This is an update to PR #827 which fixes esphome/feature-requests#460.

I have a [Mi LED Desk Lamp](https://www.mi.com/global/smartlamp) that will reset due to overloading the power supply if both the white and warm white LEDs are on full power.
This fix allows for a very smooth light temperature change with constant brightness and ensures that the LEDs will never go above the maximum power rating of the power supply.

Tested and required to get my hardware working.

**Related issue (if applicable):** fixes esphome/feature-requests#460

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#530

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by Skaronator** [comment]
The bug I've mentioned in the PR from last year (https://github.com/esphome/esphome/pull/827#issuecomment-568590184) still exist. I just flashed the latest master branch on my light and was still able to reproduce it.

After some testing it turns out that the gamma correction isn't really accounted in the brightness calculation. With the default value you can notice the dip in brightness but when you cranking up the gamma_correct value to *40* then your light just goes out for a few second before turning on in the other color.

I made a quick video, the exposure is locked on the camera so it doesn't autoadjust: https://streamable.com/2h944w


Light Config:

```yaml

output:
  - platform: esp8266_pwm
    pin: 12
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    id: pwm_cw
  - platform: esp8266_pwm
    pin: 4
    id: pwm_ww

light:
  - platform: cwww
    name: "Deckenlicht Kurz"
    gamma_correct: 40
    cold_white: pwm_cw
    warm_white: pwm_ww
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    constant_brightness: true
  - platform: rgb
    name: "Deckenlicht Kurz RGB"
    gamma_correct: 1.5
    red: pwm_r
    green: pwm_g
    blue: pwm_b

```

**Comment by glmnet** [comment]
ahhh thanks for the video, this looks like a SW bug mostly, @kroimon can you give feedback on this one? are you experiencing the same behavior?

@Skaronator: I merged this because @kroimon said it was working, I did not test it. Also I see this does not break anything (i.e. there is no change to old behavior if contant_brightness is left untouched false.

Anyway, please open a new issue pointing the video and relevant attempts so we can move over it.

**Comment by Skaronator** [comment]
Alrighty I've created a issue and really hope this get fixed before the next release. Maybe I'll give it a try and debug it but I'm not a C developer so no promises here.

**Comment by kroimon** [comment]
Thanks for the issue, continuing discussion at esphome/issues#1133

**Pull request merged**
