### PR TITLE
ac_dimmer increase gate time for robotdyn

### LINKED ISSUE #1632: ac_dimmer component doesn't dim correctly using RobotDyn AC dimmer
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESPWROOM32
**ESPHome version (latest production, beta, dev branch)**

1.15.3
**Affected component:**

https://esphome.io/components/output/ac_dimmer.html?highlight=dimmer

**Description of problem:**
When using the ac_dimmer component in combination wit the RobotDyn AC dimmer the lamp has an irregular flicker. I use a dimmable LED lamp. Also a normal light bulb doesn't work. I live in the Netherlands so we have 230v at 50hz.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esp_test
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "***"
  password: "***"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp Test Fallback Hotspot"
    password: "***"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "***"

ota:
  password: "***"

# Enable Bluetooth scanning for this ESP32
# esp32_ble_tracker:

output:
  - platform: ac_dimmer
    id: dimmer1
    gate_pin: 22
    zero_cross_pin:
      number: 23
      mode: INPUT
      inverted: yes
    method: leading
    init_with_half_cycle: False
light:
  - platform: monochromatic
    output: dimmer1
    name: Dimmer test
```

**Logs (if applicable):**

```
NA

```

**Additional information and things you've tried:**
I have tried all the possible setting for the ac_dimmer component, but the shown configuration works best with the dimmable LED lamp. The normal light bulp has an even worse irregular flicker than the LED lamp using this configuration.

### PR DESCRIPTION
**Pull request by glmnet**
# What does this implement/fix? 

Increase gate time, created for people to test and give feedback, if proven to be useful it will be merged, so send feedback.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Configuration change (this will require users to update their yaml configuration files to keep working)

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/1632

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
  
# Test Environment

- [ ] ESP32
- [ ] ESP8266
- [ ] Windows
- [ ] Mac OS
- [ ] Linux

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

# Explain your changes

Describe your changes here to communicate to the maintainers **why we should accept this pull request**.
Very important to fill if no issue linked

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
Why not make it a config option?

**Comment by glmnet** [comment]
It's really not a big deal, I was expecting some feedback from the people facing the issue but nothing happened.
I'd say we just close this and see what happens.

**Comment by jougs** [comment]
Just for the record: I can't seem to see any reduction in flickering with this change in place.

**Comment by oxan** [comment]
@glmnet So, should this be closed or merged? I see conflicting opinions :)

**Comment by glmnet** [comment]
Ups. Yes we can merge this. Just need a comment explaining why the value is incremented. I'm on a phone now, so will do it when I see chance

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
