### PR TITLE
Allow Virtual Use of Timestamp

### PR DESCRIPTION
**Pull request by RebbePod**
I needed this for a personal project where I made a custom RealTimeClock component to get the sunset of a specific day. 
More details in this discord thread
https://discord.com/channels/429907082951524364/920057401900687431/920057665084854372

# What does this implement/fix? 

Quick description and explanation of changes

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by oxan** [comment]
> I needed this for a personal project where I made a custom RealTimeClock component to get the sunset of a specific day.

I didn't read through all of the (huge) Discord thread, but I don't think overriding the clock to return a fake date is the way to go about that. Instead, the sun class should be extended to support an `ESPTime` or `time_t` parameter, instead of always querying the current clock.

**Comment by RebbePod** [comment]
> I didn't read through all of the (huge) Discord thread, but I don't think overriding the clock to return a fake date is the way to go about that. Instead, the sun class should be extended to support an `ESPTime` or `time_t` parameter, instead of always querying the current clock.

I thought the same, but @ssieb mentioned we would then have to give the time every time we want some info from the sun (which is fine for me), I can see the potential advantage to having it automatic though.

Until such functionality is added can it hurt to add this request?

**Comment by oxan** [comment]
> I thought the same, but @ssieb mentioned we would then have to give the time every time we want some info from the sun (which is fine for me), I can see the potential advantage to having it automatic though.

I don't see how that's worse than having to give it the clock. In fact, I'd consider giving the time a much cleaner design that properly follows separation of concerns.

> Until such functionality is added can it hurt to add this request?

Well, there's a (small) performance/flash usage penalty because this class will gain a vtable, but more importantly I'm hesitant because nothing is as permanent as a temporary fix, and once it's there it'll get used which makes getting rid of it later on all the more difficult.

**Comment by RebbePod** [comment]
> Well, there's a (small) performance/flash usage penalty because this class will gain a vtable, but more importantly I'm hesitant because nothing is as permanent as a temporary fix, and once it's there it'll get used which makes getting rid of it later on all the more difficult.

Ok that makes sense. What will it take to add such functionality?

**Comment by oxan** [comment]
> Ok that makes sense. What will it take to add such functionality?

I took a look at that, and accidentally implemented all of it :sweat_smile: #2933

**Comment by RebbePod** [comment]
> > Ok that makes sense. What will it take to add such functionality?
> 
> I took a look at that, and accidentally implemented all of it 😅 #2933

Thank you very much, I'll have to try it out!

**Comment by OttoWinter** [comment]
Yeah this should be done on the sun side, making this function virtual could cause issues as the component expects the time to be supplied by the c library in some of the other functions

**Pull request closed without merging**
