### PR TITLE
Add on_initialized automation to tuya component

### PR DESCRIPTION
**Pull request by david-collett**
This trigger is called at completion of tuya initialisation.

# What does this implement/fix?

This patch adds an automation called at the completion of initialization of the tuya component.
It can be used for tasks such as setting tuya datapoints which cannot be done on esphome:on_boot
due to tuya being (possibly) uninitialised at that time.

**Note:** please review the change in tuya.cpp. I found that without the delay it did not work as intended, perhaps because the subsequent handle_datapoints reset the datapoints to those just received from the MCU, perhaps there is a better place to make this call without the timeout ?

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
tuya:
  on_initialized:
    then:
      - number.set:
          id: light_duration
          value: 35

number:
  - platform: tuya
    id: light_duration
    name: "Light Duration"
    number_datapoint: 104
    unit_of_measurement: "Seconds"
    min_value: 0
    max_value: 3600
    step: 1
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
I would take a guess and say it was not working as intended because the state changes to initialized as soon as the **first** datapoint report comes in. The 1s delay for the dump allows the rest of the datapoints to be reported.

**Comment by david-collett** [comment]
Ok, thanks. 

Are you happy with this solution? i.e. adding the delay to the initialization callback.

It is the only part of the patch that could cause a change in existing behavior. The initialization callback was already present (I just utilized it for this feature). It is used in two other places, fan and cover, to restore state. I don't think a small delay would cause a problem. In fact, I wonder if the existing uses could be subject to the same issue I seem to be experiencing without the delay.

Unfortunately I'm unable to attach a serial port and get early logging on startup to explore the issue further.

**Comment by jesserockz** [comment]
> Unfortunately I'm unable to attach a serial port and get early logging on startup to explore the issue further.

Yeah this is a issue for tuya devices. One way to solve it is to delay the first heartbeat which delays the init flow.

Its not ideal (the delay) but I don't really see another way around it, and you could even be right about the existing ones not working as intended.

I didnt actually realise tuya fans and cover had restore states, which might have changed my original argument for not putting it on number too. :laughing:

**Comment by david-collett** [comment]
I might have a look at implementing restore states then and see how that looks. I suspect tuya fan implements it because the base class does. Tuya cover probably does because I guess its a pretty useful feature for a cover.

**Comment by david-collett** [comment]
It was very little extra work to add support for "restore_value" (same as Template Number). Combined with "restore_from_flash: true" in the esp8266 section, this provides the desired behavior of persisting datapoint values across power cycles.
The initialized callback is still scheduled for a 1sec delay, as this was found to be necessary.

Please let me know if you'd like anything further, or would prefer a new pull-request!

**Pull request closed without merging**
