### PR TITLE
Add DMX512 component

### LINKED ISSUE #319: Dmx output component for light / fan
**Describe the problem you have/What new integration you would like**
I have some max485 that I use to create dmx device for my light dmx is cool because its a bus system and require only 1 esp to control it I would really like an integration into esphome

**Please describe your use case for this integration and alternatives you've tried:**
Add a dmx platform for controlling for example fan speed or light intesity/color
may be a config could look like this :
`
light:
  - platform: dmx
    start_address: 0
    channel_pattern: RGBW
    name: "TestDMX"
    output: output_component1

fan:
  - platform: dmx
    start_address: 0
    channel_pattern: D
    name: "TestDMX"
    output: output_component1
`
(D for dimmer) And I didn't try to use anything else for dimming the fan since I don't really like messing with high voltage

**Additional context**

### PR DESCRIPTION
**Pull request by nagyrobi**
# What does this implement/fix? 

Add support for DMX512 protocol from https://github.com/andyboeh/esphome-dmx512

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/319

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** https://github.com/esphome/esphome-docs/pull/1875

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
dmx512:
  id: dmx
  uart_id: uart_bus
  enable_pin: GPIO33
  tx_pin: GPIO5
  uart_num: 1
  periodic_update: true
  force_full_frames: false
  custom_break_len: 92
  custom_mab_len: 12
  update_interval: 500
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by andyboeh** [comment]
It's nice to see a PR, but just some fyi from my side:

 - One user reported that it crashes the ESP if >120 channels are defined. See https://github.com/andyboeh/esphome-dmx512/issues/11
 - In an attempt to fix it, I pushed support for limiting the frame rate to the DMX specification - this commit is not in your PR (and it didn't help)
 - This version is not safe from the millis()-call to wrap around. After about 45 days of uptime, DMX will most probably stop working. This has been fixed in the meantime - this commit is not in your PR.
 - Support for ESP32-IDF is relatively easy to add, I just haven't had the time to do so.
 - You are referencing my version on top. However, a lot of the code in my repository was taken from two other projects that I mention in the README:
    - https://github.com/cupertinomiranda/esphome
    - https://github.com/jakosek/esphome/tree/dmx_no_uart
  - Please remove me from codeowners. As mentioned, I do not have the necessary time to keep supporting the code and I didn't want to create the PR myself because of this. Hence, I don't want to be notified either.

**Comment by andyboeh** [comment]
@nagyrobi I hope you didn't close it because of my comment? Don't get me wrong, I very much appreciate the PR and I'm trying to support you - that's why I pointed out some issues that IMHO need to be resolved before it can be merged.

**Comment by nagyrobi** [comment]
It looks there are even more issues to be fixed in addition to what you mentioned (look at the Checks tab) - these are stuff I wouldn't like to do on my own, it's too much work required to be maintained in parallel with yours - it doesn't make sense like that.

You don't want this to me merged - understood, we'll try to keep using it as an external component.

**Comment by andyboeh** [comment]
> It looks there are even more issues to be fixed in addition to what you mentioned (look at the Checks tab)

I did that, I only saw some minor issues that need to be fixed once.

> You don't want this to me merged - understood, we'll try to keep using it as an external component.

So you really got me wrong! I absolutely want this to be merged! I'm trying to support you, but I can't support and/or maintain it.

**Comment by nagyrobi** [comment]
It doesn't really make sense... Also to put only myself on as a codeowner, while it's certain that I'm not the author, I can't take the responsibility on my own.

@jesserockz @OttoWinter @ssieb escalating this maybe you see it differently.

**Pull request closed without merging**
