### PR TITLE
Make docker use pip installed pillow

### LINKED ISSUE #4398: Docker: Pillow old version
### The problem

When adding BDF fonts (created in Fontforge) that use the 10646-1 codepage, ESPHome will hang (on Pillow), not allowing certain characters like the Euro symbol. All BDF fonts are interpreted as Latin-1 character sets only.  It may also have problems with Unicode TTF fonts.

I think this may have been fixed in recent versions of Pillow but after going into the container, I can see the version of Pillow is quite old and since it is system-owned, unsure how to update it.

Is my only way to update pillow by recreating the container myself?

### Which version of ESPHome has the issue?

2023.3.2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Board

ESP8266 / ESP32

### Component causing the issue

python pillow

### Example YAML snippet

```yaml
font: 
  - file: ehmtx/MatrixClock-Light8-Unicode.bdf #
    id: ehmtx_font
    glyphs:  |
      ! "#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz€
```

### Anything in the logs that might be useful for us?

```txt
This is while compiling for the EspHoMaTriX (ehmtx) project:

https://github.com/lubeda/EsphoMaTrix
```

### Additional information

You can try out this font here:

https://github.com/darkpoet78/MatrixClockFonts/blob/main/8-series/MatrixClock-Light8-Unicode.bdf

### PR DESCRIPTION
**Pull request by HeMan**
# What does this implement/fix?

Don't apt install pillow to make docker container use version from requirements_optional.txt

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4398

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — CHANGES_REQUESTED** [review]
Removing build dependencies in a different dockerfile line does not free the space they originally took in the image due to the way docker layers work.

**Comment by HeMan** [comment]
> Removing build dependencies in a different dockerfile line does not free the space they originally took in the image due to the way docker layers work.

It wasn't so much the space, it was more to keep similar content in the container after the change. Should I update the PR?

**Comment by jesserockz** [comment]
I don't think we even need those extra packages, I just built the image with `python-pil` removed and it still have pillow installed from requirements_optional correctly.

**Comment by HeMan** [comment]
> I don't think we even need those extra packages, I just built the image with `python-pil` removed and it still have pillow installed from requirements_optional correctly.

It's only the ARMv7 builds that need them, I'll update the Dockerfile to only install there.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
