### PR TITLE
Dont remove effect when turning light off

### PR DESCRIPTION
**Pull request by ryanwinter**
## Description:
Currently the effect is removed if the light is turned off. This patch will not remove the effect, but will not apply it if the remote state is off.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by ryanwinter** [comment]
Is there anything else I would need for this?

**Comment by oxan** [comment]
See also #1550 which implements the same functionality and has a bit more discussion.

**Comment by ryanwinter** [comment]
Ping to keep alive.

**Comment by oxan** [comment]
Based on discussion in #1550, I think this'll need to have an option `persist_effect` added to be accepted.

**Comment by ryanwinter** [comment]
> Based on discussion in #1550, I think this'll need to have an option `persist_effect` added to be accepted.

Thanks, let me merge in a update for that.

**Comment by ryanwinter** [comment]
Pinging alive.

**Pull request closed without merging**
