### PR TITLE
Add SSD1351 OLED display support

### PR DESCRIPTION
**Pull request by kbx81**
## Description:

Adds support for the SSD1351 OLED display.

Depends on #1050 for proper color support.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#663

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by kbx81** [comment]
Oh no @glmnet we introduced a small bug with image color processing in #1050. 😆 I have fixed it in this PR. Take a look at the diff and you may be able to work out what happened... 😏

The Python bits that create the image to be stored into the program memory were already converting it to 565. Then `draw_absolute_pixel_internal()` would convert it again, trashing the color. I modified the Python so it just stores it as 8-bit color and then the `to_rgb_565()` does the final conversion. I'll do something similar for grayscale in #1064.

I'll get docs done for this in the next day or so. 🙂

**Comment by glmnet** [comment]
This one looks Awesome!!

**Comment by glmnet** [comment]
@kbx81 can you deal with the conflicts?

**Comment by kbx81** [comment]
@glmnet yup! I'll get them cleaned up now. 😄

**Comment by kbx81** [comment]
All fixed up and re-tested @glmnet 😄

**Pull request merged**
