### PR TITLE
EntityBase: Move ObjectId to Flash 

### PR DESCRIPTION
**Pull request by Fabian-Schmidt**
# What does this implement/fix?

This is a memory improvement.
The `EntityBase` field `object_id_` can be pre-calculated in python and then stay in flash instead of being copied to memory as `std::string`. The calculation in python follows the same rules as the c++ code to ensure the resulting object id is the same. In python it is much easier to also validate two ids are unique (improvement idea).

Each `std::string` instance (even empty once) occupy at least 24 bytes (15 byte capacity + length + flags) of memory. By using char pointer instead of std::string they stay in flash.

The `object_id_` field has zero direct uses. Therefore no benefit of using an `std::string` here. In case any existing code is referencing this field it will break as the field was renamed.

In my projects I get easily more than 25 instances of `EntityBase`. In my testing I get ~1kb of more free memory by performing this change.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]

**Comment by jesserockz** [comment]
Lol, moving them into flash made the flash size too large for test3. 
I actually need to split that file up a bit, not much you can do in this PR

**Comment by Fabian-Schmidt** [comment]
While re checking all EntityBase client classes I found that Sprinkler was not using the common method `setup_entity` and therefore must be adjusted or else it would have no Object Id being set.

**Review by kbx81 — APPROVED** [review]
I _think_ the sprinkler change looks good, but @jesserockz knows Python better than me so it's probably best if he were to double-check. 😄

Looks like you also have a merge conflict to resolve. 😇

**Comment by jesserockz** [comment]
This is because Sprinkler is not an Entity. An Entity is only something that can be represented in HA - Sensor/Switch/Cover/Climate/etc

**Comment by jesserockz** [comment]
Oh I see Sprinkler extends EntityBase... 
Is there a reason for this @kbx81 as it doesnt really make sense unless it can be sent directly in the API to HA...

**Comment by kbx81** [comment]
@jesserockz a reason...is copy/paste a reason? 😆

This was the first time I created a new component, so I'm not surprised to come across architectural errors such as this. I agree, knowing what I know now, it doesn't really make sense to inherit from EntityBase since sprinkler itself is more or less a controller that automates other entities -- it doesn't represent an entity itself.

Totally fine by me if we trim some fat here. 😇

**Comment by Fabian-Schmidt** [comment]
Thanks @kbx81 . I removed the `EntityBase` as base class for sprinkler and moved the name locally. Looks like more was not used by Sprinkler from the base class.

**Comment by jesserockz** [comment]
It might pay to move the sprinkler changes to another PR to merge first as there are more required like adding CONF_NAME to the schema

**Comment by jesserockz** [comment]
https://github.com/esphome/esphome/pull/4606

**Review by jesserockz — APPROVED** [review]
Thanks for updating after my `name` changes

**Pull request merged**
