### PR TITLE
Add ADE7953 Support

### LINKED ISSUE #182: Support for ADE7953 energy monitoring chip (Shelly 2.5)
**Describe the problem you have/What new integration you would like**

ADE7953, the energy monitoring chip present on the [Shelly 2.5](https://shelly.cloud/shelly-25-wifi-smart-relay-roller-shutter-home-automation/)

**Please describe your use case for this integration and alternatives you've tried:**

[Support for Shelly 2.5](https://github.com/arendst/Sonoff-Tasmota/issues/5592#issuecomment-482049374)

**Additional context**

[Datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ADE7953.pdf)

### PR DESCRIPTION
**Pull request by OttoWinter**
## Description:

Usage:

```yaml
i2c:
  sda_pin: <SDA_PIN>
  scl_pin: <SCL_PIN>

sensor:
  - platform: ade7953
    voltage:
      name: ADE7953 Voltage
    current_a:
      name: ADE7953 Current A
    current_b:
      name: ADE7953 Current B
    active_power_a:
      name: ADE7953 Active Power A
    active_power_b:
      name: ADE7953 Active Power B
```

Normal/python users: check out this branch with git to test; hass.io users: Add "esphome_version": "ade7953" to your addon config

**Related issue (if applicable):** fixes https://github.com/esphome/feature-requests/issues/182#issuecomment-497913701

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by gervaso** [comment]
Hi, as requested on the discord channel I tried to compile with this version, but after adding the "platform: ad7953" section I get the following error:

`Couldn't resolve ID for type 'uart::UARTComponent'.`

**Comment by gervaso** [comment]
Hello, I'm getting this error now, I don't know if it's just a typo in the code:

```
src/main.cpp:24:1: error: 'ace7953' does not name a type
ace7953::ADE7953 *ace7953_ade7953;
^
src/main.cpp: In function 'void setup()':
src/main.cpp:254:3: error: 'ace7953_ade7953' was not declared in this scope
ace7953_ade7953 = new ace7953::ADE7953();
^
src/main.cpp:254:25: error: expected type-specifier before 'ace7953'
ace7953_ade7953 = new ace7953::ADE7953();
^
src/main.cpp:254:25: error: expected ';' before 'ace7953'
*** [/data/shellylaundry/.pioenvs/shellylaundry/src/main.cpp.o] Error 1
```

**Comment by gervaso** [comment]
I confirm that both the compile and the upload worked without any problems, after the last fix in the code.

**Comment by gervaso** [comment]
Two more small issues:
the "a" and "b" values on the sensors names appear to be inverted, at least on the shelly 2.5, "current_a" and "power_a" are connected to the "O2" and the "b" sensors are connected to the "O1".

The volt and ampere readings are correct, the watts are negative so they should be multiplied by -1.0

**Comment by OttoWinter** [comment]
@gervaso Thanks for testing!

Yes, I saw some other implementations deliberately switched A and B channels so that the values display correctly. But the values you see are what the sensor reports - the manufacturer of the device just wired them up differently (probably because it would fit better on PCB).

Same goes for negative power reading - that depends on how the chip is wired up. The value seen here is as the sensor reports it. You can use a sensor multiply filter for it.

**Comment by gervaso** [comment]
@OttoWinter ok, I thought that could be the case, thanks for your feedback. Now I only have to sort the thermal sensor stuff out, and I would like to contribute some documentation on the shelly 2.5 device.

Unfortunately I can't find any info on the circuit in order to input the correct values for the resistor dropdown.

**Comment by erdii** [comment]
@gervaso You can ask the shelly team on facebook. I could also ask, if you don't have facebook. Just tell me what you need. :)

**Comment by gervaso** [comment]
> @gervaso You can ask the shelly team on facebook. I could also ask, if you don't have facebook. Just tell me what you need. :)

Basically I need the values to put into this sensor: https://esphome.io/components/sensor/ntc.html and I need to know how the circuit is wired in order to properly set the "Resistance Sensor" needed for it to work.

**Comment by erdii** [comment]
@gervaso I'll see what I can find out but I will be gone for the next two weeks.

**Comment by mblakleyiii** [comment]
> > @gervaso You can ask the shelly team on facebook. I could also ask, if you don't have facebook. Just tell me what you need. :)
> 
> Basically I need the values to put into this sensor: https://esphome.io/components/sensor/ntc.html and I need to know how the circuit is wired in order to properly set the "Resistance Sensor" needed for it to work.

Obviously, getting the info directly from Shelly will be best but I took a shot in the dark based on the Tasmota code. Here is the NTC yaml I have currently for my Shelly 2.5. Unfortunately, I don't have a laser thermometer to validate the readings but they seem pretty plausible to me.

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "ADE7953 Temp"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K # (25C)
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

**Comment by gervaso** [comment]
> > > @gervaso You can ask the shelly team on facebook. I could also ask, if you don't have facebook. Just tell me what you need. :)
> > 
> > 
> > Basically I need the values to put into this sensor: https://esphome.io/components/sensor/ntc.html and I need to know how the circuit is wired in order to properly set the "Resistance Sensor" needed for it to work.
> 
> Obviously, getting the info directly from Shelly will be best but I took a shot in the dark based on the Tasmota code. Here is the NTC yaml I have currently for my Shelly 2.5. Unfortunately, I don't have a laser thermometer to validate the readings but they seem pretty plausible to me.
> 
> ```yaml
> sensor:
>   - platform: ntc
>     sensor: temp_resistance_reading
>     name: "Shelly 2.5 Temp"
>     calibration:
>       b_constant: 3350
>       reference_resistance: 10kOhm
>       reference_temperature: 298.15K # (25C)
>   - platform: resistance
>     id: temp_resistance_reading
>     sensor: temp_analog_reading
>     configuration: DOWNSTREAM
>     resistor: 32kOhm
>   - platform: adc
>     id: temp_analog_reading
>     pin: A0
> ```

I can confirm that it's working well. I had pulled out the same information from the tasmota source code, but I didn't notice that I was feeding the ntc sensor with the wrong input... my bad.

So, in general I can confirm that this integration works well. I'll try to write some device-specific documentation in the next days, thanks everyone for the help and feedback.

**Comment by Lumpusz** [comment]
This looks very interesting, and I am also looking forward to this, as I own a few Shelly 2.5s. When can we expect this PR to be merged and released in a stable version?

**Pull request merged**
