### PR TITLE
Add mqtt.on_connect and mqtt.on_disconnect triggers

### PR DESCRIPTION
**Pull request by jimtng**
# What does this implement/fix?

Add mqtt.on_connect and mqtt.on_disconnect triggers

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** partially addresses esphome/feature-requests#746

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2105

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
mqtt:
  on_connect:
    - logger.log: "Yay! We're connected!"
  on_disconnect:
    - logger.log: "Bah! Disconnected again!"
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder). Add the on_connect / on_disconnect to test3.yaml

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nagyrobi** [comment]
Wow, finally!

**Comment by nagyrobi** [comment]
Would be nice to work together with https://github.com/esphome/feature-requests/issues/375

Then we could have a nice way to implement certain redundancy methods for data exchange between nodes, when HA/API is down...

**Comment by jimtng** [comment]
> Would be nice to work together with [esphome/feature-requests#375](https://github.com/esphome/feature-requests/issues/375)
> 
> Then we could have a nice way to implement certain redundancy methods for data exchange between nodes, when HA/API is down...

esphome/feature-requests#375 is a different issue and should be addressed in a different PR.

**Comment by nagyrobi** [comment]
Yes of course I was just thinking what pieces are missing from the puzzle.

**Review by jesserockz — APPROVED** [review]
All looks good except the unrelated formatting changes in the test file.

**Comment by jimtng** [comment]
> All looks good except the unrelated formatting changes in the test file.

@jesserockz Thank you for reviewing this. I have removed the unrelated formatting changes in the test file.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
