### PR TITLE
add template fan

### PR DESCRIPTION
**Pull request by ssieb**
# What does this implement/fix?

This adds a template fan including adding the necessary triggers to the base fan component.
It also reverts the optional output change from https://github.com/esphome/esphome/pull/6274.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#3655

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nagyrobi** [comment]
Will presets of the template fan be independent from speed values?

Eg ability to just have presets like `Auto`, `Manual`, independent of speed...

**Comment by ssieb** [comment]
Everything is independent.  You can do whatever you want with the presets.  Although I did see that changing any setting resets the preset back to no preset.  But that's either HA or the base fan component.

**Comment by nagyrobi** [comment]
> Everything is independent. You can do whatever you want with the presets. Although I did see that changing any setting resets the preset back to no preset. But that's either HA or the base fan component.

Yes that's the problem. Manual is when you'd adjust by hand.
Auto would be when speed would be set by some sensor etc.
And you could of course have some fixed values too as shortcuts.

Don't think it's HA...

**Comment by ssieb** [comment]
I think presets need a bit of work, but that's not for this PR.

**Comment by nagyrobi** [comment]
https://github.com/esphome/esphome/pull/6112

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
