### PR TITLE
Add Gas device class to DSMR component

### PR DESCRIPTION
**Pull request by frenck**
# What does this implement/fix? 

This adds the device class `gas` to the DSMR component, making it work with the new Gas features of the Energy Dashboard coming in Home Assistant 2021.9

⚠️ This PR might be considered for the beta, as HA & ESPHome releases are out of sync + this change is backward compatible.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
This will fail to validate as the `DEVICE_CLASS_GAS` does not pass the validation in `sensor/__init__.py`

**Comment by frenck** [comment]
@jesserockz I just noticed IRL :D

**Comment by jesserockz** [comment]
Related #2164

**Review by jesserockz — APPROVED** [review]

**Comment by frenck** [comment]
@jesserockz This PR actually closes #2164, as that PR is incorrect.

**Pull request merged**
