### PR TITLE
[esp32] Use pioarduino + IDF 5.1.5 as default for IDF builds

### PR DESCRIPTION
**Pull request by kbx81**
# What does this implement/fix?

Based on a number of discussions ([here](https://github.com/esphome/esphome/pull/7419#issuecomment-2395073751) and [here](https://github.com/espressif/arduino-esp32/discussions/10039), to call out a couple), we need to move away from using Platformio's officially provided packages for the build platform & ESP-IDF. This PR builds support for using the [pioarduino](https://github.com/pioarduino) forks for newer (5.1+) IDF versions while maintaining support for using older (pre-5.1) IDF versions we may still wish to support. In time, this can be extended to include support for Arduino 3.x, as well.

See also the discussion on #7419; this PR supersedes #7419.

**Note:**

This PR sets the default IDF version to 5.1.5 (for configurations where IDF is specified) -- ~~note that this depends on an official [release by pioarduino](https://github.com/pioarduino/esp-idf/releases) which is not _yet_ available. For now, I have modified the base test files to use version [`5.1.4.241024`](https://github.com/pioarduino/esp-idf/releases/tag/v5.1.4.241024) to confirm tests will all pass. I will remove this modification to the base test files once a `5.1.5` release is available.~~

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code quality improvements to existing code or addition of tests
- [x] Other

**Related issue or feature (if applicable):**

- fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):**

- esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Example entry for `config.yaml`:

These are a number of combinations I've tried building with to exercise the changes to the `esp32` component in this PR:

```yaml
# Example config.yaml
esp32:
  board: esp32dev
  # board: esp32-c3-devkitm-1
  # board: esp32-s3-devkitc-1
  # framework:
  #   type: esp-idf
  # framework:
  #   type: esp-idf
  #   version: 4.4.8
  #   platform_version: 5.4.0
  # framework:
  #   type: esp-idf
  #   version: 5.1.2
  #   platform_version: 6.5.0
  # framework:
  #   type: esp-idf
  #   version: 5.1.4
  #   release: "241024"
  #   platform_version: 51.03.06
  # framework:
  #   type: esp-idf
  #   version: 5.1.4
  #   source: https://github.com/pioarduino/esp-idf/releases/download/v5.1.4.241024/esp-idf-v5.1.4.zip
  #   platform_version: https://github.com/pioarduino/platform-espressif32/releases/download/51.03.06/platform-espressif32.zip
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by Jason2866** [comment]
@kbx81 Released pioarduino IDF 5.1.5

**Comment by Jason2866** [comment]
A note from my side as maintainer of pioarduino. IDF 5.1.x is not the version I would develop.
espressif has moved to IDF 5.3.x as base for there actual Arduino. The Arduino core 3.0.x is already in service status. Active development is only done in branch `release/v3.1.x` which is based on IDF 5.3.x  So imho a good idea to port code directly to this version. The changes are not so many

**Comment by edwardtfn** [comment]
I've just tested (with v5.1.4) and this will solve this old issue:
- esphome/issues#3769

**Review by jesserockz — APPROVED** [review]

**Comment by luar123** [comment]
Awesome, Thank you!

**Comment by edwardtfn** [comment]
So, as I understood, if everything goes right, v2024.12 will be using ESP-IDF v5.1.5 as default when esp-idf framework is selected...
Is that right?

**Comment by kbx81** [comment]
> So, as I understood, if everything goes right, v2024.12 will be using ESP-IDF v5.1.5 as default when esp-idf framework is selected... Is that right?

That's correct @edwardtfn

**Pull request merged**
