### PR TITLE
substitutions: Don't warn when passwords look like a substitution

### LINKED ISSUE #3712: Wifi Password containing causes error when installing updates
### The problem

After recently changing my wifi password I can no longer update my esp32 boards. After updating esphome secrets with new password,  Validation completes with warning and completes the initial upload to the board. after reboot board will not connect to wifi. all boards where running fine for weeks before changing my wifi password.

Validation warnings included along with secrets file.

**secrets file:**
```yaml
# Your Wi-Fi SSID and password
wifi_ssid: "TaxGuest"
wifi_password: 'TaxGuest$2022'
```

**validation log:**
```
INFO Reading configuration /config/esphome/esp32-bluetooth-proxy-28d188.yaml...
WARNING Found 'TaxGuest$2022' (see wifi->password) which looks like a substitution, but '2022' was not declared
WARNING Found 'TaxGuest$2022' (see wifi->password) which looks like a substitution, but '2022' was not declared
INFO Configuration is valid!
substitutions:
  name: esp32-bluetooth-proxy-28d188
  wifi_ap_password: ''
esphome:
  name: esp32-bluetooth-proxy-28d188
  name_add_mac_suffix: false
  project:
    name: esphome.bluetooth-proxy
    version: '1.0'
  build_path: .esphome/build/esp32-bluetooth-proxy-28d188
  platformio_options: {}
  includes: []
  libraries: []
  min_version: 2022.10.0
esp32:
  board: esp32dev
  framework:
    version: 1.0.6
    source: ~3.10006.0
    platform_version: platformio/espressif32 @ 3.5.0
    type: arduino
  variant: ESP32
wifi:
  ap:
    password: ''
    ap_timeout: 1min
  domain: .local
  reboot_timeout: 15min
  power_save_mode: LIGHT
  fast_connect: false
  networks:
  - ssid: TaxGuest
    password: TaxGuest$2022
    priority: 0.0
  use_address: esp32-bluetooth-proxy-28d188.local
api:
  port: 6053
  password: ''
  reboot_timeout: 15min
logger:
  baud_rate: 115200
  tx_buffer_size: 512
  deassert_rts_dtr: false
  hardware_uart: UART0
  level: DEBUG
  logs: {}
ota:
  safe_mode: true
  port: 3232
  reboot_timeout: 5min
  num_attempts: 10
improv_serial: {}
captive_portal: {}
dashboard_import:
  package_import_url: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
    duration: 5min
    continuous: true
bluetooth_proxy:
  active: true
button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic
  disabled_by_default: false
  icon: mdi:restart-alert
  device_class: restart
```

### Which version of ESPHome has the issue?

2022.10.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.0

### What platform are you using?

ESP32

### Board

generic

### Component causing the issue

validation installation of updates

### Example YAML snippet

_No response_

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tljuniper**
# What does this implement/fix?

While checking the yaml configuration, the current implementation prints passwords to the console when they contain `$`:

```bash
WARNING Found '$wifi-password' (see wifi->password) which looks like a substitution, but 'wifi' was not declared
WARNING Found 'test$ota-password' (see ota->password) which looks like a substitution, but 'ota' was not declared
```

This simply checks for the string "password" anywhere in the path and doesn't print the warning then.

I'm unsure if this warrants a documentation update or if we need further tests for this. This is my first PR in this repo, let me know if I need to change something else about it.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):**

This issue discusses the passwords but suggests changing the passwords rather than updating the code:
fixes https://github.com/esphome/issues/issues/3712

Related [discussion in HA Forum](https://community.home-assistant.io/t/warning-found-see-wifi-password-which-looks-like-a-substitution-but-b7-was-not-declared/373129)

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
substitutions:
  existing_substitution: test-substitution

esphome:
  name: ${existing_substitution}

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: test$ota-password

text_sensor:
  - platform: version
    name: ${missing_substitution_2}
```

`secrets.yaml`

```yaml
wifi_ssid: the-ssid
wifi_password: $wifi-password
```

Without change:

```bash
$ esphome config test_config.yaml
INFO Reading configuration test_config.yaml...
WARNING Found '$wifi-password' (see wifi->password) which looks like a substitution, but 'wifi' was not declared
WARNING Found 'test$ota-password' (see ota->password) which looks like a substitution, but 'ota' was not declared
WARNING Found '${missing_substitution_2}' (see text_sensor->0->name) which looks like a substitution, but 'missing_substitution_2' was not declared
WARNING Found '$wifi-password' (see wifi->password) which looks like a substitution, but 'wifi' was not declared
WARNING Found 'test$ota-password' (see ota->password) which looks like a substitution, but 'ota' was not declared
WARNING Found '${missing_substitution_2}' (see text_sensor->0->name) which looks like a substitution, but 'missing_substitution_2' was not declared
INFO Configuration is valid!
...
```

With change:

```bash
$ esphome config test_config.yaml
INFO Reading configuration test_config.yaml...
WARNING Found '${missing_substitution_2}' (see text_sensor->0->name) which looks like a substitution, but 'missing_substitution_2' was not declared
WARNING Found '${missing_substitution_2}' (see text_sensor->0->name) which looks like a substitution, but 'missing_substitution_2' was not declared
INFO Configuration is valid!
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by jesserockz** [comment]
This could affect any string value that could potentially have $ in the value, its not going to be only passwords.

And honestly, all passwords really should be using secrets, not plain text or substitutions

**Comment by tljuniper** [comment]
Thanks for taking a look!

> This could affect any string value that could potentially have $ in the value, its not going to be only passwords.

Not sure I understand, can you elaborate? We *want* the warning to occur for non-password values because in these cases it's likely that the user made a typo or forgot to declare a substitution somehow. But for passwords, it's much more likely that the password just contains a $ and the config is correct. The fix in this MR only affects password-ish fields.

> And honestly, all passwords really should be using secrets, not plain text or substitutions

Agreed. Sadly, even passwords that are stored as a secret are printed to console right now (the wifi password in the example above), so using secrets doesn't fix the issue.

**Comment by TrentHouliston** [comment]
The ideal way to do this (no idea how) would be to have a list of all the secrets and check the strings to see if they are in that list, so nothing that is a secret gets printed

**Comment by tljuniper** [comment]
> The ideal way to do this (no idea how) would be to have a list of all the secrets and check the strings to see if they are in that list, so nothing that is a secret gets printed

Yeah, that list would be nice. When replacing substitutions, the secrets have already been resolved, so at this point we don't know what used to be a secret anymore. I guess checking against the original list would be possible but that also seems quite complex and hacky.

But even if users choose not to use a secret for storing their passwords (for whatever reason), we should not be printing out that password.

I'm hoping that this PR is a decent compromise for now. It really creeps me out to see that password on the console whenever I build anything :sweat_smile:

**Comment by tljuniper** [comment]
Hi @jesserockz, any chance of getting this merged?

**Comment by jesserockz** [comment]
> Yeah, that list would be nice. When replacing substitutions, the secrets have already been resolved, so at this point we don't know what used to be a secret anymore. I guess checking against the original list would be possible but that also seems quite complex and hacky.

ESPHome already does this when printing out the validated config. So the secrets are already in memory in two dicts for reverse lookup.

**Comment by sunshiros** [comment]
I think this happens on devices that have not been flashed the first time while plugged in to the computer. For example a tasmota smart plug or a sonoff DUALR3 . For me this used to happen on d1 mini when flashed OTA but after i flashed by usb this warning was removed. 

Any idea when this will be fixed so we can use password with $ ?

**Comment by jesserockz** [comment]
> I think this happens on devices that have not been flashed the first time while plugged in to the computer. For example a tasmota smart plug or a sonoff DUALR3 . For me this used to happen on d1 mini when flashed OTA but after i flashed by usb this warning was removed.
> 
> Any idea when this will be fixed so we can use password with $ ?

Its only a warning... The existing code will not stop you using a $ in a password

**Pull request merged**
