### PR TITLE
Add TM1651 simple level, turn on, turn off actions

### PR DESCRIPTION
**Pull request by freekode**
## Description:
Added new actions setting level, turn on and turn off for TM1651.
Fixed brightness validation
Updated library to new version

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#442

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by freekode** [comment]
Maybe someone can do review?

**Comment by glmnet** [comment]
Looking good, can you update docs for turn on and turn off?

**Comment by freekode** [comment]
Fixed

**Comment by glmnet** [comment]
Thanks!

**Pull request merged**
