### PR TITLE
Heartbeat LED Initial commit

### PR DESCRIPTION
**Pull request by justlikeef**
## Description:
Heartbeat LED provides external status that the base loop is actually running by slowly blinking an led.

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#941

## Checklist:
  - [X] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by ssieb** [comment]
The description mentions "slowing blinking", but the actual effect looks more like a strobe.
I think it would be better to add this as an option to the status_led instead of making a new component.
e.g. `heartbeat: true` with a default of `false`.  And only show the heartbeat when it's not otherwise showing a fault.

**Comment by glmnet** [comment]
Thanks for your contribution, but this component does not qualify for merging into ESPHome code base. I'm afraid there is not a strict rule to this, but here are some general guidelines:

* Particularly this code does not interact with any specific hardware, this is a red flag already, e.g. a sensor, a display etc.
* This code also does not provide any communication api either, e.g. http, canbus, etc.
* This code can be easily replaced by a ESPHome automation, and you can easily reuse that code with packages.
* You can however write a Cookbook guide on how to do this so it is easily accessible in the main docs page, it will be a good example for using `custom_components`

I hope you understand, actually I made almost the same error in one of my first contributions: https://github.com/esphome/feature-requests/issues/139 

I'm leaving this open for other contributors feedback

**Comment by justlikeef** [comment]
I think combining it in to status LED introduces complexity that doesn't need to be there.  For instance, I don't want the error led and the status led to be the same, so now I have to introduce a parameter that sets what I want this LED to do (status, error, etc), and have to support multiple entries in the component/yaml instead of just having a simple pin as a parameter.  I think the KISS principal applies to most programming.

I don't think it should be done with an automation because you are, once again, adding complexity to a critical function.  Especially with the number of bugs around state and automations executing that have occurred in the past.  Visual heartbeat is a critical function for acceptance into most professional automation environments so that a technician can do a visual inspection.  It needs to be base simple to insure that it just runs, even if logic is broken.  Not having a module that does this communicates, IMHO, that this project is not serious.

**Comment by justlikeef** [comment]
> The description mentions "slowing blinking", but the actual effect looks more like a strobe.
> I think it would be better to add this as an option to the status_led instead of making a new component.
> e.g. `heartbeat: true` with a default of `false`. And only show the heartbeat when it's not otherwise showing a fault.

The heartbeat uses the "slow blink" code from the status led, so the effect is the same as has been already accepted with the description that has been accepted.

I don't want the LED to be the same because green=good/red=bad

**Comment by glmnet** [comment]
Indeed, changing the status light is not desired. All I said before stays though.

**Comment by justlikeef** [comment]
> Indeed, changing the status light is not desired. All I said before stays though.

The other think I ran into with an automation is the millions of state changes published to HA.  Is there a way to turn off the state changes without jumping through hoops?

**Comment by glmnet** [comment]
> The other think I ran into with an automation is the millions of state changes published to HA. Is there a way to turn off the state changes without jumping through hoops?

`internal: true` (or set an `id` and omit the `name`) this would however cause the component to not be seen in HA at all

**Comment by justlikeef** [comment]
> > The other think I ran into with an automation is the millions of state changes published to HA. Is there a way to turn off the state changes without jumping through hoops?
> 
> `internal: true` (or set an `id` and omit the `name`) this would however cause the component to not be seen in HA at all

As a component, it's not seen either.

Outside of not having a heartbeat function meaning it won't be used in most professional environments, I'll be happy to move it to a custom component and not have it available to others.  Making a critical function an automation is not something I think is a good idea.

**Comment by justlikeef** [comment]
> I don't see the difference. If the automation fails, the light stops blinking and obviously there's a problem. However, are you also aware that if the main loop gets stuck, that the device will very quickly reboot due to the WDT?

Automations in ESPHome have repeatedly failed while the main loop was still running because of bugs in the automation code or the light code.  The difference between automations working or not working and the base loop working or not working are not the same.  The more complexity there is, the more likelihood that something is going to fail.

There are plenty of ways that the base loop can get stuck or delayed without it rebooting.  That's why a core heartbeat function is a base requirement of PLCs in most professional environments.

**Pull request closed without merging**
