### PR TITLE
Correct BME680 gas calculation and heater_off

### LINKED ISSUE #3966: BME680 Heater Off wont work
### The problem

I wanted to set up a temperature sensor for Home Assistant, so I tested two sensors: the BME280 and the BME680. The BME680 had a slightly higher temperature than the BME280. I thought maybe it was the gas sensor and the heater, so I wanted to turn it off, but when I set the duration to 0ms, the log says that the heater is off, but the sensor does not output any values. If I do not turn off the heater I get values.

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.12.8

### What platform are you using?

ESP32

### Board

nodemcu

### Component causing the issue

bme680

### Example YAML snippet

```yaml
esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERY_VERBOSE

captive_portal:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:
  - platform: bme680
    i2c_id: bus_a
    temperature:
      name: "BME680 Temperature"
      oversampling: 16x
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    heater:
      duration: 0ms
    address: 0x77
    iir_filter: 127x
    update_interval: 5s
```

### Anything in the logs that might be useful for us?

```txt
[03:13:43][C][logger:293]: Logger:
[03:13:43][C][logger:294]:   Level: VERY_VERBOSE
[03:13:43][C][logger:295]:   Log Baud Rate: 115200
[03:13:43][C][logger:296]:   Hardware UART: UART0
[03:13:44][C][i2c.arduino:052]: I2C Bus:
[03:13:44][C][i2c.arduino:053]:   SDA Pin: GPIO21
[03:13:44][C][i2c.arduino:054]:   SCL Pin: GPIO22
[03:13:44][C][i2c.arduino:055]:   Frequency: 50000 Hz
[03:13:44][C][i2c.arduino:058]:   Recovery: bus successfully recovered
[03:13:44][I][i2c.arduino:068]: Results from i2c bus scan:
[03:13:44][I][i2c.arduino:074]: Found i2c device at address 0x77
[03:13:44][C][bme680.sensor:209]: BME680:
[03:13:44][C][bme680.sensor:210]:   Address: 0x77
[03:13:44][C][bme680.sensor:214]:   IIR Filter: 127x
[03:13:44][C][bme680.sensor:215]:   Update Interval: 5.0s
[03:13:44][C][bme680.sensor:217]:   Temperature 'BME680 Temperature'
[03:13:44][C][bme680.sensor:217]:     Device Class: 'temperature'
[03:13:44][C][bme680.sensor:217]:     State Class: 'measurement'
[03:13:44][C][bme680.sensor:217]:     Unit of Measurement: '°C'
[03:13:44][C][bme680.sensor:217]:     Accuracy Decimals: 1
[03:13:44][C][bme680.sensor:218]:     Oversampling: 16x
[03:13:44][C][bme680.sensor:219]:   Pressure 'BME680 Pressure'
[03:13:44][C][bme680.sensor:219]:     Device Class: 'pressure'
[03:13:44][C][bme680.sensor:219]:     State Class: 'measurement'
[03:13:44][C][bme680.sensor:219]:     Unit of Measurement: 'hPa'
[03:13:44][C][bme680.sensor:219]:     Accuracy Decimals: 1
[03:13:44][C][bme680.sensor:220]:     Oversampling: 16x
[03:13:44][C][bme680.sensor:221]:   Humidity 'BME680 Humidity'
[03:13:44][C][bme680.sensor:221]:     Device Class: 'humidity'
[03:13:44][C][bme680.sensor:221]:     State Class: 'measurement'
[03:13:44][C][bme680.sensor:221]:     Unit of Measurement: '%'
[03:13:44][C][bme680.sensor:221]:     Accuracy Decimals: 1
[03:13:44][C][bme680.sensor:222]:     Oversampling: 16x
[03:13:44][C][bme680.sensor:223]:   Gas Resistance 'BME680 Gas Resistance'
[03:13:44][C][bme680.sensor:223]:     State Class: 'measurement'
[03:13:44][C][bme680.sensor:223]:     Unit of Measurement: 'Ω'
[03:13:44][C][bme680.sensor:223]:     Accuracy Decimals: 1
[03:13:44][C][bme680.sensor:223]:     Icon: 'mdi:gas-cylinder'
[03:13:44][C][bme680.sensor:225]:   Heater OFF
[03:13:44][C][captive_portal:088]: Captive Portal:
[03:13:44][C][mdns:103]: mDNS:
[03:13:44][C][mdns:104]:   Hostname: -
[03:13:44][V][mdns:105]:   Services:
[03:13:44][V][mdns:107]:   - _esphomelib, _tcp, 6053
[03:13:44][V][mdns:109]:     TXT: version = 2022.12.3
[03:13:44][V][mdns:109]:     TXT: mac = 34865dfc3f08
[03:13:44][V][mdns:109]:     TXT: platform = ESP32
[03:13:44][V][mdns:109]:     TXT: board = esp32dev
[03:13:44][V][mdns:109]:     TXT: network = wifi
[03:13:44][C][ota:093]: Over-The-Air Updates:
[03:13:44][C][ota:094]:   Address: -.local:3232
[03:13:44][C][ota:097]:   Using Password.
[03:13:44][C][api:138]: API Server:
[03:13:44][C][api:139]:   Address: l-.local:6053
[03:13:44][C][api:141]:   Using noise encryption: YES
[03:13:47][VV][scheduler:196]: Running interval 'update' with interval=5000 last_execution=9513 (now=14513)
[03:13:47][VV][i2c.arduino:140]: 0x77 TX 74B5
[03:13:47][VV][i2c.arduino:164]: TX failed: not acknowledged
[03:13:47][D][api:102]: Accepted ::FFFF:10.0.1.1
[03:13:47][VV][api.socket:693]: ::FFFF:10.0.1.1: Handshake complete!
[03:13:47][VV][api.service:434]: on_hello_request: HelloRequest {
  client_info: 'Home Assistant 2022.12.8'
  api_version_major: 1
  api_version_minor: 7
}
[03:13:47][V][api.connection:900]: Hello from client: 'Home Assistant 2022.12.8 (::FFFF:10.0.1.1)' | API Version 1.7
[03:13:47][VV][api.service:013]: send_hello_response: HelloResponse {
  api_version_major: 1
  api_version_minor: 7
  server_info: 'leon-zimmer-test-2 (esphome v2022.12.3)'
  name: 'leon-zimmer-test-2'
}
[03:13:47][VV][api.service:443]: on_connect_request: ConnectRequest {
  password: ''
}
[03:13:47][D][api.connection:918]: Home Assistant 2022.12.8 (::FFFF:10.0.1.1): Connected successfully
[03:13:47][VV][api.service:019]: send_connect_response: ConnectResponse {
  invalid_password: NO
}
[03:13:47][VV][api.service:488]: on_device_info_request: DeviceInfoRequest {}
[03:13:47][VV][api.service:049]: send_device_info_response: DeviceInfoResponse {
  uses_password: NO
  name: 'leon-zimmer-test-2'
  mac_address: '34:86:5D:FC:3F:08'
  esphome_version: '2022.12.3'
  compilation_time: 'Dec 26 2022, 03:12:49'
  model: 'esp32dev'
  has_deep_sleep: NO
  project_name: ''
  project_version: ''
  webserver_port: 0
  bluetooth_proxy_version: 0
  manufacturer: 'Espressif'
}
[03:13:47][VV][api.service:497]: on_list_entities_request: ListEntitiesRequest {}
[03:13:47][VV][api.service:132]: send_list_entities_sensor_response: ListEntitiesSensorResponse {
  object_id: 'bme680_temperature'
  key: 3640870636
  name: 'BME680 Temperature'
  unique_id: 'leon-zimmer-test-2sensorbme680_temperature'
  icon: ''
  unit_of_measurement: '°C'
  accuracy_decimals: 1
  force_update: NO
  device_class: 'temperature'
  state_class: STATE_CLASS_MEASUREMENT
  legacy_last_reset_type: LAST_RESET_NONE
  disabled_by_default: NO
  entity_category: ENTITY_CATEGORY_NONE
}
[03:13:47][VV][api.service:132]: send_list_entities_sensor_response: ListEntitiesSensorResponse {
  object_id: 'bme680_pressure'
  key: 1365279611
  name: 'BME680 Pressure'
  unique_id: 'leon-zimmer-test-2sensorbme680_pressure'
  icon: ''
  unit_of_measurement: 'hPa'
  accuracy_decimals: 1
  force_update: NO
  device_class: 'pressure'
  state_class: STATE_CLASS_MEASUREMENT
  legacy_last_reset_type: LAST_RESET_NONE
  disabled_by_default: NO
  entity_category: ENTITY_CATEGORY_NONE
}
[03:13:48][VV][api.service:132]: send_list_entities_sensor_response: ListEntitiesSensorResponse {
  object_id: 'bme680_humidity'
  key: 1277562889
  name: 'BME680 Humidity'
  unique_id: 'leon-zimmer-test-2sensorbme680_humidity'
  icon: ''
  unit_of_measurement: '%'
  accuracy_decimals: 1
  force_update: NO
  device_class: 'humidity'
  state_class: STATE_CLASS_MEASUREMENT
  legacy_last_reset_type: LAST_RESET_NONE
  disabled_by_default: NO
  entity_category: ENTITY_CATEGORY_NONE
}
[03:13:48][V][component:200]: Component api took a long time for an operation (0.05 s).
[03:13:48][V][component:201]: Components should block for at most 20-30ms.
[03:13:48][VV][api.service:132]: send_list_entities_sensor_response: ListEntitiesSensorResponse {
  object_id: 'bme680_gas_resistance'
  key: 426116527
  name: 'BME680 Gas Resistance'
  unique_id: 'leon-zimmer-test-2sensorbme680_gas_resistance'
  icon: 'mdi:gas-cylinder'
  unit_of_measurement: 'Ω'
  accuracy_decimals: 1
  force_update: NO
  device_class: ''
  state_class: STATE_CLASS_MEASUREMENT
  legacy_last_reset_type: LAST_RESET_NONE
  disabled_by_default: NO
  entity_category: ENTITY_CATEGORY_NONE
}
[03:13:48][VV][api.service:055]: send_list_entities_done_response: ListEntitiesDoneResponse {}
[03:13:48][VV][api.service:506]: on_subscribe_states_request: SubscribeStatesRequest {}
[03:13:48][VV][api.service:568]: on_subscribe_homeassistant_services_request: SubscribeHomeassistantServicesRequest {}
[03:13:48][VV][api.service:140]: send_sensor_state_response: SensorStateResponse {
  key: 3640870636
  state: nan
  missing_state: YES
}
[03:13:48][VV][api.service:595]: on_subscribe_home_assistant_states_request: SubscribeHomeAssistantStatesRequest {}
[03:13:48][VV][api.service:140]: send_sensor_state_response: SensorStateResponse {
  key: 1365279611
  state: nan
  missing_state: YES
}
[03:13:48][VV][api.service:140]: send_sensor_state_response: SensorStateResponse {
  key: 1277562889
  state: nan
  missing_state: YES
}
[03:13:48][VV][api.service:140]: send_sensor_state_response: SensorStateResponse {
  key: 426116527
  state: nan
  missing_state: YES
}
[03:13:52][VV][scheduler:196]: Running interval 'update' with interval=5000 last_execution=14513 (now=19520)
[03:13:52][VV][i2c.arduino:140]: 0x77 TX 74B5
[03:13:52][VV][i2c.arduino:164]: TX failed: not acknowledged
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by CarlosGS**
# What does this implement/fix?

Gas readings in BME680 (not BSEC) had some odd jumps when crossing specific ranges, see the picture:

Screenshot_20230301_231724

Following the manufacturer's implementation in https://github.com/boschsensortec/BME68x-Sensor-API, there were some differences in variable types and operations. These are the main points:
- Static value 14 instead of the correct `data[14]`, see https://github.com/esphome/esphome/pull/4498/files#diff-b65ea512f7983fa91e88a19a48db0ace8f8266ec44c689f4f8b8cba7e2d36477L303
- Incorrectly writing the heater flag, see https://github.com/esphome/esphome/pull/4498/files#diff-b65ea512f7983fa91e88a19a48db0ace8f8266ec44c689f4f8b8cba7e2d36477L184
- Some conversions were missing in the setup https://github.com/esphome/esphome/pull/4498/files#diff-b65ea512f7983fa91e88a19a48db0ace8f8266ec44c689f4f8b8cba7e2d36477R125-R137
- Improved value reporting & error handling by @DAVe3283
- The first few readings upon a power cycle were wrong, taking a while to converge. It turns out we were missing a check for heater stability https://github.com/esphome/esphome/pull/4498/files#diff-b65ea512f7983fa91e88a19a48db0ace8f8266ec44c689f4f8b8cba7e2d36477R317-R333 (Datasheet: _The heater operation could be speeded up by setting an initial heater current for a target heater temperature by using register idac_heat_x<7:0>. This step is optional since the control loop will find the current after a few iterations anyway._).

Screenshot_20230307_000338

All fixed :tada: Marking as **breaking change** because users may need to adjust their parameters.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/3966

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by CarlosGS** [comment]
This is done, but I'm going to give it a couple of days. Please test with:
```yaml
external_components:
  - source: github://carlosgs/esphome@patch-43
    components:
      - bme680
```

**Comment by DAVe3283** [comment]
Running this I can confirm that it resolves the problem when the heater is set to 0ms (disabled). Still logging data to see if there are any discontinuities with the new code.

I like the added checks for heater stability and valid reading. One thing I would request is you have the gas sensor return NAN on invalid readings and set the warning state. Otherwise, it is publishing known incorrect readings that pollute Home Assistant history.

Since you are fixing this up anyway, right at the beginning of the read_data_() function, it silently just gives up if the registers can't be read. IMO that should also publish NAN for all sensors and set warning (or error even) for the component. As it is, there is no indication (even in the logs) that something is wrong besides noticing the last update was some time ago.

<details>
<summary>example</summary>

```c++
void BME680Component::read_data_() {
  uint8_t data[15];
  if (!this->read_bytes(BME680_REGISTER_FIELD0, data, 15)) {
    if (this->temperature_sensor_ != nullptr)
      this->temperature_sensor_->publish_state(NAN);
    if (this->pressure_sensor_ != nullptr)
      this->pressure_sensor_->publish_state(NAN);
    if (this->humidity_sensor_ != nullptr)
      this->humidity_sensor_->publish_state(NAN);
    if (this->gas_resistance_sensor_ != nullptr)
      this->gas_resistance_sensor_->publish_state(NAN);
    ESP_LOGW(TAG, "Communication with BME680 failed!"); // or log error 
    this->status_set_warning(); // or set error
    return;
  }
  this->status_clear_warning();
  // also clear error if using error above

  uint32_t raw_temperature = (uint32_t(data[5]) << 12) | (uint32_t(data[6]) << 4) | (uint32_t(data[7]) >> 4);
  uint32_t raw_pressure = (uint32_t(data[2]) << 12) | (uint32_t(data[3]) << 4) | (uint32_t(data[4]) >> 4);
  uint32_t raw_humidity = (uint32_t(data[8]) << 8) | uint32_t(data[9]);
  uint16_t raw_gas = (uint16_t)((uint32_t) data[13] * 4 | (((uint32_t) data[14]) / 64));
  uint8_t gas_range = data[14] & 0x0F;

  float temperature = this->calc_temperature_(raw_temperature);
  float pressure = this->calc_pressure_(raw_pressure);
  float humidity = this->calc_humidity_(raw_humidity);
  float gas_resistance = this->calc_gas_resistance_(raw_gas, gas_range);

  bool gas_valid = (data[14] >> 5) & 1;
  bool heat_stable = (data[14] >> 4) & 1;

  ESP_LOGD(TAG, "Got temperature=%.1f°C pressure=%.1fhPa humidity=%.1f%% gas_resistance=%.1fΩ", temperature, pressure,
           humidity, gas_resistance);
  if (!gas_valid)
    ESP_LOGW(TAG, "Gas measurement unsuccessful, reading invalid!");
  if (!heat_stable)
    ESP_LOGW(TAG, "Heater unstable, reading invalid! (Normal for a few readings after a power cycle)");

  if (this->temperature_sensor_ != nullptr)
    this->temperature_sensor_->publish_state(temperature);
  if (this->pressure_sensor_ != nullptr)
    this->pressure_sensor_->publish_state(pressure);
  if (this->humidity_sensor_ != nullptr)
    this->humidity_sensor_->publish_state(humidity);
  if (this->gas_resistance_sensor_ != nullptr) {
    if (gas_valid && heat_stable) {
      this->gas_resistance_sensor_->publish_state(gas_resistance);
    } else {
      this->status_set_warning();
      this->gas_resistance_sensor_->publish_state(NAN);
    }
  }
}
```
</details>

**Review by DAVe3283 — APPROVED** [review]
I still see a small discontinuity at 2.8-2.9kΩ:
image

The new Bosch reference code supports the BME688, and introduces an alternate method of measuring gas resistance. The new method is selected by reading the register `BME68X_REG_VARIANT_ID` (`0xF0`), which presumably indicates BME680 vs BME688. My BME680 reads as 0 (`BME68X_VARIANT_GAS_LOW`), which uses the original formula still.

I can't see any difference in how this is calculating resistance compared to the Bosch sample, so I can't explain the discontinuity.

With the discontinuity being so small, and the other big improvements made, I think this is good to go. The issue could well be the sensor itself or the Bosch formula.

**Comment by CarlosGS** [comment]
This was missing https://github.com/esphome/esphome/pull/4498/commits/6d0cca6eaab3e9b26573bdf345e90e16021d925c :tada:

Thanks for testing so promptly, and for your improvements to the PR :)

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
