### PR TITLE
Swap ADC back to use 'int' because C3

### LINKED ISSUE #4711: Unable to compile ADC for esp32-c3
### The problem

Since esphome version 2023.7.0 I get this error when compiling the ADC sensor.
I have tried cleaning the build files but the problem persists.

```
INFO ESPHome 2023.7.0
INFO Reading configuration /config/adc-esp32c3.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing adc-esp32c3 (board: esp32-c3-devkitm-1; framework: arduino; platform: platformio/espressif32@5.3.0)
--------------------------------------------------------------------------------
Library Manager: Installing esphome/AsyncTCP-esphome @ 1.2.2
INFO Installing esphome/AsyncTCP-esphome @ 1.2.2
Unpacking  [####################################]  100%
Library Manager: AsyncTCP-esphome@1.2.2 has been installed!
INFO AsyncTCP-esphome@1.2.2 has been installed!
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
INFO Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
Unpacking  [####################################]  100%
Library Manager: ESPAsyncWebServer-esphome@2.1.0 has been installed!
INFO ESPAsyncWebServer-esphome@2.1.0 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/noise-c @ 0.1.4
INFO Installing esphome/noise-c @ 0.1.4
Unpacking  [####################################]  100%
Library Manager: noise-c@0.1.4 has been installed!
INFO noise-c@0.1.4 has been installed!
Library Manager: Resolving dependencies...
INFO Resolving dependencies...
Library Manager: Installing esphome/libsodium @ 1.10018.1
INFO Installing esphome/libsodium @ 1.10018.1
Unpacking  [####################################]  100%
Library Manager: libsodium@1.10018.1 has been installed!
INFO libsodium@1.10018.1 has been installed!
HARDWARE: ESP32C3 160MHz, 320KB RAM, 4MB Flash
 - toolchain-riscv32-esp @ 8.4.0+2021r2-patch5
Dependency Graph
|-- AsyncTCP-esphome @ 1.2.2
|-- WiFi @ 2.0.0
|-- FS @ 2.0.0
|-- Update @ 2.0.0
|-- ESPAsyncWebServer-esphome @ 2.1.0
|-- DNSServer @ 2.0.0
|-- ESPmDNS @ 2.0.0
|-- noise-c @ 0.1.4
Compiling .pioenvs/adc-esp32c3/src/esphome/components/adc/adc_sensor.cpp.o
Compiling .pioenvs/adc-esp32c3/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/adc-esp32c3/src/esphome/components/api/api_frame_helper.cpp.o
Compiling .pioenvs/adc-esp32c3/src/esphome/components/api/api_pb2.cpp.o
src/esphome/components/adc/adc_sensor.cpp: In member function 'virtual float esphome::adc::ADCSensor::sample()':
src/esphome/components/adc/adc_sensor.cpp:164:55: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
       adc2_get_raw(channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw);
                                                       ^~~~
In file included from src/esphome/components/adc/adc_sensor.h:10,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
/config/.esphome/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/driver/include/driver/adc.h:381:81: note:   initializing argument 3 of 'esp_err_t adc2_get_raw(adc2_channel_t, adc_bits_width_t, int*)'
 esp_err_t adc2_get_raw(adc2_channel_t channel, adc_bits_width_t width_bit, int *raw_out);
                                                                            ~~~~~^~~~~~~
src/esphome/components/adc/adc_sensor.cpp:196:53: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
     adc2_get_raw(channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw11);
                                                     ^~~~~~
In file included from src/esphome/components/adc/adc_sensor.h:10,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
/config/.esphome/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/driver/include/driver/adc.h:381:81: note:   initializing argument 3 of 'esp_err_t adc2_get_raw(adc2_channel_t, adc_bits_width_t, int*)'
 esp_err_t adc2_get_raw(adc2_channel_t channel, adc_bits_width_t width_bit, int *raw_out);
                                                                            ~~~~~^~~~~~~
src/esphome/components/adc/adc_sensor.cpp:199:55: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
       adc2_get_raw(channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw6);
                                                       ^~~~~
In file included from src/esphome/components/adc/adc_sensor.h:10,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
/config/.esphome/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/driver/include/driver/adc.h:381:81: note:   initializing argument 3 of 'esp_err_t adc2_get_raw(adc2_channel_t, adc_bits_width_t, int*)'
 esp_err_t adc2_get_raw(adc2_channel_t channel, adc_bits_width_t width_bit, int *raw_out);
                                                                            ~~~~~^~~~~~~
src/esphome/components/adc/adc_sensor.cpp:202:57: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
         adc2_get_raw(channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw2);
                                                         ^~~~~
In file included from src/esphome/components/adc/adc_sensor.h:10,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
/config/.esphome/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/driver/include/driver/adc.h:381:81: note:   initializing argument 3 of 'esp_err_t adc2_get_raw(adc2_channel_t, adc_bits_width_t, int*)'
 esp_err_t adc2_get_raw(adc2_channel_t channel, adc_bits_width_t width_bit, int *raw_out);
                                                                            ~~~~~^~~~~~~
src/esphome/components/adc/adc_sensor.cpp:205:59: error: invalid conversion from 'int32_t*' {aka 'long int*'} to 'int*' [-fpermissive]
           adc2_get_raw(channel2_, ADC_WIDTH_MAX_SOC_BITS, &raw0);
                                                           ^~~~~
In file included from src/esphome/components/adc/adc_sensor.h:10,
                 from src/esphome/components/adc/adc_sensor.cpp:1:
/config/.esphome/platformio/packages/framework-arduinoespressif32/tools/sdk/esp32c3/include/driver/include/driver/adc.h:381:81: note:   initializing argument 3 of 'esp_err_t adc2_get_raw(adc2_channel_t, adc_bits_width_t, int*)'
 esp_err_t adc2_get_raw(adc2_channel_t channel, adc_bits_width_t width_bit, int *raw_out);
                                                                            ~~~~~^~~~~~~
*** [.pioenvs/adc-esp32c3/src/esphome/components/adc/adc_sensor.cpp.o] Error 1
========================== [FAILED] Took 6.42 seconds ==========================
```

### Which version of ESPHome has the issue?

2023.7.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.7.2

### What platform are you using?

ESP32

### Board

ESP32C3 (Lolin C3 Mini)

### Component causing the issue

adc

### Example YAML snippet

```yaml
esphome:
  name: adc-esp32c3
  friendly_name: adc-esp32c3

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***************************************"

ota:
  password: "*************************************"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Adc-Esp32C3 Fallback Hotspot"
    password: "**********"

captive_portal:

sensor:
  - platform: adc
    pin: GPIO4
    name: "Voltaje módulo Lluvia"
    id: "lluvia_analogica"
    attenuation: auto
    unit_of_measurement: "V"
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by kbx81**
# What does this implement/fix?

Fixes https://github.com/esphome/issues/issues/4711

...also adds a test for the ADC on the C3.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/issues/issues/4711

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [x] ESP32 IDF (ESP32 + ESP32-C3)
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by Noltari** [comment]
It's working now on my ESP32-C3, thanks @kbx81!

**Comment by kbx81** [comment]
Thanks for confirming @Noltari! 😄

**Review by Noltari — APPROVED** [review]
LGTM

**Comment by CarlosGS** [comment]
There was some discussion in https://github.com/esphome/issues/issues/3564
Maybe there's a way to tackle this at a higher level with the patch proposed in that thread?

Edit: Seems Tasmota solved it with a global define https://github.com/arendst/Tasmota/blob/development/include/esp32x_fixes.h#L34-L38

**Review by CarlosGS — APPROVED** [review]

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
