### PR TITLE
[remote_transmitter] accurate pulse timing for ESP8266

### PR DESCRIPTION
**Pull request by CarlosGS**
# What does this implement/fix?

This is a refactor of Remote transmitter for ESP8266 to provide more accurate timing.
Instead of using incremental calls to delayMicroseconds(), accuracy is now dictated by the internal `micros()` clock.
The output timing should now be much closer to ESP32's hardware implementation.

```
# Test code: 10us square wave
remote_transmitter.transmit_raw:
  code: [10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10,-10,10]
```

Before/after. Please excuse the crudity of the oscilloscope. **Look at the X axis for the crossing time of rising/falling edges.**
 

Note the duty cycle is now correct/square. This first change is simple (https://github.com/esphome/esphome/pull/2476/commits/d0c410d379ebb4f715389de84d8c5eac0f036828).

However, the waves measure more than 10us (almost double!) and we want to provide accurate timing.
**This is solved by using micros() as the timing reference, instead of incrementally calling delayMicroseconds().**

New timing code: (Look at the X axis for the 10us crossing time of rising/falling edges.)

Now timing is fully preserved :)

It could be considered a breaking change because a correct timing could affect installations that already include compensating offsets in their ESP8266 RF/IR codes.
However, if the raw signals are generated with ESPHome's internal IR/RF code libs (as in most cases), or measured with `remote_receiver`, this fix should simply generate signals that better match the original. And the output accuracy is now comparable to ESP32's implementation.

## Types of changes

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** likely fixes timing discrepancy issues, i.e. https://github.com/esphome/issues/issues/1216, https://github.com/esphome/issues/issues/1216, https://community.home-assistant.io/t/esphome-rf-receiver-transmitter-issues/222331, https://github.com/esphome/issues/issues/1370, etc

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [X] ESP8266

## Checklist:
  - [X] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

### CODE REVIEW

**Comment by CarlosGS** [comment]
This is done :)
I've verified it with a NEC IR remote (38khz 50% duty cycle, 560/1690us pulses) and an RF transmitter (100% duty cycle, 400/800us pulses). You can try with:
```yaml
external_components:
  - source: github://carlosgs/esphome@patch-3
    components: [remote_transmitter]
```

It is technically a breaking change as the output signals are adjusted. However, the timing is now accurate and matches ESP32. This consistency should help in the long term.

**Comment by CarlosGS** [comment]
This is done :)
I've verified it with a NEC IR remote (38khz 50% duty cycle, 560/1690us pulses) and an RF transmitter (100% duty cycle, 400/800us pulses). You can try with:
```yaml
external_components:
  - source: github://carlosgs/esphome@patch-3
    components: [remote_transmitter]
```
The timing is now accurate and matches ESP32. This consistency should help in the long term.

**Comment by CarlosGS** [comment]
Work in progress:

1. ~Tackle what happens when users define pulses that are too long, because it could cause WiFi dropouts or even trigger the watchdog timer.~ This will be fixed with https://github.com/esphome/esphome/pull/2497
2. Remove the `InterruptLock`, which was only necessary in the previous bit-banged approach. We now use relative timing that corrects for any interrupt delays. In the codebase, there is only one interruption that feels "too long for comfort" [(SoftwareSerialRX)](https://github.com/esphome/esphome/blob/aec02afcdc36d0c626db727d27dd46888c2578de/esphome/components/uart/uart_component_esp8266.cpp#L199-L223) however, it seems reasonable that serial has priority over the microsecond accuracy of these pulses.

**Comment by CarlosGS** [comment]
This is ready for review :smile:

- Note: PR awaiting https://github.com/esphome/esphome/pull/2497 before merging this one.
Otherwise you can test this by first installing that branch with: `pip3 install https://github.com/CarlosGS/esphome/archive/refs/heads/patch-5.zip`

The ESP8266 transmitter has been refactored to allow sending TX pulses with very accurate timing.
As with ESP32 this code is now robust to interruptions, so a board can read its own pulses, i.e. it can debug itself :)

Test 1: fine timing
-
<details>
<summary>Click to expand Test 1 code</summary>

```yaml
esphome:
  name: nodemcutest
  platform: ESP8266
  board: esp01_1m

external_components:
  - source: github://carlosgs/esphome@patch-3
    components: [remote_transmitter]

logger:

remote_receiver:
  pin: GPIO4
  dump: raw
  filter: 0us # allow reading pulses <50us

remote_transmitter:
  pin:
    number: GPIO5
  carrier_duty_percent: 50%

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    inverted: true
  id: thebutton
  on_press:
    - remote_transmitter.transmit_raw:
        carrier_frequency: 50kHz
        code: [100,-100,100,-100,100]
```
</details>

Pressing the on-board button triggers sending out the pulses.
Signal is `[100,-100,100,-100,100]` with `carrier_frequency: 50kHz` (i.e. three sets of 5x10us pulses)

Before: (notice the inaccurate 50kHz & overall timing lag)
 

New implementation:
 

If you bridge GPIO5 & GPIO4, the board can even read its own pulses. Here are a couple runs:
Received Raw: 14, -13, 10, -9, 9, -9, 10, -9, 9, -101, 9, -9, 11, -10, 11, -9, 9, -11, 10, -110, 9, -12, 9, -9, 11, -9, 12, -9, 11
Received Raw: 14, -13, 10, -9, 9, -9, 10, -9, 9, -105, 9, -9, 11, -10, 11, -9, 9, -11, 10, -110, 9, -12, 9, -9, 11, -9, 12, -9, 9


There is some jitter at this fine scale, but as expected they are all close to 10,-10 and -110.
It's pretty much bang-on considering we're at the limit of what ESP8266 can do.

Test 2: IR/RF protocols
-
ESPHome implements a variety of manufacturer protocols. We can also test them:

<details>
<summary>Click to expand Test 2 code</summary>

```yaml
remote_receiver:
  pin: GPIO4
  dump: all

remote_transmitter:
  pin:
    number: GPIO5
  carrier_duty_percent: 100% # change to 50% if using IR transmitter (the receiver demodulates 38kHz)

binary_sensor:
- platform: gpio
  pin:
    number: GPIO0
    inverted: true
  id: thebutton
  on_press:
    - remote_transmitter.transmit_jvc:
        data: 0x1234
    - delay: 100ms
    - remote_transmitter.transmit_lg:
        data: 0x20DF10EF # power on/off
        nbits: 32
    - delay: 100ms
    - remote_transmitter.transmit_midea:
        code: [0xA2, 0x08, 0xFF, 0xFF, 0xFF]
    - delay: 100ms
    - remote_transmitter.transmit_nec:
        address: 0x1234
        command: 0x78AB
    - delay: 100ms
    - remote_transmitter.transmit_sony:
        data: 0x123
        nbits: 12
    - delay: 100ms
    - remote_transmitter.transmit_rc5:
        address: 0x1F
        command: 0x3F
    - delay: 100ms
    - remote_transmitter.transmit_samsung:
        data: 0x1FEF05E4
    # additional example for 48-bit codes:
    - delay: 100ms
    - remote_transmitter.transmit_samsung:
        data: 0xB946F50A09F6
        nbits: 48
    - delay: 100ms
    - remote_transmitter.transmit_samsung36:
        address: 0x0400
        command: 0x000E00FF
    - delay: 100ms
    - remote_transmitter.transmit_panasonic:
        address: 0x1FEF
        command: 0x1F3E065F
    - delay: 100ms
    - remote_transmitter.transmit_dish:
        address: 1
        command: 16
    - delay: 100ms
    - remote_transmitter.transmit_pioneer:
        rc_code_1: 0xA556
        rc_code_2: 0xA506
        repeat:
          times: 2
    - delay: 100ms
    - remote_transmitter.transmit_toshiba_ac:
        rc_code_1: 0xB24DBF4040BF
        rc_code_2: 0xD5660001003C
    - delay: 100ms
    - remote_transmitter.transmit_rc_switch_raw:
        code: '001010011001111101011011'
        protocol: 1
    - delay: 100ms
    - remote_transmitter.transmit_rc_switch_type_a:
        group: '01001'
        device: '10110'
        state: off
        protocol: 1
    - delay: 100ms
    - remote_transmitter.transmit_rc_switch_type_b:
        address: 2
        channel: 3
        state: off
        protocol: 1
    - delay: 100ms
    - remote_transmitter.transmit_rc_switch_type_c:
        family: 'C'
        group: 3
        device: 1
        state: off
        protocol: 1
    - delay: 100ms
    - remote_transmitter.transmit_rc_switch_type_d:
        group: 'c'
        device: 1
        state: off
        protocol: 1
```
</details>

This code sends every implemented protocol, and uses `dump: all` to decode anything received.
Running this results in a list of successfully decoded protocols. Some are mixed up between manufacturers, I think because they are identical bitwise.

Conclusion
-
This code takes ESP8266 transmitter much closer to ESP32's hardware implementation.
It should fix some of the issues that users find when swapping code between platforms. Let me know what you think, cheers!

**Comment by cmroche** [comment]
> This is done :) I've verified it with a NEC IR remote (38khz 50% duty cycle, 560/1690us pulses) and an RF transmitter (100% duty cycle, 400/800us pulses). You can try with:
> 
> ```yaml
> external_components:
>   - source: github://carlosgs/esphome@patch-3
>     components: [remote_transmitter]
> ```
> 
> The timing is now accurate and matches ESP32. This consistency should help in the long term.

I just wanted to chime in and mention that I tested this as well, and it also solved a problem I was having with my Gree Thermopump where IR commands were not working from ESPHome specifically until I applied this patch. Then, worked perfectly.

ESP8226 (D1 Mini)

**Comment by hcoohb** [comment]
> This is done :) I've verified it with a NEC IR remote (38khz 50% duty cycle, 560/1690us pulses) and an RF transmitter (100% duty cycle, 400/800us pulses). You can try with:
> 
> ```yaml
> external_components:
>   - source: github://carlosgs/esphome@patch-3
>     components: [remote_transmitter]
> ```
> 
> The timing is now accurate and matches ESP32. This consistency should help in the long term.

Hi @CarlosGS,

I have tried your code and I am afraid, my custom component based on daikin climate stopped working... :disappointed:
It may have to do as it is one of the only component that is using a long call to delay_microseconds_accurate. It has a long space of 32300us.
It has already broke in the past see #1465 where I tried to fix things.

I haven't yet had the chance to debug a bit better and see what is going on.
Maybe your code actually fix inaccuracies and now my timings are slightly off...
But have you been able to confirm that long spaces of up to 32ms are correctly handled too?

Using, esp8266 (D1 mini) with esphome 2021.10.3 and your patch3
Thanks

**Comment by CarlosGS** [comment]
@hcoohb Thanks for testing! Your use case is specially important due to the long delay, so I'd appreciate if you can test the "full" patch that accounts for this:

If you use the command line you can setup https://github.com/esphome/esphome/pull/2497 with the instructions in https://github.com/esphome/esphome/pull/2476#issuecomment-952188362.
Or, if you are using the Home Assistant plugin, you can install the ESPHome (dev) plugin and add this option:
Screenshot_20211109_083504
That will install the specific patch for delayMicroseconds().

And with that installed, then you can test the new remote_transmitter with the external_components method you used before. Let me know if you need any help in the process, cheers!

**Comment by CarlosGS** [comment]
@hcoohb Ah, the new delayMicroseconds has just been merged https://github.com/esphome/esphome/pull/2497. ~~If you can repeat the test, you just need to update to the latest `dev` version of ESPHome and use the  `external_components` as before.~~
Let us know if that fixes the Daikin climate component, thanks!

**Review by oxan — APPROVED** [review]

**Comment by CarlosGS** [comment]
@hcoohb Just realized it was you who fixed `delay_microseconds_accurate` :bow: https://github.com/esphome/esphome/pull/1465#issuecomment-770869894
Your detailed explanation was actually super helpful while updating the delayMicroseconds code, thanks kindly!

Please give a try to the beta version of ESPHome, it should work with the Daikin component, but let me know of any issues (don't hesitate to ping). Cheers :)

**Pull request merged**
