### PR TITLE
Adding support for Whynter ARC-14S/SH Air Conditioners

### LINKED ISSUE #1767: Add Whynter ARC-14S Support to Climate IR
**Describe the problem you have/What new integration you would like**

I would like support for the ARC-14S standalone AC system in Climate IR.  I have tried other systems, but they don't work. 

**Please describe your use case for this integration and alternatives you've tried:**

Allows for full climate automation of this unit.  It is only controllable via the remote or buttons on the unit.  I have tried SmartIR and other options in the ClimateIR help page. 

**Additional context**

I captured a bunch of IR remote commands from my remote and built a spreadsheet that captures them + derives patterns.  I noticed that all commands came back with "Received NEC" and used the addr/cmd values to build a protocol table. 
https://docs.google.com/spreadsheets/d/14SvjwZCtIWM_aNN50qefxUmNAZliV9ABrFStE_0oLfI/edit#gid=0

I have quite a bit of programming experience and happy to contribute, but a little lost on how to get started with this.

### PR DESCRIPTION
**Pull request by aeonsablaze**
# What does this implement/fix?

Adds `climate_ir` support for Whynter brand air conditioners, specifically the Whynter ARC-14S and ARC-14SH

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes https://github.com/esphome/feature-requests/issues/1767

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#2186

## Test Environment
- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:
```yaml
external_components:
  - source: github://aeonsablaze/esphome@whynter-ac-support
    components: [ whynter ]

climate:
  - platform: whynter
    name: "AC"
    sensor: room_temperature
    use_fahrenheit: true
    supports_heat: true
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by aeonsablaze** [comment]
I think this is ready, not entirely sure who needs to review it. Perhaps @glmnet since it is `climate_ir` related?

**Comment by kpelzel** [comment]
Thanks for adding this component! 

I think I found a minor bug. When I have `use_fahrenheit` set to true and set the mode to `fan_only` it will display the temperature in celsius on the AC unit.

**Comment by aeonsablaze** [comment]
Hmmm... good catch. Looks like it's doing it for dry mode as well. Pretty sure I know exactly where the issue is, I'll push a fix in the morning.

**Comment by aeonsablaze** [comment]
Yep, I had it ignoring the temperature portion of the ir transmission on Dry and Fan-only mode because they don't have a "target temperature" but obviously it still effects which unit it uses to display the ambient temperature. Should be working properly now.

**Review by aeonsablaze — COMMENTED** [review]
Reviewed. Component is tested and functional.

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
