### PR TITLE
Fix for PCF8574 input

### PR DESCRIPTION
**Pull request by amishv**
## Description:
"pcf8574_does_not_update_state#667"

**Related issue (if applicable):** fixes <link to issue>
pcf8574 dont update state on input change
https://github.com/esphome/issues/issues/667
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>
https://github.com/esphome/esphome-docs/pull/382
## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — CHANGES_REQUESTED** [review]
Please see https://github.com/esphome/esphome/pull/782#discussion_r337019922

1. There needs to be a notice in `PCF8574_OUTPUT_PIN_SCHEMA` that tells the user `INPUT_PULLUP` was removed if they have that in their config.
2. The whole `ddr_mask_` and `port_mask_` thing is unnecessary now - they're both just negated versions of each other and can be combined into a single bit field.

**Comment by amishv** [comment]
@OttoWinter ,
I am unable to find any class in config_validation.py that I can use for displaying the message, can you please guide me?
I agree that PORTx is not required as per the AVR specification only setting DDRx should be able to set the pin mode to Input or Output. However, the underlying Aurdino library requires both values to be set (**Table 20 of ATmega8 specification**). 

> 
Port Pin Configurations
Reading the Pin Value
DDxn PORTxn PUD
(in SFIOR) I/O Pull-up 0 0 X Input No Tri-state (Hi-Z)
0 1 0 Input Yes Pxn will source current if external
pulled low.
0 1 1 Input No Tri-state (Hi-Z)
1 0 X Output No Output Low (Sink)
1 1 X Output No Output High (Source)
>

**Comment by OttoWinter** [comment]
> I am unable to find any class in config_validation.py that I can use for displaying the message, can you please guide me?

I see, there's no one for that right now. This can be solved by using a custom validator:

```python
def validate_pin_mode(value):
	value = cv.string(value)
    if value.upper() == 'INPUT_PULLUP':
        raise cv.Invalid("INPUT_PULLUP mode has been removed for PCF8574. Please use INPUT mode")
    return cv.enum(PCF8674_GPIO_MODES, upper=True)

# and in the schema:
cv.Optional(CONF_MODE, default="OUTPUT"): validate_pin_mode
```

**Comment by OttoWinter** [comment]
> I agree that PORTx is not required as per the AVR specification only setting DDRx should be able to set the pin mode to Input or Output.

This is not an ATMega system, this is an xtensa system. 

Besides, the docs would only apply if you're talking about using the GPIO pins on the host itself. But here we're talking about an i2c peripheral. It was only using the ATmega naming before because that's a good way to represent GPIO modes+states.

Anyway, I guess as long as it works it's ok, but this code can/should be removed at some point.

**Comment by amishv** [comment]
Oh, Python reminds me of CoBOL way back in 1990's. using termination ';' was much better both in C and Pascal :). Just my nostalgic thoughts :)

Will try to write my syntax on an CoBOL sheet

>     if value.upper() == 'INPUT_PULLUP':
    ^
IndentationError: unexpected indent
"

need to debug the addition.

**Comment by amishv** [comment]
@OttoWinter ,
tested the configuration with,
`def validate_pin_mode(value):
    value = cv.string(value)
    if value.upper() == 'INPUT_PULLUP':
        raise cv.Invalid("INPUT_PULLUP mode has been removed for PCF8574. Please use INPUT mode")
    return cv.enum(PCF8674_GPIO_MODES, upper=True)


PCF8574_OUTPUT_PIN_SCHEMA = cv.Schema({
    cv.Required(CONF_PCF8574): cv.use_id(PCF8574Component),
    cv.Required(CONF_NUMBER): cv.int_,
    cv.Optional(CONF_MODE, default="OUTPUT"): cv.enum(PCF8674_GPIO_MODES, upper=True),
    cv.Optional(CONF_INVERTED, default=False): cv.boolean,
})
PCF8574_INPUT_PIN_SCHEMA = cv.Schema({
    cv.Required(CONF_PCF8574): cv.use_id(PCF8574Component),
    cv.Required(CONF_NUMBER): cv.int_,
    cv.Optional(CONF_MODE, default="INPUT"): validate_pin_mode,
    cv.Optional(CONF_INVERTED, default=False): cv.boolean,
})`


The validator works well,  but I now have compilation issue.

> Traceback (most recent call last):
  File "/home/amish/.local/bin/esphome", line 8, in <module>
    sys.exit(main())
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/__main__.py", line 550, in main
    return run_esphome(sys.argv)
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/__main__.py", line 537, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/__main__.py", line 276, in command_compile
    exit_code = write_cpp(config)
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/__main__.py", line 150, in write_cpp
    CORE.flush_tasks()
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/core.py", line 625, in flush_tasks
    next(task)
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/core.py", line 417, in _wrapper_generator
    var = gen.send(var)
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/__main__.py", line 132, in wrapped
    conf_str = yaml_util.dump(conf)
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/yaml_util.py", line 340, in dump
    Dumper=ESPHomeDumper)
  File "/home/amish/.local/lib/python3.6/site-packages/yaml/__init__.py", line 290, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
  File "/home/amish/.local/lib/python3.6/site-packages/yaml/__init__.py", line 278, in dump_all
    dumper.represent(data)
  File "/home/amish/.local/lib/python3.6/site-packages/yaml/representer.py", line 27, in represent
    node = self.represent_data(data)
  File "/home/amish/.local/lib/python3.6/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/yaml_util.py", line 439, in <lambda>
    lambda dumper, value: dumper.represent_mapping('tag:yaml.org,2002:map', value)
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/yaml_util.py", line 376, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/amish/.local/lib/python3.6/site-packages/yaml/representer.py", line 52, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/yaml_util.py", line 439, in <lambda>
    lambda dumper, value: dumper.represent_mapping('tag:yaml.org,2002:map', value)
  File "/home/amish/.local/lib/python3.6/site-packages/esphome/yaml_util.py", line 376, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/home/amish/.local/lib/python3.6/site-packages/yaml/representer.py", line 58, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/amish/.local/lib/python3.6/site-packages/yaml/representer.py", line 231, in represent_undefined
    raise RepresenterError("cannot represent an object", data)
yaml.representer.RepresenterError: ('cannot represent an object', <function enum.<locals>.validator at 0x7fb0615e82f0>)
>
I am not conversant with OOPS:(

**Pull request closed without merging**
