### PR TITLE
Add Current based cover

### PR DESCRIPTION
**Pull request by djwmarcx**
## Description:

The ``current_based`` cover platform allows you to create covers with position control by using current
sensors to detect the fully-open and fully-closed states. This is pretty useful when using motors with 
integrated mechanical endstops. During cover operation, the component monitors the current consumption 
to detect when the motor has stopped. 

When fully open or close is requested, the corresponding relay will stay on until the current the motor is 
consuming goes below a certain amount. The amount of current needs to be specified in the configuration.

This type of cover also provides safety features like current-based obstacle detection with automatic configurable 
rollback as well as relay malfunction detection: operation cancels if there's a current flowing in the opposite 
operation circuit (typically caused by welded relays).  

Advice: I'm currently using this integration with Shelly 2.5 and it works well, but if someone can test it on his own it will be nicer. Also, it's my first esphome component, so I'm completely open to code suggestions!

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#905

## Checklist:
  - [X] The code change is tested and works locally.
  - [X] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [X] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by nliaudat** [comment]
for information, you can do "current base cover" with endstop_cover + binary_sensor + switch


```
cover:
  - platform: endstop
    name: "CH1"
    open_action:
      - switch.turn_on: CH1_IB_pin
      - switch.turn_off: CH1_IA_pin
    open_duration: 40s #39s
    open_endstop: BEMF_1_sensor
    close_action:
      - switch.turn_on: CH1_IA_pin
      - switch.turn_off: CH1_IB_pin
    close_duration: 50s #49s
    close_endstop: BEMF_1_sensor
    stop_action:
      - switch.turn_off: CH1_IA_pin
      - switch.turn_off: CH1_IB_pin
    max_duration : 55s
    id: CH1_cover



binary_sensor:
  - platform: template
    id: BEMF_1_sensor
    name: "BEMF 1 sensor"
    lambda: return (id(BEMF_1_sensor_ADC).state >= id(bemf_trigger_1));
    on_press:
      then: 
         - lambda: |-
                if (id(CH1_cover).current_operation == COVER_OPERATION_OPENING) {
                    auto call = id(CH1_cover).make_call();
                    call.set_command_stop();
                    call.perform();
                    ESP_LOGD("main", "CH1 opening endstop reached");
                    id(CH1_cover).position  = 1; //1.0 = 100% = OPEN
                    id(CH1_cover).publish_state();
                 } else if (id(CH1_cover).current_operation == COVER_OPERATION_CLOSING) {
                    auto call = id(CH1_cover).make_call();
                    call.set_command_stop();
                    call.perform();
                    ESP_LOGD("main", "CH1 closing endstop reached");
                    id(CH1_cover).position  = 0;
                    id(CH1_cover).publish_state();
                 } 

sn74hc595:
  - id: 'sn74hc595_hub'
    data_pin: GPIO16 #Pin connected to SN74HC595 SER input
    clock_pin: GPIO5 #Pin connected to SN74HC595 SRCLK pin
    latch_pin: GPIO17 #Pin connected to SN74HC595 RCLK pin
    oe_pin: GPIO18
    sr_count: 2 #Number of daisy-chained shift registers, up-to 4

switch:
    ### CH1
  - platform: gpio
    name: "CH1 IA"
    pin:
      sn74hc595: sn74hc595_hub
      number: 0
      inverted: False
    id: CH1_IA_pin
    interlock: &interlock_group_CH1 [CH1_IA_pin, CH1_IB_pin]
    restore_mode: always off
  - platform: gpio
    name: "CH1 IB"
    pin:
      sn74hc595: sn74hc595_hub
      number: 1
      inverted: False
    id: CH1_IB_pin
    interlock: *interlock_group_CH1
    restore_mode: always off
```

**Comment by djwmarcx** [comment]
Added myself as codeowner.

**Comment by djwmarcx** [comment]
@glmnet Check if codeowners is good!

Thanks!

**Comment by djwmarcx** [comment]
After two months of using this integration in 12 blinds, I can confirm is working perfectly fine with my Shellys 2.5.

BTW, Sonoff recently released the Sonoff Dual DUALR3. It has the same hardware features. It seems to be an interesting candidate for this integration. Anyone who can try this on one of those?

@glmnet Have you any comment/suggestion for the integration? Thanks!

**Comment by oxan** [comment]
Hi, sorry this took too so long! The code looks good to me, if you could resolve the couple outstanding CI warnings, I think this can be merged!

**Comment by djwmarcx** [comment]
Thanks @oxan.
I think both code & docs are ready.

**Review by oxan — APPROVED** [review]

**Comment by oxan** [comment]
Thanks!

**Pull request merged**
