### PR TITLE
Delonghi Penguino PAC W120HP ir support

### PR DESCRIPTION
**Pull request by grob6000**
# What does this implement/fix? 

Add support for a slightly odd delonghi infrared protocol. Used the daikin module as a guide.
I've done this mostly just for myself; so I haven't got around to checking whether this is the current best practice way of adding support for a device, or documenting properly; if this has any support for inclusion, after any modifications I'm happy to fix the docs etc. then.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

https://github.com/esphome/esphome-docs/pull/1953

**Related issue or feature (if applicable):**

N/A - no issue raised

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [X] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
i2c:
  sda: 4
  scl: 5
  scan: true
  id: bus_a

sensor:
  - platform: sht3xd
    temperature:
      name: "Penguino Temperature"
      id: tempsensor
    humidity:
      name: "Penguino Humidity"
      id: humiditysensor
    update_interval: 60s

climate:
  - platform: delonghi
    name: "Penguino"
    sensor: tempsensor
    receiver_id: receiver1
    
remote_receiver:
  - id: receiver1
    pin:
      number: 14
      inverted: true
      mode: INPUT_PULLUP
    tolerance: 55%
    dump: all

remote_transmitter:
  - id: transmitter1
    pin: 15
    carrier_duty_percent: 50%
```

## Checklist:
  - [X] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — APPROVED** [review]
LGTM, thanks!

Please additionally:
1. Add a really simple entry in the `tests/` folder (it's just there to test if the codegen produces compilable output)
2. Add the docs for the delonghi component.

Thanks!

**Comment by grob6000** [comment]
* Added test with 8186041023bc576a3f26a7041eea9e32618985df
* Docs are here: https://github.com/esphome/esphome-docs/commit/13cdad4a91834a8c79c8567d3b8843d5bec9dd69

**Comment by jesserockz** [comment]
Please open a PR for the docs, just making a commit in a fork is not enough

**Comment by grob6000** [comment]
Apologies. See here:
https://github.com/esphome/esphome-docs/pull/1953

**Comment by grob6000** [comment]
Refershed the docs PR; should be GTG now.

**Pull request merged**
