### PR TITLE
Fix: midea_ac: fixed query status frame

### PR DESCRIPTION
**Pull request by dudanov**
# What does this implement/fix? 

On some models of air conditioners, the status request did not work.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by esnet146** [comment]
passed!

**Comment by esnet146** [comment]
[D][midea_dongle:029]: RX: AA 22 AC 00 00 00 00 00 03 03 C0 01 49 66 7F 7F 00 3C 00 00 00 64 FF 00 00 00 00 00 00 00 00 06 E3 B4 82 
[D][midea_ac:034]: RX: query frame
[D][midea_ac:056]: TX: query
[D][midea_dongle:094]: TX: AA 21 AC 00 00 00 00 00 00 03 41 61 00 FF 02 00 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 E3 A8 
[D][midea_dongle:029]: RX: AA 22 AC 00 00 00 00 00 03 03 C0 01 49 66 7F 7F 00 3C 00 00 00 64 FF 00 00 00 00 00 00 00 00 06 E3 B4 82 
[D][midea_ac:034]: RX: query frame
[D][midea_ac:056]: TX: query
!!!!!!!!!!!!!! 👍 -)

**Review by jesserockz — APPROVED** [review]
Just gonna have to trust you here... =)

**Comment by wouterbouvy** [comment]
Not so happy with this update, since the screen on my AC blinks
With every query. Reverted to 1.19.0

**Comment by jesserockz** [comment]
Oh man. I can't win this release... Haha

@dudanov can you sort this?

**Comment by dudanov** [comment]
> Not so happy with this update, since the screen on my AC blinks
> With every query. Reverted to 1.19.0

Join our [Telegram group](https://t.me/joinchat/BhU6LRytPXLsiqTIar0jqg) for discussion.

**Comment by javierdc** [comment]
Mine no issues with the screen although it beeps on each query (aka every second), I have the Midea U AC

**Pull request merged**
