### PR TITLE
Add support for the WT32-SC01 display to the existing ili9341 driver

### PR DESCRIPTION
**Pull request by ArthurGuy**
# What does this implement/fix?

An attempt to see if support for the larger display on the WT32-SC01 can be easily added.
The existing driver works well but the screen size is wrong.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - platform: ili9341
    model: WT32_SC01
```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by ArthurGuy** [comment]
Currently failing as it cannot allocate a buffer big enough.
> Could not allocate buffer for display!

**Comment by nielsnl68** [comment]
@ArthurGuy, Did you know i created an updated version named ili9xxx (#4275) it has a lot of updates in it.
Lets combine our work.

**Comment by nielsnl68** [comment]
BTW. Are you sure that yours has a ili9341 controller and not a ST7796S?

**Comment by ArthurGuy** [comment]
@nielsnl68 your version looks like a much better solution, I have tried to update and run that however I am getting the following error during code generation. Is it in a working state?
> ERROR ID uint8_t_6 is already registered

**Comment by nielsnl68** [comment]
> @nielsnl68 your version looks like a much better solution, I have tried to update and run that however I am getting the following error during code generation. Is it in a working state?
> 
> > ERROR ID uint8_t_6 is already registered

can you show what your yaml looks like and the rest of your error log as well. so i can try to reproduce this error?

**Comment by ArthurGuy** [comment]
@nielsnl68 I had an incorrect config item from earlier testing `color_palette: GRAYSCALE`, the presence of this triggered the error.

~Do you have any support for the larger display sizes already or should I look at that?~

The `ST7796` model works perfectly, thank you

**Comment by nielsnl68** [comment]
Yes, ili9xxx supports bigger screens, the only thing you need is an esp32 with enough psram.

**Pull request closed without merging**
