### PR TITLE
Added a function to load custom characters in LCD display

### PR DESCRIPTION
**Pull request by andrewjswan**
# What does this implement/fix?

Added a function to load custom characters in LCD display

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
display:
  - platform: lcd_gpio
...
    lambda: |-
      static uint8_t packman[8] = { // PackMan
        0b00000,
        0b01110,
        0b11011,
        0b11110,
        0b11100,
        0b11110,
        0b11111,
        0b01110
      };
      const char sign_P = 0x1;

      it.loadchar(1,packman);
      it.printf(0,0,"%c", sign_P);
```
```yaml
# Example config.yaml
display:
  - platform: lcd_pcf8574
...
    lambda: |-
      static uint8_t packman[8] = { // PackMan
        0b00000,
        0b01110,
        0b11011,
        0b11110,
        0b11100,
        0b11110,
        0b11111,
        0b01110
      };
      const char sign_P = 0x1;
      it.loadchar(1,packman);
      it.printf(15, 0, "%c", sign_P);
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by andrewjswan** [comment]
IMG_20220309_103908

**Comment by jesserockz** [comment]
Is it really necessary to retransmit the custom chars on every display update?
It would be better to allow a list of a list 8 binary bytes in yaml which can send once during setup.

```yaml
display:
  - platform: ...
    custom_chars:
      - 
        - 0b00000
        - 0b01110
        - 0b11011
        - 0b11110
        - 0b11100
        - 0b11110
        - 0b11111
        - 0b01110
      # alternate format (same schema)
      - [0b00000, 0b01110, 0b11011, 0b11110, 0b11100, 0b11110, 0b11111, 0b01110]
```

**Comment by andrewjswan** [comment]
> Is it really necessary to retransmit the custom chars on every display update? It would be better to allow a list of a list 8 binary bytes in yaml which can send once during setup.
> 
> ```yaml
> display:
>   - platform: ...
>     custom_chars:
>       - 
>         - 0b00000
>         - 0b01110
>         - 0b11011
>         - 0b11110
>         - 0b11100
>         - 0b11110
>         - 0b11111
>         - 0b01110
>       # alternate format (same schema)
>       - [0b00000, 0b01110, 0b11011, 0b11110, 0b11100, 0b11110, 0b11111, 0b01110]
> ```

The display supports only 8 custom characters, I use 20 in my project, so a one-time load will not work.  In order not to be constantly loaded, I added a variable, at the first start I load the necessary symbols

**Comment by jesserockz** [comment]
I see, that was not clear from your examples. Haha

The code you have added is fine. But if this were to become a documented feature, it should be done with YAML configuration (only allowing 8), and left to advanced users to figure it out and do it the way you are if they need more than 8.

I am just concerned because the display lambda should not do communication code.

**Comment by andrewjswan** [comment]
> I see, that was not clear from your examples. Haha
> 
> The code you have added is fine. But if this were to become a documented feature, it should be done with YAML configuration (only allowing 8), and left to advanced users to figure it out and do it the way you are if they need more than 8.
> 
> I am just concerned because the display lambda should not do communication code.

An example to test the functionality.  I added an external file that describes all custom symbols, the same can be done in lambda.  Then I load the necessary characters into 8 cells and, if necessary, change them to others, etc.

**Review by jesserockz — APPROVED** [review]
Happy for this to go in as is and undocumented as #3322 added it the YAML way and your way can be more advanced =)

**Comment by andrewjswan** [comment]
> Happy for this to go in as is and undocumented as #3322 added it the YAML way and your way can be more advanced =)

In Yaml may be more understandable to many, but there we have a limit of 8 characters, well, or have to do a complicated procedure that will analyze the currently used characters from Yaml, in case they are not loaded into the display, load them and then work with them. But this is very difficult in my opinion. 
And who got to the creation of the custom symbol, he can do as he likes. The main thing is to have a mechanism and a tool.

:)

**Pull request merged**
