### PR TITLE
Setup reg writes

### PR DESCRIPTION
**Pull request by Diramu**
## Description:
New register access for atm90e32. additional registers can be setup on startup. And an interface to read write register is opened.

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs##425

## Checklist:
  - [ ] The code change is tested and works locally.
yes
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
no

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).
yes

### CODE REVIEW

**Review by OttoWinter — CHANGES_REQUESTED** [review]
This is not how ESPHome handles more complex config options.

All config options should be configurable through human-readable YAML. If there are features missing from the atm90e32 integration right now, we can add those.

If there's a still a need for custom register writes, we can make the write16() method public, so custom lambda code can call it. But adding a YAML syntax for effectively talking directly to the sensor should be reserved to people who know what they're doing (and thus also people who can code a bit of lambda code)

**Comment by Diramu** [comment]
I agree. Theses addition were added for debug. I tried to explain that in the changes in esphome-doc, include example of lambda code to access registers.  Once actual correct programming modes are know, they should be able to simplified with specific YAML statements. 
It maybe be the case, the number of possible usage/configuration are not bound, so register access could be useful for someone who understands this device.
An example is the need to bridge some jumper on the (6-channel) board, this is can be  avoided with a registers write.  Once you know know this you will want this in your initialization setup. So until a setup command is added for the function, the write: addr/data give a using a work around.

**Comment by CircuitSetup** [comment]
@OttoWinter would it be better to allow passing values to registers in decimal form? One if the issues is there are a lot of calibration and config registers, and adding a function to handle each one would just inflate the code. Most users probably do not need all these options either, but for those that want to fine tune and customize things this is very handy.

**Comment by OttoWinter** [comment]
@CircuitSetup I understand there are a lot of registers for fine tuning the operation of the ATM90E32.

However, I think the users that want to go into those details of the sensor are usually also the ones that can write some basic lambda code. I believe something like `id(id_of_atm90e32).write_register(...)` in an on_boot is enough to write register values.

**Comment by CircuitSetup** [comment]
@OttoWinter Oh okay, I wasn't sure how that could work with the lambda code. I'll have to look into that in more detail. Is there any additional code that would need to be added to the ATM90E32 sensor for that to work correctly?

**Comment by Diramu** [comment]
@OttoWinter I disagree. I suspect the average  user is not going want to touch any lambda code. So when they find out their setup is not working, they going to ask on the forum/discord whats wrong. A common problem we see now, 2 of 3 voltages per atm90e32 are reading 0V.  The solution is take a soldering iron an short 3 together, or write a register.   Writing the register with this PR make the fix easy.  i.e.  at these line to your atm90e32 platforms
```
write:
    # set input mux to all use the same voltage, no need to bridge jumpers                                                                                                                                      
    - addr: 0x02
       data: 0x0444
```
We could change **write:** to **setup_registers:**

Aside: I've add a read section that can turn register reads into sensor:
  ```
  read:
      - register:
          name: Phase A angle
          filters:
            - multiply: 0.1
        addr: 0xF9
      - register:
          name: Phase B angle
          filters:
            - multiply: 0.1
        addr: 0xFA
      - register:
          name: Phase C angle
          filters:
            - multiply: 0.1
        addr: 0xFB
```
I'm current using this to monitor "phase angles" to see if calibration can effect these.  Generally this is just from debug, if something is a useful sensor it should be added to the schema.

@CircuitSetup If you look at the PR, I added to the esphome-doc, it shows example lambda code  I added to do my debug register writes.  Similar could be used in a lambda setup.
Instead of **setup_registers:**, we have a **setup:**, that includes **write:** and **lambda**
Then simply registers changes can be done without lambda, and lambda could be used for some build in calibration.  This lambda code  code would one deal with a single atm90e32 platform.

**Comment by CircuitSetup** [comment]
@Diramu Great work! This looks very useful for fine tuning.

@OttoWinter This seems more usable to me rather than using lambda code. The only thing that could make it more user friendly is allowing the register names (as defined in atm90e32_reg.h) to be used instead of the register addresses.

**Comment by Diramu** [comment]
I haven't had much time  this past week to dig any further. It's certainly possible to enumerated every register name in the schema.  I don't under the code architecture enough to know if this will aggravate the stack issue we have seen when we have too many sensors.  It might be best to expect anyone doing register reads and writes has read the datasheet and pull out the correct register address.   I can try putting together a version with register names, but I'm still try to correctly calibrate the system.  

Ideally, I would like if every  bus protocol spi/uart/i2c have register read/write functionality  which could be inherited by platforms that uses them.....  but that's beyond  my software skills (so far its been hack by example).

**Pull request closed without merging**
