### PR TITLE
Added support for ssd1327

### PR DESCRIPTION
**Pull request by igg**
## Description:

**Related issue (if applicable):** fixes feature request esphome/feature-requests#608

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#500

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ x] Documentation added/updated in esphome/esphome-docs#500

### CODE REVIEW

**Comment by glmnet** [comment]
This is also blocked by #988 as CS pin is not optional yet

**Comment by igg** [comment]
I reverted the CS pin commit from this branch - sorry about that.

**Comment by glmnet** [comment]
Great thanks!

I'd still love to see the optional CS pin, however when that get's merged all SPI integrations must take care of it properly, and there are a few coming (slowly)

**Comment by igg** [comment]
I updated PR #988 again today, adding support for new SPI device max31856, which was added since I rebased last, ~3 weeks ago.

All SPI devices have to use the spi_device_schema() function now instead of the old SPI_DEVICE_SCHEMA variable.
They're all fixed as of now and the tests are passing.
Let me know if I should do anything else.

**Comment by igg** [comment]
I updated PR #988 again today, adding support for new SPI device max31856, which was added since I rebased last, ~3 weeks ago.

All SPI devices have to use the spi_device_schema() function now instead of the old SPI_DEVICE_SCHEMA variable.
They're all fixed as of now and the tests are passing.
Let me know if I should do anything else.

**Pull request merged**
