### PR TITLE
bme680_bsec: use BOSCH BSEC Library 1.8.1492

### LINKED ISSUE #2110: BSEC Library update for bme680 (BSEC library version 1.6.1480 to 1.7.1492)
The Bosch proprietry library for bme680 was updated recently.
Esphome uses the old version ([1.6.1480](https://github.com/boschsensortec/BSEC-Arduino-library/releases/tag/v1.6.1480)). As this version is the first update within 3 years and fixes some bugs, I hope the accuracy of the sensor is improved.

https://www.arduinolibraries.info/libraries/bsec-software-library
https://github.com/boschsensortec/BSEC-Arduino-library/releases/tag/v1.7.1492

### PR DESCRIPTION
**Pull request by bisbastuner**
# What does this implement/fix?

Use BOSCH BSEC Library version 1.8.1492, which includes some fixes and adds support for BME688

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes [#2110](https://github.com/esphome/feature-requests/issues/2110) [#2449](https://github.com/esphome/feature-requests/issues/2449)

## Test Environment

- [x] ESP32
- [ ] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040
- [ ] BK72xx
- [ ] RTL87xx

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Test with new BME688 sensor (I don't own a BME688)
  - [ ] Test on ESP8266 (I don't own a ESP8266)
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs) stating that this component supports the BME688 sensor too (to be added after confirmation from tests).

### CODE REVIEW

**Comment by kbx81** [comment]
Have you (also) seen #4585? 😄

**Comment by bisbastuner** [comment]
Awww, it seems this won't fit in the ESP8266 RAM :( the CI test-build-components test failed

**Comment by bisbastuner** [comment]
> Have you (also) seen #4585? 😄

Yess, but I need support for BME680 to use it
Once that will be included, I'll jump on that train 😉

**Comment by kbx81** [comment]
> > Have you (also) seen #4585? 😄
> 
> Yess, but I need support for BME680 to use it Once that will be included, I'll jump on that train 😉

It supports the BME680 -- I'm using it with several of them already right now. 😉

**Comment by gretel** [comment]
works fine for me using `bme680`.

**Comment by bisbastuner** [comment]
> Awww, it seems this won't fit in the ESP8266 RAM :( the CI test-build-components test failed

The problem is that .text does not fit in .iram for ESP8266
I tried in many ways to make it fit: analyzing with PlatformIO Home, when compiled for the ESP32, shows the 2 top users for the component are `dump_config()` (~4,5 KB) and `work_buffer_` (2 KB).
Even reducing `work_buffer_` to 2 bytes, and commenting out the whole content of the `dump_config()` method, nothing improved.
So I tried commenting out nearly all the code, to no avail.

In order to not break compatibility with the ESP8266, I think it's better to leave this component alone with the older BOSCH library version, and instead continue work and progress on the new [bme68x_bsec2 component](https://esphome.io/components/sensor/bme68x_bsec2.html), which is now officially released.
It also seems that [someone made progress using that new component on a ESP8266](https://community.home-assistant.io/t/full-guide-to-read-bme680-via-bsec2-on-esp8266/778505).

**Pull request closed without merging**
