### PR TITLE
Add support for controlling fan direction

### PR DESCRIPTION
**Pull request by blejdfist**
## Description:
Add support for setting the direction of a fan (Forward or Reverse).
This is handled using a BinaryOutput in the same way as oscillation.

**Related issue (if applicable):**

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#580

AIOESPHome https://github.com/esphome/aioesphomeapi/pull/8
Hass Core https://github.com/home-assistant/core/pull/36077

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by glmnet** [comment]
Does this one also requries a change here? https://github.com/home-assistant/core/blob/dev/homeassistant/components/esphome/fan.py

**Comment by blejdfist** [comment]
> Does this one also requries a change here? https://github.com/home-assistant/core/blob/dev/homeassistant/components/esphome/fan.py

Yes, and I have a patch ready for it in my fork. 
We also need https://github.com/esphome/aioesphomeapi/pull/8

This PR can be merged without those though and is forward compatible. I will create a PR to homeassistant core when this is merged.

**Comment by blejdfist** [comment]
@glmnet I have a WIP pull request with HASS that shows the updates necessary

https://github.com/home-assistant/core/pull/36077

**Comment by glmnet** [comment]
Great. I don’t know if I said this already but what we want is to have that merged before we update dev so no compatibility checks are needed

**Comment by blejdfist** [comment]
@glmnet The HASS changes will require a new version of aioesphomeapi first.

**Comment by blejdfist** [comment]
@glmnet I have tested compatibility with this patch and the current version of aioesphome (2.6.1)+HASS and it works but won't give you access to the direction controls in HASS.

**Review by glmnet — APPROVED** [review]
LGTM

**Comment by glmnet** [comment]
Now I feel tempted to bump version in aio to see what happens...

Anyway this can be used now if copying the PR esphome component of hass into the custom_components, for those who don't know.

Thanks!!

**Pull request merged**
