### PR TITLE
Added state property to ota component

### PR DESCRIPTION
**Pull request by a13ssandr0**
# What does this implement/fix? 

Added `float state` variable to ota component.
Exposed for components that fetch update progress outside ota triggers (see code below).

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml
ota:
  id: ota_comp
  on_begin:
    then:
      - display.page.show: update_page
      - component.update: my_lcd
  on_progress:
    then:
      - component.update: my_lcd
  on_end:
    then:
      - display.page.show: update_end_page
      - component.update: my_lcd

display:
  - platform: ...
    id: my_lcd
    # ...
    pages:
      - id: main_page
        lambda: |-
          //...
      - id: update_page
        lambda: |-
          it.fill(Color::BLACK);
          it.printf(0, 15, id(my_font), "Updating: %0.1f%%", id(ota_comp).state);
      - id: update_end_page
        lambda: |-
          it.fill(Color::BLACK);
          it.print(0, 15, id(my_font), "Update finished. Rebooting...");

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by jesserockz — APPROVED** [review]
I was going to comment about it actually being 100, or resetting to 0 and then had a :man_facepalming: moment and realised the board restarts. 

Might be good to reset to 0 after an error though

**Comment by a13ssandr0** [comment]
I made some tests and it reached 100% only once, usually it reaches 93% or 98% and triggers `on_end` (even the logger without the display behaves the same).
I was able to test the behaviour when the upload process is cancelled midway through (Ctrl+c on the terminal): the process stops but the board doesn't reset, leaving the display on, for example, `Updating... 18.6%`; I'll do more tests and soon make another pull request exposing the error codes.

**Comment by jesserockz** [comment]
I'm not sure about exposing the error codes as members as that could get messy. But at least resetting the `state` perhaps even initialising it as `-1` instead of `0.0` and then setting back to `-1` when the update is cancelled/failed/errored.

Yeah chances of seeing 100% fast enough are slim because of the nature of the update process.

**Comment by mmakaay** [comment]
For representing flash progress, I use the on_begin, on_progress, on_end and on_error triggers that I implemented in `ota`.
I see you are not using the on_error trigger. The error code is already exposed from the on_error trigger using the variable `x`. Any reason why that one isn't usable for your use case?

**Comment by a13ssandr0** [comment]
> I'm not sure about exposing the error codes as members as that could get messy. But at least resetting the `state` perhaps even initialising it as `-1` instead of `0.0` and then setting back to `-1` when the update is cancelled/failed/errored.
> 
> Yeah chances of seeing 100% fast enough are slim because of the nature of the update process.

Error codes are exposed anyways in the `on_error` as @mmakaay just suggested, but they are only visible there and is difficult to make them available in other lambdas such as display pages (see example code in the first message)

@jesserockz regarding setting the state to -1, I think it would be better initializing state with 0.0 (that correctly represents the update just starting from 0%) and then, eventually, setting it to -1 only on error (even though we have `on_error` for that, so we can leave the progress indicator where it stopped and display the error)

**Comment by mmakaay** [comment]
When I would need the actual error code in a different place, then I would introduce a global variable to store it from `on_error` and clear it from `on_begin`. For easy displaying logic, you could even introduce one or more booleans to represent the state as you need it for your flavor of displaying the flashing progress. That seems better to me than depending on magic values that introduce extra semantics for a single value.

**Comment by a13ssandr0** [comment]
@mmakaay I tried using global variables, they're working fine, so I think the request isn't useful anymore.

**Comment by sermayoral** [comment]
@a13ssandr0 could you write an example of esphome code doing that using global variables? Thanks

**Comment by a13ssandr0** [comment]
> @a13ssandr0 could you write an example of esphome code doing that using global variables? Thanks

Of course, here's my code. As you can see I'm using error codes integer values, instead of a text description, but it's working.

```yaml
# Example config.yaml
ota:
  on_begin:
    then:
      - display.page.show: update_page
      - component.update: lcd
  on_progress:
    then:
      - component.update: lcd
      - lambda: id(update_percentage)=x;
  on_end:
    then:
      - display.page.show: update_end_page
      - component.update: lcd
  on_error:
    then:
      - component.update: lcd
      - lambda: id(update_error_code)=x;

globals:
  - id: update_percentage
    type: float
  - id: update_error_code
    type: int

font:
  - file: "fonts/Roboto-Regular.ttf"
    id: roboto_regular_update
    size: 15
    glyphs: 0123456789RUabdefghinopst .:%

color:
  - id: red
    red: 100%
    green: 0%
    blue: 0%
    white: 0%
  - id: green
    red: 0%
    green: 100%
    blue: 0%
    white: 0%

display:
  - platform: ...
    id: lcd
    # ...
    pages:
      - id: main_page
        lambda: |-
          //...
      - id: update_page
        lambda: |-
          it.fill(Color::BLACK);
          it.printf(it.get_width() / 2, it.get_height() / 2, id(roboto_regular_update), TextAlign::BOTTOM_CENTER, "Updating: %0.1f%%", id(update_percentage));
          it.filled_rectangle(0, it.get_height() / 2 + 10, it.get_width()*(id(update_percentage)/100), 10, (id(update_error_code)!=0)?id(red):id(green));
          if(id(update_error_code)!=0){
            it.printf(it.get_width() / 2 + 30, it.get_height() / 2, id(roboto_regular_update), TextAlign::TOP_CENTER, "Error %d", id(update_error_code));
          }
      - id: update_end_page
        lambda: |-
          it.fill(Color::BLACK);
          it.print(it.get_width() / 2, it.get_height() / 2, id(roboto_regular_update), TextAlign::BOTTOM_CENTER, "Update finished. Rebooting...");



```

**Comment by mmakaay** [comment]
Happy to see that the suggestion worked, @a13ssandr0 
Good job 👍

**Pull request closed without merging**
