### PR TITLE
refactored xiaomi sensors

### PR DESCRIPTION
**Pull request by Alex9779**
## Description:
Because of the collision of #734 and #746 I refactored all the xiaomi sensors to their model names.
IMHO this is the better than mixing up series/platform names with single device names.

**Related issue (if applicable):** fixes none

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#361

## Checklist:
  - [x] The code change is tested and works locally.
  - [x] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [x] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by OttoWinter — COMMENTED** [review]
I guess it's ok to refactor them, yeah the initial naming was not ideal - most users use the pictures on the front page as the main navigation anyway so discoverability won't be an issue with the more complicated model names.

However, this will need migrations in place to mitigate the impact of this breaking change. Please look at `esp32_ble_tracker/binary_sensor.py` (`remote_transmitter/switch.py` is a second example) to see how to notify the user of how the breaking change.

**Comment by Alex9779** [comment]
Yeah cool will do so and update the PR accordingly...

**Review by OttoWinter — APPROVED** [review]
Thanks!

**Comment by OttoWinter** [comment]
Hi @Alex9779, I'm correctly working on getting https://github.com/esphome/esphome/pull/691 mergable, and am wondering: How did you find the model numbers of the devices? On the xiaomi website I can't find anything about the particular weight scale.

**Comment by Alex9779** [comment]
Long search on various chinese shop sites, sole list specs where the models are listed...

**Comment by Alex9779** [comment]
Btw the LYWSDCGQ actually has a slash and more letters and numbers behind but slashes are not so nice in code nor in file and directory names ;)

**Pull request merged**
