### PR TITLE
Modbus number/output use write single

### PR DESCRIPTION
**Pull request by glmnet**
# What does this implement/fix? 

So this change might seem cosmetic, I need to do this so my pzemac v3 module would accept the sample yaml to change the device address.
Otherwise it rejects it as the device modbus implmentation doesn't like the write multiple command.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#1713

## Test Environment

- [ ] ESP32
- [ ] ESP32 IDF
- [x] ESP8266

## Example entry for `config.yaml`:

```yaml
modbus_controller:
  address: 248 # broadcast address, you can communicate with any connected device regardless of it adress

number:
  - platform: modbus_controller
    id: pzem_addr
    name: "pzem_addr"
    address: 0x2 # this is the address registry number, and it is not related to device address, do not change
    value_type: U_WORD


# Device address is passed in with an api service, or on_boot script, etc.
```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Review by martgras — APPROVED** [review]
Yes good change to improve combability

**Review by martgras — COMMENTED** [review]
I may make sense to add an override option similar to 

https://github.com/esphome/esphome/blob/6df1d5222d23e0af7bce2d30c248046717e8c043/esphome/components/modbus_controller/switch/__init__.py#L40
and 
https://github.com/esphome/esphome/blob/6df1d5222d23e0af7bce2d30c248046717e8c043/esphome/components/modbus_controller/switch/modbus_switch.cpp#L75
I added this option because there was a device only supporting write_multiple_coils. There may be devices that only support write_multiple for holding registers as well (unlikely but I already saw a lot of odd modbus implementation)

Update:
Tried to add the changes to your PR but I seem to lack permissions or don't know how to do it properly in github :)
Added option to still force write_multiple here: 
https://github.com/martgras/esphome/tree/modbus-number-use-write-single
https://github.com/martgras/esphome/commit/6f4f132490607eeb1dea6fe8bea73dc28e65165f

**Comment by glmnet** [comment]
Ahh yes, this could have been a breaking change. Now it will require a configuration update if it fails for someone. That's way better. 
We need docs for this now. Would you please add a PR for that?

**Comment by martgras** [comment]
Done https://github.com/esphome/esphome-docs/pull/1713

**Comment by martgras** [comment]
On a second thought `output` uses the same code.  I just pushed the change for it to my branch. 
Would make sense to add it to the PR

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
