### PR TITLE
Reserve vector memory for core components before usage.

### PR DESCRIPTION
**Pull request by Fabian-Schmidt**
# What does this implement/fix?

Reserve memory for all vectors in core components (application & scheduler) before first usage. This avoids vector resize and lowers memory fragmentation.

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [x] ESP32
- [x] ESP32 IDF
- [ ] ESP8266
- [ ] RP2040

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [x] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by oxan** [comment]
I don't mind the idea of reserving memory for the vectors in advance, but passing the expected size as a gazillion parameters is quite ugly imo. Additionally, doing it in `pre_setup()` causes the memory to be reserved prior to the OTA safe mode check, which makes it unrecoverable if too much memory is reserved here (okay, it's just for a bunch of pointers, so it's quite unlikely we'll run out of memory here... but still, we should do as little as possible prior to the safe mode check).

How about adding `reserve_binary_sensors_space(size_t space)` methods (or something like that; I'm not sold on the name), and inserting calls to them after the OTA safe mode check?

**Comment by Fabian-Schmidt** [comment]
> I don't mind the idea of reserving memory for the vectors in advance, but passing the expected size as a gazillion parameters is quite ugly imo. Additionally, doing it in `pre_setup()` causes the memory to be reserved prior to the OTA safe mode check, which makes it unrecoverable if too much memory is reserved here (okay, it's just for a bunch of pointers, so it's quite unlikely we'll run out of memory here... but still, we should do as little as possible prior to the safe mode check).
> 
> How about adding `reserve_binary_sensors_space(size_t space)` methods (or something like that; I'm not sold on the name), and inserting calls to them after the OTA safe mode check?

I agree it is ugly to have this many parameter.
To keep it all within the one `to_code` method of the core I cannot see how to easily move a method call to an after ota point in time.

**Comment by oxan** [comment]
Having two `to_code` coroutines with different priorities is fine with me.

**Comment by Fabian-Schmidt** [comment]
> Having two `to_code` coroutines with different priorities is fine with me.

How is this possible? Each component can only have one `to_code` method.

**Comment by oxan** [comment]
> How is this possible? Each component can only have one `to_code` method.

You can add another job with a different priority to the core in `to_code`, similar to what's done with `_add_automations`.

**Comment by oxan** [comment]
Though I've submitted #4529 which should do allow that in a nicer way.

**Pull request closed without merging**
