### PR TITLE
Bump dashboard to 20210615.0

### PR DESCRIPTION
**Pull request by balloob**
# What does this implement/fix? 

https://github.com/esphome/dashboard/releases/tag/20210615.0

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

**Related issue or feature (if applicable):** fixes <link to issue>

**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Test Environment

- [ ] ESP32
- [ ] ESP8266

## Example entry for `config.yaml`:

```yaml
# Example config.yaml

```

## Checklist:
  - [ ] The code change is tested and works locally.
  - [ ] Tests have been added to verify that the new code works (under `tests/` folder).
  
If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by markusg1234** [comment]
Hi,
How do we open the dashboard via HTTPS to use the install via the browser option. 
Currently it just takes you to https://esphome.io/guides/getting_started_hassio.html#webserial

**Comment by jesserockz** [comment]
> How do we open the dashboard via HTTPS to use the install via the browser option

Options:
1. Use Home Assistant Cloud to open the dashboard via ingress
2. Set up the addon with the `advanced` options that enable ssl.
3. Set up one of the reverse proxy addons to do SSL termination and forward traffic to your ESPHome dashboard.


There are other options too but the simplest and easiest is number 1. Even easier if you already subscribe.

**Comment by markusg1234** [comment]
I have it now working with option 1.
Couldn't get it to work with option 2 but might try again another day.

Regards,
Markus

**Comment by balloob** [comment]
@jesserockz wonder if we should add this to the guide too?

@markusg1234 just FYI, this is a constraint set by browsers to make sure that the data we flash to your devices is delivered over a secure connection. It makes sense but it's annoying because getting HTTPS for local servers is not straightforward.

**Pull request merged**
